"""One-time replacement of prototype UI copy; all shipped UI is English."""
from pathlib import Path
f=Path(__file__).parent/'site/app.js'
replacements={
'Data katalogu se nepodařilo načíst.':'The catalogue data could not be loaded.',
"toLocaleString('cs-CZ')":"toLocaleString('en-US')",
"localeCompare(b.title_cs||b.title,'cs')":"localeCompare(b.title_cs||b.title,'en')",
'Doložena jako otevřená':'Documented as open',
'Otevřená podle zdroje':'Open in the dated source',
'Aktuální stav neověřen':'Current status unverified',
'Vyřešená / změněná':'Resolved / materially changed',
'Podrobná karta':'Detailed card',
'Zdrojová karta':'Source note',
'Původní index':'Legacy index',
'Formulace autorů v původním znění':'Original source wording',
'Novější související literatura':'Later related literature',
'Tematicky související práce; samy o sobě nepotvrzují vyřešení této otázky.':'Related papers; these references do not by themselves establish progress or resolution.',
'NOVÉ':'NEW',
'Odebrat uložený problém':'Unsave problem',
'Uložit problém':'Save problem',
'Uloženo':'Saved',
'Uložit +':'Save +',
'Bez data':'Undated',
'Zadání v dosavadním indexu':'Legacy statement',
'Formulace problému':'Problem statement',
'Kontext':'Context',
'Proč je problém důležitý':'Why it matters',
'Známé výsledky, matematický kontext a citace':'Progress, definitions & references',
'Model a značení':'Model & notation',
'Doložený pokrok':'Documented progress',
'Časová osa zatím nebyla dopracována.':'An individual progress review has not yet been completed.',
'Moje poznámka':'My note',
'Vlastní nápad, poznámka ke zdroji…':'An idea, a question, a note on the source…',
'Odkaz na kartu ↗':'Link to card ↗',
'Kopírovat zadání':'Copy statement',
'Původní zdroj ↗':'Primary source ↗',
'problémů ve výběru':'matching records',
'Tato karta v katalogu není.':'This card is not in the catalogue.',
'Celkem záznamů':'Total records',
'Nově přidané':'New additions',
'Tematických oblastí':'Research areas',
'Podrobné karty':'Detailed cards',
'Prohlížeč neumožnil trvalé uložení.':'Your browser could not save this change permanently.',
'Odkaz na kartu je v adresním řádku.':'The address bar now contains a direct link to this card.',
'Zadání a citace zkopírovány.':'Statement and references copied.',
'Kopírování není dostupné; použij export výběru.':'Copying is unavailable. Use Export selection instead.',
'tcs-atlas-vyber.json':'tcs-atlas-selection.json',
}
s=f.read_text()
for a,b in replacements.items():s=s.replace(a,b)
f.write_text(s)
