"""Editorial area descriptions and transparent screening criteria, not paper summaries."""
AREAS={
'Algebraic and numerical computation':('Algebraické výpočty','Počítání s polynomy, maticemi a tenzory. Základní otázky srovnávají aritmetické modely, konstrukce identitních testů a dolní meze.'),
'Algorithmic game theory and fair division':('Teorie her a spravedlivé dělení','Algoritmy při strategickém chování a rozdělování omezených zdrojů. Existence řešení, incentivy, spravedlnost a výpočetní proveditelnost jsou různé požadavky.'),
'Algorithms for biological structures':('Algoritmy pro biologické struktury','Diskrétní modely sekvencí, evolučních stromů a samoskládání. Fundamentální je vliv struktury vstupu na rekonstruovatelnost a výpočetní složitost.'),
'Approximation algorithms':('Aproximační algoritmy','Jak blízko optimu lze dojít v omezeném čase. Parametry garance, typ instance a předpoklad těžkosti určují přesnou hranici problému.'),
'Automata and formal languages':('Automaty a formální jazyky','Konečné popisy jazyků a transformací. Zkoumá se vyjadřovací síla, rozhodnutelnost a velikost převodů mezi reprezentacemi.'),
'Automated reasoning and unification':('Automatické dokazování a unifikace','Algoritmické rozhodování logických omezení a hledání substitucí. Volba logiky a termového modelu může měnit složitost i rozhodnutelnost.'),
'Average-case complexity':('Složitost v průměrném případě','Těžkost vůči konkrétní distribuci vstupů. Důležité je přesně vymezit vzorkování, pravděpodobnost úspěchu a sílu algoritmu.'),
'Coding and information theory':('Kódování a teorie informace','Přenos a obnova informace při šumu a omezeném přístupu. Existence kódu, jeho explicitnost a efektivní dekódování nejsou zaměnitelné.'),
'Combinatorics and graph polynomials':('Kombinatorika a grafové polynomy','Strukturální a extremální vlastnosti diskrétních objektů. Tyto vlastnosti často určují hranice algoritmů i explicitních konstrukcí.'),
'Communication complexity':('Komunikační složitost','Kolik informace musí účastníci vyměnit při rozděleném vstupu. Rozhoduje přístup k náhodě, provázání, počet kol a požadovaná chyba.'),
'Computability and algorithmic information':('Vyčíslitelnost a algoritmická informace','Hranice algoritmického řešení a složitost popisu. Orákula, uniformita a typ reprezentace mohou podstatně měnit tvrzení.'),
'Computational and circuit complexity':('Výpočetní a obvodová složitost','Síla modelů výpočtu a potřebné zdroje. Dolní mez musí platit proti celé definované třídě algoritmů či obvodů.'),
'Computational geometry':('Výpočetní geometrie','Algoritmické a strukturální otázky pro geometrické objekty. Dimenze, degenerace a model reprezentace vstupu jsou součástí zadání.'),
'Computational topology':('Výpočetní topologie','Výpočet invariantů a rozhodování topologických vlastností. Zásadní jsou dimenze a konečný způsob popisu prostoru.'),
'Constraint satisfaction':('Splnitelnost omezení','Systémy lokálních relací. Klasifikace přípustných šablon a aproximací odhaluje hranice mezi efektivním řešením a těžkostí.'),
'Cryptography':('Kryptografie','Možnost bezpečných primitiv a protokolů. Přesný protivník, bezpečnostní definice a předpoklad těžkosti jsou nedílnou částí otázky.'),
'Data structures and compressed data':('Datové struktury a komprese','Reprezentace dat s rychlými dotazy a aktualizacemi. Porovnávají se náklady paměti, předzpracování a jednotlivých operací.'),
'Database theory and finite model theory':('Databázová teorie a konečné modely','Logické dotazy nad konečnými strukturami. Vyjadřovací síla jazyka a způsob vyhodnocení určují algoritmické možnosti.'),
'Differential privacy':('Diferenciální soukromí','Algoritmy, jejichž výstup omezeně závisí na jednom záznamu. Typ soukromí, sousednost databází a měřítko chyby musí být specifikovány současně.'),
'Distributed and local algorithms':('Distribuované a lokální algoritmy','Výpočty s omezeným lokálním pohledem a komunikací. Záleží na synchronizaci, identifikátorech, zprávách a adversárním modelu.'),
'Dynamic graph algorithms':('Dynamické grafové algoritmy','Udržování grafových vlastností při změnách vstupu. Typ aktualizací a worst-case versus amortizovaná garance jsou klíčové.'),
'Enumeration and counting':('Enumerace, počítání a vzorkování','Výpočet počtu řešení nebo jejich generování. Přesnost, zpoždění a typ distribuce oddělují různé výpočetní úlohy.'),
'Existential theory of the reals':('Existenciální teorie reálných čísel','Rozhodování existence reálného řešení soustav polynomiálních podmínek a jeho vazby na geometrické realizace.'),
'Fine-grained complexity':('Jemnozrnná složitost','Konkrétní exponenty času a podmíněné redukce. Cíl musí uvádět parametry vstupu a přesný hypotetický základ dolní meze.'),
'Games, synthesis and verification':('Hry, syntéza a verifikace','Rozhodování správnosti a konstrukce strategií v přechodových systémech. Typ cíle a dostupná informace mohou změnit složitost.'),
'General algorithm design':('Obecný návrh algoritmů','Obecné výpočetní úlohy a principy návrhu. Základem je přesné rozlišení přípustných vstupů, požadovaného výstupu a nákladů.'),
'Graph theory and graph algorithms':('Grafová teorie a algoritmy','Struktura grafů a její algoritmické využití. Restrikce grafové třídy může otevřít možnost algoritmu nebo vymezit ostrou překážku.'),
'Infinite-state systems and verification':('Nekonečné stavové systémy','Konečně popsané systémy s nekonečně mnoha konfiguracemi. Hledají se hranice rozhodnutelnosti dosažitelnosti a dalších vlastností.'),
'Information-based complexity and numerical algorithms':('Informační složitost a numerika','Kolik hodnot či jiné informace je třeba k numerickému přiblížení. Přístup k funkci, dimenze a požadovaná přesnost určují model.'),
'Lattices and computational number theory':('Mřížky a výpočetní teorie čísel','Diskrétní geometrie a aritmetické úlohy. Aproximační faktor, dimenze a reprezentace čísel ovlivňují složitost i kryptografický význam.'),
'Learning theory':('Teorie učení','Kolik dat a výpočtu je potřeba k předpovídání. Typ třídy hypotéz, šum, distribuce a garance chyby určují přesné zadání.'),
'Online algorithms, bandits and stochastic optimization':('Online algoritmy, bandité a stochastická optimalizace','Rozhodování před znalostí budoucnosti. Regret a kompetitivní poměr srovnávají algoritmus s přesně definovaným benchmarkem.'),
'Optimization and mathematical programming':('Optimalizace a matematické programování','Efektivní hledání optimálních či přibližných řešení. Geometrie přípustné množiny a druh orákula určují, co lze garantovat.'),
'Parameterized and exact algorithms':('Parametrizované a přesné algoritmy','Jak závisí přesný výpočet na strukturálním parametru nebo velikosti vstupu. Algoritmické meze je třeba porovnávat ve stejném parametrickém režimu.'),
'Proof complexity and logic':('Důkazová složitost a logika','Délka a síla formálních důkazů. Rozlišují se existence krátkého důkazu, jeho nalezení a efektivita ověřování.'),
'Property testing and distribution learning':('Testování vlastností a distribucí','Rozhodování nebo odhad z omezeného počtu dotazů a vzorků. Vzdálenost od vlastnosti a povolený typ dotazu jsou součástí problému.'),
'Pseudorandomness and derandomization':('Pseudonáhodnost a derandomizace','Kdy lze náhodu nahradit explicitní strukturou. Síla testu, délka seedu a požadovaná chyba vymezují cíl konstrukce.'),
'Quantum computation':('Kvantové počítání','Síla kvantové informace a výpočtů. Počet qubitů, typ měření, přístup k orákulu a chyba musí být odlišeny.'),
'Randomized search and optimization':('Randomizované hledání a optimalizace','Výkon náhodných vyhledávacích procesů. Fundamentální jsou garance času a kvality vůči přesně dané třídě vstupů.'),
'Rewriting, lambda calculus and semantics':('Přepisování, lambda kalkul a sémantika','Formální modely programů a výpočtových pravidel. Normalizace, ekvivalence a vyjadřovací síla objasňují jejich základní možnosti.'),
'Scheduling and packing':('Rozvrhování a balení','Přidělování omezených kapacit. Druh omezení a optimalizační kritérium určují ostré aproximační i časové hranice.'),
'Streaming and sketching':('Streamování a skicování','Výpočet při omezené paměti nebo z komprimované skici. Důležité jsou počty průchodů, adaptivita a typ aktualizací.'),
'Temporal graph algorithms':('Časové grafy','Grafy s časově dostupnými hranami. Pořadí událostí mění dosažitelnost a ruší řadu vlastností statických grafů.')}

CRITERIA={
'models':dict(label='Síla výpočetních modelů',pattern=r'separat|equivalen|hierarch|more power|versus|\bvs\b|\bQMA\b|\bBQP\b|\bBPP\b',why='Otázka porovnává sílu dvou modelů nebo reprezentací. Výsledek by určil, zda jejich rozdíl mění samotnou výpočetní možnost; to je strukturální důvod pro zařazení.'),
'resources':dict(label='Nezbytné výpočetní zdroje',pattern=r'communication|space|memory|qubits?|samples?|queries|query complexity|rounds?|probes?|regret',why='Otázka se týká ceny omezeného výpočetního či informačního zdroje. Ostrá mez by rozlišila nedostatek současného algoritmu od omezení, které musí respektovat každý algoritmus v daném modelu.'),
'assumptions':dict(label='Minimální předpoklady',pattern=r'assumption|unconditional|weaker|without|remove.*restrict|standard model',why='Otázka zkoumá nutnost předpokladu nebo restrikce. Její odstranění, případně důkaz nezbytnosti, by ukázalo skutečný rozsah tvrzení či konstrukce.'),
'characterization':dict(label='Strukturální charakterizace',pattern=r'characteriz|characteris|dichotomy|classif|necessary.*sufficient|which|exact complexity',why='Cílem je charakterizace celé třídy případů. Takový výsledek může vysvětlit společnou příčinu algoritmické snadnosti či těžkosti místo dalšího izolovaného příkladu.'),
'reductions':dict(label='Vazba mezi problémy',pattern=r'reduc|impli|relation between|connection between',why='Otázka hledá redukci nebo logickou vazbu mezi úlohami. Vazba by umožnila přenášet algoritmy nebo překážky a objasnila, zda dva problémy sdílejí stejný zdroj těžkosti.'),
'construction':dict(label='Existence a explicitnost',pattern=r'explicit|construct|deterministic|derandom|exist|\bcode|\bextractor|\bgenerator',why='Otázka žádá existenci objektu nebo efektivní konstrukci. Rozdíl mezi existenčním argumentem a explicitním algoritmem bývá základní překážkou použití dané struktury.'),
'tightness':dict(label='Ostrá mez nebo práh',pattern=r'optimal|tight|lower bound|upper bound|threshold|constant.factor|approximation|asymptotic|exponent|gap',why='Otázka žádá ostrou hranici či uzavření konkrétní mezery. Taková mez určuje, co lze při dané garanci skutečně dosáhnout, a poskytuje cíl i benchmark pro další metody.'),
'decision':dict(label='Hranice algoritmického řešení',pattern=r'decidab|complexity|polynomial|NP.hard|FPT|algorithm|computab',why='Otázka míří na možnost algoritmického řešení v daném modelu. Její význam spočívá ve vymezení hranice mezi dostupným postupem a výpočetní či logickou překážkou.')}
