"""Reviewable import payload; canonical IDs are allocated by import_cards.py."""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent
ROOT = BASE.parent.parent
DATE = '2026-09-11'
CATEGORIES = {c['id']: c['key'] for g in json.loads((ROOT/'data/categories.json').read_text())['groups'] for c in g['categories']}
ROWS = [line.split('\t') for line in (BASE/'plan.tsv').read_text().splitlines()]
CARDS = []

def add(slug, title, category, formal, definitions, context, why, score, reference, authors, year, url, locator, progress, *, criterion='decision', issue=None, note='', kind='yes_no', related=()):
    card = dict(key='personal-101-300-20260911-'+slug, title=title, area=CATEGORIES[category],
        criterion=criterion, question_type=kind, formal=formal, definitions=definitions,
        context_blocks=[dict(text=p,citation='primary') for p in context.split('\n\n')], why=why,
        answer_criterion=('Determine the stated minimax quantity up to universal multiplicative constants, including all logarithmic factors, with matching upper and lower bounds.' if kind=='asymptotic_complexity' else 'Prove the stated proposition or its logical negation, preserving the quantifiers, model and guarantees. Conditional results settle only their conditional claims.')+' Benchmark acceptance requires a complete proof-assistant-checked proof of the full target.',
        references=[dict(id='primary',title=reference,authors=authors,year=year,url=url,locator=locator)],
        progress=[dict(date=str(year),text=progress,citation='primary')], related=list(related), year=year,
        evidence='source' if issue else 'reviewed', status='source_open',
        status_note='Open target supported by the dated sources. Literature was checked on 11 September 2026, with the limits recorded here; this is not an exhaustive certification of current openness. '+note,
        model_self_contained=not bool(issue), requires_context=bool(issue),
        statement_review=dict(status='needs_specification' if issue else 'revised',reviewed_on=DATE,remaining_issue=issue or '',reason='Individual source, importance and duplicate review.'),
        formulation_reviewed_on=DATE,review_note=note,
        importance=dict(score=score,method='editorial',assessed_on=DATE,reason=why),
        personal_import=dict(batch='personal-101-300-20260911',candidate='new-'+slug,researchers=[dict(number=int(r[0]),name=r[1]) for r in ROWS if 'new-'+slug in r[2:4]],affinity_status='Editorial inference from the supplied research profiles, not an attributed personal priority.'),
        category_assignment=dict(method='editorial_topic',reason='The main mathematical target determines the category; no quota was used to justify admission.'))
    CARDS.append(card)
    return card

def cite(card, id, title, authors, year, url, locator, progress):
    card['references'].append(dict(id=id,title=title,authors=authors,year=year,url=url,locator=locator))
    card['progress'].append(dict(date=str(year),text=progress,citation=id))

c=add('komlos','Komlós conjecture: dimension-free vector balancing','optimization',
    'Does there exist a universal real constant C>0 such that, for all integers m,n≥1 and every real matrix A∈ℝ^{m×n} with ∑_{i=1}^m A_{ij}²≤1 for each column j, there is a vector x∈{−1,1}^n satisfying max_{1≤i≤m}|∑_{j=1}^n A_{ij}x_j|≤C?',
    'All matrices are finite. Columns may have arbitrary real entries, including negative entries. The sign vector may depend on the entire matrix; C may not depend on the dimensions or entries. This is an existence question, with no algorithmic or input-encoding requirement.',
    'Discrepancy measures how accurately a fractional choice can be replaced by signs while controlling many linear constraints simultaneously. Komlós asks whether normalizing every column in Euclidean norm suffices to bound every coordinate of the signed sum by an absolute constant.\n\nThe 2025 improvement gives a polylogarithmic bound smaller than the classical square-root-logarithmic bound, but does not reach a constant. Komlós implies the Beck–Fiala conjecture after scaling an incidence matrix; the converse is not known. Both are retained as established landmarks with different hypotheses, rather than as unrelated questions.',
    'A defining vector-balancing conjecture with consequences for rounding, approximation and the geometry of linear constraints.',97,
    'Decoupling via Affine Spectral-Independence: Beck-Fiala and Komlós Bounds Beyond Banaszczyk','Nikhil Bansal; Haotian Jiang',2025,'https://arxiv.org/abs/2508.03961','Introduction and main Komlós bound.',
    'The authors improve the general Komlós upper bound to roughly a fourth power of log n, with additional logarithmic factors; a universal constant is not obtained.',criterion='resources',note='The companion Beck–Fiala target is a documented consequence, not a duplicate. No algorithmic construction requirement is added.')

c=add('beck-fiala','Beck–Fiala conjecture: square-root discrepancy in set systems','optimization',
    'Is there a universal C>0 such that, for all integers m,n,t≥1 and every A∈{0,1}^{m×n} having at most t ones in each column, some x∈{−1,1}^n satisfies max_i |∑_j A_{ij}x_j|≤C√t?',
    'The matrix is the incidence matrix of a finite set system: its columns are elements and its rows are sets. Thus each element belongs to at most t sets. Empty sets and unused elements are allowed. The bound is independent of the number of elements and sets. The question asks for existence of a signing, without an algorithmic time requirement.',
    'Bounded element frequency is a basic sparsity assumption in rounding problems. The conjecture asks whether its discrepancy cost is proportional to the square root of the frequency even when the system is arbitrarily large.\n\nRecent results prove this scale for substantial ranges of t relative to the size of the system. The full statement includes all frequencies and remains stronger than those range-restricted results. The separate Komlós conjecture implies this statement by rescaling each incidence column.',
    'A central discrepancy conjecture governing how local incidence restrictions control global rounding error.',95,
    'Decoupling via Affine Spectral-Independence: Beck-Fiala and Komlós Bounds Beyond Banaszczyk','Nikhil Bansal; Haotian Jiang',2025,'https://arxiv.org/abs/2508.03961','Introduction and Beck–Fiala parameter ranges.',
    'The square-root bound is established in the paper for a high-frequency range, not uniformly for every t.',criterion='resources',note='TCS-5224 concerned a particular route to a known range of Beck–Fiala, not the full conjecture admitted here.')
cite(c,'later','Online Beck--Fiala Down to Logarithmic Sparsity','Dylan J. Altschuler; Konstantin Tikhomirov',2026,'https://arxiv.org/abs/2607.14238','Abstract and sparsity assumptions.','A July 2026 preprint further extends the covered sparsity range. Its lower threshold still leaves the unrestricted conjecture open.')

c=add('matroid-secretary','A constant-competitive algorithm for the general matroid secretary problem','online',
    'Does there exist a universal constant C≥1 such that every finite matroid M admits a randomized online selection strategy which, for every assignment of nonnegative weights to its elements, returns an independent set of expected weight at least OPT(M,w)/C when the elements arrive in a uniformly random order?',
    'A matroid is a finite set E and a nonempty family I⊆2^E closed under subsets and satisfying augmentation: if A,B∈I and |A|<|B|, some b∈B∖A has A∪{b}∈I. The strategy knows E and I in advance, but not the weights. A fixed adversary assigns w:E→ℝ_{≥0} before the order and strategy coins are sampled. Upon each arrival its identity and weight are revealed. The strategy must accept or reject it irrevocably before the next arrival, keeping the accepted set in I. OPT(M,w)=max_{S∈I}∑_{e∈S}w(e). Expectation includes a uniformly random permutation of E and the strategy’s independent random coins. There is no computation or oracle-query bound; this is the competitive-existence conjecture for the full-information matroid model.',
    'The general matroid secretary problem asks whether random arrival order is enough to recover a constant fraction of a best feasible weighted set without seeing future weights. It unifies classical secretary selection with broad independence constraints.\n\nThe random-assignment model also randomizes where weights are placed, and admits stronger results. Those results do not settle the adversarial-assignment, random-arrival model used here.',
    'The main unresolved competitive-ratio question for online selection under general matroid constraints.',94,
    'Constant-Competitiveness for Random Assignment Matroid Secretary Without Knowing the Matroid','Richard Santiago; Ivan Sergeev; Rico Zenklusen',2025,'https://arxiv.org/abs/2305.05353','Introduction, general matroid secretary conjecture and distinction from random assignment.',
    'The source treats the general constant-competitive conjecture as open while resolving the more symmetric random-assignment setting.',note='No polynomial-time restriction has been silently appended. Earlier exclusions TCS-2570 and TCS-5552 address narrower algorithm/model questions.')

c=add('polylog-kserver','A polylogarithmic randomized competitive ratio for k-server on every metric','online',
    'Do universal constants C,a>0 exist such that, for every integer k≥2, finite metric space (X,d) with |X|≥k+1, and initial placement of k servers, a randomized online strategy has expected total movement cost at most C(1+log₂k)^a OPT(σ)+β on every finite request sequence σ? The additive constant β may depend on the metric, k and initial placement, but not on σ or its length.',
    'There are k movable servers at points of X; repeated server locations are allowed. Each request names a point of X. Before the next request, at least one server must occupy that point. Moving a server from u to v costs d(u,v). The full finite metric and initial placement are known. OPT(σ) is the minimum total movement of a strategy knowing the entire sequence and starting at the same placement. The adversary is oblivious: it fixes σ independently of the online strategy’s random coins. The strategy uses only the prefix revealed so far. No running-time bound is imposed. The exponent a and multiplicative constant C must be independent of |X|, k and the metric.',
    'Randomized k-server is a central test of whether an online algorithm can manage a large changing state at a cost depending mildly on the number of servers. The number of metric points must not occur in the competitive ratio.\n\nThe old O(log k) conjecture is false: a superlogarithmic lower bound is known. Polylogarithmic dependence on k remains a different open target. Bounds containing log|X| do not settle it.',
    'A surviving central problem in randomized competitive analysis, beyond the refuted logarithmic k-server conjecture.',93,
    'Randomized k-server in polynomial time','Christian Coester; Romain Cosson',2026,'https://arxiv.org/abs/2605.01497','Introduction, Theorem 1 and the general-metric corollary.',
    'The 2026 work gives O(log² k) on hierarchical tree metrics and an O(log|X| log² k) consequence on general metrics; it does not remove dependence on |X|.',note='This is explicitly the polylogarithmic k-only question, not the false O(log k) conjecture or the resolved worst-case metrical-task-system ratio.')
cite(c,'lower','The Randomized k-Server Conjecture is False!','Sébastien Bubeck; Christian Coester; Yuval Rabani',2023,'https://arxiv.org/abs/2211.05753','Main lower bound and metrical task systems.','An Ω(log² k) lower bound refutes the original logarithmic conjecture; it is consistent with a polylogarithmic upper bound.')

c=add('hierarchical-clustering','Constant-factor approximation for Dasgupta’s hierarchical clustering objective','approximation',
    'Do a universal constant C≥1 and a deterministic polynomial-time algorithm exist which, for every finite undirected graph G=([n],E) with nonnegative rational edge weights w, output a rooted full binary tree T whose leaves are bijectively labeled by [n] and whose cost is at most C times the minimum cost of such a tree, where cost_G(T)=∑_{{u,v}∈E}w_{uv}|L_T(lca_T(u,v))|?',
    'Here n≥2. The least common ancestor lca_T(u,v) is the lowest common ancestor of the leaves u and v. L_T(z) is the set of leaves below node z, including a leaf itself. Every internal node has exactly two children. Weights are encoded by binary integer numerators and positive denominators; running time is polynomial in the total explicit input bit length. If all weights vanish, every tree has zero cost. The output tree is explicit. No auxiliary distance, planted model or triplet-query oracle is given.',
    'Dasgupta’s objective makes hierarchical clustering a single optimization problem: heavily connected items pay more when they are separated high in the hierarchy. This gives a mathematically specified approximation question on arbitrary similarity graphs.\n\nKnown general guarantees and conditional hardness leave a substantial gap. The Small-Set Expansion hypothesis rules out constant-factor approximation, but that is a conditional barrier rather than an unconditional resolution. Constant guarantees with extra comparison oracles concern a different input model.',
    'The principal approximation barrier for a foundational objective in hierarchical clustering, with links to graph partitioning and metric optimization.',87,
    'A cost function for similarity-based hierarchical clustering','Sanjoy Dasgupta',2016,'https://arxiv.org/abs/1510.05043','Definition of the objective and approximation discussion.',
    'The paper introduces the objective and relates its approximation to graph partitioning.',note='The question is the unrestricted graph objective. No data stability or external clustering oracle is assumed.')
cite(c,'hardness','Approximate Hierarchical Clustering via Sparsest Cut and Spreading Metrics','Moses Charikar; Vaggos Chatziafratis',2017,'https://arxiv.org/abs/1609.09548','Approximation guarantee and Small-Set Expansion hardness.','The paper supplies an O(√log n) approximation and conditional hardness of all constant factors under Small-Set Expansion.')

c=add('calibration','The minimax rate of sequential binary calibration','online',
    'Determine C(T)=inf_A sup_B E[∑_{p∈P_A}|∑_{t:p_t=p}(y_t−p)|] up to universal multiplicative constants as the integer horizon T tends to infinity, in the finite-forecast sequential game below. The requested rate includes logarithmic factors.',
    'Before play, forecaster A selects a finite set P_A⊆[0,1], which may depend on T. Both players know this set and T. At each time t, A selects p_t∈P_A and adversary B selects y_t∈{0,1} simultaneously; neither sees the other’s current selection. Each may randomize using independent coins and the full history (p_s,y_s)_{s<t}, and after the round both selections become public. The infimum is over every such finite set and randomized forecaster, and the supremum is over all randomized adaptive adversaries. There is no computational restriction. The displayed sum measures unnormalized ℓ₁ calibration error and is finite; groups are defined by exact equality of predictions. Expectation is over both players’ coins.',
    'Calibration asks whether forecasts agree with empirical frequencies on the rounds when each probability was announced. The minimax rate measures the unavoidable error in this requirement against an adaptive sequence of binary events.\n\nThe long-standing T^{2/3} upper bound has already been improved by a constant in the exponent. A lower bound strictly above √T is also known. Thus neither the old two-thirds barrier nor a square-root target is an appropriate new open question. The remaining problem is the optimal rate itself.',
    'A fundamental quantitative problem in sequential prediction, with consequences for calibrated learning and decision making.',89,
    'Breaking the T^{2/3} Barrier for Sequential Calibration','Yuval Dagan; Constantinos Daskalakis; Maxwell Fishelson; Noah Golowich; Robert Kleinberg; Princewill Okoroafor',2024,'https://arxiv.org/abs/2406.13668','Section 2.1 and Theorems 1.3–1.4.',
    'The paper proves an upper bound O(T^{2/3−ε}) for an absolute ε>0 and a lower bound Ω(T^{0.54389}); these do not match.',kind='asymptotic_complexity',criterion='resources',related=['TCS-1529'],note='Ordinary calibration is distinct from multicalibration and from simultaneous regret bounds for all proper scoring rules. The source’s finite forecast-set convention is preserved.')

c=add('counting-dichotomy','Are all Boolean log-supermodular counting CSPs #BIS-easy?','counting',
    'For every fixed finite family F of functions f:{0,1}^{r_f}→ℚ_{≥0} satisfying f(x∨y)f(x∧y)≥f(x)f(y) for all x,y, is #CSP(F) approximation-preserving reducible to #BIS?',
    'Arity r_f is a nonnegative integer fixed with f; ∨ and ∧ act coordinatewise. A #CSP(F) instance consists of finitely many Boolean variables and a list of constraints, each naming a function in F and an ordered tuple of variables of its arity; repeats in a tuple are permitted. Its value Z is the sum over all Boolean assignments of the product of all constraint values. Function tables are fixed nonnegative rationals, not part of the instance. #BIS counts all independent vertex sets of a finite simple bipartite graph. An approximation-preserving reduction is a randomized oracle algorithm which, on an instance I and rational ε∈(0,1), returns a relative (1±ε) estimate of Z with probability at least 3/4 using time polynomial in |I| and 1/ε. Its oracle calls request relative approximations to #BIS with inverse tolerances polynomially bounded in |I| and 1/ε. Oracle failure probabilities may be reduced to an inverse polynomial by independent repetitions; the reduction’s overall correctness guarantee includes them. If Z=0, a valid relative estimate is exactly zero. Reduction polynomials may depend on the fixed family F. The oracle is an approximation oracle, not exact counting.',
    'Exact finite-domain counting CSPs already have major dichotomy theorems. Approximate counting has a different landscape, and log-supermodularity is one of its central boundaries. This question asks whether that whole Boolean region reduces to the benchmark problem #BIS.\n\nSome log-supermodular functions cannot be represented by the standard implication-and-unary gadgets. That algebraic obstruction does not refute an approximation-preserving reduction, which is a more general notion. The target is this computational gap, not a claim that every counting problem has an established three-way classification.',
    'A broad missing piece in the classification of approximate counting and weighted constraint satisfaction.',89,
    'Counting Constraint Satisfaction Problems','Mark Jerrum',2017,'https://drops.dagstuhl.de/storage/02dagstuhl-follow-ups/dfu-vol007/DFU.Vol7.15301.205/DFU.Vol7.15301.205.pdf','Sections 3.1 and 3.4; pp. 217–218 and 226–227.',
    'The survey separates log-supermodular expressibility from #BIS-easiness, and leaves the general computational classification open.',criterion='resources',related=['TCS-7221'],note='The finite rational-weight formulation follows the conservative counting-CSP literature. No recent source settling this full reduction was identified; current-status confidence is bounded by the dated sources.')
cite(c,'primary-model','The complexity of approximating conservative counting CSPs','Xi Chen; Martin Dyer; Leslie Ann Goldberg; Mark Jerrum; Pinyan Lu; Colin McQuillan; David Richerby',2015,'https://arxiv.org/abs/1208.1783','Definitions of weighted functions, AP-reductions and log-supermodularity.','The classification isolates the log-supermodular approximation region but does not collapse it to #BIS by a general AP-reduction.')

c=add('real-pnp','P_R versus NP_R in the Blum–Shub–Smale model','complexity',
    'Is P_ℝ=NP_ℝ for the unit-cost Blum–Shub–Smale model over the ordered field of real numbers?',
    'Inputs are finite tuples x∈ℝ^n, with input size n. A machine has a finite program and finitely many fixed real constants. It can store and copy real numbers, perform +, −, ×, and division by a nonzero number, and branch on the sign or equality to zero of a stored real, at unit cost per operation; the ordinary BSS input, output and register-shift operations are included. P_ℝ consists of subsets of the disjoint union of the spaces ℝ^n decidable by one such deterministic machine in polynomially many steps as a function of n. NP_ℝ consists of sets for which membership of x is equivalent to existence of a real witness y of length bounded by a polynomial in n that is accepted by one deterministic BSS verifier in polynomially many steps. Machine constants are finite and independent of input length; witnesses may contain arbitrary reals. The target is equality of these classes, not equality in a finite-precision or bit-cost model.',
    'The BSS model treats exact field operations and order tests as elementary computation. Its version of nondeterminism allows real witnesses and captures basic real algebraic feasibility problems.\n\nThis separation is a foundational question about algebraic computation over a continuum. Classical P versus NP does not by itself answer it: the input representation, cost model and certificates differ.',
    'The defining complexity-class question for exact computation over the reals, connecting TCS to algebraic geometry and numerical computation.',94,
    'A survey on real structural complexity theory','Klaus Meer; Christian Michaux',1997,'https://www.emis.de/journals/BBMS/Bulletin/bul971/meer.pdf','Section 2: real machines, P_ℝ, NP_ℝ and completeness.',
    'The survey develops the model and its central P_ℝ versus NP_ℝ question; the literature check found no established resolution.',criterion='models',note='The full real-constant BSS convention is explicit. This is not a duplicate of the atlas’s classical P versus NP target.')

c=add('superstring','A polynomial-time 2-approximation for shortest common superstring','strings',
    'Does a deterministic polynomial-time algorithm exist which, on every finite collection S of explicitly given strings over a finite alphabet, returns a string containing every member of S as a contiguous substring and having length at most 2·OPT(S), where OPT(S) is the smallest possible length of such a string?',
    'Symbols are integers from {1,…,σ}, encoded in binary; σ and all strings are input. Running time is measured on a deterministic Turing machine in the total bit length of this explicit representation. String length counts symbols. Repeated and empty input strings are allowed. For an empty collection, OPT is zero. The output is an explicit string over the input alphabet, and containment means ordinary forward contiguous occurrence without reversal, reverse complementation or cyclic wraparound. All preprocessing is charged.',
    'Shortest common superstring formalizes assembly of overlapping sequences. The unresolved factor two is an approximation barrier for the problem itself, regardless of the algorithm used.\n\nAn August 2026 preprint gives a 7/3 approximation. A separate September preprint claims a counterexample to the factor-two guarantee for maximum-overlap greedy. Even if that claim is correct, it concerns a particular algorithm and does not answer the general existence question here.',
    'A long-standing approximation threshold for a basic string-assembly problem with direct algorithmic genomics and compression motivation.',85,
    'A Tight Cycle-Cover Inequality for Shortest Common Superstring','Nikolai Chukhin; Alexander S. Kulikov; Ivan Mihajlin; Alexander Smal',2026,'https://eccc.weizmann.ac.il/report/2026/157/','Introduction and main approximation guarantee.',
    'The August 2026 report claims a 7/3 general approximation and a factor-three upper bound for maximum-overlap greedy.',related=['TCS-0816'],note='TCS-0816 is the separate exact exponential-time question from Dagstuhl 2013. The factor-two target does not specify greedy, whose conjectured guarantee has a recent refutation claim.')
cite(c,'greedy-claim','Disproving the Greedy Superstring Conjecture','Hiroki Shibata',2026,'https://arxiv.org/abs/2609.01365','Abstract and main counterexample claim.','A 1 September 2026 preprint claims a 9/4 lower bound for greedy. This report records the claim without certifying its proof; it does not refute general 2-approximation.')

c=add('pir-owf','Nontrivial single-server private information retrieval from one-way functions','crypto',
    'Does the existence of classical one-way functions imply a computationally private single-server private-information-retrieval protocol with sublinear communication and no client database preprocessing?',
    'The client holds an index i into an n-bit database held by one server and must recover its bit, while the server cannot computationally distinguish requests for different indices. The client receives no database-dependent hint before the retrieval. Both parties use classical computation, and the intended security is against polynomial-time server distinguishers in the plain model. No public-key, homomorphic-encryption or ideal-oracle assumption is given in addition to one-way functions. The precise joint asymptotic communication/security convention remains to be fixed from the source; this is an admitted source draft, not a self-contained benchmark statement.',
    'Nontrivial private retrieval separates communication from database size while hiding which item is requested. The assumption question asks how far this capability lies above one-way computation.\n\nSingle-server PIR implies oblivious transfer under appropriate nontriviality conditions. That implication does not supply a construction from arbitrary one-way functions. Results allowing a database-dependent client hint or preprocessing concern a different model.',
    'A basic unresolved assumption relationship between one-way computation, public-key-style interaction and private access to data.',88,
    'Single-Database Private Information Retrieval Implies Oblivious Transfer','Giovanni Di Crescenzo; Tal Malkin; Rafail Ostrovsky',2000,'https://www.iacr.org/archive/eurocrypt2000/1807/18070122-new.pdf','Introduction, nontrivial PIR definition and main implication.',
    'The source relates nontrivial PIR to oblivious transfer rather than constructing PIR from arbitrary one-way functions.',criterion='construction',issue='Fix the security parameter, database-length range, exact sublinear communication convention, correctness error and adversary uniformity jointly. Do not confuse n-bit nontriviality with an arbitrarily strengthened n^α bound, or with preprocessing PIR.',note='TCS-0461 excluded a bundle of narrower PIR construction/work questions; its deletion reason explicitly did not exclude the general subject. This new card remains a source draft pending the listed formal conventions.')

c=add('offline-oram','Unrestricted offline ORAM bandwidth lower bounds','crypto',
    'Is logarithmic amortized bandwidth overhead necessary for offline oblivious RAM with constant client storage, even when stored words may be arbitrarily encoded rather than merely moved as indivisible items?',
    'An offline simulation receives the logical read/write access sequence in advance and must hide that sequence through its physical memory-access distribution. Bandwidth overhead compares physical memory words transferred with logical operations. Constant client storage is measured in words. The question concerns unrestricted encoding of word contents. The precise word-size regime, sequence-length range, server storage, correctness and statistical-security conventions still require a completed source extraction; no universal bound across incompatible parameter regimes is asserted by this draft.',
    'Oblivious memory is a central primitive for hiding access patterns. The historical logarithmic lower bound used a restriction on how data could be represented, and lifting that restriction in the offline setting exposes a connection to Boolean circuit lower bounds.\n\nLater online lower bounds do not automatically apply when the whole logical access sequence is known beforehand. Moreover, online/offline separations with different logical and physical word sizes make the parameter choices consequential.',
    'A major lower-bound barrier for oblivious computation, linking memory privacy to fundamental circuit complexity.',86,
    'Is There an Oblivious RAM Lower Bound?','Elette Boyle; Moni Naor',2016,'https://www.wisdom.weizmann.ac.il/~naor/PAPERS/oram_lower.pdf','Sections 1.1–1.2 and the offline simulation model.',
    'The paper shows that a general offline logarithmic lower bound would imply a corresponding new Boolean sorting-circuit lower bound.',criterion='resources',issue='Complete the joint model: equal logical/physical word size, its growth with n, client and server space, amortization and sequence length, and statistical correctness/privacy. A lower bound cannot be copied from the online or indivisible-data models.',note='This source draft deliberately does not claim a completed Ω(log n) statement for all word-size choices.')
cite(c,'separation','A Separation Between Offline and Online Oblivious RAM','Ilan Komargodski; Wei-Kai Lin',2025,'https://doi.org/10.1137/21M1428431','Model parameters and the offline/online separation.','The paper separates the models for a parameter regime with different logical and physical word sizes; this reinforces the need to state those parameters before completing the draft.')

c=add('linear-bellman','Efficient learning for stochastic linear Bellman-complete MDPs','learning',
    'Can online episodic reinforcement learning find an ε-optimal policy in every stochastic-transition linear Bellman-complete MDP with sample and computation complexity polynomial in feature dimension d, horizon H, action count A and 1/ε, without an oracle that supplies exploratory state-action coverage?',
    'The learner knows feature maps φ_h(x,a)∈ℝ^d and interacts through episodes of H steps; transition probabilities are unknown and may be stochastic. Rewards lie in [0,1], their means are linear in the features, ||φ_h(x,a)||₂≤1, and the instantaneous reward coefficient has norm at most √d. Linear Bellman completeness means that taking the expected maximum over next-step actions of a bounded linear feature function gives a linear function of the current features. No norm bound on arbitrary Q-function coefficients is silently imposed. Success means returning a policy within ε of optimal expected total reward with probability at least 2/3. Finite action sets are used; exact feature/state representation and arithmetic cost still need to be fixed.',
    'Linear Bellman completeness is a fundamental assumption for value-function approximation, broader than the standard linear-transition MDP model. Polynomial statistical complexity is known, while efficient exploration and computation remain problematic in the general setting.\n\nThe March 2026 result makes the deterministic-transition case efficient. It explicitly leaves stochastic transitions as the major remaining extension. Algorithms exponential in the number of actions do not satisfy the requested polynomial dependence.',
    'A central computational-statistical gap in reinforcement learning with function approximation, rather than a tuning question for a particular algorithm.',91,
    'End-to-End Efficient RL for Linear Bellman Complete MDPs with Deterministic Transitions','Zakaria Mhammedi; Alexander Rakhlin; Nneka Okolo',2026,'https://arxiv.org/abs/2603.23461','Definition 2.1, Assumption 2.2, finite-action model and Section 5.',
    'The 2026 paper handles deterministic transitions, including stochastic rewards and initial states; its conclusion retains stochastic dynamics as an open target.',issue='Specify the measurable/encoded state space, access cost and precision for features, Bellman-closure domain and terminal convention, and bit versus real-arithmetic computational model. Preserve the source’s reward bound without imposing a stronger Q-parameter norm restriction.',note='Admitted as a source draft. The deterministic-transition theorem is recorded as progress, not mistaken for a solution of the stochastic model.')

if __name__=='__main__':
    assert len(CARDS)==12 and len({c['key'] for c in CARDS})==12
    (BASE/'additions.json').write_text(json.dumps(CARDS,ensure_ascii=False,indent=2)+'\n')
    print('Authored',len(CARDS),'cards;',sum(c['evidence']=='source' for c in CARDS),'source drafts')
