PREFIX dblp: <https://dblp.org/rdf/schema#>
SELECT DISTINCT ?paper ?title ?toc ?author ?name WHERE {
  ?paper a dblp:Inproceedings ;
    dblp:publishedInStream <https://dblp.org/streams/conf/focs> ;
    dblp:listedOnTocPage ?toc ; dblp:title ?title ; dblp:authoredBy ?author .
  ?author dblp:primaryCreatorName ?name .
}