from review import card,save,DATE
i='TCS-4009';_,c=card(i);refs=c['references']
refs[0]['locator']='Section 2: finite sets and partially assigned circuits; Definition 3: BC; Section 5: the addition-only arithmetic question.'
refs += [dict(id='full',title='Balance Problems for Integer Circuits — revised full report',authors='Titus Dose',year=2018,url='https://eccc.weizmann.ac.il/report/2018/055/',pdf_url='https://eccc.weizmann.ac.il/report/2018/055/revision/5/download/',locator='Revision 5, 21 June 2018; finite-set circuit definitions and concluding question.'),dict(id='journal',title='Balance problems for integer circuits',authors='Titus Dose',year=2019,url='https://doi.org/10.1016/j.tcs.2019.09.052',locator='Theoretical Computer Science 799, pp. 124–139; publication metadata checked. Journal full text was not accessible; the later author thesis below contains the continuing question.'),dict(id='thesis',title='Balance Problems for Integer Circuits and Separations of Relativized Conjectures on Incompleteness in Promise Classes',authors='Titus Dose',year=2021,url='https://www1.pub.informatik.uni-wuerzburg.de/pub/theses/2021-dose-dissertation.pdf',pdf_url='https://www1.pub.informatik.uni-wuerzburg.de/pub/theses/2021-dose-dissertation.pdf',locator='Submitted 23 July 2020, defended 21 January 2021; Chapter 4 definitions and Section 4.4, question 1 on page 115, explicitly retain the addition question.')]
notes=['Recovered existential assignment of arbitrary finite subsets of nonnegative integers, not singleton variables or evaluation of a fully fixed circuit.','Defined the exact balance predicate and exclusion of an empty output; recovered finite-set constants, sharing and left/right gate inputs.','Distinguished Minkowski addition and set difference from multiplication, integer subtraction and full set complement.','Restated the existence of an undecidable operation subset as the equivalent undecidability question for the maximal permitted operation set, documenting the simple restriction equivalence.','Read the 2021 author thesis, which retains the question, and checked the final 2018 revision and 2019 journal metadata.']
save(i,dict(title='Decidability of additive balance circuits',
 formal='Is BC({∖,∪,∩,+}) undecidable? An instance is a finite partially assigned circuit over finite subsets of ℕ={0,1,2,…}, using set difference, union, intersection and pairwise addition. It is a YES instance if some assignment of arbitrary finite subsets of ℕ to its unassigned input gates makes its output S nonempty and balanced, meaning 2|S|=max(S)+1. Undecidability means that no Turing algorithm halts on every encoded circuit and correctly decides this existence predicate. This is equivalent to the source’s question whether there exists O⊆{∖,∪,∩} such that BC(O∪{+}) is undecidable.',
 definitions='''Let P_fin(ℕ) contain all finite subsets of ℕ, including ∅. For A,B in this domain, A∖B={a∈A:a∉B}, A∪B and A∩B have their usual set meanings, and A+B={a+b:a∈A,b∈B}. These are sets: repeated sums contribute only one element. In particular, A+A uses all pairs of elements of A, not merely the doubled elements. Difference is a binary set operation, not arithmetic subtraction; there is no complement relative to all of ℕ and no pairwise multiplication gate. Every gate evaluates to a finite set.

A circuit is a nonempty finite directed acyclic graph given in topological order, with a designated output gate. Each gate has either no predecessors or an ordered pair of predecessors. A source gate is labeled by an explicitly supplied finite set or marked unassigned. An inner gate is labeled by one allowed operation. Reuse of gates is allowed, and both inputs of a gate may refer to the same predecessor. The left/right order matters for difference. Each unassigned source gate is one independent variable; its value is used consistently at all outgoing edges. Constants are encoded as finite lists of nonnegative integers in binary, with delimiters; duplicates may be removed. Gate descriptions and predecessor indices also have finite binary encodings. Constants, the number of gates and the number k≥0 of unassigned gates are unrestricted parts of the input. Invalid descriptions are rejected. A candidate assignment is a tuple (X₁,…,X_k)∈P_fin(ℕ)^k; neither the cardinalities nor the largest elements of the assigned sets have an a priori bound in terms of circuit size. For k=0 there is one empty assignment. Evaluate the circuit in topological order using the specified set operations.

For a nonempty finite output S, its comparison universe is the finite interval {0,…,max(S)}, which depends on the output itself. Balance means |S|=|{0,…,max(S)}∖S|, equivalently 2|S|=max(S)+1. The empty set is not balanced and never witnesses a YES instance. For any operation set Q, BC(Q) is the language of valid Q-circuits admitting at least one balanced-output assignment. A decider must accept exactly those circuits and reject all others, halting in both cases; no time or space bound beyond termination is imposed. The claimed equivalence with the source’s existential O follows because every smaller-operation circuit is already an instance using the maximal set {∖,∪,∩,+}; a decider for the maximal set decides each restriction. Conversely, if the maximal set is undecidable, O={∖,∪,∩} is one of the allowed choices. The further classification of all eight subsets is a separate question and is not required here.''',
 question_type='yes_no',answer_criterion='A positive answer proves that no total Turing decider exists for the specified language. A negative answer supplies a decider and proves termination and correctness on every finite input circuit. Merely enumerating successful assignments does not decide NO instances. Undecidability for circuits with multiplication or full complement, or hardness within NP/PSPACE for a decidable variant, does not establish the requested undecidability.',
 context_blocks=[dict(title='The variables range over whole finite sets',text='Unlike the singleton-input integer circuits used in some earlier work, these circuits permit an unknown finite set at each unassigned source. Checking one fully assigned circuit is a finite computation; the question quantifies over all finite assignments without a supplied size or magnitude bound.',citation='primary'),dict(title='Multiplication already gives an undecidable variant',text='The source proves that BC({∖,·}), using pairwise multiplication and set difference, is recursively enumerable complete. It also classifies its proper operation subsets: multiplication alone is NL-complete, difference alone is NP-complete, and no operations gives a logarithmic-space problem. These results do not substitute addition for multiplication.',citation='primary'),dict(title='The remaining arithmetic operation is addition',text='The concluding question asks whether addition together with some selection of finite-set operations can already yield undecidability. The main statement uses all three permitted set operations, an equivalent way to ask whether any such selection is undecidable; it does not require a full classification of the smaller selections.',citation='full'),dict(title='Later exposition still asks the same question',text='The author’s doctoral thesis, submitted in 2020 and defended in January 2021, repeats the addition question as the first question in Section 4.4. Its additional undecidability consequences involve multiplication and symmetric-difference variants, so they do not settle the additive target.',citation='thesis')],
 why='Locates a decidability boundary for finite-set constraints with a cardinality condition tied to the output’s numerical range. It asks whether addition and basic finite-set operations can encode unbounded computation without the multiplication used in the known undecidable case.',
 progress=[dict(date='2018',text='The multiplication-and-difference balance problem is proved recursively enumerable complete, and the source leaves the corresponding additive question open.',citation='primary'),dict(date='2019',text='The results appear in Theoretical Computer Science; publication metadata checked.',citation='journal'),dict(date='2021',text='The author’s thesis repeats the additive undecidability question on page 115.',citation='thesis')],references=refs,status='open',status_note='Read the original finite-set semantics and final question, ECCC revision 5 of 21 June 2018, and the later author thesis’s definitions and Section 4.4. Checked the 2019 journal publication metadata; journal full text was unavailable. Searches through 12 September 2026 found no resolution for the specified additive operation set and are not exhaustive.',model_self_contained=True,requires_context=False,
 review_note='The maximal-operation formulation is logically equivalent to the saved existential-subset question. The card retains existential finite-set inputs, exact output-dependent balance and ordinary undecidability; it does not replace them by singleton arithmetic, bounded assignments, emptiness or evaluation.',
 importance=dict(score=c['importance']['score'],method='editorial',reason='A clean computability boundary between additive and multiplicative finite-set constraints, revealing the expressive role of set operations and exact balance. Existing score retained.',assessed_on=DATE),
 working_summary=dict(sentences=['An integer circuit here computes finite sets using union, intersection, set difference and pairwise addition.','Its unknown inputs may be arbitrary finite sets of nonnegative integers.','The question asks whether deciding the existence of an assignment with exactly half the numbers up to the output maximum present is undecidable.','Multiplication with set difference already yields an undecidable problem, but this does not establish the additive case.','The 2021 author thesis explicitly retains the question; using all allowed set operations is equivalent to asking whether some subset makes it undecidable.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','full','journal','thesis'])
),notes=notes,checked_sources=[r['url'] for r in refs]+['https://api.crossref.org/works/10.1016/j.tcs.2019.09.052'])
