from review import card,save,DATE
i='TCS-3959';_,c=card(i);refs=c['references']
refs[0]['locator']='Problem 1, Theorems 2 and 15, and the final open question on page 10:17.'
refs += [dict(id='journal',title='Algebraic Dependencies and PSPACE Algorithms in Approximative Complexity over Any Field',authors='Zeyu Guo; Nitin Saxena; Amit Sinhababu',year=2019,url='https://doi.org/10.4086/toc.2019.v015a016',pdf_url='https://theoryofcomputing.org/articles/v015a016/v015a016.pdf',locator='Published 14 December 2019; Problem 1.2, Theorem 1.3, Lemma 4.1 and Theorem 4.2; Section 6 explicitly repeats the AM-under-GRH question.'),dict(id='strong2026',title='When Hilbert approximates: A Strong Nullstellensatz for Approximate Polynomial Satisfiability',authors='Sanyam Agarwal; Sagnik Dutta; Anurag Pandey; Himanshu Shukla',year=2026,url='https://eccc.weizmann.ac.il/report/2026/026/',pdf_url='https://eccc.weizmann.ac.il/report/2026/026/revision/1/download/',locator='Revision 1, 20 February 2026; Theorem 1.4 gives a PSPACE bound for approximate-vanishing containment; Section 4 still calls for improved complexity bounds.')]
notes=['Defined the rational-coefficient bit-model formulation of the characteristic-zero question, following the source’s comparison with HN over Q; arbitrary unencoded field constants are not computational inputs.','Recovered universal quantification over all annihilators, the YES polarity, origin-in-image-closure equivalence, and Laurent-polynomial approximate solutions.','Specified division-free circuit encoding with unrestricted degree, polynomial bit-time AM verifiers and all public-coin completeness/soundness quantifiers.','Separated arbitrary limiting satisfiability from exact root existence and from any fixed-error numerical test.','Read the December 2019 journal and February 2026 strong approximative Nullstellensatz preprint; neither gives the requested AM bound.']
save(i,dict(
 title='Approximate polynomial satisfiability in AM under GRH',
 formal='Assuming the Generalized Riemann Hypothesis, is approximate polynomial satisfiability for rational-coefficient arithmetic circuits in AM? An instance consists of division-free circuits computing f₁,…,f_m∈ℚ[x₁,…,x_n]. It is a YES instance if, for every real η>0, there is a point a∈ℂⁿ with max_i |f_i(a)|<η; otherwise it is a NO instance. Equivalently, for every polynomial A∈ℚ[y₁,…,y_m], the identity A(f₁,…,f_m)=0 must imply A(0,…,0)=0. This equivalent decision predicate is AnnAtZero. Ask for one uniform public-coin protocol with verifier time, random-tape length and prover-message length polynomial in the full binary input length, with completeness at least 2/3 and soundness at most 1/3 on every instance.',
 definitions='''The integers n,m are positive and part of the instance. Each circuit is a finite acyclic graph with input gates x_j or rational constants and binary +,−,× gates; no division by expressions is allowed. The encoding lists gates in topological order, their input indices, their types, and the output gates. A rational constant is given by signed binary numerator and positive binary denominator. The bit length L counts this entire finite description, including constants and gate references. Variables can be relabeled so n is at most the description length; unused variables do not affect the predicate. Shared gates are allowed. Neither total degree nor the magnitudes of intermediate coefficients are promised polynomial in L. The target is a Turing bit-complexity bound, not unit-cost arithmetic with arbitrary complex constants.

An annihilator is a nonzero polynomial A(y₁,…,y_m) over ℚ such that substituting the f_i yields the zero polynomial. Equivalently one can quantify over all A, including zero as in the formal statement. AnnAtZero asks whether every such A has zero constant term, not whether some annihilator exists. In particular, algebraically independent f_i satisfy it vacuously. The same condition holds if the annihilator coefficients are allowed in the algebraic closure ℚ̄. A further equivalent algebraic formulation is: there are finite Laurent polynomials β_j(t)∈ℚ̄[t,t⁻¹] such that f_i(β₁(t),…,β_n(t))∈tℚ̄[t] for every i. Negative powers in the β_j are permitted, but all nonpositive powers must disappear after evaluation of each f_i. There is no input error tolerance or promised bound on the exponents, coefficient descriptions or sizes of these witnesses. The Laurent formulation is equivalent to the rational-function formulation in the source. Geometrically, the origin belongs to the Zariski closure of the polynomial image f(ℂⁿ): the smallest set defined by polynomial equations containing that image. For complex polynomial maps this is also equivalent to membership in its Euclidean closure, giving the η formulation. The approximating points may escape every bounded region; the target does not require an exact common zero in ℂⁿ.

AM means the following. There are a deterministic polynomial-time bit algorithm V and polynomials r,p such that Arthur samples a uniformly random string u∈{0,1}^{r(L)} and sends it to Merlin, who returns w∈{0,1}^{p(L)}; then V(instance,u,w) accepts or rejects. Merlin knows the instance and u and has unlimited computation. All verifier randomness is in u; the verifier has no remaining private coins. For every YES instance, Pr_u[∃w:V(instance,u,w)=1]≥2/3, and for every NO instance this probability is at most 1/3. Constants and polynomial exponents are universal across n,m,L. Shorter messages may be padded. GRH here is the usual number-field form: every nontrivial zero in 0<Re(s)<1 of the Dedekind zeta function ζ_K(s) of every number field K has real part 1/2. It is an assumption, not an oracle supplied to the verifier. The task asks for the stated inclusion under that assumption; no certificate of the truth of GRH is demanded.''',
 question_type='yes_no',answer_criterion='Prove, under GRH, that one AM protocol satisfying the stated bounds decides every encoded instance, or refute the inclusion under the same assumption. A protocol only for exact common-root existence, algebraic dependence, bounded-degree special cases, or finite fields does not establish the target. A PSPACE algorithm or a test at one fixed positive numerical tolerance is insufficient. Failure of a proposed protocol is not a proof that APS is outside AM.',
 context_blocks=[dict(title='Limits add solutions that are not exact roots',text='For f₁=x and f₂=xy−1, the values at (t,1/t) approach (0,0) as t tends to zero, although no complex point makes both polynomials vanish. Thus exact Hilbert Nullstellensatz satisfiability and APS have different YES sets; the source’s conditional AM result for the former cannot simply be reused for the latter.',citation='journal'),dict(title='Known general complexity',text='The source proves that APS is NP-hard and belongs to PSPACE, improving the earlier EXPSPACE upper bound. Its equivalence with AnnAtZero and with origin membership in the closure of an image explains the relevance to border complexity, where limits of small algebraic circuits matter.',citation='journal'),dict(title='Recent progress retains the complexity gap',text='The February 2026 preprint develops a strong approximative Nullstellensatz for containment of approximate-vanishing sets and proves a PSPACE upper bound for that containment problem. Its conclusion still identifies improved complexity bounds as an open direction. It does not establish AM membership for APS under GRH.',citation='strong2026'),dict(title='Coefficient-field interpretation',text='The source phrases the question over characteristic-zero fields and motivates it by the HN result for F=ℚ. This card fixes the usual rational-coefficient binary input version, with solutions over the algebraic closure or ℂ. It makes no claim of equivalence to a model with arbitrary characteristic-zero fields supplied as computational inputs or with unencoded complex constants.',citation='journal')],
 why='Would place a fundamental decision problem about limiting algebraic solutions inside a low level of interactive complexity rather than merely polynomial space. This would clarify the computational cost of passing from exact algebraic objects to their closures, a central operation in border complexity and geometric complexity theory.',
 progress=[dict(date='2018',text='APS is introduced as a geometric and algebraic reformulation of AnnAtZero, with NP-hardness and a PSPACE upper bound.',citation='primary'),dict(date='2019',text='The journal version explicitly retains the AM-under-GRH question in its conclusion.',citation='journal'),dict(date='2026-02-20',text='A revised preprint extends the algebraic characterization to approximate-vanishing containment and provides another PSPACE bound, leaving faster decision procedures open.',citation='strong2026')],references=refs,status='open',status_note='Checked the original source, the full 2019 journal definitions and open question, and the February 2026 preprint’s theorem statements and conclusion. A July 2026 SC² invited-talk abstract mentions APS but states the GRH-to-AM result only for exact HN; it is not evidence that APS has been placed in AM. Searches through 12 September 2026 found no resolution of the stated rational-coefficient target and are not exhaustive.',model_self_contained=True,requires_context=False,
 review_note='The target is an exact decision question about arbitrarily accurate limiting solutions, not a numerical approximation task. Its rational-coefficient computational interpretation is explicit, the AnnAtZero polarity is preserved, and the 2026 containment theorem is not presented as the requested class inclusion.',
 importance=dict(score=c['importance']['score'],method='editorial',reason='A basic complexity question about algebraic closure operations with consequences for border computation and geometric complexity; it asks whether an established polynomial-space upper bound can drop to AM under a standard arithmetic hypothesis. Existing score retained.',assessed_on=DATE),
 working_summary=dict(sentences=['Approximate polynomial satisfiability asks whether a rational polynomial system can have all residuals arbitrarily close to zero over the complex numbers.','The approximating points may diverge, so an exact common root need not exist.','Equivalently, every algebraic relation among the input polynomials must have zero constant term.','The question asks whether a polynomial-time public-coin interactive verifier can decide this under GRH; APS is currently known to be NP-hard and in PSPACE.','A February 2026 extension treats containment of approximate solution sets in PSPACE and does not supply the requested AM bound.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','journal','strong2026'])
),notes=notes,checked_sources=[r['url'] for r in refs]+['https://www.sc-square.org/CSA/workshop11.html'])
