from review import card,save,DATE
i='TCS-6721';_,c=card(i);refs=c['references'];refs[0]['locator']='Open Problems, Problem 3, pages 448–449; Section 4.6 supplies the ordinary one-dimensional bin-packing model. The requested endpoint is one extra bin, with a general constant presented as partial progress.'
refs += [dict(id='logarithmic',title='A Logarithmic Additive Integrality Gap for Bin Packing',authors='Rebecca Hoberg; Thomas Rothvoss',year=2017,url='https://doi.org/10.1137/1.9781611974782.172',pdf_url='https://arxiv.org/pdf/1503.08796',locator='SODA 2017, pages 2616–2625, published online 4 January 2017. Full author preprint submitted 30 March 2015: Section 1.1, Theorem 2, gives the logarithmic additive guarantee in randomized expected polynomial time.')]
save(i,dict(
formal=r'''Is there a polynomial-time approximation algorithm for one-dimensional offline bin packing that uses at most one more bin than optimum? Explicitly allowing randomization, the target is one uniform probabilistic algorithm \(A\) and a polynomial \(p\) such that, for every finite input list \(I=(s_{1},\ldots,s_{n})\) of rational sizes \(0<s_{i}\le1\), \(A\) runs within \(p(L)\) steps for every coin sequence, always outputs a feasible packing, and satisfies
\[
\Pr\bigl[B(A(I))\le\operatorname{OPT}(I)+1\bigr]\ge\tfrac23.
\]
Here \(L\) is the total binary input length, \(B\) is the number of bins used, and probability is over the algorithm’s independent fair random bits for each fixed input. A deterministic algorithm with the same bound on every input also qualifies.''',
definitions=r'''All items and their sizes are given before computation starts. Each item is listed separately, including repetitions. Write \(s_{i}=a_{i}/b_{i}\), where \(a_{i},b_{i}\) are positive binary integers and \(a_{i}\le b_{i}\). Input length includes the item list, numerators, denominators and separators; arithmetic precision is not free.

A packing partitions the item indices \(\{1,\ldots,n\}\) into nonempty bins \(B_{1},\ldots,B_{q}\) such that
\[
\sum_{i\in B_{j}}s_{i}\le1\quad\text{for every }j.
\]
Items are indivisible and must each appear in exactly one bin. The output explicitly assigns every item to a bin. The integer \(\operatorname{OPT}(I)\) is the minimum feasible number \(q\); the empty input has optimum zero and can be packed in zero bins. Zero-size items, if allowed by an alternative convention, can be handled separately without changing the existence question.

Running time is worst-case bit complexity on a uniform probabilistic multitape Turing machine. There is no input advice, supplied optimal packing or promise on the size distribution, number of distinct sizes or optimum. The input is an explicit list, not binary multiplicities representing exponentially many separate output items.

The additive allowance is exactly one bin with capacity exactly 1. It does not grow with the instance, and it is not a multiplicative factor \(1+\varepsilon\). Neither larger bin capacities nor discarding an item is permitted. The target concerns the integer optimum of the packing problem, not the optimum of a fractional relaxation.

The probability convention makes explicit an algorithmic interpretation that includes randomized approximation algorithms, as in the later logarithmic-additive result. Its theorem gives expected polynomial runtime with its quality guarantee; that is a separately reported form of the known result. For the target here, the output must always be feasible and only the one-extra-bin guarantee may fail with probability at most \(1/3\).''',
question_type='yes_no',answer_criterion=r'Give one algorithm and a proof of all stated time, feasibility and probability guarantees, or refute the existence of such an algorithm. A conditional impossibility result must expose its assumption, including any assumption needed to exclude randomized algorithms. An \(\operatorname{OPT}+C\) bound with unspecified constant \(C>1\), an asymptotic approximation scheme, or a nonconstructive fractional-integrality-gap bound alone does not meet the target.',
context_blocks=[
dict(title='One extra bin is the source’s endpoint',text='Problem 3 asks whether bin packing can join problems that admit polynomial-time solutions within one unit of their integer optimum. The book separately highlights a constant number of extra bins as significant progress. This card keeps the one-bin endpoint as its main target.',citation='primary'),
dict(title='The historical logarithmic-squared bound improved',text=r'The book recalls the Karmarkar–Karp additive \(O((\log n)^{2})\) guarantee. Hoberg and Rothvoss later give a randomized algorithm with expected polynomial runtime and at most \(\operatorname{OPT}_{f}+O(\log(\operatorname{OPT}_{f}+2))\) bins, where \(\operatorname{OPT}_{f}\le\operatorname{OPT}\) is the fractional packing optimum. In particular this gives \(\operatorname{OPT}+O(\log(\operatorname{OPT}+2))\) bins, without establishing a constant additive bound.',citation='logarithmic'),
dict(title='Fractional packing is a related comparison',text=r'The Gilmore–Gomory relaxation permits a nonnegative fractional number of copies of each feasible bin pattern and requires enough total coverage of each item type. Its objective is the total fractional number of bins. Statements comparing its optimum to integer packings concern an integrality gap; an existence bound for that gap does not by itself specify the efficient algorithm required here.',citation='logarithmic'),
dict(title='Asymptotic ratios do not fix the additive allowance',text=r'Bounds of the form \((1+\varepsilon)\operatorname{OPT}+C_{\varepsilon}\) can approach multiplicative ratio 1 while retaining an unbounded or larger additive loss. They therefore do not imply the requested one-extra-bin guarantee on every instance.',citation='primary')],
why='A one-extra-bin algorithm would show that a strongly NP-hard packing problem can nevertheless be solved to a uniformly tiny additive error. The question tests a much sharper notion of approximation than a ratio tending to one and is a long-standing benchmark for understanding the structure of feasible packings.',
progress=[dict(date='2011',text='Williamson and Shmoys list the one-extra-bin target among their principal open approximation questions, with constant additive error as partial progress.',citation='primary'),dict(date='2015',text='Hoberg and Rothvoss announce the logarithmic additive improvement in their author preprint.',citation='logarithmic'),dict(date='2017',text='The logarithmic additive result is published at SODA.',citation='logarithmic')],
references=refs,status='open',status_note='Checked the complete two-page source question and the full Hoberg–Rothvoss author manuscript, especially Theorem 2 and its expected-time randomization convention. Confirmed the SODA 2017 publication date from publisher metadata. Searches through 12 September 2026 found no algorithm achieving the stated one-extra-bin target; newer results for online, dynamic or other packing variants do not establish it. The dated known bound is not presented as a newly proved 2026 theorem.',
model_self_contained=True,requires_context=False,review_note='Defined explicit binary rational inputs, offline packing output, integer optimum, exact capacity, additive-one guarantee and uniform bit complexity. Explicitly allows bounded-error randomization; preserves the source’s constant-additive discussion as partial progress.',
importance=dict(score=c['importance']['score'],method='editorial',reason='A major additive-approximation question for a foundational packing problem: whether efficient algorithms can remain within one bin of the integer optimum on every instance. Existing score retained.',assessed_on=DATE),
working_summary=dict(sentences=['Bin packing assigns indivisible items of known sizes to bins of unit capacity.','The goal is to find a packing that uses at most one bin more than the minimum possible.','The algorithm must run in polynomial time in the complete binary input length.','Known general algorithms achieve a logarithmic additive loss, while approximation schemes do not guarantee one extra bin.','The question asks how closely efficient computation can approach the exact optimum of a fundamental packing problem.'],basis='saved_sources',written_on=DATE,source_refs=['primary','logarithmic'])),
notes=['Recovered the source’s one-bin endpoint rather than replacing it with an arbitrary additive constant.','Defined item encoding, packing witness and exact capacity.','Specified a uniform randomized polynomial-time interpretation with per-input success probability.','Checked the full later logarithmic-additive theorem and distinguished integrality gaps from algorithms.'],
checked_sources=[r['url'] for r in refs]+['https://arxiv.org/abs/1503.08796','https://api.crossref.org/works/10.1137/1.9781611974782.172'])
