from review import card,save,DATE
i='TCS-5798';_,c=card(i);refs=c['references'];refs[0]['locator']='Definition 2, page 87:8; concluding polynomial-time search questions, page 87:12. This card explicitly selects the prime-generation question.'
refs += [dict(id='primes',title='Polynomial-Time Pseudodeterministic Construction of Primes',authors='Lijie Chen; Zhenjian Lu; Igor C. Oliveira; Hanlin Ren; Rahul Santhanam',year=2026,url='https://doi.org/10.1145/3803408',pdf_url='https://eccc.weizmann.ac.il/report/2023/076/revision/1/download',locator='Journal of the ACM 73(2), article 14, published 23 April 2026 (publisher-deposited metadata). Full author manuscript dated 3 December 2025, ECCC revision posted 4 December 2025, introduction, Theorem 1.1 and Corollary 1.2. Earlier FOCS 2023 DOI 10.1109/FOCS57990.2023.00074.')]
save(i,dict(title='Pseudodeterministic construction of primes at every length',
formal=r'Does there exist a uniform randomized algorithm \(A\), a constant \(c\), and a sequence of primes \((p_{n})_{n\geq2}\), with \(2^{n-1}\leq p_{n}<2^{n}\), such that \(A\) runs in time \(O(n^{c})\) on input \(1^{n}\) and \[\Pr[A(1^{n})=p_{n}]\geq 2/3\qquad\text{for every integer }n\geq2?\]',
definitions=r'''The input \(1^{n}\) is unary: a string of \(n\) copies of the symbol 1. The output is the ordinary binary representation of an integer. An \(n\)-bit prime is an integer \(p\) in \([2^{n-1},2^{n})\) whose only positive divisors are 1 and \(p\). The domain begins at \(n=2\), since there is no one-bit prime.

The machine is a single classical probabilistic Turing machine, with independent unbiased random bits and a polynomial worst-case running-time bound on every random tape. There is no advice depending on \(n\), precomputed table of primes, oracle, or free preprocessing. All computation, including any primality tests, counts toward its time bound.

Pseudodeterminism means that for each fixed length there is one fixed prime \(p_{n}\) returned with the stated probability across independent executions. The prime may depend on the algorithm and on \(n\), but not on the execution’s random bits. It need not be the smallest \(n\)-bit prime or a prime prescribed in advance. The remaining probability mass may produce a failure symbol, another prime, or an invalid output.

The guarantee is required at every length. Success on infinitely many unbounded lengths alone does not suffice. A guarantee for all sufficiently large lengths would suffice, since finitely many shorter lengths can be handled by a fixed finite part of the algorithm.

The constant success probability is the usual bounded-error convention for pseudodeterminism. Independent repetitions followed by a majority output can amplify concentration on the same canonical prime with polynomial overhead. Merely finding some prime with high probability, while different runs usually return different primes, does not meet the requirement.

The source lists several distinct search tasks. This card explicitly selects prime generation as its main target; it does not assert that solving it is equivalent to making every randomized search problem pseudodeterministic.''',
question_type='yes_no',answer_criterion='Construct such an algorithm and prove the polynomial bound and concentration on a fixed valid prime at every length, or prove that no such algorithm exists. A result conditional on a number-theoretic or complexity assumption must identify that assumption. Infinitely-often correctness, nonuniform advice, or ordinary randomized prime generation does not settle the stated unconditional question.',
context_blocks=[
dict(title='Repeatability is the missing requirement',text='Primes can be generated in randomized polynomial time with high probability by sampling candidates and using polynomial-time primality testing. The resulting distribution typically spreads its mass over many primes. Pseudodeterminism asks for a reproducible output even though randomness is used internally.',citation='primes'),
dict(title='Polynomial time is achieved infinitely often',text='The 2023 result of Chen, Lu, Oliveira, Ren and Santhanam, with a 2025 revised manuscript and 2026 journal publication, constructs a canonical prime in polynomial time on infinitely many input lengths. Its guarantee does not cover every sufficiently large length.',citation='primes'),
dict(title='Failure on other lengths remains possible',text=r'Theorem 1.1 gives an algorithm for each dense polynomial-time decidable property that almost always outputs either its canonical valid string or a failure symbol. The probability of actually producing the canonical string is at least \(1-2^{-n}\) only on infinitely many lengths. Allowing near-certain failure on other lengths is precisely weaker than the target here.',citation='primes'),
dict(title='Other questions in the source are separate',text=r'The same 2017 paragraph also asks about constructing irreducible degree-\(d\) polynomials over \(\mathbb F_{p}\) from a prime \(p\) and unary \(d\), and finding primitive roots modulo a prime when the factorization of \(p-1\) is supplied. These are retained as source context, not additional requirements or claimed equivalents of prime construction.',citation='primary')],
why='A canonical prime construction tests how far efficient randomized search can be made reproducible without fully removing randomness. It is a prominent concrete problem connecting derandomization, explicit constructions and computational number theory; extending the infinitely-often theorem would close its remaining length-coverage gap.',
progress=[dict(date='2017',text='The source lists pseudodeterministic polynomial-time prime generation among its open search problems.',citation='primary'),dict(date='2023',text='An unconditional polynomial-time construction succeeds pseudodeterministically on infinitely many lengths.',citation='primes'),dict(date='2025-12-04',text='The revised full manuscript retains the infinitely-often guarantee and distinguishes the all-length question.',citation='primes'),dict(date='2026-04-23',text='The result appears in the Journal of the ACM.',citation='primes')],
references=refs,status='open',status_note='Read the original conclusion and definition of pseudodeterminism, and the December 2025 full revised prime-construction theorem. Checked publisher-deposited metadata for the April 2026 journal publication and searched through 12 September 2026. No unconditional uniform polynomial-time guarantee at every length was found. The major infinitely-often theorem is recorded as partial progress, not as a resolution.',
model_self_contained=True,requires_context=False,review_note='Selected the explicitly listed prime-generation branch, replacing the overbroad generic search title. Defined canonical outputs, unary input, the valid length domain, uniformity, time and per-length probability, and separated infinitely-often from all-length guarantees.',
importance=dict(score=c['importance']['score'],method='editorial',reason='A foundational explicit-construction challenge and concrete test of pseudodeterministic search, with a major infinitely-often theorem leaving a consequential uniform length-coverage gap. Existing score retained.',assessed_on=DATE),
working_summary=dict(sentences=['Given a length in unary, generate a prime with exactly that many binary digits in polynomial time.','For each length, independent runs must return the same fixed prime with probability at least two thirds.','The fixed prime may depend on the algorithm; it is not prescribed in advance.','The requirement must hold at every length of at least two bits.','The known polynomial-time construction meets this requirement only on infinitely many lengths.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','primes'])),
notes=['Explicitly selected the source’s prime-construction question and retained the other algebraic tasks as separate context.','Defined unary input, canonical output, all-length quantifiers, bounded error and uniform polynomial time.','Checked the full revised infinitely-often theorem and the 2026 journal metadata.','Removed solution suggestions and prevented an infinitely-often result from being mislabeled as complete.'],checked_sources=[r['url'] for r in refs]+['https://eccc.weizmann.ac.il/report/2023/076/'])
