from review import card,save,DATE
i='TCS-5787';_,c=card(i);refs=c['references']
refs[0]['locator']='Introduction, page 30:1; drawing, crossing-number and good-drawing definitions, page 30:3.'
refs += [
dict(id='hardness',title='Hardness of Approximation for Crossing Number',authors='Sergio Cabello',year=2013,url='https://doi.org/10.1007/s00454-012-9440-6',pdf_url='https://arxiv.org/pdf/1204.0660',locator='Abstract and main hardness theorem; excludes one fixed approximation ratio greater than one under P ≠ NP, even for cubic graphs.'),
dict(id='subpolynomial',title='A Subpolynomial Approximation Algorithm for Graph Crossing Number in Low-Degree Graphs',authors='Julia Chuzhoy; Zihan Tan',year=2022,url='https://arxiv.org/abs/2202.06827',pdf_url='https://arxiv.org/pdf/2202.06827',locator='Introduction and Corollary 1.3; STOC 2022, DOI 10.1145/3519935.3519984.'),
dict(id='dense',title='An Algorithm for Estimating the Crossing Number of Dense Graphs, and Continuous Analogs of the Crossing and Rectilinear Crossing Numbers',authors='Oriol Solé-Pi',year=2026,url='https://doi.org/10.1007/s00454-025-00783-w',locator='Published online 21 October 2025; Discrete & Computational Geometry 76, 896–930 (2026), Theorem 1.2.'),
dict(id='variant',title="A New Conjecture on Hardness of 2-CSP’s with Implications to Hardness of Densest k-Subgraph and Other Problems",authors='Julia Chuzhoy; Mina Dalirrooyfard; Vadim Grinberg; Zihan Tan',year=2023,url='https://doi.org/10.4230/LIPIcs.ITCS.2023.38',locator='Pages 38:4–38:5 distinguish Minimum Crossing Number from Maximum Bounded-Crossing Subgraph.')]
save(i,dict(title='Constant-factor approximation of graph crossing number',
formal=r'Do there exist a universal constant \(C\geq1\) and a uniform randomized polynomial-time algorithm that, on every finite undirected graph \(G\), outputs a drawing \(D\) in the plane satisfying \[\operatorname{cr}(D)\leq C\,\operatorname{cr}(G)\] with probability at least \(2/3\)?',
definitions=r'''The input explicitly lists the vertices and edges of an unweighted graph. Parallel edges are permitted and counted separately, as in the source. Self-loops can be omitted because they can be drawn locally without crossings. There is no bound on degree, genus or crossing number, and no planar subgraph or embedding is provided. Running time is polynomial in the full input length on every random tape.

A drawing places vertices at distinct points and represents each edge by a simple polygonal curve joining its endpoints, without passing through any other vertex. The objective \(\operatorname{cr}(D)\) is the total number of pairwise edge crossings, summed over the entire drawing. The crossing number \(\operatorname{cr}(G)\) is its minimum over all drawings. One may restrict to good drawings: adjacent edges do not cross, two edges cross at most once, and no three edges cross at one point.

The output must specify a drawing, rather than only an unsupported estimate of its value. A finite combinatorial representation suffices: list crossings in order along each original edge and give a planar embedding of the graph obtained by replacing crossings with degree-four vertices. At each such vertex, the two segments of each original edge must be opposite in the cyclic order. This records the original curves and their crossings without requiring real-number coordinates.

Randomization with bounded error is explicitly allowed, in keeping with the later approximation literature; a deterministic algorithm would also qualify. The success probability is over internal coins for each fixed graph. The constant \(C\) and the polynomial time bound are independent of the graph. In particular, a factor depending on its maximum degree does not meet the target. When \(\operatorname{cr}(G)=0\), the approximation guarantee requires a drawing with no crossings.

This is ordinary topological crossing number. Edges need not be straight, there is no prescribed rotation system, and the objective is not the maximum number of crossings on any one edge. The source’s Multiple Edge Insertion problem additionally keeps a specified subgraph planar; that constraint is absent here.''',
question_type='yes_no',answer_criterion='Give such an algorithm and prove its running time and universal constant-factor guarantee, or prove that none exists. A conditional impossibility result must state its complexity assumption and cover randomized algorithms in the stated model. Hardness for a particular small approximation factor alone does not exclude all constant factors.',
context_blocks=[
dict(title='The existing hardness leaves room for a larger constant',text=r'Cabello proves that there is a constant \(c_{0}>1\) for which deterministic polynomial-time \(c_{0}\)-approximation is impossible unless \(\mathrm P=\mathrm{NP}\), even on cubic graphs. This does not rule out an algorithm with some larger fixed factor. A randomized algorithm is not excluded merely by assuming \(\mathrm P\ne\mathrm{NP}\).',citation='hardness'),
dict(title='Subpolynomial progress for low degree',text=r'Chuzhoy and Tan give a randomized approximation factor \(2^{O((\log n)^{7/8}\log\log n)}\operatorname{poly}(\Delta)\) for simple graphs with \(n\) vertices and maximum degree \(\Delta\). For bounded degree this is subpolynomial in \(n\), but still does not supply a universal constant.',citation='subpolynomial'),
dict(title='Dense graphs admit much sharper approximation',text=r'Solé-Pi’s Theorem 1.2 constructs drawings with \(\operatorname{cr}(G)+O(n^{4}/(\log\log n)^{\delta})\) crossings, for an absolute \(\delta>0\), in randomized polynomial time. This yields asymptotic factor \(1+o(1)\) for dense simple graphs, but the additive error does not yield a constant multiplicative guarantee on arbitrary graphs with small crossing number.',citation='dense'),
dict(title='A later hardness conjecture concerns a different objective',text='The 2023 paper studies maximizing the number of retained edges subject to a crossing budget. Its conditional hardness for Maximum Bounded-Crossing Subgraph should not be read as hardness of every constant approximation for the minimum total crossings of the entire input graph.',citation='variant')],
why='Crossing minimization is a basic graph-layout optimization problem with applications to drawing networks and circuit layouts. A constant approximation would establish a general algorithmic guarantee across sparse and dense inputs, beyond the degree-dependent and additive-error bounds currently available.',
progress=[dict(date='2013',text='A fixed-factor inapproximability result establishes an obstruction to arbitrarily accurate polynomial-time approximation.',citation='hardness'),dict(date='2022',text='A subpolynomial approximation factor is obtained for bounded-degree graphs.',citation='subpolynomial'),dict(date='2025-10-21',text='An additive-error approximation and drawing theorem yields asymptotically optimal approximation for dense graphs.',citation='dense')],
references=refs,status='open',status_note='Checked the original full question and drawing model, the 2022 full approximation theorem, the distinct 2023 hardness variant, and the 2025/2026 dense-graph theorem. Searches through 12 September 2026 found no universal constant-factor approximation or impossibility covering all constants. The randomized convention is explicit; the historical P ≠ NP hardness is stated only for deterministic algorithms.',
model_self_contained=True,requires_context=False,review_note='Recovered the constant-factor drawing target, global crossing objective, unrestricted graph class and output encoding. Separated degree-dependent, dense-graph, local-crossing and edge-retention variants.',
importance=dict(score=c['importance']['score'],method='editorial',reason='A central approximability gap for a classical graph-layout objective, with a large separation between known general guarantees and constant-factor hardness. Existing score retained.',assessed_on=DATE),
working_summary=dict(sentences=['Draw every graph in the plane using at most a fixed constant times its minimum possible number of crossings.','The constant must be independent of the graph size and maximum degree.','The algorithm must construct a drawing in polynomial time; bounded-error randomization is allowed.','Existing low-degree and dense-graph results do not provide this guarantee for all graphs.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','subpolynomial','dense'])),
notes=['Recovered the exact constant-factor target for drawings of general graphs.','Made the randomized convention, input encoding, output and zero-optimum requirement explicit.','Updated later approximation progress and distinguished unrelated hardness variants.','Restored the assumption and quantifier scope of the known fixed-factor hardness.'],checked_sources=[r['url'] for r in refs])
