from review import card,save,DATE
i='TCS-5892';_,c=card(i);refs=c['references'];refs[0]['locator']='Introduction, pages 50:2–50:3: the omitted continuation explicitly names randomized communication, but gives no quantified direct-sum conjecture.'
refs += [dict(id='amortization',title='Efficient Communication Using Partial Information',authors='Mark Braverman; Anup Rao',year=2010,url='https://eccc.weizmann.ac.il/report/2010/083/',pdf_url='https://eccc.weizmann.ac.il/report/2010/083/download',locator='Full report dated 12 May 2010, abstract, Theorem 1.4 and the explicitly per-coordinate error definition preceding it.'),dict(id='claim2026',title='Zero-error information equals amortized communication complexity',authors='Daiki Suruga',year=2026,url='https://arxiv.org/abs/2608.04141',pdf_url='https://arxiv.org/pdf/2608.04141v1',locator='Version 1 submitted 4 August 2026, manuscript dated 6 August 2026; Section 1.2, Theorems 1–2 and Corollary 1. Preprint claims, not independently verified here.')]
issue='The source identifies randomized communication but does not specify total functions versus partial functions or relations, public versus private coins, worst-case versus distributional inputs, global versus per-coordinate error, or the quantitative meaning of a near-perfect direct sum. A recent preprint claims a negative answer for a global-error relation version while explicitly leaving total-function separation open. Select one exact version before treating this as a complete benchmark.'
notes=['Recovered randomized communication from the complete source continuation.','Defined repeated two-party tasks and the distinct error and cost conventions.','Avoided silently choosing a universal linear lower bound or restricting the task class to total Boolean functions.','Recorded the August 2026 claimed relation result and its explicit total-function caveat.']
save(i,dict(title='Direct sums in randomized communication',
formal='Does a near-perfect direct-sum theorem hold for randomized two-party communication complexity? The complete source passage identifies this as the open setting, but does not specify a single quantitative statement or task class. The conventions below explain what must be fixed; this card remains a formulation requiring specification.',
definitions=r'''In a two-party communication task, Alice knows \(x\), Bob knows \(y\), and they exchange bits to produce a valid output. A function has one correct output for each allowed pair; a relation can permit several. A total function is defined on every pair in the product of the two finite input sets. A partial function or relation can impose an input promise.

For a task \(f\), its \(k\)-fold direct sum \(f^{k}\) gives Alice \(x_{1},\ldots,x_{k}\) and Bob \(y_{1},\ldots,y_{k}\), and requires an output for every corresponding pair. It does not ask only for the parity or disjunction of the outputs. In a worst-case formulation the input tuples are arbitrary; calling the copies independent does not provide a sampling distribution.

One common convention writes \(R_{\varepsilon}(f)\) for the minimum worst-case number of communicated bits of a public-coin randomized interactive protocol that errs with probability at most \(\varepsilon\) on each allowed input pair. The parties have unbounded local computation, shared random bits, and may also use private random bits. A designated party outputs the answer; messages and any communicated output bits count, but local computation does not.

Under the global-error convention, \(R_{\varepsilon}(f^{k})\) requires the entire tuple of \(k\) answers to be valid with probability at least \(1-\varepsilon\). Requiring each coordinate separately to be correct with that probability is a weaker condition. An expected-communication measure averages protocol length over random coins for each input, while worst-case communication bounds every transcript. A distributional measure instead fixes an input distribution and permits average error under it.

A strong version would seek a universal \(c>0\) such that
\[R_{1/3}(f^{k})\geq c\,k\,R_{1/3}(f)\]
for every task in a specified class and every integer \(k\geq1\). Allowing logarithmic losses, changing the single-copy error, taking a limit for a fixed task, or making the constant depend on the task produces different assertions. This displayed formula illustrates a precise version; the source paragraph does not establish that it is the exact intended claim for all relations or for total functions.

These distinctions must be chosen together. The card does not replace randomized communication by nondeterministic communication or by a parity decision-tree model, and does not turn a theorem about information revealed into a theorem about bits transmitted without its required assumptions.''',
question_type='yes_no',answer_criterion='First fix the task class, randomness, input and communication-cost conventions, errors and allowed loss in the lower bound. A solution must then prove the resulting universally quantified direct-sum assertion or refute it with a family whose joint complexity violates that bound. An amortized theorem for one error convention or a counterexample using relations does not automatically settle a total-function, global-error version.',
context_blocks=[
dict(title='The missing continuation is now recovered',text='The source contrasts near-perfect nondeterministic direct sums with failures in a deterministic setting and an open randomized setting. It is a brief motivation for studying composition, not a formal statement of all the conventions needed for this benchmark.',citation='primary'),
dict(title='Per-coordinate amortization is already characterized',text='Braverman and Rao’s report characterizes amortized distributional communication by internal information cost when error is bounded separately on each coordinate. Its definition explicitly permits this per-copy error. This does not by itself give the same theorem when every output must be correct simultaneously.',citation='amortization'),
dict(title='A new preprint claims progress for global error',text='Suruga’s August 2026 preprint claims an exact asymptotic characterization of expected communication under global error by zero-error internal information complexity, and constant-factor bounds for worst-case amortized communication. It further claims that the strong direct sum fails for relations by combining this characterization with a search-problem separation. These are recorded as preprint claims, without an independent verification of their proofs.',citation='claim2026'),
dict(title='The preprint retains a total-function question',text='Immediately after Corollary 1, the preprint states that a corresponding separation for total functions remains open. Thus its claimed relation counterexample cannot justify declaring every randomized direct-sum question resolved. The task-class omission in the original source matters to both formulation and current status.',citation='claim2026')],
why='Direct sums ask whether communicating about many tasks together can save a substantial fraction of the single-task cost. They connect communication lower bounds with interactive compression and the distinction between information revealed and bits transmitted. The exact error and task conventions determine which savings are possible.',
progress=[dict(date='2010',text='Information cost is related exactly to amortized distributional communication with error allowed separately in each copy.',citation='amortization'),dict(date='2019',text='The source describes randomized direct sums as an open setting without fixing one complete conjecture.',citation='primary'),dict(date='2026-08-04',text='A preprint claims a global-error amortization characterization and relation counterexamples, while retaining a total-function question.',citation='claim2026')],
references=refs,status='uncertain',status_note='Read the complete source continuation and the relevant error definitions in the 2010 full report. Read the August 2026 preprint’s main theorem statements, model comparison and explicit total-function caveat, and checked its revision history. Searches through 12 September 2026 did not supply a uniquely intended formalization of the source sentence or independent establishment of the new claimed result. No machine-generated review is treated as proof verification.',
model_self_contained=False,requires_context=True,review_note=issue,
statement_review=dict(reviewed_on=DATE,status='needs_specification',notes=notes,remaining_issue=issue,scope='Individual source and later-result review; the source leaves substantive mathematical model choices unresolved.'),
importance=dict(score=c['importance']['score'],method='editorial',reason='A central question about economies of scale in interactive computation, linked to communication lower bounds and compression. Its importance does not remove the need to fix the precise variant. Existing score retained.',assessed_on=DATE),
working_summary=dict(sentences=['Alice and Bob must solve many communication tasks together, each on its own pair of private inputs.','The question asks how much they can save compared with solving the tasks separately.','The recovered source continuation names randomized communication but omits the exact direct-sum inequality and model.','A new preprint claims a relation counterexample in a global-error model while leaving a total-function version open.','The task class, error convention and quantitative bound must be fixed before this card has a single verifiable target.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','amortization','claim2026'])),
notes=notes,checked_sources=[r['url'] for r in refs],state='improved_unfinished')
