from review import card,save,DATE

i='TCS-3799';_,c=card(i);refs=c['references']
refs[0]['locator']='Section 4, pages 55:12–55:13: subsequent work and the logarithmic-depth large-error question.'
refs += [dict(id='journal',title='The Large-Error Approximate Degree of AC⁰',authors='Mark Bun; Justin Thaler',year=2021,url='https://doi.org/10.4086/toc.2021.v017a007',pdf_url='https://theoryofcomputing.org/articles/v017a007/v017a007.pdf',locator='Theory of Computing 17(7), published 23 September 2021; Section 1 defines the error regime, Section 4 pages 13–14 retains this question, Section 8 proves the O(1/δ)-depth result.'),dict(id='bounded',title='A Nearly Optimal Lower Bound on the Approximate Degree of AC⁰',authors='Mark Bun; Justin Thaler',year=2020,url='https://doi.org/10.1137/17M1161737',pdf_url='https://arxiv.org/pdf/1703.05784',locator='SIAM Journal on Computing; FOCS 2017 precursor. Constant-error approximate-degree result, contrasted with large error in Section 4 of the 2021 paper.')]
notes=['Recovered the missing ε=1−2^{-Ω(n^{1−δ})} regime, total-degree notation and uniform real-polynomial approximation model.','Made the universal logarithmic-depth constant and δ-dependent size, degree and error constants explicit.','Kept the large-error branch selected by this card; separated the source’s additional threshold-degree question and removed amplification advice.','Read the 2021 journal version, which retains the question after accounting for Sherstov and Wu’s results, and searched for subsequent resolutions.']
save(i,dict(
 title='Large-error approximate degree at logarithmic AC⁰ depth',
 formal='Does there exist an absolute constant A≥1 such that, for every real δ with 0<δ≤1/2, there are constants aδ>0, bδ>0, sδ≥1 and an integer Nδ≥2, and Boolean functions fδ,n:{−1,1}ⁿ→{−1,1} for every integer n≥Nδ, satisfying both of the following? First, fδ,n has an unbounded-fan-in AND/OR circuit of size at most n^{sδ} and depth at most ⌈A log₂(1/δ)⌉, with negations allowed at inputs. Second, deg_{εδ,n}(fδ,n)≥aδ n^{1−δ}, where εδ,n=1−2^{−bδ n^{1−δ}}. Here degε denotes the minimum total degree of a real polynomial that approximates the function with absolute error at most ε at every Boolean input. The same A must work for all δ; the other constants and the circuit family may depend on δ.',
 definitions='For f:{−1,1}ⁿ→{−1,1} and 0≤ε<1, define degε(f)=min{deg(p): p∈ℝ[x₁,…,xₙ] and max_{x∈{−1,1}ⁿ}|p(x)−f(x)|≤ε}. Degree means total degree, the largest sum of exponents of a monomial with nonzero coefficient. Constants, including the zero polynomial, have degree zero by convention here. Coefficients may be arbitrary reals of arbitrary magnitude: no sparsity, coefficient-bit bound or boundedness away from the Boolean cube is imposed. Equivalently one may use multilinear polynomials, since restricting xᵢ²=1 on the cube does not increase degree. Approximation is worst case over all 2ⁿ inputs, not an average over a distribution. A circuit is a finite acyclic directed graph whose internal gates are AND or OR gates of arbitrary fan-in, whose input literals are xᵢ or their Boolean negations, and whose single output computes f under the usual identification of Boolean values with −1 and +1. Size counts internal gates; depth counts the maximum number of internal gates on an input-to-output path. Any polynomially equivalent gate/wire size convention gives the same existence question, since the polynomial exponent is unrestricted. The family is nonuniform: no algorithm for constructing its circuits or evaluating the polynomial coefficients is required. For each fixed δ its depth is independent of n and its size is polynomial in n, so it is in AC⁰. The question controls how that constant depth grows as δ decreases. Only A is uniform in δ; Nδ and the positive constants in the degree and error bounds need not be. Restricting δ to (0,1/2] records the small-δ asymptotic question and avoids a zero logarithm at δ=1. All sufficiently large input lengths are required, with constants chosen before n. The source’s Ω notation is expanded into aδ and bδ; the gap 1−εδ,n is exponentially small in n^{1−δ}. At error exactly 1 the zero polynomial approximates every ±1-valued function, so keeping a specified positive gap below 1 is essential. For comparison, threshold degree is the minimum degree of a polynomial p satisfying p(x)f(x)>0 at every input; it imposes no specified approximation gap and is a different measure.',
 question_type='yes_no',
 answer_criterion='Prove existence of a single absolute depth constant A and families with all the stated bounds for every 0<δ≤1/2, or prove the negation of that quantified existence statement. A result only at fixed approximation error, only at depth O(1/δ), or only for selected values of δ is insufficient. A negative answer must rule out arbitrary polynomial-size nonuniform families at the stated logarithmic depth, not merely one proposed construction.',
 context_blocks=[dict(title='Near-linear degree is known at larger depth',text='Bun and Thaler prove near-linear approximate-degree lower bounds even when error is exponentially close to the trivial value 1. Their depth grows proportionally to 1/δ. The question is whether the same degree and error regime can occur with depth only proportional to log(1/δ).',citation='journal'),dict(title='Constant error has a better depth dependence',text='Earlier work obtains degree Ω(n^{1−δ}) at depth O(log(1/δ)) for error 1/3. Allowing error extremely close to 1 can make polynomial approximation much easier, so that theorem does not establish the target here.',citation='bounded'),dict(title='Threshold degree is a separate branch',text='The journal discussion includes Sherstov and Wu’s depth-k threshold-degree bound of order n^{(k−1)/(k+1)} up to logarithmic factors. It then asks separately for logarithmic-depth improvements for large-error approximate degree and for threshold degree. This card retains the large-error approximate-degree branch of the extracted question.',citation='journal'),dict(title='Why the error scale matters',text='The source connects this large-error regime to randomized query and communication models that charge both access cost and the logarithm of the inverse advantage over guessing. This makes the tradeoff meaningful even though the approximation advantage is very small.',citation='journal')],
 why='Would determine whether the favorable depth dependence of strong AC⁰ polynomial lower bounds survives when approximation is allowed to be almost trivial, sharpening the relation between shallow circuits and weak randomized computation.',
 progress=[dict(date='2017',text='The FOCS precursor establishes near-linear constant-error approximate degree at depth O(log(1/δ)); the journal version appeared later.',citation='bounded'),dict(date='2019',text='Large-error near-linear lower bounds are obtained at depth O(1/δ), and the logarithmic-depth question is posed.',citation='primary'),dict(date='2021-09-23',text='The full journal paper retains the logarithmic-depth question after discussing later threshold-degree and sign-rank results.',citation='journal')],
 references=refs,status='open',status_note='Checked the full 2021 journal definitions, Section 4 question and Section 8 result, and the earlier constant-error theorem’s scope. Searches through 12 September 2026 found no result attaining the stated logarithmic depth in this large-error regime. The dated source remains the evidence for the open question; the subsequent-work search is not exhaustive.',
 model_self_contained=True,requires_context=False,review_note='Expands the source’s asymptotic notation into explicit quantifiers. This is an existence question about nonuniform Boolean circuit families, with no added efficient-construction requirement. Threshold degree is related context, not an additional required target.',
 importance=dict(score=c['importance']['score'],method='editorial',reason='Separates the depth requirements for constant-error and almost-trivial-error polynomial approximation, with consequences for lower bounds on weak randomized query and communication models. Existing score retained.',assessed_on=DATE),
 working_summary=dict(sentences=['Approximate degree is the least degree of a real polynomial that approximates a Boolean function at every input.','This question allows error 1 minus an exponentially small quantity, while still demanding degree of order n^{1−δ}.','Such lower bounds are known for polynomial-size AC⁰ circuits of depth O(1/δ).','The target is a universal O(log(1/δ)) depth bound for every small fixed δ.','The 2021 journal version retains this question and distinguishes it from known constant-error bounds and from threshold degree.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','journal','bounded'])
),notes=notes,checked_sources=[r['url'] for r in refs]+['https://arxiv.org/abs/1703.05784'])
