from review import card,save,DATE,DIRECTORY,write
import json
def b(title,text,citation=None):
 d=dict(title=title,text=text)
 if citation:d['citation']=citation
 return d
i='TCS-2827';_,c=card(i);refs=c['references'];refs[0]['locator']='ALT 2022, pp. 107–127: Section 2 defines the noiseless online-learning setup; Section 7, p. 16, restates the two bounded-loss questions and the sublinear measurable visits conjecture. These historical statements were resolved at COLT 2022.'
refs.extend([
 dict(id='question2021',title='Open Problem: Is There an Online Learning Algorithm That Learns Whenever Online Learning Is Possible?',authors='Steve Hanneke',year=2021,url='https://proceedings.mlr.press/v134/hanneke21b.html',locator='COLT 2021: Open Problems 1–2 and Definition 5. The source of the historical optimistically universal learning and measurable-visits questions.'),
 dict(id='solution',title='Universal Online Learning: an Optimistically Universal Learning Rule',authors='Moïse Blanchard',year=2022,url='https://proceedings.mlr.press/v178/blanchard22b.html',pdf_url='https://proceedings.mlr.press/v178/blanchard22b/blanchard22b.pdf',locator='COLT 2022, PMLR 178, pp. 1077–1125: Section 2, Theorems 3–4, Corollaries 9–10 and 14–15. Proves both optimistic universality and SUOL=SMV for bounded nonzero separable near-metric losses; also resolves the weak versions. arXiv:2201.05947v2, 8 March 2022.')
])
save(i,dict(
 title='Optimistically universal online learning with bounded losses',status='resolved',
 formal='Historical question, resolved positively: in the noiseless online-learning setting with a separable metric input space and a separable near-metric output space with bounded nonzero loss, does one learning rule learn every process in SUOL, and is SUOL exactly the class SMV of processes with sublinear measurable visits? Blanchard’s COLT 2022 Theorems 3–4 answer both questions affirmatively.',
 definitions='Let (X,ρ) be a nonempty separable metric space with its Borel σ-algebra. Let Y be a nonempty separable near-metric space with loss ℓ:Y×Y→[0,∞), symmetric, zero exactly on equal pairs, satisfying ℓ(a,c)≤C(ℓ(a,b)+ℓ(b,c)) for a fixed finite C, and 0<sup_{a,b}ℓ(a,b)<∞. Separability means a countable dense subset in the corresponding topology; measurable functions use the Borel structures. The input process (X_t)_{t≥1} is arbitrary, without independence or stationarity assumptions. Labels have the form Y_t=f*(X_t) for one fixed unknown measurable function f*:X→Y. A learning rule is a sequence of measurable functions h_t:(X×Y)^{t−1}×X→Y; its prediction at time t uses the labeled past and the current X_t, before Y_t is revealed. Strong universal consistency under a process means that, for every f*, T^{-1}Σ_{t=1}^T ℓ(h_t((X_s,Y_s)_{s<t},X_t),Y_t) tends to zero almost surely. The probability-one event may depend on f*. SUOL is the set of processes for which some one rule has this property for all measurable f*. An optimistically universal rule has it for every process in SUOL, without being told the process law. SMV consists of those processes such that, for each countable measurable partition (A_j)_{j≥1} of X, the number |{j: A_j∩{X₁,…,X_T}≠∅}| is o(T) almost surely; the null event may depend on the partition. No computational running-time or sample-rate bound is part of the question. The identically zero loss is a separate trivial case in which all processes are learnable.',
 question_type='yes_no',answer_criterion='The affirmative resolution is the published COLT 2022 theorem: an optimistically universal rule exists, and SUOL=SMV. Both the learner and the process characterization match the deterministic-target bounded-loss setting of the historical question. A theorem only for i.i.d. processes or for a selected target class would not have sufficed.',
 context_blocks=[b('Learning whenever any rule could succeed','Optimistic universality asks for one rule that succeeds on every process admitting universal learning, rather than selecting a separate rule after the process is known. The process itself may have arbitrary dependence over time.','question2021'),b('A condition on the input process alone','SMV requires sublinear visits to the cells of every countable measurable partition. It does not simply require a sublinear number of distinct input points, and the quantifier over partitions is essential.','solution'),b('Both historical questions are resolved','Blanchard proves the process characterization and provides an optimistically universal rule, called 2C1NN. The same paper also proves corresponding expected-loss results with an expected sublinear-visits condition. The strong almost-sure statement is the one restated in the source card.','solution'),b('The label model limits the conclusion','The target labels are a fixed measurable function of the inputs. Questions involving arbitrary dependent or noisy responses require different guarantees; the historical bounded-loss theorem must not be replaced by such a stronger problem.','primary')],
 why='Gives a complete process-level criterion for noiseless universal online learnability under bounded losses, together with a single rule achieving it without distributional assumptions.',
 references=refs,progress=[dict(date='2021',text='Hanneke poses existence of an optimistically universal rule and characterization by sublinear measurable visits.',citation='question2021'),dict(date='2022',text='The ALT article retains these as historical bounded-loss questions while resolving an unbounded-loss question.',citation='primary'),dict(date='2022-07',text='COLT publishes Blanchard’s Theorems 3–4 resolving both bounded-loss questions, including the strong and weak variants.',citation='solution')],
 status_note='Resolved by Blanchard, COLT 2022, Theorems 3–4 and Corollaries 9–10. Checked the original deterministic-target setup, the full SMV definition, bounded nonzero separable near-metric loss assumptions and the published theorem. The arXiv version record and later searches through 12 September 2026 revealed no correction invalidating this conclusion. This is published-theorem/model matching, not an independent proof audit or proof-assistant certificate.',model_self_contained=True,requires_context=False,
 importance=dict(score=c['importance']['score'],method='editorial',reason='A general characterization of learnability without independence or stationarity, historically connecting optimal model-free behavior with measurable recurrence. Existing score retained.',assessed_on=DATE),review_note='Recovered the noiseless bounded-loss setting and matched both parts of the historical question to the COLT 2022 resolution. Marked resolved instead of manufacturing an unresolved noisy-response extension.',
 working_summary=dict(sentences=['Optimistically universal online learning asks for one rule that succeeds whenever any universally consistent rule can.','For bounded losses and deterministic measurable target labels, the input process can have arbitrary temporal dependence.','Blanchard’s COLT 2022 theorem supplies such a rule and proves that learnability is exactly sublinear measurable visits.','The partition condition is stronger than a statement about visits to finitely many selected regions.','Both historical questions in this card are therefore resolved in their intended noiseless setting.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','question2021','solution'])
 ),notes=['Recovered the bounded-loss, separable-space and deterministic-target assumptions.','Defined SUOL, optimistic universality and the per-partition almost-sure SMV condition.','Matched both historical questions to the published COLT 2022 theorems and marked resolved.'],checked_sources=[r['url'] for r in refs]+['https://arxiv.org/abs/2201.05947','https://proceedings.mlr.press/v167/hanneke22a/hanneke22a.pdf'])
p=DIRECTORY/'queue.json';q=json.loads(p.read_text());_,c=card(i)
if not any(r['id']==i for r in q['dispositions']):q['dispositions'].append(dict(id=i,title=c['title'],state='resolved',reason=c['status_note'],card='data/cards/'+i+'.json'))
write(p,q)
