from review import card,save,DATE
i='TCS-3945';_,c=card(i);refs=c['references']
refs[0]['locator']='Definitions 3–4; introduction and Footnote 5; Problem 10 in Section 4, page 73:12.'
refs += [dict(id='journal',title='An Exponential Separation Between MA and AM Proofs of Proximity',authors='Tom Gur; Yang P. Liu; Ron D. Rothblum',year=2021,url='https://doi.org/10.1007/s00037-021-00212-3',pdf_url='https://link.springer.com/content/pdf/10.1007/s00037-021-00212-3.pdf',locator='Published 18 August 2021; Definitions 2.1–2.2; Problem 6.2 on page 36 retains the O(√n) versus Ω(n) question; Appendix A excludes randomness from the cost.')]
notes=['Restored the missing square root and the direction MAP easy versus AMP hard.','Recovered proof-length-plus-input-bits cost, uncharged public randomness, adaptive proof-dependent queries, and the different order of proof and randomness quantifiers.','Specified the constant-proximity interpretation, total table bit length, symbol-Hamming distance, uniform verifiers and unrestricted computation rather than silently counting alphabet symbols as bits.','Read the full 2021 journal definitions and Problem 6.2, which still asks the exact separation; checked subsequent literature.']
save(i,dict(
 title='Quadratic advantage of MA over AM proofs of proximity',
 formal='Does there exist a family Π of finite-input properties admitting a Merlin–Arthur proof of proximity (MAP) of complexity O(√n) at every fixed positive proximity parameter, but for which every Arthur–Merlin proof of proximity (AMP) has complexity Ω(n) at some fixed positive proximity parameter ε₀? Here n is the full input-table length in bits and complexity is proof length plus input bits read. More precisely, ask for Π, a rational constant ε₀∈(0,1/2), and one MAP verifier V such that for every fixed rational ε∈(0,1) there are Cε,Nε with p_V(n)+q_V(n,ε)≤Cε√n for all admissible n≥Nε. For every AMP verifier W for Π there must be c_W>0,N_W such that p_W(n,ε₀)+q_W(n,ε₀)≥c_W n for every admissible n≥N_W. Neither bound hides factors growing with n. The same family and the same distance notion are used on both sides.',
 definitions='''To cover the source’s function properties, a candidate specifies an infinite decidable set I of admissible bit lengths, and, uniformly from n∈I, positive integers m(n),b(n) with m(n)b(n)=n and a finite alphabet Σ_n⊆{0,1}^{b(n)} of at least two symbols. An input is a table x∈Σ_n^{m(n)}, equivalently a function [m(n)]→Σ_n, and Π_n is a nonempty subset of these tables. The family and its finite alphabet descriptions must be mathematically specified; no polynomial-time membership test for Π is required. Boolean strings are the case b=1,m=n. Distance is Δ(x,Π_n)=min_{y∈Π_n}|{j:x_j≠y_j}|/m(n), the fraction of differing table entries, not the fraction of differing bits inside their symbols. A NO input has Δ>ε; members are YES inputs; no verdict is required for nonmembers with Δ≤ε. A query chooses j and reads x_j, charging b(n) bits. Queries may depend on the proof and on earlier answers. This is ordinary oracle access, not independent sampling, proof-oblivious access or a distribution-testing model. All n-asymptotics range over I.

A verifier is one finite, uniform oracle algorithm for the whole family, given n and rational ε∈(0,1) explicitly. It halts on every input, proof and random tape; it uses a finite computably bounded number of independent fair bits for each n,ε. Local computation and random bits are not charged and have no polynomial-time restriction. The prover knows the entire input and is computationally unrestricted. Proofs are binary strings of the specified length; shorter proofs may be padded, and oversized strings can be rejected without querying the input. Cost counts the whole permitted proof length, even if the verifier reads fewer proof bits. Query bounds hold for all inputs, proofs and randomness, not only in expectation.

For an MAP, the prover sends w before the verifier uses private randomness r. Completeness requires, for every n and x∈Π_n, a single w of length p(n), independent of ε and r, such that Pr_r[V^x(n,ε,w;r)=1]≥2/3 for every rational ε∈(0,1). Soundness requires Pr_r[V^x(n,ε,w;r)=1]≤1/3 for every allowed w when Δ(x,Π_n)>ε. For an AMP the verifier first reveals its entire random tape r, independently of the input; the prover then sends w=w(x,n,ε,r) of length p(n,ε). The verifier has no private or subsequently hidden coins and is deterministic given r. Completeness is Pr_r[∃w:W^x(n,ε,w;r)=1]≥2/3 for every member; soundness is Pr_r[∃w:W^x(n,ε,w;r)=1]≤1/3 for every ε-far input. Thus even a malicious prover may choose a different proof after each public tape. The public tape is not counted as communication in this model. Both protocols have exactly one prover message. No extra promise restricting the set of far tables is allowed. Constants in the MAP bound may depend on ε and the family; the AMP lower-bound constant may depend on W, but ε₀ is fixed once for the family.''',
 question_type='yes_no',answer_criterion='A positive answer specifies one property family and proves both the MAP upper bound and the AMP lower bound in the stated model. A negative answer rules out such a family, for example through a sufficiently strong general simulation; failure of one candidate family is insufficient. A lower bound confined to nonadaptive or proof-oblivious AMP verifiers does not cover the required class. Polylogarithmic losses do not meet the exact O(√n) versus Ω(n) separation.',
 context_blocks=[dict(title='Why revealing coins can hurt',text='A private-coin verifier can choose tests after receiving a fixed proof. In an AMP the prover sees the entire tape and may tailor its answer to the verifier’s choices. The validity conditions therefore quantify over proofs in a different order even though only one prover message is sent.',citation='journal'),dict(title='The quadratic ceiling',text='The source gives a general conversion of an MAP with proof length p and query cost q to an AMP with the same proof length and query cost O((p+1)q). Thus an MAP of total cost c has an AMP of cost O(c²+c). Problem 6.2 asks whether a family can attain the corresponding square-root versus linear separation.',citation='journal'),dict(title='The proved separation goes the other way',text='The paper exhibits a permutation property with an AMP of O(log n) complexity at constant proximity and an MAP lower bound of Ω̃(n^{1/4}). This exponential advantage for AM does not answer the question of a quadratic advantage for MA. The separate results for proof-oblivious verifiers also do not resolve the unrestricted target.',citation='journal'),dict(title='Parameter convention',text='The open-problem display suppresses ε. This card states the constant-proximity reading explicitly: one MAP works for every fixed ε, with constants allowed to depend on ε, while the AMP lower bound already holds at one fixed ε₀. The input parameter counts all table bits, whereas distance counts changed table entries, as in the function model; variable alphabets are not treated as free one-bit answers.',citation='primary')],
 why='Would determine whether keeping verifier randomness private achieves the largest possible advantage in minimally interactive verification of large inputs. The comparison isolates the information revealed to a prover while keeping proof length, input access and error requirements comparable.',
 progress=[dict(date='2018',text='The source proves the opposite exponential separation and records the general quadratic MAP-to-AMP simulation, leaving tightness open.',citation='primary'),dict(date='2021',text='The expanded journal version explicitly repeats the square-root versus linear question as Problem 6.2.',citation='journal')],references=refs,
 status='open',status_note='Read the 2018 source and the complete relevant definitions and open-question section in the journal version published 18 August 2021. Also checked ECCC TR18-083 revision 2, dated 9 May 2018. Subsequent-work searches through 12 September 2026 found no resolution of this unrestricted classical separation; quantum, sample-based and proof-oblivious results concern different models. Searches are not exhaustive.',model_self_contained=True,requires_context=False,
 review_note='Preserves the existence question and its direction. The constant-proximity and function-table conventions are now explicit; proof and query bounds are worst-case bit costs. There is no efficiency requirement on the untrusted prover or verifier’s local computation and no supplied construction strategy.',
 importance=dict(score=c['importance']['score'],method='editorial',reason='A basic limit on the power of private randomness in sublinear verification, testing the tightness of a general simulation between two foundational proof models. Existing score retained.',assessed_on=DATE),
 working_summary=dict(sentences=['An MA proof is fixed before the verifier’s private coins, whereas an AM proof can depend on the complete public random tape.','Both costs count proof bits plus bits read from the input.','The question asks whether some property has an O(√n) MA proof but requires Ω(n) cost from every AM proof at fixed positive proximity.','A general simulation prevents MA from gaining more than a quadratic factor, and the 2021 journal version still asks whether that limit is attained.','The known exponential separation favors AM and does not answer this opposite-direction question.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','journal'])
),notes=notes,checked_sources=[r['url'] for r in refs]+['https://eccc.weizmann.ac.il/report/2018/083/','https://quantum-journal.org/papers/q-2022-10-13-834/','https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ITCS.2022.77'])
