from review import card,save,DATE
i='TCS-6270';_,c=card(i);refs=c['references'];refs[0]['locator']='Introduction, pages 68:1–68:2; Theorems 1 and 6, page 68:4; open-question remark and graph definitions, page 68:5.'
refs += [dict(id='swat2026',title='Cutwidth Versus BFS-Width with Applications to Graph Reconstruction from Distance Queries',authors='Chirag Kaudan; Amir Nayyeri',year=2026,url='https://doi.org/10.4230/LIPIcs.SWAT.2026.24',locator='Section 4.3, pages 24:11–24:12: query model, current general upper bound and a deterministic subquadratic algorithm under bounded cutwidth.'),dict(id='treelength',title='Reconstructing Bounded Treelength Graphs with Linearithmic Shortest Path Distance Queries',authors='Chirag Kaudan; Amir Nayyeri',year=2026,url='https://arxiv.org/abs/2603.10432',pdf_url='https://arxiv.org/pdf/2603.10432',locator='Version 1, 11 March 2026, Theorem 1; bounded degree and a supplied upper bound on treelength are required. A conference version appears in CCCG 2025.')]
save(i,dict(title='Near-linear-query reconstruction of bounded-degree graphs',
formal=r'For every fixed integer \(\Delta\geq2\), is there a randomized exact reconstruction algorithm \(A_{\Delta}\) and constants \(C_{\Delta}>0\), \(k_{\Delta}\geq0\) such that every hidden connected simple unweighted undirected graph \(G\) on \(n\) labeled vertices with maximum degree at most \(\Delta\) can be reconstructed using \[\mathbb E[Q(A_{\Delta},G)]\leq C_{\Delta}\,n(\log(n+2))^{k_{\Delta}}\] queries to an oracle that returns the shortest-path distance between one requested pair of vertices?',
definitions=r'''The algorithm is given the entire vertex set, identified with \(\{1,\ldots,n\}\), and the fixed degree bound. The edge set is hidden. The graph is fixed throughout the execution and is promised connected; no random input distribution is assumed.

A query supplies two named vertices \(u,v\) and receives the integer
\[d_{G}(u,v)=\min\{\text{number of edges on a path from }u\text{ to }v\}.\]
The answer contains no path, intermediate vertices or distances to other destinations. An edge has distance one. Computing all distances from one vertex by querying this oracle costs \(n-1\) queries, rather than one query.

The algorithm may choose each new query using all previous answers and its private random bits. Its output must be exactly the set \(E(G)\) on the given vertex labels. Isomorphism type, an approximate metric, a graph consistent with only some answers, or a sample of edges is insufficient.

The randomized convention is Las Vegas: the output is correct whenever returned, and the procedure terminates with probability one. The query bound is an expectation over its internal randomness for each fixed allowed graph. This is not average-case complexity over randomly generated graphs. Deterministic algorithms also qualify.

The constants may depend on the fixed \(\Delta\), but not on \(n\) or the particular graph. The displayed bound specifies the meaning of \(\widetilde O(n)\): a linear number of vertices times a fixed power of a logarithm. A bound \(n^{1+\varepsilon}\) for a fixed positive \(\varepsilon\) does not meet it.

Only calls to the distance oracle are charged in this query-complexity question. The algorithm must be an effective finite procedure, but no separate polynomial bound on local computation or memory is imposed. No restriction is placed on the number of adaptive rounds. There is no additional promise of bounded treewidth, treelength, cutwidth or a planar graph.

Simplicity matters because distances cannot reveal edge multiplicities or loops. Connectedness is also part of the source model: allowing a graph with just one hidden edge and otherwise isolated vertices would already force a quadratic search for that edge.''',
question_type='yes_no',answer_criterion='Give algorithms with the displayed expected-query bound for every fixed degree bound, and prove exact reconstruction on every promised graph, or show that such bounds are impossible for at least one fixed degree bound. A lower bound against the source’s particular algorithm alone does not refute the general question.',
context_blocks=[
dict(title='A general upper bound still has a polynomial gap',text=r'The original source compares its algorithm with the earlier \(\widetilde O_{\Delta}(n^{3/2})\)-expected-query reconstruction algorithm. The 2026 SWAT paper still identifies this as the best known general bound for connected bounded-degree graphs.',citation='swat2026'),
dict(title='The source obtains the target on random regular graphs',text=r'The source’s Theorem 1 gives \(\widetilde O(n)\) expected distance queries for uniformly random regular graphs of fixed degree. Its general-graph guarantee is weaker. The random-graph theorem averages over a restricted input distribution and therefore does not establish the per-graph bound asked here.',citation='primary'),
dict(title='The source algorithm itself cannot solve the full question',text='The concluding remark gives complete binary trees as a family requiring a superlinear number of queries for the particular Simple algorithm. That limitation does not apply to every possible reconstruction algorithm.',citation='primary'),
dict(title='Recent near-linear results require additional structure',text=r'Kaudan and Nayyeri give deterministic \(O_{\Delta,\tau}(n\log n)\) reconstruction for graphs with bounded treelength and a supplied bound \(\tau\). Treelength means the minimum, over tree decompositions, of the largest graph-metric distance between vertices in one bag. The 2026 SWAT result instead gives deterministic subquadratic reconstruction for bounded cutwidth. Neither hypothesis follows from bounded degree alone.',citation='treelength')],
why='The problem asks how much pairwise distance information is inherently needed to discover an entire sparse network. A near-linear worst-input guarantee would show that distances allow almost output-sized exact reconstruction despite hiding every edge, without relying on randomness in the network itself.',
progress=[dict(date='2021',text='The source reaches near-linear expected queries on random regular graphs and retains the general bounded-degree question.',citation='primary'),dict(date='2026-03-11',text='A full preprint gives deterministic linearithmic queries with a bounded-treelength promise.',citation='treelength'),dict(date='2026',text='The SWAT paper adds deterministic subquadratic reconstruction for bounded cutwidth and restates the general three-halves-exponent upper bound.',citation='swat2026')],
references=refs,status='open',status_note='Read the original complete query model, theorem guarantees and open-question remark. Checked the March 2026 treelength theorem and the full SWAT 2026 graph-reconstruction section. Searches through 12 September 2026 found no near-linear expected distance-query algorithm for every connected graph of fixed maximum degree. The source’s expectation convention is retained as exact randomized reconstruction, not a random-input or stronger all-distances model.',
model_self_contained=True,requires_context=False,review_note='Defined visible labels, the fixed hidden simple connected graph, pairwise distance-only oracle, exact edge output, Las Vegas expectation and the polylogarithmic overhead. Separated query complexity from local runtime and structured graph special cases.',
importance=dict(score=c['importance']['score'],method='editorial',reason='A natural information-access boundary for exact sparse-network reconstruction, with a long-standing gap between nearly linear special-case bounds and the general three-halves exponent. Existing score retained.',assessed_on=DATE),
working_summary=dict(sentences=['All vertices of a connected bounded-degree graph are known, but its edges are hidden.','One query returns only the shortest-path distance between two named vertices.','The goal is to recover every edge using a linear number of vertices times polylogarithmically many expected queries.','The expectation is over the algorithm’s randomness for each fixed graph, and the returned answer must be exact.','Near-linear results for random regular or bounded-treelength graphs do not cover every graph in the question.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','swat2026','treelength'])),
notes=['Recovered the connected bounded-degree pairwise-distance oracle model.','Specified exact reconstruction and expected query complexity on every fixed graph.','Defined near-linear precision without imposing an unsupported local runtime target.','Checked 2026 general-bound summaries and distinguished structured special cases.'],checked_sources=[r['url'] for r in refs])
