"""Individually authored continuation of the interrupted review."""
from review import card, save, DATE

def block(title, text, citation='primary'):
    return dict(title=title, text=text, citation=citation)

def summary(sentences, refs=('primary',)):
    return dict(sentences=sentences, basis='saved_sources', source_basis='source-text', written_on=DATE, source_refs=list(refs))

def unfinished(issue):
    return dict(reviewed_on=DATE, status='needs_specification', notes=['Recovered the source target and made its remaining choices explicit.'], remaining_issue=issue)

def version(title, authors, year, url, locator):
    return dict(id='version_record', title=title, authors=authors, year=year, url=url, locator=locator)

i='TCS-1562'; _,c=card(i); refs=c['references']
refs[0]['locator']='MFCS 2025, Question 32 and the preceding paragraph on p. 25:16; read alongside Theorem 31. The coefficients are powers 2^c with binary-encoded exponents. These are ordinary ordered rational inequalities, not an order on a p-adic field.'
refs.append(version('Polynomial-time Tractable Problems over the p-adic Numbers — version record','Manuel Bodirsky, Arno Fehm',2025,'https://arxiv.org/abs/2504.13536','Abstract and version record checked on 12 September 2026; subsequent searches did not locate a resolution of Question 32.'))
save(i,dict(
 title='Polynomial-time feasibility of linear inequalities with succinct powers of two',
 formal='Is there a deterministic algorithm deciding feasibility of finite systems of weak linear inequalities over the rationals in time polynomial in their succinct input length, when coefficients are powers 2^c and each integer exponent c is given in binary? A power is represented by its exponent, rather than by writing its numerator or denominator in full. The source formulation leaves sign and constant-term encoding implicit; those conventions must be fixed as described below before final benchmark certification.',
 definitions='A weak inequality permits equality. Variables range over Q with its usual order; feasibility is the existence of one rational assignment satisfying every inequality. For a finite rational linear system, feasibility over Q is equivalent to feasibility over R. A power 2^c is rational for every c in Z. The binary description of c has length O(log(2+|c|)), while writing 2^c as an ordinary binary rational can require Θ(|c|) bits. A nontrivial signed formulation allows such terms on both sides of an inequality, equivalently signed powers and zero entries after rearrangement, with similarly encoded constants. The source question does not spell out whether sums of succinct powers may appear as one coefficient or how constants are represented; these are representation choices, not p-adic ordering conventions.',
 question_type='yes_no',
 answer_criterion='For the explicitly fixed coefficient/sign/constant encoding, prove that a deterministic polynomial-time feasibility algorithm exists, or prove that none exists. Runtime is measured in the succinct description, including binary exponents, not in the exponentially longer expanded linear program. A conditional hardness theorem must retain its hypothesis and does not unconditionally disprove polynomial-time solvability.',
 context_blocks=[block('Why ordinary linear programming does not immediately settle it','A coefficient 2^(2^r) needs only r+1 bits for its exponent, but exponentially many bits if expanded. Thus a polynomial-time algorithm for conventionally encoded rational linear programming need not run in polynomial time on this input. The challenge is compressed numerical representation, despite the fact that every constraint is linear.'),block('The role of p-adic numbers','The paper solves several systems combining rational linear constraints with restrictions on p-adic valuations. Its final question concerns ordinary weak linear inequalities with compactly represented powers of two. The paper states that an affirmative answer would also imply a polynomial-time algorithm for mean-payoff games; it does not prove equivalence.')],
 why='Connects a basic feasibility problem with succinct arithmetic and the unresolved complexity of mean-payoff games. It isolates the cost of numerical representation from nonlinear algebra or p-adic satisfiability.',
 status='source_open',status_note='Question 32 is open in the MFCS 2025 source. Source, version record and targeted subsequent searches checked on 12 September 2026; no matching resolution was located. Encoding conventions remain to be finalized.',
 progress=[dict(date='2025',text='The paper proves polynomial-time results for several valuation-constrained linear systems and identifies succinct-power linear feasibility as a further open question.',citation='primary')],
 references=refs, review_note='Restored the missing coefficient form and corrected the misleading suggestion that this is ordered p-adic linear programming. Explained succinct bit complexity without silently certifying omitted encoding conventions.',
 statement_review=unfinished('Question 32 does not explicitly fix signs, zero/constant terms or whether a coefficient may be a sum of succinct powers. Confirm the intended nontrivial signed rational linear-system encoding against the cited reduction before certifying one exact benchmark language.'),
 working_summary=summary(['The question concerns ordinary linear inequalities with very large or very small coefficients.','Each coefficient is specified by a binary exponent of two, which may be exponentially shorter than its usual rational representation.','The goal is polynomial-time feasibility in this compressed input length.','The source relates a positive answer to polynomial-time mean-payoff games.','The p-adic setting motivates the question, but the inequalities use the usual rational order and still need explicit encoding conventions.'])
),notes=['Restored powers of two and binary exponent encoding.','Distinguished rational order from p-adic valuations.','Explained input-size and remaining representation choices.'],checked_sources=[r['url'] for r in refs],state='improved_unfinished')

i='TCS-1566';_,c=card(i);refs=c['references'];refs[0]['locator']='Section 6, third open problem, p. 38:21; square-root placement checked in the PDF. The source asks about existence, not an explicit construction, below sqrt(n), and does not fix a complete degree/error/entropy tradeoff.'
refs.append(version('Low-Degree Polynomials Are Good Extractors — version record','Omar Alrabiah, Jesse Goodman, Jonathan Mosheiff, João Ribeiro',2024,'https://arxiv.org/abs/2405.10297','Abstract and version record checked on 12 September 2026, together with a targeted search for later low-degree two-source results.'))
save(i,dict(title='Low-degree two-source extraction below square-root min-entropy',
 formal='Do there exist low-degree, low-error two-source extractors for two independent n-bit sources whose individual min-entropy is below sqrt(n)? The target is existence of a single polynomial working for every eligible pair of sources. The source leaves the precise asymptotic degree bound, error bound and meaning of a below-sqrt(n) improvement unspecified.',
 definitions='For an n-bit random variable X, H∞(X)=−log₂(max_x Pr[X=x]). A one-bit two-source extractor with entropy threshold k and error ε is a function F:{0,1}^n×{0,1}^n→{0,1} for which |Pr[F(X,Y)=1]−1/2|≤ε for every independent X,Y with H∞(X),H∞(Y)≥k. Low degree refers to the total degree of the unique multilinear polynomial for F over F₂ in its 2n input bits, not to Fourier degree over the reals. The polynomial must be fixed before X and Y are chosen. Existence need not provide a uniform efficient construction.',
 question_type='yes_no',answer_criterion='After fixing degree d(n), error ε(n)<1/2 and entropy k(n) below the square-root threshold, prove existence for all sufficiently large n, or prove nonexistence with matching quantifiers. A polynomial working for only one pair of sources or a disperser that merely takes both output values does not meet an extractor guarantee. Until the asymptotic tradeoff is selected, this source question is not one complete binary benchmark.',
 context_blocks=[block('Two independent imperfect random inputs','Each input can be very far from uniform; min-entropy only forbids any one string from carrying too much probability. Independence is essential. The extractor must output an almost unbiased bit for every pair obeying the entropy promise, including pairs selected after the polynomial is known.'),block('The square-root barrier','The paper reports non-explicit degree-at-most-four extractors for linear min-entropy using approximate duality. The stated sqrt(n) obstruction concerns that approach, not a general impossibility theorem for every low-degree extractor. Recovering this distinction prevents the imported broken formula from turning a research question into a false lower bound.')],
 why='Tests how much randomness can be recovered by algebraically simple maps, beyond the entropy regime supported by an existing existence argument.',status='source_open',status_note='Open direction in Section 6 of the 2025 proceedings paper. Checked with the version record and later-result searches on 12 September 2026; no matching resolution located. Precise tradeoff remains unspecified.',references=refs,
 progress=[dict(date='2025',text='The source gives low-degree extraction results and records degree-at-most-four two-source extractors for linear min-entropy, then asks whether low-error extraction can go below sqrt(n).',citation='primary')],
 review_note='Repaired the square-root threshold, distinguished existence from construction and extraction from dispersion, and preserved the unspecified quantitative target.',
 statement_review=unfinished('Fix the asymptotic degree, error and entropy functions. Constant degree versus growing degree, constant versus vanishing error, and k(n)=o(sqrt(n)) versus a smaller constant multiple of sqrt(n) are not interchangeable.'),
 working_summary=summary(['Two independent weak random strings must yield an almost unbiased output bit.','The combining function is restricted to a low-degree polynomial over F₂.','The question asks for entropy requirements below sqrt(n).','Existing approximate-duality arguments supply a linear-entropy result but have their own square-root barrier.','The intended degree, error and asymptotic improvement still need to be fixed.'])
),notes=['Restored sqrt(n) and the polynomial model.','Separated an approach-specific barrier from general impossibility.','Retained the missing quantitative tradeoff explicitly.'],checked_sources=[r['url']for r in refs],state='improved_unfinished')

i='TCS-1610';_,c=card(i);refs=c['references'];refs[0]['locator']='Conjecture 1.8 and Lemma 1.9 on p. 124:8, Figure 4 visually inspected on p. 124:9, and hypergraph definitions on p. 124:12. H_triangle has six vertices and four triples, not three graph edges.'
refs.append(version('Subgraph Counting in Subquadratic Time for Bounded Degeneracy Graphs — version record','Daniel Paul-Pena, C. Seshadhri',2024,'https://arxiv.org/abs/2410.08376','Abstract and version record checked on 12 September 2026; searched later hypergraph-counting work without locating a resolution of Conjecture 1.8.'))
save(i,dict(title='A quadratic barrier for counting the four-edge hypergraph H△',
 formal='For every constant ε>0, is there no deterministic algorithm that exactly counts non-induced copies of the fixed hypergraph H△ in an arbitrary simple 3-uniform hypergraph G with m hyperedges in worst-case time O(m^(2−ε))? H△ has vertices {a,b,c,d,e,f} and hyperedges {{a,b,c},{c,d,e},{e,f,a},{f,b,d}}. This is the source’s proposed fine-grained hardness conjecture, rather than a consequence already established under another named hypothesis.',
 definitions='A simple 3-uniform hypergraph is a finite vertex set with distinct unordered triples as hyperedges. Use the explicit list of triples on binary-labelled vertices, discard isolated vertices, and relabel so n≤3m. Count subhypergraphs isomorphic to H△, without requiring that other triples on the same six vertices be absent. Equivalently, count injective maps from its labelled six vertices preserving all four triples and divide by the fixed automorphism-group size. The time convention is the usual word-RAM with O(log(m+2))-bit words; constant-size multiword exact counts fit because H△ is fixed. The unrestricted host hypergraph in this conjecture is distinct from the bounded-degeneracy graph used in its application.',
 question_type='yes_no',answer_criterion='Prove the stated absence of an O(m^(2−ε)) exact counting algorithm for every fixed ε>0, or refute it by giving such an algorithm for some fixed ε>0. Counting ordinary graph triangles, listing occurrences, or handling only a restricted host family does not settle this target. Any conditional lower bound must state its extra hypothesis.',
 context_blocks=[block('The pattern hidden by the imported notation','The six-vertex pattern consists of four triples. Every two triples share one vertex, and no vertex belongs to three triples. Extra host edges are allowed because the count is non-induced. For instance, a host consisting of exactly the four displayed triples contains one unlabelled copy.'),block('Why a hypergraph question appears in a graph paper','The source relates this pattern to a ten-vertex graph by replacing triples with incidence stars. Its conjecture would rule out truly subquadratic algorithms for counting all ten-vertex patterns in bounded-degeneracy graphs. The paper explicitly leaves connections to other fine-grained assumptions open.')],
 why='Could identify the first quadratic counting obstruction in a classification of small patterns on sparse graphs. It separates exact counting from listing and makes the source’s proposed hardness assumption explicit.',
 status='source_open',status_note='Conjecture 1.8 is open in ICALP 2025. Figure, statement and reduction consequence checked with the version record and subsequent searches on 12 September 2026; no resolution located. The explicit deterministic word-RAM convention here records the algorithmic interpretation of the source’s unqualified running-time claim.',
 progress=[dict(date='2025',text='The source formulates this hypergraph-counting conjecture and proves its conditional consequence for ten-vertex patterns in bounded-degeneracy graphs.',citation='primary')],references=refs,review_note='Reconstructed all four triples from Figure 4 and separated the hypergraph conjecture from its sparse-graph consequence. Recorded input, non-induced counting and computational conventions.',
 working_summary=summary(['H△ is a six-vertex hypergraph with four triples, every pair meeting in one vertex.','The task is to count all its non-induced occurrences in an arbitrary host hypergraph.','The conjecture excludes any polynomial improvement over quadratic time in the number of host hyperedges.','The source uses this conjecture to obtain a barrier for ten-vertex graph patterns on bounded-degeneracy graphs.','It is a new proposed hardness assumption, not an already proved consequence of a familiar one.'])
),notes=['Defined the six vertices and four hyperedges from the source figure.','Separated hypergraph hosts, non-induced counting and bounded-degeneracy consequences.','Recorded exact counting and computational conventions.'],checked_sources=[r['url']for r in refs])

i='TCS-1693';_,c=card(i);refs=c['references'];refs[0]['locator']='Section 2.2 and footnote 10 on paper p. 9, with the functional-inequality discussion. The passage concerns an exact temperature threshold for useful PI/LSI bounds; it does not claim nonexistence of finite-dimensional inequalities.'
refs.append(dict(id='weak2026',title='Weak Poincaré Inequalities via Approximate Stochastic Localization: Application to Sampling the Sherrington-Kirkpatrick Model',authors='Ewan Davies, Holden Lee, Juspreet Singh Sandhu, Jonathan Shi',year=2026,url='https://arxiv.org/abs/2607.08160',locator='July 2026 preprint abstract checked on 12 September 2026. Claims a weak Poincaré inequality and warm-start Glauber sampling for β<1/2 in its normalization; this is not a sharp strong PI/LSI threshold.'))
save(i,dict(title='Sharp temperature thresholds for functional inequalities in the SK model',
 formal='Determine the temperature threshold at which quantitatively useful Poincaré or logarithmic Sobolev bounds for Glauber dynamics of the Sherrington–Kirkpatrick (SK) model cease to hold. The source mentions this as an unresolved threshold question but does not specify the allowed growth of the constants, disorder probability, field or normalization needed to define one exact threshold.',
 definitions='One standard zero-field normalization has spins σ∈{−1,+1}^n, independent standard Gaussian couplings g_ij for i<j, Hamiltonian H_g(σ)=n^(−1/2)Σ_(i<j)g_ij σ_iσ_j and Gibbs law μ_(β,g)(σ)=exp(βH_g(σ))/Z_(β,g), where β≥0 is inverse temperature. This normalization is explanatory and does not identify numerical thresholds across papers. Continuous-time heat-bath Glauber dynamics resamples each spin at rate one from its conditional Gibbs law. For its generator L, let E(f,f)=−E_μ[fLf]. A Poincaré bound is Var_μ(f)≤C_P E(f,f); a log-Sobolev bound is Ent_μ(f²)≤2C_LS E(f,f), where Ent_μ(h)=E_μ[h log(h/E_μ h)]. At finite n and finite β all spin configurations have positive mass and the chain is irreducible, so some finite constants exist. The meaningful question is how they grow with n and with high probability over g.',
 question_type='exact_value',answer_criterion='Specify the spin/field normalization, update-rate convention, disorder probability and acceptable growth of C_P or C_LS, then determine the threshold with bounds on both sides. A finite-n existence argument, a change of time normalization or a weak inequality with an error term does not by itself identify the intended sharp threshold.',
 context_blocks=[block('Relaxation rather than mere existence','A Poincaré inequality controls variance decay; a logarithmic Sobolev inequality controls entropy relaxation. For a finite irreducible spin system neither is simply absent. The hard issue is whether their constants stay small enough to support useful sampling as the number of spins grows.'),block('Later progress has a different guarantee','A July 2026 preprint reports a weak Poincaré inequality for SK and efficient Glauber sampling from a warm start when β<1/2 in its convention. Weak inequalities allow an extra error term and warm starts restrict initialization. This is relevant progress, but it does not supply the unspecified exact threshold for strong PI/LSI bounds.','weak2026')],
 why='Relates the statistical physics of a disordered spin system to the efficiency of local sampling. A sharp threshold would distinguish thermodynamic temperature regimes by a precise algorithmic relaxation criterion.',
 status='uncertain',status_note='The 2025 footnote is a broad threshold question. Checked with the July 2026 preprint abstract and later searches on 12 September 2026; the original numerical and asymptotic conventions remain unspecified.',
 progress=[dict(date='2026-07-09',text='A preprint claims weak Poincaré bounds and warm-start Glauber sampling for β<1/2 in its SK normalization. This is distinct from a complete sharp strong PI/LSI threshold.',citation='weak2026')],references=refs,review_note='Recovered the threshold interpretation and explained why finite-n existence alone is trivial. Recorded newer weak-inequality progress without treating it as a complete resolution.',
 statement_review=unfinished('Fix the exact SK normalization and external field, PI versus LSI, rate-one-per-site versus one-total-update dynamics, disorder probability and required n-dependence of the constant. Without those choices there is no unique numerical threshold to determine.'),
 working_summary=summary(['The SK model assigns a random interaction to every pair of spins.','The question concerns temperature thresholds for useful variance or entropy relaxation bounds for local spin updates.','Some finite inequality always holds in each finite irreducible instance.','The unresolved issue must therefore specify how the constants may grow with system size.','Recent weak Poincaré progress concerns warm-start sampling and does not by itself settle a sharp strong-inequality threshold.'],('primary','weak2026'))
),notes=['Recovered the exact-threshold intent of footnote 10.','Defined functional inequalities and explained finite-state existence.','Distinguished recent weak-inequality progress from the missing sharp specification.'],checked_sources=[r['url']for r in refs],state='improved_unfinished')

i='TCS-1699';_,c=card(i);refs=c['references'];refs[0]['locator']='Definition 1, Theorem 2 and Section 8 discussion on p. 11:16. The first open question asks for hardness under any complexity assumption; it does not select the ordinary random-graph planted-clique conjecture.'
refs.append(version('On Finding Randomly Planted Cliques in Arbitrary Graphs — version record',"Francesco Agrimonti, Marco Bressan, Tommaso d’Orsi",2025,'https://arxiv.org/abs/2505.06725','Abstract and version record checked on 12 September 2026; targeted later-result searches did not locate a corresponding hardness theorem in this planting model.'))
save(i,dict(title='Conditional hardness of finding a clique randomly planted in an arbitrary graph',
 formal='Can one prove a nontrivial computational hardness result, under a stated complexity assumption, for finding large cliques after a clique is planted at a uniformly random location in an arbitrary background graph? The source asks for any such hardness result, leaving the hypothesis and the precise recovery/approximation guarantee open rather than specifying one fixed conditional proposition.',
 definitions='Choose an arbitrary n-vertex simple graph G before the planting randomness. For k≤n, choose a uniformly random k-element vertex subset S independently of G and output Ĝ with E(Ĝ)=E(G)∪binom(S,2). The algorithm sees Ĝ, not S or the background graph. The paper emphasizes k=cn for fixed c∈(0,1). Finding any large clique in Ĝ is different from recovering S exactly, since G may already contain cliques. A guarantee must quantify over every allowed G, planting randomness and any algorithmic randomness. An adversary choosing G after observing S defines a different problem.',
 question_type='yes_no',answer_criterion='Specify a substantive complexity hypothesis, parameter regime, output size or recovery target, and success probability, then prove a corresponding computational obstruction in precisely this random-location/arbitrary-background model. The original “any hardness result” request still needs those choices to become a fixed benchmark; assuming the desired obstruction itself or transferring hardness from a different planted model does not resolve it.',
 context_blocks=[block('Only the location is random','Unlike the usual Erdős–Rényi planted-clique model, the background need not be random. Unlike an adaptive adversarial construction, it cannot depend on the chosen planted set. These distinctions determine which algorithmic and hardness results apply.'),block('Existing algorithms constrain a possible lower bound','For fixed planting fraction and a background maximum degree bounded away from n, the source gives an almost-linear-time algorithm returning a clique of linear size with high probability. Its worst-case UGC comparison is not a hardness theorem for random planting. Any new lower bound must respect the actual positive guarantee.')],
 why='Asks how much algorithmic power comes from randomly locating a hidden structure when the rest of the instance is arbitrary. A matching obstruction would clarify the gap between worst-case and random-input clique problems.',
 status='source_open',status_note='The first final-section question remains a broad hardness program in the 2025 source. Source, version record and subsequent searches checked on 12 September 2026; no matching resolution located.',
 progress=[dict(date='2025',text='The source proves an almost-linear-time linear-clique guarantee under a maximum-degree promise and asks separately for hardness under a complexity assumption.',citation='primary')],references=refs,review_note='Recovered planting order, the arbitrary background and the distinction between finding any large clique and identifying the planted one. Preserved the unspecified assumption and hardness target.',
 statement_review=unfinished('Fix the complexity assumption, k(n), background promises, required clique size versus exact planted-set recovery, algorithm class and success probability. The source’s invitation to establish any hardness result does not uniquely select these.'),
 working_summary=summary(['An adversary first chooses a graph, then a clique is added on a uniformly random subset of vertices.','The algorithm sees only the resulting graph.','The question seeks a hardness theorem under a suitable complexity hypothesis.','A known positive result already finds a linear-sized clique under a maximum-degree promise.','The exact hypothesis, parameter regime and required output remain to be specified.'])
),notes=['Recovered the order of randomness and adversarial choices.','Separated clique finding from exact recovery.','Recorded the known positive regime and unresolved hardness specification.'],checked_sources=[r['url']for r in refs],state='improved_unfinished')

i='TCS-1714';_,c=card(i);refs=c['references'];refs[0]['locator']='Sections 2.1–2.2, Definitions 4–5, Table 1 and the main open question in Section 6 on p. 31:19. Target is an arbitrary stable matching in a unimodular hypergraph, with strict preferences and capacity one.'
refs.append(dict(id='network2026',title='Polynomial-time Stable Matching in Network Hypergraphs',authors='Karthekeyan Chandrasekaran, Krishna Kalathur',year=2026,url='https://arxiv.org/abs/2608.24728',locator='Preprint v1, 25 August 2026. Introduction, Theorem 1.1, model and family-containment discussion read on 12 September 2026. The network subclass is addressed; general unimodular hypergraphs remain outside the theorem.'))
save(i,dict(title='Polynomial-time stable matching in unimodular hypergraphs',
 formal='Does there exist a deterministic algorithm that, given any finite hypergraph H=(V,E) whose vertex–hyperedge incidence matrix is totally unimodular and a strict preference ordering at each vertex over its incident hyperedges, finds a stable matching in time polynomial in the explicit input length? A matching is a collection of pairwise disjoint hyperedges. Stability means that every unchosen hyperedge e contains some vertex v already matched to an edge it strictly prefers to e.',
 definitions='Hyperedges are explicitly listed nonempty subsets of V. The incidence matrix A has A_(v,e)=1 if v∈e and 0 otherwise; it is totally unimodular when every square submatrix has determinant in {−1,0,1}. Each vertex supplies a strict total order on its incident edges and prefers any such edge to remaining unmatched. With M a matching, an edge e∉M blocks M exactly when every v∈e is unmatched or prefers e to its unique incident edge in M. The promise is total unimodularity, with no bound on hyperedge size; all vertex capacities are one. Input length includes every incidence and preference-list entry. The output is any stable M, without a cardinality or weight objective.',
 question_type='yes_no',answer_criterion='Give a polynomial-time algorithm and prove that its output is stable for every promised instance, or prove that no such deterministic algorithm exists. An NP/PPAD hardness result must retain its complexity assumption. Existence alone, fractional matchings, maximum-weight optimization, or an algorithm for a proper subclass does not settle this search question.',
 context_blocks=[block('Coalitions rather than pairs','A hyperedge represents a group that could cooperate. Selected groups cannot share members. Stability forbids an unselected group whose members would all prefer forming it to their current situation. The input includes each participant’s ranking, so merely finding disjoint groups is insufficient.'),block('Existence and computation','The source explains why total unimodularity together with a classical stable-fractional existence theorem guarantees an integral stable matching. It does not give a general polynomial running-time bound. Hardness of maximizing weight among stable matchings is a different question from finding any stable one.'),block('A newer special-case result','An August 2026 preprint gives a polynomial-time algorithm for network hypergraphs. In that class the ground elements are arcs of an oriented tree and each hyperedge is a directed tree path. Network hypergraphs are a subclass of unimodular hypergraphs, so this narrows the open frontier without resolving the general target.','network2026')],
 why='Tests whether a strong integrality promise can turn guaranteed coalition stability into an efficient algorithm. It extends the computational perspective of classical stable matching while keeping the target independent of optimization over stable outcomes.',
 status='source_open',status_note='General unimodular stable matching is open in the ICALP 2025 source. Checked against the August 2026 network-hypergraph preprint and subsequent searches on 12 September 2026; no general resolution located. The new special-case theorem is recorded as a preprint result, without an independent proof audit.',
 progress=[dict(date='2025',text='The source treats structured subclasses and leaves arbitrary unimodular hypergraphs open.',citation='primary'),dict(date='2026-08-25',text='Chandrasekaran and Kalathur report a polynomial-time algorithm for the network-hypergraph subclass.',citation='network2026')],references=refs,review_note='Restored the complete search question, total unimodularity and blocking condition, and distinguished the newly addressed network subclass from the full promise.',
 working_summary=summary(['Vertices are participants and hyperedges are feasible coalitions.','Each participant strictly ranks the coalitions containing them.','A stable matching leaves no unchosen coalition preferred by all its members.','Total unimodularity guarantees existence, but the question asks for an efficient construction.','An August 2026 preprint addresses network hypergraphs while the full unimodular target remains open in the checked sources.'],('primary','network2026'))
),notes=['Defined the full unimodular promise and strict-preference stability.','Separated search from weighted optimization and fractional existence.','Added the August 2026 network-subclass result with its precise scope.'],checked_sources=[r['url']for r in refs])
