from review import card,save,DATE
i='TCS-6934';_,c=card(i);refs=c['references'];refs[0]['locator']='Section 1, page 2, asks whether exhaustive-search dependence can be proved necessary on a robust computation model and notes the lack of unrestricted superlinear bounds; page 3 separately fixes a word-RAM for the subsequent fine-grained discussion.'
refs += [
dict(id='tradeoffs',title='Time-space lower bounds for satisfiability',authors='Lance Fortnow; Richard Lipton; Dieter van Melkebeek; Anastasios Viglas',year=2005,url='https://doi.org/10.1145/1101821.1101822',locator='Journal of the ACM 52(6), pages 835–865, 1 November 2005. Checked publisher abstract: its deterministic random-access lower bounds impose a simultaneous workspace restriction.'),
dict(id='simulation',title='Simulating Time with Square-Root Space',authors='Ryan Williams',year=2026,url='https://doi.org/10.1145/3798104',pdf_url='https://arxiv.org/pdf/2502.17779v1',locator='STOC 2025 predecessor DOI 10.1145/3717823.3718225; Journal of the ACM 73(3), online 16 June 2026. Full February 2025 author report: Theorem 1.1, Corollaries 1.2–1.3, Remark 1.6 and Section 5. Journal abstract/metadata checked; publisher full journal text unavailable.')]
issue='The source paragraph identifies a broad lower-bound program, not one complete benchmark assertion. Choose CNF-SAT versus Circuit-SAT and the encoding/size measure, a particular robust machine model and instruction set, deterministic versus randomized computation, and whether the target excludes linear time, proves a specified superlinear bound, or establishes exponential dependence on the number of variables. These choices cannot be inferred from polynomial-time model equivalence or merged into a single conjunction.'
notes=['Recovered the full SAT paragraph and distinguished its exponential ambition from the separate linear-time milestone.','Defined SAT variants, bit length, variable count and unconditional versus conditional lower bounds.','Explained why a workspace restriction changes the claim.','Checked the 2025 simulation result and its 2026 journal publication without transferring its lower bound to SAT or arbitrary RAMs.']
save(i,dict(
title='Unconditional SAT time lower bounds',
formal='Can one prove an unconditional time lower bound for Boolean satisfiability on a general computation model, without an additional workspace restriction? The source discusses both proving an exponential dependence on the number of variables and the much smaller milestone of ruling out linear time. It does not select one machine model, representation and quantitative endpoint for this card. The recovered scope is explained below; the entry remains a formulation requiring specification.',
definitions=r'''A Boolean assignment gives each variable a value in \(\{0,1\}\). A literal is a variable or its negation. A conjunctive normal form formula is an AND of clauses, each clause being an OR of literals. CNF-SAT asks whether there is an assignment satisfying every clause. General CNF-SAT permits unbounded clause width; \(k\)-CNF-SAT restricts every clause to at most the fixed integer \(k\) literals.

Circuit-SAT instead receives a finite acyclic Boolean circuit with input variables, AND, OR and NOT gates, and a designated output gate, and asks whether some input assignment makes that output 1. These problems are polynomially interreducible, but an arbitrary polynomial increase in input length cannot be ignored in a linear-time or precise exponential-time claim.

The number \(n\) of variables differs from the full input bit length \(L\). An explicit CNF encoding includes every literal occurrence, its variable index, sign and clause separators. A circuit encoding includes gate descriptions and wire endpoints. A bound in \(n\) alone must specify how formula or circuit size may grow with \(n\), or separately account for input-reading and polynomial factors in \(L\). Statements about linear time in \(L\), linear time in the number of machine words, and linear time in \(n\) are not interchangeable.

A deterministic multitape Turing machine has a fixed finite program, alphabet and number of tapes; each step accesses a constant number of tape cells and moves each head by at most one cell. A random-access model instead permits addressed memory access. A word-RAM typically stores words of \(O(\log L)\) bits and charges unit cost for a specified list of arithmetic, Boolean, shift and memory operations. The instruction list, word length and treatment of larger integers affect fine time bounds. The source’s phrase “robust model” does not itself fix these details.

A worst-case time bound requires one uniform algorithm to halt and give the correct satisfiability answer on every valid input within that bound. For a randomized version, correctness probability and whether time is worst-case or expected must additionally be fixed. No oracle or nonuniform advice is implicit.

For a selected encoding and model, excluding \(O(L)\) time means that no constant \(C\) and correct algorithm have running time at most \(CL\) on every sufficiently long valid input. A specified lower bound such as \(\Omega(L^{1+\varepsilon})\) for some fixed \(\varepsilon>0\) is stronger than merely excluding linear time. Likewise, excluding \(2^{o(n)}\operatorname{poly}(L)\) time and excluding every \((2-\varepsilon)^{n}\operatorname{poly}(L)\) algorithm are different exponential claims. These are examples of possible endpoints, not a replacement conjecture selected by this review.

An unconditional lower bound uses no assumption such as \(\mathrm P\ne\mathrm{NP}\), the Exponential Time Hypothesis or the Strong Exponential Time Hypothesis. It may still be a theorem only about a restricted class of algorithms. In particular, a time-space tradeoff rules out satisfying a time bound and a separate workspace bound simultaneously. It does not rule out an algorithm with the same running time that uses more workspace. “Unrestricted space” here means no extra workspace promise beyond what the running time itself permits.''',
question_type='yes_no',answer_criterion='First specify one SAT variant, explicit encoding and input measure, computational model, randomness convention and quantitative time claim. Then give a proof of that claim without a conjectural complexity assumption, or a matching algorithm that refutes it. A restricted-space theorem, a lower bound for another complete problem, or a conditional fine-grained reduction does not meet an unrestricted SAT time target.',
context_blocks=[
dict(title='The source names a research program and two different scales',text='The introduction asks whether the exponential dependence of exhaustive search can be proved inherent on a robust model. It then emphasizes that even excluding linear-time SAT remains beyond the unrestricted lower bounds discussed there. Treating both remarks as one fully quantified conjecture would conflate distinct targets.',citation='primary'),
dict(title='Resource restrictions are part of existing theorems',text='The time-space literature proves lower bounds for general random-access machines while limiting their workspace. Fortnow, Lipton, van Melkebeek and Viglas explicitly require simultaneous time and space bounds in their theorem. The significance of using a general machine does not remove the workspace condition.',citation='tradeoffs'),
dict(title='A recent time lower bound concerns other languages',text=r'Williams’s simulation theorem places time \(t\) on multitape Turing machines inside space \(O(\sqrt{t\log t})\). Its consequences include languages decidable in linear space that require almost quadratic time on that model. Corollary 1.3 identifies a space-bounded machine-acceptance language; it does not identify SAT as that hard language.',citation='simulation'),
dict(title='The recent model distinction also matters',text='The checked simulation report explicitly leaves extension to arbitrary random-access computation unresolved, while discussing an oblivious-access special case. The 2026 journal abstract retains the multitape Turing-machine result. Thus it neither supplies a general RAM lower bound nor fills the missing SAT-specific target in this card.',citation='simulation')],
why='An unconditional lower bound for satisfiability would establish a limitation of general computation for a central natural problem, beyond limitations of a solver family or consequences of a conjecture. Even a modest bound is significant when it applies without an extra memory restriction. Its precise computational model is part of the mathematical achievement.',
progress=[dict(date='2005',text='Published time-space lower bounds for SAT apply to general random-access machines subject to explicit workspace bounds.',citation='tradeoffs'),dict(date='2018',text='The survey contrasts the lack of unrestricted SAT lower bounds with progress under resource restrictions and motivates conditional fine-grained complexity.',citation='primary'),dict(date='2025',text='Williams proves a square-root-space simulation for multitape Turing-machine time and derives nearly quadratic time lower bounds for certain linear-space languages.',citation='simulation'),dict(date='2026-06-16',text='The simulation result appears in the Journal of the ACM; it is not an unrestricted SAT lower bound.',citation='simulation')],
references=refs,status='uncertain',status_note='Checked the full source introduction and its later word-RAM convention, the primary time-space paper’s publisher abstract, and the full 2025 simulation report with the 2026 journal abstract and publication metadata. Searches through 12 September 2026 did not supply a unique quantitative model for the source’s broad request or an unrestricted SAT resolution. The publisher blocked the full 2026 journal text; detailed simulation statements are attributed to the checked author report.',
model_self_contained=False,requires_context=True,review_note=issue,
statement_review=dict(reviewed_on=DATE,status='needs_specification',notes=notes,remaining_issue=issue,scope='Individual source and subsequent-result review; the source does not uniquely select one model and quantitative lower-bound target.'),
importance=dict(score=c['importance']['score'],method='editorial',reason='A fundamental lower-bound challenge for satisfiability and general computation. A precise modest time separation would already be consequential, but importance does not determine the omitted model and endpoint. Existing score retained.',assessed_on=DATE),
working_summary=dict(sentences=['Boolean satisfiability asks whether some assignment makes a formula or circuit true.','The source asks for unconditional time lower bounds on general computation models.','It contrasts the ambition of exponential lower bounds with the unresolved milestone of excluding linear time without a workspace restriction.','Recent multitape time-space results establish lower bounds for other languages and do not resolve this SAT question.','A single representation, machine model and quantitative target still need to be selected.'],basis='saved_sources',written_on=DATE,source_refs=['primary','tradeoffs','simulation'])),
notes=notes,checked_sources=[r['url'] for r in refs]+['https://doi.org/10.1145/3717823.3718225','https://api.crossref.org/works/10.1145/3798104'],state='improved_unfinished')
