from review import card,save,DATE
def b(title,text,citation=None):
 d=dict(title=title,text=text)
 if citation:d['citation']=citation
 return d
i='TCS-2813';_,c=card(i);refs=c['references'];refs[0]['locator']='ITCS 2022, article 8: Definitions 5 and 8, Theorem 19 and the paragraph immediately following it. Full ECCC TR22-006 (12 January 2022), Theorem 4.2, gives the same comparison. The quoted Ω(n²/log n) refers to total shares, not one participant’s share.'
refs.extend([
 dict(id='journal2026',title='Secret Sharing, Slice Formulas, and Monotone Real Circuits — journal publication',authors='Benny Applebaum, Amos Beimel, Oded Nir, Naty Peter, Toniann Pitassi',year=2026,url='https://doi.org/10.1145/3812798',locator='ACM Transactions on Computation Theory 18(2), article 16, June 2026. Publication confirmed on the author’s publication list and publisher Crossmark metadata. The ACM full text was inaccessible; theorem details here are grounded in the accessible conference and ECCC versions, not independently checked against this version of record.'),
 dict(id='shannon2026',title='Secret Sharing at the Shannon Ceiling',authors='Christopher Williamson',year=2026,url='https://arxiv.org/abs/2608.17047',locator='Preprint v1 submitted 17 August 2026, PDF dated 18 August: Section 3, Theorem 2, Corollary 3 and Section 7 read. Claims Ω(n²) normalized total share entropy and Ω(n) maximum share entropy. Its displayed access-structure formula has O(n²) Boolean gates; it supplies no improved comparison with minimum monotone real formula size. Unrefereed claim; no independent proof audit.')
])
issue='The source observes that improving its separation would require an ω(n²/log n) general total-share lower bound, but does not state a quantified separation conjecture. It leaves open whether the intended target retains an O(n)-size MRF, asks for a larger ratio of the two minimum complexities with unrestricted MRF size, or specifies another growth rate. Fix that comparison and its asymptotic quantifiers before certifying a single yes/no benchmark. The newly claimed general Ω(n²) bound does not by itself determine the missing formula-size comparison.'
save(i,dict(
 title='A stronger separation between secret sharing and monotone real formulas',
 formal='Can the separation in Theorem 19 be improved? The source exhibits n-variable authorization functions computable by monotone real formulas of size O(n), but requiring normalized total share size Ω(n²/log n) in every perfect secret-sharing scheme. It asks for a larger gap between these complexity measures. A general lower bound above n²/log n is relevant, but the intended formula-size comparison and precise asymptotic target still need specification.',
 definitions='An access structure on n parties is represented by a nonconstant monotone Boolean function f:{0,1}ⁿ→{0,1}: A⊆[n] is authorized when f(1_A)=1, and authorization is preserved by adding parties. A perfect secret-sharing scheme has a finite secret alphabet S with |S|≥2 and finite share alphabets S₁,…,Sₙ. Its randomized dealer assigns to each secret s a distribution on S₁×⋯×Sₙ. For every authorized A, the marginal supports for distinct secrets are disjoint, so the shares indexed by A determine the secret exactly. For every unauthorized A, those marginal distributions are identical for all secrets. No computational restrictions, linearity assumptions, error or statistical leakage are allowed. All logarithms are base two. The total share size is Σᵢlog|Sᵢ|, and its normalized value is Σᵢlog|Sᵢ|/log|S|. Let SS(f) be the infimum of this normalized value over all perfect schemes and all finite secret alphabets. A monotone real formula is a finite rooted binary tree whose leaves are Boolean input variables (repetitions allowed) and whose internal gates compute arbitrary coordinatewise nondecreasing functions R²→R. Its output must equal f(x) for every Boolean input x, although intermediate values may be real. Size counts every gate, including every input occurrence; the gate functions have no bit-complexity or computability restriction in this model. Let MRF(f) be the minimum such size. These are separate measures: computing who is authorized need not implement a secret-sharing scheme. The reference separation has MRF(fₙ)=O(n) and SS(fₙ)=Ω(n²/log n).',
 question_type='asymptotic_complexity',answer_criterion='Specify the strengthened asymptotic comparison intended by the source and prove the required upper bound on MRF complexity together with the lower bound on SS for the same access-structure family. A lower bound against only linear or efficient schemes, a one-share/total-share confusion, or merely a bound on the size of currently known constructions is insufficient. The exact improvement threshold and whether linear MRF size must be retained remain unresolved formulation choices.',
 context_blocks=[b('Recognizing authorization and enforcing privacy are different tasks','A small formula can determine which groups are authorized. A secret-sharing scheme must also distribute correlated information so every authorized group can recover the secret while every other group learns nothing. The source measures the gap between these requirements.','primary'),b('The comparison already goes beyond Boolean formula size','Real gates can apply arbitrary monotone functions to real intermediate values. The known linear-size MRF and the lower bound for unrestricted perfect sharing therefore compare two substantially different notions of representation.','primary'),b('The historical lower-bound barrier has a new claimed advance','An August 2026 preprint claims normalized total share entropy Ω(n²) for an explicit family, improving the historical general lower bound by a logarithmic factor. Entropy is at most log alphabet size, so the claimed bound also implies a total-share-size bound. This is recorded as a preprint claim, not an independently verified resolution.','shannon2026'),b('That claim is not yet the stated separation comparison','The new paper presents an O(n²)-size Boolean formula for its family, and does not give the small-MRF versus large-share theorem needed to compare with Theorem 19. The original paragraph must not be reduced to the general share lower-bound question alone.','shannon2026'),b('Remaining formulation issue',issue)],
 why='Would show a sharper distinction between succinctly recognizing authorized groups and realizing their access policy with perfect information-theoretic privacy, clarifying the limitations of monotone computation as a proxy for secret-sharing complexity.',references=refs,
 progress=[dict(date='2022',text='Theorem 19 exhibits O(n) MRF size versus Ω(n²/log n) normalized total share size, and asks for a larger separation.',citation='primary'),dict(date='2026-06',text='The work appears in ACM Transactions on Computation Theory; accessible proof details were checked in its earlier full version.',citation='journal2026'),dict(date='2026-08-17',text='A new preprint claims Ω(n²) general total-share complexity. It does not establish the improved minimum-MRF comparison in this card.',citation='shannon2026')],
 status='uncertain',status_note='Read the original definitions, separation and full ECCC version. Confirmed the June 2026 journal publication, but could not access its full text. Read the August 2026 general lower-bound claim and searched its title and author’s page for updates through 12 September 2026. The claim was not independently proved or formally checked; the separation target also remains underspecified.',model_self_contained=False,requires_context=True,
 statement_review=dict(reviewed_on=DATE,status='needs_specification',remaining_issue=issue,notes=['Recovered both complexity measures and distinguished a general lower bound from the desired stronger separation.']),
 importance=dict(score=c['importance']['score'],method='editorial',reason='A structural comparison between unrestricted perfect privacy and monotone real computation, with relevance to general secret-sharing barriers. Existing score retained.',assessed_on=DATE),review_note='Restored total-share normalization and fan-in-two real-formula size. Added the August 2026 claimed general advance without treating it as the missing small-formula separation. Preserved the unresolved comparison target.',
 working_summary=dict(sentences=['This problem compares the size of monotone real formulas with the total information needed for perfect secret sharing of the same access structure.','The source gives linear formula size and a nearly quadratic total-share lower bound.','It seeks a larger separation, but does not fix the precise strengthened comparison.','An August 2026 preprint claims a quadratic general share lower bound without supplying the corresponding small-MRF separation.','The card therefore records the new claim and the remaining formulation issue separately.'],basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=['primary','shannon2026'])
 ),notes=['Recovered perfect privacy, reconstruction, normalized total shares and minimum monotone real formula size.','Separated the missing larger-gap target from a general share lower bound.','Recorded the new August 2026 claimed bound and the limited accessibility of the journal version.','Left the desired formula-size comparison and asymptotic quantifiers explicitly unresolved.'],checked_sources=[r['url'] for r in refs]+['https://eccc.weizmann.ac.il/report/2022/006/','https://bennyapplebaum.sites.tau.ac.il/publications','https://williamsonchris.com/research/'],state='improved_unfinished')
