from review import card,save,DATE

def b(title,text,citation=None):
 d=dict(title=title,text=text)
 if citation:d['citation']=citation
 return d
def summary(sentences,refs):
 return dict(sentences=sentences,basis='saved_sources',source_basis='source-text',written_on=DATE,source_refs=refs)

i='TCS-2681';_,c=card(i);refs=c['references']
refs[0]['locator']='CCC 2022, article 33: Theorem 1 (EOPL=PLS∩PPAD) and conclusion on p. 12. The circuit-class equality question is distinct from the proposed black-box separation.'
refs.extend([
 dict(id='definitions',title='Unique End of Potential Line',authors='John Fearnley, Spencer Gordon, Ruta Mehta, Rahul Savani',year=2020,url='https://doi.org/10.1016/j.jcss.2020.05.007',pdf_url='https://arxiv.org/pdf/1811.03841',locator='Full version, Section 2, Definitions 9 and 12, pp. 11–13, and Figure 2. The UV3 display omits V around S(x); the surrounding explanation and Figure 2 explicitly give V(x)<V(y)<V(S(x)).'),
 dict(id='separation2024',title='Separations in Proof Complexity and TFNP',authors='Mika Göös, Alexandros Hollender, Siddhartha Jain, Gilbert Maystre, William Pires, Robert Robere, Ran Tao',year=2024,url='https://doi.org/10.1145/3663758',pdf_url='https://www.osti.gov/pages/servlets/purl/2582805',locator='JACM 71(4), article 26: Theorem 5 and Section 8.3 establish EOPL^dt not contained in UEOPL^dt; Section 2 explains the resulting oracle separation. This does not separate the ordinary circuit-defined classes.')
])
save(i,dict(
 title='Does UEOPL equal EOPL?',
 formal='Does EndOfPotentialLine reduce to UniqueEOPL by a deterministic polynomial-time many-one reduction for total search problems? Equivalently, is UEOPL=EOPL? Instances contain explicit Boolean circuits, and the reduction may inspect their descriptions. The question concerns the ordinary classes without an oracle.',
 definitions='A total NP search problem is a polynomial-time decidable relation R(a,z) with polynomially bounded witnesses z and at least one witness for every input a. A reduction R≤S consists of deterministic polynomial-time maps F and G such that every S-witness w for F(a) gives an R-witness G(a,w); running times are polynomial in the explicit input lengths. For EndOfPotentialLine, an instance consists of circuits P,S:{0,1}ⁿ→{0,1}ⁿ and V:{0,1}ⁿ→{0,…,2ᵐ−1}, for n,m≥1, with P(0ⁿ)=0ⁿ, S(0ⁿ)≠0ⁿ and V(0ⁿ)=0. Potentials are m-bit nonnegative integers. A valid answer is a vertex x satisfying at least one of: (a) P(S(x))≠x; (b) x≠0ⁿ and S(P(x))≠x; (c) x≠S(x), P(S(x))=x and V(S(x))≤V(x). UniqueEOPL has the same instances and accepts all these answers, and additionally accepts two vertices x≠y with x≠S(x), y≠S(y), and either V(x)=V(y) or V(x)<V(y)<V(S(x)). Thus uniqueness is enforced by additional verifiable witnesses, not assumed as an unverifiable promise. Circuits are finite acyclic AND/OR/NOT circuits with their complete gate lists as input; size includes all gates, wires, input and output labels. The displayed restrictions at 0ⁿ are directly checkable; malformed encodings or failed restrictions may be assigned a distinguished trivial answer. EOPL and UEOPL consist of all total NP search problems reducible to their respective canonical problems by the reductions just defined. In particular UEOPL⊆EOPL, since an EndOfPotentialLine answer is always also a UniqueEOPL answer.',
 question_type='yes_no',answer_criterion='Prove equality by a polynomial-time reduction from EndOfPotentialLine to UniqueEOPL, valid for every output that the target relation permits, or prove that no such reduction exists. A separation limited to oracle queries or decision trees does not establish inequality of the ordinary circuit-defined classes.',
 context_blocks=[b('Searching along a path','The circuits describe a graph too large to list: each vertex has at most one predecessor and successor, and a potential labels progress. An answer may be an endpoint or a locally checkable failure of the proposed path structure.','definitions'),b('What uniqueness changes','UniqueEOPL also accepts a pair whose potentials witness incompatible lines. This extra set of acceptable outputs can make the search easier. It is essential to the definition; merely promising one line would give a different problem.','definitions'),b('The broader intersection is already understood','The 2022 theorem identifies EOPL with PLS∩PPAD, combining local-search and directed-path existence principles. The equality here asks whether the additional structure captured by UEOPL loses any of that computational power.','primary'),b('The black-box separation is now known','The JACM 2024 theorem separates EOPL from UEOPL in the decision-tree model and consequently relative to an oracle. Reductions receiving full circuit descriptions are more general, so this theorem leaves the displayed question open.','separation2024')],
 why='Would determine whether uniqueness with efficiently detectable violations defines a strictly easier form of total search inside PLS∩PPAD, affecting the classification of fixed-point, orientation and game problems captured by UEOPL.',
 references=refs,progress=[dict(date='2020',text='The defining paper proves UEOPL⊆EOPL and conjectures strict containment.',citation='definitions'),dict(date='2022',text='Further Collapses in TFNP proves EOPL=PLS∩PPAD and retains the UEOPL equality question.',citation='primary'),dict(date='2024-08',text='Theorem 5 gives the black-box and oracle separation, without an unconditional separation of the ordinary classes.',citation='separation2024')],
 status='source_open',status_note='Checked the canonical definitions, the 2022 collapse, and the published 2024 separation. Searches through 12 September 2026, including the abstracts of Super Unique Tarski is in UEOPL and On Cutting Cakes and Crossing Curves, found no resolution of the ordinary class equality. Those later applications are not equality or separation results.',
 model_self_contained=True,requires_context=False,review_note='Replaced the proposed black-box first step with its now-published result. Defined every allowed canonical witness and the reduction, preserving the unrelativized equality question.',
 importance=dict(score=c['importance']['score'],method='editorial',reason='A structural boundary within total search, distinguishing uniqueness-based problems from the full local-search/directed-path intersection. Existing score retained.',assessed_on=DATE),
 working_summary=summary(['EOPL describes total search along succinct paths with potentials.','UEOPL admits additional answers witnessing failures of uniqueness.','The question asks whether both ordinary circuit-defined classes nevertheless have the same power.','A published theorem separates them in the black-box model, which does not decide this equality.','Resolving it would clarify the computational role of uniqueness in total search.'],['primary','definitions','separation2024'])
 ),notes=['Removed solution advice and recorded the now-known black-box separation.','Defined circuit inputs, every valid canonical output and deterministic many-one search reductions.','Preserved the non-promise, unrelativized equality target.'],checked_sources=[r['url'] for r in refs]+['https://arxiv.org/abs/2411.05666','https://arxiv.org/abs/2606.13980'])

i='TCS-2718';_,c=card(i);refs=c['references'];refs[0]['locator']='IPEC 2022, article 12: Definitions 2.1–2.2 and Section 5 restore the target Õ(|D|^{(2−ε)n} polylog M). Conference constant 5/6 was improved in the full version.'
refs.append(dict(id='journal',title='Computing Generalized Convolutions Faster Than Brute Force — journal version',authors='Barış Can Esmer, Ariel Kulik, Dániel Marx, Philipp Schepper, Karol Węgrzycki',year=2024,url='https://doi.org/10.1007/s00453-023-01176-2',pdf_url='https://pure.mpg.de/rest/items/item_3561539_1/component/file_3561540/content',locator='Algorithmica 86, pp. 334–366; online 6 October 2023. Theorem 1.1 improves the even-domain constant to 3/4; Definition 2.2, Section 3.1 and Section 6 give the input model, exact deterministic arithmetic algorithm and retained open question. arXiv:2209.01623v2, 30 January 2023, also has the improvement.'))
save(i,dict(
 title='A uniform exponent saving for arbitrary generalized convolution',
 formal='Does there exist an absolute ε>0 such that, for every fixed finite domain D with d=|D|≥2 and every fixed function f:D×D→D, the entire f-convolution of two integer tables on Dⁿ can be computed exactly in Õ(d^{(2−ε)n}·polylog(2+M)) time? The same ε must work for all domains and operations; n is unbounded and M bounds the absolute input values. No associativity, commutativity or algebraic structure of f is assumed.',
 definitions='Identify D with {0,…,d−1}. For u,w∈Dⁿ set (u⊕_f w)ⱼ=f(uⱼ,wⱼ) for 1≤j≤n. Input tables g,h:Dⁿ→{−M,…,M}, with n≥1 and M≥1, list every signed integer in binary. The output is the full table C:Dⁿ→Z, where C(v)=Σ_{u,w∈Dⁿ: u⊕_f w=v}g(u)h(w); an empty sum is zero. All arithmetic is ordinary integer arithmetic. In the source’s fixed-operation convention, D and the finite d²-entry table of f specify the convolution problem; the growing inputs are g,h. More explicitly, the requested bound means a deterministic algorithm, uniform in n and the input tables, taking at most C_{D,f} d^{(2−ε)n}(1+n log d+log(2+M))^{a_{D,f}} bit operations, for constants C_{D,f},a_{D,f} depending only on D,f. Any finite preparation of that fixed table can be included in C_{D,f}; ε is chosen before D,f. This states the fixed-domain asymptotic question from the source, not a bound for reading an arbitrary operation table when n=1. Standard random-access storage of the listed tables is permitted, with arithmetic charged for operand bit length; addressing costs are absorbed in the displayed polynomial factor. Each output has O(n log d+log(2+M)) bits. The target concerns every output entry, not a query for a single specified v.',
 question_type='yes_no',answer_criterion='Establish the bound with one positive ε independent of D and f, for all fixed finite operations and all input tables, or refute that universally quantified existence claim in the stated deterministic exact-computation model. An exponent saving that tends to zero with d, a theorem restricted to selected operations, or a faster single-entry query algorithm does not suffice.',
 context_blocks=[b('A common table-combination problem','Many exact algorithms combine two tables of partial solutions coordinate by coordinate. The function f specifies how one pair of coordinate states combines; the convolution sums the contributions of every compatible pair.','primary'),b('The input size and the brute-force cost differ','There are dⁿ entries in each input table and in the output, whereas there are d^{2n} pairs of input indices. The question asks for a fixed saving in this exponent for arbitrary coordinate-combination rules.','journal'),b('The full version improves the published conference bound','The journal theorem computes the full convolution in Õ(((3/4)d²)ⁿ polylog M) for even d; for odd d the base is (3/4)d²+(1/4)d. This improves the conference constant 5/6.','journal'),b('Why a smaller base does not settle this target','For even d the known bound corresponds to ε_d=log_d(4/3). It is positive for each fixed d but approaches zero as d grows. The open question requires a single positive ε valid for all d.','journal'),b('A single value is a different task','The paper also obtains Õ(d^{ωn/2} polylog M) for one requested output entry, where ω is the matrix-multiplication exponent. The card requires all dⁿ entries within the total time bound.','journal')],
 why='Would give a broadly applicable improvement for table-merging computations without requiring an algebraic law on the state-combination operation, strengthening a common primitive in exact and parameterized algorithms.',
 references=refs,progress=[dict(date='2022',text='The conference paper beats brute force by a factor (6/5)ⁿ for even d and asks for an absolute saving in the d-exponent.',citation='primary'),dict(date='2023-01-30',text='The revised preprint improves the constant to 3/4; the Algorithmica version retains the absolute-exponent-saving question.',citation='journal')],
 status='source_open',status_note='Read the IPEC question and the improved Algorithmica version, including its retained Section 6 question. Checked the January 2023 arXiv revision and later exact-title/generalized-convolution searches through 12 September 2026; no result meeting the uniform exponent target was found.',
 model_self_contained=True,requires_context=False,review_note='Restored the damaged (2−ε)n exponent and all convolution inputs/outputs. Made the fixed-operation asymptotic convention explicit, with ε uniform across domains, and updated 5/6 to the later 3/4 theorem.',
 importance=dict(score=c['importance']['score'],method='editorial',reason='A general exact-computation primitive whose improvements can transfer across many dynamic programs, rather than a speedup for one chosen operation. Existing score retained.',assessed_on=DATE),
 working_summary=summary(['Generalized convolution combines two integer tables using an arbitrary operation on each coordinate.','The card asks to compute the entire output table with a fixed saving over the brute-force exponent.','The saving must be independent of the size of the coordinate domain.','The improved journal algorithm reduces the exponential base by a constant factor, which gives a domain-dependent exponent saving only.','A faster algorithm for one output entry does not meet the full-table target.'],['primary','journal'])
 ),notes=['Recovered the (2−ε)n target and required one ε across all domain sizes.','Defined full-table integer convolution, costs and the source’s fixed-operation convention.','Updated the conference constant to the improved full/journal result and separated single-entry queries.'],checked_sources=[r['url'] for r in refs]+['https://arxiv.org/abs/2209.01623','https://cispa.de/en/research/publications/76983-computing-generalized-convolutions-faster-than-brute-force'])
