"""Source-specific repairs of initially underspecified demo questions."""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from publish import CARDS, publish

def revise(identifier, **changes):
 path=next(p for p in CARDS.glob('*.json') if json.loads(p.read_text())['id']==identifier)
 c=json.loads(path.read_text()); c.update(changes)
 c['question_type']='yes_no';c['formulation_reviewed_on']='2026-09-10'
 path.write_text(json.dumps(c,ensure_ascii=False,indent=2));publish()

if __name__ == '__main__':
 revise('TCS-0506',
  title='Is private PAC sample complexity polynomial in VC dimension and log-star Littlestone dimension?',
  formal=r'Is there a universal polynomial p such that every finite Boolean concept class C admits a realizable, possibly improper PAC learner using some number $m\le p(1+\mathrm{VC}(C),1+\log^*\mathrm{LD}(C))$ of independent labeled examples, with error at most 1/10 and confidence at least 9/10, while satisfying $(1,1/(100m^2))$-differential privacy? The learning guarantee must hold for every distribution on the domain and every target concept in C. Computation time is unrestricted. Take both dimensions to be at least one; constant classes can be handled separately.',
  definitions=r'A concept class is a finite set of functions from a domain X to {0,1}. VC(C) is the largest size of a subset of X on which all binary labelings occur. LD(C) is the greatest depth of a complete binary tree labeled by domain points such that every root-to-leaf edge-label sequence is realized by a concept. The function log-star counts base-two logarithms needed to reach at most one. A learner may output a hypothesis outside C. Privacy requires $\Pr[A(S)\in E]\le e\Pr[A(S\prime)\in E]+1/(100m^2)$ whenever the two m-record samples differ by replacement of one record.',
  answer_criterion='Prove one polynomial upper bound that works for all finite concept classes under the fixed privacy and learning parameters, or prove that no universal polynomial of these two dimensions suffices. An unspecified new characterization or a smaller bound for one class alone is not a resolution.',
  review_note='Concrete specialization of the quantitative target following Open Question 1: accuracy, confidence, epsilon, delta, and the meaning of polynomial overhead are fixed explicitly. The survey itself suppresses these parameters. Importance is editorial; cited proofs have not been independently audited.')

 revise('TCS-6447',
  formal=r'Does every QMA promise problem admit a constant-round strong quantum interactive oracle proof with a uniform polynomial-time verifier, total prover-message length polynomial in the input length n, total query complexity O(1), completeness at least 2/3, and soundness at most 1/3? The strong access model is defined below. The prover may be computationally unbounded, and soundness quantifies over all prover strategies.',
  definitions=r'In each round the prover supplies a quantum register W. The verifier chooses queried positions through a measurement and applies a quantum channel only to those qubits and its private register; query cost counts accessed message qubits, summed over rounds. It returns the entire W register, may send additional classical information, and sends no additional quantum register. It can retain its own private workspace, but cannot retain any part of a prover-message register. The parties have no initial shared entanglement. Total prover-message length counts the full incoming registers, not only queried qubits. This restates the strong model of Definitions 5.1–5.2 and 5.13–5.15.',
  answer_criterion='Construct such a protocol for every QMA promise problem, or prove that at least one QMA promise problem has no protocol meeting all these bounds. Polynomial communication in the weaker general qIOP model does not suffice.',
  context_blocks=[{'text':'A quantum proof can be much larger than the portion a verifier actually inspects. An interactive oracle proof lets a prover supply such messages over several rounds, with the verifier charged for the qubits it touches. Communication volume and access complexity are therefore different resources.'},{'text':'The strong model requires the verifier to hand each received quantum message back in full and forbids sending an additional quantum message of its own. It still has private workspace. Returning a message does not mean undoing the measurement or channel applied to the queried qubits; the resulting state can be returned.'},{'text':'For example, a protocol might inspect only two qubits from an enormous register. That has constant query complexity but still transmits the enormous register. Conversely, allowing the verifier to retain part of a received message changes the protocol model even if the amount of communication is small.'},{'text':'The existing constructions meet different combinations of the desired bounds: general qIOPs have polynomial communication, while the strong construction has exponential communication. The question asks for polynomial communication in the strong model itself. The constant-round requirement and constant total query budget must hold together.','citation':'qiop'}],
  context='A quantum proof can be much larger than the portion a verifier actually inspects. An interactive oracle proof lets a prover supply such messages over several rounds, with the verifier charged for the qubits it touches. Communication volume and access complexity are therefore different resources.\n\nThe strong model requires the verifier to hand each received quantum message back in full and forbids sending an additional quantum message of its own. It still has private workspace. Returning a message does not mean undoing the measurement or channel applied to the queried qubits; the resulting state can be returned.\n\nFor example, a protocol might inspect only two qubits from an enormous register. That has constant query complexity but still transmits the enormous register. Conversely, allowing the verifier to retain part of a received message changes the protocol model even if the amount of communication is small.\n\nThe existing constructions meet different combinations of the desired bounds: general qIOPs have polynomial communication, while the strong construction has exponential communication. The question asks for polynomial communication in the strong model itself. The constant-round requirement and constant total query budget must hold together.')

 revise('TCS-6456',
  formal=r'For every fixed integer $k\ge3$ and $0<\varepsilon<1$, does there exist $\rho>0$ depending only on k and epsilon with the following property? Let q be prime, let $S_i\le\mathbb F_q^\times$ have pairwise coprime sizes $s_i$, and let $C_i=\{(f(a))_{a\in S_i}:\deg f<d_i\}$ with $1\le d_i<(1-\varepsilon)s_i$. Put $\Omega=\prod_i S_i$ and let $L_i$ be the arrays on Omega whose every i-axis line belongs to $C_i$. Every $M\in\sum_i L_i$ must admit a decomposition $M=\sum_i M_i$, $M_i\in L_i$, satisfying $|\operatorname{supp}M|\ge\rho\sum_i s_i\ell_i(M_i)$, where $\ell_i$ counts nonzero i-axis lines.',
  definitions='An i-axis line fixes all coordinates except coordinate i. Support size counts nonzero array entries; a nonzero line is one containing at least one nonzero entry. The sum of the L_i is their vector-space sum, so the assertion concerns an economical choice of decomposition, not every decomposition. Each C_i is a Reed–Solomon evaluation code of dimension d_i and rate d_i/s_i. The expansion constant must not depend on the field, subgroup sizes, or individual dimensions.',
  answer_criterion='Prove a positive uniform expansion constant for every fixed k and epsilon, or refute this quantified statement, for example by a family with no such positive constant for one fixed k and epsilon. A proof for k=2 or for unrelated random codes does not resolve it.')

 revise('TCS-6454',
  title='Does worst-case Nearest Codeword hardness imply low-noise LPN hardness?',
  formal=r'Does the following implication hold? If binary Nearest Codeword is not in BPP, then no uniform probabilistic polynomial-time distinguisher D has advantage at least $n^{-c}$, for any fixed $c>0$ and all sufficiently large square n, between $(A,As+e)$ and $(A,u)$. Here $A\in\mathbb F_2^{n^2\times n}$, $s\in\mathbb F_2^n$, and $u\in\mathbb F_2^{n^2}$ are independent uniform random variables, and the coordinates of e are independent Bernoulli variables with rate $1/\sqrt n$. Advantage is the absolute difference of D’s acceptance probabilities in the two experiments.',
  definitions=r'Binary Nearest Codeword receives a binary matrix G, a binary target y with the same number of rows, and an integer t, and asks whether $\min_z\operatorname{wt}(Gz-y)\le t$, with arithmetic over F_2 and Hamming weight wt. BPP means a uniform randomized polynomial-time decider correct with probability at least 2/3 on every instance. The LPN side here is a decision problem with n-squared samples, random secret, and inverse-square-root noise. Restricting n to squares makes the noise parameter an exact rational; this is an explicit specialization of the source’s broader low-noise direction.',
  answer_criterion='Prove the displayed complexity-theoretic implication, for example by a reduction turning such an LPN distinguisher into a BPP algorithm for Nearest Codeword, or prove that the implication is false. Invoking simultaneous hardness of an additional problem on the dual code does not establish this implication.',
  review_note='Editorial specialization of the NCP-only direction in Section 1.2 of the September 2026 revision. It fixes the starting problem, decision-LPN distribution, sample count, noise, uniformity, and asymptotic advantage, replacing the vague phrase natural worst-case problem. The source does not state this exact parameter specialization as a numbered conjecture.')

 revise('TCS-6453',
  title='Does average-case NP hardness imply infinitely-often one-way functions?',
  formal=r'Does $\mathrm{DistNP}\not\subseteq\mathrm{HeurBPP}$ imply the existence of a polynomial-time computable function f such that, for every probabilistic polynomial-time inverter I and every constant c>0, infinitely many lengths n satisfy $\Pr[f(I(1^n,f(U_n)))=f(U_n)\ \land\ |I(1^n,f(U_n))|=n]<n^{-c}$? The inverter is run once per experiment; the two occurrences denote that same output. The probability is over uniform U_n and inverter randomness. This card fixes the infinitely-often security convention used by the cited characterization.',
  definitions=r'DistNP consists of pairs (L,D) with L in NP and D_n a polynomial-time samplable distribution on n-bit inputs. Such a pair is in HeurBPP if a single randomized algorithm A runs in time polynomial in n and 1/delta and, for every n and $0<\delta<1$, at least a $1-\delta$ fraction of x drawn from D_n have $\Pr[A(x,\delta)=L(x)]\ge2/3$. The output is a decision bit. Infinitely-often security is weaker than requiring negligible inversion probability at all sufficiently large lengths; the latter is a distinct stronger target.',
  answer_criterion='Prove the implication under the two explicit distributional and security definitions, or prove that average-case NP hardness can hold while every polynomial-time function fails that infinitely-often inversion guarantee. A result only about an oracle world does not settle the unrelativized implication.',
  review_note='The earlier shorthand omitted the infinitely-often qualifier. This version fixes it to match Theorem 1.5 of revision 1. The all-sufficiently-large-length variant must not be silently identified with this statement. Importance is editorial and proofs have not been independently audited.')
