from authoring import ref, paragraph

LCL = ('A promise-free LCL Π has one fixed degree bound Δ≥2, one fixed checking radius r≥1, finite vertex input/output alphabets, and a finite list of permitted rooted radius-r input/output neighborhoods. A labeling is legal exactly when all vertices pass this check. The problem must admit a legal output for every finite simple undirected graph of degree at most Δ and every input assignment, including disconnected graphs. Legality is invariant under isomorphism and does not depend on identifiers, port orders, or graph size. No assumption of bipartiteness, planarity, a rooted structure, or a special global input encoding is made. ')

DYNAMIC = ('In incremental dynamic-LOCAL, a central deterministic algorithm starts with the empty graph and a known upper bound N on the eventual number of vertices. An adversary inserts isolated vertices with immutable input labels and identifiers, or inserts edges between existing vertices, always respecting Δ and the size bound. After every event the algorithm must maintain a legal output on the entire current graph. Existing outputs may change only within distance R(N) of an endpoint of the inserted edge, or of the inserted vertex, measured after the event. The algorithm may inspect the entire revealed graph and retain arbitrary state, but future vertices, inputs, and edges are unknown. The locality is the largest radius of any output change, not the number of changes or the update time. ')

ONLINE = ('In deterministic online-LOCAL, the eventual graph has n vertices, n is known, and an adversary requests every vertex once in an arbitrary order. At the request for v, the entire radius-R(n) neighborhood of v in the eventual graph is revealed, including input labels and edges in the accumulated revealed subgraph. The algorithm has global memory, but must choose v’s final output immediately and never change a previous output. All final outputs must be legal for every graph and request order. It has no advance access to the rest of the eventual graph. ')

LOCAL = ('In deterministic LOCAL, vertices initially know n, their own input, degree, ports, and a distinct identifier in [n²]. They exchange unbounded messages with neighbors in synchronous rounds. One finite computable program must work on every input, with unrestricted terminating local computation. Round complexity is the worst case over input graphs, labels, ports, and identifiers. ')

UNIFORM = ('All algorithms are uniform finite programs, all local computation must terminate, and all guarantees are deterministic and worst case. A constant locality bound is independent of size and may depend only on the fixed problem. A linear lower bound means that for every correct algorithm A there are a constant c_A>0 and arbitrarily large size bounds with an input or update sequence forcing locality at least c_A times that bound. This infinitely-often formulation is already ruled out by a uniform sublinear upper bound.')

def sources():
 return [
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#dynamic-online','Updated 23 February 2026; Promise-free separation for LCLs'),
  ref('models','Locality in Online, Dynamic, Sequential, and Distributed Graph Algorithms','Amirreza Akbari; Navid Eslami; Henrik Lievonen; Darya Melnyk; Joona Särkijärvi; Jukka Suomela',2023,'https://doi.org/10.4230/LIPIcs.ICALP.2023.10','ICALP 2023, Article 10; model definitions and LOCAL → dynamic-LOCAL → online-LOCAL simulations'),
  ref('component','Online Locality Meets Distributed Quantum Computing','Amirreza Akbari; Xavier Coiteux-Roy; Francesco d’Amore; François Le Gall; Henrik Lievonen; Darya Melnyk; Augusto Modanese; Shreyas Pai; Marc-Olivier Renou; Václav Rozhoň; Jukka Suomela',2026,'https://arxiv.org/abs/2403.01903v4','Corrected 13 February 2026 version; Definition 7.4 and Lemma 7.5 apply to families closed under disjoint union and node/edge deletion. The withdrawn general dynamic derandomization claim is not used.'),
  ref('sublinear','Distributed Quantum Advantage in Locally Checkable Labeling Problems','Alkida Balliu; Filippo Casagrande; Francesco d’Amore; Massimo Equi; Barbara Keller; Henrik Lievonen; Dennis Olivetti; Gustav Schmid; Jukka Suomela',2026,'https://arxiv.org/abs/2504.05191v2','17 August 2026; Section 1.6, Section 4.1 clustering and completion, Corollary 4.13, Appendix A and Remark A.4. The conclusion on this card is a stated editorial composition of these simulations.')]

def simulation_context():
 return [
  paragraph('The first step removes dependence on unrelated revealed components. Lemma 7.5 turns an online algorithm of locality T(n) into one whose decision depends only on its current revealed component, with locality T(2^O(n³)). If T is a constant, this enormous change of the size argument leaves locality constant. The family of all bounded-degree graphs satisfies the lemma’s closure assumptions.', 'component'),
  paragraph('The second step simulates that component-wise algorithm in sublinear deterministic LOCAL time. The clustering framework separates small-diameter regions with only O(√n) leftover vertices. Grouping nearby leftovers gives components of diameter O(√n) whose constant-radius views are mutually separate. Each such component can simulate the deterministic online rule on its leftovers independently; these simulations form one valid online prefix. Each remaining region can then choose a compatible completion by finite exhaustive search. Local checkability makes the separate completions compatible. The total communication radius is O(√n·polylog n). This explains the deterministic specialization of the component-wise simulation.', 'sublinear')]
