import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('classical-fourier-entropy-influence',
 id='TCS-6604', title='The Fourier Entropy–Influence conjecture',
 area='Communication complexity and Boolean function analysis', criterion='tightness', question_type='yes_no',
 formal='Does there exist a finite universal constant C>0 such that, for every integer n≥1 and every Boolean function f:{−1,1}ⁿ→{−1,1}, H(f)≤C I(f), where H(f) is the base-two Shannon entropy of its squared Fourier coefficients and I(f) is its total influence under the uniform distribution, as defined below?',
 definitions='Write [n]={1,…,n}. For S⊆[n], let χ_S(x)=∏_{i∈S}x_i, with χ_∅=1, and let f̂(S)=2⁻ⁿ∑_{x∈{−1,1}ⁿ}f(x)χ_S(x). Put q_S=f̂(S)²; Parseval gives ∑_S q_S=1. Define H(f)=∑_S q_S log₂(1/q_S), with a zero summand when q_S=0. If x is uniform and x^{⊕i} differs only by flipping coordinate i, define I_i(f)=Pr[f(x)≠f(x^{⊕i})] and I(f)=∑_{i=1}ⁿ I_i(f)=∑_S |S|q_S. All Boolean functions are quantified, without circuit-size, monotonicity, balance, or efficient-computability assumptions. The same C must work for all dimensions and all functions. Constant functions have H(f)=I(f)=0 and satisfy the non-strict inequality.',
 answer_criterion='Prove a dimension-independent finite upper bound for H(f)/I(f) over all nonconstant Boolean functions, or prove that this ratio is unbounded. The latter can be witnessed by a sequence of Boolean functions whose ratios tend to infinity; efficient construction is not required. Refuting one numerical choice of C does not refute existence of some larger constant. A theorem only about Fourier min-entropy, a particular circuit class, biased input distributions, or quantum Boolean operators does not settle this formulation.',
 context=[
  paragraph('The Fourier expansion expresses a Boolean rule as a linear combination of parity tests on subsets of its inputs. Squaring the coefficients produces a probability distribution on these subsets. Its entropy measures how dispersed that distribution is; total influence measures the expected size of a subset sampled from it. The conjecture says that the Boolean constraint forces the first quantity to be at most a constant times the second, even though there are exponentially many possible subsets.'),
  paragraph('This is not a generic fact about probability distributions on subsets. A distribution uniform on the n singleton sets has entropy log₂ n but expected set size one. It is the squared Fourier spectrum of the normalized real function g(x)=(x₁+⋯+x_n)/√n, which is generally not Boolean. Conversely, a parity of all n inputs has entropy zero and total influence n. These examples explain both why Boolean-valuedness matters and why the proposed inequality has only one direction.'),
  paragraph('A useful consequence would be spectral concentration: for any 0<δ<1, all but δ of the Fourier mass could be captured by at most 2^{C I(f)/δ} coefficients. This follows by applying Markov’s inequality to the surprisal log₂(1/q_S) of a random spectral subset. It supplies a quantitative connection between stability under individual bit flips and approximation by a short linear combination of parities. The dependence on δ is essential; the claim is not an accuracy-independent support bound.','han'),
  paragraph('O’Donnell, Wright and Zhou establish the conjecture for symmetric Boolean functions and for functions computed by read-once decision trees. Their paper also explains the connection to learning DNF formulas: the conjecture would imply polynomial Fourier concentration for a DNF with polynomially many terms, at each fixed approximation accuracy. This is a structural learning-theory consequence, rather than an assertion that arbitrary Boolean functions become efficiently learnable.','classes'),
  paragraph('A general bound proved by Han is H(f)≤O(I(f)+∑_i I_i(f) log(1/I_i(f))). The extra term records how influence is distributed across coordinates. It can exceed a constant multiple of I(f), so this does not settle the conjecture. The December 2025 revision adds an acknowledgement of related earlier work by Keller, Mossel and Schlank. Bounds on min-entropy concern the largest Fourier coefficient alone and must not be substituted for a Shannon-entropy bound.','han'),
  paragraph('González, MacManus and Pereyra’s June 2026 revision verifies additional classes, including δ-tribes and functions with specified separation properties. Their method splits on selected coordinates and stops at restrictions already satisfying FEI. It also demonstrates failure of a stronger sufficient inequality when the splitting coordinate is chosen badly. Those examples do satisfy FEI when handled with a suitable coordinate, so they expose a limitation of that inductive route rather than a counterexample to the conjecture.','separation'),
  paragraph('Slote’s August 2026 preprint disproves a quantum analogue using Hermitian unitary operators with flat, very large Pauli expansions. For the constructed degree-d operators, the spectral entropy grows quadratically in d while the influence grows linearly. These are quantum Boolean functions, not scalar maps on the classical Boolean cube. The result makes the distinction between the two settings concrete and does not provide a classical counterexample.','quantum'),
  paragraph('A positive solution would expose a strong restriction on the spectra of every Boolean computation, independently of how that computation is represented. A negative solution would identify Boolean functions whose spectral information greatly exceeds their sensitivity to input changes. Either outcome would clarify a basic link between combinatorial stability, harmonic analysis and the possibility of learning from sparse spectral descriptions.')],
 why='A central structural conjecture connecting sensitivity to spectral information. Its resolution would sharpen our understanding of Boolean functions and spectral learning, while testing a relation that fails without the Boolean constraint.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A longstanding, broadly consequential conjecture in Boolean function analysis, with direct learning-theory implications and active 2026 progress that still leaves the universal classical inequality open.'),
 progress=[
  step('1996','Friedgut and Kalai propose the conjecture; the historical attribution and its applications are described by O’Donnell, Wright and Zhou.','classes'),
  step('2011','The conjecture is verified for symmetric functions and read-once decision trees.','classes'),
  step('2023–2025','Han proves a general bound with an additional coordinate-influence entropy term; Combinatorica publication is in volume 45 (2025), and arXiv v2 of 10 December 2025 acknowledges related prior work.','han'),
  step('2026-06-09','The revised González–MacManus–Pereyra preprint proves FEI for new separated classes and δ-tribes; the unrestricted classical question remains open.','separation'),
  step('2026-08-02','Slote posts a counterexample to the quantum FEI conjecture. Its operator-valued construction does not resolve classical FEI.','quantum')],
 references=[
  ref('classes','The Fourier Entropy–Influence Conjecture for certain classes of Boolean functions','Ryan O’Donnell; John Wright; Yuan Zhou',2011,'https://www.cs.cmu.edu/~jswright/papers/fei.pdf','ICALP 2011, pp. 330–341; introduction, applications and symmetric/read-once results'),
  ref('han','A new bound for the Fourier-Entropy-Influence conjecture','Xiao Han',2025,'https://arxiv.org/abs/2312.08271','Combinatorica 45, article 4 (2025), DOI 10.1007/s00493-024-00133-z; arXiv v2, 10 December 2025; Theorem 1 and Note added'),
  ref('separation','Further evidence towards the Fourier Entropy-Influence conjecture','María José González; Paul MacManus; María Cristina Pereyra',2026,'https://arxiv.org/abs/2606.00246','v2, 9 June 2026, first submitted 29 May; Theorem 1.3, §§4–6; failure of stronger fixed-coordinate inequality is not failure of FEI'),
  ref('quantum','Dense Hamiltonians at the Parseval Limit: The Noncommutative BH Constant is Exponential and the Quantum FEI Conjecture is False','Joseph Slote',2026,'https://arxiv.org/abs/2608.01424','v1, 2 August; quantum Boolean operators with N(d)=exp(Ω(d²)) equal-magnitude degree-d Pauli coefficients')],
 status='source_open', status_note='Checked through 10 September 2026. The June 2026 primary paper explicitly retains classical FEI as open and proves only specified classes. The August 2026 disproof is of the quantum extension. No classical resolution was found in the checked sources; the formulation uses Shannon entropy, uniform measure and scalar Boolean functions throughout.', formulation_reviewed_on='2026-09-10')
