import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('tarski-fixed-dimension-log-squared-query-bound',
 id='TCS-0491',title='Can every fixed-dimensional Tarski problem be solved with O(log² n) queries?',
 area='General algorithm design',criterion='tightness',question_type='yes_no',
 formal=r'''Let Q(n,k) be the minimum worst-case number of adaptive deterministic value queries needed to find any fixed point of an unknown monotone function $f:[n]^k\to[n]^k$, where [n]={1,...,n} and monotonicity is with respect to coordinatewise order. A query at x reveals the entire vector f(x). Is it true that for every integer k>=1 there is a constant C_k such that $Q(n,k)\le C_k(1+\log_2 n)^2$ for every n>=2? Arbitrary finite computation between queries is allowed. Constants may depend on k but not on n or f. This asks for an exponent independent of the fixed dimension, not a polynomial bound on C_k.''',
 definitions='For x,y in the grid, x<=y means x_i<=y_i for every coordinate i. The oracle is promised to satisfy x<=y implies f(x)<=f(y). A valid output is any x with f(x)=x; no minimum or maximum fixed point is required. An adaptive query procedure can choose each query using all earlier queries and answers, and must terminate correctly for every promised oracle. Equivalently, Q(n,k) is the minimum depth of a finite deterministic oracle decision tree whose leaves output valid fixed points for every monotone function consistent with that leaf. Neither a circuit description nor the table of f is part of the input. Query cost is one per returned vector, and places no restriction on the bit complexity of choosing the next query. The finite product grid is a complete lattice, so a fixed point always exists.',
 answer_criterion='Prove the bound for every fixed k, or show that there is a fixed k for which Q(n,k)/(1+log_2 n)^2 is unbounded as n grows. A growing factor depending only on k is permitted. A bound whose logarithmic exponent grows with k does not answer yes. A lower bound obtained only by letting k grow with n does not answer no unless it implies failure at some fixed k.',
 context=[
  paragraph('Starting at the bottom of the grid and repeatedly applying f gives a nondecreasing chain until a fixed point is reached. This directly proves existence constructively, but the chain can contain a number of steps proportional to n times the dimension. Since the coordinates need only log n bits to describe, dependence on n can be exponentially larger than dependence on the coordinate description length.'),
  paragraph('One-dimensional search can exploit order by repeatedly discarding a large interval. In a product order, two points can be incomparable: one coordinate is larger and another smaller. The oracle’s monotonicity then does not directly compare their images. The question asks whether these multidimensional interactions must eventually increase the power of log n, or whether they can be absorbed into a dimension-dependent constant.'),
  paragraph('The first surprise was that dimensions two and three both have Theta(log^2 n) query complexity. Chen, Li, and Yannakakis extend this equality to dimension four in their March 2026 preprint. Their more general upper bound is O(log^(ceil((k-1)/3)+1) n) for fixed k. The concluding discussion explicitly raises a bound of the form f(k) log^2 n, which is the target on this card.', 'fourdim'),
  paragraph('Query complexity and computational efficiency must be separated here. The 2026 algorithm uses expensive intermediate search and counting; its authors leave a time-efficient implementation open. Even a positive answer to this card would only limit how much oracle information is needed. Obtaining a polynomial-time algorithm when both k and log n are input parameters would require additional control of the constants and the work between queries.', 'fourdim')],
 why='This probes the information cost of finding a guaranteed fixed point under monotonicity, a basic organizing principle in algorithms, semantics, and equilibrium computation. The same sharp bound in dimensions two, three, and four makes the dependence on dimension a substantive structural mystery rather than just a loose analysis of one algorithm.',
 importance=dict(score=85,method='editorial',assessed_on='2026-09-10',reason='A broad oracle-complexity question about monotone fixed points, with a surprising low-dimensional pattern and connections to equilibrium search. It distinguishes intrinsic information requirements from implementation time.'),
 progress=[
  step('2020','Etessami, Papadimitriou, Rubinstein, and Yannakakis prove an Omega(log^2 n) lower bound already in two dimensions, including for randomized algorithms; the 2022 seminar records this starting point.','seminar'),
  step('2021 / 2022 journal','Fearnley, Pálvölgyi, and Savani give an O(log^2 n)-query algorithm in three dimensions, matching the two-dimensional lower bound.','threedim'),
  step('2025-07-13','Brânzei, Phillips, and Recker prove randomized query lower bound Omega(k log^2 n / log k) for n,k>=2. For fixed k this remains quadratic in log n, so it does not rule out the card’s target.','lower'),
  step('2026-03-31','Chen, Li, and Yannakakis obtain O(log^2 n) queries in four dimensions and improve the exponent in every fixed dimension. Section 9 proposes the possibility of a generic dimension-dependent constant times log^2 n.','fourdim')],
 references=[
  ref('seminar','Finite and Algorithmic Model Theory (Dagstuhl Seminar 22051)','Kousha Etessami (problem contributor)',2022,'https://doi.org/10.4230/DagRep.12.1.101','Section 4.2, query bounds for Tarski fixed points on grid lattices'),
  ref('threedim','A Faster Algorithm for Finding Tarski Fixed Points','John Fearnley; Dömötör Pálvölgyi; Rahul Savani',2022,'https://doi.org/10.1145/3524044','ACM Transactions on Algorithms; earlier version at STACS 2021'),
  ref('lower','Tarski Lower Bounds from Multi-Dimensional Herringbones','Simina Brânzei; Reed Phillips; Nicholas Recker',2025,'https://arxiv.org/abs/2502.16679v2','Version 2, 13 July 2025; randomized lower bound'),
  ref('fourdim','The Mystery Deepens: On the Query Complexity of Tarski Fixed Points','Xi Chen; Yuhao Li; Mihalis Yannakakis',2026,'https://arxiv.org/abs/2604.00268v1','Theorem 1, Corollary 1, and Section 9; posted 31 March 2026')],
 status='source_open',status_note='The broad 2022 question has substantial later progress: dimension four is settled by the 2026 preprint. The displayed all-fixed-dimensions target is explicitly discussed as open in that paper’s conclusion. Searches through 10 September 2026 did not locate a resolution.',
 formulation_reviewed_on='2026-09-10')
