import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('general-gapped-two-dimensional-ground-state-entropy-area-law',
 id='TCS-6516', title='An entanglement entropy area law for general gapped two-dimensional Hamiltonians',
 area='Quantum computation', criterion='tightness', question_type='yes_no',
 formal='For every fixed local dimension q≥2, interaction range r≥1, interaction incidence bound g≥1, norm bound J>0, and spectral gap Δ>0, is there a finite constant C=C(q,r,g,J,Δ) such that every Hamiltonian H described below, on every square lattice Λ_L, has unique ground state ψ satisfying S(ρ_A)≤C|∂A| for every A⊆Λ_L?',
 definitions='Let L≥1 be an integer, Λ_L={1,…,L}² with open boundaries, and the Hilbert space be the tensor product of C^q over its sites. Write H=Σ_a h_a, where each h_a is Hermitian and acts only on a nonempty support X_a⊆Λ_L of diameter at most r in the maximum-coordinate metric. Each site belongs to at most g supports, counting terms with the same support separately, and the operator norm of every h_a is at most J. Suppose H has a unique normalized lowest-energy eigenvector ψ and its next eigenvalue is at least Δ above the lowest eigenvalue. This is a gap of the entire Hamiltonian; no spectral-gap condition is imposed on subregions or subsets of terms. For A⊆Λ_L, let A^c be its complement in Λ_L and ρ_A=Tr_(A^c)(|ψ⟩⟨ψ|) and S(ρ_A)=−Tr(ρ_A log_2 ρ_A), with 0 log_2 0=0. The boundary ∂A is the set of nearest-neighbor lattice edges with exactly one endpoint in A; its cardinality is the boundary length in lattice units. Empty and full regions have entropy zero. The local parameters and C must be independent of L, A, and the actual interaction matrices. Interactions may vary from site to site and with L. They need not commute or share a simultaneous minimum-energy state; translation invariance and frustration freeness are not assumed. No approximation or state-preparation algorithm is requested.',
 answer_criterion='Prove the uniform entropy bound for all fixed choices of local parameters, or produce a family with the same q,r,g,J,Δ throughout and regions A for which S(ρ_A)/|∂A| is unbounded. A gap that closes with lattice size, growing local dimension or term norms, or degeneracy allowing a highly entangled choice of ground state does not refute this formulation. A bound with an extra unbounded logarithmic or subpolynomial factor is progress but does not establish the strict area law stated here.',
 context=[
  paragraph('A region with m spins has enough Hilbert-space dimension for entropy m log_2 q. For a square block of side length ℓ, that is proportional to ℓ², whereas this conjecture allows only a constant times ℓ. The physical idea is that finite-range interactions and a gap should constrain how much quantum information crosses the boundary. Fixing both interaction strength and the gap prevents an artificial rescaling from making a gapless family appear uniformly gapped.'),
  paragraph('In one dimension, Hastings proves the corresponding entropy bound for gapped local systems. Since an interval has only a constant number of boundary points, its entropy remains bounded as the chain grows. Matrix-product-state approximations then connect this structure to classical numerical methods. Grouping columns of a two-dimensional lattice into single one-dimensional sites does not directly extend the theorem: each new site has dimension q^L, which grows exponentially with the width.','hastings'),
  paragraph('Anshu, Arad, and Gosset make major progress for frustration-free systems with a local gap. Frustration freeness means one state minimizes every local term; the local-gap assumption controls Hamiltonians obtained from subsets of terms, and is stronger than the global gap here. Their cited version proves a vertical-cut entropy bound n^(1+O((log n)^(−1/5))) for cut length n. It is asymptotically almost linear, but the remaining factor is not a constant and neither extra assumption follows from the statement in this card.','ff'),
  paragraph('Anshu, Harrow, and Soleimanifar prove an area law for entanglement spread, a measure of variation among the Schmidt coefficients after an appropriate smoothing. This controls a different feature of entanglement from its entropy. For intuition, a maximally entangled state can have arbitrarily many equal Schmidt coefficients: its spread is zero while its entropy is the logarithm of their number. A spread bound therefore does not by itself answer the entropy question.','spread'),
  paragraph('Arad, Firanko, and Jain’s February 2026 theorem treats mutual information of the maximally mixed ground state. It assumes a sufficiently accurate approximation to the ground-space projector whose operator Schmidt rank is suitably small. Constructing such an approximation for general gapped two-dimensional Hamiltonians remains a missing ingredient; the general wording of the title does not remove this hypothesis.','mixed'),
  paragraph('Garratt and Abanin’s April 2026 preprint provides thermodynamic upper bounds and proves area laws for frustration-free systems when ground-space degeneracies of the relevant subsystem Hamiltonians have suitable boundary scaling. A unique ground state for the full system does not impose that condition on each subsystem. These results give further routes toward the conjecture while retaining additional assumptions.','thermal'),
  paragraph('The computational significance also needs care. Huang proves that two-dimensional local Hamiltonian instances whose ground states satisfy area laws can still be QMA-complete. Those instances are not claimed to have the uniform gap fixed here. The result nevertheless shows why an entropy bound alone should not be advertised as a general efficient classical algorithm for finding or manipulating two-dimensional ground states.','complexity')],
 why='A central problem in quantum Hamiltonian complexity: whether locality plus a uniform gap controls the quantum information in ground states in two dimensions. It would sharpen the structural foundations of tensor-network methods and separate the task of bounding entanglement from the further task of computing the state.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A fundamental unresolved link between spectral gaps, geometric locality, entanglement, and the resources needed to describe quantum many-body ground states.'),
 progress=[
  step('2007','Hastings proves the area law for gapped one-dimensional quantum systems; the bound depends on fixed local parameters.','hastings'),
  step('2021','Huang establishes QMA-completeness of two-dimensional local Hamiltonian problems even when ground states satisfy area laws, without claiming a uniform spectral gap.','complexity'),
  step('2022','Anshu, Harrow, and Soleimanifar publish an area law for entanglement spread, rather than von Neumann entropy.','spread'),
  step('2022–2023','Anshu, Arad, and Gosset give a nearly linear entropy bound for vertical cuts in locally gapped frustration-free systems. In arXiv version 3, the explicit bound is n^(1+O((log n)^(−1/5))) at the end of §4.','ff'),
  step('2026-02-05','Arad, Firanko, and Jain extend approximate-projector methods to mutual information of maximally mixed ground states; their theorem still requires a good approximate ground-space projector.','mixed'),
  step('2026-04-15','Garratt and Abanin derive entropy bounds from thermodynamic information and area laws for frustration-free systems with suitably bounded subsystem ground-space degeneracies.','thermal')],
 references=[
  ref('hastings','An Area Law for One Dimensional Quantum Systems','Matthew B. Hastings',2007,'https://arxiv.org/abs/0705.2024v4','Journal of Statistical Mechanics P08024 (2007); corrected arXiv version 10 July 2018'),
  ref('ff','An area law for 2D frustration-free spin systems','Anurag Anshu; Itai Arad; David Gosset',2022,'https://arxiv.org/abs/2103.02492v3','STOC 2022, DOI 10.1145/3519935.3519962; 17 February 2023 version, Theorem 1.1, local gap Eq. (41), and final entropy bound following Eq. (48)'),
  ref('spread','Entanglement spread area law in gapped ground states','Anurag Anshu; Aram W. Harrow; Mehdi Soleimanifar',2022,'https://doi.org/10.1038/s41567-022-01740-7','Nature Physics 18, 1362–1366; author preprint arXiv:2004.15009, titled From communication complexity to an entanglement spread area law in the ground state of gapped local Hamiltonians'),
  ref('mixed','Area Laws and Tensor Networks for Maximally Mixed Ground States','Itai Arad; Raz Firanko; Rahul Jain',2026,'https://doi.org/10.1007/s00220-026-05554-z','Communications in Mathematical Physics 407, article 54; 5 February 2026; introduction and Definition 2.1 explain the required approximate-projector hypothesis'),
  ref('thermal','Quantum matter is weakly entangled at low energies','Samuel J. Garratt; Dmitry A. Abanin',2026,'https://arxiv.org/abs/2604.14143v1','15 April 2026 preprint; entropy bounds from thermal data and frustration-free subsystem ground-space dimensions'),
  ref('complexity','Two-dimensional local Hamiltonian problem with area laws is QMA-complete','Yichen Huang',2021,'https://doi.org/10.1016/j.jcp.2021.110534','Journal of Computational Physics 443, 110534; Theorem 1 and discussion distinguishing area laws from efficient state representations')],
 status='source_open', status_note='Checked through 10 September 2026. The February and April 2026 results retain extra hypotheses; the general globally gapped 2D entropy area law remains unresolved. The formulation explicitly requires a size-independent constant and fixes the geometric boundary, interaction norms, local dimension, uniqueness, and global gap.', formulation_reviewed_on='2026-09-10')
