import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('polynomial-time-versus-polynomial-space',
 id='TCS-6530',title='Does P equal PSPACE?',
 area='Computational complexity',criterion='resources',question_type='yes_no',
 formal=r'''Does every language decidable by a deterministic Turing machine using polynomial working space have a deterministic polynomial-time decision algorithm? Equivalently, do there exist a machine A and constants C,k such that A decides truth of every closed quantified Boolean formula of encoded length n in at most $C(n+1)^k$ steps?''',
 definitions=r'''P consists of languages decided by one deterministic multitape Turing machine with a fixed polynomial worst-case time bound. PSPACE consists of languages decided by one deterministic Turing machine which halts on every input and visits at most C(n+1)^k work-tape cells, for some constants C,k, on inputs of length n. The input is read-only and is not charged as work space; a fixed finite tape alphabet is used. PSPACE imposes no polynomial time bound. A closed quantified Boolean formula has the form Q₁x₁⋯Qₘxₘ φ(x₁,…,xₘ), where each Qᵢ is ∃ or ∀, quantified variables are distinct, and φ is an explicitly encoded Boolean formula using AND, OR, and NOT, with no free variables. Every quantifier ranges over {0,1}. The number of quantifiers and their alternations may grow with n; the input is not restricted to a fixed number of blocks. Use any standard explicit binary encoding, reject malformed inputs, and count its full bit length n. Truth means the usual nested Boolean quantifier semantics. This language, TQBF, is PSPACE-complete under polynomial-time many-one reductions. No oracle, advice, randomization, or promise is allowed.''',
 answer_criterion='Prove P=PSPACE or P≠PSPACE. A polynomial-time TQBF decider proves equality. To prove separation, exhibit one PSPACE language that has no polynomial-time algorithm, equivalently rule out every polynomial-time TQBF decider. A lower bound against only one fixed polynomial time exponent is insufficient.',
 context=[
  paragraph('Time measures the total number of computation steps; space measures how much information the machine retains at once. Space can be reused. For example, a machine can evaluate a quantified formula by recursively exploring possible choices and reusing its work area when it returns from a branch. The resulting computation may inspect exponentially many choices while keeping only a polynomial amount of information.','book'),
  paragraph('Alternating quantifiers express a finite game of choices: existential moves try to make the final formula true, and universal moves challenge them. A full winning strategy may have exponentially many branches, although each play has polynomial length. The characterization of polynomial space by polynomial-time alternation explains why many polynomial-length planning and game problems are PSPACE-complete.','alternation'),
  paragraph('The inclusion P⊆PSPACE is immediate, but its strictness is unknown. P≠NP would imply P≠PSPACE because NP⊆PSPACE. A proof of P=NP, however, would collapse the polynomial hierarchy without automatically giving a polynomial-time algorithm for formulas with an unbounded number of quantifier alternations. This separates the present question from merely solving satisfiability.','book'),
  paragraph('The theorem IP=PSPACE characterizes the same space class through interaction: a polynomial-time randomized verifier can check claims from an unbounded prover using a bounded-error interactive protocol. The prover’s assistance is a resource. Removing the prover to obtain an ordinary deterministic polynomial-time algorithm is not a consequence of that characterization.','interactive'),
  paragraph('Williams’ time-to-space simulation gives a concrete advance toward time lower bounds. A multitape computation taking t steps can be simulated in O(sqrt(t log t)) space. Combined with the space hierarchy, this excludes near-quadratic time bounds for some linear-space problems. The exponent is still fixed: it does not give a polynomial-space language outside every polynomial time bound.','simulation')],
 why='This asks whether reusing a feasible amount of memory can provide computational power beyond feasible running time. It is a central unresolved separation even when the allowed language class is enlarged from NP to all of PSPACE, and it organizes the complexity of quantified reasoning, games, and verification.',
 importance=dict(score=100,method='editorial',assessed_on='2026-09-10',reason='A defining question about the relationship between the two basic computational resources, time and working memory. It is a top-priority foundational class separation.'),
 progress=[
  step('1970s–1981','Quantified Boolean formulas provide a PSPACE-complete target. Chandra, Kozen, and Stockmeyer characterize deterministic polynomial space as alternating polynomial time.','alternation'),
  step('1992','Shamir proves IP=PSPACE, giving an interactive-proof characterization without resolving deterministic polynomial-time computation.','interactive'),
  step('2025 conference / 2026 journal','Williams proves the O(sqrt(t log t)) space simulation of time-t multitape machines, improving the decades-old O(t/log t) bound. It yields fixed-exponent time lower bounds for linear-space languages.','simulation'),
  step('2026-08','Williams’ MFCS invited survey discusses this simulation and further space-complexity developments. It supplies no separation of the unions P and PSPACE.','recent')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2019,'https://www.math.ias.edu/files/Book-online-Aug0619.pdf','6 August 2019 edition; Section 4.1, Figure 10, and Chapter 14 time/space containments and hierarchy discussion'),
  ref('alternation','Alternation','Ashok K. Chandra; Dexter C. Kozen; Larry J. Stockmeyer',1981,'https://doi.org/10.1145/322234.322243','JACM 28(1), 114–133; polynomial-time alternation equals polynomial space; quantified-game viewpoint also explained in Wigderson Section 4.1'),
  ref('interactive','IP = PSPACE','Adi Shamir',1992,'https://doi.org/10.1145/146585.146609','JACM 39(4), 869–877; interactive-proof characterization'),
  ref('simulation','Simulating Time With Square-Root Space','R. Ryan Williams',2025,'https://arxiv.org/abs/2502.17779v1','STOC 2025; author full text and abstract. Journal version: JACM 73(3), Article 16 (2026), DOI 10.1145/3798104.'),
  ref('recent','Some Recent Developments in Space Complexity','R. Ryan Williams',2026,'https://doi.org/10.4230/LIPIcs.MFCS.2026.3','MFCS 2026 invited talk, published 21 August 2026; one-page survey abstract')],
 status='source_open',status_note='Explicitly unresolved in Wigderson’s class-containment discussion. The 2025 time-space simulation and August 2026 survey were checked for their precise scope; no separation or equality of P and PSPACE was located through 10 September 2026. Fixed-exponent time lower bounds do not settle the full polynomial-time question.',formulation_reviewed_on='2026-09-10')
