import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('metric-kmedian-hardness-threshold-approximation',
 id='TCS-6659',title='Can metric k-Median reach the 1+2/e threshold?',area='Approximation algorithms and hardness of approximation',criterion='tightness',question_type='yes_no',
 formal='For every fixed rational ε∈(0,1), does a randomized polynomial-time (1+2/e+ε)-approximation algorithm exist for general metric k-Median that always opens at most k facilities?',
 definitions='An input consists of a finite set V, a full table of nonnegative rational distances d on V encoded in binary, nonempty subsets C,F⊆V of clients and allowable facilities with C∪F=V, and an integer 1≤k≤|F|. The table is promised to satisfy d(u,v)=d(v,u), d(u,v)=0 exactly when u=v, and the triangle inequality. Each client has unit demand. For nonempty S⊆F define cost(S)=Σ_{c∈C}min_{s∈S}d(c,s), and OPT=min{cost(S):S⊆F,1≤|S|≤k}. L is the total bit length of the input. For each fixed ε the target is one uniform classical randomized algorithm A_ε, with constants K_ε,d_ε such that every execution takes at most K_ε L^{d_ε} bit operations. It always returns an explicit nonempty S⊆F with |S|≤k, and on each input Pr[cost(S)≤(1+2/e+ε)OPT]≥2/3. Here e is the base of the natural logarithm. The constants may depend on ε but not on k, |C|, |F| or distance precision. No Euclidean, low-dimensional, stability, capacity or input-distribution promise is made. Candidate facilities are part of the input and cannot be enlarged. The guarantee also covers OPT=0.',
 answer_criterion='Give the stated algorithms for every fixed ε>0, or rule them out for at least one fixed ε, explicitly identifying any complexity assumption used. This card fixes the yes/no question of approaching the known hardness threshold; it does not additionally require finding a different exact threshold after a negative answer. An algorithm opening k facilities only in expectation, one allowing k+o(k) facilities, or an FPT algorithm with unrestricted dependence on k does not prove the claim.',
 context=[
 paragraph('Metric k-Median selects a limited number of service locations and minimizes total distance to the nearest selected location. The number of clients and the number of candidate facilities may differ, and the distance table need not come from a Euclidean embedding. The same formulation models representative selection for clustering and placement of facilities. Its simplicity makes the unresolved approximation threshold a central benchmark for algorithm design.'),
 paragraph('The two endpoint numbers are approximately 1.73576 and 2. The lower endpoint is the classical hardness threshold 1+2/e; the best general feasible guarantee in the checked literature is 2+ε. The inherited STOC 2025 paper explicitly asks for a tight approximation result after obtaining that upper bound. Asking for 1+2/e+ε for every fixed ε avoids requiring that an infimum approximation ratio be achieved exactly.','primary'),
 paragraph('The coverage origin of the lower endpoint can be seen directly. Represent each set as a candidate facility and each universe element as a client. Give a client–facility pair distance one when the set contains the element and distance three otherwise, and give distinct pairs on the same side distance two. These distances satisfy the triangle inequality. A collection of k sets covering a fraction p of the elements then has clustering cost (3−2p) times the universe size.'),
 paragraph('Feige’s Max k-Cover gap distinguishes complete coverage from coverage of at most 1−1/e+η, for any fixed η>0. Under the preceding metric construction this becomes a gap between cost one per client and cost at least 1+2/e−2η per client. This is why the constant is not an arbitrary numerical target. A randomized algorithm beating that gap on every input would yield randomized algorithms for the underlying NP-hard decision problem; the appropriate exclusion is NP≠RP for this card’s success convention.','coverage'),
 paragraph('Jain–Mahdian–Saberi’s 2002 paper gives the classical metric k-Median lower bound through a reduction to approximating Set Cover. Its historical statement uses the then-known slightly-superpolynomial-time assumption for Set Cover hardness. The coverage reduction above explains the stronger ordinary NP-hardness formulation without silently changing the assumption in the original theorem. Neither lower-bound route excludes approximation from just above 1+2/e.','hardness'),
 paragraph('The 2025 algorithm combines two components. One permits a logarithmic number of extra centers while retaining a 2+ε cost bound; another handles instances where deleting one optimal center increases the optimum substantially. Combining them returns a feasible solution opening at most k centers. The full paper’s May 2026 revision retains this result. It is therefore incorrect to describe the headline 2+ε theorem as only a bicriteria approximation.','primary'),
 paragraph('The usual linear relaxation has a separate barrier near two. It uses fractional openings y_s, assignments x_{c,s}≤y_s, unit total assignment for each client, and Σ_s y_s≤k. For a star with q≥3 leaves, all vertices available as facilities, clients at the leaves and k=q−1, every integral optimum has cost two. Set the central opening to 1/(q−1), each leaf opening to (q−2)/(q−1), and assign each client’s remaining fraction to the center. This feasible LP solution costs q/(q−1), giving an integrality gap approaching two.'),
 paragraph('That explicit example limits a guarantee measured against this relaxation, not every polynomial algorithm measured against OPT. A sharper algorithm might use additional constraints, a different relaxation, or another method. Likewise, a lower bound for one rounding framework is not a computational impossibility theorem for the original optimization problem. The card’s target is deliberately stated using the true integral optimum.'),
 paragraph('There is already a matching-threshold algorithm in a different runtime regime. Cohen-Addad–Gupta–Kumar–Lee–Li’s ICALP 2019 work achieves 1+2/e+ε in fixed-parameter time with respect to k. The potentially large dependence on the number of opened facilities is permitted there. This does not supply a polynomial-time algorithm when k grows as part of the input, but it shows that the target ratio has meaningful algorithmic support.','fpt'),
 paragraph('A 2026 development concerns geometric input. Cohen-Addad and coauthors improve approximation-scheme runtimes in low-dimensional Euclidean spaces, where additional structure is available. Such a scheme does not apply to arbitrary distance tables.','geometry'),
 paragraph('Anand and coauthors’ July 2026 spectral dual-fitting paper improves k-Means guarantees, including in general metrics. That objective sums squared distances; squaring changes both the analysis and the hardness constants. It does not establish the stated k-Median ratio.','means'),
 paragraph('Resolving this question would determine whether the coverage obstruction captures the full cost of efficient metric clustering. A positive answer would bridge the remaining gap beyond the familiar LP benchmark. A stronger hardness threshold would reveal an obstruction not expressed by coverage alone. The exact facility budget is essential to either conclusion: averaging an excessive number of facilities over random choices changes the feasible problem.')],
 why='A central unresolved approximation threshold for metric clustering, separating known coverage hardness from the best algorithms with a strict facility budget.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A major optimization problem with a substantial remaining algorithm–hardness gap and connections to coverage, facility location, LP rounding and parameterized approximation.'),
 progress=[step('1998','Feige proves the 1−1/e hardness threshold for Max k-Cover, which yields the 1+2/e metric k-Median gap through a client–facility metric construction.','coverage'),step('2002','Jain–Mahdian–Saberi give the classical k-Median lower bound via Set Cover approximation; Theorem 10 states the historical reduction.','hardness'),step('2019','Cohen-Addad–Gupta–Kumar–Lee–Li reach 1+2/e+ε in fixed-parameter time with respect to k, not unrestricted polynomial time.','fpt'),step('2025–19 May 2026','Cohen-Addad–Grandoni–Lee–Schwiegelshohn–Svensson obtain a randomized polynomial-time 2+ε approximation with at most k facilities; the May 2026 full-version revision retains the theorem.','primary'),step('10 March 2026','Improved approximation-scheme runtimes apply to low-dimensional Euclidean clustering, a restricted metric setting.','geometry'),step('16 July 2026','Spectral dual fitting improves k-Means approximation; squared-distance clustering is a different objective.','means')],
 references=[ref('primary','A (2+ε)-Approximation Algorithm for Metric k-Median','Vincent Cohen-Addad; Fabrizio Grandoni; Euiwoong Lee; Chris Schwiegelshohn; Ola Svensson',2025,'https://people.idsia.ch/~grandoni/Pubblicazioni/CGLSS25stoc.pdf','Inherited source; STOC 2025, 615–624; Theorems 1.1–1.3 and concluding paragraph of §1.1; full version arXiv:2503.10972 v2 dated 19 May 2026'),ref('coverage','A threshold of ln n for approximating set cover','Uriel Feige',1998,'https://disco.ethz.ch/alumni/pascalv/refs/ds_1998_feige.pdf','Journal of the ACM 45(4), 634–652; Max k-Cover hardness, distinguished from the stronger historical assumption for Set Cover'),ref('hardness','A new greedy approach for facility location problems','Kamal Jain; Mohammad Mahdian; Amin Saberi',2002,'https://cgi.di.uoa.gr/~vassilis/co/co-papers/jain02.pdf','STOC 2002, 731–740; §6, Theorem 10; DOI 10.1145/509907.510012'),ref('fpt','Tight FPT Approximations for k-Median and k-Means','Vincent Cohen-Addad; Anupam Gupta; Amit Kumar; Euiwoong Lee; Jason Li',2019,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2019.42','ICALP 2019, 42:1–42:14; fixed-parameter approximation with respect to k'),ref('geometry','Almost-Optimal Upper and Lower Bounds for Clustering in Low Dimensional Euclidean Spaces','Vincent Cohen-Addad; Karthik C. S.; David Saulpic; Chris Schwiegelshohn',2026,'https://arxiv.org/abs/2603.09846','Posted 10 March 2026; approximation schemes use a low-dimensional Euclidean promise'),ref('means','Spectral Dual Fitting for k-Means','Aditya Anand; Moses Charikar; Vincent Cohen-Addad; Ruiquan Gao; Fabrizio Grandoni; Euiwoong Lee; Amatya Sharma; Ernest van Wijland',2026,'https://arxiv.org/abs/2607.14654','Posted 16 July 2026; primary title and abstract concern k-Means, despite a malformed combined title on a third-party mirror')],
 status='source_open',status_note='Reviewed through 11 September 2026. The checked general-metric result remains 2+ε with a strict budget, while the classical hardness threshold is 1+2/e. The FPT algorithm, Euclidean schemes and 2026 k-Means results do not settle the polynomial-time target here.',formulation_reviewed_on='2026-09-11')
