import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('logarithmic-space-versus-polynomial-time',
 id='TCS-6531', title='Can every polynomial-time decision problem be solved in logarithmic space?',
 area='Computational complexity', criterion='resources', question_type='yes_no',
 formal=r'''Is L=P? Equivalently, does the Circuit Value Problem have a deterministic algorithm that always halts and uses O(log(n+2)) bits of working memory on an input of binary encoding length n?''',
 definitions=r'''L consists of total decision languages recognized by a fixed deterministic Turing machine with a read-only input tape and a fixed finite number of initially blank read/write work tapes over fixed finite alphabets. The input can be revisited freely; all visited work-tape cells count toward space, but the read-only input itself does not. For each language there must be a constant C such that every n-bit input uses at most C log₂(n+2) work bits and the machine halts. Acceptance is a final state, not a long output tape usable as memory. A halting machine in this model has only polynomially many possible configurations on a fixed input, so its time is automatically polynomial. P is the class of languages decided by uniform deterministic Turing machines in O((n+2)ᶜ) time for some fixed c. Circuit Value receives an explicit topologically ordered DAG of AND, OR, and NOT gates, Boolean input values, and one designated output gate, and asks whether its value is 1. The entire gate and input encoding counts toward n; malformed encodings are rejected. There are no random bits, oracle, advice, auxiliary catalytic tape, or restrictions on circuit depth.''',
 answer_criterion='Answer yes by giving a logarithmic-workspace decider for Circuit Value or otherwise proving P⊆L. Answer no by proving that some fixed language in P has no O(log n)-space deterministic decider. A lower bound on memory used by one evaluation strategy, or on algorithms with an extra time restriction, does not rule out all of L.',
 context=[
  paragraph('A polynomial-time algorithm may keep a large table of intermediate results. A small-space algorithm may instead recompute information when it is needed. The question asks whether this tradeoff can always reduce working memory to a constant number of input indices and counters. The input remains available for repeated reading, so this is a different model from a single-pass streaming algorithm.'),
  paragraph('Circuit Value is a concrete complete problem for P under logarithmic-space reductions. Evaluating gates in topological order uses polynomial time and readily stores their values. An alternative may recompute gate values, but shared dependencies make naive recursive expansion expensive in both stack space and repeated work. Completeness says that a logarithmic-space solution to this one task would extend to all polynomial-time decision problems.','parallel'),
  paragraph('Logarithmic workspace already forces polynomial time for a halting deterministic machine: revisiting the same full configuration would produce an infinite loop. Consequently the question does not grant unlimited superpolynomial recomputation while retaining membership in L. The polynomial time exponent can nevertheless depend on the machine, so lower bounds for one fixed time budget are insufficient.','course'),
  paragraph('L⊆NL⊆P, where NL allows nondeterministic logarithmic-space computation. A proof that L≠NL would therefore separate L from P, but L=NL would not itself settle L=P. Reingold resolves undirected reachability in logarithmic space; directed reachability remains a separate NL-complete target, and Circuit Value represents the potentially larger class P.','connectivity'),
  paragraph('Recent time-to-space simulation substantially improves general upper bounds without reaching logarithmic space. Williams simulates time t in O(√(t log t)) space and obtains an analogous square-root-type space bound for Boolean circuit evaluation. With polynomial t, the guarantee is still polynomial space. This advances the tradeoff while leaving the much smaller O(log n) target unresolved.','simulation')],
 why='This is a fundamental question about how much memory efficient computation needs. It asks whether all of polynomial-time reasoning can be reorganized around logarithmic working storage, and connects circuit evaluation, graph reachability, recomputation, and the structure of space-bounded complexity.',
 importance=dict(score=98, method='editorial', assessed_on='2026-09-10', reason='A canonical unresolved boundary between time and memory, asking whether any polynomial-time decision problem intrinsically needs more than logarithmic workspace.'),
 progress=[
  step('1975','Ladner’s logspace completeness theorem for Circuit Value supplies a universal P-complete problem for the question.','parallel'),
  step('2005–2008','Reingold proves undirected connectivity is in L. This resolves a major special case of low-memory graph computation without handling all directed reachability or P-complete problems.','connectivity'),
  step('2025–2026','Williams obtains the O(√(t log t)) deterministic space simulation and square-root-type circuit-evaluation space bounds. These remain far above logarithmic space in the general case.','simulation'),
  step('2026','Blais’s logarithmic-space notes explicitly state that strictness between these basic classes remains unknown and fix the read-only-input convention needed to formulate the question.','course')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2019,'https://www.math.ias.edu/files/Book-online-Aug0619.pdf','Chapter 14, especially Section 14.1, basic space complexity and open separations'),
  ref('parallel','Limits to Parallel Computation: P-Completeness Theory','Raymond Greenlaw; H. James Hoover; Walter L. Ruzzo',1995,'https://homes.cs.washington.edu/~ruzzo/papers/limits.pdf','Chapter 6 and Theorem 4.2.2, Circuit Value completeness under logarithmic-space reductions'),
  ref('connectivity','Undirected Connectivity in Log-Space','Omer Reingold',2008,'https://omereingold.wordpress.com/wp-content/uploads/2014/10/sl.pdf','Author version 3 May 2008; Journal of the ACM 55(4), Article 17; DOI 10.1145/1391289.1391291'),
  ref('simulation','Simulating Time With Square-Root Space','R. Ryan Williams',2025,'https://arxiv.org/abs/2502.17779v1','STOC 2025; multitape time-space and Boolean-circuit evaluation bounds; JACM 73(3), Article 16 (2026), DOI 10.1145/3798104'),
  ref('course','Logarithmic Space','Eric Blais',2026,'https://cs.uwaterloo.ca/~eblais/cs365/w26/L-and-NL','University of Waterloo CS 365, Winter 2026, Chapter 18; machine model, L⊆NL⊆P, and unknown strictness')],
 status='source_open', status_note='Explicitly unresolved in the space-complexity sources and Winter 2026 course notes. Research through 10 September 2026 found no equality or separation. Recent square-root-space simulation and undirected-connectivity algorithms do not meet the general logarithmic-space target.', formulation_reviewed_on='2026-09-10')
