import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('nearly-linear-general-sparse-linear-systems',
 id='TCS-6585', title='Nearly linear-time solution of general sparse linear systems',
 area='Optimization and numerics', criterion='resources', question_type='yes_no',
 formal='For every fixed integer c≥1, does there exist a uniform randomized classical algorithm A_c with the following guarantee? Given n≥2, a nonsingular rational n×n matrix A with m nonzero entries, a nonzero rational vector b, and an integer 1≤p≤c·ceil(log_2 n), output an explicit rational vector x̂ such that ||Ax̂−b||_2≤2^(−p)||b||_2 with probability at least 2/3. Each numerator and positive denominator of A and b has at most c·ceil(log_2 n) binary digits, and the spectral condition number κ_2(A) is promised at most n^c. The worst-case running time must be O_c(m log^(d_c)n) for some constant d_c independent of the input.',
 definitions='The input lists the row index, column index and rational value of each nonzero coefficient, without duplicate positions, together with the n entries of b; hence n≤m≤n². The Euclidean norm is ||v||_2=(Σ_i v_i²)^(1/2), and κ_2(A)=σ_max(A)/σ_min(A), the ratio of its largest and smallest singular values. Nonsingularity makes the denominator positive. A may be nonsymmetric, indefinite and unrelated to a graph Laplacian. The algorithm need only meet its guarantee on promised inputs; it is not asked to certify the condition-number promise. Computation uses a word RAM with Θ(log n)-bit words, conventional arithmetic, comparison, bit operations and memory access; all operations on longer numbers, preprocessing, random-bit generation and writing the output are charged. No operation on an arbitrary real number has unit cost. Converting word operations to bit operations changes only polylogarithmic factors. Constants and the fixed program may depend on c, but neither nonuniform advice depending on n nor a supplied inverse or preconditioner is allowed. Here ε=2^(−p); this is the polynomial-condition, inverse-polynomial-accuracy regime of the near-input-size target.',
 answer_criterion='Give such a finite-precision algorithm for every fixed c, or prove that the specified guarantee is impossible for some fixed c. A conditional lower bound must state its unproved assumption and is progress rather than an unconditional negative answer. An exact-real arithmetic count, performance only on a structured matrix class, implicit quantum-state output, or a bound with polynomial dependence on κ instead of only polylogarithmic overhead in this regime does not settle the question.',
 context=[
  paragraph('Solving Ax=b is a basic operation inside scientific simulation, optimization and data analysis. A sparse input can be read and multiplied by a vector without scanning all n² matrix positions. The question is whether solving one system can always be comparably inexpensive, up to powers of logarithms. Peng and Vempala frame the general complexity problem around exploiting sparsity while also controlling numerical precision, rather than treating arithmetic on exact real numbers as free.','pv'),
  paragraph('The target fixes a residual norm because different meanings of approximate solution can conceal different costs. If x*=A^(-1)b, the elementary inequality ||x̂−x*||_2/||x*||_2≤κ_2(A)·||Ax̂−b||_2/||b||_2 relates residual error to forward error. Thus a tiny residual need not mean an equally tiny solution error. For instance, A=diag(1,δ), b=(1,δ) and x̂=(1,0) have residual δ while the second solution coordinate is wrong by one. The condition promise and requested accuracy make this dependence explicit.'),
  paragraph('Nearly linear solvers already exist for major structured families. Spielman and Teng establish such algorithms for symmetric diagonally dominant systems using preconditioning and graph structure. Their guarantee is naturally expressed in the matrix energy norm. For positive-definite systems, norm comparisons relate this guarantee to residual accuracy, with conditioning affecting the required tolerance. An arbitrary sparse matrix lacks the diagonal-dominance structure that supports this machinery.','sdd'),
  paragraph('Peng and Vempala’s SODA 2021 result breaks the matrix-multiplication barrier for sufficiently sparse, polynomially conditioned systems. They implement a randomized block Krylov approach using structured factorizations and a numerical-stability analysis. This is why merely asking for a sparse solver faster than matrix multiplication would be an obsolete open question. The stronger near-input-size target remains far beyond that theorem.','pv'),
  paragraph('Nie improves the required anti-concentration bounds for random Krylov matrices. His STOC 2022 result yields a bound of Õ(m^((ω−2)/(ω−1))n²) in the polynomial-conditioning and precision regime. For m=Õ(n), this becomes Õ(n^((3ω−4)/(ω−1))). The paper’s numerical exponent 2.2716 uses the matrix-multiplication bound available at that time; it is not a claim about today’s best numerical value of ω. Either expression remains far above linear for very sparse inputs.','nie'),
  paragraph('The distinction between a sparse matrix and a structurally easy sparse matrix is sharpened by Ding, Kyng, Probst Gutenberg and Zhang. They reduce general linear equations with polynomially bounded integer coefficients and conditioning to Laplacians of two-dimensional simplicial complexes while preserving sparsity up to logarithmic factors. Consequently, extending graph-Laplacian techniques to those higher-dimensional Laplacians would already have general consequences. This is a completeness reduction, not an unconditional proof that a near-linear solver cannot exist.','complexes'),
  paragraph('The Simons workshop report, revised in August 2026, calls for broader classes of scalably solvable systems and studies the finite-precision behavior of iterative methods. Its benchmark questions are more focused than a universal worst-case solver, and its discussion of preconditioning makes clear that constructing a useful preconditioner is itself part of the computational task. The present card is an explicit editorial formulation of the general complexity target; it is not attributed to a numbered conjecture in that report.','workshop'),
  paragraph('The output requirement also matters. An explicit n-vector is compatible with nearly linear time because a nonsingular n×n input has at least n nonzeros. Returning only access to a vector, a few observables, or a quantum state encoding its normalized coordinates changes the task. Conversely, demanding an exact rational solution could introduce much larger output encodings; the specified numerical approximation avoids building that extra requirement into the question.')],
 why='This tests whether sparsity and moderate conditioning suffice for solving linear equations at essentially the cost of reading them. A resolution would clarify the limits of graph-based solvers, preconditioning and numerical subroutines used throughout algorithms and optimization.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A fundamental input-size complexity question for one of the most widely used computational primitives, with meaningful positive results for structured classes and general reductions from apparently special systems.'),
 progress=[
  step('2004–2014','Spielman and Teng develop nearly linear algorithms for graph-structured and symmetric diagonally dominant systems; the expanded solver paper appears in SIAM J. Matrix Analysis and Applications in 2014.','sdd'),
  step('2020–2021','Peng and Vempala give a finite-precision general sparse-system algorithm faster than matrix multiplication; the July 2020 preprint is presented at SODA 2021.','pv'),
  step('2021–2022','Nie strengthens matrix anti-concentration and improves the block Krylov solver. The November 2021 preprint, revised in December, appears at STOC 2022.','nie'),
  step('2022-06-28','Ding, Kyng, Probst Gutenberg and Zhang publish a sparsity-preserving reduction from general equations to Laplacians of two-dimensional simplicial complexes.','complexes'),
  step('2026-08-21','The Simons workshop report is revised to reflect status through 20 August, retaining questions about extending scalable solvers and understanding finite-precision iterative methods. It does not give a universal nearly linear algorithm.','workshop')],
 references=[
  ref('pv','Solving Sparse Linear Systems Faster than Matrix Multiplication','Richard Peng; Santosh Vempala',2021,'https://arxiv.org/abs/2007.10254','SODA 2021, pp. 504–521, DOI 10.1137/1.9781611976465.31; preprint v2, 7 January 2021; finite-precision block Krylov solver; expanded JACM 2025 version DOI 10.1145/3767721'),
  ref('sdd','Nearly Linear Time Algorithms for Preconditioning and Solving Symmetric, Diagonally Dominant Linear Systems','Daniel A. Spielman; Shang-Hua Teng',2014,'https://epubs.siam.org/doi/10.1137/090771430','SIAM Journal on Matrix Analysis and Applications 35(3); arXiv:cs/0607105; energy-norm approximation, with STOC 2004 precursor'),
  ref('nie','Matrix anti-concentration inequalities with applications','Zipei Nie',2022,'https://arxiv.org/abs/2111.05553','STOC 2022; preprint v2, 2 December 2021; §1.4, Theorem 1.10 and subsequent solver analysis'),
  ref('complexes','Hardness Results for Laplacians of Simplicial Complexes via Sparse-Linear Equation Complete Gadgets','Ming Ding; Rasmus Kyng; Maximilian Probst Gutenberg; Peng Zhang',2022,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2022.53','ICALP 2022, 53:1–53:19, published 28 June; reduction preserves sparse-instance complexity and high accuracy'),
  ref('workshop','Linear Systems and Eigenvalue Problems: Open Questions from a Simons Workshop','Noah Amsel; Yves Baumann; Paul Beckman; Peter Bürgisser; Chris Camaño; Tyler Chen; Edmond Chow; Anil Damle; Michal Derezinski; Mark Embree; Ethan N. Epperly; Robert Falgout; Mark Fornace; Anne Greenbaum; Chen Greif; Diana Halikias; Zhen Huang; Elias Jarlebring; Yiannis Koutis; Daniel Kressner; Rasmus Kyng; Jörg Liesen; Jackie Lok; Raphael A. Meyer; Yuji Nakatsukasa; Kate Pearce; Richard Peng; David Persson; Eliza Rebrova; Ryan Schneider; Rikhav Shah; Edgar Solomonik; Nikhil Srivastava; Alex Townsend; Robert J. Webber; Jess Williams',2026,'https://arxiv.org/abs/2602.05394','Version 3, 21 August 2026; §2.1 broader scalable solver classes, §2.5 preconditioning and §2.6 finite-precision Krylov methods')],
 status='source_open', status_note='Checked through 10 September 2026. This is an editorial, fully specified near-linear target in the polynomial-conditioning and precision regime, not a named positive conjecture. The faster-than-matrix-multiplication problem has already been solved. The August 2026 report discusses broader scalable solvers but does not claim this universal guarantee; the simplicial-Laplacian reduction is not a general running-time lower bound.', formulation_reviewed_on='2026-09-10')
