import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('exact-general-two-receiver-broadcast-capacity',
 id='TCS-6665',title='The capacity region of a general two-receiver broadcast channel',area='Coding and information theory',criterion='characterization',question_type='exact_value',
 formal='Determine the weighted capacity F(W,λ)=sup{λR₁+(1−λ)R₂:(R₁,R₂)∈C(W)} for every finite-alphabet discrete memoryless broadcast channel W(y,z|x) with rational transition probabilities and every rational λ∈[0,1]. C(W) is the capacity region for two independent private messages, vanishing average decoding error, and no feedback. Require a characterization admitting certified evaluation to arbitrary accuracy as specified below.',
 definitions='The nonempty finite alphabets X,Y,Z and the full table of nonnegative rational numbers W(y,z|x), summing to one for each x, are explicitly given. Over n uses, the conditional law is ∏_{t=1}^n W(y_t,z_t|x_t). Independent messages M₁ and M₂ are uniform on sets of sizes K₁ and K₂. One deterministic encoder, knowing both messages, sends xⁿ=f(M₁,M₂); receiver 1 observes only Yⁿ and estimates M₁, while receiver 2 observes only Zⁿ and estimates M₂. The average error is Pr[the first estimate is wrong or the second estimate is wrong], averaged over both messages and channel randomness. A rate pair is achievable if there are codes with block lengths tending to infinity, error tending to zero, and liminf (log₂Kᵢ)/n≥Rᵢ for i=1,2. C(W) is the closure of achievable nonnegative pairs. There is no common message, feedback, receiver communication, secrecy constraint, input-cost constraint or restriction on code complexity. Arbitrary dependence among a codeword’s symbols and time sharing are allowed. C(W) is compact, convex and downward closed; its support values for all rational λ determine it. Rational channel laws make the evaluation task a finite-input question.',
 answer_criterion='Give a matching achievability and converse characterization together with one terminating algorithm that, on input (W,λ,p), where p≥1 is an integer, outputs rational ℓ≤u with u−ℓ≤2⁻ᵖ and ℓ≤F(W,λ)≤u. No efficiency bound or single-letter restriction is imposed. A finite-dimensional formula with justified auxiliary-cardinality bounds, or a multiletter characterization with an effective certified convergence bound, would qualify. A bare limit over all block codes, an unevaluated regularization without an error bound, or numerically close inner and outer estimates does not. A proof that such uniform certified evaluation is impossible would instead settle the computability obstruction to this formulation.',
 context=[
  paragraph('A broadcast channel has one transmitter that knows both messages and two receivers with different observations. This differs from an interference channel, whose transmitters know separate messages. The difficulty is to use one sequence of transmitted symbols for two purposes simultaneously: some structure can help both receivers, while other structure must carry information tailored to only one. A capacity region records all achievable tradeoffs, not just the best sum of rates.','marton'),
  paragraph('The two point-to-point capacities alone do not determine this tradeoff. If a noiseless binary symbol X is delivered identically to both receivers, each receiver separately has capacity one, but independent private messages must satisfy R₁+R₂≤1. If X instead consists of two bits and each receiver gets its own bit, the region is the square 0≤R₁,R₂≤1. Both examples have the same individual capacities and different joint possibilities.'),
  paragraph('Marton’s coding method introduces auxiliary random variables describing private and shared layers and uses correlated codebooks to coordinate their information. Its inner region is achievable, so it gives a lower bound on capacity. For important structured channel classes it is exact, but neither efficient evaluation of that inner region nor optimality on those classes determines the general answer.','marton'),
  paragraph('Gohari and Anantharam establish finite auxiliary-cardinality bounds for Marton’s region, turning the previously unrestricted optimization into a computable finite-dimensional problem. They also show that Marton’s inner region and the Nair–El Gamal outer region differ for some channels. A gap between an achievable region and an outer bound alone does not reveal which bound is loose; it is not evidence that an intermediate numerical value is capacity.','cardinality'),
  paragraph('There is already an exact multiletter perspective: applying Marton’s construction to successively larger product channels and regularizing recovers the operational capacity region. Geng, Gohari, Nair and Yu develop this approach and establish new special cases. The obstacle in the present formulation is a certified finite answer: an asymptotic union without an effective convergence guarantee does not tell us how many channel uses must be examined for a requested accuracy.','product'),
  paragraph('Huang, Liu and Liu’s August 2026 preprint claims strict suboptimality of the full one-letter Marton region. It first finds a ternary-input example with a fixed-input-distribution advantage for two-letter coding, supported by interval-arithmetic bounds. A separate constraint-removal construction then produces a finite unconstrained channel with M(W⊗W)>2M(W), where M is Marton’s maximum private-message sum-rate. The unconstrained example has an enlarged alphabet; the result should not be stated as an unconstrained ternary-input counterexample.','suboptimal'),
  paragraph('That claimed inequality means a two-use code can beat the one-letter inner bound after normalizing rates per use. It does not compute capacity: further block lengths may improve the region again, and a matching converse is still needed. The paper explicitly retains the general capacity question as open. Its numerical certificates and auxiliary construction have not been independently rerun as part of this card.','suboptimal'),
  paragraph('On the converse side, Gohari, Liu and Nair’s ISIT 2026 work introduces two auxiliary receivers to strengthen outer bounds. These are hypothetical observers used in the proof, not additional terminals allowed in the communication model. Their reported bounds improve the sum-rate upper bound for examples such as the binary skew-symmetric broadcast channel, while still leaving an inner/outer gap.','outer'),
  paragraph('Finding globally optimal numerical values is also separate from deriving the correct region. Dou and coauthors develop Blahut–Arimoto-style methods for evaluating inner and outer bounds, with convergence statements tied to the optimization’s structure. Such methods help explore examples, but convergence to a local optimum or to an optimum of an unproved bound is not a capacity theorem.','evaluation')],
 why='One of the smallest communication networks whose full capacity region is unknown. It asks for the basic law governing simultaneous transmission of independent information to different receivers, with consequences for coding methods and converse techniques throughout network information theory.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A central multiuser capacity problem with a precisely defined rate region, decades of partial characterizations and recent challenges to the longstanding candidate inner bound.'),
 progress=[
  step('1979','Marton develops the general achievable region based on correlated auxiliary codebooks.','marton'),
  step('2009–2012','Gohari–Anantharam prove finite cardinality bounds and computability of Marton’s inner region, while exhibiting gaps from a known outer region.','cardinality'),
  step('2014','Geng and coauthors study product channels, regularization and new classes where Marton is optimal.','product'),
  step('2024-02-20','Dou and coauthors publish numerical algorithms for inner and outer bounds; these evaluate bounds rather than settle their tightness.','evaluation'),
  step('2026','Gohari–Liu–Nair obtain stronger outer bounds using two auxiliary receivers, with strict improvements on example channels.','outer'),
  step('2026-08-20','Huang–Liu–Liu post a claimed counterexample to one-letter Marton optimality, first with an input-distribution constraint and then on an enlarged unconstrained channel. The full capacity region remains unknown.','suboptimal')],
 references=[
  ref('marton','A Coding Theorem for the Discrete Memoryless Broadcast Channel','Katalin Marton',1979,'https://www.seas.ucla.edu/csl/files/temp/DBCAchievability.pdf','IEEE Transactions on Information Theory 25(3):306–311; original achievable region and special cases'),
  ref('cardinality','Evaluation of Marton’s Inner Bound for the General Broadcast Channel','Amin Aminzadeh Gohari; Venkat Anantharam',2012,'https://arxiv.org/abs/0904.4541','IEEE Transactions on Information Theory 58(2):608–619, DOI 10.1109/TIT.2011.2169537; auxiliary-cardinality bounds and inner/outer mismatch'),
  ref('product','On Marton’s Inner Bound and Its Optimality for Classes of Product Broadcast Channels','Yanlin Geng; Amin Gohari; Chandra Nair; Yuanming Yu',2014,'https://doi.org/10.1109/TIT.2013.2285925','IEEE Transactions on Information Theory 60(1):22–41; multiletter extension, special product-channel capacity results and limitations of the UV outer bound'),
  ref('evaluation','Blahut–Arimoto Algorithms for Inner and Outer Bounds on Capacity Regions of Broadcast Channels','Yanan Dou; Yanqing Liu; Xueyan Niu; Bo Bai; Wei Han; Yanlin Geng',2024,'https://pmc.ncbi.nlm.nih.gov/articles/PMC10969477/','Entropy 26(3), 178; DOI 10.3390/e26030178; published 20 February; convergence conditions and numerical bound evaluation'),
  ref('outer','A Two Auxiliary Receiver Outer Bound to the Capacity Region of a Two-Receiver Discrete Memoryless Broadcast Channel','Amin Gohari; Yi Liu; Chandra Nair',2026,'https://chandra.ie.cuhk.edu.hk/pub/papers/BC/GK-outer.pdf','ISIT 2026, DOI 10.1109/ISIT62367.2026.11653844; Theorems 7–8, §IV examples, and full-version Theorem 9'),
  ref('suboptimal','Sub-optimality of Marton’s Inner Bound for the Two-Receiver Broadcast Channel','Mian Huang; Yanxiao Liu; Yi Liu',2026,'https://arxiv.org/abs/2608.19869','v1, 20 August; Theorem 4 removes the input constraint, Theorem 5 states unconstrained suboptimality; §III.D gives an explicit enlarged-alphabet realization')],
 status='source_open',status_note='Checked through 10 September 2026. The general capacity question remains open in the checked primary literature, including the August 2026 paper. That paper’s narrower Marton-suboptimality claim is identified as a preprint result; accepting it would not solve the full characterization or certified-evaluation task.',formulation_reviewed_on='2026-09-10')
