import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('two-anticomplete-paths-unrestricted-terminal-pairing',
 id='TCS-0595',title='Two anticomplete paths with unrestricted terminal pairing',
 area='Graph theory and graph algorithms',criterion='decision',question_type='yes_no',
 formal='Is there a deterministic polynomial-time algorithm that, given a finite simple undirected graph G and four distinct pairwise nonadjacent vertices a,b,c,d, decides whether G contains two vertex-disjoint paths with no edge between their vertex sets, whose four endpoints are exactly a,b,c,d? Any of the three pairings of the four terminals is accepted.',
 definitions='The input is an n×n adjacency matrix together with four vertex indices. A path is a sequence of distinct vertices with an edge between each consecutive pair. The two paths must have disjoint vertex sets P and Q and satisfy E(G)∩(P×Q)=∅. Each terminal is the endpoint of exactly one path; none is an internal vertex. The accepted endpoint pairings are {ab,cd}, {ac,bd}, and {ad,bc}, with no prescribed source/sink partition. Paths can equivalently be required to be induced: replace either path by a shortest path between its endpoints in its own vertex set. This does not create an edge to the other path. Polynomial time means that one uniform deterministic Turing machine answers correctly on every valid input in at most C(n+1)^k steps for fixed constants C,k. Invalid encodings or nonindependent terminal sets are rejected by this formulation. There are no restrictions on the degree, genus, or connectivity of G.',
 answer_criterion='Give such a polynomial-time algorithm with a proof, or prove that none exists. An NP-hardness proof for this exact unrestricted-pairing language would establish a negative answer under P≠NP, and must be labelled conditional accordingly. Hardness for a single prescribed pairing or for a prescribed source/sink partition is insufficient.',
 context=[
  paragraph('Ordinary disjoint routing prevents the paths from sharing vertices. Here even an unused graph edge between the two routes is forbidden. Thus one path must avoid the entire neighborhood of the other, and deciding which vertices to reserve can constrain a distant part of the graph.'),
  paragraph('The freedom to choose partners is the point of the question. Four terminals have three perfect pairings. A graph is accepted if at least one pairing works. A hard instance for a prescribed pairing may have an easy solution using another pairing; therefore simply invoking the hardness of any individual pairing does not classify their union.'),
  paragraph('The stable-terminal restriction isolates the unresolved case in Trotignon’s question. To see why an edge between two terminals helps, its endpoints would have to lie on the same solution path. That path can be shortened to the edge itself, leaving a reachability test for the remaining two terminals after deleting the closed neighborhoods of the first pair. Testing terminal edges handles these nonindependent cases.', 'problem'),
  paragraph('This is a small routing primitive relevant to detecting induced minors, where a model must preserve both adjacency and nonadjacency between its connected pieces. An algorithm would allow a search to postpone the choice of which terminal belongs with which other terminal. A hardness proof would show that this flexibility still cannot overcome the anticompleteness constraint.', 'problem'),
  paragraph('There are useful tractable restrictions. For graphs of any fixed bounded genus, polynomial algorithms for prescribed induced paths also solve this question by trying the three pairings. Conversely, the 2025 hardness theorem even for string graphs concerns prescribed pairs or a source/sink partition. The latter permits only two of our three pairings.', 'recent')],
 why='This isolates a basic difference between specifying two routes and merely asking for two separated connections among four terminals. It is a compact test of how much freedom in terminal assignment can change the complexity of induced graph structure detection.',
 importance=dict(score=77,method='editorial',assessed_on='2026-09-10',reason='A concrete four-terminal primitive at the boundary of tractable routing and induced-containment hardness. Its importance comes from a missing basic complexity classification and its role in induced-minor detection, rather than from a large parameter range.'),
 progress=[
  step('Baseline','The problem is in NP: the two vertex sequences form a certificate of length O(n log n), and adjacency, disjointness, terminal coverage, and absence of cross edges can all be checked in polynomial time. This is an immediate consequence of the stated definition, not a polynomial-time decision algorithm.','problem'),
  step('2019','Trotignon explicitly asks for the complexity of the four-terminal problem with no prescribed pairing in Section 4.5 of the Dagstuhl report, printed page 140. The card makes its polynomial-time membership question explicit.','problem'),
  step('2025','Aboulker, Bonnet, Picavet, and Trotignon prove NP-completeness for induced two-path routing even in a restricted class of string graphs. Their stronger flow theorem fixes two source terminals and two sink terminals. It does not automatically classify the language accepting all three perfect pairings.','recent'),
  step('2026-09 review','The exact unrestricted-pairing question remains supported by its 2019 open-problem source. The checked recent theorem concerns different terminal constraints; no subsequent primary-source resolution of this exact question was located.','recent')],
 references=[
  ref('problem','Computing disjoint paths, in Graph Colouring: from Structure to Algorithms','Nicolas Trotignon; report edited by Maria Chudnovsky, Daniel Paulusma, and Oliver Schaudt',2019,'https://drops.dagstuhl.de/entities/document/10.4230/DagRep.9.6.125','Dagstuhl Seminar 19271, Section 4.5, printed p. 140. The problem statement requires NO edges between the paths; the following remark omits “no”.'),
  ref('recent','Induced Disjoint Paths Without an Induced Minor','Pierre Aboulker; Édouard Bonnet; Timothé Picavet; Nicolas Trotignon',2025,'https://drops.dagstuhl.de/storage/00lipics/lipics-vol334-icalp2025/html/LIPIcs.ICALP.2025.4/LIPIcs.ICALP.2025.4.html','ICALP 2025, Article 4; Section 1 defines linkage and S–T flow separately; Theorems 1–2. Full preprint: arXiv:2502.05289v1, 7 February 2025.')],
 status='source_open',status_note='Explicitly open in the 2019 problem source. Primary literature checked through 10 September 2026 did not provide a resolution for all three terminal pairings. The 2025 hardness results for prescribed pairs and S–T flow are kept separate; the evidence date of the original open statement is retained.',formulation_reviewed_on='2026-09-10')
