import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('noninteractive-zero-knowledge-from-one-way-functions',
 id='TCS-6552',title='Noninteractive zero knowledge from one-way functions',area='Cryptography',criterion='assumptions',question_type='yes_no',
 formal='Does the existence of classical one-way functions imply reusable, adaptively secure noninteractive zero-knowledge arguments for circuit satisfiability in the honestly generated common-reference-string model, with computational soundness and computational zero knowledge against nonuniform polynomial-size adversaries?',
 definitions='A one-way function is a uniformly polynomial-time computable family f_n on uniform n-bit inputs with polynomial-length outputs, such that every nonuniform randomized polynomial-size adversary given 1ⁿ and f_n(X) finds any n-bit preimage with negligible probability. Circuit satisfiability has statements x encoding Boolean circuits and witnesses w assigning their inputs, with R(x,w)=1 exactly when the circuit outputs 1. A proposed argument consists of uniform algorithms Setup(1^λ,1^B)→crs, Prove(crs,x,w)→π, and Verify(crs,x,π)→{0,1}; their time and output length are polynomial in λ+B, where B bounds statement and witness lengths. Setup is independent of the later statements; its private coins are not published. For every polynomial B=B(λ), completeness error is negligible uniformly over valid (x,w) of length at most B. Adaptive computational soundness means that every nonuniform polynomial-time adversary given crs has negligible probability of outputting an unsatisfiable x and an accepted π. Reusable computational zero knowledge means there exist uniform polynomial-time SimSetup and SimProve such that no nonuniform polynomial-time distinguisher separates these experiments: (i) it receives honest crs and can adaptively request Prove(crs,x,w) for polynomially many valid pairs; (ii) it receives simulated crs from SimSetup, and each valid query is answered by SimProve using the simulation trapdoor and x, without receiving w. Both experiments reject invalid queries, and the distinguisher retains arbitrary polynomial-size auxiliary information. All negligible bounds are in λ: for each a>0 the error is eventually below λ^{-a}. Only crs is public in the real system, and one proof message is sent for each statement. No random oracle, extra cryptographic assumption, online verifier challenge, proof of knowledge or succinctness requirement is included. Circuit satisfiability covers every NP language through witness-preserving polynomial reductions.',
 answer_criterion='Prove the stated existence implication, or refute it in the ordinary computational model. The result may use the code of the one-way function and need not be black-box. A construction adding LWE, an appropriate batch argument, trapdoor hashing, or strong extra complexity assumptions does not suffice unless those ingredients are themselves derived from the same ordinary OWF premise. An interactive proof, a witness-indistinguishable argument, or a single-theorem result without a justified reusable upgrade is not the specified conclusion.',
 context=[
 paragraph('An NP witness can be easy to check and sensitive to reveal. For circuit satisfiability, publishing a satisfying assignment gives a verifier complete evidence, but also exposes every bit of that assignment. Zero knowledge asks for convincing evidence whose visible distribution can instead be simulated without the assignment. It formalizes the requirement that verification disclose no additional information beyond the statement’s truth.'),
 paragraph('The common reference string is an explicit resource. An honest setup algorithm produces public parameters before any statements are selected. After that setup, a prover sends one message that anyone can verify. The setup may retain randomness while generating the string, but that randomness is not handed to users. The simulation trapdoor exists only in the security experiment. This model differs from asking for a noninteractive system with no setup at all.'),
 paragraph('The card allows computational soundness: a computationally unbounded attacker might find a false accepted proof, but efficient attackers must not. Such a system is called an argument. It also asks for a reusable reference string, with statements chosen after seeing the string and earlier proofs. These choices make the target precise without requiring short proofs or a way to extract a witness from a successful prover.'),
 paragraph('The classical Goldreich–Micali–Wigderson theorem already supplies interactive zero-knowledge proofs for NP from one-way functions. Interaction gives the verifier a role in challenging what the prover has prepared. The inherited Damgård–Nielsen survey explicitly asks whether one-way functions suffice in the noninteractive setting. That survey discusses a proof-system version with stronger soundness; the argument target here asks for protection only against efficient cheating.','primary'),
 paragraph('Known positive constructions use more structure. Peikert and Shiehian construct NIZK for NP from ordinary LWE in 2019. Their method builds hash families whose correlation-intractability property supports a sound Fiat–Shamir transformation. The point is a proved property of a specially constructed family, not simply substituting an arbitrary hash function for a verifier’s random challenge. LWE is a sufficient assumption, but it has not thereby been derived from arbitrary one-way functions.','lwe'),
 paragraph('Bradley, Waters and Wu show that an adaptively sound noninteractive batch argument for NP, together with a one-way function, yields NIZK. Their TCC 2024 result also studies how to obtain the needed adaptive soundness from other batch-argument guarantees. The title “Batch Arguments to NIZKs from One-Way Functions” must be read with its starting resource intact: the batch argument is an additional primitive, rather than something their theorem constructs from a bare one-way function.','barg'),
 paragraph('Branco and coauthors develop a vector-trapdoor-hash approach, with an updated version in March 2026. Their constructions use either LWE or a combination of DDH and LPN assumptions. The initial black-box constructions provide single-theorem zero knowledge, and their multi-theorem upgrade uses cryptography in a non-black-box way. This distinction is compatible with the target here, which allows any construction technique but requires the OWF-only assumption and reusable security.','vtdh'),
 paragraph('Chen, Rothblum and Tell pursue a different route through derandomization and strong computational hardness. Their construction combines a subexponentially secure one-way function with an additional complexity assumption and obtains computational soundness against uniform adversaries. It is progress toward avoiding highly structured cryptographic primitives, but the extra hardness and the adversary convention both differ from this card.','derandomization'),
 paragraph('Recent results in the reverse direction should not be read as a construction. Chakraborty, Hulett, Khurana and Tomer show in February 2026 that nontrivial NIZK arguments imply one-way functions under the hypothesis that NP is not contained in ioP/poly, even in a broad high-error regime. Their amplification consequences improve existing weak NIZK systems. Neither direction starts with an ordinary OWF alone and produces the desired NIZK system.','reverse'),
 paragraph('Another 2026 result gives succinct zero-knowledge proofs using one-way functions as black boxes. Florentz–Konopnicki and Rothblum’s protocol is interactive: its theorem explicitly bounds a number of public-coin rounds that depends on the relation’s parameters. Its noninteractive commitment component does not make the whole protocol noninteractive. A resolution of this card would isolate exactly how much cryptographic structure is needed to remove that interaction after a single reusable setup.','interactive')],
 why='Determine whether the minimal assumption supporting basic cryptography is sufficient for reusable, publicly verifiable proofs that reveal no witness and require no online interaction.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A fundamental boundary between interactive and noninteractive zero knowledge, with implications for the assumptions behind privacy-preserving proof systems and cryptographic transformations.'),
 progress=[
 step('1986','Goldreich–Micali–Wigderson establish interactive zero knowledge for NP from one-way functions; the inherited survey distinguishes the noninteractive open question.','primary'),
 step('2019','Peikert–Shiehian construct NIZK for NP from plain LWE using correlation-intractable hashing.','lwe'),
 step('2024-09-20','The revised Bradley–Waters–Wu work derives NIZK from adaptively sound BARGs plus OWFs, retaining the extra batch-argument premise.','barg'),
 step('2025-04-03','Chen–Rothblum–Tell’s revised work gives NIZK with uniform soundness from subexponential OWFs and additional strong complexity assumptions.','derandomization'),
 step('2026-02-19','Chakraborty–Hulett–Khurana–Tomer extend conditional implications from nontrivial NIZK to OWFs and error amplification; this is not OWF-to-NIZK.','reverse'),
 step('2026-03-30','Updated vector-trapdoor-hash constructions distinguish black-box single-theorem NIZK from a non-black-box multi-theorem upgrade under stronger assumptions.','vtdh'),
 step('2026-08-11','Florentz–Konopnicki–Rothblum’s CRYPTO 2026 chapter appears online; its succinct OWF-based zero-knowledge proof remains interactive.','interactive')],
 references=[
 ref('primary','Commitment Schemes and Zero-Knowledge Protocols (2011)','Ivan Damgård; Jesper Buus Nielsen',2011,'https://homepages.cwi.nl/~schaffne/courses/crypto/2014/papers/ComZK08.pdf','Inherited reference; title page says 2011 despite filename ComZK08; pp. 28–29, Theorem 3.5 and the question immediately following it'),
 ref('lwe','Noninteractive Zero Knowledge for NP from (Plain) Learning With Errors','Chris Peikert; Sina Shiehian',2019,'https://web.eecs.umich.edu/~cpeikert/pubs/nizk-lwe.pdf','Author manuscript 5 June 2019; CRYPTO 2019, 89–114; plain LWE, with computational/statistical soundness and zero-knowledge modes'),
 ref('barg','Batch Arguments to NIZKs from One-Way Functions','Eli Bradley; Brent Waters; David J. Wu',2024,'https://eprint.iacr.org/2023/1938','TCC 2024; first posted 21 December 2023, revised 20 September 2024; adaptively sound BARG plus OWF implication'),
 ref('vtdh','Black-Box Non-Interactive Zero Knowledge from Vector Trapdoor Hash','Pedro Branco; Arka Rai Choudhuri; Nico Döttling; Abhishek Jain; Giulio Malavolta; Akshayaram Srinivasan',2025,'https://eprint.iacr.org/2024/1514','EUROCRYPT 2025, updated 30 March 2026; single-theorem constructions and multi-theorem upgrade, with LWE or DDH/LPN assumptions'),
 ref('derandomization','Fiat-Shamir in the Plain Model from Derandomization (Or: Do Efficient Algorithms Believe that NP = PSPACE?)','Lijie Chen; Ron D. Rothblum; Roei Tell',2025,'https://eccc.weizmann.ac.il/report/2024/116/','Revision 1, 3 April 2025, first posted July 2024; Corollary 1.11, subexponential OWF plus a strong extra hardness assumption; uniform adversaries'),
 ref('reverse','Non-Trivial Zero-Knowledge Implies One-Way Functions','Suvradip Chakraborty; James Hulett; Dakshita Khurana; Kabir Tomer',2026,'https://arxiv.org/abs/2602.17651','19 February 2026; Section 4 and abstract: nontrivial NIZK implies OWF assuming NP⊈ioP/poly; Section 6 treats amplification'),
 ref('interactive','Succinct Zero-Knowledge Proofs from One-Way Functions: The Blackbox Way','Eden Florentz–Konopnicki; Ron D. Rothblum',2026,'https://doi.org/10.1007/978-3-032-35424-2_6','CRYPTO 2026, 157–188, online 11 August 2026; Theorem 1.1 is a public-coin interactive protocol; ECCC25/162 revised 21 February 2026')],
 status='source_open',status_note='No construction of reusable adaptive NIZK arguments from ordinary OWFs alone, or refutation of that unrestricted implication, was found through 11 September 2026. The cited BARG, trapdoor-hash and derandomization constructions retain extra assumptions; recent OWF-only succinct proofs are interactive, and high-error characterizations run in the reverse direction.',formulation_reviewed_on='2026-09-11')
