import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('deterministic-worst-case-polylog-dynamic-connectivity',
 id='TCS-6625',title='Deterministic fully dynamic connectivity with polylogarithmic worst-case updates',
 area='Dynamic graph algorithms',criterion='resources',question_type='yes_no',
 formal='Does there exist a single deterministic data structure and fixed constants C,c,d>0 such that, for every n≥2, an initially empty undirected simple graph on vertex set [n] can be maintained under any online sequence of edge insertions, edge deletions and pairwise connectivity queries, using at most C n^d words of memory and at most C(log₂ n)^c time for each individual operation? Initialization may take at most C n^d time and depends only on n. All connectivity answers must be exact in the word-RAM model specified below.',
 definitions='An insertion insert(u,v) adds a previously absent unordered edge {u,v}, where u≠v; a deletion delete(u,v) removes an existing edge. A query connected(u,v) returns whether the current graph contains a path from u to v, with connected(u,u)=true. Updates are valid, arrive one at a time and must finish before the next operation is revealed. No future operations or advance description of the sequence is supplied. The data structure must work for every finite sequence, including sequences chosen in response to its previous behavior. The word RAM has word size w=⌈a log₂ n⌉ for a fixed constant a large enough to address its polynomial space. Unit-cost instructions are indirect reads/writes, word addition, subtraction, multiplication, integer quotient/remainder, comparisons, Boolean bit operations and shifts; arithmetic results stored in one word are reduced modulo 2ʷ where appropriate. Arbitrary-precision computation costs its constituent word operations. All maintenance, rebuilding and query work is charged to the operation performing it. The exponent c is independent of n and of the length or contents of the operation sequence. The graph is unrestricted apart from being undirected and simple; no planarity, bounded-degree or expansion promise is given.',
 answer_criterion='Construct and analyze a deterministic data structure meeting every bound, or prove that none exists in this model. A polylogarithmic amortized bound controls total work over a sequence and does not bound every operation. An expected or high-probability time bound leaves random execution outcomes and does not meet the deterministic requirement. A subpolynomial bound n^{o(1)} need not be polylogarithmic. Maintaining only insertion sequences, only deletion sequences, or only a restricted graph class is a partial result.',
 context=[
  paragraph('The difficulty is deleting an edge that belongs to a maintained spanning forest. Removing it splits one tree into two parts, but the graph might still connect those parts through an edge outside the forest. The data structure must find such a replacement quickly or correctly certify that none exists. A single deletion can expose a large cut, so simply scanning all candidate edges gives no small bound on the time of that update.'),
  paragraph('Holm, de Lichtenberg and Thorup give deterministic O(log² n) amortized operation bounds for connectivity, using a hierarchy of forests and edge levels. Their result establishes that long update sequences can be processed efficiently. The accounting permits an individual deletion to spend work paid for by other operations. Guaranteeing low latency after every deletion requires more than redistributing the same amortized accounting on paper.','amortized'),
  paragraph('Kapron, King and Mountjoy obtain polylogarithmic worst-case update time with randomization and a small error probability. Their cutset sampling technique tries to isolate a remaining edge across a cut, which can then be recovered from a compact sketch. Failure to recover an edge may mean either that the cut is empty or that the random samples missed it. Eliminating this uncertainty while keeping every update fast is part of the deterministic challenge.','montecarlo'),
  paragraph('Chuzhoy and coauthors use deterministic balanced-cut machinery to achieve n^{o(1)} worst-case update time, removing the earlier polynomial barrier. This is a major improvement but still leaves the present target open. For example, exp(√log n) is smaller than every fixed positive power of n and larger than every fixed power of log n. Thus a subpolynomial theorem does not imply the polylogarithmic bound merely by choosing a small exponent.','balanced'),
  paragraph('Meierhans and Probst Gutenberg’s SODA 2026 algorithm is Las Vegas: it maintains a correct spanning forest and achieves polylogarithmic expected worst-case update time, even against an adaptive adversary with access to its state. It alternates vertex and edge sparsification in a hierarchy. Each graph update changes the output forest by at most two edges, so maintaining the explicit answer itself does not cause large update costs. The expectation remains a distinction from the deterministic target.','core'),
  paragraph('The same paper gives a concrete sufficient condition for derandomization. If a deterministic algorithm constructs a near-linear-edge subgraph together with paths routing the original edges through it in m·polylog(m) time, with congestion at most (m/n)·polylog(m), the framework yields deterministic polylogarithmic worst-case connectivity. Congestion counts how many routed paths use the busiest retained edge. Finding any spanning forest is insufficient: its tree edges may carry far too many such paths.','core'),
  paragraph('A companion SODA 2026 result by Meierhans, Probst Gutenberg and Saranurak controls both the time and the number of vertices removed when pruning an expander after one edge deletion. This avoids a large burst of changes propagating through a hierarchy. It is an ingredient in the recent randomized progress; it does not by itself supply the deterministic sparsifier construction needed for the full conclusion.','pruning'),
  paragraph('Known lower bounds do not rule out the target. Pătraşcu and Demaine prove logarithmic amortized cell-probe lower bounds, including for connectivity on disjoint paths. Those results show that dynamic connectivity already has a real information-transfer cost in very simple graphs, but a logarithmic barrier is compatible with polylogarithmic upper bounds. The open issue is whether exact connectivity, deterministic computation and a bound on every operation can be achieved simultaneously.','lower')],
 why='A basic unresolved guarantee for dynamic graph data structures. Connectivity is both a natural maintenance problem and a source of techniques used throughout graph algorithms; combining determinism, exactness and fast individual updates would close a longstanding gap.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A foundational dynamic-graph frontier directly relevant to data structures, with a new randomized breakthrough and an explicit remaining deterministic bottleneck.'),
 progress=[
  step('1998–2001','Holm–de Lichtenberg–Thorup establish deterministic polylogarithmic amortized connectivity; the journal version gives O(log² n).','amortized'),
  step('2004–2006','Pătraşcu–Demaine establish logarithmic cell-probe lower bounds, including on disjoint paths; they do not exclude a polylogarithmic worst-case algorithm.','lower'),
  step('2013','Kapron–King–Mountjoy give a Monte Carlo structure with polylogarithmic worst-case operation time and high-probability correctness.','montecarlo'),
  step('2019–2020','Chuzhoy–Gao–Li–Nanongkai–Peng–Saranurak obtain deterministic n^{o(1)} worst-case dynamic connectivity, published at FOCS 2020.','balanced'),
  step('2026-01-07','SODA publishes Meierhans–Probst Gutenberg’s Las Vegas expected polylogarithmic worst-case algorithm and conditional deterministic reduction, first posted 9 October 2025.','core'),
  step('2026-01-07','SODA also publishes expander pruning with worst-case recourse and update bounds, an ingredient in the connectivity framework.','pruning')],
 references=[
  ref('amortized','Poly-Logarithmic Deterministic Fully-Dynamic Algorithms for Connectivity, Minimum Spanning Tree, 2-Edge, and Biconnectivity','Jacob Holm; Kristian de Lichtenberg; Mikkel Thorup',2001,'https://u.cs.biu.ac.il/~rodittl/p723-holm.pdf','Journal of the ACM 48(4):723–760, DOI 10.1145/502090.502095; connectivity hierarchy and amortized bound; STOC 1998 precursor'),
  ref('montecarlo','Dynamic graph connectivity in polylogarithmic worst case time','Bruce M. Kapron; Valerie King; Ben Mountjoy',2013,'https://doi.org/10.1137/1.9781611973105.81','SODA 2013, pp. 1131–1142; randomized cutset sampling and one-sided error'),
  ref('balanced','A Deterministic Algorithm for Balanced Cut with Applications to Dynamic Connectivity, Flows, and Beyond','Julia Chuzhoy; Yu Gao; Jason Li; Danupon Nanongkai; Richard Peng; Thatchaphol Saranurak',2020,'https://arxiv.org/abs/1910.08025','v2, 3 May 2020; FOCS 2020; deterministic n^{o(1)} worst-case connectivity and minimum-spanning-forest application'),
  ref('core','Dynamic Connectivity with Expected Polylogarithmic Worst-Case Update Time','Simon Meierhans; Maximilian Probst Gutenberg',2026,'https://arxiv.org/abs/2510.08297','SODA 2026, pp. 6184–6198, DOI 10.1137/1.9781611978971.220; Theorems 1.1 and 1.3 and §3.7; arXiv v1, 9 October 2025'),
  ref('pruning','Expander Pruning with Polylogarithmic Worst-Case Recourse and Update Time','Simon Meierhans; Maximilian Probst Gutenberg; Thatchaphol Saranurak',2026,'https://doi.org/10.1137/1.9781611978971.103','SODA 2026, pp. 2792–2823, published 7 January; worst-case pruning and applications'),
  ref('lower','Logarithmic Lower Bounds in the Cell-Probe Model','Mihai Pătraşcu; Erik D. Demaine',2006,'https://erikdemaine.org/papers/DynamicConnectivity_SICOMP/','SIAM Journal on Computing; author page and full paper; logarithmic amortized randomized lower bounds, including connectivity on disjoint paths')],
 status='source_open',status_note='Checked through 10 September 2026. The SODA 2026 connectivity paper explicitly retains deterministic polylogarithmic worst-case updates as open. Its unconditional new bound is randomized and expected; its deterministic polylogarithmic conclusion depends on the stated static low-congestion sparsifier construction. Deterministic subpolynomial worst-case bounds and polylogarithmic amortized bounds are already known.',formulation_reviewed_on='2026-09-10')
