import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('almost-linear-triangle-detection',
 id='TCS-6539',title='Almost-linear triangle detection',area='Algorithms & data structures',criterion='resources',question_type='yes_no',
 formal='Does there exist one uniform randomized word-RAM algorithm that, on every finite simple undirected graph with n vertices and m edges given by adjacency lists, decides whether a triangle exists with success probability at least 2/3 and worst-case running time (n+m+2)^{1+o(1)}?',
 definitions='A triangle is a set of three distinct vertices u,v,w for which all three unordered edges {u,v},{v,w},{w,u} are present. The input gives labelled vertices 1,…,n and explicit adjacency lists; it is promised to describe a simple undirected graph, and can be disconnected or contain isolated vertices. The RAM has words of w=⌈4 log₂(n+2)⌉ bits, random-access memory, and unit-cost word reads/writes, comparisons, Boolean operations, shifts, addition, subtraction and multiplication modulo 2ʷ, and integer division by a nonzero word. Independent random words may be generated at unit cost. Input reading and all preprocessing count toward time. The running-time bound holds for every graph and every random tape, while correctness probability is over the algorithm’s internal randomness. The o(1) is a function tending to zero as n+m tends to infinity, for this one fixed algorithm; equivalently, for every ε>0 the same algorithm eventually uses at most (n+m+2)^{1+ε} operations. There is no promise on density, degree, arboricity or triangle count. Matrix multiplication and other algebraic techniques are allowed if their implementation fits this machine model. Only one yes/no answer is required.',
 answer_criterion='Construct and analyze an algorithm meeting the stated all-input time and probability guarantees, or prove that no such algorithm exists. A deterministic O(n+m) algorithm would be an even stronger positive answer. A fixed exponent above one, an O(n²) bound that is only input-linear on dense graphs, output-sensitive listing, or an algorithm restricted to bounded-arboricity graphs does not settle the question. The target fixes the original draft’s “linear or at least almost-linear” alternative at the precise almost-linear threshold.',
 context=[
 paragraph('Triangle detection is among the smallest nontrivial pattern-finding tasks in a graph. The pattern has only three vertices, but a graph may contain an enormous number of possible triples. The question asks whether all the relevant combinations can be handled in essentially the time required to read the graph. It must also handle triangle-free instances, where an algorithm cannot stop upon finding a convenient local witness.'),
 paragraph('Detection is different from listing. A complete graph has Θ(n²) input edges and Θ(n³) triangles, so explicitly listing every triangle cannot take linear time in the input size. A yes/no answer has constant output size and faces no such output-size obstruction. Likewise, approximate counting or finding triangles in a distribution of random inputs does not supply an exact decision guarantee on every adversarial graph.'),
 paragraph('Chiba and Nishizeki give triangle listing in O(m·a(G)) time, apart from reading isolated vertices, where arboricity a(G) is the minimum number of forests needed to cover the graph’s edges. This gives linear time on any family of bounded arboricity, including planar graphs. General graphs can have arboricity of order √m, so this approach has a superlinear worst-case cost. A sparse graph can still contain a dense, difficult region.','arboricity'),
 paragraph('Alon, Yuster and Zwick improve the general sparse-graph bound using a degree threshold. Handle triangles touching a low-degree vertex by local enumeration, and use matrix multiplication on the smaller set of high-degree vertices. For an available square matrix-multiplication exponent τ, the resulting standard bound is O(n+m^{2τ/(τ+1)}), roughly O(n+m^{1.407}) at familiar current exponents. The optimization balances the cost of the two parts.','cycles'),
 paragraph('Even setting the matrix-multiplication exponent to two in this particular reduction leaves exponent 4/3 in m. Thus faster dense multiplication alone, inserted into the same degree-splitting argument, would not make the sparse algorithm almost linear. This is an observation about the upper-bound method, not a proof that a different graph algorithm cannot do better.'),
 paragraph('Abboud and Vassilevska Williams formulate a no-almost-linear triangle hypothesis and use it to derive conditional lower bounds for dynamic problems. The conjecture concerns general algorithms on logarithmic-word RAMs. Their separate combinatorial Boolean-matrix-multiplication conjecture restricts the kinds of techniques used; it should not be substituted for the unrestricted question here. Reductions transfer assumed hardness, rather than establish an unconditional superlinear lower bound.','dynamic'),
 paragraph('The distinction remains useful in current work. Kumabe and Uezato’s ICALP 2026 paper reduces triangle detection to matching certain fixed regular expressions with two backreference uses. Consequently, an almost-linear algorithm for that matching task would also give an almost-linear triangle algorithm. This illustrates why a small graph pattern can govern complexity in a seemingly unrelated setting.','regex'),
 paragraph('Search results require source checks. Dumitrescu’s March 2024 claim of faster combinatorial triangle algorithms was withdrawn three days after posting; the author states that the algorithm may fail and identifies an invalid case analysis. It is not an established improvement.','withdrawn'),
 paragraph('I also checked the parent-edge rule in Vega’s August 2025 linear-time proposal. Consider the path 0–1–2–3–4–5–6 plus edges 0–3, 3–6 and 0–6. A legal DFS follows the whole path. Its unique triangle is {0,3,6}, consisting entirely of back edges. No test restricted to a DFS parent, its child and a common neighbour can find it. A local simulation and exhaustive triple check confirm this counterexample to the stated rule; this is not a test of later replacement implementations.','oldclaim'),
 paragraph('A separate September 2026 Aegypti revision claims O(n²) time via bucket reduction. That claimed bound is not almost linear for every sparse input, even if its correctness were established. I have not adjudicated its different proof. An all-density statement must keep both n and m visible: a dense-case breakthrough and an input-linear sparse algorithm are distinct achievements.','laterclaim'),
 paragraph('A resolution would identify whether a basic three-way adjacency condition inherently requires substantial work beyond scanning an explicit graph. A positive algorithm would affect graph-pattern routines and invalidate hardness assumptions used by many reductions. A negative result would provide a major unconditional lower bound for a simple polynomial-time graph problem on a strong, standard machine model.')],
 why='Determine whether detecting the simplest cyclic graph pattern requires a superlinear amount of computation beyond reading the input.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A fundamental graph primitive and fine-grained hardness assumption with consequences for dynamic data structures, joins and string matching.'),
 progress=[
 step('1985','Chiba–Nishizeki give O(m·a(G)) triangle listing, yielding linear time for bounded-arboricity families.','arboricity'),
 step('1997','Alon–Yuster–Zwick combine degree splitting with fast matrix multiplication to improve sparse triangle detection.','cycles'),
 step('2014','Abboud–Vassilevska Williams formulate the no-almost-linear triangle hypothesis and derive conditional dynamic lower bounds.','dynamic'),
 step('2024-03-05','Dumitrescu withdraws the claimed faster combinatorial algorithm because its case analysis is invalid.','withdrawn'),
 step('2026-07','Kumabe–Uezato use triangle hardness to exclude almost-linear matching for a restricted two-use backreference class, conditionally.','regex'),
 step('2026-09-08','A separate Aegypti revision claims O(n²), which is not an almost-linear guarantee for all graph densities; correctness not adjudicated here.','laterclaim')],
 references=[
 ref('arboricity','Arboricity and Subgraph Listing Algorithms','Norishige Chiba; Takao Nishizeki',1985,'https://www.cs.cornell.edu/courses/cs6241/2019sp/readings/Chiba-1985-arboricity.pdf','SIAM Journal on Computing 14(1), February 1985, 210–223; O(m·a(G)) triangle listing'),
 ref('cycles','Finding and Counting Given Length Cycles','Noga Alon; Raphael Yuster; Uri Zwick',1997,'https://www.math.tau.ac.il/~nogaa/PDFS/ayz4.pdf','Algorithmica 17(3), 209–223; sparse triangle bound, also restated as Theorem 3.5 in Akmal–Fischer ICALP 2026; the authors’ erratum corrects other counting formulas in equations 12 and 18'),
 ref('dynamic','Popular conjectures imply strong lower bounds for dynamic problems','Amir Abboud; Virginia Vassilevska Williams',2014,'https://arxiv.org/abs/1402.0054','1 February 2014, FOCS 2014; Conjecture 4 in this arXiv version is the no-almost-linear triangle hypothesis; inherited reference'),
 ref('current','Node-Weighted Triangles: Faster and Simpler','Shyan Akmal; Nick Fischer',2026,'https://drops.dagstuhl.de/storage/00lipics/lipics-vol374-icalp2026/html/LIPIcs.ICALP.2026.10/LIPIcs.ICALP.2026.10.html','ICALP 2026, Article 10; introduction and preliminaries recall the general unweighted bounds; Remark 3 distinguishes an infimal matrix exponent from an attained runtime'),
 ref('regex','On the Complexity of the Matching Problem of Regular Expressions with Backreferences','Soh Kumabe; Yuya Uezato',2026,'https://drops.dagstuhl.de/storage/00lipics/lipics-vol374-icalp2026/html/LIPIcs.ICALP.2026.135/LIPIcs.ICALP.2026.135.html','ICALP 2026, Article 135; Theorem 4 and Section 4’s reduction from triangle detection to matching with two backreference uses'),
 ref('withdrawn','A Strongly Subcubic Combinatorial Algorithm for Triangle Detection with Applications','Adrian Dumitrescu',2024,'https://arxiv.org/abs/2403.01085','v2, 5 March 2024, withdrawn; author identifies invalid Case 2.1 analysis; not a valid upper bound'),
 ref('oldclaim','A Linear-Time Solution to the Triangle Finding Problem: The Aegypti Algorithm','Frank Vega',2025,'https://www.preprints.org/manuscript/202506.0875/v3','Version 3, 19 August 2025; Section 3 parent-edge rule and completeness argument; counterexample checked locally in this review; later versions under this identifier change topic'),
 ref('laterclaim','Aegypti: Feasible Quadratic-Time Combinatorial Triangle Detection via Sparse Bucket Reduction','Frank Vega',2026,'https://www.preprints.org/manuscript/202511.2197/v10','Version 10, submitted 7 September and posted 8 September 2026; claims O(n²), not almost-linear time for arbitrary sparsity; proof not independently validated')],
 status='source_open',status_note='No established almost-linear algorithm or unconditional impossibility theorem found through 11 September 2026. The 2024 combinatorial proposal is withdrawn. The stated parent-edge rule in the August 2025 linear proposal has the explicit counterexample described above. The separate September 2026 O(n²) claim does not meet the all-density target and is not treated as an established bound.',formulation_reviewed_on='2026-09-11')
