import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('linear-vc-sample-compression-with-counted-side-information',
 id='TCS-6541', title='Does every VC class admit linear-size sample compression?',
 area='Learning theory', criterion='resources', question_type='yes_no',
 formal='Is there a universal constant C such that every nonempty binary concept class H⊆{0,1}^X of finite VC dimension d≥1 admits a labeled sample compression scheme with kernel bound k and side-information bound b satisfying k+b≤Cd, in the model below? The same compressor and reconstructor must work for every finite H-realizable sample, independently of its size.',
 definitions='The domain X is an arbitrary set, and a concept h∈H is a total function X→{0,1}. A finite set A⊆X is shattered if {h|_A:h∈H}={0,1}^A; d is the largest cardinality of a shattered set. A realizable sample is a finite set S⊆X×{0,1} agreeing with some h∈H. A scheme consists of deterministic maps κ and ρ, which may depend on H, and nonnegative integers k,b. For every realizable S, κ(S)=(T,z), where T⊆S is an unordered labeled subset with |T|≤k and z∈{0,1}^b. The reconstructor receives only T and z and produces a total predictor ρ(T,z):X→{0,1} agreeing with every pair in S. It does not receive S, its size, the omitted points, or their indices. The side string has fixed length b; padding shorter strings changes only constant-factor size conventions. Reconstruction need not lie in H, be stable under deleting unused examples, or have any prescribed computational complexity. No probability distribution, efficiency, or measurability condition is part of this combinatorial existence question. Dimension zero is harmless: a nonempty such class has one labeling and needs no stored examples.',
 answer_criterion='Prove a bound k+b≤Cd with C independent of H, X and the sample size, or refute the existence of every such constant by concept classes whose minimum scheme size divided by their positive VC dimension is unbounded. A bound depending on the number of examples, an exponential bound in d, or a theorem for selected classes does not settle this question. Requiring exactly d retained examples with no side information, or requiring proper reconstruction, specifies a stronger variant.',
 context=[
  paragraph('The stored object is a small selection of examples that lets a fixed decoding rule recover every training label. It need not identify the unknown target function on points never observed. For example, consider indicators of closed intervals on the real line. Retain the leftmost and rightmost positive examples, or the empty set if there are no positives. Decode to the interval between those retained points, or to the all-zero function in the empty case. Realizability ensures that no negative example lies between the extreme positives. Thus an arbitrarily large sample can be represented by at most two examples.'),
  paragraph('The distinction between examples and bits is essential. A real-valued example may itself require arbitrarily many bits to describe; sample compression charges one unit for retaining it. Conversely, permitting an arbitrary uncharged side message would trivialize the problem, because that message could encode the whole sample. The fixed reconstructor and the explicit bound b prevent this loophole. The question concerns the combinatorial information carried by selected observations, rather than ordinary lossless compression of their numerical representations.'),
  paragraph('Moran and Yehudayoff proved that every finite-VC binary class has a scheme of size 2^{O(d)}, settling the earlier existence question. Their argument combines learning with an approximate minimax principle. More precisely, their bound also involves the dual VC dimension: this reverses the roles of domain points and concepts, treating each point as its pattern of membership across the concepts. Since the dual dimension can be exponential in d, that result leaves a substantial quantitative gap. Their corrected 2015 version retains the binary theorem while withdrawing an erroneous multiclass extension.','my'),
  paragraph('An influential proposed route was to place a class inside a better-structured extremal class of comparable VC dimension and compress there. Chase and coauthors show that such embeddings can require an exponential increase in dimension. Their COLT 2024 result rules out that general route to a linear bound; it does not show that the original class itself needs exponential compression. A failed intermediate representation is different from a lower bound against every compressor.','embedding'),
  paragraph('The problem also has concrete graph instances. Fix a graph and label sampled vertices according to membership in an unknown metric ball. Bourneuf and coauthors give proper schemes of size O(t log(t+1)) when the graph has treewidth at most t, and an analogous bound for cliquewidth. Proper means that decoding produces another ball, a stronger requirement than this card imposes. Their April 2026 work supplies structured examples and explicitly leaves the general linear-VC conjecture open.','balls'),
  paragraph('Attias, Hanneke, and Ramaswami show how binary compression results transfer to multiclass, regression, and robust-learning settings, with additional factors or additional requirements on the binary scheme. Consequently, a solution could have consequences beyond binary prediction, but those transfers have hypotheses. In particular, their Open Problem 28 is about adversarially robust compression; the standard conjecture used here appears in their introduction.','reductions')],
 why='A central question connecting the combinatorial complexity of prediction with how many observations suffice to represent all training decisions. Its universality across concept classes, and its links to learning, extremal set systems and graph geometry, make the linear-versus-exponential gap fundamental.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A longstanding general conjecture asking whether VC dimension controls sample representation up to a constant factor; it reaches far beyond any one learning algorithm or geometric example.'),
 progress=[
  step('1986–2003','The framework of Littlestone and Warmuth led to the conjecture that compression size can be linear in VC dimension; the general conjecture remains explicit in the 2025 survey of reductions.','reductions'),
  step('2015–2016','Moran and Yehudayoff prove a general 2^{O(d)} bound for binary classes. The corrected arXiv v2 is the appropriate preprint; the journal version appeared in JACM in 2016.','my'),
  step('2024','Chase and coauthors prove an exponential dimension obstruction to embedding arbitrary VC classes in extremal classes, limiting a major proposed approach without refuting sample compression itself.','embedding'),
  step('2026-04-03','Bourneuf and coauthors obtain almost-linear proper compression in treewidth and cliquewidth for graph-ball classes, while retaining the general conjecture as open.','balls'),
  step('2026-08-03','The latest version of arXiv:2603.23561, which had earlier claimed a compression breakthrough and later a no-clash teaching result, is withdrawn. Its authors identify an incorrect proof of Lemma 2. This is not a resolution.','withdrawn')],
 references=[
  ref('my','Sample compression schemes for VC classes','Shay Moran; Amir Yehudayoff',2016,'https://arxiv.org/abs/1503.06960v2','Corrected preprint v2, 14 April 2015, §§1.2–1.3; Journal of the ACM 63(3), Article 21 (2016), DOI 10.1145/2890490'),
  ref('embedding','Dual VC Dimension Obstructs Sample Compression by Embeddings','Zachary Chase; Bogdan Chornomaz; Steve Hanneke; Shay Moran; Amir Yehudayoff',2024,'https://proceedings.mlr.press/v247/chase24a.html','COLT 2024, PMLR 247:923–946; exponential obstruction to low-dimensional extremal embeddings'),
  ref('reductions','Sample Compression Scheme Reductions','Idan Attias; Steve Hanneke; Arvind Ramaswami',2025,'https://proceedings.mlr.press/v272/attias25a.html','ALT 2025, PMLR 272:134–162; §1 standard linear conjecture, Definition 1 size conventions; Open Problem 28 is a separate robust-learning question'),
  ref('balls','Sample compression schemes for balls in structurally sparse graphs','Romain Bourneuf; Jędrzej Hodor; Piotr Micek; Clément Rambaud',2026,'https://arxiv.org/abs/2604.02949v1','3 April 2026; §1 unordered subsample/side-bit definitions, general conjecture and width-dependent proper compression results'),
  ref('withdrawn','The No-Clash Teaching Dimension is Bounded by VC Dimension [withdrawn]','Jiahua Liu; Benchong Li',2026,'https://arxiv.org/abs/2603.23561v4','Version 4, 3 August 2026; withdrawal notice and comment identifying the incorrect proof of Lemma 2; earlier versions used a sample-compression title')],
 status='source_open', status_note='Checked through 10 September 2026. The general linear bound remains open in the primary sources checked. The 2026 graph-ball theorems concern structured classes. The claimed breakthrough at arXiv:2603.23561 is withdrawn and is included only to document its status. This card fixes labeled, possibly improper, unordered-subset compression with all side bits counted.', formulation_reviewed_on='2026-09-10')
