import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('offline-heap-final-survivors-linear-comparisons',
 id='TCS-0477',title='Can the final survivors of an offline heap sequence be found with linear comparisons?',
 area='Data structures and compressed data',criterion='resources',question_type='yes_no',
 formal=r'''Does there exist a deterministic comparison algorithm and an absolute constant C that, for every legal sequence of N insert and delete-min operations starting from an empty priority queue, determines exactly which inserted items remain after the entire sequence using at most CN key comparisons? The complete operation sequence and all inserted keys are available before computation begins. Only the final membership vector is required; the algorithm need not output the items removed at intermediate delete-min operations or their removal order.''',
 definitions='Each insert introduces a distinct item with a key in an opaque totally ordered universe; all inserted keys are pairwise distinct. A delete-min removes the currently present item of smallest key. Legality means that in every prefix the number of delete-min operations is at most the number of inserts. If I is the total number of inserts, the output is an I-bit vector in insertion order, marking exactly the items still present after all N operations. The algorithm may examine any part of the input sequence at any time. Its only access to key values is by pairwise order comparisons; operation positions and item identities carry no information about key order. Count every key comparison, including preprocessing comparisons. Ordinary computation on indices and comparison outcomes is not the cost measure, but the algorithm must terminate and be correct on every input.',
 answer_criterion='Give a uniform deterministic algorithm meeting the CN comparison bound for every legal sequence, or prove that every such algorithm requires a superlinear number of comparisons on a family of inputs. Sorting all removed items or simulating the queue online would solve stronger tasks; a lower bound for those stronger tasks is not a negative answer here.',
 context=[
  paragraph('A usual priority queue must identify each minimum when the corresponding request arrives. The offline task can postpone every decision and return only a final set. For example, after insert(8), insert(2), delete-min, insert(1), the survivors are 8 and 1. This is not simply the set of the two largest inserted keys: 2 disappeared before 1 became available. The interleaving still matters even though the intermediate outputs are discarded.'),
  paragraph('One upper bound is to simulate a comparison heap and mark its remaining elements, using O(N log(N+2)) comparisons. At the other extreme, when all insertions precede all deletions, one linear-time selection suffices to find the surviving upper part of the key order. The question asks whether arbitrary temporal interleaving can be handled without losing that linear comparison bound.', 'seminar'),
  paragraph('The ordinary heap sorting lower bound depends on recovering the entire order of the extracted keys. Here, if I items were inserted, there are at most 2^I possible membership vectors. Counting outputs therefore does not give the usual factorial number of leaves needed for sorting. This observation only removes one lower-bound argument: a small output space by itself is not a construction of a shallow comparison decision tree.'),
  paragraph('A successful approach can exploit future deletions and later insertions, because the complete schedule is known. It need not maintain any particular heap representation. That freedom makes the problem a useful test of how much information an algorithm really needs when only a summary of a dynamic process is requested. The formulation deliberately asks about comparisons, leaving a linear total running time as a stronger goal.')],
 why='This isolates a basic gap between maintaining a dynamic process and computing its final outcome. It connects offline data structures with selection and comparison lower bounds, in a small enough model that both algorithms and adversaries can be stated precisely.',
 importance=dict(score=74,method='editorial',assessed_on='2026-09-10',reason='A clean offline-versus-online information question for the priority-queue primitive. It could reveal a general way to avoid reconstructing unneeded intermediate outputs, while remaining narrower than model-wide dynamic lower bounds.'),
 progress=[
  step('2021','Kozma explicitly asks whether final heap survivors can be computed in o(N log N), or even O(N), comparisons. The source identifies the all-insertions-first case as solvable by linear-time selection and notes that the usual sorting argument does not apply.','seminar')],
 references=[ref('seminar','Scalable Data Structures (Dagstuhl Seminar 21071)','László Kozma (problem contributor)',2021,'https://doi.org/10.4230/DagRep.11.1.1','Section 5.3, Open Problem 3: Sequences of Heap Operations')],
 status='source_open',status_note='Open in the 2021 primary source. Searches through 10 September 2026 did not locate a published resolution for this final-survivor comparison problem. Other problems called offline heaps may require every intermediate answer and should not be conflated with it.',
 formulation_reviewed_on='2026-09-10')
