import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('kolmogorov-loveland-randomness-versus-martin-lof-randomness',
 id='TCS-6648',title='Kolmogorov–Loveland randomness versus Martin-Löf randomness',area='Computability and algorithmic information',criterion='characterization',question_type='yes_no',
 formal='Is every Kolmogorov–Loveland random infinite binary sequence Martin-Löf random with respect to the fair-coin product measure?',
 definitions='Work in Cantor space 2^N, with coordinates numbered 0,1,… and fair-coin product measure μ. For a finite binary string σ, the cylinder [σ]={X:σ is a prefix of X} has measure 2^{−|σ|}. A Martin-Löf test is a sequence (U_k)_{k≥1} of open sets obtained by one algorithm enumerating pairs (k,σ), with U_k equal to the union of its enumerated cylinders for index k and μ(U_k)≤2^{−k}. A sequence X is Martin-Löf random if for every such test X∉⋂_k U_k. A Kolmogorov–Loveland betting strategy starts with capital 1. From the finite history h of bits already revealed, a partial computable procedure outputs a previously unqueried coordinate j and a rational multiplier q∈[0,2], before seeing X(j). The selected coordinates can be reconstructed from the earlier history and the same procedure; no coordinate may be selected twice along any run. After X(j) is revealed, the capital is multiplied by q if the bit is 0 and by 2−q if it is 1, and that bit is appended to h. Thus each bet preserves expected capital under a fresh unbiased bit and cannot create debt. q=1 allows reading a bit without risking capital. The next coordinate may depend on all revealed values and need not exceed previous coordinates. If the procedure fails to produce its next action, no further capital is earned. There are no oracle, running-time or space allowances beyond ordinary partial computability. A strategy succeeds on X if its capital at completed bets has unbounded supremum. X is Kolmogorov–Loveland random if every such strategy has bounded capital on X; the bound may depend on both X and the strategy. Rational multipliers suffice for the standard notion, and allowing partial rather than total computable strategies does not change the resulting class.',
 answer_criterion='Prove that every sequence outside Martin-Löf randomness admits at least one successful computable nonmonotonic betting strategy, or construct/prove the existence of one infinite sequence X that fails some Martin-Löf test but defeats every such strategy. The reverse implication, Martin-Löf randomness implies Kolmogorov–Loveland randomness, is already known. A finite exceptional prefix cannot be a separating witness. Failure of one strategy, one finite collection of strategies or one proposed uniform simulation of tests is not a negative answer to the universal statement.',
 context=[
 paragraph('These are two ways to say that an individual infinite sequence behaves randomly. Martin-Löf tests describe effectively recognizable events of arbitrarily small probability, and a sequence is nonrandom if one test catches it at every level. The betting definition instead asks whether an algorithm can turn knowledge of selected bits into unbounded profit. It measures mathematical unpredictability of a whole sequence, rather than a statistical confidence score assigned to a finite data sample.'),
 paragraph('The betting order is adaptive. A strategy may inspect a faraway coordinate before deciding which earlier, still unseen coordinate to bet on. It may also read a coordinate with a zero wager to gather information. It cannot bet on a bit already revealed, since that would permit guaranteed profit even from a fair-coin sequence. Its choice of the next position must be computed using only the information it has actually observed.'),
 paragraph('The known implication from Martin-Löf randomness follows from the fairness of the bets. For a fixed strategy starting with capital one, the set of sequences on which capital ever reaches a threshold R has measure at most 1/R. Reaching a threshold is witnessed after finitely many completed actions and can be effectively enumerated. Taking increasing thresholds produces a Martin-Löf test covering the sequences on which this strategy succeeds. The unresolved direction would convert every effective failure of randomness into success of some permitted gambler.'),
 paragraph('Choosing the query order in advance is insufficient. Kastermans and Lempp show that randomness against computable injective query orders is weaker than Martin-Löf randomness; they also establish the separation for computable permutation orders. The full Kolmogorov–Loveland definition permits choices that depend on observed bit values. Consequently their separating sequences do not establish the separation requested here.','orders'),
 paragraph('Merkle, Miller, Nies, Reimann and Stephan prove that Kolmogorov–Loveland random sequences have arbitrarily dense subsequences that are Martin-Löf random. A key splitting result says that when a computable set of coordinates and its complement are both infinite, at least one of the two resulting subsequences is Martin-Löf random. This places the notion close to Martin-Löf randomness, but the randomness of a subsequence does not by itself imply randomness of the original interleaving.','splitting'),
 paragraph('A different way to approach the question is to enlarge what a bet can ask. Generalized betting games may split a current set of possible sequences into computably described pieces, instead of querying exactly one fresh bit. Petrović’s 2021 paper gives a pair of strategies in a generalized half-betting model that together succeed on every non-Martin-Löf-random sequence. The greater freedom of the query is part of that theorem, so it does not directly give two Kolmogorov–Loveland strategies.','generalized'),
 paragraph('Petrović’s 2025 result identifies a limitation of a method used for those more flexible games. Kolmogorov–Loveland strategies do not admit the same finite-family guarantee of uniformly forcing large capital on every sequence in a sufficiently small effective open set. The paper constructs small open sets containing sequences on which the relevant capital bounds are not exceeded. This is a barrier to that style of quantitative coverage argument.','barrier'),
 paragraph('The remaining quantifier matters: finding a suitable sequence inside each of arbitrarily small open sets need not produce one sequence lying in every level of a single Martin-Löf test. Likewise, excluding one fixed finite family of gamblers does not exclude a strategy chosen separately for each nonrandom sequence. The 2025 paper explicitly keeps the equivalence question open.','barrier'),
 paragraph('A positive answer would show that the ability to choose unseen coordinates adaptively compensates for the restrictions of an ordinary computable betting procedure. A negative answer would exhibit effective statistical nonrandomness that escapes every such procedure. Either outcome would resolve a basic mismatch between two precise definitions of randomness and sharpen our understanding of what information an adaptive algorithm can extract from an infinite object.')],
 why='A central equivalence problem for algorithmic randomness: determine whether adaptive computable prediction detects every failure of effective measure-theoretic randomness.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A defining open question linking computability, adaptive information access, fair betting and effective null tests; a resolution would settle the relationship between two foundational randomness notions.'),
 progress=[
 step('2005–2006','Merkle and coauthors prove strong Martin-Löf-random subsequence and splitting properties for Kolmogorov–Loveland random sequences, without proving equivalence.','splitting'),
 step('2010-01-06','Kastermans–Lempp separate injective-order and permutation-order randomness from Martin-Löf randomness; adaptive query orders remain outside these separations.','orders'),
 step('2021-12','Petrović gives a universal pair of strategies in the more general half-betting model.','generalized'),
 step('2024-03-28','Petrović posts the open-set betting-game obstruction to a proposed form of uniform capital amplification.','barrier'),
 step('2025-03-04','The revised preprint retains the equivalence as open and proves the open-set obstruction; the journal article appears on 11 May 2025.','barrier')],
 references=[
 ref('barrier','Kolmogorov-Loveland betting strategies lose the Betting game on open sets','Tomislav Petrović',2025,'https://arxiv.org/abs/2403.19817','First posted 28 March 2024; checked v2, 4 March 2025; Theoretical Computer Science 1037, Article 115177, 11 May 2025; introduction, Definition 2.2 and Theorem 1; inherited source'),
 ref('splitting','Kolmogorov–Loveland randomness and stochasticity','Wolfgang Merkle; Joseph S. Miller; André Nies; Jan Reimann; Frank Stephan',2006,'https://people.math.wisc.edu/~jsmiller8/Papers/kl.pdf','Annals of Pure and Applied Logic 138(1–3), 183–210, March 2006; STACS 2005 precursor; Section 2 defines partial/total betting strategies; main results concern dense random subsequences and effective splits'),
 ref('orders','Comparing notions of randomness','Bart Kastermans; Steffen Lempp',2010,'https://people.math.wisc.edu/~slempp/papers/injrandom.pdf','Theoretical Computer Science 411(3), 602–616, 6 January 2010; definitions explain rational stakes; Sections 2–3 separate predetermined permutation and injective orders from Martin-Löf randomness'),
 ref('generalized','A universal pair of 1/2-betting strategies','Tomislav Petrović',2021,'https://www.sciencedirect.com/science/article/pii/S0890540121000183','Information and Computation 281, Article 104703, December 2021; universal pair uses a generalization of the nonmonotonic bit-query game')],
 status='source_open',status_note='The revised 2025 primary paper and its journal version explicitly retain KLR=MLR as a major open problem. Its finite-family/open-set obstruction is not a separating infinite sequence. No later resolution found through 11 September 2026. The formulation fixes fair-coin measure, fresh adaptive coordinates, rational fair bets, partial computability and unbounded-capital success.',formulation_reviewed_on='2026-09-11')
