import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('planted-clique-polynomial-gap-constant-success-detection',
 id='TCS-6656', title='Planted clique: can polynomial time detect a clique below the square-root scale?',
 area='Beyond worst-case and average-case analysis', criterion='decision', question_type='yes_no',
 formal='Is the following hardness statement true? For every fixed ε∈(0,1/2), there is no uniform classical randomized polynomial-time algorithm A whose success probability in the experiment below is at least 2/3 for every sufficiently large n, with k=⌊n^(1/2−ε)⌋.',
 definitions='Set [n]={1,…,n}. The null distribution N_n draws a simple undirected labeled graph by including each unordered pair independently with probability 1/2. The planted distribution P_(n,k) first chooses S uniformly among all k-element subsets of [n], includes all edges inside S, and includes every other edge independently with probability 1/2. Draw b uniformly from {0,1}; draw G from N_n if b=0 and P_(n,k) if b=1. Give A the binary integers n,k and the full adjacency matrix of G, but neither b nor S. It outputs a bit b̂. Success means Pr[b̂=b], averaged over b, the graph, S when present, and A’s independent random bits. Equivalently success is (Pr_N[A=0]+Pr_P[A=1])/2. Polynomial time means at most C(n+1)^c bit operations for every input and random tape, with fixed C,c; they and A may depend on the fixed ε. The forbidden guarantee is ∃A,C,c,N ∀n≥N, success≥2/3. This is a one-graph detection problem; A may generate its own random graphs at its own computational cost. The size of S is exactly k, not an independent per-vertex planting probability. No advice, quantum computation, oracle, side information, or algorithm-family restriction is allowed.',
 answer_criterion='Prove the stated impossibility for every fixed ε∈(0,1/2), or refute it by giving one such ε and a uniform randomized polynomial-time algorithm with a proved success probability at least 2/3 for all sufficiently large n. Lower bounds for a restricted class of algorithms, or results assuming this hardness hypothesis, do not constitute a proof. A guarantee for k=c√n with fixed c>0 does not provide the required fixed polynomial improvement in clique size.',
 context=[
  paragraph('This asks whether a planted structure can be statistically obvious yet computationally inaccessible. In the specified regime, k grows as a positive power of n, while an unplanted graph has no clique of size r=⌈3 log_2 n⌉ with probability tending to one: a union bound is at most n^r·2^(−r(r−1)/2), which tends to zero. Enumerating all r-subsets therefore distinguishes the two distributions with success tending to one in quasipolynomial time n^O(log n). The obstacle is reducing that computation to polynomial time, not a lack of information in the graph.'),
  paragraph('The classical spectral algorithm of Alon, Krivelevich, and Sudakov recovers the hidden vertex set for every fixed positive constant times √n, with a polynomial whose exponent can depend on that constant. Recovery immediately yields detection here by checking that the reported set is a sufficiently large clique. Letting the constant shrink as n^(−ε) does not keep that analysis polynomial with a fixed exponent.','spectral'),
  paragraph('Substantial evidence comes from provable failures of general algorithmic frameworks. Barak and coauthors show that low-degree sum-of-squares relaxations assign a random graph an implausibly large clique value near √n, despite its true largest clique having only logarithmic size. This is an unconditional limitation of that relaxation. It does not rule out every algorithm allowed in this card.','sos'),
  paragraph('Recent positive work also illustrates why an algorithmic barrier must state its model. Gheissari, Jagannath, and Xu permit local optimization to pass through vertex sets that are not cliques, penalizing missing edges. Starting from the whole graph, their procedure reaches the planted clique at a sufficiently large constant times √n. Restrictions to moves among actual cliques can fail even in easier regimes; those failures do not establish the unrestricted conjecture.','gradient'),
  paragraph('Nagda and Raghavendra obtain sharp bounds on efficient distinguishing advantage assuming planted-clique hardness. Their paper uses independent vertex planting, so the planted size fluctuates around its mean, and uses a different normalization of advantage. It strengthens consequences of a hypothesis in that related model. It is not an unconditional lower bound for the fixed-size experiment here.','optimal'),
  paragraph('The question isolates detection from stronger output requirements such as recovering every planted vertex. It also fixes the random background: arbitrary base graphs, geometric random graphs, and adversarially modified edges describe different experiments. Work on robust recovery of overlapping planted cliques in random intersection graphs continued in COLT 2026, but its distribution and signal regime do not settle this question.','intersection')],
 why='A foundational average-case hardness hypothesis and a central test case for statistical–computational gaps. It asks for a clean separation between the presence of information and efficient extraction of that information; reductions transfer related assumptions to sparse estimation and latent-structure learning. Proving this formulation would in particular imply P≠NP, since a polynomial algorithm for maximum clique would distinguish the distributions.',
 importance=dict(score=98, method='editorial', assessed_on='2026-09-10', reason='A canonical computational threshold with broad consequences in average-case complexity, statistical inference, and the study of algorithmic lower-bound frameworks.'),
 progress=[
  step('1998','Alon, Krivelevich, and Sudakov give polynomial-time recovery for k≥c√n for any fixed c>0, using spectral methods and boosting.','spectral'),
  step('2016–2019','Barak, Hopkins, Kelner, Kothari, Moitra, and Potechin prove a nearly tight sum-of-squares integrality gap: degree d=o(log n) assigns random graphs clique value n^(1/2−o(1)). This is a restricted-model lower bound.','sos'),
  step('2023–2025','Gheissari, Jagannath, and Xu show that an appropriate discrete gradient descent and low-temperature local chain recover at the √n scale from the full-graph initialization; the final preprint version is dated 15 May 2025.','gradient'),
  step('2025-07-19','Nagda and Raghavendra derive optimal efficient distinguishing advantages conditional on a planted-clique hypothesis, in the independent-vertex planting model.','optimal'),
  step('2026','Göbel, Ruff, and Schiller give robust sum-of-squares algorithms for multiple overlapping cliques in random intersection graphs when clique size is much larger than √(n log n). This is progress in a related model, not below the threshold fixed here.','intersection')],
 references=[
  ref('spectral','Finding a Large Hidden Clique in a Random Graph','Noga Alon; Michael Krivelevich; Benny Sudakov',1998,'https://people.math.ethz.ch/~sudakovb/hidden-clique.pdf','Random Structures & Algorithms 13(3–4), 457–466; fixed-size model, spectral algorithm and extension to every fixed c>0'),
  ref('sos','A Nearly Tight Sum-of-Squares Lower Bound for the Planted Clique Problem','Boaz Barak; Samuel B. Hopkins; Jonathan Kelner; Pravesh K. Kothari; Ankur Moitra; Aaron Potechin',2019,'https://doi.org/10.1137/17M1138236','SIAM Journal on Computing 48(2), 687–735; FOCS 2016 version and arXiv:1604.03084; lower bound on the relaxation value in G(n,1/2)'),
  ref('gradient','Finding planted cliques using gradient descent','Reza Gheissari; Aukosh Jagannath; Yiming Xu',2025,'https://arxiv.org/abs/2311.07540v2','15 May 2025 final version; §1.1 fixed-size distribution, Theorem 1.1 and Remark 1.2; earlier title used Markov chain Monte Carlo'),
  ref('optimal','On optimal distinguishers for Planted Clique','Ansh Nagda; Prasad Raghavendra',2025,'https://arxiv.org/abs/2505.01990v2','19 July 2025 version; Conjecture 1.1 and Theorem 1.4; §1 footnotes specify independent-vertex planting and advantage normalization'),
  ref('intersection','Robust Algorithms for Finding Cliques in Random Intersection Graphs via Sum-of-Squares','Andreas Göbel; Janosch Ruff; Leon Schiller',2026,'https://proceedings.mlr.press/v336/gobel26a.html','COLT 2026, PMLR 336:2720–2802; overlapping planted cliques in a different random graph model')],
 status='source_open', status_note='Checked through 10 September 2026; no unrestricted polynomial-time solution below n^(1/2−ε) or unconditional hardness proof was identified. The exact formulation fixes constant-success detection and exactly k planted vertices. Low-degree and sum-of-squares bounds remain scoped to their models; the optimal-advantage result is conditional.', formulation_reviewed_on='2026-09-10')
