import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('unbounded-continuous-skolem-rational-linear-system',
 id='TCS-6566',title='Decidability of unbounded Continuous Skolem',area='Semantics, logic and verification',criterion='decision',question_type='yes_no',
 formal='Is there a Turing algorithm that, given any dimension d≥1, rational matrix A∈Q^{d×d}, and rational column vectors b,c∈Q^d, always halts and correctly decides whether cᵀexp(tA)b=0 for some real t≥0?',
 definitions='Every input rational is represented exactly by a signed binary integer numerator and a positive binary integer denominator. The dimension is part of the input and has no fixed upper bound. The matrix exponential is exp(tA)=Σ_{j=0}^∞ t^j A^j/j!, and x(t)=exp(tA)b is the unique real solution of x′(t)=Ax(t), x(0)=b. The target is the hyperplane {x:cᵀx=0}; c=0 is allowed and gives an immediate yes instance. Time ranges over all finite nonnegative real numbers, not just rational or integer times. Equality is exact. A zero at t=0 counts, as does a trajectory that is identically in the hyperplane. If the scalar function approaches zero only in the limit t→∞, the answer is no unless it also has a finite zero. No promise of diagonalizability, simple eigenvalues, bounded dimension, stability, spectral separation, transverse intersection, or robust distance from the hyperplane is supplied. The requested algorithm is an ordinary finite-input decision procedure without real-number or number-theoretic oracles; no complexity upper bound is prescribed. This card retains the rational-data version; some cited work treats the more general real-algebraic-data version.',
 answer_criterion='Give an unconditional always-halting decision algorithm for every rational input, or prove that no such Turing algorithm exists. A conditional procedure assuming Schanuel’s conjecture, a solver for a fixed low dimension, a procedure that may run forever on some inputs, or a certified answer only under a nonzero distance promise is partial progress. An undecidability theorem allowing more general coefficients or nonlinear differential equations must be reduced to this rational linear model to refute the proposition.',
 context=[
 paragraph('Linear differential equations have explicit matrix-exponential solutions, yet an explicit formula does not automatically decide whether a trajectory hits an exact target. The scalar output cᵀx(t) may combine growth, decay, polynomial factors and oscillations. The matrix and vectors are finite rational data, while the possible hitting time is an unrestricted real number. This makes the question a basic test of what exact verification can decide even for linear continuous dynamics.','bell'),
 paragraph('Numerical proximity is insufficient. The one-dimensional system x′=−x, x(0)=1 has output e^{−t}, which becomes arbitrarily small but never reaches zero. Conversely, a zero need not be accompanied by a sign change: the polynomial (t−1)² touches zero and returns to positive values. Such a polynomial is itself an output of a rational nilpotent linear system. A grid search or a sign-change detector can therefore miss the distinction required by the card.'),
 paragraph('Simple degenerate cases can be removed exactly. The initial-time condition is cᵀb=0. By the Cayley–Hamilton theorem, the scalar function is identically zero precisely when cᵀA^j b=0 for j=0,…,d−1. These are finite rational calculations. Outside that case, analyticity ensures only finitely many zeros in each bounded interval, but neither a uniform numerical precision nor a final time beyond all zeros follows from that finiteness statement.'),
 paragraph('Spectral decomposition writes the output as a sum of polynomial multiples of exponentials, with conjugate terms combining into real sine and cosine expressions. The imaginary parts of eigenvalues give oscillation frequencies. Repeated eigenvalues can introduce polynomial factors. Competing terms can nearly cancel at very large times, so a proof that the long-term behaviour is simple enough to inspect is a substantive part of an unbounded decision procedure.','bounded'),
 paragraph('Chonev, Ouaknine and Worrell prove decidability of the bounded Continuous Skolem problem assuming Schanuel’s conjecture. That conjecture gives a transcendence-degree lower bound for complex numbers linearly independent over the rationals together with their exponentials. Their algorithm uses it to handle possible tangential zeros. The result does not supply an unconditional bounded-time procedure, and a bounded-time procedure alone does not supply a stopping criterion for checking all t≥0.','bounded'),
 paragraph('The same paper reduces certain unbounded spectral cases to the bounded problem, including the case with at most one rationally independent frequency. A separate recurrent-reachability result decides whether a solution of differential order at most seven has infinitely many zeros and gives an effective last-zero bound when it has only finitely many. Combined with the conditional bounded solver, this yields conditional decisions in that low-order regime. Infinite recurrence and existence of even one zero are nevertheless different questions.','recurrent'),
 paragraph('The broader algebraic-coefficient formulations reveal a connection with effective Diophantine approximation: handling multiple independent oscillations can entail computing quantities measuring unusually good rational approximations to algebraic numbers. Those implications are evidence of the mathematical obstacles, not undecidability proofs. Their precise dimension thresholds belong to the coefficient model of the cited theorem; this card does not automatically transfer them to the rational-matrix representation fixed above.','bounded'),
 paragraph('Platzer and Qian’s 2025 completeness theorem for compact initial-value problems concerns specified open safety and liveness properties. Its discussion explicitly identifies exact hyperplane reachability as an obstacle to replacing those topological conditions by arbitrary closed targets. A proof system that certifies entry into an open neighbourhood need not decide whether the trajectory touches its central hyperplane. This distinction matters when interpreting advances in numerical verification as progress on exact decision questions.','open-properties'),
 paragraph('The July 2026 survey by Bacik and coauthors places the continuous problem alongside discrete recurrence questions, while emphasizing differences in technique. Sampling only integer times gives a sequence but changes the question: for example, a rational rotation system can have output cos t and reach zero at π/2. The card asks whether any real hitting time exists, so discrete-time zero testing cannot simply replace the continuous analysis.','survey')],
 why='A minimal exact reachability question for continuous linear systems whose decidability remains unresolved, linking algorithmic verification to real analysis, transcendence and effective number theory.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A fundamental boundary for verification of linear differential systems, with a precisely finite rational input and an unrestricted exact reachability target.'),
 progress=[
 step('2010','Bell and coauthors establish the continuous Skolem framework, equivalent formulations and decidable special cases.','bell'),
 step('2016','Chonev–Ouaknine–Worrell obtain conditional bounded decidability and reductions for restricted frequency patterns.','bounded'),
 step('2016','Their recurrent-reachability work decides infinitely many zeros at differential order at most seven and supplies effective last-zero bounds in that regime.','recurrent'),
 step('2025-11','Platzer–Qian explain why exact closed-target reachability is not covered by their completeness results for open properties.','open-properties'),
 step('2026-07-26','The Skolem/Positivity survey records continuous analogues and their distinct analytic obstacles.','survey')],
 references=[
 ref('bell','The continuous Skolem-Pisot problem','Paul C. Bell; Jean-Charles Delvenne; Raphaël M. Jungers; Vincent D. Blondel',2010,'https://perso.uclouvain.be/vincent.blondel/publications/10BDJ.pdf','Theoretical Computer Science 411, 3625–3634; matrix-exponential, differential-equation and zero-testing formulations'),
 ref('bounded','On the Skolem Problem for Continuous Linear Dynamical Systems','Ventsislav Chonev; Joël Ouaknine; James Worrell',2016,'https://arxiv.org/abs/1506.00695','v3, 10 May; ICALP 2016, article 100; bounded decidability assumes Schanuel, and the input definition permits real algebraic coefficients'),
 ref('recurrent','On Recurrent Reachability for Continuous Linear Dynamical Systems','Ventsislav Chonev; Joël Ouaknine; James Worrell',2016,'https://arxiv.org/abs/1507.03632','LICS 2016, pp. 515–524; infinite-zeros and effective cutoff results are distinct from unconditional existence-of-a-zero decisions'),
 ref('open-properties','Axiomatization of Compact Initial Value Problems: Open Properties','André Platzer; Long Qian',2025,'https://publikationen.bibliothek.kit.edu/1000188295/170660770','Journal of the ACM 72(6), article 41, November; p. 41:7, Continuous Skolem limitations; DOI 10.1145/3763228'),
 ref('survey','A Survey of the Skolem and Positivity Problems for Linear Recurrence Sequences','Piotr Bacik; Toghrul Karimov; Florian Luca; Joris Nieuwveld; Joël Ouaknine; David Purser; James Worrell',2026,'https://people.mpi-sws.org/~joel/publications/skolem_and_positivity_survey26.pdf','Manuscript 26 July; closing discussion, Continuous-time analogues; its main results concern discrete sequences')],
 status='source_open',status_note='No unconditional decision procedure or undecidability proof for this rational linear model was found through 11 September 2026. Bounded conditional results, low-order recurrence algorithms, approximate/robust verification and nonlinear-system hardness do not settle the unbounded exact question.',formulation_reviewed_on='2026-09-11')
