import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('deterministic-finite-field-polynomial-factorization',
 id='TCS-6614',title='Deterministic polynomial-time factorization over finite fields',area='Algebraic computation',criterion='construction',question_type='yes_no',
 formal='Does there exist a deterministic Turing algorithm that, for every explicitly represented finite field F_q and every nonzero dense univariate f∈F_q[x] of degree n≥1, outputs its complete irreducible factorization using (n+log₂q)^{O(1)} bit operations, with one absolute polynomial bound?',
 definitions=r'The field is supplied as F_q=F_p[t]/(h(t)), where p is a binary-encoded prime, h∈F_p[t] is a supplied monic irreducible polynomial of degree e≥1, and q=p^e. These field promises are part of the input specification; no algorithm for constructing h is required. An element is represented by its e coefficients of degree below e, each in {0,…,p−1}. The polynomial f is given by all n+1 coefficients in this representation. Output a unit u∈F_q\{0}, pairwise distinct monic irreducible polynomials g₁,…,g_r∈F_q[x], and positive integer multiplicities m₁,…,m_r with f=u∏_i g_i^{m_i}. Output order is irrelevant. Arithmetic, conversions, preprocessing and writing the factors all count in bit time. Repeated factors and characteristic-p inseparability are allowed. The running-time exponent must be independent of n,p,e and f. No randomness, number-theoretic hypothesis, factorization oracle or precomputed field-specific advice is allowed.',
 answer_criterion='An affirmative answer gives a correct complete-factorization algorithm with the stated uniform worst-case polynomial bit bound for every valid input. A negative answer proves no such algorithm exists in this model; failure of a particular deterministic strategy is insufficient. Polynomial dependence on q or p instead of log q, average-case bounds, fixed-degree results, or conditional algorithms do not resolve the claim.',
 context=[
 paragraph('Finite-field polynomial factorization is a setting where randomization already gives efficient exact algorithms. The desired output has a short representation and is unique up to ordering after normalizing the factors. The open issue is therefore whether random choices are essential for guaranteed efficiency, rather than whether factorization is possible or whether its answer is too large to write down.'),
 paragraph('The logarithm of the field size is the relevant parameter because one coefficient occupies about log₂q bits. Enumerating all q field elements may be reasonable for a tiny field, but is exponential in the coefficient length when q grows. This distinction is already visible for quadratics over a prime field: the general problem includes finding roots of x²−a modulo an arbitrary large odd prime when a is a quadratic residue.'),
 paragraph('The field presentation makes a potentially hidden prerequisite explicit. Supplying an irreducible h gives a concrete way to add, multiply and invert extension-field elements using polynomial arithmetic modulo h. The algorithm is not being asked to discover a field representation. At the same time, arithmetic operations are not free: the requested complexity includes their bit cost and must remain polynomial as the extension degree and characteristic vary.'),
 paragraph('Classical algorithms organize the work into squarefree factorization, separation by irreducible-factor degree, and splitting products whose factors have equal degree. The first two stages have deterministic polynomial-time methods. Randomized equal-degree splitting then completes the factorization efficiently. This organization, surveyed by von zur Gathen–Panario, isolates a concrete source of the derandomization difficulty.','survey'),
 paragraph('A proposed answer can be checked efficiently without solving the search problem from scratch. Multiplying the claimed factors verifies their product, and finite-field irreducibility tests use modular powering and gcd computations. For a monic polynomial g of degree d, one checks divisibility by x^{q^d}−x and excludes common factors with x^{q^{d/ℓ}}−x for prime divisors ℓ of d. The huge exponents are handled by repeated powering modulo g, not by writing enormous polynomials.','survey'),
 paragraph('Unconditional deterministic methods do work in time polynomial in n, log q and the characteristic p. Consequently fixed characteristic is already a tractable regime even when the extension field is large. The general obstacle is a large characteristic encoded in only log p bits. Guo’s account records a p^{1/2} dependence up to factors polynomial in n and log q for the best general deterministic methods discussed there.','guo'),
 paragraph('GRH does not currently remove every obstacle. Evdokimov’s algorithm gives quasipolynomial degree dependence under GRH, and Galois-theoretic methods obtain polynomial time for certain supplied lifts with controlled groups. Guo’s P-scheme framework extends those special cases and unifies earlier methods. Neither its polynomial-time subclass theorem nor the general quasipolynomial bound is a general deterministic polynomial-time factorization theorem.','guo'),
 paragraph('The inherited September 2025 paper by Altman changes the averaging question. Starting from one integer polynomial f, it factors its reductions for every prime below a bound N. The average cost per prime is polynomial in the input parameters and the degree m of the splitting field over Q. This gives a strong amortized result when m is polynomially bounded, but m can be as large as n!, and processing all primes below N does not give a polynomial-time algorithm for one arbitrary prime supplied in binary.','primary'),
 paragraph('Altman also distinguishes averaging over primes from older averaging over input polynomials. A deterministic procedure can run quickly on most randomly selected polynomials and still have hard individual inputs. The present question requires a worst-case bound for every f over every supplied field. Neither kind of averaging can silently replace that quantifier.','primary'),
 paragraph('Recent multivariate factorization results sometimes suppress the underlying univariate cost in their headline bounds. Chuyoon–Shpilka’s March 2026 paper explicitly restores this dependence in Remark 1.7 and §2.2. Its finite-field subroutine runs in time polynomial in p, log q and the degree; its multivariate theorem includes a factor T for univariate factorization. Specializing the number of variables does not erase that cost.','sparse'),
 paragraph('Umans–Wang’s November 2025 work pursues a different improvement: a number-theoretic conjecture could reduce the degree exponent in fast polynomial-factorization algorithms below the familiar three-halves bound. It also has a separate consequence for deterministic integer factoring. Those are valuable quantitative directions, but the abstract’s deterministic integer result must not be misread as a general derandomization theorem for finite-field polynomials.','faster'),
 paragraph('The problem is fundamental because polynomial factorization is repeatedly used as a subroutine in symbolic computation and computational number theory. A deterministic solution would make many algorithms independent of randomized splitting choices. A proof that no such solution exists would instead establish a striking separation for an exact algebraic search problem whose answers are efficiently verifiable.')],
 why='A canonical exact derandomization problem in computer algebra, with broad consequences wherever finite-field factorization is used as a subroutine.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A defining open problem in algebraic computation: randomized polynomial-time search is known, while uniform deterministic polynomial bit complexity remains unresolved even for basic root-finding cases.'),
 progress=[step('1967–1981','Berlekamp and subsequent randomized splitting algorithms establish the classical framework for finite-field factorization.','survey'),step('1990','Shoup reduces the characteristic dependence of general deterministic methods to roughly a square root, as reviewed in the later sources.','guo'),step('1994','Evdokimov obtains deterministic quasipolynomial degree dependence under GRH, not a general polynomial bound.','guo'),step('2019–2020','Guo’s P-scheme framework supplies GRH-based polynomial algorithms for additional Galois-group classes and a common treatment of earlier results.','guo'),step('2025-09-16','Altman gives unconditional amortized factorization over many primes, with dependence on splitting-field degree.','primary'),step('2025-11-13','Umans–Wang propose a number-theoretic route to better degree exponents in fast factorization; general deterministic finite-field factoring is not resolved.','faster'),step('2026-03-08','Chuyoon–Shpilka’s sparse multivariate results explicitly retain the univariate-factorization cost and a polynomial dependence on p for the finite-field subroutine.','sparse')],
 references=[ref('primary','Deterministic polynomial factorisation modulo many primes','Daniel Altman',2025,'https://arxiv.org/abs/2509.12705','Inherited reference; 16 September 2025; Theorem 1.1, comparison with earlier methods, and explicit statement that general deterministic polynomial time remains open even under GRH'),ref('survey','Factoring Polynomials Over Finite Fields: A Survey','Joachim von zur Gathen; Daniel Panario',2001,'https://people.csail.mit.edu/dmoshkov/courses/codes/poly-factorization.pdf','Journal of Symbolic Computation 31, 3–17; §§2–4 describe complete factorization, deterministic preliminary stages, randomized splitting and irreducibility tests'),ref('guo','Deterministic polynomial factoring over finite fields: a uniform approach via P-schemes','Zeyu Guo',2020,'https://zeyuguo.bitbucket.io/papers/pscheme.pdf','Journal of Symbolic Computation, DOI 10.1016/j.jsc.2019.02.011; inspected author manuscript dated 16 November 2019; §1.1 distinguishes unconditional, GRH quasipolynomial, and Galois-restricted bounds'),ref('faster','A number-theoretic conjecture implying faster algorithms for polynomial factorization and integer factorization','Chris Umans; Siki Wang',2025,'https://arxiv.org/abs/2511.10851','Posted 13 November 2025; conditional route below degree exponent 3/2 and a separate deterministic integer-factorization consequence'),ref('sparse','On Factorization of Sparse Polynomials of Bounded Individual Degree','Aminadav Chuyoon; Amir Shpilka',2026,'https://eccc.weizmann.ac.il/report/2026/036/','ECCC TR26-036, 8 March 2026; Remark 1.7 and §2.2, Theorems 2.7–2.8 explicitly charge for univariate factorization and polynomial dependence on the characteristic')],
 status='source_open',status_note='Open unconditionally for all explicitly represented finite fields and dense univariate inputs, based on sources checked through 11 September 2026. GRH alone is not known to give the requested general polynomial bound. Amortization over primes, fixed characteristic, special Galois groups and multivariate bounds retaining a univariate oracle do not resolve this exact question.',formulation_reviewed_on='2026-09-11')
