import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('constant-non-signaling-beyond-log-star-local',
 id='TCS-0518',title='Constant non-signaling locality beyond deterministic log-star LOCAL',
 area='Distributed and local algorithms',criterion='models',question_type='yes_no',
 formal=r'''Does there exist a fixed locally checkable labeling problem Π on all finite graphs of some fixed maximum degree Δ, with finite input and output alphabets, that admits a zero-error non-signaling outcome of constant locality, but has no deterministic LOCAL algorithm using $O(1+\log^* n)$ rounds? The degree bound, checking radius, alphabets, and non-signaling locality must all be independent of n.''',
 definitions=r'''An LCL is specified by an integer Δ≥2, a fixed radius r≥1, finite input/output alphabets, and a finite list of permitted rooted radius-r neighborhoods with input/output labels, degrees, and ports. A labeling is valid when every vertex sees a permitted pattern. Legality does not depend on identifiers or n. Inputs range over all simple undirected n-vertex graphs of maximum degree at most Δ, all finite-alphabet input assignments, all port numberings, and all injective identifiers from [n²]; disconnected graphs are included. For one constant integer R, a non-signaling outcome assigns each input a joint probability distribution on all vertex outputs, supported entirely on valid labelings. For every vertex subset S and any two inputs of the same size, an identifier-, input-, and port-preserving isomorphism of their radius-R neighborhoods of S must carry one marginal output distribution on S to the other. This condition applies to every subset, not only to individual vertices. Arbitrary real probabilities and correlations are allowed; there is no requirement that the outcome be sampled by a classical or quantum protocol. Exact n may be used. In deterministic LOCAL every node initially knows n, its identifier, its input, degree, and ports, follows one finite computable program, and exchanges arbitrarily long messages with neighbors in synchronous rounds. Local computation is unrestricted but must terminate. The negative classical condition is: for every correct algorithm A and constant C, arbitrarily large inputs require more than C(1+log* n) rounds. Here log* counts base-2 logarithms needed to reduce n to at most 1.''',
 answer_criterion='Exhibit one finite LCL specification and a constant-locality family of non-signaling distributions, and prove that no deterministic O(log* n)-round solver exists; or prove that every LCL with such a distribution has a deterministic O(log* n)-round solver. This card fixes the all-bounded-degree-graphs, zero-error formulation of the saved question. A family whose degree grows with n, or an outcome of logarithmic locality, does not establish the required separation.',
 context=[
  paragraph('A distributed algorithm can only react to information that has reached it. Non-signaling keeps this causality requirement but removes the demand for a physically implementable algorithm. It asks whether the joint output probabilities could exist without letting a distant input change the observations of any group of nearby or far-apart observers. This makes it a useful setting for proving strong communication lower bounds.'),
  paragraph('Requiring consistency only for one vertex would be much too weak. For example, choosing the two colors of a connected bipartite graph with a random global flip makes each vertex individually uniform. The correlation between two vertices can nevertheless reveal whether their distance has even or odd parity. The marginal condition for every subset is what detects such hidden signaling.'),
  paragraph('The iterated logarithm marks an established symmetry-breaking regime. Every LCL solvable there by a deterministic LOCAL algorithm has a constant-locality, finitely dependent solution distribution, and therefore a constant-locality non-signaling distribution. The question asks whether constant non-signaling locality reaches further than this classical regime.', 'bridge'),
  paragraph('The rooted-tree case is constrained by a simulation theorem: sufficiently small non-signaling locality leads back to a deterministic O(log* n)-round algorithm there. That theorem cannot simply be extended to unrooted trees or arbitrary graphs. The corrected February 2026 manuscript explicitly withdraws an earlier claim about unrooted trees.', 'bridge'),
  paragraph('Recent quantum separations show that the models can differ for a fixed LCL, but at a larger time scale. The August 2026 revision gives a quantum O(log n) upper bound and a classical randomized lower bound of Ω(log n·(log log n)^0.99). These rates leave the constant-locality threshold on this card unresolved.', 'quantum')],
 why='A resolution would locate the boundary of what causality alone permits for locally verifiable tasks. It would either extend a fundamental symmetry-breaking classification to arbitrary non-signaling correlations, or provide a concrete obstruction to such a classification and a benchmark for quantum lower bounds.',
 importance=dict(score=87,method='editorial',assessed_on='2026-09-10',reason='A foundational boundary question between local computation and causal output distributions. The fixed degree and constant locality requirements isolate an unresolved structural issue beyond the already known logarithmic quantum separations.'),
 progress=[
  step('2024–2026','Akbari and coauthors prove that deterministic O(log* n) LCLs admit constant-locality finitely dependent distributions. They also show that o(log log log n) randomized online locality in rooted trees implies deterministic O(log* n), which covers non-signaling outcomes through their simulation.','bridge'),
  step('2026-02','Suomela’s updated problem list still asks for an LCL with constant non-signaling locality and classical deterministic complexity beyond the log-star regime. This card fixes zero error and a finite specification on all bounded-degree graphs.','problem'),
  step('2026-08','Balliu and coauthors strengthen the established quantum separation to O(log n) versus Ω(log n·(log log n)^0.99). Their general simulation also bounds the power of finitely dependent distributions; finite dependence imposes an extra independence condition absent from general non-signaling outcomes.','quantum')],
 references=[
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#non-signaling','Updated 23 February 2026; Non-signaling advantage for LCLs, second concrete question'),
  ref('bridge','Online Locality Meets Distributed Quantum Computing','Amirreza Akbari; Xavier Coiteux-Roy; Francesco d’Amore; François Le Gall; Henrik Lievonen; Darya Melnyk; Augusto Modanese; Shreyas Pai; Marc-Olivier Renou; Václav Rozhoň; Jukka Suomela',2026,'https://arxiv.org/abs/2403.01903v4','Corrected version, 13 February 2026; Theorems 1.2 and 1.5, Definitions 5.1–5.2, Theorem 5.3, and Errata. Original conference publication: STOC 2025.'),
  ref('quantum','Distributed Quantum Advantage in Locally Checkable Labeling Problems','Alkida Balliu; Filippo Casagrande; Francesco d’Amore; Massimo Equi; Barbara Keller; Henrik Lievonen; Dennis Olivetti; Gustav Schmid; Jukka Suomela',2026,'https://arxiv.org/abs/2504.05191v2','17 August 2026 revision of SODA 2026 work; Theorems 1.1–1.2 and Section 1.6')],
 status='source_open',status_note='The February 2026 author-maintained list explicitly poses the constant non-signaling versus deterministic log-star question. The checked August 2026 quantum separation does not supply the constant-locality witness required here. No resolution of this fixed zero-error formulation was located through 10 September 2026.',formulation_reviewed_on='2026-09-10')
