import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('superlogarithmic-static-cell-probe-lower-bound',
 id='TCS-6540',title='An explicit static problem requiring superlogarithmically many cell probes',area='Algorithms & data structures',criterion='resources',question_type='yes_no',
 formal='Does there exist a fixed integer k≥2 and a uniformly polynomial-time computable family of Boolean functions F_n on an n-word database and a k⌈log₂ n⌉-bit query such that its optimal deterministic static cell-probe query complexity t*F(n), with word size ⌈4log₂ n⌉ bits and n⌈log₂ n⌉² memory cells, satisfies t*F(n)/log₂ n→∞ as n→∞?',
 definitions='For each integer n≥2 put w=⌈4log₂ n⌉ and s=n⌈log₂ n⌉². A database is D∈({0,1}^w)^n, a query is q∈{0,1}^{k⌈log₂ n⌉}, and F_n(D,q)∈{0,1}. Explicit means that a single deterministic Turing machine computes F_n(D,q), given (1^n,D,q), in time polynomial in n; no advice is allowed in this definition. A data structure may preprocess D by any map E_n into s cells of w bits each. Preprocessing time is unrestricted, and this encoding may be nonlinear and nonuniform. For each query, a deterministic adaptive decision tree reads cells, choosing the next address from the query and previously read contents, and must output F_n(D,q) exactly for every database. Computation between probes is free. The trees may depend on n, F and the query, but their only access to D is through E_n(D). Each query starts without free database-dependent private information; memory is static and read-only. Define t*F(n) as the minimum, over all such encodings and trees, of the maximum number of probes over all D and q. All memory cells count toward s. This card fixes a near-linear-space, short-query, one-bit-answer specialization of the broader static lower-bound challenge; it does not assert equivalence to every space or word-size variant.',
 answer_criterion='Exhibit one k and one explicit family F and prove the stated ω(log n) lower bound for all sufficiently large n, or refute the existential claim. Its exact negation is: for every such k and F there is a constant C and infinitely many n for which t*F(n)≤C log₂ n. An upper bound O(log n) at every sufficiently large n for every explicit F would be a stronger refutation. A bound restricted to nonadaptive queries, linear encodings, one-bit cells, larger queries, or dynamically updated memory does not settle this fixed model.',
 context=[
 paragraph('A static data structure pays an initial cost to organize a database and then answers queries against that fixed information. In the cell-probe model, only the number of memory cells read during a query matters. The query algorithm has unlimited computational power between reads. Consequently, a lower bound must identify information that cannot be made locally accessible even by an ingenious encoding; showing that a particular search procedure or arithmetic computation is slow is insufficient.'),
 paragraph('The space allowance is central. With enough space, preprocessing could store every answer in a table, giving constant-probe queries. Here there are at least n² possible queries, while the stored representation has only O(n log³ n) bits. Conversely, the database itself fits in n cells, so reading all n cells always suffices. The target therefore lies strictly between two elementary strategies: exhaustive answer storage is unavailable, but the problem is always solvable without a computational-time obstruction.'),
 paragraph('The one-bit answer avoids obtaining a large probe bound merely because the output contains many independent bits. The query length is O(log n), with a fixed constant k. Increasing the query length to n bits can create communication lower bounds of an entirely different magnitude. Likewise, allowing only linear combinations in preprocessing or forbidding adaptive reads changes the collection of encodings and algorithms that a lower bound must defeat.'),
 paragraph('Koucký, Loff, Molli and Saks formulate the broad static challenge explicitly as Open Problem 1.1. Away from storage that is extremely close to the information-theoretic minimum, familiar general lower-bound approaches have not exceeded the logarithm of the number of queries. The present card turns this challenge into one yes/no proposition by fixing the word size, storage overhead, output alphabet and uniform meaning of an explicit problem. Its stricter conventions should be kept in mind when transferring results from a survey.','natural'),
 paragraph('Korten, Pitassi and Impagliazzo obtain stronger tradeoffs through local pseudorandom generators. Their improvements are especially informative when the number of probes is small and the cells contain few bits. Their general bound includes an explicit dependence on word size. A gain proved for one-bit cells therefore cannot simply be carried over unchanged to Θ(log n)-bit words. These results advance the tradeoff frontier without proving the superlogarithmic lower bound at the parameters fixed here.','local'),
 paragraph('Ko’s 2025 result illustrates another important parameter distinction. For random linear operators with m possible row queries, the lower bound is Ω(min{log(m/s), n/log s}) in a bit-cell formulation. It can exceed log n when the number m of queries grows sufficiently rapidly. With only polynomially many queries, the first term is at most O(log n). The random choice of an operator also does not by itself supply the uniformly polynomial-time explicit family required in this card.','operator'),
 paragraph('The STOC 2026 natural-proofs paper supplies conditional obstacles to a broad class of proof methods. Such a proof recognizes a sufficiently large, efficiently testable property of function tables that implies data-structure hardness; conjectured local pseudorandom functions would obstruct that recognition. This is not an unconditional impossibility theorem for stronger lower bounds. The authors’ errata also flag a new sampling method whose coverage had not been checked and explain why a previously cited rigidity consequence no longer constitutes an unachieved barrier.','natural'),
 paragraph('Static and dynamic memory have different sources of hardness. Larsen, Weinstein and Yu crossed the logarithmic barrier for dynamic Boolean problems, where updates limit how information can be reorganized. Ko’s March 2026 preprint claims a further Ω((log n/log log n)²) bound for a dynamic multiphase problem. Those update constraints are absent here: the whole database may be preprocessed without a time bound before any query arrives. Neither dynamic result automatically gives the requested static lower bound.','dynamic'),
 paragraph('A positive solution would show that limited storage and short answers can force a substantial number of reads even when computation is free. It would therefore separate a real memory-access bottleneck from the running time of currently known implementations. The deterministic formulation is already a landmark target; a lower bound that additionally survives randomized encodings and bounded-error queries would be stronger.')],
 why='A central unconditional lower-bound bottleneck for data structures: establish that a short, explicitly defined static query fundamentally needs more than logarithmically many memory accesses despite unrestricted preprocessing.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A model-wide challenge connecting algorithms, communication complexity, pseudorandomness and circuit lower bounds, with implications beyond any single geometric or graph problem.'),
 progress=[
 step('2018','Larsen–Weinstein–Yu cross the logarithmic barrier for dynamic Boolean data structures; the journal version appeared in 2020. This does not settle the static question.','dynamic-classic'),
 step('2025-05-28','Revision 1 of Korten–Pitassi–Impagliazzo improves cell-probe space/time tradeoffs using local PRGs and studies conditional barriers.','local'),
 step('2025-10-22','Ko proves stronger bit-cell bounds for random linear operators, including regimes with superpolynomially many queries.','operator'),
 step('2026-03-26','Ko’s preprint claims a nearly log-squared lower bound for dynamic Boolean multiphase problems. No independent proof audit of that claim is supplied here.','dynamic'),
 step('2026-06','Koucký–Loff–Molli–Saks appears at STOC 2026, with conditional natural-proofs barriers and an explicit statement of the static challenge.','natural')],
 references=[
 ref('natural','The Natural Proofs Barrier against Data-Structure Lower-Bounds','Michal Koucký; Bruno Loff; Tulasimohan Molli; Michael E. Saks',2026,'https://doi.org/10.1145/3798129.3800843','STOC 2026, pp. 1338–1343; full author manuscript dated 27 December 2025, Open Problem 1.1, §§1.2–1.3 and 2.3; front-matter errata qualify coverage and the older rigidity discussion'),
 ref('local','Stronger Cell Probe Lower Bounds via Local PRGs','Oliver Korten; Toniann Pitassi; Russell Impagliazzo',2025,'https://eccc.weizmann.ac.il/report/2025/030/','Revision 1, 28 May; even-probe tradeoff retains the 2^{-O(w)} word-size term; additional bit-cell and nonadaptive results have separate hypotheses'),
 ref('operator','Lower Bounds for Linear Operators','Young Kun Ko',2025,'https://eccc.weizmann.ac.il/report/2025/155/','22 October; random operators and bit-probe storage; dependence on the number m of queries is essential'),
 ref('dynamic-classic','Crossing the Logarithmic Barrier for Dynamic Boolean Data Structure Lower Bounds','Kasper Green Larsen; Omri Weinstein; Huacheng Yu',2020,'https://epubs.siam.org/doi/10.1137/18M1198429','STOC 2018 precursor; SIAM Journal on Computing 49(5), STOC18-323–STOC18-367, online 12 March 2020'),
 ref('dynamic','An Ω((log n/log log n)²) Cell-Probe Lower Bound for Dynamic Boolean Data Structures','Young Kun Ko',2026,'https://eccc.weizmann.ac.il/report/2026/047/','Manuscript 26 March, report published 5 April; Theorem 1.1 concerns updates in a multiphase problem, not unrestricted static preprocessing')],
 status='source_open',status_note='The primary sources checked through 11 September 2026 leave the static logarithmic barrier open. This card explicitly specializes the broad challenge to deterministic adaptive queries, polynomial-time explicit Boolean functions, Θ(log n)-bit words, and n log² n cells. Conditional proof barriers, larger-query random operators and recent dynamic claims do not resolve that specialization.',formulation_reviewed_on='2026-09-11')
