import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('constant-factor-approximation-for-general-santa-claus-allocation',
 id='TCS-6639',title='A constant-factor approximation for general Santa Claus allocation',area='Scheduling and packing',criterion='resources',question_type='yes_no',
 formal='Is there a universal constant C≥1 and a uniform randomized polynomial-time algorithm that allocates indivisible items with arbitrary nonnegative additive agent-specific values so that, with probability at least 2/3, every agent receives total value at least OPT/C, where OPT is the largest achievable minimum agent value?',
 definitions='An input consists of n≥1 agents, m≥1 items and an explicit n×m matrix (v_ij) of nonnegative rational values, encoded by binary numerators and positive binary denominators. Agent i values a bundle S⊆[m] at v_i(S)=Σ_{j∈S}v_ij. An allocation is a tuple of pairwise disjoint bundles (S_1,…,S_n); unallocated items are permitted. Its value is F(S_1,…,S_n)=min_{i∈[n]}v_i(S_i), and OPT is the maximum of F over all allocations. Let L be the total input bit length. There must be one algorithm, one C independent of n,m and all numerical values, and one polynomial P such that the algorithm always outputs a feasible allocation within P(L) bit operations, for every random tape, and Pr[F≥OPT/C]≥2/3 on every input. The probability refers only to the algorithm’s independent internal random bits and requires the guarantee for all agents simultaneously. A deterministic algorithm is allowed as a special case. Zero values and OPT=0 are allowed, and no positive lower bound on OPT is supplied. The input values are used as given: one may not rescale each agent separately without changing the optimization problem. No identical-valuation, restricted-assignment, bounded-number-of-agents, bounded-number-of-values or bounded-item-degree assumption is imposed. All values are available to a centralized algorithm; incentives, payments and valuation oracles are not part of this problem.',
 answer_criterion='Construct a polynomial-time algorithm achieving the stated guarantee for some fixed C, or prove that no such algorithm exists. Hardness results conditional on a complexity assumption must identify that assumption, including the distinction between deterministic and randomized algorithms. A factor depending on the number of items or agents, a quasi-polynomial-time constant approximation, an estimate without an allocation, or an expected-value guarantee separately for each agent does not meet the target.',
 context=[
 paragraph('The objective protects the least satisfied participant. Suppose two agents value each of two items at one. Allocating one item to each gives minimum value one, whereas giving both items to either agent gives minimum value zero. A lottery that gives both items to a uniformly chosen agent gives each agent expected value one, but its minimum value is always zero. This illustrates why the guarantee must concern the quality of one simultaneous allocation.'),
 paragraph('Even additive values allow substantial heterogeneity: an item can be extremely valuable to one agent, moderately valuable to another, and worthless to a third. Maximizing total welfare would assign each item to an agent valuing it most, independently of the other items. Maximizing minimum welfare couples those decisions because every agent needs adequate value from resources that cannot be reused. The valuations are inputs to the optimization problem, without strategic reporting constraints.'),
 paragraph('The name Santa Claus is used differently across papers. Some reserve it for restricted assignment, where each item j has a single intrinsic value w_j and v_ij is either w_j or zero. This card uses the broader max-min allocation problem with arbitrary entries. The difference is decisive: constant-factor algorithms are known for restricted assignment, while the general constant-factor question remains open.','restricted'),
 paragraph('Chakrabarty, Chuzhoy and Khanna give an approximation within m^ε for every fixed ε>0, where m is the number of items in this card’s notation. Their approximation–time tradeoff also yields a polylogarithmic factor in quasi-polynomial time. Choosing a smaller fixed ε improves the approximation exponent but increases the polynomial running-time exponent. Letting ε depend on m to try to force a constant factor does not preserve the known polynomial-time guarantee.','general'),
 paragraph('Their work also highlights a limitation of a standard configuration relaxation. For a target T, a configuration for agent i is a bundle worth at least T; fractional variables select configurations while respecting item capacities in aggregate. Integral feasible configurations would give every agent enough value. In the general setting, however, the relaxation can overestimate the integral optimum by a factor of order √n. The algorithm uses the relaxation recursively on transformed instances, instead of relying on a constant-loss rounding of its original optimum.','general'),
 paragraph('Restricted assignment has stronger structure. Haxell and Szabó’s 2025 work improves its configuration-LP integrality-gap bound from 3.808 to 3.534 using topological criteria for independent transversals. This is a bound on the distance between fractional and integral optima in the restricted model. It does not assert a 3.534 algorithm for the arbitrary-value matrix, and an existence argument for a good integral solution must be distinguished from an efficient way to construct it.','restricted'),
 paragraph('There is a striking link with minimizing makespan on unrelated machines. Bamas, Lindermayr, Megow, Rohwedder and Schlöter show that a (2−1/α)-approximation for unrelated makespan, for fixed α≥2, would yield an (α+δ)-approximation for general Santa Claus for every fixed δ>0. Thus any fixed improvement below two in that scheduling problem would answer this question positively. Their general implication goes in this direction; equivalence is established for a specified two-value case.','reduction'),
 paragraph('Bamas, Morell and Rohwedder’s SODA 2025 result extends the m^ε and quasi-polynomial polylogarithmic guarantees to arbitrary monotone submodular valuations. It uses a recursively structured LP with exponentially many variables and constraints. This broadens the class of preferences that can be handled, while retaining a growing approximation factor even on the additive instances considered here.','submodular'),
 paragraph('More recent constant guarantees also require attention to their input promise. Boehmer’s April 2026 paper obtains value at least 0.4OPT for identical monotone submodular valuations. Identical preferences are a substantial restriction, even though submodularity is more general than additivity. The outstanding question concerns unrestricted disagreement about item values. Settling it would clarify whether balancing heterogeneous indivisible resources admits a constant loss at polynomial computational cost.','identical')],
 why='The central unresolved max-min allocation question: can all agents be protected to within a constant factor when indivisible resources have arbitrary heterogeneous additive values?',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A major approximation barrier in fair allocation and scheduling, linked by reductions to beating two for unrelated makespan and by relaxation gaps to the limits of fractional methods.'),
 progress=[
 step('2009','Chakrabarty–Chuzhoy–Khanna achieve an arbitrarily small fixed power of the number of items in polynomial time, and a polylogarithmic approximation in quasi-polynomial time.','general'),
 step('2023–2024','Bamas and coauthors show that any fixed improvement below two for unrelated makespan implies a constant-factor approximation for general Santa Claus.','reduction'),
 step('2024–2025','Bamas–Morell–Rohwedder extend the additive problem’s approximation–time tradeoff to monotone submodular valuations; the work appears at SODA 2025.','submodular'),
 step('2025-03-27','Haxell–Szabó prove a 3.534 configuration-LP integrality-gap bound for restricted assignment; arbitrary agent-specific values are outside the result.','restricted'),
 step('2026-04-14','Boehmer obtains a 0.4 welfare guarantee for identical submodular valuations, a different restricted input class.','identical')],
 references=[
 ref('reduction','Santa Claus meets Makespan and Matroids: Algorithms and Reductions','Étienne Bamas; Alexander Lindermayr; Nicole Megow; Lars Rohwedder; Jens Schlöter',2024,'https://arxiv.org/abs/2307.08453','Preprint 17 July 2023; SODA 2024, pp. 2829–2860; Theorem 1 gives the general makespan-to-allocation implication, Theorem 2 concerns two values; inherited source'),
 ref('general','On Allocating Goods to Maximize Fairness','Deeparnab Chakrabarty; Julia Chuzhoy; Sanjeev Khanna',2009,'https://www.cs.dartmouth.edu/~deepc/PUBS/CCK-full.pdf','Full manuscript dated 23 September 2009; FOCS 2009 precursor; abstract and introduction state the approximation–time tradeoff and general configuration-LP gap. Their n denotes items and m agents, opposite to this card.'),
 ref('submodular','The Submodular Santa Claus Problem','Étienne Bamas; Sarah Morell; Lars Rohwedder',2025,'https://arxiv.org/abs/2407.04824','v1, 5 July 2024; SODA 2025, pp. 616–640; introduction retains the general additive constant-factor question and states the extension to submodular values'),
 ref('restricted','Improved Integrality Gap in Max–Min Allocation, or, Topology at the North Pole','Penny Haxell; Tibor Szabó',2025,'https://link.springer.com/article/10.1007/s00493-025-00141-7','Published 27 March; Combinatorica 45, Article 22; restricted-assignment model, 3.534 gap theorem, and distinction between estimation and constructive approximation'),
 ref('identical','Submodular Max-Min Allocation under Identical Valuations','Kimon Boehmer',2026,'https://arxiv.org/abs/2604.12417','v1, 14 April; SWAT 2026 paper; 0.4 approximation assumes the same valuation function for every player')],
 status='source_open',status_note='The SODA 2024 reduction paper and SODA 2025 submodular paper explicitly retain the general additive constant-approximation question. Later checked constant guarantees concern restricted assignment or identical valuations, not arbitrary additive matrices. No general resolution found through 11 September 2026. Randomization and simultaneous success for all agents are explicit in this formulation.',formulation_reviewed_on='2026-09-11')
