import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('graph-isomorphism-in-bqp',
 id='TCS-6522',title='Graph isomorphism in BQP',area='Quantum computation',criterion='resources',question_type='yes_no',
 formal='Is GI∈BQP? Equivalently, does a uniform quantum algorithm decide, on every pair of finite simple graphs on n vertices given by their adjacency matrices, whether they are isomorphic, with error probability at most 1/3 and worst-case total running time n^{O(1)}?',
 definitions='A graph is finite, undirected, loopless and has no parallel edges. For equally sized vertex sets [n]={1,…,n}, an isomorphism from G to H is a bijection π:[n]→[n] satisfying {u,v}∈E(G) if and only if {π(u),π(v)}∈E(H) for every u≠v. The input consists of the two explicitly written binary adjacency matrices; unequal vertex counts are rejected immediately and empty graphs are handled trivially. There are no promises of rigidity, bounded degree, typicality, or a particular input distribution. BQP means a polynomial-time uniform family of quantum circuits over a fixed universal gate set such as Clifford+T, acting on computational-basis encodings of the classical input and initialized ancillas, with a measured output bit. There must be fixed constants C,c such that all gates, measurements and classical control can be implemented within C(n+2)ᶜ total elementary operations. The algorithm accepts each isomorphic pair with probability at least 2/3 and each nonisomorphic pair with probability at most 1/3. It receives no nonuniform advice, witness, graph-orbit state, isomorphism oracle or uncounted memory-preparation service. The target is the decision problem for an ordinary vertex permutation; it is not the distinct relation called quantum graph isomorphism in nonlocal-game theory.',
 answer_criterion='Prove membership by giving a correct uniform quantum algorithm with the stated worst-case polynomial total cost, or prove GI∉BQP. A classical polynomial-time algorithm would also answer yes. A separation for a specified Fourier-sampling or sieve model is not a negative answer for unrestricted BQP; an invariant that distinguishes only some nonisomorphic pairs is not a complete positive answer.',
 context=[
 paragraph('Graph isomorphism asks whether two descriptions encode the same finite relational structure after renaming the vertices. It is an exact equivalence problem, rather than a search for approximately similar networks. A proposed permutation is easy to verify by comparing all adjacency entries, but finding a successful permutation or ruling out every permutation can require reasoning about highly symmetric graphs.'),
 paragraph('Elementary invariants help without settling the problem. For instance, a six-cycle and two disjoint triangles both have six vertices, six edges and degree two at every vertex, but cannot be isomorphic because one is connected and the other is not. More elaborate invariants must likewise be assessed by whether they distinguish every required pair, not just by how well they perform on a test set.'),
 paragraph('Aaronson’s 2005 challenge list identifies graph isomorphism among the natural targets for quantum algorithms beyond Shor and Grover. The formulation on this card turns that broad research motivation into one exact complexity-class membership question. It imposes no particular algorithmic approach and permits a classical algorithm as a special case of a quantum one.','primary'),
 paragraph('Babai’s classical breakthrough gives a quasipolynomial-time algorithm, with bound exp((log n)^{O(1)}). The original argument required a correction in January 2017, after which the quasipolynomial claim was restored. This is the relevant general classical benchmark, rather than brute-force examination of n! permutations. Quasipolynomial time is still larger than the polynomial bound asked for here.','classical'),
 paragraph('One tempting quantum approach uses the action of permutations on graphs. The state that is a uniform superposition over all distinct labeled copies of G would be identical for isomorphic graphs and orthogonal for nonisomorphic ones. If such states could always be prepared efficiently, an overlap test would help. The state-preparation step is the difficulty: preparing a superposition of pairs |π⟩|πG⟩ is easy, but coherently removing the permutation register does not follow from that construction. Simply discarding the register gives a mixed state, not the desired pure superposition.'),
 paragraph('The established hidden-subgroup approach makes this difficulty precise in another form. Graph isomorphism can be reduced to finding hidden symmetry in permutation groups, and the standard procedure generates quantum coset states. Hallgren, Roetteler and Sen, independently of Moore and Russell and later in joint work, prove that measurements on too few such states reveal insufficient information in the relevant hard cases. Their bound requires joint access to Ω(n log n) states to obtain useful information.','cosets'),
 paragraph('That lower bound is a restriction on information extraction in a particular representation. The number of required states is itself polynomial. It does not say that every measurement on that many states needs superpolynomial computation, and it does not forbid an algorithm that uses the explicit input graphs in a different way. A negative solution to GI∈BQP would have to rule out those broader possibilities as well.','cosets'),
 paragraph('The inherited quantum-inspired reference has a substantive June 2026 revision. Maxwell, van den Hoven and Renema analyze correlations in Gaussian boson samplers and derive a classical test for a necessary condition of graph isomorphism. At restricted correlation order it can certify that some graph pairs are different. At the maximum order their condition becomes sufficient, but their method is no longer efficient. The authors explicitly separate these two regimes.','ref2'),
 paragraph('This illustrates why a photonic sampling procedure is not automatically a polynomial-time decision algorithm for all graphs. One must account for how many samples or correlations are required to distinguish a worst-case pair, how accurately they must be estimated, and the classical work used to interpret them. Efficiently generating individual samples does not by itself establish a uniform bound for the complete decision task.','ref2'),
 paragraph('May 2026 work by Gheorghiu, Jacobs, Mehraban and Motamedi studies isomorphism of quantum states under group actions. They show, among other results, that a Clifford-group state problem is at least as hard as ordinary graph isomorphism, while a Pauli-group variant is BQP-complete. The direction and the group matter: the BQP algorithm for the Pauli problem is not thereby an algorithm for the GI-hard Clifford problem.','states'),
 paragraph('A further naming distinction appears in the 2026 paper on the NPA hierarchy by Kar, Roberson, Seppelt and Zeman. It studies a quantum isomorphism relation and its noncommutative semidefinite relaxations, with polynomial-time algorithms at each fixed level. Those statements concern a different relation on graphs and fixed relaxations; they do not establish a quantum algorithm deciding whether an ordinary vertex bijection exists.','quantum-relation'),
 paragraph('A positive answer would enlarge the collection of important exact structure problems known to admit efficient quantum algorithms, unless a classical polynomial algorithm arrived at the same time. A negative answer would be exceptionally strong: GI has efficiently verifiable permutation witnesses and hence belongs to NP, so GI∉BQP would in particular imply P≠NP. The question is fundamental on both sides, independently of any particular physical implementation.')],
 why='A canonical test of whether quantum computation can efficiently recognize equivalence of explicit combinatorial structures, beyond the algebraic problems already handled by standard period finding.',
 importance=dict(score=94,method='editorial',assessed_on='2026-09-11',reason='A central quantum-algorithm target linking graph algorithms, permutation groups and the computational use of entangled states.'),
 progress=[step('2005','Aaronson lists graph isomorphism as a target for new quantum algorithmic ideas.','primary'),step('2005–2010','Coset-state lower bounds establish the need for highly joint measurements in the standard hidden-subgroup approach; the joint journal paper appears in 2010.','cosets'),step('2015–2017','Babai gives a classical quasipolynomial-time algorithm; his January 2017 update repairs the affected recursion and restores the bound.','classical'),step('28 January 2026','Kar–Roberson–Seppelt–Zeman publish polynomial algorithms for fixed levels of a hierarchy for a different quantum isomorphism relation.','quantum-relation'),step('12 May 2026','Gheorghiu and coauthors classify several group-action quantum state problems, with GI-hardness for the Clifford-group version.','states'),step('2 June 2026','Maxwell–van den Hoven–Renema revise their quantum-inspired necessary-condition algorithm; its sufficient full-order version is not efficient.','ref2')],
 references=[ref('primary','Ten Semi-Grand Challenges for Quantum Computing Theory','Scott Aaronson',2005,'https://www.scottaaronson.com/writings/qchallenge.html','Challenge 5, Beyond Shor and Grover; written July 2005; historical motivation only'),ref('ref2','A Quantum-Inspired Algorithm for Graph Isomorphism','Innes L. Maxwell; Stefan N. van den Hoven; Jelmer J. Renema',2026,'https://arxiv.org/abs/2512.24423','Inherited preprint; v3 posted 2 June 2026, original December 2025; §2 distinguishes necessary conditions from the inefficient sufficient full-order test'),ref('classical','Graph Isomorphism in Quasipolynomial Time','László Babai',2016,'https://arxiv.org/abs/1512.03547','STOC 2016, 684–697; original preprint 2015; read together with the January 2017 author correction'),ref('correction','Graph Isomorphism update, January 9, 2017','László Babai',2017,'https://people.cs.uchicago.edu/~laci/update.html','Quasipolynomial claim restored; January 14 addition links the corrected recursive step'),ref('cosets','Limitations of Quantum Coset States for Graph Isomorphism','Sean Hallgren; Martin Roetteler; Pranab Sen',2005,'https://arxiv.org/abs/quant-ph/0511148','Original three-author preprint; later joint version with Cristopher Moore and Alexander Russell, STOC 2006 and JACM 57(6), Article 34 (2010)'),ref('states','Quantum state isomorphism problems for groups','Alexandru Gheorghiu; Dale Jacobs; Saeed Mehraban; Arsalan Motamedi',2026,'https://arxiv.org/abs/2605.12615','12 May 2026; §§4.4–4.5 distinguish Pauli BQP-completeness from Clifford GI-hardness'),ref('quantum-relation','NPA Hierarchy for Quantum Isomorphism and Homomorphism Indistinguishability','Prem Nigam Kar; David E. Roberson; Tim Seppelt; Peter Zeman',2026,'https://quantum-journal.org/papers/q-2026-01-28-1989/','Quantum 10, 1989; fixed hierarchy levels and a different quantum isomorphism relation')],
 status='source_open',status_note='Reviewed through 11 September 2026. No uniform polynomial-time quantum algorithm for ordinary graph isomorphism, or proof of GI∉BQP, was found in the checked primary sources. The 2026 correlation tests, state-isomorphism classifications and NPA hierarchy results do not settle this question.',formulation_reviewed_on='2026-09-11')
