import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('constant-factor-densest-k-subgraph',
 id='TCS-6587', title='Constant-factor approximation for Densest k-Subgraph',
 area='Approximation algorithms and hardness of approximation', criterion='tightness', question_type='yes_no',
 formal='Do there exist a universal constant C≥1 and a uniform deterministic polynomial-time algorithm A such that, for every finite simple undirected unweighted graph G=(V,E) and every integer 1≤k≤|V|, A(G,k) outputs a set S⊆V with |S|=k and |E(G[S])|≥OPT(G,k)/C, where OPT(G,k)=max_{T⊆V, |T|=k}|E(G[T])|?',
 definitions='G is explicitly represented by its vertices and edges, and k is supplied in binary as part of the input. G[S] contains all edges of G with both endpoints in S; loops and parallel edges are absent. The running time is polynomial in the full input length with a fixed exponent independent of k. The same finite C must work for all graphs, all graph sizes and all choices of k; it cannot increase with n=|V| or with k. The output must be a vertex set, not only an estimate of the optimum. When OPT=0, every k-set meets the requirement. Because all feasible sets have the same cardinality, maximizing edge count, average degree 2|E(G[S])|/k, or edges per selected vertex gives the same approximation objective. No promise of a clique, graph expansion, metric edge weights or a random input distribution is supplied. This card fixes deterministic algorithms; a randomized constant-factor guarantee would be major progress but has a distinct derandomization requirement.',
 answer_criterion='Construct one such algorithm and universal constant, or prove that no deterministic polynomial-time constant-factor approximation exists. Under an explicitly stated assumption, a matching impossibility theorem is a conditional answer; ETH already supplies one. Establishing hardness from P≠NP alone would substantially strengthen the evidence. An exact-optimization NP-hardness proof, an integrality gap for a relaxation, an approximation factor growing with n, or a solution permitted to use more than k vertices does not settle the stated existence question.',
 context=[
  paragraph('The task asks for a fixed-size collection of vertices containing as many internal interactions as possible. The cardinality restriction is what turns an otherwise tractable density objective into a central approximation problem. Without a prescribed size, maximizing edges per vertex can be solved in polynomial time. Allowing at least k vertices also changes which solutions compete: a large moderately dense region may be a valid answer even when no comparably useful k-vertex portion can be extracted.','upper'),
  paragraph('Exact optimization contains CLIQUE: a graph has a k-clique precisely when OPT(G,k)=k(k−1)/2. This observation alone gives almost no multiplicative approximation gap. A k-set missing only one possible edge is nearly optimal as k grows, even though it is not a clique. To rule out a constant-factor algorithm, a reduction must create a substantial separation between the best densities of its YES and NO instances, not merely a one-edge difference.'),
  paragraph('Bhaskara, Charikar, Chlamtac, Feige and Vijayaraghavan achieve O(n^(1/4+ε)) approximation in n^O(1/ε) time for every fixed ε>0. Their method uses small tree patterns and a hierarchy of conditioned information to identify a dense region. The O(n^(1/4)) phrase in the paper’s title needs care: attaining that endpoint in their analysis takes quasipolynomial n^O(log n) time. Neither rate is a constant approximation.','upper'),
  paragraph('There is substantial evidence against the target. Manurangsi proves that ETH rules out even approximation within n^(1/(log log n)^a), for a universal constant a>0. ETH asserts that 3SAT has no 2^o(N)-time algorithm on N variables. This is a stronger assumption than P≠NP; the result therefore already excludes every fixed constant under ETH, while leaving the weaker-assumption hardness problem unresolved. Its YES instances can contain a k-clique, a property called perfect completeness.','eth'),
  paragraph('Semidefinite-programming lower bounds supply a different kind of evidence. Bhaskara, Charikar, Guruswami, Vijayaraghavan and Zhou construct polynomial integrality gaps for strong hierarchies of relaxations. A relaxation can assign a large fractional or vector-valued objective even when no genuine k-set has comparable density. Such a gap limits approximation guarantees obtained from that relaxation, but it is not a theorem excluding every polynomial-time combinatorial algorithm.','gaps'),
  paragraph('Chuzhoy, Dalirrooyfard, Grinberg and Tan propose a 2-CSP hardness conjecture that would imply NP-hardness of approximating Densest k-Subgraph within 2^((log n)^ε) for some ε>0. Their paper also connects its approximability to graph partitioning, dense coloring and bounded-crossing subgraphs. Some connections use quasipolynomial reductions, so they should not be read as constant-factor polynomial-time equivalences. The conjectural premise remains a real part of the hardness claim.','csp'),
  paragraph('Laekhanukit, Manurangsi and Trabelsi’s May 2026 paper still reports that no NP-hardness of approximation is known for Densest k-Subgraph even at factor 1.001. They show that the absence of any constant-factor DkS algorithm implies a (3/2−ε) barrier for the at-least-k density problem. This transfers a hypothetical negative answer to a neighboring objective; the neighboring problem’s known 2-approximation does not answer this card.','atleast'),
  paragraph('An AAAI 2026 result by Liu, Liu, Ma and Konar gives an exact continuous penalization reformulation and an efficient nonconvex proximal-gradient method. Exactness concerns the relationship between optima of the formulations. It does not mean the method finds a global optimum, or even a fixed approximation ratio, on every graph in polynomial time. The distinction explains how useful practical progress can coexist with the unresolved worst-case guarantee.','continuous')],
 why='Densest k-Subgraph is a basic test of how well algorithms can identify a concentrated combinatorial structure. Its unresolved approximation landscape influences many reductions and separates strong evidence of difficulty from the hardness consequences currently obtainable from P≠NP.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A flagship approximation problem with a simple objective, a large algorithmic gap, strong conditional and relaxation barriers, and consequences for several other optimization problems.'),
 progress=[
  step('2010','Bhaskara and coauthors obtain O(n^(1/4+ε)) approximation in polynomial time for each fixed ε; the exact quarter-power endpoint has quasipolynomial running time in this work.','upper'),
  step('2012','Bhaskara and coauthors prove polynomial integrality gaps for strong SDP hierarchies, establishing barriers for those relaxations.','gaps'),
  step('2016–2017','Manurangsi proves almost-polynomial-ratio hardness under ETH, with perfect completeness; the revised April 2017 manuscript appears at STOC 2017.','eth'),
  step('2023-02-01','Chuzhoy and coauthors publish a 2-CSP conjecture and conditional superconstant NP-hardness for DkS, together with reductions to related graph objectives.','csp'),
  step('2026-03-14','Liu, Liu, Ma and Konar publish an exact continuous penalization and a nonconvex optimization method; no general constant-factor polynomial-time guarantee is established.','continuous'),
  step('2026-05-25','Laekhanukit, Manurangsi and Trabelsi give reductions to Densest At-Least-k-Subgraph and explicitly retain the missing NP-hardness of even 1.001 approximation for DkS.','atleast')],
 references=[
  ref('upper','Detecting High Log-Densities — an O(n^1/4) Approximation for Densest k-Subgraph','Aditya Bhaskara; Moses Charikar; Eden Chlamtac; Uriel Feige; Aravindan Vijayaraghavan',2010,'https://arxiv.org/abs/1001.2891','STOC 2010, pp. 201–210, DOI 10.1145/1806689.1806718; §1.1 and §4; distinguish fixed-ε polynomial time from the endpoint'),
  ref('gaps','Polynomial integrality gaps for strong SDP relaxations of Densest k-subgraph','Aditya Bhaskara; Moses Charikar; Venkatesan Guruswami; Aravindan Vijayaraghavan; Yuan Zhou',2012,'https://arxiv.org/abs/1110.1360','SODA 2012, pp. 388–405, DOI 10.1137/1.9781611973099.34; Sherali–Adams and Lasserre integrality gaps'),
  ref('eth','Almost-Polynomial Ratio ETH-Hardness of Approximating Densest k-Subgraph','Pasin Manurangsi',2017,'https://arxiv.org/abs/1611.05991','STOC 2017, pp. 954–961, DOI 10.1145/3055399.3055412; v2, 10 April 2017; ETH hardness and perfect completeness'),
  ref('csp','A New Conjecture on Hardness of 2-CSP’s with Implications to Hardness of Densest k-Subgraph and Other Problems','Julia Chuzhoy; Mina Dalirrooyfard; Vadim Grinberg; Zihan Tan',2023,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ITCS.2023.38','ITCS 2023, 38:1–38:23, 1 February; §1 pp. 2–3 conditional DkS hardness; full version arXiv:2211.05906'),
  ref('continuous','A Scalable and Exact Relaxation for Densest k-Subgraph via Error Bounds','Ya Liu; Junbin Liu; Wing-Kin Ma; Aritra Konar',2026,'https://ojs.aaai.org/index.php/AAAI/article/view/38562','AAAI 2026, 40(18):15360–15368, 14 March; DOI 10.1609/aaai.v40i18.38562; continuous penalization and nonconvex optimization'),
  ref('atleast','A Note on Approximability of Densest At-Least-k-Subgraph','Bundit Laekhanukit; Pasin Manurangsi; Ohad Trabelsi',2026,'https://arxiv.org/abs/2605.25464','Preprint v1, 25 May 2026; §1 current DkS hardness status, Theorem 2 reduction to the at-least-k objective')],
 status='source_open', status_note='Checked through 10 September 2026. The constant-factor algorithm is already ruled out assuming ETH, which remains unproved. The May 2026 primary source explicitly notes the absence of NP-hardness of approximation even at factor 1.001. This card asks about a deterministic constant-factor algorithm on all unweighted graphs, and preserves the distinction between conditional evidence and an unconditional resolution.', formulation_reviewed_on='2026-09-10')
