import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('bpp-versus-bqp-bounded-error-decision',
 id='TCS-0036',title='Does BPP differ from BQP?',
 area='Quantum computation',criterion='models',question_type='yes_no',
 formal=r'''Is $\mathrm{BPP}\subsetneq\mathrm{BQP}$? Equivalently, is there a total decision language L⊆{0,1}* with a uniform polynomial-time quantum algorithm that is correct with probability at least 2/3 on every input, but no uniform probabilistic polynomial-time classical algorithm with the same per-input correctness guarantee?''',
 definitions=r'''BPP uses a single classical probabilistic Turing machine with independent unbiased coins, worst-case time C(n+1)^k on n-bit inputs, and error probability at most 1/3 separately for every input. BQP uses a polynomial-time uniform family of polynomial-size quantum circuits: a deterministic classical machine on 1ⁿ generates the circuit description in polynomial time. Fix gates H, T, and CNOT, where H is the Hadamard gate, T=diag(1,exp(iπ/4)), and CNOT is controlled bit-flip. Gates may act on any addressed qubits. The input register starts in |x⟩, polynomially many auxiliary qubits start in |0⟩, and one designated qubit is measured in the computational basis at the end. Its output must equal the membership bit with probability at least 2/3 for every x. The family has no advice, oracle gates, postselection, or arbitrary real-number gate parameters. Size and register bounds use fixed polynomial exponents independent of n. Equivalent standard uniform quantum-machine definitions give the same class. The problem concerns one-bit decisions on all binary strings, with no promise on the input. It does not ask for exact amplitudes, full output distributions, or a separation restricted to shallow classical circuits.''',
 answer_criterion='Prove BPP≠BQP or prove BPP=BQP. Since classical randomized computation can be simulated efficiently by quantum computation, a separation requires a BQP language outside BPP. An exponential oracle-query separation, a sampling separation, or a classical lower bound confined to bounded depth does not by itself provide that language.',
 context=[
  paragraph('Quantum computation uses interference between amplitudes, while a randomized classical algorithm evolves a probability distribution. Both models on this card ultimately output one ordinary bit with bounded error. Efficient classical random computation can be embedded in a quantum circuit, so the question is whether interference provides a strict advantage for some decision problem when both sides receive unrestricted polynomial time.','book'),
  paragraph('Shor’s algorithms give polynomial-time quantum factoring and discrete logarithms. They are compelling candidate advantages because efficient classical algorithms for these tasks are not known. Their classical intractability has not been proved, so the quantum algorithms alone do not separate BPP from BQP. Moreover, these are naturally function problems; a class separation still needs an appropriate decision language and a classical lower bound.','shor'),
  paragraph('Oracle results demonstrate a stronger separation in a different setting. Raz and Tal construct an oracle relative to which BQP is not contained even in the polynomial hierarchy. In that model, an oracle call accesses a specially chosen function at unit cost, including coherently for the quantum machine. Replacing that oracle by an explicit efficiently implemented input computation is an additional requirement, not part of the oracle theorem.','oracle'),
  paragraph('There are also unconditional advantages against restricted classical circuits. Bene Watts and Parham’s August 2026 publication separates constant-depth quantum sampling from specified bounded-fan-in classical sampling models, including a restriction on available random inputs in its uniform result. This establishes an actual lower bound in that model. It leaves open arbitrary-depth polynomial-time classical decision procedures.','shallow'),
  paragraph('Even the equality BPP=BQP would assert efficient simulation only of the decision tasks defining these classes. A demand to reproduce every quantum output distribution or calculate every amplitude to high precision can be computationally stronger. Keeping the output requirement explicit prevents those simulation problems from being mistaken for this one.')],
 why='This is the basic complexity-theoretic question of whether quantum computation expands the set of efficiently decidable problems beyond classical randomization. It gives a precise target behind the broader phrase quantum advantage and distinguishes unrestricted computational power from experimentally or structurally restricted demonstrations.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A central foundational separation between classical and quantum efficient computation, with consequences for algorithms, simulation, and the computational interpretation of quantum mechanics.'),
 progress=[
  step('1990s','Uniform bounded-error quantum computation is formalized, with BPP⊆BQP. Wigderson’s Definition 11.1 and Theorem 11.2 state the model and inclusion.','book'),
  step('1994 conference / 1995–1996 preprint','Shor gives polynomial-time quantum algorithms for prime factorization and discrete logarithms. No unconditional classical polynomial-time lower bound for those tasks follows.','shor'),
  step('2019 conference / 2022 journal','Raz and Tal prove an oracle separation BQP⊄PH. This also separates BQP from BPP relative to that oracle, but not in ordinary unrelativized computation.','oracle'),
  step('2026-08','Bene Watts and Parham publish an unconditional shallow-circuit sampling separation. Its classical resource restrictions and sampling output differ from the unrestricted decision model fixed here.','shallow')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2018,'https://www.math.ias.edu/files/mathandcomp.pdf','27 March 2018 draft; Chapter 11, Definition 11.1, Theorem 11.2, and Conjecture 11.4, printed page 136'),
  ref('shor','Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer','Peter W. Shor',1996,'https://arxiv.org/abs/quant-ph/9508027v2','25 January 1996 revision; preliminary FOCS 1994 result, subsequent SIAM Journal on Computing publication'),
  ref('oracle','Oracle Separation of BQP and PH','Ran Raz; Avishay Tal',2022,'https://doi.org/10.1145/3530258','JACM 69(4), Article 30; preliminary STOC 2019 version; the theorem is explicitly relativized'),
  ref('shallow','Unconditional Quantum Advantage for Sampling with Shallow Circuits','Adam Bene Watts; Natalie Parham',2026,'https://quantum-journal.org/papers/q-2026-08-12-2188/','Quantum 10, 2188, published 12 August 2026; corresponding arXiv:2301.00995v5. The uniform sampling theorem restricts classical fan-in and randomness.')],
 status='source_open',status_note='Wigderson’s Conjecture 11.4 explicitly asks for strict containment. Primary literature was checked through 10 September 2026; no unrelativized separation of these bounded-error decision classes was located. Oracle and shallow-circuit sampling advantages are recorded with their model restrictions.',formulation_reviewed_on='2026-09-10')
