import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('nonuniform-tc-zero-versus-nc-one',
 id='TCS-6535', title='Is nonuniform TC⁰ strictly smaller than nonuniform NC¹?',
 area='Computational complexity', criterion='models', question_type='yes_no',
 formal='Is TC⁰⊊NC¹ for the nonuniform circuit classes defined below? Equivalently, does there exist a Boolean function family f=(f_n:{0,1}^n→{0,1}) in NC¹ such that for every fixed depth d≥1, exponent k≥1, and constant M≥1, there is an n for which every depth-at-most-d majority circuit computing f_n exactly has size greater than M(n+1)^k?',
 definitions='A circuit is a finite directed acyclic graph with input nodes x_1,…,x_n, optional constants 0,1, and one output. Depth is the maximum number of gates on an input-to-output path. Size is the number of gates plus the number of wires; if an input is repeated at a gate, each occurrence counts as a wire. A majority circuit has AND and OR gates of arbitrary positive fan-in, NOT gates of fan-in one, and MAJ gates of arbitrary positive fan-in m, with output 1 exactly when strictly more than m/2 inputs equal 1. TC⁰ consists of all families with such circuits of size M(n+1)^k and depth at most d for every n, for some constants M,k,d depending on the family. NC¹ consists of families with circuits over AND, OR, NOT, with fan-in at most two (one for NOT), size M(n+1)^k, and depth at most b log_2(n+1), for fixed M,k,b. Circuits may share intermediate gates. Both classes are nonuniform: an arbitrary separate circuit may be chosen for each input length, without any requirement to compute its description. The output must be correct on every input; no randomness, approximation, promise, or distributional error is allowed.',
 answer_criterion='Prove that some NC¹ family has no polynomial-size majority circuits of any fixed depth, or prove NC¹⊆TC⁰, which would give equality because TC⁰⊆NC¹ is known. Excluding only one or finitely many depths, or proving a fixed polynomial lower bound, is not by itself a separation. A lower bound for an E^NP language without NC¹ membership does not provide the required family. Results for uniform classes alone must not be substituted for this nonuniform question.',
 context=[
  paragraph('The two models trade different resources. A majority gate can aggregate arbitrarily many bits in one step, whereas a binary Boolean gate sees only two. NC¹ permits logarithmically many layers of binary computation. A majority of polynomially many bits can itself be computed by a polynomial-size logarithmic-depth Boolean circuit, so a constant number of majority layers gives TC⁰⊆NC¹. The open issue is whether counting in a fixed number of layers can also replace every logarithmic-depth computation.'),
  paragraph('Arithmetic tasks are an instructive warning against judging depth from familiar sequential algorithms. Hesse, Allender, and Barrington prove that integer division and iterated multiplication have even DLOGTIME-uniform TC⁰ circuits. A binary long-division procedure takes many dependent steps, but that procedure does not establish a lower bound on all circuits for division. These arithmetic problems therefore cannot serve as the missing separation.','division'),
  paragraph('There are concrete complete problems on the NC¹ side. Evaluating a Boolean formula, and evaluating a product of elements of the fixed permutation group S_5, capture NC¹ under very simple reductions. S_5 consists of the 120 permutations of five objects, with permutation composition as its operation. Thus the problem can be approached through a fixed finite algebraic operation repeated on a long input, without requiring complicated individual gates. Chen and Tell study these complete problems in their lower-bound amplification results.','boot'),
  paragraph('Their result shows that surprisingly mild improvements in known bounds could suffice. Suitable wire lower bounds of the form n^(1+c^(−d)) for an NC¹-complete problem, uniformly strong enough as the constant depth d grows, would imply a full separation. The depth dependence of the exponent is essential: obtaining a superlinear bound at an isolated depth is a much weaker statement.','boot'),
  paragraph('Dawar and Evans give an algebraic characterization of uniform NC¹ using typed monoids in FSTTCS 2025, extending earlier work on uniform TC⁰. Typed monoids allow infinite algebraic structures while restricting recognition through finitely many types. This supplies another mathematical language in which to compare the classes. Their theorem is a characterization, not a separation, and its uniform scope must be kept distinct from this card’s formulation.','typed'),
  paragraph('Chen, Tal, and Wang’s 2026 result proves n^(2.5−ε) gate lower bounds for depth-two linear-threshold circuits computing an E^NP function. Linear-threshold gates test weighted sums against a threshold, unlike the unweighted majority gates fixed in the definition above. Beyond this gate convention, the result addresses a single depth, a polynomial bound, and a much larger ambient class for the hard function. Those distinctions explain why the new lower bound does not resolve TC⁰ versus NC¹.','ctw')],
 why='One of the central small-circuit questions: whether a constant number of counting layers can perform every logarithmic-depth Boolean computation. A resolution would clarify the power of threshold circuits, finite-group computation, and the role of sequential dependence in parallel computation.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A flagship unresolved containment between basic circuit classes, with explicit complete problems and connections to arithmetic, algebraic automata theory, and lower-bound amplification.'),
 progress=[
  step('2002','Hesse, Allender, and Barrington place division and iterated multiplication in DLOGTIME-uniform TC⁰, demonstrating the arithmetic power already available at constant depth.','division'),
  step('2018–2019','Chen and Tell show how improvements in the depth dependence of superlinear wire lower bounds for certain NC¹-complete problems would yield superpolynomial TC⁰ lower bounds.','boot'),
  step('2025-12-09','Dawar and Evans characterize uniform NC¹ with typed monoids and unary generalized quantifiers. The containment comparison remains open.','typed'),
  step('2026','Chen, Tal, and Wang prove superquadratic gate lower bounds for depth-two weighted threshold circuits for an E^NP function; the result does not supply an NC¹ separation against every constant depth.','ctw')],
 references=[
  ref('boot','Bootstrapping Results for Threshold Circuits “Just Beyond” Known Lower Bounds','Lijie Chen; Roei Tell',2019,'https://eccc.weizmann.ac.il/report/2018/199/','ECCC TR18-199; STOC 2019; lower-bound implication for NC¹-complete Boolean formula evaluation, S_5 word problem and width-five connectivity'),
  ref('division','Uniform constant-depth threshold circuits for division and iterated multiplication','William Hesse; Eric Allender; David A. Mix Barrington',2002,'https://doi.org/10.1016/S0022-0000(02)00025-9','Journal of Computer and System Sciences 65(4), 695–716; DLOGTIME-uniform TC⁰ upper bounds'),
  ref('typed','Characterizing NC¹ with Typed Monoids','Anuj Dawar; Aidan T. Evans',2025,'https://doi.org/10.4230/LIPIcs.FSTTCS.2025.26','FSTTCS 2025, 26:1–26:19; §§1–2 explicitly fix uniform classes; §4 algebraic characterization'),
  ref('ctw','Super-quadratic Lower Bounds for Depth-2 Linear Threshold Circuits','Lijie Chen; Avishay Tal; Yichuan Wang',2026,'https://eccc.weizmann.ac.il/report/2026/039/','ECCC TR26-039, 14 March 2026; STOC 2026; n^(2.5−ε) gate lower bounds for THR∘THR and hard functions in E^NP')],
 status='source_open', status_note='Checked through 10 September 2026. No separation or collapse of these nonuniform classes was identified. Recent typed-monoid results concern uniform characterizations, while 2026 depth-two lower bounds concern polynomial gate or wire counts for E^NP functions. All-depth superpolynomial lower bounds for an NC¹ family remain the target.', formulation_reviewed_on='2026-09-10')
