import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('bodirsky-pinsker-infinite-domain-csp-dichotomy',
 id='TCS-6636',title='The Bodirsky–Pinsker infinite-domain CSP dichotomy',
 area='Constraint satisfaction',criterion='characterization',question_type='yes_no',
 formal='For every countable finitely bounded homogeneous structure A over a finite relational signature, and every finite-signature first-order reduct B of A, is CSP(B) either decidable in deterministic polynomial time or NP-complete under polynomial-time many-one reductions?',
 definitions='A relational signature is a finite list of relation symbols with fixed finite arities. A is homogeneous if every isomorphism between two finite induced substructures extends to an automorphism of A. It is finitely bounded if there is a finite set F of finite structures in its signature such that a finite structure embeds into A exactly when none of the structures in F embeds into it; embeddings preserve both relations and their complements. Countable allows finite or countably infinite domains. B has the same domain as A, with finitely many relations each definable by a first-order formula over A without parameters; it may forget original relations and introduce definable ones. For each fixed B, an input to CSP(B) is an explicitly encoded finite structure I in B’s signature. Accept exactly when there is a map h from the domain of I to that of B preserving every relation tuple. Equivalently, a finite conjunction of atomic B-constraints must have a satisfying assignment. h need not be injective. A, B and their defining formulas are fixed, not part of the input; running times are measured in the finite instance’s bit length.',
 answer_criterion='Prove the stated dichotomy for every permitted template B, or exhibit a permitted fixed B and prove that CSP(B) is neither in P nor NP-complete. These CSPs are in NP, so a counterexample would be an NP-intermediate problem and would in particular establish P≠NP. A conditional negative answer must state its assumption. The question does not require an algorithm that decides which side an arbitrary encoded template belongs to, nor the stronger proposed algebraic characterization of the two sides.',
 context=[
  paragraph('The finite-domain CSP dichotomy, proved independently by Bulatov and Zhuk in 2017, says that fixing a finite collection of relations on a finite domain leaves no intermediate complexity between polynomial time and NP-completeness. The infinite-domain conjecture asks whether this organizing principle survives when variables can take rational values, positions in a countable graph, or other infinitely many possibilities, provided the template has a finite structural description.','finite'),
  paragraph('The restrictions explain why the question is computationally meaningful. Homogeneity means that finite patterns completely determine their symmetry type. Finite boundedness gives a finite list of forbidden patterns for checking whether a proposed finite configuration can occur. For a fixed reduct, one can guess a partition of the variables representing equal values and the finite relational pattern on those values, then check the constraints and forbidden patterns. The signature and forbidden sizes are constants, so this yields polynomial-size NP certificates despite the infinite domain.','book'),
  paragraph('For a concrete example, the ordered rational numbers (ℚ;<) are homogeneous and finitely bounded. Constraints consisting only of strict inequalities are feasible exactly when their directed inequality graph is acyclic. Adding the definable ternary relation “y lies strictly between x and z” gives the classical NP-complete Betweenness problem. Thus the same domain can support both tractable and hard constraint languages; the choice of allowed relations is decisive.','three'),
  paragraph('A central method studies polymorphisms: operations which, applied coordinatewise to several satisfying tuples of any relation, produce another satisfying tuple. Such operations record ways of combining solutions and can prevent standard hardness gadgets. Barto and Pinsker identify a particular algebraic identity that characterizes the absence of the relevant hardness construction for model-complete cores. The missing general step is turning the tractable-side algebraic structure into polynomial-time algorithms. The bare P/NP-complete dichotomy asked here is weaker than proving that full algebraic classification.','algebra'),
  paragraph('Pinsker, Rydval, Schöbi, Spiess and Winkler’s May 2026 revision shows that the conjecture can be reduced to templates without algebraicity: fixing finitely many elements does not force any additional element into a finite orbit. Their construction replaces domain elements by infinite families while preserving the relevant constraint complexity. They also connect tractable infinite-domain templates to finite-domain promise CSPs through intermediate structures. These are reductions in the scope of the conjecture, rather than a general tractability algorithm.','three'),
  paragraph('Dorochko and Wrona’s July 2026 revision proves a different dichotomy: for first-order expansions of finitely bounded homogeneous model-complete cores, the CSP is first-order definable or hard for deterministic logarithmic space under first-order reductions. An expansion retains all original relations; this hypothesis does not cover arbitrary reducts. Moreover, L-hard problems can still be in P, so the result separates a much lower boundary and leaves the P versus NP-complete question open.','fo'),
  paragraph('Feller and Pinsker’s August 2026 revision develops effective tools for comparing templates. In particular, a model-complete core is computable when the structure has a finitely bounded Ramsey expansion, an additional structural hypothesis. Their decidability results concern interpretability and equivalent algebraic presentations, not a complete algorithmic classification of all templates in this card.','interpret'),
  paragraph('A resolution would say whether a finite description by symmetric local patterns rules out intermediate NP complexity across a large family of logical and combinatorial problems. The difficulty is to find algorithms that exploit this description uniformly within each fixed template, without assuming that the infinitely many possible values can simply be replaced by one fixed finite domain.')],
 why='The main tractability-classification conjecture for well-behaved infinite-domain CSPs. It links algorithm design, universal algebra and model theory, and would extend the finite-domain dichotomy to substantially richer constraint languages.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A central unifying conjecture about the boundary of polynomial-time constraint solving, with broad logical scope and active links to promise CSPs.'),
 progress=[
  step('2017','Bulatov and Zhuk independently prove the finite-domain CSP dichotomy; infinite domains require additional structural arguments.','finite'),
  step('2020','Barto–Pinsker give a purely algebraic characterization of the relevant hardness obstruction for model-complete cores. The general tractability implication remains conjectural.','algebra'),
  step('2021–2026','Bodirsky’s monograph develops the framework; the checked author postprint is dated 31 January 2026.','book'),
  step('2026-05-06','The revised Three Fundamental Questions paper reduces the conjecture to templates without algebraicity and strengthens links with finite-domain promise CSPs.','three'),
  step('2026-07-14','Dorochko–Wrona’s v3 establishes an FO/L-hard dichotomy for expansions of homogeneous model-complete cores, not the full P/NP-complete dichotomy.','fo'),
  step('2026-08-05','Feller–Pinsker’s v2 provides decidability and computable-core tools under additional structural hypotheses.','interpret')],
 references=[
  ref('finite','A Proof of the CSP Dichotomy Conjecture','Dmitriy Zhuk',2020,'https://arxiv.org/abs/1704.01914','FOCS 2017 precursor; Journal of the ACM 67(5), Article 30, DOI 10.1145/3402029; independent finite-domain proof by Bulatov, arXiv:1703.03021'),
  ref('book','Complexity of Infinite-Domain Constraint Satisfaction','Manuel Bodirsky',2021,'https://wwwpub.zih.tu-dresden.de/~bodirsky/Book.pdf','Cambridge Lecture Notes in Logic 52, DOI 10.1017/9781107337534; checked author postprint 31 January 2026; Chapter 1 and Chapter 14'),
  ref('algebra','Topology Is Irrelevant (In a Dichotomy Conjecture for Infinite Domain Constraint Satisfaction Problems)','Libor Barto; Michael Pinsker',2020,'https://doi.org/10.1137/18M1216213','SIAM Journal on Computing 49(2):365–393; pseudo-Siggers characterization of the hardness obstruction'),
  ref('three','Three Fundamental Questions in Modern Infinite-Domain Constraint Satisfaction','Michael Pinsker; Jakub Rydval; Moritz Schöbi; Christoph Spiess; Paul Winkler',2026,'https://arxiv.org/abs/2502.06621','v4, 6 May; Conjecture 1.4, Theorem 1.5 and §1.4; MFCS 2025 precursor, DOI 10.4230/LIPIcs.MFCS.2025.83'),
  ref('fo','Constraint Satisfaction Problems over Finitely Bounded Homogeneous Structures: a Dichotomy between FO and L-hard','Leonid Dorochko; Michał Wrona',2026,'https://arxiv.org/abs/2601.22691','v3, 14 July; Conjecture 1.1, Theorem 1.3 and explicit discussion of why expansions are required'),
  ref('interpret','Decidability of Interpretability','Roman Feller; Michael Pinsker',2026,'https://arxiv.org/abs/2602.02302','v2, 5 August; LICS 2026.42, DOI 10.4230/LIPIcs.LICS.2026.42; computable model-complete cores under a finitely bounded Ramsey-expansion hypothesis')],
 status='source_open',status_note='Checked through 10 September 2026. The latest checked primary papers explicitly retain the general dichotomy as open. The July FO/L-hard classification has both a different complexity boundary and an expansion hypothesis; the August interpretability result does not settle tractability.',formulation_reviewed_on='2026-09-10')
