import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('dynamic-local-bipartite-three-coloring-logarithmic',
 id='TCS-0516',title='Can bipartite 3-coloring be maintained with logarithmic recoloring radius?',
 area='Distributed and local algorithms',criterion='resources',question_type='yes_no',
 formal=r'''Is there a deterministic algorithm and a universal constant C such that, for every n and every adversarial sequence of edge insertions into an initially edgeless graph on [n], with every intermediate graph bipartite, the algorithm maintains a proper coloring with colors {1,2,3} while changing colors only within distance C log₂(n+2) of an endpoint of the newly inserted edge? Distance is measured in the graph immediately after that insertion. The algorithm sees the entire current graph and may retain arbitrary state, but has no knowledge of future insertions.''',
 definitions=r'''The vertex set [n] and n are supplied initially. The graphs are finite, simple and undirected, and maximum degree is unrestricted. An insertion adds one previously absent edge {u,v}; no edge deletions or supplied bipartition are included. The adversary may select its next insertion after inspecting the algorithm’s previous colors. Before any insertion the algorithm chooses a color for each isolated vertex. After update i it must output c_i:[n]→{1,2,3} with c_i(x)≠c_i(y) for every edge {x,y} of G_i. If min(dist_G_i(w,u),dist_G_i(w,v))>⌈C log₂(n+2)⌉, then c_i(w)=c_{i−1}(w); vertices in other components have infinite distance. All colors must be valid after every update. One computable program works for all n and terminates on every update. Global reading, computation time, memory and the number of recolorings inside the permitted neighborhood are unrestricted. The resource being bounded is the worst-case spatial radius of changed output, not amortized update time or communication rounds. This fixes the incremental edge-update convention of dynamic-LOCAL.''',
 answer_criterion='Give such an algorithm with a proof valid for every bipartite insertion sequence, or prove that no deterministic algorithm has an O(log n) worst-case recoloring radius. A bound only for trees, only on the number of recolored vertices, or for a model with advance access to future edges does not settle this formulation.',
 context=[
  paragraph('Every intermediate graph has a two-coloring, but a maintained coloring commits to choices before future edges are known. Two separately colored components may later be joined with incompatible parities. With only two colors, repairing that conflict can force a change across a large component. A third color offers additional ways to create a local transition between regions.'),
  paragraph('The question measures where a repair spreads. It does not limit how much of the graph the algorithm may inspect to decide on that repair. In particular, an algorithm could perform expensive global computation and still have small dynamic locality if only nearby output labels change. Conversely, a fast data structure could recolor a distant vertex and violate the radius bound.'),
  paragraph('The online-LOCAL model has a different source of power: when a vertex must be colored, a neighborhood in the eventual input graph is revealed. The ICALP 2023 algorithm uses logarithmic visibility to 3-color bipartite graphs. That result is a useful benchmark, but does not provide a logarithmic repair radius when edges themselves arrive without such advance visibility.', 'models'),
  paragraph('The later logarithmic lower bound for online-LOCAL already holds on grids and transfers to the weaker dynamic-LOCAL setting. Therefore an affirmative answer here would attain the correct asymptotic order. It remains possible that repairing a sequence of past commitments requires a substantially larger radius than choosing a color with a view into the eventual graph.', 'lower'),
  paragraph('The corrected February 2026 comparison paper still lists a logarithmic lower bound and a roughly square-root upper bound for dynamic-LOCAL bipartite 3-coloring. It also withdraws an earlier general claim about derandomizing LOCAL in dynamic-LOCAL. The card uses the corrected version when describing the relationship between the models.', 'comparison')],
 why='Bipartite 3-coloring is a simple test of whether global information and local repairs can match the power of online lookaround. A tight answer would clarify a basic separation between dynamic and online computation without hiding the issue in expensive local processing.',
 importance=dict(score=81,method='editorial',assessed_on='2026-09-10',reason='A canonical coloring task that tests the power of maintaining solutions under local changes. The logarithmic target matches a known lower bound, and its resolution would clarify the relationship between two general locality models.'),
 progress=[
  step('2023','Akbari and coauthors define incremental dynamic-LOCAL and give an O(log n)-locality online-LOCAL algorithm for 3-coloring bipartite graphs. The online algorithm is not a dynamic repair algorithm.','models'),
  step('2024','Chang, Mishra, Nguyen, Yang, and Yeh establish an Ω(log n) deterministic online-LOCAL lower bound even for grids. Together with the model simulation, this supplies the same lower bound for dynamic-LOCAL.','lower'),
  step('2026-02-13','The corrected v4 of Online Locality Meets Distributed Quantum Computing retains Õ(√n) versus Ω(log n) in the dynamic-LOCAL entry of Table 1. Its corrections section withdraws a claimed general dynamic derandomization theorem from earlier versions.','comparison'),
  step('2026-02-23','Suomela’s updated open-problem page explicitly asks whether dynamic-LOCAL can 3-color bipartite graphs with O(log n) locality.','problem')],
 references=[
  ref('models','Locality in Online, Dynamic, Sequential, and Distributed Graph Algorithms','Amirreza Akbari; Navid Eslami; Henrik Lievonen; Darya Melnyk; Joona Särkijärvi; Jukka Suomela',2023,'https://doi.org/10.4230/LIPIcs.ICALP.2023.10','ICALP 2023; dynamic-LOCAL definition, model simulations, Theorem 1.1 and open questions; full version arXiv:2109.06593'),
  ref('lower','A Tight Lower Bound for 3-Coloring Grids in the Online-LOCAL Model','Yi-Jun Chang; Gopinath Mishra; Hung Thuan Nguyen; Mingyang Yang; Yu-Cheng Yeh',2024,'https://arxiv.org/abs/2312.01384v4','Revised 1 May 2024; abstract and main logarithmic lower bound'),
  ref('comparison','Online Locality Meets Distributed Quantum Computing','Amirreza Akbari; Xavier Coiteux-Roy; Francesco d’Amore; François Le Gall; Henrik Lievonen; Darya Melnyk; Augusto Modanese; Shreyas Pai; Marc-Olivier Renou; Václav Rozhoň; Jukka Suomela',2026,'https://arxiv.org/abs/2403.01903v4','Corrected 13 February 2026 version of STOC 2025 work; Table 1, model definitions, and corrections section'),
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#dynamic-online','Updated 23 February 2026; Dynamic-LOCAL and online-LOCAL models, vertex coloring')],
 status='source_open',status_note='The February 2026 primary problem list retains the logarithmic-radius question, consistently with the corrected v4 comparison table. No later resolution located through 10 September 2026.',formulation_reviewed_on='2026-09-10')
