import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('constant-factor-universally-truthful-submodular-auctions',
 id='TCS-6632',title='Constant-factor universally truthful auctions for submodular bidders',area='Algorithmic game theory, mechanism design and fair division',criterion='resources',question_type='yes_no',
 formal='Does there exist a universal constant C≥1 and a randomized, universally truthful combinatorial-auction mechanism that, for every number n of bidders, number m of items and normalized monotone submodular valuation profile, uses polynomial communication and produces an allocation of expected social welfare at least OPT/C?',
 definitions='There are m≥1 distinct indivisible items and n≥1 bidders. Bidder i privately knows v_i:2^[m]→Q_{≥0}, with v_i(∅)=0, v_i(S)≤v_i(T) for S⊆T, and v_i(S)+v_i(T)≥v_i(S∪T)+v_i(S∩T) for all S,T. To make communication in bits precise, a public integer B≥1 bounds the binary lengths of the numerator and positive denominator of each value. This is a bound per value, not permission to transmit the exponential table. One uniform protocol must work for every n,m,B with at most P(n,m,B) communicated bits in the worst case, for one fixed polynomial P. Arbitrary interactive messages and demand queries are allowed; all query descriptions, replies, allocations and payments count toward communication. Local computation by bidders and auctioneer is unrestricted but must terminate. An outcome consists of pairwise disjoint bundles S_1,…,S_n and rational payments p_1,…,p_n; unallocated items are allowed. Utilities are quasilinear, u_i=v_i(S_i)−p_i. There are no private budgets or distributional assumptions. Universal truthfulness means the mechanism is a report-independent distribution over deterministic dominant-strategy truthful mechanisms: for every fixed random seed r, every i, every admissible true and alternative reported type v_i,v_i′, and every v_{−i}, v_i(S_i(v_i,v_{−i};r))−p_i(v_i,v_{−i};r)≥v_i(S_i(v_i′,v_{−i};r))−p_i(v_i′,v_{−i};r). A low-communication protocol implements this outcome and payment rule on the distributed reported types. OPT=max Σ_i v_i(T_i), where the maximum is over pairwise disjoint T_i⊆[m]. The expected welfare guarantee holds for every truthful valuation profile, with expectation only over the mechanism’s randomness; C is independent of n,m,B. No additional individual-rationality or transfer-sign restriction is imposed in this formulation.',
 answer_criterion='Construct such a universal constant-factor mechanism, or prove that every universally truthful polynomial-communication mechanism fails every constant welfare factor on some admissible profiles. A lower bound for value queries alone, or for polynomial local computation, does not refute this communication-model question. Truthfulness only in expectation is a weaker incentive condition and does not constitute a positive answer. A factor growing with m, even as slowly as log log m, is partial progress.',
 context=[
 paragraph('A bidder may value several items as substitutes. For example, a coverage valuation assigns each item a set of useful features and values a bundle by the total weight of features covered at least once. Receiving an item has less marginal value when many of its features are already covered. Submodularity abstracts this diminishing-returns property without requiring the valuation to be supplied as an explicit coverage instance.'),
 paragraph('The auctioneer must allocate the items using information held by strategic bidders. Maximizing the sum of their values is the social-welfare objective; maximizing the auctioneer’s revenue would be a different problem. Payments influence what information bidders choose to provide, but are transfers and do not enter the welfare objective. Even a very poor revenue guarantee would be acceptable here if incentives and welfare met the stated requirements.'),
 paragraph('There are two individually successful starting points. With complete reports and unrestricted resources, the Vickrey–Clarke–Groves mechanism obtains optimal welfare and truthful incentives. If incentives are omitted, submodular welfare admits constant-factor approximation from compact queries. The difficulty is combining the guarantees while avoiding communication of exponentially many bundle values. The 2026 graph-auctions paper describes this communication perspective explicitly.','graphs'),
 paragraph('Universal truthfulness is a strong use of randomization: each mechanism obtained after fixing the coins must itself make truthful reporting optimal. Truthfulness in expectation requires only that the average utility discourage lying. The distinction has mathematical force; Dobzinski and Dughmi separate the two notions in a restricted multi-unit setting. Their separation is useful background, but their multi-unit approximation scheme does not supply a mechanism for arbitrary heterogeneous submodular valuations.','randomness'),
 paragraph('A demand query offers item prices and asks a bidder to choose a bundle maximizing its value minus its total price. Sending that bundle requires only m membership bits, even when finding it takes enormous local computation. This is why allowing demand queries changes the problem substantially. The formulation deliberately measures communication: an algorithm that delegates difficult optimization to a bidder can qualify. It would need further work to become computationally efficient for that bidder.'),
 paragraph('Dobzinski’s impossibility theorem rules out universally truthful m^{1/2−ε}-approximation using polynomially many value queries, for every fixed ε>0. A value query reveals only one specified bundle’s value. The theorem is a genuine barrier in that access model, but it cannot be extended by simply treating a demand query as one more value query. A demand answer can encode the result of comparing exponentially many bundles.','value_lower'),
 paragraph('Assadi and Singla reached an expected O((log log m)³) approximation using O(n) demand queries, at FOCS 2019. Assadi, Kesselheim and Singla subsequently improved the submodular guarantee to O((log log m)²), while obtaining O((log log m)³) for the broader subadditive class. These asymptotic factors grow with the number of items, despite growing very slowly.','improved'),
 paragraph('The latter mechanism learns approximate item prices through random groups of bidders. A bidder participates in a single fixed-price auction, so its own report cannot manipulate the menu it faces. Some price-learning rounds can become the final allocation rather than merely gathering information; the analysis accounts for welfare earned in those rounds. This makes price discovery compatible with truthfulness, but leaves a loss between the learned allocation and optimal welfare.','soda'),
 paragraph('Recent positive results for graph auctions restrict each item to a small set of eligible bidders. For example, the 2026 paper gives a truthful factor-two mechanism when each item has two eligible bidders and valuations are subadditive. This structural restriction supplies information absent in a general auction, so it does not settle the present question. A general constant-factor mechanism would show that exact incentive compatibility need not impose an unbounded welfare loss in this central communication model.','graphs')],
 why='Determine whether exact truthful incentives inherently cause an unbounded loss of allocative efficiency, even when arbitrary compact communication and unlimited local optimization are available.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A central multi-parameter mechanism-design problem linking truthful incentives, submodular optimization, information elicitation and the communication cost of welfare approximation.'),
 progress=[
 step('2009','Dobzinski–Dughmi distinguish universal truthfulness from truthfulness in expectation and separate their power in a restricted multi-unit setting.','randomness'),
 step('2010–2011','Dobzinski proves exponential value-query requirements for universally truthful m^{1/2−ε}-approximation; arbitrary communication remains outside this lower bound.','value_lower'),
 step('2019','Assadi–Singla obtain expected O((log log m)³)-approximation with universal truthfulness and O(n) demand queries.','improved'),
 step('2020–2021','Assadi–Kesselheim–Singla improve the submodular and XOS factor to O((log log m)²); Theorem 2 uses at most n value and demand queries.','soda'),
 step('2026-02-25','Christodoulou–Koutsoupias–Kovács–Vlachos establish constant truthful guarantees under graph eligibility restrictions, without solving unrestricted submodular auctions.','graphs')],
 references=[
 ref('improved','Improved Truthful Mechanisms for Combinatorial Auctions with Submodular Bidders','Sepehr Assadi; Sahil Singla',2025,'https://epubs.siam.org/doi/10.1137/20M1316068','FOCS 2019 result; journal online 14 February 2023, collected in SIAM Journal on Computing 54(4), August 2025; O((log log m)³) universal guarantee; inherited source'),
 ref('randomness','On the Power of Randomization in Algorithmic Mechanism Design','Shahar Dobzinski; Shaddin Dughmi',2009,'https://theory.stanford.edu/~shaddin/papers/randompower-focs09.pdf','FOCS 2009; introduction defines the two randomized truthfulness notions; separation concerns restricted multi-unit auctions; inherited source'),
 ref('value_lower','An Impossibility Result for Truthful Combinatorial Auctions with Submodular Valuations','Shahar Dobzinski',2011,'https://arxiv.org/abs/1011.1830','Preprint 8 November 2010; STOC 2011, pp. 139–148; lower bound expressly restricted to value queries'),
 ref('soda','Improved Truthful Mechanisms for Subadditive Combinatorial Auctions: Breaking the Logarithmic Barrier','Sepehr Assadi; Thomas Kesselheim; Sahil Singla',2021,'https://arxiv.org/abs/2010.01420','v1, 3 October 2020; SODA 2021, pp. 653–661; Sections 1–2 define the model; Theorem 2 gives the improved squared-log-log factor for submodular and XOS bidders'),
 ref('graphs','The Communication Complexity of Combinatorial Auctions in Graphs','George Christodoulou; Elias Koutsoupias; Annamária Kovács; Ioannis Vlachos',2026,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.STACS.2026.27','Published 25 February; introduction and Section 1.2 discuss general communication complexity; Corollary 22 is the factor-two truthful subadditive mechanism with two eligible bidders per item')],
 status='source_open',status_note='The checked primary literature retains a gap between constant nontruthful welfare approximation and the general universally truthful guarantee. Theorem 2 of the SODA 2021 paper supplies O((log log m)²) for submodular bidders. The 2026 graph-auction results impose eligibility restrictions. No general constant-factor resolution found through 11 September 2026. The public per-value precision parameter makes the inherited polynomial-communication question explicit in bits.',formulation_reviewed_on='2026-09-11')
