import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('constant-colour-polynomial-time-colouring-of-three-colourable-graphs',
 id='TCS-6637',title='Constant-colour polynomial-time colouring of 3-colourable graphs',area='Constraint satisfaction',criterion='resources',question_type='yes_no',
 formal='Is there a fixed integer C≥3 and a uniform randomized polynomial-time algorithm that, on every finite simple undirected graph G promised to be 3-colourable, outputs a proper vertex colouring using at most C colours with probability at least 2/3?',
 definitions='The input is an explicitly given graph G=([n],E), n≥1, with no loops or parallel edges, encoded by its adjacency matrix. A proper k-colouring is a map c:[n]→[k] such that c(u)≠c(v) for every {u,v}∈E. The promise is existence of a proper 3-colouring; such a colouring is not supplied. There must be one C, one randomized Turing machine A, and fixed constants K,d such that A uses at most K(n+1)^d bit operations on every graph and every random tape. On each promised input, the probability, over independent unbiased internal random bits, of outputting a proper C-colouring is at least 2/3. Invalid outputs can be replaced by a failure symbol after checking all edges. No correctness requirement is imposed on non-3-colourable inputs, but the time bound still applies. The algorithm may colour such an input whenever it can; it need not recognize the promise. C is independent of n, degree, density and the input graph. No planarity, bounded-degree, expansion, forbidden-subgraph, random-input or supplied-decomposition promise is available. Randomization is explicitly permitted in this version of the inherited question; a deterministic algorithm would be a stronger positive result. The algorithm must colour every vertex and avoid every monochromatic edge on a successful run.',
 answer_criterion='Give such an algorithm for at least one fixed C, or prove that no such C and randomized polynomial-time algorithm exist. A growing colour bound, a partial colouring of most vertices, or a guarantee only on a restricted graph family is insufficient. NP-hardness of the 3-versus-C promise for every fixed C would establish the usual complexity-theoretic obstruction; excluding randomized algorithms from that obstruction additionally uses NP≠RP. Hardness for C=5 alone leaves all larger constants unresolved. Conditional hardness results must keep their assumptions explicit.',
 context=[
 paragraph('The input comes with a guarantee that three colours suffice, but not with the partition into three independent sets. Allowing more colours is a relaxation of the output requirements. The question asks whether some fixed amount of this relaxation makes the problem efficiently solvable on every promised input. A mechanism for choosing 100 colours would qualify just as a mechanism for choosing six colours would; the constant need not be close to three.'),
 paragraph('This promise matters. Strong inapproximability results for the chromatic number on unrestricted graphs can use instances whose chromatic number grows with the graph size. They do not automatically establish hardness when the yes-instances must have chromatic number at most three. Conversely, an algorithm for planar graphs would use a structural assumption missing here. Three-colourable graphs can be dense and can have high-degree vertices.'),
 paragraph('The problem is a basic example of promise constraint satisfaction. An edge asks its two endpoints to receive different labels. The promise says the constraints have a solution over a three-element domain; the algorithm is allowed to use a larger fixed domain. In graph-homomorphism language, an input maps to K₃ and the output must provide a map to K_C. The associated decision promise distinguishes graphs mapping to K₃ from graphs not mapping to K_C.','algebra'),
 paragraph('Barto, Bulín, Krokhin and Opršal prove NP-hardness of finding a five-colouring of a three-colourable graph, as part of a broader algebraic framework. This is far stronger than hardness of finding the promised three-colouring, yet it excludes only particular small output domains under standard complexity assumptions. It does not rule out a successful algorithm using six, 100 or any other larger fixed number of colours.','algebra'),
 paragraph('A useful elementary observation is that the neighbours of any vertex in a three-colourable graph induce a bipartite graph: the vertex’s own colour cannot appear among its neighbours. Thus one can efficiently colour a large neighbourhood using two fresh colours. When all remaining degrees are small, greedy colouring is effective. Balancing these two procedures already gives an O(√n)-colour algorithm. The challenge is to extract much more global information than this local observation provides.'),
 paragraph('Modern algorithms combine combinatorial reductions with semidefinite relaxations. The relaxation assigns vectors that mimic the separation of colours, and rounding extracts independent sets or other useful progress. Kawarabayashi, Thorup and Yoneda’s STOC 2024 work strengthens the combinatorial side and obtains Õ(n^{0.19747}) colours after combining it with the SDP approach. The suppressed factors are polylogarithmic in n.','stoc'),
 paragraph('Bansal, Huang and Lee’s February 2026 preprint improves the SDP analysis using third-level neighbourhoods and a new vector 5/2-colouring construction. Combined with the combinatorial component, its theorem gives O(n^{0.19539}) colours. A vector 5/2-colouring is a geometric relaxation, not an ordinary assignment using a fractional number of colours. The exponent improvement is real progress, while the final number of actual colours still grows with n.','sdp'),
 paragraph('Hardness evidence also goes beyond five colours under additional assumptions. Guruswami and Sandeep show that a fixed d-to-1 Label Cover conjecture implies hardness for every constant output palette. Their premise requires perfectly satisfiable yes-instances. Replacing perfect completeness by near-perfect completeness changes what the reduction guarantees, so established results about almost-satisfiable games cannot simply be substituted into this argument.','conditional'),
 paragraph('Dawar and Molnár’s full version, revised in March 2026, proves that fixed-point logic with counting cannot separate three-colourable graphs from graphs requiring more than any fixed number of colours. This is an unconditional obstruction for that logic on unordered structures, not for all polynomial-time algorithms on explicitly encoded graphs. The card sits at the intersection of approximation algorithms, algebraic reductions and limits of relaxation methods: a resolution would tell us how much a fixed expansion of the solution domain can help.','logic')],
 why='A defining promise-CSP problem: determine whether relaxing an NP-hard colouring task to any fixed larger palette permits efficient construction of a valid solution.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='The paradigmatic approximate graph-colouring question, central to promise CSPs and to the gap between algorithmic relaxations and hardness with perfect completeness.'),
 progress=[
 step('2018–2021','Barto–Bulín–Krokhin–Opršal establish the NP-hardness of five-colouring three-colourable graphs; the full work appears in JACM in 2021.','algebra'),
 step('2020-06-29','Guruswami–Sandeep derive hardness for every fixed output palette from a d-to-1 conjecture with perfect completeness.','conditional'),
 step('2024-06-01','Kawarabayashi–Thorup–Yoneda obtain Õ(n^{0.19747}) colours using improved combinatorial progress combined with SDP methods.','stoc'),
 step('2026-02-05','Bansal–Huang–Lee improve the general polynomial-time upper bound to O(n^{0.19539}) colours through a new SDP-based analysis.','sdp'),
 step('2026-03-01','The revised Dawar–Molnár full version proves an all-constant obstruction for fixed-point logic with counting; it does not establish unrestricted computational hardness.','logic')],
 references=[
 ref('stoc','Better coloring of 3-colorable graphs','Ken-ichi Kawarabayashi; Mikkel Thorup; Hirotaka Yoneda',2024,'https://arxiv.org/abs/2406.00357','v1, 1 June; STOC 2024; combinatorial progress theorem and combined Õ(n^{0.19747}) bound; inherited source'),
 ref('algebra','Algebraic Approach to Promise Constraint Satisfaction','Libor Barto; Jakub Bulín; Andrei Krokhin; Jakub Opršal',2021,'https://arxiv.org/abs/1811.00970','First posted 2 November 2018; checked v3, 21 June 2019; JACM 68(4), Article 28, July 2021; NP-hardness of (2k−1)-colouring k-colourable graphs for k≥3'),
 ref('conditional','d-To-1 Hardness of Coloring 3-Colorable Graphs with O(1) Colors','Venkatesan Guruswami; Sai Sandeep',2020,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2020.62','Published 29 June; Theorem 1; perfect completeness in the d-to-1 conjecture is essential to the stated colouring consequence'),
 ref('sdp','Improved SDP-Based Algorithm for Coloring 3-Colorable Graphs','Nikhil Bansal; Neng Huang; Euiwoong Lee',2026,'https://arxiv.org/abs/2602.05904','v1, 5 February; Theorem 1.1 gives O(n^{0.19539}); Section 1.1 describes the third-level neighbourhood and vector-colouring ideas'),
 ref('logic','Undefinability of Approximation of 2-to-2 Games','Anuj Dawar; Bálint Molnár',2026,'https://arxiv.org/abs/2504.03523','First posted 4 April 2025; checked v2, 1 March 2026; full version of CSL 2025 work; fixed-point-with-counting inseparability of K₃-colourability from failure of K_t-colourability for each fixed t')],
 status='source_open',status_note='No constant-colour algorithm or unrestricted all-constant hardness resolution found through 11 September 2026. The February 2026 primary paper retains the gap between five-colour NP-hardness and a growing O(n^{0.19539}) algorithmic bound. The March logic result is restricted to fixed-point logic with counting. This card explicitly allows bounded-error randomized algorithms.',formulation_reviewed_on='2026-09-11')
