import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('exact-two-user-gaussian-interference-capacity',
 id='TCS-6606', title='The exact capacity region of the two-user Gaussian interference channel',
 area='Coding and information theory', criterion='characterization', question_type='exact_value',
 formal='Determine the capacity region C(a,b,P₁,P₂) of the memoryless real channel Y₁,t=X₁,t+aX₂,t+Z₁,t and Y₂,t=bX₁,t+X₂,t+Z₂,t for every fixed a,b∈ℝ and finite P₁,P₂≥0, with independent messages, average power constraints, no feedback or cooperation, and vanishing average decoding error. Equivalently, determine the exact function F(a,b,P₁,P₂,λ)=sup_{(R₁,R₂)∈C}[λR₁+(1−λ)R₂] for every λ∈[0,1], under the operational definitions below.',
 definitions='For a block of n uses, messages M_i are independent and uniform on {1,…,K_{i,n}}. Transmitter i applies a deterministic encoder f_{i,n}:{1,…,K_{i,n}}→ℝⁿ depending only on its own message. Its codebook satisfies (nK_{i,n})⁻¹∑_{m=1}^{K_{i,n}}∑_{t=1}ⁿ f_{i,n}(m)_t²≤P_i. All Z_{i,t} are mutually independent N(0,1) random variables independent of the messages. Receiver i applies a measurable decoder g_{i,n}:ℝⁿ→{1,…,K_{i,n}} to its own received vector. The probability that either decoded message is wrong is averaged over both messages and all noise. A nonnegative pair (R₁,R₂) is achievable if there is a sequence of such codes with this error tending to zero and liminf_{n→∞} n⁻¹ log₂ K_{i,n}≥R_i for i=1,2. C is the closure of achievable pairs, measured in bits per real channel use. Gains, powers and both codebooks are known to all terminals. Arbitrary encoding across time and predetermined time sharing with power allocation are permitted; transmitters have no messages in common, output feedback, or communication between them. C is compact, convex and downward closed, so the nonnegative supporting function F uniquely determines it.',
 answer_criterion='Give matching achievability and converse characterizations that evaluate C, or equivalently F, for all the stated parameters. A finite-dimensional information-theoretic formula with a proof of equality would qualify; merely restating the limit over arbitrary block codes would not. A constant additive gap, numerical optimization of one coding scheme, a high-power scaling law, or only the maximum unweighted sum rate does not determine the exact requested function. No polynomial-time computation requirement is imposed on the final characterization.',
 context=[
  paragraph('Two independent conversations share the same medium: each receiver sees its desired signal, a scaled version of the other sender’s signal, and Gaussian noise. With only one sender, Shannon’s formula gives the rate ½ log₂(1+P). With two senders, improving one link can make the other harder to decode. The mathematical object is therefore a two-dimensional region of feasible rate pairs. Knowing its largest total rate does not identify all tradeoffs between the users.'),
  paragraph('Han–Kobayashi coding splits each message into a part decoded by both receivers and a private part decoded only by its intended receiver. It includes treating interference as noise and decoding interference as special strategies. Time sharing can also allocate different powers to different phases while meeting the average constraints. Shang and Chen’s monograph organizes these inner bounds and the exact results in particular regimes, including the distinction between full regions and sum-rate capacity.','survey'),
  paragraph('Strong interference is a solved benchmark. When |a|≥1 and |b|≥1, the capacity region consists of R₁≤½log₂(1+P₁), R₂≤½log₂(1+P₂), and R₁+R₂≤min{½log₂(1+P₁+a²P₂),½log₂(1+b²P₁+P₂)}. Both receivers can decode both messages. With a=b=0, the region is the rectangle given by the two individual bounds. These exact cases anchor the question but do not characterize arbitrary interference strengths.','correlated'),
  paragraph('Etkin, Tse and Wang show that a simple Han–Kobayashi strategy and new converse bounds locate the general region within a universal additive gap. Their celebrated one-bit theorem also gives high-signal-to-noise insights. A fixed gap can be extremely useful for system design while leaving the exact boundary unknown: it does not shrink merely because longer codes are allowed.','onebit'),
  paragraph('Recent work separates several different Gaussian-optimality questions. Nair and Zhao’s ISIT 2025 result identifies a substantial parameter range in the one-sided, or Z, channel where the optimized Gaussian-signaling region needs no multiplexing. This optimizes a particular achievable region; it does not prove that no other signaling distribution or coding strategy can do better.','noiseberg'),
  paragraph('Their January 2026 manuscript then shows that Gaussian distributions can be suboptimal within a single-phase Han–Kobayashi region when power control is disallowed. Its Conjecture 1 still asks whether Gaussian signaling with power control achieves full Z-channel capacity. Remark 2 reports difficulty verifying parts of an earlier Khandani proof claim. The counterexamples concern the restricted single-phase statement and do not disprove optimality after the allowed power allocation and time sharing.','local'),
  paragraph('Gohari, Nair and Zhao’s February 2026 work combines auxiliary-receiver and genie-aided converse techniques. Its Gaussian specialization captures known corner and sum-rate behavior, including associated changes in boundary slope. The theorem supplies an outer region rather than a general equality with an achievable region, so it advances the converse side without itself resolving the full target.','outer'),
  paragraph('Khandani’s preprint, revised on 7 September 2026, makes a stronger claim: Gaussian Han–Kobayashi coding attains capacity throughout weak interference, with at most two time-sharing phases. This would settle a major part of the problem if established. The current revision has not been independently validated in this review. The earlier Nair–Zhao criticism predates it and cannot automatically be applied to every revised argument. This card therefore marks the present status as uncertain and records the claim explicitly.','claim'),
  paragraph('The original short proposal cited a withdrawn paper by Huleihel and Merhav. Its claimed improvement using codewords with Gaussian memory was withdrawn in April 2018. Nair and Ng subsequently establish that temporally correlated Gaussian inputs do not enlarge the Gaussian Han–Kobayashi region once the comparison includes the appropriate scalar time sharing. The withdrawn result is retained only as a status correction, not as evidence of progress.','withdrawn')],
 why='A defining problem in network information theory: even two interfering sender–receiver pairs expose limits of our ability to characterize optimal communication. An exact solution would distinguish which forms of message splitting, interference decoding and power allocation are fundamentally necessary.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A foundational multi-user capacity frontier with a simple channel model, strong approximate results and unresolved exact tradeoffs. Recent disputed claims make the precise formulation and status record especially valuable.'),
 progress=[
  step('1981','Han–Kobayashi coding and strong-interference capacity results establish core exact benchmarks; the 2013 monograph surveys the resulting capacity and sum-capacity regimes.','survey'),
  step('2008','Etkin–Tse–Wang establish a universal constant-gap approximation to the two-user Gaussian capacity region.','onebit'),
  step('2018-04-08','Huleihel–Merhav withdraw their claimed improvement by Gaussian codeword memory; the original draft’s citation must not be treated as a valid improvement.','withdrawn'),
  step('2019','Nair–Ng prove invariance of the Gaussian Han–Kobayashi region under temporally correlated Gaussian extensions.','correlated'),
  step('2025','Nair–Zhao settle a conjecture about the structure of the Gaussian-signaling region for Z-interference channels; this is not a full capacity converse.','noiseberg'),
  step('2026-01','Nair–Zhao demonstrate failure of Gaussian optimality without power control and explicitly distinguish the still-conjectured full Gaussian region.','local'),
  step('2026-02','Gohari–Nair–Zhao present a combined auxiliary-receiver outer bound at the Information Theory and Applications Workshop.','outer'),
  step('2026-09-07','Khandani’s arXiv v12 claims the full weak-interference capacity region. The latest proof is not independently validated here; status remains qualified.','claim')],
 references=[
  ref('survey','Two-User Gaussian Interference Channels: An Information Theoretic Point of View','Xiaohu Shang; Biao Chen',2013,'https://doi.org/10.1561/0100000071','Foundations and Trends in Communications and Information Theory 10(3):179–257; publisher abstract distinguishes strong-interference regions from other sum-rate results'),
  ref('onebit','Gaussian Interference Channel Capacity to Within One Bit','Raul Etkin; David Tse; Hua Wang',2008,'https://arxiv.org/abs/cs/0702045','IEEE Transactions on Information Theory 54(12):5534–5562, DOI 10.1109/TIT.2008.2006447; first preprint February 2007; universal additive-gap result'),
  ref('correlated','Invariance of the Han–Kobayashi region with respect to temporally-correlated Gaussian inputs','Chandra Nair; David Ng',2019,'https://chandra.ie.cuhk.edu.hk/pub/papers/IC/temp-corr.pdf','Author manuscript of March 2019 IEEE Transactions on Information Theory paper; model, strong-interference benchmark and Gaussian temporal-correlation invariance'),
  ref('noiseberg','Proof of a conjecture on the Gaussian signaling region for the Gaussian Z-interference channel','Chandra Nair; Jinpei Zhao',2025,'https://chandra.ie.cuhk.edu.hk/pub/papers/IC/GZ-Noi-con.pdf','Full author manuscript of ISIT 2025 paper; Gaussian-signaling region and conditions eliminating multiplexing'),
  ref('local','On the Local Optimality of Gaussian distributions for the Han-Kobayashi Inner Bound for the Gaussian Z-interference channel','Chandra Nair; Jinpei Zhao',2026,'https://chandra.ie.cuhk.edu.hk/pub/papers/IC/Gau-Her.pdf','January 2026 manuscript listed on authors’ publications page; Conjecture 1, Remarks 1–2 and Theorem 4; counterexamples exclude power control'),
  ref('outer','A New Outer Bound for the Discrete Memoryless Two-User Interference Channel','Amin Gohari; Chandra Nair; Jinpei Zhao',2026,'https://staff.ie.cuhk.edu.hk/~cnair/pub/papers/IC/INT-OB-ITA-26.pdf','Presented at ITA, February 2026; Gaussian specialization and combined auxiliary-receiver outer region'),
  ref('claim','On the Optimality of Gaussian Code-books for Signaling over a Two-Users Weak Gaussian Interference Channel','Amir K. Khandani',2026,'https://arxiv.org/abs/2501.14941v12','v12, 7 September 2026, first posted January 2025; claimed weak-interference capacity theorem, §§7–8; latest proof not independently validated here'),
  ref('withdrawn','Codewords With Memory Improve Achievable Rate Regions of the Memoryless Gaussian Interference Channel','Wasim Huleihel; Neri Merhav',2018,'https://arxiv.org/abs/1508.05726','v2 withdrawal notice, 8 April 2018; originally posted 24 August 2015; included solely to correct the original proposal’s reference')],
 status='uncertain', status_note='Status checked on 10 September 2026. Khandani arXiv:2501.14941v12 (7 September) claims capacity throughout weak interference. Nair–Zhao’s January manuscript questions parts of an earlier version and disproves a restricted Gaussian-optimality statement without power control; that is not an adjudication of v12. This review has not established the correctness of the latest claim or a complete arbitrary-parameter characterization. Established partial results are separated from the claim. The original proposal’s arXiv:1508.05726 reference was withdrawn in 2018.', formulation_reviewed_on='2026-09-10')
