import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('decidability-positivity-integer-linear-recurrences',
 id='TCS-6565', title='Is positivity of integer linear recurrences decidable?',
 area='Semantics, logic and verification', criterion='decision', question_type='yes_no',
 formal='Does there exist a Turing machine that, on every input consisting of an integer d≥1, integer initial values u_0,…,u_{d−1}, and integer coefficients a_0,…,a_{d−1}, halts and decides whether u_n≥0 for every n≥0, where u_{n+d}=sum_{i=0}^{d−1}a_i u_{n+i}? The order d is part of the input and has no fixed upper bound.',
 definitions='All integers are given exactly in signed binary, and the coefficient and initial-value lists are explicit. The recurrence is homogeneous and its coefficients are constant in n. The requested property includes every term from u_0 onward and allows zero terms. It is enough to require a_0≠0: zero trailing coefficients can be removed after separately checking a finite prefix. No promise of distinct characteristic roots, reversibility, eventual nonnegativity, or bounded order is imposed. The recurrence supplied need not be of minimal order. Computation uses the ordinary Turing model, with no real-number or number-theoretic oracle. No polynomial-time or other specified running-time bound is required, but the machine must halt for both possible answers. A simple sequence has a minimal characteristic polynomial with no repeated complex roots.',
 answer_criterion='Give a total, correct algorithm deciding the stated all-indices nonnegativity property, or prove that this exact problem is undecidable. Detecting a negative term by enumeration only semidecides the NO instances. Deciding whether all sufficiently late terms are nonnegative, or handling every sequence within a fixed restricted subclass, does not by itself settle the question.',
 context=[
  paragraph('A recurrence is a finite description of an infinite trajectory. One can compute any requested term exactly, but checking every term asks for a finite justification covering unbounded time. This makes positivity a basic test case for the limits of algorithmic verification. The July 2026 survey still lists its general decidability among the central unresolved problems. The word positivity is conventional here: the inequality is non-strict.','survey'),
  paragraph('The connection to linear dynamics is direct. Store d consecutive values in a vector x_n. A fixed integer companion matrix M then gives x_{n+1}=Mx_n, and the first coordinate of M^n x_0 is u_n. The question is whether that coordinate ever enters the negative half-line. Even though the transition is linear and deterministic, the trajectory can combine growth, decay and oscillation through its characteristic roots.'),
  paragraph('No universal finite amount of simulation certifies the desired answer. For any chosen integer N, the sequence u_n=N−n satisfies u_{n+2}=2u_{n+1}−u_n, is nonnegative through index N, and becomes negative afterward. Of course this particular family is easy to analyze. Its role is to distinguish sampling a long prefix from proving a bound that is computed from an arbitrary input and is sufficient for that input.'),
  paragraph('Ouaknine and Worrell decide positivity for all sequences of order at most five. Their analysis combines effective estimates from Diophantine approximation with decision procedures for real algebraic conditions. At order six, decidability would already imply that certain approximation constants associated with transcendental numbers are computable. This is a precise mathematical consequence, rather than a proof that no algorithm can exist.','low'),
  paragraph('Removing repeated characteristic roots improves the known frontier: positivity is decidable for simple sequences through order nine.','simple'),
  paragraph('A separate theorem decides ultimate positivity for simple sequences of every order, in polynomial space. Ultimate positivity asks whether some finite prefix contains all negative terms. The algorithm need not provide an effective cutoff beyond which the terms are nonnegative. Without such a cutoff, the theorem cannot be turned into a positivity decider by checking the remaining prefix.','ultimate'),
  paragraph('There are larger decidable orders under a different structural promise. An integer recurrence is reversible when its extension to all negative indices also has integer values. Kenison and coauthors decide positivity through order eleven for reversible sequences, and through order seventeen when they are also simple. The extra integrality in backward time matters; these bounds do not apply to arbitrary integer recurrences of those orders.','reversible'),
  paragraph('A general solution would also decide the Skolem problem, which asks whether an integer recurrence ever equals zero. Integer recurrence sequences are effectively closed under termwise products and subtraction of a constant. Thus w_n=u_n²−1 is another such sequence, and it is nonnegative at every index exactly when u has no zero. Negating the answer to a positivity decider would decide Skolem. This reduction explains why positivity has consequences beyond sign analysis itself.','survey')],
 why='A basic infinite-time safety question for finite linear descriptions. Its resolution would establish a major decidability boundary connecting verification, discrete dynamical systems and effective number theory, and would also settle general Skolem decidability.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A longstanding foundational decision problem with an elementary input model, strong links to verification, and consequences for the separate Skolem problem; unrestricted decidability is unknown before any efficiency requirement is imposed.'),
 progress=[
  step('2014','Ouaknine and Worrell establish positivity decidability through order five, and Diophantine consequences of extending it to order six.','low'),
  step('2014','For simple sequences, positivity is decidable through order nine.','simple'),
  step('2014','Ultimate positivity is decidable for simple sequences of arbitrary order in PSPACE, and in polynomial time at each fixed order; this does not supply a general effective threshold.','ultimate'),
  step('2023-07-05','Kenison, Nieuwveld, Ouaknine and Worrell establish positivity decidability for reversible sequences through order eleven, and simple reversible sequences through order seventeen.','reversible'),
  step('2026-07-26','The new survey retains general positivity as open and gives a concrete order-ten example whose positivity is unsettled. It also presents a reduction from order-five Skolem to positivity of simple order-ten sequences.','survey')],
 references=[
  ref('survey','A Survey of the Skolem and Positivity Problems for Linear Recurrence Sequences','Piotr Bacik; Toghrul Karimov; Florian Luca; Joris Nieuwveld; Joël Ouaknine; David Purser; James Worrell',2026,'https://people.mpi-sws.org/~joel/publications/skolem_and_positivity_survey26.pdf','Manuscript dated 26 July 2026; §1, §7 Problems 44–45 and Theorem 52, §8.4 concrete positivity example'),
  ref('low','Positivity Problems for Low-Order Linear Recurrence Sequences','Joël Ouaknine; James Worrell',2014,'https://arxiv.org/abs/1307.2779','SODA 2014; preprint v2, 9 October 2013; positivity through order five and order-six Diophantine hardness'),
  ref('simple','On the Positivity Problem for Simple Linear Recurrence Sequences','Joël Ouaknine; James Worrell',2014,'https://arxiv.org/abs/1309.1550','ICALP 2014; preprint v3, 28 April 2014; simple recurrences of order at most nine'),
  ref('ultimate','Ultimate Positivity is Decidable for Simple Linear Recurrence Sequences','Joël Ouaknine; James Worrell',2014,'https://arxiv.org/abs/1309.1914','ICALP 2014; latest preprint v4, 5 April 2017; arbitrary-order simple sequences and ineffective growth bounds'),
  ref('reversible','Positivity Problems for Reversible Linear Recurrence Sequences','George Kenison; Joris Nieuwveld; Joël Ouaknine; James Worrell',2023,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2023.130','ICALP 2023, 130:1–17; reversible order eleven and simple reversible order seventeen')],
 status='source_open', status_note='Checked through 10 September 2026. The 26 July 2026 primary survey explicitly leaves general positivity undecided. Low-order, simple and reversible cases are partial results. Ultimate positivity quantifies only sufficiently late indices and is a different decision problem; its simple-sequence decider supplies no general effective prefix bound.', formulation_reviewed_on='2026-09-10')
