import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('exact-capacity-binary-independent-deletion-channel',
 id='TCS-6607',title='The exact capacity of the binary deletion channel',area='Coding and information theory',criterion='tightness',question_type='exact_value',
 formal='Determine the capacity function C(δ) of the binary independent deletion channel for every fixed δ∈[0,1], in bits per input bit, with matching achievability and converse results.',
 definitions='For input x=x₁⋯x_n∈{0,1}^n, retain each bit independently with probability 1−δ and output the retained subsequence in its original order. The receiver sees the subsequence and its length, but neither terminal sees the deletion locations; there are no erasure markers, substitutions, insertions, feedback or side channels. Both terminals know n and δ. A block code consists of deterministic maps Enc_n:[M_n]→{0,1}^n and Dec_n:⋃_{k=0}^n{0,1}^k→[M_n]. Its average error is Pr[Dec_n(Y)≠M], where M is uniform on [M_n] and Y is the channel output on Enc_n(M). A rate R is achievable if there is a sequence of such codes with liminf_{n→∞}(log₂ M_n)/n≥R and average error tending to zero. Define C(δ) as the supremum of achievable nonnegative rates. Encoding and decoding have no computational or storage restrictions. The parameter δ is fixed as n grows. Equivalently, Dobrushin’s coding theorem gives C(δ)=lim_{n→∞} C_n(δ), where C_n(δ)=(1/n) max_{P_X on {0,1}^n} I(X;Y), with base-two mutual information. These C_n are normalized per input bit; the random output length is not the normalization. The endpoints are C(0)=1 and C(1)=0.',
 answer_criterion='Give the exact capacity curve, with codes approaching the proposed rate from below and a converse showing that no higher rate has vanishing average error, for each fixed δ. The displayed multiletter limit already defines and characterizes the quantity; simply restating it is not a new determination of capacity. A capacity result at one interior parameter, a finite-block numerical interval, or a finite-order expansion near an endpoint is valuable partial progress rather than resolution of the whole curve.',
 context=[
 paragraph('A deletion removes a bit and also hides where it belonged. For example, receiving 00 after sending three bits is compatible with several input strings and deletion patterns. The output length reveals how many symbols survived, but it does not reveal their positions. This uncertainty couples the interpretation of consecutive output symbols even though the deletion decisions themselves are independent.'),
 paragraph('If the receiver were additionally given the deletion locations, the channel would become the binary erasure channel with capacity 1−δ. Revealing information cannot make decoding harder, so C(δ)≤1−δ is an immediate upper bound. The challenge is to quantify the further loss caused by missing alignment. Counting surviving bits alone therefore does not determine the answer.'),
 paragraph('The basic coding theorem is known. Optimizing mutual information over distributions on n-bit inputs and letting n grow gives the operational capacity. Moreover, C_n(δ)−log₂(n+1)/n≤C(δ)≤C_n(δ). Thus the issue is not the absence of a definition or an approximation scheme in principle. The finite optimization has 2^n possible inputs, and its rapidly growing size obstructs useful evaluation at large block lengths.','survey'),
 paragraph('The input bits should not automatically be assumed independent. Correlations can make runs of equal symbols easier to identify after deletions. Run-based constructions choose a distribution on run lengths and analyze how deleted runs disappear and neighboring surviving runs merge. Rubinstein and Con optimize such distributions to prove C(δ)>0.1221(1−δ) for every 0<δ<1. This establishes a positive constant fraction of the surviving-bit rate throughout the parameter range.','bounds'),
 paragraph('Near the noiseless endpoint, a much sharper asymptotic description is available. Kanoria and Montanari prove C(δ)=1+δ log₂ δ−A₁δ+A₂δ²+O(δ^{3−ε}) for every fixed ε>0 as δ tends to zero, with explicit constants A₁≈1.15416377 and A₂≈1.67814594. They also identify input distributions achieving this order. This determines several leading terms, but its remainder does not vanish identically at a fixed nonzero deletion probability.','small'),
 paragraph('Numerical converse bounds use finite channels in which the input and output lengths are bounded and the transition matrix is explicit. Blahut–Arimoto optimization can bound their capacities, which in turn upper-bound the unsegmented deletion channel. Pinto and Ribeiro’s 2026 implementation handles larger instances, including selected input lengths of 31, and reports C(δ)≤0.3578(1−δ) for δ≥0.64. These are computer-assisted bounds reported by the authors; this review has not rerun their large computations.','upper'),
 paragraph('The half-deletion point illustrates the remaining gap. Rubinstein and Con report an achievable rate above 0.104075, while the 2026 upper-bound table gives 0.1896. A universal lower bound proportional to 1−δ is useful for the whole curve, but it can be weaker than a pointwise run-length optimization. These different types of statements should therefore not be collapsed into one purported best numerical bound for every parameter.','bounds'),
 paragraph('An August 2026 preprint by Chen claims a further half-deletion lower bound above 0.11032415, using joint information from several output runs and a rational certificate. Its asserted slightly sharper upper number is conditional on a precision assumption about a previously published table. This card records the new lower bound as a preprint claim whose certificate has not been independently reproduced here, and does not present the conditional upper number as a separately established converse. Even if the new lower bound is confirmed, a substantial gap remains.','multirun'),
 paragraph('This is a transmission problem: the sender may select a codebook designed for the channel. Trace reconstruction instead starts with an arbitrary unknown string and observes repeated independently deleted copies of that same string. Adversarial deletion codes also use a different error model. Progress in either neighboring subject can be informative without giving the exact Shannon capacity requested here.')],
 why='The simplest channel with hidden synchronization errors still lacks an exact nontrivial capacity formula. Resolving it would establish how much information is fundamentally lost through missing alignment.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='The canonical capacity problem for synchronization errors, connecting coding, information theory, sequence reconstruction and the structure of optimal input processes.'),
 progress=[
 step('1967','Dobrushin establishes a coding theorem relating operational capacity of synchronization channels to normalized multiletter mutual information.','survey'),
 step('2013','Kanoria–Montanari determine the small-deletion expansion through the δ² term and input processes achieving that order.','small'),
 step('2023-05-11','Rubinstein–Con improve run-based achievable rates and finite-channel numerical converses; their universal lower bound is 0.1221(1−δ).','bounds'),
 step('2026-04-07','Pinto–Ribeiro improve computer-assisted upper bounds, including 0.3578(1−δ) for δ≥0.64 and a reported 0.1896 upper bound at δ=1/2.','upper'),
 step('2026-08-03','Chen posts a claimed certified lower bound C(1/2)>0.11032415. The preprint and its limits are recorded; the numerical certificate is not independently reproduced in this review.','multirun')],
 references=[
 ref('survey','An Overview of Capacity Results for Synchronization Channels','Mahdi Cheraghchi; João Ribeiro',2019,'https://arxiv.org/abs/1910.07199','v2, 8 November; Sections 2–4, coding theorem, Theorem 5 and equation (7); inherited survey reference'),
 ref('small','Optimal Coding for the Binary Deletion Channel With Small Deletion Probability','Yashodhan Kanoria; Andrea Montanari',2013,'https://ykanoria.github.io/Deletion_paper.pdf','IEEE Transactions on Information Theory 59(10), 6192–6219; Theorem 1.1 and explicit constants'),
 ref('bounds','Improved Upper and Lower Bounds on the Capacity of the Binary Deletion Channel','Ittai Rubinstein; Roni Con',2023,'https://arxiv.org/abs/2305.07156','v1, 11 May; Theorem 1.2 gives the universal lower bound; pointwise numerical table gives 0.104075 at deletion probability 1/2'),
 ref('upper','Improved Capacity Upper Bounds for the Deletion Channel using a Parallelized Blahut-Arimoto Algorithm','Martim Pinto; João Ribeiro',2026,'https://arxiv.org/abs/2604.05867','v1, 7 April; Sections 1–2 and 6, Table 3; ISIT 2026; reported computer-assisted upper bounds'),
 ref('multirun','A Certified Multi-Run Capacity Lower Bound for the Binary Deletion Channel at d = 1/2','Hungjen Chen',2026,'https://zenodo.org/records/21780666','Posted 3 August; abstract, Section IX and certificate appendices; lower-bound claim not independently reproduced here; upper reconstruction explicitly assumes printed-table precision')],
 status='source_open',status_note='The 2026 primary sources retain a gap between achievable rates and converses. The August half-deletion improvement is recorded as an unreplicated preprint claim, not an exact-capacity solution. Checked through 11 September 2026.',formulation_reviewed_on='2026-09-11')
