import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('learning-juntas-from-uniform-examples',
 id='TCS-6543',title='Learning Boolean juntas from uniform random examples',area='Learning theory',criterion='resources',question_type='yes_no',
 formal='Does there exist a uniform randomized algorithm that learns every Boolean k-junta on n variables from independent uniform random labelled examples in time polynomial in n, 2^k and 1/ε, with uniform-distribution error at most ε and success probability at least 2/3?',
 definitions='For integers 0≤k≤n, a k-junta is a function f:{0,1}ⁿ→{0,1} for which there is an unknown set S⊆{1,…,n}, |S|≤k, and an arbitrary Boolean function g on |S| bits such that f(x)=g(x restricted to S). The learner receives n,k and a positive integer t≥3, setting ε=1/t. Each requested example consists of an independently uniform x∈{0,1}ⁿ and its exact, noiseless label f(x). The learner may request further independent examples, but cannot choose inputs to be labelled or obtain correlated examples. The output is a finite Boolean circuit h on n input bits; it need not itself be a k-junta. With probability at least 2/3 over all examples and internal random bits, Pr over a fresh uniform x that h(x)≠f(x) is at most 1/t. One fixed classical probabilistic Turing machine must run, on every sample and random tape, for at most (n+2^k+t)^C steps, up to a fixed multiplicative constant, for a universal constant C independent of n,k,t,f. Reading examples, computation and writing the circuit count toward this bound. Restricting ε to reciprocal integers is equivalent, up to polynomial factors, to the usual arbitrary-accuracy requirement.',
 answer_criterion='Construct a learner satisfying these uniform guarantees for every target and parameter choice, or prove that no such learner exists. The polynomial exponent must be independent of k. An n^{O(k)} algorithm, an arbitrary f(k)·poly(n) bound with superexponential f, a learner needing membership queries, or a method for only a restricted subclass does not establish the positive answer. A lower bound confined to statistical-query algorithms does not establish the negative answer for unrestricted learners.',
 context=[
 paragraph('A junta is a model of prediction with many irrelevant features. The target may use only a small hidden subset of a very long input, but its behaviour on those relevant features is unrestricted. The goal is accurate prediction on a new uniform input. Identifying the support exactly is not required: variables that affect too little probability mass may be ignored at the requested accuracy.'),
 paragraph('The allowance of 2^k is deliberate. An arbitrary function on the relevant coordinates can have a truth table with 2^k entries, so a polynomial dependence on that quantity accommodates the complexity of the target itself. The desired improvement is in locating useful coordinates among n possibilities. For k proportional to log n, the proposed bound would give polynomial-time learning. Brute-force support enumeration has about n^k possibilities and becomes quasipolynomial in that regime.'),
 paragraph('The sample requirement already fits the target. There are at most (k+1)n^k·2^{2^k} juntas on n variables. A union bound shows that O((2^k+k log(n+1)+log(k+1)+1)/ε) independent examples suffice for every consistent hypothesis in this finite class to have error at most ε, with constant confidence. Such a hypothesis exists because the labels come from a junta. The difficulty is finding it efficiently; enumerating supports and filling their truth tables gives a direct but expensive method.'),
 paragraph('Mossel, O’Donnell and Servedio obtained the first constant-factor improvement in the exponent of this search. Their algorithm combines structural information about Boolean functions with algebraic computation and learns exactly in approximately n^{0.704k}·poly(n,2^k) time at the matrix-multiplication exponent used in the paper. This is an algorithm for arbitrary juntas from uniform random examples, so it addresses the same access model.','mos'),
 paragraph('Gregory Valiant subsequently improved the exponent to below 0.6k, with polynomial factors in n and 2^k, through algorithms for finding correlations and learning sparse parities with noise. His argument combines a noise-robust parity learner with the junta structure used in earlier work. The approximately n^{0.6k} benchmark is still stated in Servedio’s November 2025 survey. It is a major improvement over exhaustive search, but the exponent on the ambient dimension still grows with k.','valiant'),
 paragraph('Simple correlation screening is insufficient. For example, f(x)=x₁ XOR x₂ XOR x₃ is independent of each individual input bit under the uniform distribution, although all three are relevant. This does not make noiseless parity computationally hard: one can learn an unknown parity by solving linear equations over the two-element field. It explains why a limitation of low-order correlations or statistical queries cannot automatically be converted into a lower bound for every algorithm using actual examples.','mos'),
 paragraph('Membership queries change the task substantially. They allow the learner to choose an input and ask for its label, making it possible to isolate relevant variables by carefully comparing nearby points. Learning juntas in polynomial time in n and 2^k is known with this additional access. Servedio’s survey also notes that monotone juntas admit the desired bound from ordinary uniform examples; arbitrary juntas need not expose their variables through such first-order information.','survey'),
 paragraph('The phrase “learning junta distributions” describes another problem: recovering a probability mass function that depends on a small coordinate set. Beretta’s RANDOM 2025 paper relates that distribution-learning task to learning sparse parities with noise. Its introduction explicitly distinguishes noiseless Boolean junta learning and reports the existing n^{0.6k} benchmark. An equivalence for distribution learning is not an unconditional lower bound for the noiseless prediction task here.','distributions'),
 paragraph('Cornacchia, Mikulincer and Mossel show in May 2026 that a suitable neural-network training procedure can learn juntas efficiently from a lazy random walk on the hypercube, with essentially linear sample complexity in ambient dimension for each fixed k. Their loss uses differences between consecutive samples. Even if each sample has a uniform marginal distribution, consecutive samples are correlated; an independent-example oracle does not provide those labelled neighbouring points. This result therefore leaves the present question intact.','walk'),
 paragraph('The problem is a gateway to learning richer representations. A k-junta has both a decision tree and a DNF representation of size at most 2^k. Efficient uniform-example learners for those general classes would consequently learn juntas within the requested resource bound. A positive result here would solve a central obstacle, while a negative result for unrestricted learners would explain a computational limitation of feature selection even under a particularly simple input distribution.','survey')],
 why='Determine whether arbitrary dependence on a small hidden set of variables can be learned efficiently from ordinary observations, separating computational search from sample sufficiency.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A central unresolved task in computational learning theory, isolating feature selection and serving as a prerequisite for efficient learning of general decision trees and DNF formulas.'),
 progress=[
 step('2004','Mossel–O’Donnell–Servedio publish the first constant-factor improvement over the brute-force exponent for learning arbitrary juntas from uniform examples.','mos'),
 step('2012–2015','Valiant’s FOCS work and JACM version improve noiseless junta learning to roughly n^{0.6k}, using fast correlation algorithms.','valiant'),
 step('2025-07-12','Beretta’s revised RANDOM paper distinguishes junta-distribution learning from noiseless function learning and records the continuing computational gap.','distributions'),
 step('2025-11-11','Servedio’s survey explicitly retains the uniform-example junta barrier and contrasts it with efficient learning using membership queries.','survey'),
 step('2026-05-11','A new gradient-based learning result uses labelled samples from a lazy random walk; its temporal dependence is outside the independent-example model.','walk')],
 references=[
 ref('mos','Learning functions of k relevant variables; author manuscript titled Learning juntas','Elchanan Mossel; Ryan O’Donnell; Rocco A. Servedio',2004,'https://www.cs.cmu.edu/~odonnell/papers/juntas.pdf','Journal of Computer and System Sciences 69(3), 421–434; manuscript Sections 1–2 and 5 define uniform-example learning and contrast membership and statistical queries'),
 ref('valiant','Finding Correlations in Subquadratic Time, with Applications to Learning Parities and the Closest Pair Problem','Gregory Valiant',2015,'https://theory.stanford.edu/~valiant/papers/corrFull.pdf','Author full manuscript dated 29 August 2013, following FOCS 2012; JACM 62(2), Article 13, 2015, DOI 10.1145/2728167; junta-learning corollary and Appendix A'),
 ref('survey','The Probably Approximately Correct Learning Model in Computational Learning Theory','Rocco A. Servedio',2025,'https://arxiv.org/abs/2511.08791','11 November 2025; manuscript pp. 18 and 26–27: membership-query advantage, junta barrier and monotone juntas'),
 ref('distributions','New Statistical and Computational Results for Learning Junta Distributions','Lorenzo Beretta',2025,'https://arxiv.org/abs/2505.05819','v3, 12 July 2025; RANDOM 2025, Article 31; Section 1.1 separates learning Boolean functions from learning distributions'),
 ref('walk','The Benefits of Temporal Correlations: SGD Learns k-Juntas from Random Walks Efficiently','Elisabetta Cornacchia; Dan Mikulincer; Elchanan Mossel',2026,'https://arxiv.org/abs/2605.10237','11 May 2026; lazy-random-walk examples and temporal-difference loss, not independent uniform examples'),
 ref('primary','Inherited OpenReview research pointer; bibliographic identity not verified','',None,'https://openreview.net/pdf?id=wszZlP1K14','Preserved from the source proposal. Browser verification and API access prevented retrieval on 11 September 2026; no mathematical or status claim in this review relies on this pointer')],
 status='source_open',status_note='No general learner with the stated polynomial dependence, or impossibility theorem for unrestricted learners, was found through 11 September 2026. Current sources retain the uniform-example barrier. Efficient membership-query, monotone-junta and correlated-random-walk results do not meet this exact model.',formulation_reviewed_on='2026-09-11')
