import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('single-pair-shortest-path-cubic-min-plus-circuits',
 id='TCS-0481', title='Do single-pair shortest paths require cubic-size min-plus circuits?',
 area='Computational and circuit complexity', criterion='tightness', question_type='yes_no',
 formal=r'''For n >= 2, assign an arbitrary nonnegative real weight x_{ij} to every unordered edge {i,j} of the complete undirected graph on vertices 1,...,n. Define $f_n(x)=\min_{P:1\leadsto n}\sum_{e\in P}x_e$, where P ranges over simple paths. A circuit is a finite directed acyclic graph with input gates x_{ij} and optional constants 0 and infinity, binary gates min(a,b) or a+b, unrestricted reuse of gate outputs, and one designated output. Its topology depends on n but not on x, and it must compute f_n exactly for every permitted weight assignment. Let s(n) be the minimum number of binary gates in such a circuit. Is s(n)=Omega(n^3)? Equivalently, do there exist constants c>0 and n0 such that every such circuit has at least c n^3 gates for every n>=n0?''',
 definitions='A simple path visits no vertex twice. The two occurrences x_{ij} and x_{ji} denote the same input, because the graph is undirected. Infinity is an optional internal constant with min(a,infinity)=a and a+infinity=infinity; all input edge weights are finite and nonnegative. The circuit has no subtraction, tests with separate Boolean outputs, conditional routing, or input-dependent memory access. A min gate directly returns the smaller of its two numerical arguments. Input gates, wires, and reuse of an already computed value are free; binary arithmetic gates are counted. Circuits need not be generated uniformly by an efficient algorithm, so the proposed lower bound is nonuniform and imposes no depth restriction.',
 answer_criterion='Prove the quantified cubic lower bound, or refute it by proving its negation: for every c>0 and every n0 there is an n>=n0 with a correct circuit using fewer than c n^3 gates. An o(n^3)-size circuit family for all sufficiently large n would suffice for a negative answer. A lower bound for a more restricted circuit class, for all-pairs output, or for shortest paths allowing negative input weights does not establish this statement.',
 context=[
  paragraph('The numerical task is elementary to state: return one shortest-path distance. The difficulty is understanding what can be done by a fixed network of minimum and addition operations. An algorithm that chooses which vertex to process next using comparisons may use information to control its future computation. This circuit model cannot turn the identity of a minimum into arbitrary control flow. Consequently, a fast implementation of a graph-search algorithm does not automatically supply a circuit of comparable size.'),
  paragraph('A concrete upper bound comes from repeated relaxation. Initialize d_0(1)=0 and d_0(v)=infinity otherwise, and compute d_k(v)=min(d_{k-1}(v), min over u distinct from v of d_{k-1}(u)+x_{uv}). After n-1 layers, output d_{n-1}(n). Each layer uses O(n^2) gates. Nonnegative weights ensure that deleting cycles cannot increase a walk’s cost, so these layers suffice for the simple-path optimum. This gives O(n^3) gates.', 'paper'),
  paragraph('Every edge can influence the answer: choose a simple source-to-target path through that edge, make its other edges cheap, and all edges outside the path expensive. Thus dependence on the quadratic number of inputs gives a quadratic lower bound, but does not charge separately for repeated reuse of intermediate computations. The missing factor n is the substantive issue.', 'seminar'),
  paragraph('For all-pairs shortest paths, a cubic lower bound is known in the same general min-plus framework. Its many required outputs are essential to the usual argument; requesting only the distance from 1 to n leaves room for different sharing. The database formulation places the question in absorptive semirings, where adding an unnecessary detour is absorbed. This card fixes the nonnegative tropical instance so that its allowed operations and output are unambiguous.', 'supplement')],
 why='This is a basic unconditional lower-bound question for dynamic programming. A resolution would clarify whether the standard cubic relaxation computation is intrinsically necessary even for one distance when computation is restricted to minimum and addition, and would illuminate why monotone lower-bound methods struggle with paths of varying lengths.',
 importance=dict(score=89,method='editorial',assessed_on='2026-09-10',reason='A central explicit lower-bound problem for tropical circuits, linking shortest paths, pure dynamic programming, and provenance computation. The gap concerns a basic polynomial-time task rather than a specialized graph family.'),
 progress=[
  step('2015','Jukna gives the O(n^3) min-plus upper bound and explicitly asks for a cubic lower bound for the single-pair connectivity polynomial; his framework distinguishes nonnegative tropical evaluation from formal polynomial production.','paper'),
  step('2023 onward','The author’s book supplements discuss the known cubic all-pairs lower bound and the unresolved single-source and single-pair optimality questions. The all-pairs argument does not directly settle one output.','supplement'),
  step('2025','Koutris restates the question for complete undirected graphs over absorptive semirings, recording the O(n^3) upper bound and the quadratic input-dependence lower bound, with the gap open already over the tropical semiring.','seminar')],
 references=[
  ref('paper','Lower Bounds for Tropical Circuits and Dynamic Programs','Stasys Jukna',2015,'https://doi.org/10.1007/s00224-014-9574-4','Circuit definitions, shortest-path polynomials, and concluding open problem; author manuscript: https://web.vu.lt/mif/s.jukna/ftp/tropical-manuscript.pdf'),
  ref('seminar','Semirings in Databases, Automata, and Logic (Dagstuhl Seminar 25081)','Paris Koutris (problem contributor)',2025,'https://doi.org/10.4230/DagRep.15.2.89','Section 4.1: Circuit Size for Reachability'),
  ref('supplement','Supplements to Tropical Circuit Complexity','Stasys Jukna',2023,'https://web.vu.lt/mif/s.jukna/tropical/comments.html','Item 5 and linked shortest-path optimality problem; accessed 10 September 2026')],
 status='source_open',status_note='Open in the 2025 seminar and still listed in the author’s book supplements accessed on 10 September 2026. Current searches did not locate a resolution of this exact single-output, nonnegative-weight, min-plus-circuit question.',
 formulation_reviewed_on='2026-09-10')
