import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('np-not-contained-in-polynomial-size-circuits',
 id='TCS-0021',title='Does NP contain a language without polynomial-size Boolean circuits?',
 area='Computational and circuit complexity',criterion='models',question_type='yes_no',
 formal=r'''Is $\mathrm{NP}\nsubseteq\mathrm{P/poly}$? Precisely, does there exist one language L∈NP such that, for every integer k≥1, real C>0, and integer N≥1, some n≥N satisfies $\operatorname{CC}(L_n)>C(n+1)^k$, where Lₙ is the characteristic function of L on n-bit inputs and CC is minimum Boolean circuit size?''',
 definitions=r'''A Boolean circuit is a finite directed acyclic graph with n input bits, binary AND and OR gates, unary NOT gates, constants 0 and 1, and one output bit. There are no depth or fan-out restrictions; a gate output may be reused arbitrarily. Size counts AND, OR, and NOT gates. Lₙ must be computed exactly on every n-bit string. A family {Cₙ} is nonuniform: no algorithm is required to construct Cₙ from n, and the circuit may depend arbitrarily on the input length, but not on the particular input of that length. P/poly consists of languages having circuits of size at most C(n+1)^k for some fixed constants C,k and every n. NP consists of languages L with a deterministic polynomial-time verifier V and polynomial p such that x∈L iff some y of length at most p(|x|) satisfies V(x,y)=1. The existentially chosen language L is the same for every exponent k. The lower bound need only hold at arbitrarily large lengths for each k; an eventual bound at every sufficiently large length would be stronger. Equivalently, ask whether the NP-complete language SAT has no polynomial-size circuit family under an ordinary explicit binary formula encoding.''',
 answer_criterion='Prove NP is not contained in P/poly, or prove the containment. A positive separation requires one NP language escaping every polynomial circuit-size bound. Proving that, for each exponent k, a possibly different language requires more than n^k gates does not suffice. Containment can be established by giving polynomial-size circuits for SAT at every input length; an efficient uniform circuit generator is not required.',
 context=[
  paragraph('A polynomial-time algorithm yields a polynomial-size circuit for each input length by unrolling its computation. The converse fails because a different circuit may be selected for every length without any effective way to generate those circuits. The conjecture asks whether NP retains hard problems even after granting this substantial extra freedom. A separation would imply P≠NP, while P≠NP alone does not establish the circuit claim.','book'),
  paragraph('Counting arguments show that most truth tables need exponentially many gates. They do not produce the required language in NP: an arbitrary sequence of hard truth tables need not have efficiently verifiable membership certificates. This is the central explicitness difficulty. It is also why enumerating hard functions at a few fixed lengths cannot satisfy the quantified statement on this card.','book'),
  paragraph('The Karp–Lipton theorem gives a consequence of the opposite outcome: if NP has polynomial-size circuits, the polynomial hierarchy collapses to its second level. This is evidence linking nonuniform algorithms to uniform complexity, but it is not a contradiction because the hierarchy is not known to be infinite.','book'),
  paragraph('The natural-proofs theorem identifies a conditional obstacle to a broad family of circuit lower-bound techniques. Under sufficiently strong pseudorandom-function assumptions, a property of truth tables that is both efficiently recognizable and sufficiently common cannot distinguish all hard functions from polynomial-size circuits in the required way. The theorem constrains a method, not every possible proof.','natural'),
  paragraph('Williams’ separation for nondeterministic exponential time and constant-depth modular circuits demonstrates that faster satisfiability algorithms can yield nonuniform lower bounds. It leaves two restrictions relative to this target: the hard language may lie above NP, and the competing circuits have constant depth.','acc')],
 why='This is the main unrestricted Boolean circuit lower-bound conjecture for efficiently verifiable problems. Circuits remove issues of uniform program construction and expose a finite combinatorial object, making the problem a central route toward unconditional computational lower bounds. It connects complexity classes, pseudorandomness, learning, and limitations of proof techniques.',
 importance=dict(score=98,method='editorial',assessed_on='2026-09-10',reason='A foundational strengthening of P≠NP and the central target of general Boolean circuit lower bounds. Its consequences and methods reach across complexity, derandomization, learning, and cryptography.'),
 progress=[
  step('1980s','The Karp–Lipton theorem shows NP⊆P/poly implies PH=Σ₂^P. Wigderson’s Theorem 5.5 records this consequence next to Conjecture 5.4.','book'),
  step('1997','Razborov and Rudich prove the natural-proofs barrier under a strong cryptographic hardness assumption. This does not establish the desired circuit lower bound or its impossibility.','natural'),
  step('2011 conference / 2014 journal','Williams proves that NEXP lacks polynomial-size nonuniform ACC circuits. ACC has fixed depth and allows modular counting gates; the result does not handle unrestricted circuits for an NP language.','acc'),
  step('2026-03','Chen, Tal, and Wang obtain n^(2.5−ε) gate lower bounds against depth-two linear-threshold circuits for a function in E^NP, for every ε>0. Their introduction identifies NP⊄P/poly as the flagship open target.','recent')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2018,'https://www.math.ias.edu/files/mathandcomp.pdf','27 March 2018 draft, Section 5.2, Definition 5.2, Conjecture 5.4, Theorem 5.5, and Section 5.2.1; printed pages 64–65'),
  ref('natural','Natural Proofs','Alexander A. Razborov; Steven Rudich',1997,'https://doi.org/10.1006/jcss.1997.1494','Journal of Computer and System Sciences 55(1), 24–35; conditional obstruction to natural general-circuit lower bounds'),
  ref('acc','Nonuniform ACC Circuit Lower Bounds','Ryan Williams',2014,'https://people.csail.mit.edu/rrw/acc-lbs-journal-final.pdf','JACM 61(1), Article 2; DOI 10.1145/2559903; preliminary CCC 2011 version'),
  ref('recent','Super-quadratic Lower Bounds for Depth-2 Linear Threshold Circuits','Lijie Chen; Avishay Tal; Yichuan Wang',2026,'https://eccc.weizmann.ac.il/report/2026/039/','ECCC TR26-039, 14–15 March 2026; abstract and introduction. Hard function is in E^NP, and the circuit class is THR∘THR.')],
 status='source_open',status_note='Explicitly posed by Wigderson and identified as the flagship unresolved circuit target in the March 2026 primary paper. Checked through 10 September 2026; no unconditional resolution of NP versus general polynomial-size circuits located. Restricted-depth or conditional lower bounds do not settle this card.',formulation_reviewed_on='2026-09-10')
