import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('classical-polynomial-time-polynomial-factor-euclidean-svp',
 id='TCS-6667',title='Polynomial-time, polynomial-factor approximation of Euclidean SVP',area='Lattices and computational number theory',criterion='resources',question_type='yes_no',
 formal='Does there exist a constant C>0 and a classical randomized algorithm A running in polynomial time such that, for every rank-n rational lattice basis B, A outputs a nonzero integer vector z satisfying ∥Bz∥₂≤nᶜλ₁(L(B)) with probability at least 2/3?',
 definitions='The input is an explicitly encoded matrix B∈ℚ^{d×n}, d≥n≥1, with linearly independent columns. Each rational entry is given by a binary numerator and positive binary denominator. L(B)={Bz:z∈ℤⁿ} is the lattice, and λ₁(L)=min{∥v∥₂:0≠v∈L} is the length of a shortest nonzero vector in the Euclidean norm ∥v∥₂=(Σᵢvᵢ²)^{1/2}. Rank n, rather than ambient dimension d or coefficient magnitude, controls the approximation factor. There must be one polynomial P such that every run halts in at most P(L) bit operations, where L is the input’s total bit length; output bits and random bits are counted. Randomness consists of independent fair bits. Require z to be a nonzero integer vector on every run, while the length guarantee may fail with probability at most 1/3. Both P and C are independent of all input parameters. There are no distributional, uniqueness, conditioning, ideal-lattice or basis-quality promises. A deterministic algorithm would also qualify. The one-dimensional case is exactly solvable by a basis vector.',
 answer_criterion='Give one finite constant C and an algorithm meeting the stated guarantees for all bases, or prove that no such algorithm exists for any constant C. Any conditional lower bound must state its hypothesis. A hardness theorem for approximation nᵟ at one particular small δ>0 does not rule out an algorithm with a larger exponent C. Returning an estimate of λ₁ or deciding a gap promise without producing a lattice vector is a different task unless accompanied by a reduction that preserves a polynomial approximation factor.',
 context=[
  paragraph('A lattice basis can disguise very short vectors as cancellations between long columns. For example, b₁=(N,1) and b₂=(N+1,1) both have length about N, while b₂−b₁=(1,0) has length one. Simply selecting the shortest input column therefore has no dimension-only approximation guarantee. Basis reduction changes the representation without changing the lattice, aiming to expose short integer combinations.'),
  paragraph('The LLL algorithm solves a major version of this task in polynomial bit time: with the standard reduction parameter, it finds a nonzero vector within 2^{(n−1)/2} of the shortest length. The factor is exponential in rank, even though the running time is polynomial. This was enough to transform computational number theory and enable applications such as factoring rational polynomials, but it leaves the much stronger approximation asked for here open.','lll'),
  paragraph('Block reduction improves the quality by solving shorter-vector problems in projected sublattices of limited rank. The best general polynomial-time guarantees summarized by Bennett have approximation factor 2^{O(n log log n/log n)}. That is smaller than the basic LLL factor but still grows faster than every fixed power of n. Larger blocks improve approximation at the cost of more expensive local computations; a polynomial number of calls to an expensive subroutine does not imply polynomial total time.','survey'),
  paragraph('Known hardness results approach, but do not reach, the polynomial-factor regime. Haviv and Regev show that approximation within 2^{(log n)^{1−δ}}, for fixed δ>0, cannot be polynomial time unless NP has randomized quasipolynomial-time algorithms. Stronger assumptions give further nearly polynomial factors. Every such factor must be read with its quantifiers: hardness for a smaller approximation factor concerns a more demanding task and does not eliminate the possibility of a much looser nᶜ approximation.','hardness'),
  paragraph('Decision and search also need care. GapSVP distinguishes λ₁≤r from λ₁>γr, with no requirement on intermediate inputs. Aharonov and Regev place the decision problem with γ=O(√n) in NP∩coNP, using short certificates on both sides. This is strong evidence about its structural complexity and a barrier to certain NP-hardness proofs. It is not a polynomial-time search algorithm that finds a short lattice vector.','certificates'),
  paragraph('The intermediate approximation regime is central to lattice cryptography. Worst-case to average-case reductions relate particular polynomial-factor lattice problems to problems such as SIS and LWE at specified parameters. These implications have a direction: an efficient worst-case algorithm would invalidate the corresponding hardness premise, but the existence of a security reduction alone would not prove that every deployed cryptosystem is broken. The exponent, problem variant and cryptographic parameters all matter.','survey'),
  paragraph('Sato and Yasuda’s May 2026 PotBKZ algorithm guarantees termination after a polynomial number of calls to its potential-reducing enumeration routine. This improves control of the reduction process, including a self-dual variant. It does not give a polynomial-time polynomial-factor approximation for arbitrary rank, because the cost and quality of the block enumeration must still be accounted for.','potbkz'),
  paragraph('Hirahara and Ogitsuka’s August 2026 preprint improves the randomness properties of lattice hardness reductions. Under a stated exponential lower-bound assumption for nondeterministic circuits, they obtain deterministic NP-hardness reductions for every constant Euclidean approximation factor. Both qualifications matter: the derandomization is conditional, and the approximation factors are constants, rather than all polynomial factors. Their separate parameterized hardness results also use a different resource measure.','onesided'),
  paragraph('The question isolates the large gap between useful reduction algorithms and the approximation range used in fundamental hardness assumptions. Even an algorithm with a very large fixed exponent C would be a major qualitative advance; the target does not demand exact SVP or a small approximation constant.')],
 why='A central algorithmic gap in lattice complexity: known polynomial-time methods give superpolynomial approximation factors, while key computational and cryptographic questions lie in the polynomial-factor regime.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A fundamental worst-case algorithm question at the heart of lattice reduction, with a wide gap between current methods and the target and connections to cryptographic hardness.'),
 progress=[
  step('1982','LLL gives polynomial-time lattice reduction with an exponential-in-rank approximation guarantee.','lll'),
  step('2004–2005','Aharonov–Regev place O(√n)-GapSVP in NP∩coNP; the theorem concerns gap decision certificates.','certificates'),
  step('2007–2012','Haviv–Regev strengthen approximation hardness to nearly polynomial factors under randomized complexity assumptions.','hardness'),
  step('2023','Bennett’s survey documents the polynomial-time upper factor 2^{O(n log log n/log n)} and the unresolved polynomial-factor region.','survey'),
  step('2026-05-11','Sato–Yasuda prove a polynomial bound on PotBKZ’s enumeration calls, without making unrestricted block enumeration polynomial time.','potbkz'),
  step('2026-08-14','Hirahara–Ogitsuka obtain one-sided-error reductions and conditional deterministic constant-factor Euclidean NP-hardness.','onesided')],
 references=[
  ref('lll','Factoring Polynomials with Rational Coefficients','Arjen K. Lenstra; Hendrik W. Lenstra Jr.; László Lovász',1982,'https://www.math.ucdavis.edu/~deloera/MISC/LA-BIBLIO/trunk/Lovasz/LovaszLenstraLenstrafactor.pdf','Mathematische Annalen 261(4):515–534; lattice reduction and the short-vector guarantee'),
  ref('survey','The Complexity of the Shortest Vector Problem','Huck Bennett',2023,'https://www.cs.umd.edu/~gasarch/open/svp-color.pdf','24 January author version; Figures 1 and 3, §2.1, and §§4.1–4.2; ECCC TR22-170 revision 1 accepted 31 January 2023'),
  ref('hardness','Tensor-based Hardness of the Shortest Vector Problem to within Almost Polynomial Factors','Ishay Haviv; Oded Regev',2012,'https://theoryofcomputing.org/articles/v008a023/v008a023.pdf','Theory of Computing 8(23):513–531; Theorem 1.1, including the randomized complexity assumptions; STOC 2007 precursor'),
  ref('certificates','Lattice Problems in NP ∩ coNP','Dorit Aharonov; Oded Regev',2005,'https://cims.nyu.edu/~regev/papers/cvpconp.pdf','Journal of the ACM 52(5):749–765; FOCS 2004 precursor; O(√n) gap-decision certificates, not a general short-vector search algorithm'),
  ref('potbkz','A new BKZ-type reduction with provable termination and development of its self-dual variant','Arata Sato; Masaya Yasuda',2026,'https://link.springer.com/article/10.1007/s13160-026-00799-6','Japan Journal of Industrial and Applied Mathematics 43, Article 42; published 11 May; polynomial number of calls to PotENUM'),
  ref('onesided','One-Sided-Error Parameterized Reductions for the Minimum Distance and Shortest Vector Problems','Shuichi Hirahara; Kazuki Ogitsuka',2026,'https://arxiv.org/abs/2608.14305','v1, 14 August; full version of RANDOM 2026; Theorem 1.5 assumes E is not contained in i.o.-NSIZE(2^{εn}) for some ε>0 and yields constant-factor deterministic NP-hardness')],
 status='source_open',status_note='Checked through 10 September 2026. No classical polynomial-time algorithm with any fixed polynomial approximation factor was found for unrestricted Euclidean search SVP. Recent termination guarantees count costly subroutine calls, and the August conditional hardness theorem concerns constant factors. The card explicitly allows bounded-error classical randomization.',formulation_reviewed_on='2026-09-10')
