import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('polylogarithmic-worst-case-fully-dynamic-minimum-spanning-forest',
 id='TCS-6626',title='Polylogarithmic worst-case updates for exact dynamic minimum spanning forests',area='Dynamic graph algorithms',criterion='resources',question_type='yes_no',
 formal='Can an exact minimum spanning forest of a fully dynamic n-vertex graph with polynomially bounded integer weights be maintained with polylogarithmic worst-case time per edge update, polynomial preprocessing and space, and high-probability correctness against an oblivious adversary?',
 definitions='The graph is simple and undirected on the fixed labelled vertex set [n], n≥2, and starts empty. An update inserts one currently absent edge with integer weight in {1,…,n⁴}, or deletes one present edge. Edge weights remain fixed until deletion. A minimum spanning forest consists of one minimum-total-weight spanning tree for each connected component. Break equal-weight ties by the fixed lexicographic order (weight, smaller endpoint, larger endpoint), so the target is the unique forest selected by Kruskal’s algorithm in that order. After each update the data structure must report the edges removed from and added to the maintained forest; on a correct execution at most one edge of each kind changes. These reports specify the entire current forest starting from the empty one. Use a uniform randomized classical word RAM with Θ(log n)-bit words, standard word operations and random-word generation; all input processing and memory accesses count. For every fixed pair of integers a,b≥1, the target permits a separately tuned uniform data structure and constants K,C≥1 whose preprocessing and space are n^{O(1)}, and for which every update takes at most K(log₂(n+2))^C steps on every execution. For every valid update sequence of length at most n^a fixed before its random choices, all reported forests must be correct simultaneously with probability at least 1−n^{−b}. Constants and polynomial exponents may depend on a,b, but not on n or the sequence. This is a Monte Carlo worst-case-time formulation; an always-correct deterministic solution would also suffice. The integer range n⁴ is an explicit specialization, and weights occupy O(1) words. There is no advance access to future updates.',
 answer_criterion='Construct data structures satisfying the stated bounds for every fixed a,b, or prove the proposition false. Amortized polylogarithmic updates, merely subpolynomial worst-case updates, or maintaining an approximate minimum forest are insufficient. A lower bound against deterministic algorithms alone does not rule out the allowed randomization. A data structure that only stores the graph and postpones finding the forest to an expensive query does not meet the required per-update reporting guarantee.',
 context=[
 paragraph('One edge update can force a global search even though the optimal forest changes by very little. Deleting a tree edge splits one tree into two parts; the algorithm must find the cheapest surviving edge crossing that cut, if one exists. There may be many candidate edges dispersed throughout the graph. Inserting an edge is easier to understand: it creates a cycle if its endpoints are already connected, and it replaces the largest edge on that cycle when this improves the ordered forest.'),
 paragraph('The reporting convention makes the maintained answer observable without requiring the algorithm to print all n−1 tree edges after every update. With fixed tie-breaking, the forest changes by at most one insertion and one deletion. Holm, Rotenberg and Wulff-Nilsen use this explicit update model in their formulation. The difficulty is finding those few changes quickly, rather than paying for a large unavoidable output.','amortized'),
 paragraph('Polylogarithmic amortized maintenance is already established. Holm, de Lichtenberg and Thorup give a deterministic O(log⁴ n) amortized update bound. Amortization allows occasional expensive operations as long as their cost can be charged across a sequence. The present target limits the time of each individual update, so long rebuilds and large replacement-edge searches must be spread out while keeping the current answer ready.','hdlt'),
 paragraph('Later amortized refinements improve the logarithmic factors. The 2015 work of Holm, Rotenberg and Wulff-Nilsen obtains O(log⁴ n/log log n) using the randomized priority-queue option in its table of RAM implementations. Its deterministic implementation has a different bound. None of these variants supplies the worst-case per-update guarantee requested here.','amortized'),
 paragraph('The worst-case frontier crossed a major threshold in 2017. Nanongkai, Saranurak and Wulff-Nilsen obtain Las Vegas maintenance with subpolynomial worst-case update time with high probability. Their approach combines expander maintenance with a reduction to graphs having few edges beyond a forest. Chuzhoy and coauthors subsequently derandomize the needed expander-decomposition component and obtain deterministic n^{o(1)} worst-case updates.','random'),
 paragraph('Subpolynomial is still weaker than polylogarithmic. For example, exp(√log n) grows more slowly than every fixed positive power of n but faster than every fixed power of log n. Thus a statement of n^{o(1)} update time does not automatically meet this card’s bound. The 2020 deterministic theorem resolves an earlier polynomial-exponent barrier while leaving the sharper target.','deterministic'),
 paragraph('The SODA 2026 connectivity result of Meierhans and Probst Gutenberg achieves expected polylogarithmic worst-case updates for maintaining an unweighted spanning forest, and also discusses conversion to high-probability time bounds. It extends to a (1+ε)-approximate weighted minimum spanning forest with overhead proportional to log(U)/ε for weights in [1,U]. The approximation parameter is essential; this is not an exact weighted minimum-forest theorem.','connectivity'),
 paragraph('For integer weights, one could force an approximation guarantee to become exact by taking ε smaller than the reciprocal of a polynomial upper bound on the optimum cost. But the displayed 1/ε overhead would then become polynomial in n. The straightforward reduction therefore does not preserve polylogarithmic update time for exact optimization. It identifies a concrete gap between maintaining connectivity at a few approximate weight thresholds and identifying the exact cheapest replacement edge.','connectivity'),
 paragraph('The oblivious-adversary convention means the update sequence is chosen without reacting to the data structure’s random outcomes. A solution robust to an adaptive adversary would be stronger. Even this stated convention would remove a longstanding delay barrier for a central dynamic optimization primitive, with uses in algorithms that repeatedly maintain weighted spanning structures.')],
 why='A basic dynamic optimization problem with very small changes to its answer but potentially expensive global replacement searches. It tests whether amortized efficiency can be made reliable for every update.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='One of the main unresolved worst-case update barriers in dynamic graph algorithms, closely connecting connectivity, weighted optimization, sparsification and expander maintenance.'),
 progress=[
 step('1998–2001','Holm–de Lichtenberg–Thorup establish deterministic O(log⁴ n) amortized minimum-spanning-forest updates.','hdlt'),
 step('2014–2015','Holm–Rotenberg–Wulff-Nilsen improve amortized bounds; the O(log⁴ n/log log n) option uses randomized priority queues in the stated RAM model.','amortized'),
 step('2017','Nanongkai–Saranurak–Wulff-Nilsen give Las Vegas subpolynomial worst-case update time with high probability.','random'),
 step('2020','Chuzhoy and coauthors obtain deterministic n^{o(1)} worst-case updates via deterministic expander decomposition.','deterministic'),
 step('2026-01-07','Meierhans–Probst Gutenberg’s SODA paper gives expected polylogarithmic worst-case connectivity maintenance; its weighted extension is (1+ε)-approximate with inverse-ε overhead.','connectivity')],
 references=[
 ref('hdlt','Poly-Logarithmic Deterministic Fully-Dynamic Algorithms for Connectivity, Minimum Spanning Tree, 2-Edge, and Biconnectivity','Jacob Holm; Kristian de Lichtenberg; Mikkel Thorup',2001,'https://u.cs.biu.ac.il/~rodittl/p723-holm.pdf','Journal of the ACM 48(4), 723–760; STOC 1998 precursor; deterministic amortized minimum-spanning-tree bound'),
 ref('amortized','Faster Fully-Dynamic Minimum Spanning Forest','Jacob Holm; Eva Rotenberg; Christian Wulff-Nilsen',2015,'https://arxiv.org/abs/1407.6832','Preprint 25 July 2014; ESA 2015, 742–753; introduction specifies reporting forest-edge changes; Table 1 separates deterministic and randomized implementations'),
 ref('random','Dynamic Minimum Spanning Forest with Subpolynomial Worst-case Update Time','Danupon Nanongkai; Thatchaphol Saranurak; Christian Wulff-Nilsen',2017,'https://arxiv.org/abs/1708.03962','FOCS 2017; Las Vegas correctness, subpolynomial worst-case time with high probability'),
 ref('deterministic','A Deterministic Algorithm for Balanced Cut with Applications to Dynamic Connectivity, Flows, and Beyond','Julia Chuzhoy; Yu Gao; Jason Li; Danupon Nanongkai; Richard Peng; Thatchaphol Saranurak',2020,'https://arxiv.org/abs/1910.08025','v2, 3 May; FOCS 2020; Theorem 1.5 and Section 6.2 give deterministic dynamic MSF with n^{o(1)} worst-case updates'),
 ref('connectivity','Dynamic Connectivity with Expected Polylogarithmic Worst-Case Update Time','Simon Meierhans; Maximilian Probst Gutenberg',2026,'https://arxiv.org/abs/2510.08297','SODA 2026, 6184–6198; first preprint 9 October 2025; Theorem 1.1, introductory time-conversion remark, and Corollary 3.17 on approximate weighted MSF'),
 ref('legacy_correction','Deterministic Rounding of Dynamic Fractional Matchings','Sayan Bhattacharya; Peter Kiss',2021,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2021.27','Provenance correction: the inherited citation is a dynamic matching paper, not a source of an exact dynamic MSF theorem; retained to make the correction traceable')],
 status='source_open',status_note='Current sources distinguish exact subpolynomial worst-case MSF maintenance from polylogarithmic amortized maintenance and the 2026 approximate weighted extension of connectivity algorithms. The inherited ICALP 2021 link was a mismatched matching citation and is identified as such. Checked through 11 September 2026.',formulation_reviewed_on='2026-09-11')
