import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('deterministic-linear-time-comparison-minimum-spanning-tree',
 id='TCS-6536',title='Deterministic linear-time minimum spanning tree',area='Algorithms & data structures',criterion='tightness',question_type='yes_no',
 formal='Is there one deterministic comparison-based algorithm that, on every connected simple undirected graph with n vertices, m edges and arbitrary real edge weights, outputs a minimum spanning tree in O(m+n) worst-case time in the comparison RAM model below?',
 definitions='The graph is explicitly supplied as vertex and edge records, with vertices numbered 1,…,n and edges given distinct identifiers. An edge record contains its two endpoints and a weight key representing an arbitrary real number. A spanning tree is a set T of n−1 edges connecting all vertices without a cycle; it is minimum when Σ_{e∈T}w(e) is smallest among all spanning trees. For n=1 the output is empty. Equal and negative weights are permitted, and any minimum tree is acceptable. Weight keys may be copied and compared, but their bit representations cannot be inspected, and arithmetic on their numerical values is unavailable. Each comparison has unit cost. Nonweight data, addresses and indices use O(log(m+n+2))-bit words on a random-access machine, with unit-cost reads, writes, comparisons, standard word arithmetic, bitwise Boolean operations and shifts; arithmetic is restricted to these words. All ordinary operations count in the running time, not just weight comparisons. The algorithm has a fixed finite description and no input-length-dependent advice or free precomputed tables. Any tables it constructs, as well as writing the output, are charged to its time. The hidden linear-time constant must be independent of graph topology, n,m and the weights. This fixes a conventional uniform sequential comparison model.',
 answer_criterion='Give such an algorithm with a proof of correctness and a worst-case C(m+n) bound for a universal constant C, or prove that no deterministic algorithm in this model has a linear worst-case bound. A randomized expected-time algorithm, a result only for selected graph classes, a bound with an unbounded inverse-Ackermann factor, or a linear number of comparisons with superlinear computational overhead is not a yes answer.',
 context=[
 paragraph('A minimum spanning tree connects a graph as cheaply as possible without redundant cycles. It is among the basic examples where a local greedy rule produces a global optimum, and it appears in network design and clustering. The optimization objective is well understood; the unsettled issue is how much computation is fundamentally needed to identify the right n−1 edges when the input already contains m edge records.'),
 paragraph('Sorting every edge is sufficient for Kruskal’s algorithm, but sorting is a stronger task than the required output. On a graph that is itself a tree, every edge belongs to the answer regardless of their relative weights. On a triangle, only the identity of a largest-weight edge is needed: discard it. Thus the familiar comparison lower bound for sorting all keys does not automatically become a lower bound for finding an MST. A faster algorithm must exploit the graph’s structure to avoid unnecessary ordering information.'),
 paragraph('The cut and cycle rules make this possible. A lightest edge across a cut can be selected safely, and a strictly heaviest edge on a cycle can be discarded. Equal weights can be handled consistently by comparing pairs consisting of the weight and the edge identifier. These rules avoid numerical arithmetic on weights, so the problem is meaningful for arbitrary real keys even though the objective is expressed as a sum.','random'),
 paragraph('Karger, Klein and Tarjan combine random sampling with linear-time MST verification to obtain a Las Vegas algorithm with expected O(m+n) running time. It always returns a correct tree; randomness controls the work spent on recursive filtering. The target here is a deterministic guarantee for every input, so fixing an arbitrary random seed does not inherit the expected-time theorem.','random'),
 paragraph('Chazelle’s deterministic algorithm achieves O(mα(m,n)) time, where α is a slowly growing inverse-Ackermann function. Its soft-heap machinery deliberately permits a controlled set of key increases inside an auxiliary data structure while the surrounding algorithm preserves the exact MST answer. The extra factor is tiny for practical input sizes, yet unbounded asymptotically. Removing it asks for an exact structural understanding of the problem’s complexity, not merely an implementation improvement.','chazelle'),
 paragraph('Pettie and Ramachandran establish a different kind of optimality: total algorithmic running time can match, within a constant factor, the optimal worst-case number of edge comparisons for MST. Their algorithm is uniform; it constructs the small optimal decision trees it needs within the time analysis. But the asymptotic size of that optimum is itself unknown. Consequently a proof that linear-size comparison decision trees always suffice would settle the algorithmic question through their theorem.','optimal'),
 paragraph('The graph family also matters. Eisenstat and coauthors show that it is enough to solve graphs with at most 3n/2 edges, and separately relate the general problem to graphs with any fixed lower bound on girth, the length of a shortest cycle. Their available high-girth algorithm requires a lower bound that grows with n. That difference between a fixed girth threshold and a slowly growing threshold leaves the general deterministic question open.','girth'),
 paragraph('Changing the access model can remove the obstacle. Fredman and Willard give a deterministic linear-time algorithm using integer-word operations on the weights. That theorem can exploit their binary representation, which the real-key comparison model deliberately withholds. Similarly, an algorithm that is fast for a random graph topology has an average-instance guarantee, even if the algorithm itself is deterministic; it does not bound the work on every graph.','integer'),
 paragraph('The remaining challenge can therefore be stated without ambiguity: retain exactness, arbitrary real-key weights and all graph topologies, and make every part of the computation linear without random choices. A negative answer would be equally significant, by establishing an intrinsic cost for deterministic comparison-based optimization that expected-time random sampling avoids.')],
 why='A central unresolved boundary between deterministic and randomized algorithms for a classical graph optimization problem, and a rare case where a provably optimal algorithm exists before its exact asymptotic complexity is understood.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A foundational graph-algorithm question about the necessity of randomness and the relationship between comparison complexity and actual computation.'),
 progress=[
 step('1994','Fredman–Willard obtain deterministic linear time in a stronger integer-word model.','integer'),
 step('1995','Karger–Klein–Tarjan obtain randomized linear time for arbitrary comparison weights.','random'),
 step('2000','Chazelle achieves deterministic O(mα(m,n)) comparison-based time.','chazelle'),
 step('2002','Pettie–Ramachandran match the optimal decision-tree complexity with a uniform deterministic algorithm, without determining that complexity.','optimal'),
 step('2008','Pettie–Ramachandran develop alternative randomized MST algorithms using far fewer random bits; complete deterministic linear time remains unresolved.','bits')],
 references=[
 ref('random','A Randomized Linear-Time Algorithm to Find Minimum Spanning Trees','David R. Karger; Philip N. Klein; Robert E. Tarjan',1995,'https://people.csail.mit.edu/karger/Papers/mst.pdf','Journal of the ACM 42, 321–328; author manuscript dated 7 July 1994; comparison RAM, sampling and verification'),
 ref('chazelle','A Minimum Spanning Tree Algorithm with Inverse-Ackermann Type Complexity','Bernard Chazelle',2000,'https://www.cs.princeton.edu/~chazelle/pubs/mst.pdf','Journal of the ACM 47(6), 1028–1047; deterministic pointer-machine comparison algorithm'),
 ref('optimal','An Optimal Minimum Spanning Tree Algorithm','Seth Pettie; Vijaya Ramachandran',2002,'https://www.cs.princeton.edu/courses/archive/fall05/cos528/handouts/An%20Optimal%20Minimum.pdf','Journal of the ACM 49(1), 16–34; §§1,4–6 distinguish uniform optimality from a known linear bound'),
 ref('integer','Trans-dichotomous algorithms for minimum spanning trees and shortest paths','Michael L. Fredman; Dan E. Willard',1994,'https://www.sciencedirect.com/science/article/pii/S0022000005800649','Journal of Computer and System Sciences 48(3), 533–551; integer representation and word operations'),
 ref('girth','Minimum Spanning Tree in Deterministic Linear Time For Graphs of High Girth','Sarah Eisenstat; Dana Moshkovitz; Robert E. Tarjan; Siyao Xu',None,'https://people.csail.mit.edu/dmoshkov/papers/mst/high-girth.pdf','Undated author-hosted manuscript; Corollary 1, Lemma 1 and Theorem 1. Moshkovitz’s publication page notes that a prior paper implicitly had the high-girth algorithm'),
 ref('bits','Randomized minimum spanning tree algorithms using exponentially fewer random bits','Seth Pettie; Vijaya Ramachandran',2008,'https://web.eecs.umich.edu/~pettie/papers/random-mst.pdf','ACM Transactions on Algorithms 4(1), Article 5; randomized approaches and comparison of soft-heap and sampling methods')],
 status='source_open',status_note='The deterministic linear-time comparison problem remains open in the primary-author material checked through 11 September 2026. Integer-word algorithms, high-girth results and the optimal-decision-tree theorem do not settle this formulation.',formulation_reviewed_on='2026-09-11')
