import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('algebraic-clique-leading-exponent',
 id='TCS-6597',title='The algebraic k-Clique Hypothesis: the leading exponent',area='Fine-grained complexity',criterion='tightness',question_type='yes_no',
 formal='Let τ(k) be the infimum of worst-case time exponents of randomized algorithms deciding k-Clique, as specified below, and let ω be the arithmetic matrix-multiplication exponent over C. Is liminf_{k→∞} τ(k)/k=ω/3?',
 definitions='For each fixed integer k≥3, the input is the adjacency matrix of a simple undirected graph on n≥k labeled vertices; accept iff some k distinct vertices are pairwise adjacent. A uniform randomized word-RAM algorithm must be correct with probability at least 2/3 on every input, and its time bound must hold for every random tape. Set τ(k)=inf{a≥0: such an algorithm runs in O(n^a) time as n→∞}. The program and hidden constants may depend on k, but not on n. Words have C_k⌈log₂(n+2)⌉ bits for some fixed constant C_k; arithmetic modulo the word range, division with remainder, comparisons, Boolean operations, shifts and indirect memory access cost one step, and a fresh random word costs one step. Initial memory apart from the input is zero; preprocessing counts; there is no nonuniform advice, giant-word operation or free oracle. For ω, let M(N) be the smallest number of binary +,−,× gates in a circuit over C that computes all entries of the product of two formal N×N matrices. Arbitrary complex constants and sharing are allowed, but division and branching are not. Define ω=inf{a:M(N)=O(N^a)}. This fixes the characteristic-zero arithmetic convention, separately from the bit-based graph algorithm. The question concerns the coefficient of k in the exponent; it does not fix k proportional to n or treat the latest published numerical upper bound on ω as its exact value.',
 answer_criterion='The matrix-multiplication reduction gives the upper asymptotic benchmark ω/3. An affirmative answer therefore proves that, for every δ>0, there is K such that τ(k)≥(ω/3−δ)k for every fixed k≥K. A negative answer proves a strict saving in this coefficient, for example via algorithms with τ(k)≤(ω/3−δ)k for arbitrarily large k and one δ>0. Saving logarithmic time factors or an additive o(k) in the exponent does not refute this leading-exponent formulation.',
 context=[
 paragraph('For each fixed k, clique detection is already a polynomial-time problem: one can inspect every k-element subset. The issue is which polynomial is necessary. An exponent near k and an exponent near 0.79k differ dramatically as the fixed pattern size increases. This is why ordinary NP-hardness, which allows k to vary with the input, leaves the main quantitative question unanswered.'),
 paragraph('The arithmetic reduction groups the vertices of a candidate clique into three parts. For k=3r, create auxiliary vertices representing r-cliques and join two auxiliary vertices when their represented sets are disjoint and their union is a clique. A triangle in this auxiliary graph represents a 3r-clique in the original graph. There are O(n^r) auxiliary vertices, so matrix-based triangle detection gives the familiar leading time exponent ωk/3.'),
 paragraph('When k is not divisible by three, the groups have unequal sizes. Rectangular matrix multiplication gives more refined bounds for individual k; padding to the next multiple of three already changes the exponent by only a constant. Because this card asks for the leading coefficient as k grows, those residue-class effects do not alter the target. They would matter in a card asking for the exact exponent at a particular small k.','regularity'),
 paragraph('The inherited source states the hypothesis in the n^{ωk/3−o(k)} form and allows both randomized and deterministic algorithms. The explicit liminf formulation records the order of limits: first study n→∞ for each fixed k, then ask about large k. The model definitions make time, error and machine operations explicit. This avoids relying on an informal distinction between which graph algorithms count as combinatorial.','primary'),
 paragraph('The word algebraic names the benchmark supplied by matrix multiplication. It does not restrict the algorithms against which the conjecture asserts hardness. A refuting algorithm could use arithmetic, combinatorial structure, randomization, or a combination. Likewise, ω is an unknown mathematical constant defined by the best possible arithmetic circuits, rather than a decimal frozen at the date of an old reduction.'),
 paragraph('A better upper bound on ω immediately improves the matrix-based clique algorithm without disproving this hypothesis. Conversely, an algorithm whose exponent beats an old numerical estimate may still be slower than the conjectured benchmark using the true ω. The distinction becomes especially relevant after small improvements in matrix multiplication: Dupont and coauthors’ August 2026 note reports ω<2.371177, improving the preceding 2.371339 bound. Its numerical certificate has not been replayed for this catalogue.','matrix'),
 paragraph('Abboud–Fischer–Shechter improve the algorithms usually called combinatorial by logarithmic factors. At fixed k, their displayed detection bound is n^k(log n)^{−(k+1)}(log log n)^{k+3}. Such progress is useful, but the logarithmic factor changes an exponent by o(1) as n grows and does not establish a new leading coefficient below ω/3. Their separate hypergraph and listing results have different outputs or incidence structures.','combinatorial'),
 paragraph('The hypothesis supports lower bounds for tasks that do not look like clique detection. Das–Lincoln–Lynch–Munro use clique reductions for dynamic Boolean-formula evaluation and counting. A faster data structure with the relevant preprocessing and update guarantees could therefore force faster clique algorithms. This explains the inclusion of an apparently indirect dynamic-data-structure paper as the inherited reference: its computational-hypothesis section states this exact leading-exponent assumption.','primary'),
 paragraph('Recent work strengthens the network of reductions rather than proving the hypothesis. Fischer–Künnemann–Redžić–Stieß show that suitable regularity restrictions on partite graphs and hypergraphs preserve the relevant detection exponent, with parameter-dependent factors. This helps transfer conditional hardness to Boolean constraint optimization. Their result cannot be read as an unconditional lower bound for all word-RAM algorithms.','regularity'),
 paragraph('Fischer–Künnemann–Redzic’s January 2026 coverage and partial-domination results similarly give algorithms and matching bounds conditional on clique and hyperclique hypotheses. The 3-uniform hyperclique assumption concerns triples as constraints and has a different exhaustive-search benchmark; it is not the graph hypothesis in this card. Keeping the two separate prevents a strong conditional statement for one problem from being mistaken for a resolution of the other.','coverage'),
 paragraph('The fundamental question is whether all-pairs algebra can capture the optimal leading cost of enforcing every pairwise adjacency in a growing fixed pattern. An affirmative answer would justify a widely used quantitative barrier. A negative answer would identify a way to exploit the clique decision task beyond the matrix-multiplication benchmark, potentially changing many currently conditional optimality claims.')],
 why='A basic quantitative hardness hypothesis for graph patterns and many reductions in fine-grained complexity, precisely testing whether the matrix-multiplication exponent gives the optimal leading coefficient.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A principal fine-grained benchmark connecting clique detection, matrix multiplication, dynamic data structures, and constraint optimization.'),
 progress=[step('1985','Nešetřil–Poljak’s grouping reduction gives the matrix-multiplication benchmark, with rectangular refinements for k not divisible by three.','regularity'),step('2021','Das–Lincoln–Lynch–Munro explicitly formulate randomized/deterministic n^{ωk/3−o(k)} hardness and use it in dynamic formula lower bounds.','primary'),step('2024–2026','Abboud–Fischer–Shechter improve combinatorial clique detection by logarithmic factors; the preprint revision is August 2024 and the Algorithmica version appears in 2026.','combinatorial'),step('2025','Fischer–Künnemann–Redžić–Stieß prove exponent-preserving regularization reductions and apply them to Boolean CSP optimization.','regularity'),step('2026-01-23','Fischer–Künnemann–Redzic obtain conditional optimality results for maximum coverage and partial domination using clique and hyperclique assumptions.','coverage'),step('2026-08-17','Dupont and coauthors report ω<2.371177, improving the available clique upper bound through the existing reduction without settling optimality.','matrix')],
 references=[ref('primary','Dynamic Boolean Formula Evaluation','Rathish Das; Andrea Lincoln; Jayson Lynch; J. Ian Munro',2021,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ISAAC.2021.61','Inherited reference; ISAAC 2021, article 61; §2.1, Definition 2 states n^{ωk/3−o(k)} hardness for randomized or deterministic algorithms'),ref('combinatorial','Faster Combinatorial k-Clique Algorithms','Amir Abboud; Nick Fischer; Yarin Shechter',2024,'https://arxiv.org/abs/2401.13502v2','Revision 3 August 2024; LATIN 2024, later Algorithmica 88, article 48 (2026), DOI 10.1007/s00453-026-01390-8; Theorem 1 and Corollary 1'),ref('regularity','The Role of Regularity in (Hyper-)Clique Detection and Implications for Optimizing Boolean CSPs','Nick Fischer; Marvin Künnemann; Mirza Redžić; Julian Stieß',2025,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2025.78','ICALP 2025; §1.1 gives the grouping bound and its divisibility qualification; Theorem 1.1 preserves detection exponents under regularization'),ref('coverage','Conditionally Tight Algorithms for Maximum k-Coverage and Partial k-Dominating Set via Arity-Reducing Hypercuts','Nick Fischer; Marvin Künnemann; Mirza Redzic',2026,'https://arxiv.org/abs/2601.16923','Posted 23 January 2026; applications of separate graph-clique and 3-uniform hyperclique hypotheses'),ref('matrix','Improving the matrix multiplication exponent with modern optimization and AlphaEvolve','Emilien Dupont; Marvin Eisenberger; Borislav Kozlovskii; Abbas Mehrabian; Francisco J. R. Ruiz; Abigail See; Renfei Zhou; Josh Alman; Virginia Vassilevska Williams; Matej Balog',2026,'https://arxiv.org/abs/2608.16884','Posted 17 August 2026; reports ω<2.371177 via optimized combination-loss bounds; numerical verification not rerun for this catalogue')],
 status='source_open',status_note='Open in the stated unrestricted randomized leading-exponent form, following the inherited hypothesis and later primary sources checked through 11 September 2026. The liminf and machine conventions make the asymptotic claim explicit. Logarithmic speedups, matrix-exponent improvements and conditional lower bounds do not settle it.',formulation_reviewed_on='2026-09-11')
