import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('polynomial-time-polylogarithmic-directed-steiner-tree',
 id='TCS-6588',title='A polynomial-time polylogarithmic approximation for Directed Steiner Tree',area='Approximation algorithms and hardness of approximation',criterion='resources',question_type='yes_no',
 formal='Do there exist constants a≥1 and C≥1 and a uniform randomized polynomial-time algorithm that, for every feasible Directed Steiner Tree instance with k terminals, outputs a feasible subgraph of cost at most a(log₂(k+2))^C times optimum with probability at least 2/3?',
 definitions='An instance consists of a finite directed graph G=(V,E), a root r∈V, a nonempty terminal set T⊆V∖{r} with k=|T|, and nonnegative rational arc costs c_e given exactly in binary. Every terminal is promised reachable from r; this can also be checked in polynomial time, with infeasibility reported otherwise. A feasible solution is an arc subset F⊆E such that (V,F) contains a directed path from r to every t∈T. Its cost is Σ_{e∈F}c_e, counting an arc once even if many paths use it. OPT is the minimum such cost. The algorithm must output a feasible subset on every execution and satisfy the approximation guarantee on every instance with probability at least 2/3 over its internal randomness. Its bit running time on every execution is bounded by one fixed polynomial in the entire input encoding length, including cost bits. The constants a,C and the polynomial are independent of n=|V|, k and the costs. If OPT=0, the successful output must also have zero cost. Local computation is ordinary uniform classical computation without advice or free optimization oracles. There is no planarity, acyclicity, bounded depth, bounded treewidth, metric, or supplied fractional-solution promise. The word tree refers to the optimization problem: any feasible subgraph may be returned, and redundant edges can be removed.',
 answer_criterion='Construct an algorithm and fixed constants satisfying these bounds, or prove that no such randomized polynomial-time algorithm exists. An O(k^ε)-approximation for every separately fixed ε>0, a polylogarithmic approximation taking quasipolynomial time, or a guarantee on a restricted graph class is partial progress. A gap for a particular LP relaxation limits that relaxation, not every algorithm. A hardness result ruling out only some smaller powers of log k does not exclude all fixed powers and therefore does not refute this proposition.',
 context=[
 paragraph('The problem asks how cheaply a root can reach many destinations through one shared directed network. Buying a common initial segment can save cost across many root-to-terminal paths, but the directions restrict which branching structures are usable. With one terminal the problem is shortest path. With many terminals, selecting where the paths should share infrastructure becomes the central optimization challenge.'),
 paragraph('A simple reduction explains why ordinary reachability is insufficient. For a set-cover instance, create a vertex for each set and each element, an arc of cost one from the root to every set vertex, and zero-cost arcs from each set to its elements. Make all element vertices terminals. A feasible network must buy a collection of set arcs covering all elements, and its cost equals the number of chosen sets. The directed graph can thus encode a nontrivial covering problem even with only two layers after the root.'),
 paragraph('The familiar polynomial-time approximation frontier is O(k^ε) for every fixed ε>0, from the classical directed Steiner algorithms. The running-time exponent depends on the chosen accuracy parameter. Setting ε to a quantity that shrinks with k is not a free improvement: it changes that dependence and can produce quasipolynomial time. A power of k, however small and fixed, eventually exceeds every fixed power of log k.','classical'),
 paragraph('Grandoni, Laekhanukit and Li obtain an O(log² k/log log k)-approximation in quasipolynomial time. Their techniques combine a structured reduction with a hierarchy of strengthened linear relaxations and dependent rounding. This establishes that a good approximation exists at a slower time scale. The requested advance is to achieve some polylogarithmic factor with a fixed polynomial running-time exponent; matching the sharper quasipolynomial factor is not required.','quasipoly'),
 paragraph('The same work gives near-matching quasipolynomial-time hardness under additional complexity assumptions, including the Projection Games Conjecture. This does not show that every polynomial-time polylogarithmic approximation is impossible: a larger fixed logarithmic power is allowed in this card. The issue is a gap between what can currently be computed in polynomial time and what is known with more time, rather than the already settled hardness of exact optimization.','quasipoly'),
 paragraph('A natural flow relaxation buys a fractional capacity x_e for each arc and, separately for each terminal, sends a unit flow from the root using at most x_e on that arc. Different terminals may reuse the same purchased capacity because a network edge is bought once. In general graphs this relaxation has polynomial-size integrality gaps, including Ω(√k) examples. Those examples explain why a straightforward LP-rounding strategy cannot guarantee a polylogarithmic factor against that relaxation on every instance. They do not rule out stronger relaxations or a different algorithm.','embedding'),
 paragraph('The inherited Laekhanukit reference requires careful version tracking. Its December 2024 general claim was withdrawn in version 2. Version 3, submitted in October 2025, presents itself as a rectification restricted to a relatively integral fractional solution: each terminal flow on an edge is either zero or the entire purchased capacity. The record still displays the earlier withdrawal comment about a reachability-proof error. This card treats the later restricted statement as a reported claim, not an established general approximation; finding an appropriate fractional solution is an additional requirement.','relative'),
 paragraph('Planarity changes the picture substantially. Friggstad and Mousavi give a polynomial-time O(log k)-approximation for planar directed graphs, using shortest-path separators. Later work extends the structural approach to other rooted planar network-design problems and bounds a natural planar LP gap by O(log² k). These theorems show that directedness alone does not preclude the requested factor, but their separator arguments do not apply to arbitrary directed graphs.','planar'),
 paragraph('Chekuri and Jain’s July 2026 work extends planar results to length-constrained network design. Its guarantees are bicriteria: they approximate cost while allowing an O(log k) multiplicative violation of the path-length constraint. The paper explicitly retains the general Directed Steiner Tree approximation question as open. Removing a length constraint or changing the objective does not remove the planarity hypothesis needed by those algorithms.','length')],
 why='A defining gap in directed network-design approximation: determine whether a shared directed connection network can be approximated within a polylogarithmic factor using only polynomial time.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A central approximation problem encompassing covering and rooted network design, with a persistent gap between polynomial and quasipolynomial algorithms.'),
 progress=[
 step('1998–1999','Classical directed Steiner approximation algorithms give O(k^ε) for every fixed ε>0 in polynomial time.','classical'),
 step('2019','Grandoni–Laekhanukit–Li obtain O(log² k/log log k) in quasipolynomial time, with conditional matching-scale hardness.','quasipoly'),
 step('2023','Friggstad–Mousavi obtain a polynomial-time O(log k)-approximation for planar digraphs.','planar'),
 step('2024','Chekuri and coauthors extend planar rooted-network techniques and prove an O(log² k) planar LP gap.','embedding'),
 step('2024-12-20','Version 2 of Laekhanukit’s initial general claim is withdrawn.','relative'),
 step('2025-10-10','Version 3 narrows that claim to access to a relatively integral fractional solution; the record retains its withdrawal comment.','relative'),
 step('2026-07-28','Chekuri–Jain obtain planar length-constrained bicriteria approximations and explicitly retain the general polynomial-time polylogarithmic question.','length')],
 references=[
 ref('classical','Approximation Algorithms for Directed Steiner Problems','Moses Charikar; Chandra Chekuri; To Yat Cheung; Zuo Dai; Ashish Goel; Sudipto Guha; Ming Li',1999,'https://chekuri.web.engr.illinois.edu/pub.html','Journal of Algorithms 33, 73–91; SODA 1998 precursor. Author bibliography corrects the original quasipolynomial O(log² k) claim to O(log³ k) because of the height-reduction lemma'),
 ref('quasipoly','O(log² k/log log k)-Approximation Algorithm for Directed Steiner Tree: A Tight Quasi-Polynomial-Time Algorithm','Fabrizio Grandoni; Bundit Laekhanukit; Shi Li',2019,'https://people.idsia.ch/~grandoni/Pubblicazioni/GLL19stoc.pdf','STOC 2019, 253–264; polynomial versus quasipolynomial time distinction and explicit extra hardness assumptions'),
 ref('planar','An O(log k)-Approximation for Directed Steiner Tree in Planar Graphs','Zachary Friggstad; Ramin Mousavi',2023,'https://arxiv.org/abs/2302.04747','v2, 21 April; ICALP 2023 article 63, Theorem 1; requires planarity'),
 ref('embedding','From Directed Steiner Tree to Directed Polymatroid Steiner Tree in Planar Graphs','Chandra Chekuri; Rhea Jain; Shubhang Kulkarni; Da Wei Zheng; Weihao Zhu',2024,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ESA.2024.42','Planar tree embeddings and LP gap; introduction records the polynomial integrality gap in general graphs'),
 ref('relative','On the Integrality Gap of Directed Steiner Tree LPs with Relatively Integral Solutions','Bundit Laekhanukit',2025,'https://arxiv.org/abs/2412.10744','v2 withdrawn 20 December 2024; v3 submitted 10 October 2025, PDF dated 13 October with title On the LP-relaxation for Directed Steiner Tree with Relatively Integral Solution; first-page rectification note and Theorem 1; record still carries withdrawal comment'),
 ref('length','Length-Constrained Network Design in Planar Digraphs','Chandra Chekuri; Rhea Jain',2026,'https://arxiv.org/abs/2607.25811','v1, 28 July; APPROX/RANDOM 2026 article 15; introduction explicitly states the general open question; bicriteria length violation is O(log k)')],
 status='source_open',status_note='The July 2026 primary literature explicitly leaves this general-graph question open. The inherited 2024 claim was withdrawn, and its October 2025 replacement is restricted to a special supplied fractional solution; that claim is not counted as an established general result. Planar and quasipolynomial algorithms do not satisfy this card. Checked through 11 September 2026.',formulation_reviewed_on='2026-09-11')
