import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('cerny-conjecture-sharp-quadratic-reset-threshold',
 id='TCS-6558', title='Černý conjecture: a reset word of length at most (n−1)²',
 area='Automata and formal languages', criterion='tightness', question_type='yes_no',
 formal=r'''Does every synchronizing complete deterministic finite automaton with n≥1 states have a reset word of length at most (n−1)²?''',
 definitions=r'''An automaton here is a finite transition system A=(Q,Σ,δ), with |Q|=n, a finite nonempty alphabet Σ, and a total function δ:Q×Σ→Q. Extend δ to words by δ(q,ε)=q and δ(q,wa)=δ(δ(q,w),a). A word w is a reset word when |{δ(q,w):q∈Q}|=1. The automaton is synchronizing if at least one such word exists; its reset threshold rt(A) is the minimum number of letters in a reset word. The quantification ranges over every n and every finite alphabet and total transition function satisfying this promise. The common final state need not be specified beforehand. Initial states and accepting states play no role. The empty word handles n=1. No strong-connectivity, binary-alphabet, permutation-letter, or other structural restriction is imposed. Partial automata, nondeterministic transitions, and synchronizing only a prescribed proper subset of Q are different models.''',
 answer_criterion='Prove the exact bound rt(A)≤(n−1)² for all promised automata, or exhibit a finite complete synchronizing automaton and prove its shortest reset word exceeds that bound. A universal O(n²) bound with a larger constant would be major progress but would not settle this exact statement.',
 context=[
  paragraph('Synchronization asks how to restore a finite system to a known state when its current state is unknown. A fixed input sequence must work simultaneously from every possible starting state; it cannot observe the intermediate state and adapt its next letter. The length bound therefore measures the cost of an open-loop reset, rather than ordinary shortest-path navigation from a known vertex.','volkov'),
  paragraph('The proposed constant is forced by a concrete family. On states 0,…,n−1, let a cyclically increment the state and let b send n−1 to 0 while fixing the other states. For n≥2, the word b(a^{n−1}b)^{n−2} has length (n−1)² and resets this automaton. Černý’s construction also proves that no shorter reset word works. A proof of the conjecture must match this obstruction exactly.','list'),
  paragraph('Knowing that a reset exists is much easier than establishing its sharp maximum length. Pairwise merging gives polynomial criteria for synchronizability, and successive compression of subsets gives general polynomial length bounds. The bottleneck is how much progress one can force as the current set of possible states shrinks. Adding separate worst-case bounds for these stages gives a cubic estimate and can lose information about how the stages interact.','survey'),
  paragraph('The best general estimate recorded in the August 2026 open-problems survey remains approximately 0.1654n³+o(n³), following Shitov’s improvement of Szykuła’s compression and avoidance argument. Thus even a subcubic bound for unrestricted automata would close a significant part of the gap. Numerous positive results for special classes demonstrate useful mechanisms, but do not impose those mechanisms on an arbitrary transition system.','shitov'),
  paragraph('A July 2026 preprint reports the conjectured bound for one-cluster automata: systems having a letter whose functional graph has exactly one directed cycle. Its sharper positive-level estimate uses the cycle length and the distance of off-cycle states from that cycle. This is a claim for a restricted class, and the later general survey still states the unrestricted conjecture as open.','onecluster')],
 why='A central extremal problem in automata theory, with a simple finite-state formulation and a sharp explicit candidate bound. It tests whether local compression and algebraic structure can force globally short control sequences in every synchronizing system.',
 importance=dict(score=98, method='editorial', assessed_on='2026-09-10', reason='The flagship quantitative question about synchronizing automata, connecting finite-state control, extremal combinatorics, and linear-algebraic methods.'),
 progress=[
  step('1964','Černý constructs an n-state family with reset threshold exactly (n−1)², establishing the sharp lower-bound target.','list'),
  step('1978–1982','The classical Pin–Frankl compression argument gives a general cubic upper bound; the survey records (n³−n)/6−1 for n≥4.','survey'),
  step('2018','Szykuła combines compression with avoiding words to improve the long-standing leading cubic constant.','szykula'),
  step('2019','Shitov improves that argument to a leading constant approximately 0.1654; the exponent remains three.','shitov'),
  step('2026-01','Volkov’s updated list records established special classes and their reset-threshold bounds while keeping the general conjecture open.','list'),
  step('2026-07-22','Zhu reports a proof for the one-cluster subclass in a preprint. This card does not independently certify that proof or extend it to unrestricted automata.','onecluster'),
  step('2026-08-25','Szykuła’s AFL 2026 survey explicitly states the general conjecture and identifies the cubic Shitov estimate as the best known unrestricted bound.','survey')],
 references=[
  ref('survey','Synchronizing Automata: Open Problems','Marek Szykuła',2026,'https://arxiv.org/abs/2608.24245','25 August 2026; AFL 2026, EPTCS 451, 33–47; §§1.1, 2.1 and 2.6; Conjecture 1; DOI 10.4204/EPTCS.451.3'),
  ref('volkov','Synchronization of finite automata','Mikhail V. Volkov',2022,'https://doi.org/10.4213/rm10005e','Russian Mathematical Surveys 77(5), 819–891; general synchronization survey'),
  ref('list','List of Results on the Černý Conjecture and Reset Thresholds for Synchronizing Automata','Mikhail V. Volkov',2026,'https://arxiv.org/abs/2508.15655','Version 4, 13 January 2026; §1.2 and catalogue of special classes; original Černý family and bound'),
  ref('szykula','Improving the Upper Bound on the Length of the Shortest Reset Word','Marek Szykuła',2018,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.STACS.2018.56','STACS 2018, 56:1–56:13; avoidance and compression upper bound'),
  ref('shitov','An Improvement to a Recent Upper Bound for Synchronizing Words of Finite Automata','Yaroslav Shitov',2019,'https://doi.org/10.25596/jalc-2019-367','Journal of Automata, Languages and Combinatorics 24(2–4), 367–373; refined cubic upper bound'),
  ref('onecluster','The Černý Conjecture for One-Cluster Automata via Annular Spectral Descent','Yinfeng Zhu',2026,'https://arxiv.org/abs/2607.19675','Version 1, 22 July 2026; abstract and §1; restricted-class preprint claim, not a general resolution')],
 status='source_open', status_note='Explicitly open in the AFL survey posted 25 August 2026. Literature checked through 10 September 2026. The July one-cluster preprint is identified as a restricted-class claim and does not change the general status.', formulation_reviewed_on='2026-09-10')
