import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('np-outside-bqp',
 id='TCS-0037',title='NP outside BQP',area='Quantum computation',criterion='resources',question_type='yes_no',
 formal='Is NP⊈BQP? Equivalently, is there no uniform polynomial-time quantum algorithm that decides satisfiability of every Boolean 3-CNF formula with error probability at most 1/3 on each input?',
 definitions='NP is the class of languages L⊆{0,1}* for which there exist a deterministic polynomial-time verifier V and a polynomial p such that x∈L exactly when some binary string y of length at most p(|x|) satisfies V(x,y)=1. BQP consists of languages decided by polynomial-size quantum circuit families {C_n} that a deterministic classical algorithm generates from 1ⁿ in polynomial time. The circuits use a fixed finite universal gate set, for example Hadamard, T and controlled-NOT, polynomially many qubits initialized with the input x and zero ancillas, and a final measured output bit. Acceptance probability is at least 2/3 when x∈L and at most 1/3 when x∉L. The size bound counts all elementary gates, not only calls to a selected subroutine. There is no advice, postselection, oracle or supplied witness. A 3-CNF formula is a conjunction of clauses, each a disjunction of at most three literals, with a literal being a variable or its negation. The input length is the length of a conventional explicit binary encoding; malformed encodings are rejected. NP⊈BQP asserts the existence of at least one language in NP outside BQP, rather than merely inequality of the two classes.',
 answer_criterion='Prove an unconditional separation NP⊈BQP, or refute it by establishing NP⊆BQP. By NP-completeness and closure under classical polynomial-time reductions, the latter is equivalent to putting 3-SAT in BQP. An oracle separation, a lower bound only on unstructured search, an algorithm for a restricted family of formulas, or a conditional hardness statement does not settle the question. A separation from BQP must exclude every uniform polynomial-size circuit family, not just a particular quantum algorithm or architecture.',
 context=[
 paragraph('An NP witness gives a short, classically checkable reason for a yes answer. For satisfiability, that witness is an assignment to the variables. The question is whether the existence of such a witness can always be decided efficiently using quantum computation, even when the witness itself is not supplied. Wigderson lists the noncontainment as Conjecture 11.5 in the inherited 2018 draft.','book'),
 paragraph('The distinction between verification and discovery is essential. A quantum computer can certainly evaluate a Boolean formula on a proposed assignment. It can also place assignments into superposition. But a measurement does not reveal a list of the values computed on every assignment. An efficient algorithm must arrange interference so that the eventual measurement supplies the desired decision with bounded error.'),
 paragraph('Shor’s factoring and discrete-logarithm algorithms show that quantum computation can exploit special mathematical structure to solve important problems in polynomial time. Their speed comes from extracting periodic information, not from a general procedure for every efficiently checkable witness relation. Factoring is not known to be NP-complete, so its quantum algorithm does not imply that 3-SAT or all of NP belongs to BQP.','shor'),
 paragraph('Grover’s search algorithm gives a different kind of advantage: a quadratic improvement for an unstructured search space. Applied to N Boolean variables, the space has 2ᴺ assignments, so the generic search scale becomes 2^{N/2}, with additional polynomial work to evaluate the formula. This is a substantial speedup and remains exponential in N. The distinction is about asymptotic resources, even if that reduction could be valuable on concrete instances.','grover'),
 paragraph('Bennett, Bernstein, Brassard and Vazirani prove a matching black-box obstruction and an oracle separation of NP from quantum polynomial time. Their result excludes a universal shortcut that treats the witness verifier only as an unknown function. An explicit formula reveals more than black-box evaluations: an algorithm can inspect shared variables, clauses and every feature of its encoding. Thus the oracle theorem does not establish the unrelativized separation asked for here.','bbbv'),
 paragraph('There is a useful elementary implication. Since deterministic polynomial-time computation is contained in BQP, P=NP would put all of NP in BQP. Therefore a positive answer to this card would also prove P≠NP. The converse implication is unavailable: P≠NP alone does not rule out quantum polynomial-time algorithms for NP-complete problems. This helps explain why proving an unrestricted quantum lower bound is such an ambitious target.'),
 paragraph('The decision version already captures efficient witness finding for SAT. If a bounded-error quantum SAT decider existed, one could repeatedly fix a variable, ask whether the remaining formula is satisfiable, and retain a satisfiable branch. Amplifying the decision success probability makes the probability of any mistake across the polynomially many calls small. Finally, the resulting assignment can be checked classically. This is a consequence of SAT’s self-reduction, not an assumption that a quantum algorithm hands over all possible witnesses at once.'),
 paragraph('The conjecture also supports hardness results for tasks whose inputs and outputs are intrinsically quantum. In June 2026, Cifuentes proves that an efficient quantum algorithm for detecting a large nonidentity Pauli coefficient of a circuit-prepared state would imply NP⊆BQP. The reduction holds even for pure states and a constant threshold with a promised gap. It transfers the conjecture to a tomography-related task; it does not prove the conjecture itself.','pauli'),
 paragraph('Several nearby questions should remain distinct. BPP versus BQP asks whether quantum computation adds power beyond classical randomization. NP versus BQP asks whether quantum computation can solve every classically verifiable decision problem. Allowing a quantum witness changes the verifier class again, to QMA. Establishing a separation or a speedup involving one pair does not automatically establish the relation between the others.'),
 paragraph('A resolution would locate a fundamental boundary of quantum computation. If NP⊆BQP, quantum algorithms would provide a universal efficient route to classical constraint satisfaction and its many reductions. If NP⊈BQP, some efficiently verifiable problems would resist even ideal fault-tolerant quantum computers. Neither answer is about today’s hardware capacity: the model already grants arbitrarily scalable, accurate quantum computation with polynomial resources.')],
 why='Determine whether efficient classical verification always leads to efficient quantum solution, a central limit on what quantum computation can achieve.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A foundational relation between quantum algorithms and NP-completeness; a noncontainment proof would also separate P from NP.'),
 progress=[
 step('1994–1997','Shor gives polynomial-time quantum factoring and discrete-logarithm algorithms, establishing major structured algorithmic successes without solving an NP-complete problem.','shor'),
 step('1996','Grover obtains a quadratic speedup for unstructured search, which yields an exponential-time generic approach to searching SAT assignments.','grover'),
 step('1997','Bennett–Bernstein–Brassard–Vazirani prove quantum search lower bounds and NP-versus-quantum separations relative to random oracles.','bbbv'),
 step('2018','Wigderson explicitly records NP⊈BQP as Conjecture 11.5, distinct from BPP≠BQP.','book'),
 step('2026-06-17','Cifuentes reduces NP hardness to detecting a large Pauli coefficient, deriving quantum algorithmic hardness under NP⊈BQP rather than resolving the assumption.','pauli')],
 references=[
 ref('book','Mathematics and Computation','Avi Wigderson',2018,'https://www.math.ias.edu/files/mathandcomp.pdf','Inherited 27 March 2018 draft, Chapter 11, Conjecture 11.5, printed page 136; neighbouring Conjecture 11.4 concerns BPP versus BQP'),
 ref('shor','Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer','Peter W. Shor',1997,'https://arxiv.org/abs/quant-ph/9508027','FOCS 1994 precursor; checked v2, 25 January 1996; SIAM Journal on Computing 26(5), 1484–1509, 1997'),
 ref('grover','A fast quantum mechanical algorithm for database search','Lov K. Grover',1996,'https://arxiv.org/abs/quant-ph/9605043','STOC 1996, 212–219; checked v3, 19 November 1996; O(√M) search over M candidates'),
 ref('bbbv','Strengths and Weaknesses of Quantum Computing','Charles H. Bennett; Ethan Bernstein; Gilles Brassard; Umesh Vazirani',1997,'https://arxiv.org/abs/quant-ph/9701001','SIAM Journal on Computing 26(5), 1510–1523; random-oracle NP lower bound; the oracle setting is essential'),
 ref('pauli','Complexity of detecting large coefficients in the Pauli basis','Santiago Cifuentes',2026,'https://arxiv.org/abs/2606.19545','17 June 2026; promised ε-versus-ε/2 Pauli-coefficient detection for circuit-prepared states; NP reduction and conditional exclusion from BQP')],
 status='source_open',status_note='No unconditional separation or general quantum polynomial-time SAT algorithm found through 11 September 2026. Black-box lower bounds do not establish the ordinary language-class separation. June 2026 work continues to use NP⊈BQP explicitly as an unproved hardness hypothesis.',formulation_reviewed_on='2026-09-11')
