import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('planar-ksets-sharp-asymptotic-bound',
 id='TCS-0318',title='How many k-element subsets can a line separate from a planar point set?',
 area='Computational geometry',criterion='tightness',question_type='asymptotic_complexity',
 formal=r'''Let K₂(n,k) be the maximum, over sets P of n distinct points in $\mathbb R^2$ with no three collinear, of the number of distinct subsets S⊆P of size k strictly separable from P\S by a line. Determine K₂(n,k) up to universal constant factors, uniformly for all integers n≥2 and 1≤k≤⌊n/2⌋.''',
 definitions=r'''Strict separation means that there are real a,b,c with (a,b)≠(0,0), ax+by<c for every (x,y)∈S, and ax+by>c for every (x,y)∈P\S. The objects counted are subsets S, not their infinitely many possible separating lines. Coordinates have no bounded-precision, grid, or random-distribution promise. The target is worst-case combinatorial complexity, not the running time of an enumeration algorithm. A matching bound means an asymptotic expression F(n,k) and absolute constants 0<c₀≤C₀<∞ such that c₀F(n,k)≤K₂(n,k)≤C₀F(n,k) throughout the stated range, apart from finitely many n which can be absorbed into the constants. Bounds must cover k that grows with n. Complementation supplies the remaining values n/2<k<n; k=0,n each have one subset. This card specializes the original all-dimensions problem to the plane.''',
 answer_criterion='Prove an upper bound for every admissible planar point set and a lower-bound construction for each admissible n,k that match within absolute constant factors. Resolving only fixed k, only the balanced case k=⌊n/2⌋, or only the exponent while leaving an unbounded factor between the bounds is partial progress.',
 context=[
  paragraph('A line can realize only a small fraction of all choices of k points. The question measures the combinatorial capacity of one linear cut at a fixed output size. For example, when k=1 the separable points are the convex-hull vertices, and their maximum number is n. The difficult regime lets k increase with the input size.'),
  paragraph('Point-line duality translates changes of a separating line into the structure of levels in a line arrangement. A level tracks positions having a specified number of lines below them. These level bounds recur in geometric selection and in analyses of parametric optimization. Dey’s method also yields bounds for related level structures, convex chains, and parametric spanning-tree problems.', 'upper'),
  paragraph('For even n, the balanced case is closely tied to halving edges: segments joining two input points whose supporting line leaves (n−2)/2 of the other points on each side. A halving edge is not itself a separating line, since it passes through input points. The correspondence between k-sets and directed (k−1)-edges gives K₂(n,n/2) equal to twice the maximum number of undirected halving edges.', 'nivasch'),
  paragraph('The known planar upper bound is O(n k^(1/3)), whereas constructions give n exp(Ω(√log k)) subsets. In the balanced regime the latter grows faster than n times any fixed power of log n, yet slower than n^(1+ε) for each fixed ε>0. Thus neither a linear bound nor an ordinary polylogarithmic correction to linear growth can describe the worst case.', 'lower'),
  paragraph('Sharper finite-size constructions and improvements to the additive terms of halving-line bounds are useful progress. They do not close the gap in asymptotic growth. Keeping this distinction explicit matters here: an improved upper bound may retain the same 4/3 exponent in the balanced case.', 'recent')],
 why='A central unresolved counting problem in computational geometry, it controls the complexity of levels and line-separated ranges. Its persistent gap tests the strength of crossing-number methods and geometric constructions, with consequences for output-sensitive and parametric algorithms.',
 importance=dict(score=94,method='editorial',assessed_on='2026-09-10',reason='A defining extremal-complexity question for geometric algorithms, already unresolved in the plane and connected to levels, geometric selection, and parametric optimization.'),
 progress=[
  step('1997–1998','Dey proves K₂(n,k)=O(n k^(1/3)) for 1≤k≤n/2 through a crossing-number argument. The balanced specialization gives an O(n^(4/3)) upper bound.','upper'),
  step('2000–2001','Tóth constructs planar point sets with n exp(Ω(√log k)) k-sets for n≥2k>0, improving the earlier n log k scale. This remains separated from the upper bound by an unbounded factor when k grows.','lower'),
  step('2008','Nivasch gives a simpler halving-edge construction improving the constant in the square-root-log exponent. The construction does not produce n^(1+ε) halving edges for any fixed positive ε.','nivasch'),
  step('2024-07','Alonso, López, and Rodrigo improve a linear subtractive term in the upper bound on the maximum number of halving lines for even n, and improve some finite-n bounds. The asymptotic upper exponent remains 4/3.','recent'),
  step('2025-06','The revised Open Problems Project entry still lists the planar asymptotic gap as unresolved. A search through September 2026 did not locate matching general upper and lower bounds.','problem')],
 references=[
  ref('problem','The Open Problems Project: Problem 7, k-sets','Erik D. Demaine; Joseph S. B. Mitchell; Joseph O’Rourke (editors)',2025,'https://topp.openproblem.net/p7','Entry revised 14 June 2025; original question allows higher dimensions'),
  ref('upper','Improved Bounds for Planar k-Sets and Related Problems','Tamal K. Dey',1998,'https://courses.cs.duke.edu/cps234/fall08/handouts/dey.pdf','Discrete & Computational Geometry 19, pp. 373–382; DOI 10.1007/PL00009354; preliminary FOCS 1997 result'),
  ref('lower','Point Sets with Many k-Sets','Géza Tóth',2001,'https://link.springer.com/article/10.1007/s004540010022','Discrete & Computational Geometry 26, pp. 187–194; abstract; preliminary SoCG 2000 result'),
  ref('nivasch','An Improved, Simple Construction of Many Halving Edges','Gabriel Nivasch',2008,'https://rangevoting.org/many_halving_edges.pdf','Contemporary Mathematics 453; Section 1, k-set/k-edge correspondence and bound (1.2)'),
  ref('recent','An Improvement of the Upper Bound for the Number of Halving Lines of Planar Sets','Estrella Alonso; Mariló López; Javier Rodrigo',2024,'https://oa.upm.es/89576/1/10302927.pdf','Symmetry 16(7), 936, 22 July 2024; introduction and conclusion; DOI 10.3390/sym16070936')],
 status='source_open',status_note='The June 2025 problem entry retains the gap. The 2024 halving-line improvement changes lower-order terms rather than the exponent. No matching asymptotic bound was located in the status search through 10 September 2026.',
 formulation_reviewed_on='2026-09-10')
