import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('universality-turing-equivalence-borel',
 id='TCS-6679',title='Universality of Turing equivalence',area='Computability and algorithmic information',criterion='reductions',question_type='yes_no',
 formal='For every countable Borel equivalence relation E on a standard Borel space X, does there exist a Borel function f:X→2^ℕ such that x E y if and only if f(x)≡_T f(y), for all x,y∈X?',
 definitions='The space 2^ℕ consists of all infinite binary sequences, identified with subsets of ℕ. For a,b∈2^ℕ, a≤_T b means that some oracle Turing machine with oracle b computes every bit of a and halts on every input coordinate; a≡_T b means both a≤_T b and b≤_T a. There is no time or space restriction on these computations. A standard Borel space is a set with the Borel σ-algebra of some Polish topology. The relation E must be a Borel subset of X×X and each equivalence class must be at most countable; X itself may be uncountable. The function f is Borel measurable: inverse images of Borel sets are Borel. It need not be computable, continuous, injective on points, or uniform on indices witnessing equivalence. It must preserve both equivalence and inequivalence on every input pair, not merely almost everywhere for a chosen measure. The quantifiers ask for a separate Borel reduction for each E, without requiring an algorithm that takes a code for E and outputs f. This is the ordinary ZFC formulation of Borel universality.',
 answer_criterion='Prove that Turing equivalence is universal by producing the requisite Borel reductions, or prove it is not by identifying one countable Borel relation that does not reduce to it. Equivalently, settle whether E_∞≤_B≡_T for a fixed standard universal countable Borel relation E_∞. A negative theorem conditional on a form of Martin’s conjecture must be labeled conditional. Failure of reductions with an additional uniformity or computability requirement is not a negative solution to the unrestricted Borel question.',
 context=[
 paragraph('Two infinite binary sequences have the same Turing degree when each can compute the other. This partitions all possible oracles by their computational power. The universality question asks how complicated that partition is as a classification problem: can every countable Borel pattern of equivalence be represented exactly by equality of Turing degrees? The objects being classified are infinite sequences, not finite machine descriptions.'),
 paragraph('There are countably many oracle programs. Consequently, for a fixed oracle b, only countably many sequences can be computed from b, and its Turing-equivalence class is countable. The relation is Borel because a claim that an oracle program computes a given sequence can be written using countably many conditions about finite computations. Thus Turing equivalence itself belongs to the class of relations compared on this card.'),
 paragraph('A Borel reduction is a structured assignment of invariants. If f reduces E to Turing equivalence, the Turing degree of f(x) is a complete invariant for the E-class of x: equivalent objects receive the same degree, and inequivalent objects receive different degrees. Distinct representatives of one E-class may receive different binary sequences, provided those sequences have the same degree. Injectivity on equivalence classes is essential; injectivity on individual points is not.'),
 paragraph('It suffices to study a single standard benchmark E_∞. One realization is the orbit relation for the shift action of the free group F₂ on {0,1}^{F₂}: two labelings x,y are equivalent when y(h)=x(g⁻¹h) for some group element g and every h∈F₂. This countable Borel relation is universal. A reduction of that one relation to Turing equivalence would therefore answer the full universally quantified question.','ref2'),
 paragraph('The inherited Caicedo–Löwe survey records the question as Question 6 in its discussion of Martin’s conjecture. It traces the universality problem to Kechris and distinguishes it from nearby statements about arithmetic equivalence and uniform coding. The source is a 2019 preprint; the later published chapter updates the year in its title. The card retains the exact inherited version and locator.','primary'),
 paragraph('There are strong positive results for neighboring relations. Slaman and Steel proved that arithmetic equivalence is universal; Marks, Slaman and Steel provide a published proof and discussion. Arithmetic equivalence allows each sequence to be computed from some finite Turing jump of the other, with the finite jump levels depending on the pair. That extra allowance changes which sequences become equivalent.','arithmetic'),
 paragraph('In the other direction, Marks proved universality of polynomial-time Turing equivalence, as well as polynomial-time many-one equivalence. These compare arbitrary languages over finite strings by resource-bounded oracle reductions. The theorem concerns the entire space of languages, not only decidable languages or languages inside a familiar complexity class. It establishes universality for a finer relation than unrestricted Turing equivalence.','polynomial'),
 paragraph('Finer and coarser relations do not give an automatic transfer here. A coding that keeps two outputs inequivalent under polynomial-time reductions may still make them equivalent under unrestricted oracle computation. Once that happens, the reverse implication required of a Borel reduction fails. Preserving the encoding under all additional computations is the missing task; simply reusing the polynomial-time result does not complete it.'),
 paragraph('There is also a structural obstruction to familiar coding approaches. With Turing equivalence generated in its usual way by oracle-program reductions, it is not uniformly universal. Roughly, uniformity would require indices for computations between encoded outputs to be chosen solely from the indices witnessing the original equivalence, independently of the particular objects. Marks develops this distinction and shows why the choice of generating maps must be specified.','uniform'),
 paragraph('The present problem permits arbitrary Borel reductions, so that uniform obstruction is not the desired nonuniversality theorem. Whether ordinary universality must entail appropriate stronger uniformity properties is itself part of the surrounding theory. A proof that rules out one common coding pattern therefore reveals a methodological barrier without exhausting all Borel encodings.','uniform'),
 paragraph('Martin’s conjecture supplies a competing prediction. Its Borel form implies that Turing equivalence is not universal; in particular, it obstructs reducing two disjoint copies of Turing equivalence into one copy. Conversely, a universality proof would contradict that prediction. The point is a genuine conditional connection between two major structural questions, not an unconditional settlement in either direction.','arithmetic'),
 paragraph('Day and Marks’ February 2026 revision investigates an older question about writing Turing equivalence as an increasing union whose stages omit certain uniformly computable infinite sequences. A positive answer would imply nonuniform invariant functions and universality of ordinary many-one equivalence. Their consequences remain conditional on that decomposition question, and concern distinctions among degree relations that must not be collapsed into a proof of Turing universality.','recent'),
 paragraph('Settling the card would tell us whether mutual computability provides a universal language for countable Borel classification, or has a structural limitation absent from some nearby degree notions. Either outcome would matter beyond computability: it would constrain the ways orbit equivalence relations, invariants and definable encodings can interact. The answer criterion is a precise existence theorem for reductions, with no algorithmic-efficiency requirement hidden inside the word “Borel.”')],
 why='A central bridge between computability and descriptive set theory, asking whether equality of computational power can encode every countable Borel classification problem.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A classical universality question with consequences for Martin’s conjecture and for the distinction between definable and uniform computational encodings.'),
 progress=[step('1992','Kechris’s universality question is recorded in the historical sources surveyed by Caicedo–Löwe.','primary'),step('2011–2016','Marks–Slaman–Steel publish the universality proof for arithmetic equivalence and explain the conflict between Turing universality and Martin’s conjecture.','arithmetic'),step('2016–2018','Marks proves universality of polynomial-time Turing equivalence; online publication is 2016 and the journal issue is 2018.','polynomial'),step('2017','Marks develops uniform universality and records the obstruction for Turing equivalence with its standard generating reductions.','uniform'),step('2024','Kechris’s book preprint retains Turing universality as Problem 12.5.','ref2'),step('16 February 2026','Day–Marks revise their paper connecting an unresolved decomposition question to nonuniform invariance and many-one universality.','recent')],
 references=[ref('primary','The Fourteen Victoria Delfino Problems and Their Status in the Year 2019','Andrés Eduardo Caicedo; Benedikt Löwe',2019,'https://preprint.math.uni-hamburg.de/public/papers/hbm/hbm770.pdf','Inherited preprint, Question 6, printed page 16; distinguish the later published chapter with 2020 in its title'),ref('ref2','The Theory of Countable Borel Equivalence Relations','Alexander S. Kechris',2024,'https://www.pma.caltech.edu/documents/5921/CBER.pdf','Inherited prepublication version; Problem 12.5 and §12.4; chapter numbering differs from the final Cambridge edition'),ref('arithmetic',"Martin’s conjecture, arithmetic equivalence, and countable Borel equivalence relations",'Andrew Marks; Theodore Slaman; John Steel',2016,'https://arxiv.org/abs/1109.1875','Lecture Notes in Logic 43, 200–219; introduction and §2; preprint 2011, v2 November 2012'),ref('polynomial','The universality of polynomial time Turing equivalence','Andrew S. Marks',2018,'https://arxiv.org/abs/1601.03343','Mathematical Structures in Computer Science 28(3), 448–456; Theorem 1.1; DOI 10.1017/S0960129516000232'),ref('uniform','Uniformity, Universality, and Computability Theory','Andrew S. Marks',2017,'https://arxiv.org/abs/1606.01976','Journal of Mathematical Logic 17(1), 1750003; §3.1, especially the dependence on the chosen generating functions'),ref('recent','On a question of Slaman and Steel','Adam R. Day; Andrew S. Marks',2026,'https://arxiv.org/abs/2004.00174','Original preprint 2020; v2 posted 16 February 2026; Theorem 3.5 and Corollary 5.6; author manuscript dated 15 February 2026')],
 status='source_open',status_note='Reviewed through 11 September 2026. No proof or refutation of ordinary Borel universality of unrestricted Turing equivalence was found in the checked sources. Arithmetic and polynomial-time universality, nonuniformity obstructions and the conditional February 2026 consequences concern distinct statements.',formulation_reviewed_on='2026-09-11')
