import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('fpras-perfect-matchings-general-graphs',
 id='TCS-6628',title='An FPRAS for perfect matchings in general graphs',
 area='Counting and enumeration',criterion='resources',question_type='yes_no',
 formal='Does there exist a fully polynomial randomized approximation scheme for the number Z(G) of perfect matchings in every finite undirected simple graph G? More precisely, is there one randomized algorithm A and one polynomial p such that, for every explicitly encoded graph G and rational 0<ε<1, A halts within p(L,⌈1/ε⌉) bit operations and outputs a nonnegative rational Ẑ satisfying Pr[(1−ε)Z(G)≤Ẑ≤(1+ε)Z(G)]≥3/4, where L is the total binary input length?',
 definitions='A matching is a set of edges with no shared endpoints. It is perfect if every vertex is incident to exactly one selected edge. Z(G) is the number of distinct such edge sets; edges and vertices are unweighted. The graph is specified by a labeled vertex set and its full edge list, without bipartiteness, density, degree, expansion or planarity promises. For an odd number of vertices Z(G)=0; for the empty graph Z(G)=1. The random bits are independent fair bits, all computational and output costs are counted, and the time bound holds for every random tape. When Z(G)=0, require output zero with probability one; this causes no loss of generality because existence of a perfect matching can be decided deterministically in polynomial time before approximation begins. The fixed success probability 3/4 can be amplified to 1−δ by independent repetitions and a median, with an O(log(1/δ)) multiplicative overhead. The same polynomial p must work for all graphs and all requested accuracies.',
 answer_criterion='Give an algorithm and proof of the stated relative-error guarantee and polynomial dependence on both graph size and 1/ε, or prove that no such scheme exists. A hardness result assuming a complexity separation must retain that qualification. Approximating the number of all matchings, the maximum matching size, a logarithm of Z(G), or Z(G) within an exponential factor does not meet this criterion. A bipartite-only FPRAS or exact algorithm for planar graphs is a partial answer.',
 context=[
  paragraph('Finding a perfect matching and estimating how many exist are different tasks. Edmonds’ algorithm handles existence and maximum cardinality in general graphs, whereas exact counting is #P-complete even in bipartite graphs. Approximation avoids asking for every digit of a potentially exponential count, but still requires a reliable multiplicative estimate. The 2018 paper of Štefankovič, Vigoda and Wilmes places this gap at the center of general matching-counting research.','general'),
  paragraph('Jerrum, Sinclair and Vigoda resolve the bipartite case through an FPRAS for the permanent of any nonnegative matrix. A square bipartite adjacency matrix records allowed pairs between two fixed vertex classes; a permutation chooses one partner for every vertex. The algorithm combines a Markov chain on perfect and near-perfect matchings with simulated annealing and weights that balance different pairs of unmatched vertices.','permanent'),
  paragraph('Applying that theorem to the ordinary adjacency matrix of a nonbipartite graph does not count its perfect matchings. For example, K₄ has three perfect matchings, but its adjacency matrix has permanent nine: the latter also counts directed cycle-cover patterns. The corresponding general-graph quantity is a hafnian, a sum over partitions of the vertex set into unordered pairs. The distinction is combinatorial, not a matter of merely changing the matrix dimensions.'),
  paragraph('Counting all matchings is another solved neighboring problem: Jerrum and Sinclair give an FPRAS for the monomer–dimer partition function. The desired perfect matchings may form a very small fraction of that distribution. A disjoint union of k edges already has 2ᵏ matchings and just one perfect matching. Thus approximate uniform sampling from all matchings, followed by waiting for a perfect one, need not run in polynomial time. This example concerns that proposed reduction, not hardness of counting on the example graph.','all'),
  paragraph('Štefankovič, Vigoda and Wilmes show that the straightforward extension of the JSV chain encounters exponential mixing bottlenecks on general graphs; changing weights based only on the unmatched-vertex pattern does not give a universal remedy. They also use the Gallai–Edmonds decomposition to obtain algorithms for structurally restricted graphs. A factor-critical component is one whose deletion of any one vertex leaves a perfect matching. Their parameter concerns the number of ears in such a component’s ear decomposition, not simply its vertex count.','general'),
  paragraph('The problem matters beyond matching counts themselves. Fei, Goldberg and Lu’s 2025 journal paper classifies approximation of several two-state spin-system partition functions. Some parameter settings are linked by approximation-preserving reductions to perfect-matching counting in general graphs, and the paper explicitly retains that task as a central open question. A resolution would therefore determine tractability for related counting models as well.','spin'),
  paragraph('On 27 August 2026, Chen, Vigoda and Yang post an improved permanent FPRAS. For an r×r zero–one matrix their stated bound is O(r⁶ ε⁻² log⁵ r log(2/δ)), improving the previous leading dependence at fixed accuracy and success probability. Their analysis controls mixing of observables describing unmatched-vertex patterns through a restricted Poincaré inequality and coupled flows. The state space remains bipartite; the new theorem does not remove the general-graph obstruction.','faster'),
  paragraph('The central issue is whether the extra structure available in bipartite graphs is essential for efficient approximate counting. A positive result would extend one of the landmark successes of randomized counting to all graphs. A negative result would establish a striking boundary: even though perfect matching existence remains efficiently decidable on both sides, relative counting would become computationally harder once arbitrary odd-cycle structure is permitted.')],
 why='A canonical unresolved problem in approximate counting, separating efficient existence testing from estimating the number of solutions. It also controls the approximability of other counting and partition-function problems through reductions.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='The major missing generalization of the permanent FPRAS, with an established obstruction to the direct Markov-chain approach and consequences beyond matchings.'),
 progress=[
  step('1989','Jerrum–Sinclair give an FPRAS for the monomer–dimer partition function, which counts matchings of all sizes. This is not an unrestricted perfect-matching FPRAS.','all'),
  step('2001–2004','Jerrum–Sinclair–Vigoda establish an FPRAS for nonnegative permanents, solving approximate perfect-matching counting in bipartite graphs.','permanent'),
  step('2017–2018','Štefankovič–Vigoda–Wilmes prove slow mixing for general-graph extensions of the JSV approach and give algorithms based on bounded factor-critical structure.','general'),
  step('2025-08-17','The revised Fei–Goldberg–Lu paper retains general perfect-matching counting as an unresolved approximation class in its spin-system classification.','spin'),
  step('2026-08-27','Chen–Vigoda–Yang improve the permanent FPRAS to O(r⁶ ε⁻² log⁵ r log(2/δ)) for r×r zero–one matrices. The graph remains bipartite.','faster')],
 references=[
  ref('all','Approximating the Permanent','Mark Jerrum; Alistair Sinclair',1989,'https://doi.org/10.1137/0218077','SIAM Journal on Computing 18(6):1149–1178; includes an FPRAS for arbitrary monomer–dimer systems, distinct from unrestricted perfect-matchings counting'),
  ref('permanent','A Polynomial-Time Approximation Algorithm for the Permanent of a Matrix with Nonnegative Entries','Mark Jerrum; Alistair Sinclair; Eric Vigoda',2004,'https://faculty.cc.gatech.edu/~vigoda/Permanent.pdf','Journal of the ACM 51(4):671–697, DOI 10.1145/1008731.1008738; STOC 2001 precursor; arbitrary nonnegative permanent FPRAS'),
  ref('general','On Counting Perfect Matchings in General Graphs','Daniel Štefankovič; Eric Vigoda; John Wilmes',2018,'https://arxiv.org/abs/1712.07504','Preprint 20 December 2017; LATIN 2018, pp. 873–885, DOI 10.1007/978-3-319-77404-6_63; §§2–4, chain bottlenecks and factor-critical decomposition'),
  ref('spin','Two-State Spin Systems with Negative Interactions','Yumou Fei; Leslie Ann Goldberg; Pinyan Lu',2025,'https://arxiv.org/abs/2309.04735','v3, 17 August 2025; Information and Computation 307, 105340, DOI 10.1016/j.ic.2025.105340; Proposition 1.2 and surrounding open-status discussion; ITCS 2024 precursor'),
  ref('faster','Faster FPRAS for the Permanent via Restricted Poincaré Inequalities and Coupled Flows','Xiaoyu Chen; Eric Vigoda; Xiongxin Yang',2026,'https://arxiv.org/abs/2608.26599','v1, 27 August; Theorem 1 gives full ε and δ dependence, and §2 fixes the bipartite state space')],
 status='source_open',status_note='Checked through 10 September 2026. The general-graph question remains open in the checked primary literature. The August 2026 improvement is a permanent algorithm for bipartite graphs. Slow mixing of the particular general-graph Markov chains does not establish impossibility of all FPRAS approaches.',formulation_reviewed_on='2026-09-10')
