import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('optimal-quantitative-excluded-grid-theorem',
 id='TCS-6683',title='The optimal quantitative Excluded Grid Theorem',area='Structural graph theory',criterion='tightness',question_type='asymptotic_complexity',
 formal='For each integer r≥2, let f(r) be the least nonnegative integer t such that every finite simple undirected graph of treewidth at least t contains the r×r square grid as a minor. Determine the asymptotic order of f(r) up to universal constant factors, including the correct logarithmic dependence.',
 definitions='The r×r grid has vertex set {1,…,r}², with an edge between (i,j) and (i′,j′) exactly when |i−i′|+|j−j′|=1. It has r² vertices; r denotes side length. A graph H is a minor of G if H can be obtained by deleting vertices, deleting edges and contracting edges, after removing loops and merging parallel edges. Equivalently, a model of H consists of one nonempty connected vertex set in G for each vertex of H, all pairwise disjoint, with an edge of G joining the corresponding sets for every edge of H. Additional edges are permitted. A tree decomposition of G is a tree T with bags B_t⊆V(G), such that every vertex belongs to some bag, the endpoints of every edge belong together to some bag, and the bags containing any given vertex form a connected subtree of T. Its width is max_t |B_t|−1; treewidth tw(G) is the minimum such width. Robertson–Seymour’s Grid-Minor Theorem guarantees that f(r) is finite. The quantifier over G includes graphs of arbitrary size, degree and genus. This is an extremal existence threshold; no efficiency requirement for finding the grid model is imposed. Polylogarithmic factors mean (log r)^c for a fixed constant c, and matching bounds here must resolve such factors rather than suppress them.',
 answer_criterion='Identify an explicit asymptotic function h(r) and universal constants a,b>0 such that a h(r)≤f(r)≤b h(r) for all sufficiently large r. The upper bound must force a grid minor in every graph above the stated threshold; the lower bound must give graphs of comparable treewidth that exclude it. In particular, this determines whether f(r)=O(r²(log r)^c) for some fixed c. Merely improving a nonmatching polynomial exponent, solving the planar-host case, or replacing minors by a different containment relation is progress rather than a complete answer.',
 context=[
 paragraph('Treewidth measures how large the interacting pieces of a graph must be when organized along a tree. Many algorithms work by dynamic programming across the bags of a tree decomposition, with a strong dependence on bag size. A grid provides a canonical obstruction to small treewidth: its rows and columns create many overlapping connections that cannot be separated into very small bags. The Excluded Grid Theorem states that every graph of sufficiently large treewidth contains such an obstruction as a minor.','original'),
 paragraph('The unknown quantity is how much treewidth must be spent to force a grid of a given side length. The qualitative theorem only says that some finite threshold exists. A sharp quantitative bound would explain how efficiently general tangled connectivity can be organized into a planar grid. This is not a statement that the graph itself is planar, or that a grid must appear as an induced subgraph.'),
 paragraph('A vertex-count example already rules out a linear threshold. The complete graph on r²−1 vertices has treewidth r²−2, but cannot contain an r×r grid minor because taking a minor cannot increase the number of vertices. Thus f(r)≥r²−1. Its many edges cannot replace the need for r² disjoint nonempty branch sets in a minor model. This is why the fact that the r×r grid itself has treewidth r does not imply a linear bound for arbitrary host graphs.'),
 paragraph('The known lower bound is stronger: f(r)=Ω(r² log r). Robertson, Seymour and Thomas obtain it using bounded-degree expanders of logarithmic girth. Such graphs have treewidth proportional to their number of vertices, while every cycle is long. A large grid contains quadratically many vertex-disjoint small cycles; lifting those cycles through a minor model requires quadratically many disjoint long cycles in the host. This consumes a logarithmic factor of additional vertices.','lower'),
 paragraph('Chekuri and Chuzhoy obtain the first polynomial upper bound, replacing an enormous quantitative gap by a polynomial relationship between treewidth and grid size. Their proof is constructive: a randomized polynomial-time algorithm finds a grid model at the scale established by their theorem. This makes the result useful both as a structural guarantee and as a subroutine, although this card asks only for the optimal existence threshold.','polynomial'),
 paragraph('Chuzhoy and Tan improve the general upper bound to O(r⁹(log r)^c) for an absolute constant c. Their SODA 2019 paper, published in journal form in 2021, builds on well-linked sets and paths of connected clusters. Well-linkedness supplies many disjoint connections; the challenge is arranging them into the grid’s particular pattern without losing too much width at successive stages. The lower and upper bounds still differ by a large power of r.','best'),
 paragraph('The same paper records competing predictions: Robertson–Seymour–Thomas conjectured that the r² log r lower bound is tight, while Demaine and coauthors proposed a cubic threshold. Consequently, the catalogue target is the actual asymptotic order. A near-quadratic upper bound would be a major result, but should not be described as the only conjectured answer. Even r² times an unspecified power of log r would leave part of the present target unresolved.','best'),
 paragraph('The 2025 paper The Grid-Minor Theorem Revisited strengthens the structural description of graphs excluding a fixed planar minor. It represents them inside clique blow-ups of graphs whose treewidth is controlled by the excluded graph’s treedepth. The blow-up size is an unspecified function of the excluded graph. This gives useful product structure and colouring applications, while leaving the optimal numerical threshold f(r) undetermined.','revisited'),
 paragraph('Catching Rats in H-minor-free Graphs, presented at SODA 2026, makes another substantial refinement under an extra host-graph restriction. For a fixed excluded graph H with t vertices and Euler genus g, a graph excluding both H and the r×r grid has treewidth O(gr+t^{2304}), hence O(t²r+t^{2304}). This is linear in r when H is fixed. General graphs in our question need not exclude any fixed H, so that additional parameter cannot be treated as a universal constant.','rats'),
 paragraph('The threshold influences the quantitative strength of grid-based routing arguments, packing-versus-covering theorems and parameterized algorithms. Better bounds can improve how a large-treewidth case yields useful structure, or how a no-grid case bounds the state space for dynamic programming. A matching lower bound would be equally informative: it would identify an unavoidable loss in converting unrestricted graph connectivity into a planar obstruction.')],
 why='Determine the exact asymptotic loss when converting large treewidth into a square-grid minor, a foundational link between graph structure and algorithms.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A central quantitative problem in graph minor theory with direct implications for structural decompositions, routing, packing and parameterized algorithms.'),
 progress=[
 step('1986','Robertson–Seymour prove that sufficiently large treewidth forces any fixed planar graph, including every square grid, as a minor.','original'),
 step('1994','Robertson–Seymour–Thomas strengthen quantitative bounds; logarithmic-girth expanders give the Ω(r² log r) obstruction.','lower'),
 step('2013–2016','Chekuri–Chuzhoy obtain the first polynomial relationship, with a randomized algorithm finding a grid model; STOC 2014 and JACM 2016.','polynomial'),
 step('2019–2021','Chuzhoy–Tan prove the general O(r⁹ polylog r) upper bound; SODA 2019, Journal of Combinatorial Theory B 2021.','best'),
 step('2025-11-07','The Grid-Minor Theorem Revisited gives a qualitative product-structure strengthening, with an unspecified blow-up factor depending on the excluded planar graph.','revisited'),
 step('2026-01','Catching Rats in H-minor-free Graphs gives bounds linear in grid side length and polynomial in |V(H)| under additional exclusion of H; SODA 2026.','rats')],
 references=[
 ref('original','Graph minors. V. Excluding a planar graph','Neil Robertson; Paul D. Seymour',1986,'https://doi.org/10.1016/0095-8956(86)90030-4','Journal of Combinatorial Theory, Series B 41(1), August 1986, 92–114; qualitative Grid-Minor Theorem'),
 ref('lower','Quickly Excluding a Planar Graph','Neil Robertson; Paul D. Seymour; Robin Thomas',1994,'https://www.sciencedirect.com/science/article/pii/S0095895684710732','Journal of Combinatorial Theory, Series B 62(2), November 1994, 323–348; high-girth expander lower bound and tightness conjecture described in Chuzhoy–Tan’s introduction'),
 ref('polynomial','Polynomial Bounds for the Grid-Minor Theorem','Chandra Chekuri; Julia Chuzhoy',2016,'https://arxiv.org/abs/1305.6577','First posted 28 May 2013; checked v5, 9 August 2016; STOC 2014, JACM 63(5), Article 40, 2016; source defines the inverse function: guaranteed grid side length from treewidth'),
 ref('best','Towards Tight(er) Bounds for the Excluded Grid Theorem','Julia Chuzhoy; Zihan Tan',2021,'https://arxiv.org/abs/1901.07944','Preprint 23 January 2019; SODA 2019; JCTB 146, January 2021, 219–265; Theorem 1.1 and introduction’s lower bounds and competing conjectures; inherited reference'),
 ref('revisited','The Grid-Minor Theorem Revisited','Vida Dujmović; Robert Hickingbotham; Jędrzej Hodor; Gwenaël Joret; Hoang La; Piotr Micek; Pat Morin; Clément Rambaud; David R. Wood',2025,'https://link.springer.com/article/10.1007/s00493-025-00168-w','Combinatorica 45, Article 62, published 7 November 2025; Theorem 1 and introduction; c=c(X) is unspecified; inherited reference'),
 ref('rats','Catching Rats in H-minor-free Graphs','Maximilian Gorsky; Giannos Stamoulis; Dimitrios M. Thilikos; Sebastian Wiederrecht',2026,'https://arxiv.org/abs/2506.22857','First posted 28 June 2025; checked v2, 23 October 2025; SODA 2026, 4644–4654; treewidth/branchwidth O(gr+t^{2304}) with the additional fixed excluded minor H')],
 status='source_open',status_note='The checked general bounds remain Ω(r² log r) and O(r⁹ polylog r). The November 2025 product-structure result and SODA 2026 fixed-minor result refine different aspects and do not determine the all-graphs threshold. No matching asymptotic bounds found through 11 September 2026. The problem does not assume that either the near-quadratic or cubic conjecture is correct.',formulation_reviewed_on='2026-09-11')
