import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import dispose, ref, step

dispose('TCS-0476',kind='model_proposal',
 reason='The source proposes an extended instruction set for the word RAM. It does not pose a quantified claim about algorithms, simulation overhead, or lower bounds. The saved label should therefore not be presented as a well-defined unresolved mathematical problem.',
 formal='Model proposal: augment a w-bit word RAM with constant-cost evaluation of Boolean functions on O(w) input bits that have circuits of depth O(log w) and size O(w^2). The source motivates adopting this convention; it does not specify a proposition whose truth is unknown.',
 context='A machine model determines which operations are charged as elementary steps. The word RAM usually treats several arithmetic and bitwise operations on an entire word as constant-time instructions. An analysis in that model can therefore count a multiplication as one step even though implementing it at the bit level requires a circuit with many gates.\n\nEven’s proposal uses circuit size and depth to describe a broader class of candidate instructions. The motivation is to make the computational convention less dependent on which particular operations happen to be listed, and to avoid long simulations using the standard instruction set. This is a substantive modeling idea that can affect the interpretation of data-structure bounds.\n\nThe seminar entry nevertheless supplies no theorem to prove or refute about the proposed model. For example, an equivalence with the ordinary word RAM would be a separate question requiring explicit circuit uniformity, instruction-family, and simulation-cost conventions. The source does not fix that question, and this catalogue should not attribute it to the author by inference. The record is retained as background for model-sensitive questions, with an individual disposition rather than a fabricated open statement.',
 why='Retained because the cost of word operations is fundamental to interpreting algorithmic speedups. Excluded from the open-problem selection because defining or advocating a model is not itself an unresolved proposition with an objective answer criterion.',
 progress=[step('2021','Even proposes admitting instructions according to bounded-depth, bounded-size Boolean circuits and gives motivations for the extension. The source does not state an open simulation theorem.','primary')],
 references=[ref('primary','Scalable Data Structures (Dagstuhl Seminar 21071)','Guy Even (proposal contributor)',2021,'https://doi.org/10.4230/DagRep.11.1.1','Section 5.1: A Suggestion for the Extension of the Word RAM Model')])
