import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('connected-planar-circle-reporting-additive-output',
 id='TCS-0472',title='Can circle–segment reporting on connected planar graphs have additive output cost?',
 area='Computational geometry',criterion='tightness',question_type='yes_no',
 formal=r'''Is there a deterministic static data structure that preprocesses a connected straight-line planar graph with n >= 2 edges in $O(n\log^3 n)$ time and space and reports all k edges intersecting a query circle in $O(\log^3 n+k)$ worst-case time? The graph is embedded in the Euclidean plane: edges are nonzero closed line segments, distinct edge interiors are disjoint, and edges meet only at shared endpoints. A query supplies a center c and radius r > 0. Promise that the circle contains no graph vertex on its boundary and is tangent to no edge. Report each intersected input edge once. All hidden constants are independent of the graph, circle, and output size.''',
 definitions=r'''The query circle is the boundary $\{p:\|p-c\|_2=r\}$, not the filled disk. An edge intersects it if at least one point of that segment lies on the boundary, including when both edge endpoints are outside the disk. k counts distinct reported edges, even if one segment has two intersection points. Connectivity is that of the graph with the specified endpoints as vertices; crossing edges without a shared vertex are excluded. Use a unit-cost real RAM with exact real addition, subtraction, multiplication, division, square roots, and comparisons, together with random access and O(log n)-bit integer indices. Each stored real or integer occupies one cell; integer bit manipulation does not apply to arbitrary real values. Preprocessing includes construction of every auxiliary index. Queries return edge identifiers and use only the stored structure and the query. The target specializes the older connected-segment direction to planar input and removes a multiplicative output overhead from a later bound.''',
 answer_criterion='Construct a data structure with all three stated worst-case bounds, or prove that no such data structure exists in this model. An O((k+1) log^3 n) query bound still incurs the overhead this proposition asks to remove. Improvements only for disks, approximate answers, or a restricted family of graph embeddings do not establish the positive answer.',
 context=[
  paragraph('A large circle can enclose many graph edges while crossing very few of them. Reporting every segment inside its disk can therefore be far more expensive than the requested boundary query. There is also a second geometric obstacle: a segment can cross the circle twice while both of its endpoints are outside. An index of endpoint locations alone does not identify every answer.'),
  paragraph('Connectivity gives the search more structure. If a connected piece of the graph contains vertices on both sides of the circle, then some edge crosses the boundary. This observation suggests organizing the input into connected pieces and using geometric tests to discard pieces containing no answer. Planarity is an additional promise in this card; the graph is not an arbitrary collection of crossing segments.'),
  paragraph('The ISAAC 2025 construction makes this strategy effective using a hierarchy of connected edge subsets. Its preprocessing depends on n plus the number of edge crossings, and its reporting bound is O((k+1) log^3 n), including the empty-output case. With planar input the crossing term disappears. The remaining target here is to pay the logarithmic search overhead once per query, then only constant additional cost per reported edge.', 'isaac'),
  paragraph('This is a sharper question than the broad direction recorded at the May 2025 seminar. The later paper already demonstrates that connectivity can improve the old bounds substantially. Its final section discusses faster repeated searches and lower bounds. The precise additive-output target, fixed preprocessing budget, and nondegenerate-query promise here are editorial choices that turn that remaining direction into a yes/no proposition.', 'isaac')],
 why='Output-sensitive reporting separates the unavoidable cost of listing answers from the cost of finding them. This question asks whether connected planar structure is strong enough to achieve that separation for a curved boundary query, combining topological promises with geometric searching.',
 importance=dict(score=64,method='editorial',assessed_on='2026-09-10',reason='A focused structural reporting problem: removing per-answer search overhead would clarify the algorithmic value of connected planar input. It is narrower than general range-searching trade-off questions.'),
 progress=[
  step('2025 (May seminar)','Storandt proposes exploiting connectivity for circle–segment queries. The stored draft originally described this broad direction without a fixed remaining target.','seminar'),
  step('2025 (ISAAC)','Afshani, Bosch, and Storandt obtain O((n+C) log^3 n) preprocessing time and space for C crossings, and O((k+1) log^3 n) reporting. Thus the historical direction has substantial positive progress; Theorem 8 is not the additive-output bound asked here.','isaac')],
 references=[
  ref('seminar','Adaptive and Scalable Data Structures (Dagstuhl Seminar 25191)','Sabine Storandt (problem contributor)',2025,'https://doi.org/10.4230/DagRep.15.5.1','Section 5.7, first problem'),
  ref('isaac','Circle-Segment Intersection Queries in Connected Geometric Graphs','Peyman Afshani; Yannick Bosch; Sabine Storandt',2025,'https://doi.org/10.4230/LIPIcs.ISAAC.2025.3','Theorems 7–8 and Section 5; the +1 charges a zero-output query')],
 status='source_open',status_note='Reformulated after finding ISAAC 2025 progress. This is an explicit editorial target within the paper’s remaining reporting-time direction, not a claim that the original 2025 direction saw no progress. Searches through 10 September 2026 did not locate the stated additive-output bound.',
 formulation_reviewed_on='2026-09-10')
