import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('seven-vertex-induced-minor-detection-resolved',
 id='TCS-0589',title='Polynomial-time detection of the seven-vertex tree H* as an induced minor — resolved',
 area='Graph theory and graph algorithms',criterion='decision',question_type='yes_no',
 formal=r'''Let H* have vertex set {a₁,a₂,b,c,d,e₁,e₂} and edge set {a₁b,a₂b,bc,cd,de₁,de₂}. Is there a deterministic polynomial-time algorithm that decides, for every finite simple undirected input graph G, whether H* is an induced minor of G? Answer: yes, by Eagling-Vose, Martin, Paulusma, and Trotignon (April 2026).''',
 definitions=r'''An induced-minor model is a family of seven nonempty, pairwise disjoint vertex sets Bₓ⊆V(G), indexed by x∈V(H*). Each induced subgraph G[Bₓ] must be connected. For every two distinct x,y, an edge of G joins Bₓ to Bᵧ if and only if xy is an edge of H*. Vertices outside the bags are discarded. Equivalently, H* is obtained by deleting vertices and contracting edges; arbitrary edge deletion is forbidden. Parallel edges and loops created inside contractions are suppressed to obtain a simple graph. The seven pattern vertices are names, not prescribed terminals in G. Bags can have unbounded size. H* is fixed and is not part of the input. The input is an adjacency matrix of an n-vertex graph, with no promise of planarity, bounded degree, or exclusion of another induced subgraph. Polynomial time means at most C(n+1)^k elementary steps of a deterministic Turing machine, for fixed finite constants C and k. The question asks for membership in P, not the optimal polynomial exponent.''',
 answer_criterion='A deterministic algorithm with a polynomial worst-case running time and correctness on every input answers yes. Theorem 17 of the April 2026 paper provides such an algorithm. The historical question is therefore closed; a smaller running-time exponent would be a separate question.',
 context=[
  paragraph('The original Dagstuhl question specifies this particular seven-vertex tree: two degree-three branch vertices joined through a degree-two vertex, with two leaves at each branch vertex. Its generic saved title concealed this concrete target. Keeping the target fixed is essential: a classification for arbitrary patterns H is a larger problem, and the theorem closing this card does not settle that classification.','problem'),
  paragraph('Ordinary minors permit deletion of inconvenient edges between bags. Induced minors must preserve every adjacency among the surviving bags, so connectivity alone is insufficient. Although H* has only seven vertices, trying all seven-vertex induced subgraphs does not decide the question: a valid bag can require many vertices of G. The branch-set definition makes the exact extra obstruction visible.'),
  paragraph('Fiala, Kamiński, and Paulusma developed algorithms for star-like induced minors in 2012. Their results covered all forests with at most seven vertices except this case. Thus H* isolated a small missing boundary in a much broader family of tractable containment problems, rather than an arbitrary choice of a graph with seven vertices.','stars'),
  paragraph('The October 2025 version of Induced Minor Models II still identifies this tree as open. It expands several polynomial-time pattern families and proves tractability for any fixed pattern when the input excludes a fixed induced path. Those input-restricted results do not decide containment in an unrestricted graph.','models'),
  paragraph('The April 2026 solution first searches for models having a small branch bag. If none exists, a structural description permits a shortest-path detector to find the remaining models. The order of these steps matters: some auxiliary configurations are themselves hard to detect without the structural promise established by the first step. Together with earlier results, the solution completes polynomial-time detection for every forest on at most seven vertices.','solution')],
 why='This was the smallest unresolved forest-pattern case in induced-minor detection, a basic graph containment operation sitting between subgraph detection and ordinary minor detection. Its solution explains how forbidding unwanted cross-edges can remain algorithmically manageable. It is retained as a resolved historical benchmark, with its original identifier and source.',
 importance=dict(score=79,method='editorial',assessed_on='2026-09-10',reason='A historically important minimal missing case in a structural algorithm classification. The precise seven-vertex pattern has now been solved; its importance score records that role, while resolved status removes it from the active open-problem ordering.'),
 progress=[
  step('2012','Star-like induced-minor algorithms establish polynomial-time detection for all forests on at most seven vertices except H*.','stars'),
  step('2022 seminar / 2023 publication','Paulusma explicitly asks for the complexity of detecting H* as an induced minor in Section 4.3 of the Dagstuhl report.','problem'),
  step('2025-10','Induced Minor Models II still records the seven-vertex case as open while proving other fixed-pattern and restricted-input algorithms.','models'),
  step('2026-04','Theorem 17 gives a polynomial-time algorithm for the same pattern, denoted H₂ in the paper. Theorem 2 then covers every forest on at most seven vertices. The historical decision question has answer yes.','solution')],
 references=[
  ref('problem','Vertex Partitioning in Graphs: From Structure to Algorithms — Finding H-Induced Minors','Daniël Paulusma',2023,'https://doi.org/10.4230/DagRep.12.11.109','Dagstuhl Reports 12(11), 109–123; Section 4.3. Seminar 22481 took place in November–December 2022; report published 4 May 2023.'),
  ref('stars','Detecting induced star-like minors in polynomial time','Jiří Fiala; Marcin Kamiński; Daniël Paulusma',2012,'https://doi.org/10.1016/j.jda.2012.11.002','Journal of Discrete Algorithms 17, 74–85; earlier classification summarized in the 2025 and 2026 primary papers'),
  ref('models','Induced Minor Models. II. Sufficient conditions for polynomial-time detection of induced minors','Clément Dallard; Maël Dumas; Claire Hilaire; Anthony Perez',2025,'https://arxiv.org/abs/2501.00161v4','28 October 2025 version; introduction identifies the seven-vertex open case; fixed-P_t-free input theorem'),
  ref('solution','On Detecting H-Induced Minors for Small H','Tala Eagling-Vose; Barnaby Martin; Daniël Paulusma; Nicolas Trotignon',2026,'https://arxiv.org/abs/2604.24216v1','27 April 2026; Figure 1, Section 6 and Theorem 17 (H₂ is H* here), Theorem 2, and Section 8')],
 status='resolved',status_note='Resolved positively by Theorem 17 of Eagling-Vose, Martin, Paulusma, and Trotignon, arXiv:2604.24216v1 (27 April 2026). The full paper was checked against the exact seven-vertex pattern in the original question. The theorem concerns unrestricted input graphs and polynomial-time detection.',formulation_reviewed_on='2026-09-10')
