import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('polynomial-hierarchy-strict-at-every-level',
 id='TCS-6532',title='Is the polynomial hierarchy strict at every finite level?',
 area='Computational complexity',criterion='models',question_type='yes_no',
 formal=r'''Is $\Sigma_k^{\mathrm P}\subsetneq\Sigma_{k+1}^{\mathrm P}$ for every integer k≥0? Here Σ₀^P=P, and Σₖ^P for k≥1 consists of languages definable by k alternating blocks of polynomially bounded Boolean quantifiers, beginning existentially, followed by a deterministic polynomial-time predicate.''',
 definitions=r'''A language L is in Σₖ^P if there exist a polynomial p and a deterministic polynomial-time predicate R such that, for every binary input x, $x\in L\iff\exists y_1\in\{0,1\}^{p(|x|)}\ \forall y_2\in\{0,1\}^{p(|x|)}\cdots Q_k y_k\in\{0,1\}^{p(|x|)}:R(x,y_1,\ldots,y_k)=1$, where Qₖ is existential for odd k and universal for even k. Each yᵢ is an entire string, so k counts quantifier blocks, not individual bits. The predicate is polynomial-time in the combined input length. k is fixed for a class membership claim and cannot grow with |x|; p and R may depend on k and L. Let Πₖ^P consist of complements of Σₖ^P languages, and let PH=⋃ₖ≥0Σₖ^P. In particular Σ₁^P=NP and Π₁^P=coNP. These are uniform, unrelativized classes of total decision languages. Strictness at level k means that some language in Σₖ₊₁^P is absent from Σₖ^P. The separating language may depend on k. All classes use ordinary Turing computation with no advice or external oracle.''',
 answer_criterion='Prove strict containment at every finite level, or prove equality Σₖ^P=Σₖ₊₁^P for some fixed k. Equality at any adjacent pair collapses all higher levels to that level, so a collapse at even one finite level answers no. Proving strictness for finitely many levels or relative to an oracle does not answer yes.',
 context=[
  paragraph('NP captures a single existential choice of a certificate. A second block permits a statement of the form “there is a candidate that survives every challenge”; a third permits a response to every challenge. Polynomially many bits may be chosen at each stage. The question is whether every additional fixed stage enables some decision problem that cannot be expressed with fewer stages and a polynomial-time final check.','book'),
  paragraph('The hierarchy is monotone because unused quantifier blocks can be inserted. Its collapse property is much stronger: if two neighboring levels coincide, all later alternations can be eliminated down to that level. Consequently the target is a single binary statement, not a request to classify an unspecified collection of logical formulas.','survey'),
  paragraph('Strictness includes P≠NP at its first step, but P≠NP alone would leave the possibility of a later collapse. The conjecture also implies that PH is a proper subclass of PSPACE: if TQBF belonged to PH, it would belong to one fixed level, and PSPACE-completeness would force the whole hierarchy into that level. Allowing arbitrarily many quantifier alternations in the input is therefore a separate issue from allowing any fixed number.','book'),
  paragraph('The Karp–Lipton implication connects this conjecture to circuit complexity. Polynomial-size circuits for NP would collapse PH, so an infinite hierarchy would imply an NP language without polynomial-size circuits. Conditional collapse arguments are useful precisely because they can turn an assumption about nonuniform circuits into a conclusion about uniform classes; the conditional conclusion is not an established collapse.','book'),
  paragraph('Rossman, Servedio, and Tan prove that PH is infinite relative to a random oracle with probability one, through an average-case circuit-depth hierarchy theorem. Random membership bits supplied by an oracle are an extra computational resource. The result shows that strictness is compatible with, and typical in, that oracle model; it leaves the unrelativized hierarchy open.','oracle')],
 why='This is the organizing conjecture behind the computational cost of alternating existential and universal reasoning. It strengthens the basic P-versus-NP distinction across all fixed quantifier depths and underlies many conditional lower bounds in complexity, verification, and graph problems with nested solution requirements.',
 importance=dict(score=99,method='editorial',assessed_on='2026-09-10',reason='A foundational conjecture asserting that every further alternation increases computational power. It governs a large family of complexity classifications and has major circuit-lower-bound consequences.'),
 progress=[
  step('1970s','Meyer and Stockmeyer introduce the hierarchy; Stockmeyer develops its structural properties and complete problems.','foundation'),
  step('1980s','Oracle constructions show that all levels can be distinct in a relativized world. Karp–Lipton-type theorems connect small circuits for NP to a collapse of the unrelativized hierarchy.','survey'),
  step('2015','Rossman, Servedio, and Tan establish infinitude relative to a random oracle with probability one. Their proof comes from an average-case lower bound separating consecutive constant circuit depths.','oracle'),
  step('2025–2026','Hirsch and Volkovich study the Linear Ordering Principle, related small complexity classes, and Karp–Lipton-style conditional collapses. These are implications under hypotheses, not an unconditional collapse or separation of PH.','recent')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2019,'https://www.math.ias.edu/files/Book-online-Aug0619.pdf','6 August 2019 edition; Section 4.1, polynomial hierarchy discussion, and Section 5.2, Karp–Lipton consequence'),
  ref('foundation','The Polynomial-Time Hierarchy','Larry J. Stockmeyer',1976,'https://research.ibm.com/publications/the-polynomial-time-hierarchy','Theoretical Computer Science 3(1), 1–22; DOI 10.1016/0304-3975(76)90061-X'),
  ref('survey','The Polynomial Hierarchy, Random Oracles, and Boolean Circuits','Benjamin Rossman; Rocco A. Servedio; Li-Yang Tan',2015,'https://www.cs.columbia.edu/~rocco/Public/sigact15.pdf','SIGACT News 46(4), 50–68; Sections 1–2, formal hierarchy and relativized history'),
  ref('oracle','An Average-Case Depth Hierarchy Theorem for Boolean Circuits','Benjamin Rossman; Rocco A. Servedio; Li-Yang Tan',2015,'https://arxiv.org/abs/1504.03398','FOCS 2015, 1030–1048; probability-one random-oracle hierarchy theorem'),
  ref('recent','Upper and Lower Bounds for the Linear Ordering Principle','Edward Hirsch; Ilya Volkovich',2026,'https://eccc.weizmann.ac.il/report/2025/142/','ECCC TR25-142, Revision 1 accepted 30 March 2026; conditional collapse and circuit-lower-bound context')],
 status='source_open',status_note='Explicitly conjectured in the primary-source survey and Wigderson’s hierarchy discussion. Research through 10 September 2026 yielded no unrelativized proof of infinitude or finite collapse. Random-oracle infinitude and conditional Karp–Lipton collapses are not recorded as resolutions.',formulation_reviewed_on='2026-09-10')
