import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('unknot-recognition-in-polynomial-time',
 id='TCS-6528',title='Unknot recognition in polynomial time',area='Computational geometry and metric spaces',criterion='resources',question_type='yes_no',
 formal='Is there a deterministic Turing algorithm and a constant c such that, on every explicit combinatorial knot diagram D of encoding length N, the algorithm decides in O((N+1)^c) bit operations whether the represented knot in the 3-sphere is ambient isotopic to the unknot?',
 definitions='A knot is a tame embedding of one circle into S³; the unknot is the isotopy class of a round circle. Ambient isotopy means a continuous family of homeomorphisms of S³ starting at the identity and carrying one embedded circle to the other at its endpoint. A diagram is a generic projection with transverse double crossings and specified over/under information. Encode it by an explicitly listed connected 4-regular planar multigraph, including loops when needed, its cyclic orders of half-edges at vertices, a distinguished outer face and the overpassing pair of opposite half-edges at each crossing. Tracing the opposite pairs must give one component. A separate constant-size encoding represents the crossing-free circle. The embedding is required to be a valid sphere embedding; malformed encodings may be rejected by polynomial-time combinatorial checks. If the diagram has n crossings, a standard such encoding has O(n log(n+1)) bits. The complexity parameter is the supplied encoding length N, not the minimum crossing number among equivalent diagrams. The input is explicit rather than a compressed description of an exponentially larger diagram. No disk, simplification sequence, knot invariant, auxiliary advice or promise of triviality is supplied.',
 answer_criterion='Give a deterministic algorithm with a proved polynomial worst-case bit complexity that correctly handles both unknotted and knotted diagrams, or prove that no such algorithm exists. The requested output is a yes/no decision; producing a simplification sequence is optional. Short certificates, polynomial bounds on the existence of Reidemeister sequences, experimental performance, a quasipolynomial algorithm, or a polynomial algorithm for only a restricted diagram family do not alone settle the problem. A September 2026 preprint claims the affirmative result; this card records that claim without treating its proof as independently validated.',
 context=[
 paragraph('Status requires special care: Chad Musick’s preprint of 6 September 2026 claims a positive answer in Corollary 1. Its route is a polynomial-time construction of a locally minimal bridge presentation using compressed descriptions, followed by an existing characterization of bridge presentations of the unknot. I checked the claim and its main proof dependencies, but have not independently verified the local-minimality argument or compressed-update complexity. The card is therefore marked uncertain pending validation of this fresh claimed resolution.','claim'),
 paragraph('The underlying task is deceptively simple: determine whether a closed loop can be untangled without cutting it or passing one strand through another. A diagram can contain many crossings that are artifacts of its projection. Looking complicated does not prove knottedness, while repeatedly removing visible twists can get stuck on a diagram that still represents the unknot. The input can be deliberately chosen to frustrate familiar simplification strategies.'),
 paragraph('The chosen representation makes the computational question independent of numerical geometry. Coordinates, thickness, physical forces and drawing quality do not enter the running time. Cyclic orders record the planar embedding, and the crossing data tell us which strand passes over the other. The task concerns the topology represented by those finite combinatorial data, not the visual complexity of a particular rendering.'),
 paragraph('Hass, Lagarias and Pippenger prove that unknot recognition belongs to NP using normal-surface techniques. Informally, an unknot bounds an embedded disk, and a suitable disk can be encoded compactly through its intersections with tetrahedra in a triangulation. Large counts are stored in binary. The existence of a polynomial-size verifiable certificate gives an upper bound on nondeterministic complexity, while finding such a certificate may still require substantial search.','np'),
 paragraph('Lackenby proves that knottedness also belongs to NP, so unknot recognition lies in coNP as well. This is an unconditional theorem, unlike earlier approaches that required the generalized Riemann hypothesis. It places the problem in NP∩coNP and makes ordinary NP-completeness unlikely: an NP-hard language in coNP would imply NP=coNP. Membership in both classes does not itself give a polynomial-time decision algorithm.','conp'),
 paragraph('There is another strong certificate theorem. Lackenby proves that any n-crossing unknot diagram can be reduced to a crossing-free circle using at most (236n)¹¹ Reidemeister moves. These are local diagram changes preserving the knot type. The result bounds the length of a successful route; it does not identify which route to choose efficiently. Enumerating a branching collection of polynomial-length routes can still take exponential time.','moves'),
 paragraph('In 2021, Lackenby announced an algorithm with quasipolynomial running time. The SoCG 2025 source still describes this as an announcement, and the checked author webpage lists talks on it. I retain that attribution rather than presenting a fully checked published proof. Quasipolynomial time, of the form exp((log N)^{O(1)}), can be much smaller than exponential time while remaining above a fixed polynomial bound.','quasipoly'),
 paragraph('Practical algorithms illustrate a different kind of progress. He, Sedgwick and Spreer’s SoCG 2025 paper builds knot factorisation machinery around edge-ideal triangulations and normal-surface crushing. Their introduction notes that Regina’s unknot-recognition implementation behaves polynomially in experiments but has an exponential worst-case bound. Strong performance on a census or on difficult examples is useful evidence for implementation design, without controlling every possible input diagram.','practical'),
 paragraph('Lackenby’s July 2026 preprint gives a new algorithm through incompressible surfaces and hierarchies. For a nontrivial knot, the boundary of its exterior is incompressible; for the unknot it is compressible. This turns knot recognition into a question about surfaces in a 3-manifold. The paper’s Section 9 explicitly leaves key hierarchy-length and surface-complexity parameters unbounded in terms of the input, so it does not establish polynomial running time.','hierarchies'),
 paragraph('The central challenge is algorithmic control over global topology. A small diagram may hide the disk or decomposition that makes its type evident. Good certificates show that concise explanations exist; an efficient recognizer would show how to decide without searching an uncontrolled space of explanations. Any verified polynomial-time solution, including the new claimed one, would resolve a basic benchmark of computational topology and change how we understand this gap.')],
 why='Determine whether triviality of an explicitly given knot can be decided efficiently, a foundational test of the gap between topological certificates and algorithms.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A central algorithmic topology problem in NP∩coNP; a fresh claimed polynomial-time solution makes precise formulation and validation especially valuable.'),
 progress=[
 step('1997–1999','Hass–Lagarias–Pippenger prove NP membership using normal surfaces, with deterministic exponential-time algorithms; FOCS 1997, JACM 1999.','np'),
 step('2013–2015','Lackenby proves a polynomial bound on the number of Reidemeister moves needed to simplify an unknot, without a polynomial algorithm to find the sequence.','moves'),
 step('2016–2021','Lackenby establishes unconditional NP certificates for knottedness, placing unknot recognition in coNP; journal publication 2021.','conp'),
 step('2021','Lackenby announces quasipolynomial-time unknot recognition; retained as an announced result.','quasipoly'),
 step('2025','He–Sedgwick–Spreer present practical factorisation algorithms and explicitly distinguish empirical performance from worst-case polynomial unknot recognition.','practical'),
 step('2026-07-25','Lackenby gives a new hierarchy-based recognition algorithm; its Section 9 does not establish polynomial input-size complexity.','hierarchies'),
 step('2026-09-06','Musick’s preprint claims polynomial-time recognition via locally minimal bridge presentations. This review has not independently validated the proof.','claim')],
 references=[
 ref('np','The Computational Complexity of Knot and Link Problems','Joel Hass; Jeffrey C. Lagarias; Nicholas Pippenger',1999,'https://arxiv.org/abs/math/9807016','FOCS 1997 precursor; arXiv 3 July 1998; Journal of the ACM 46(2), 185–211, 1999; NP certificate and deterministic complexity'),
 ref('moves','A polynomial upper bound on Reidemeister moves','Marc Lackenby',2015,'https://annals.math.princeton.edu/2015/182-2/p03','Annals of Mathematics 182(2), 491–564; published online 30 July 2015; bound (236n)¹¹; preprint arXiv:1302.0180v2'),
 ref('conp','The efficient certification of knottedness and Thurston norm','Marc Lackenby',2021,'https://arxiv.org/abs/1604.00290','First posted 1 April 2016; checked final v3, 12 April 2021; Advances in Mathematics 387, Article 107796; unconditional NP membership of knottedness'),
 ref('quasipoly','Unknot recognition in quasi-polynomial time','Marc Lackenby',2021,'https://www.maths.ox.ac.uk/node/60914','Oxford seminar announcement; corroborated as an announced result in the SoCG 2025 source; full algorithmic proof not independently checked here'),
 ref('practical','A Practical Algorithm for Knot Factorisation','Alexander He; Eric Sedgwick; Jonathan Spreer',2025,'https://drops.dagstuhl.de/storage/00lipics/lipics-vol332-socg2025/html/LIPIcs.SoCG.2025.55/LIPIcs.SoCG.2025.55.html','SoCG 2025, LIPIcs 332, Article 55; Section 1 states the complexity status and explains practical versus worst-case guarantees; inherited reference'),
 ref('hierarchies','Incompressible surfaces, hierarchies and unknot recognition','Marc Lackenby',2026,'https://arxiv.org/abs/2607.23350','25 July 2026; Theorem 1.1, Corollary 1.2 and Section 9: running-time analysis leaves hierarchy length L and pattern complexity g unbounded'),
 ref('claim','Locally Minimal Bridge Presentations of Knots','Chad Musick',2026,'https://arxiv.org/abs/2609.06492','6 September 2026, v1; Theorem 1 and Corollary 1, pp. 14–15; claimed polynomial-time result, not independently validated here')],
 status='uncertain',status_note='Musick’s 6 September 2026 preprint claims a polynomial-time solution. Its correctness has not been independently established in this review, so the card is not labelled either a settled theorem or an unqualified open problem. Established certificates and earlier algorithmic results are distinguished from this new claim. Checked through 11 September 2026.',formulation_reviewed_on='2026-09-11')
