import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('explicit-polynomial-time-functions-with-superlinear-boolean-circuits',
 id='TCS-0015',title='An explicit function with no linear-size Boolean circuits',area='Computational complexity',criterion='construction',question_type='yes_no',
 formal='Does there exist a total function F:{0,1}*→{0,1}*, computable by one deterministic polynomial-time algorithm and satisfying |F(x)|=|x|, such that its unrestricted Boolean circuit complexity is not O(n)? Explicitly, for every C>0 and N≥1, must some n≥N satisfy CC(Fₙ)>Cn?',
 definitions='Fₙ is the restriction of F to n-bit inputs, with n output bits. CC(Fₙ) is the least number of gates in a directed acyclic Boolean circuit computing all these outputs exactly on every input. Each gate may compute any Boolean function of at most two input bits: the full B₂ basis, including AND, OR, XOR and negation. Input nodes, constants 0 and 1, and designated output wires are free; gates have unrestricted fan-out and there is no depth bound. Gates may be shared among outputs. The family of competing circuits is nonuniform: the circuit at one input length need have no effective relationship to circuits at other lengths. In contrast, explicitness of F means a single deterministic Turing machine outputs F(x) in at most p(|x|) steps for one fixed polynomial p, with no advice. The empty input has empty output. This card fixes a polynomial-time interpretation of the source’s broader word “explicit” and preserves its allowance of n output bits. Changing between B₂ and the usual bounded-fan-in AND/OR/NOT basis changes size by at most a constant factor.',
 answer_criterion='Exhibit one such polynomial-time function and prove that CC(Fₙ)/n is unbounded along arbitrarily large input lengths, or prove that every polynomial-time length-preserving function has O(n)-size nonuniform circuits, with the hidden constant allowed to depend on the function. A fixed bound such as 10n is insufficient. The precise target is not O(n); it does not additionally require the ratio to tend to infinity at every sufficiently large length. A superlinear single-output example would also settle the question after padding the output with zeros.',
 context=[
  paragraph('A circuit is a finite computation with a separate design for each input length. Intermediate results can be used many times, and different output bits can share the same work. This sharing is a central source of power: a lower bound for formulas, which cannot freely reuse intermediate results, need not hold for circuits. The target here leaves depth, fan-out and Boolean operations unrestricted apart from the two-input gate bound.','book'),
  paragraph('The explicitness requirement prevents a counting argument from solving the problem. There are vastly more Boolean functions than small circuits, so most functions require exponentially many gates. But describing one by its entire truth table takes exponential space, and selecting the first hard truth table by exhaustive search need not yield a polynomial-time function. We need an efficiently specified computation and a proof that every circuit for it exceeds every fixed linear bound.','book'),
  paragraph('Multi-output functions make the question especially concrete. A fixed, efficiently constructible binary matrix Aₙ defines Fₙ(x)=Aₙx over the two-element field. Its n outputs are parity sums of selected inputs. Computing every output separately can cost Θ(n²), yet a clever circuit may share partial sums across rows. Counting proves that some matrices need Ω(n²/log n) gates, but an explicit superlinear lower bound remains unknown even for this linear-algebra setting. A lower bound against XOR-only circuits would not automatically rule out smaller circuits that use nonlinear Boolean gates.','linear'),
  paragraph('The polynomial-time convention also separates this question from NP versus P/poly. The desired F already has polynomial-size circuits because its algorithm can be simulated by circuits. Showing that it lacks linear-size circuits would separate two size scales within efficient nonuniform computation; it would not establish P≠NP. Conversely, proving superpolynomial circuit lower bounds for an NP language would address a stronger resource barrier but would not by itself make that language a polynomial-time example for this card.'),
  paragraph('For one output bit, Li and Yang obtain a 3.1n−o(n) lower bound over the full two-input basis. Their functions are affine dispersers, meaning that they remain nonconstant on every sufficiently large affine subspace of the Boolean cube, and suitable examples are polynomial-time computable. The proof refines gate elimination: restrict inputs so that gates disappear while retaining enough difficulty in the restricted function. Raising the constant was a substantial advance, but any fixed constant still falls short of the present target.','liyang'),
  paragraph('Cavalar and Oliveira’s 2025 work develops another route through the fusion method and combinatorial covering problems. It translates circuit lower-bound questions into suitably defined two-dimensional covers and proves strong bounds for random graphs. The remaining challenge is obtaining the necessary explicit cover lower bounds. A reformulation that can express the desired hardness is valuable, but does not yet provide the hard polynomial-time function.','covers'),
  paragraph('Two 2026 developments clarify proof techniques. Carmosino, Dang and Jackman formalize convergent gate simplification in selected bases and construct efficient refuters for a classical parity lower bound. Their constructive proof notion concerns finding errors in proposed small circuits; it is additional structure on a lower-bound proof, rather than a superlinear size bound.','rewriting'),
  paragraph('Raz’s July 2026 revision studies natural proofs specifically for linear maps represented by matrices. Under the stated cryptographic assumptions, pseudorandom matrices with unusually small circuits obstruct large, efficiently recognizable classes of hard matrices. Different constructions yield barriers above near-linear or linear size. These are conditional restrictions on a defined proof strategy, not an impossibility theorem for proving the desired lower bound by other means.','linear')],
 why='This asks for the first unbounded improvement over linear size for an efficiently computable unrestricted circuit task. It isolates a basic gap between knowing that hard functions abound and proving hardness for one explicitly computable function.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-10',reason='A fundamental lower-bound milestone for unrestricted computation, with connections to matrix complexity, proof techniques and the limitations of nonuniform algorithms.'),
 progress=[
  step('2018','Wigderson’s Open Problem 5.8 asks for an explicit n-input, n-output function with circuit complexity not O(n).','book'),
  step('2021–2022','Li–Yang improve the general B₂ single-output lower bound to 3.1n−o(n).','liyang'),
  step('2025-03-21','Cavalar–Oliveira publish a fusion and graph-cover framework for Boolean circuit lower bounds.','covers'),
  step('2026-02-20','Carmosino–Dang–Jackman give constructive gate-elimination proofs for a classical linear lower bound in selected bases.','rewriting'),
  step('2026-07-23','Raz’s revision adds a conditional natural-proofs barrier for superlinear lower bounds on explicit linear maps.','linear')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2018,'https://www.math.ias.edu/files/mathandcomp.pdf','27 March draft, §5.2, Definition 5.1 and Open Problem 5.8, printed pages 63–66; this card fixes polynomial-time explicitness'),
  ref('liyang','3.1n − o(n) Circuit Lower Bounds for Explicit Functions','Jiatu Li; Tianqi Yang',2022,'https://eccc.weizmann.ac.il/report/2021/023/','ECCC submitted 20 February 2021, published 21 February; STOC 2022, pages 1180–1193; full fan-in-two basis and affine dispersers'),
  ref('covers','Boolean Circuit Complexity and Two-Dimensional Cover Problems','Bruno P. Cavalar; Igor C. Oliveira',2025,'https://eccc.weizmann.ac.il/report/2025/033/','Submitted 18 March, published 21 March; §1 and §§3–4; random cover lower bounds and explicit-construction obstacles'),
  ref('rewriting','Convergent Gate Elimination and Constructive Circuit Lower Bounds','Marco Carmosino; Ngu Dang; Tim Jackman',2026,'https://arxiv.org/abs/2602.17942','v1, 20 February; convergence for selected bases, failure of a similar formalization for B₂ and U₂, and a constructive classical parity lower bound'),
  ref('linear','A Note on Natural-Proofs for Super-Linear Lower Bounds for Linear Functions','Ran Raz',2026,'https://eccc.weizmann.ac.il/report/2026/008/','Revision 1, 23 July; matrix representation, Corollary 1 and the additional CCS 2025-based conditional barrier; assumptions and proof-strategy restrictions are essential')],
 status='source_open',status_note='Checked through 10 September 2026. No superlinear unrestricted Boolean circuit lower bound for a polynomial-time length-preserving function was located. The question fixes the source’s explicitness convention; recent gate-simplification, covering and conditional natural-proofs results do not furnish such an example.',formulation_reviewed_on='2026-09-10')
