import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('polynomial-time-learning-parity-with-constant-noise',
 id='TCS-6542',title='Polynomial-time learning parity with constant random noise',area='Learning theory',criterion='resources',question_type='yes_no',
 formal='For every fixed rational noise rate η with 0<η<1/2, does there exist a uniform classical randomized polynomial-time algorithm that, for every n and every secret s∈{0,1}^n, recovers s with probability at least 2/3 from independent samples (a,⟨a,s⟩⊕e), where a is uniform in {0,1}^n and e is independently Bernoulli(η)?',
 definitions='The inner product ⟨a,s⟩ is Σ_i a_i s_i modulo two, and ⊕ is addition modulo two. The unknown s is fixed throughout an execution. Each requested sample uses a fresh independent uniform vector a and an independent error bit e, with Pr[e=1]=η. The learner knows n and the fixed rate η, and receives only classical samples. It cannot choose a, request a noiseless label, identify which labels were corrupted, or make coherent quantum queries. For each fixed η the algorithm and its polynomial bound pη may depend on η, but they must be uniform in n, without advice. Every execution uses at most pη(n) bit operations and requests at most pη(n) samples; reading and storing samples is charged. Polynomially many stored bits and repeated access to stored samples are allowed. The success probability is over the example generator and the learner’s random coins, for each fixed s. The desired output is the entire secret vector, not merely a predictor with unspecified advantage. No sparsity promise is imposed on s or on a. The quantifier over fixed rational η does not demand a running-time bound uniform as η approaches 1/2 with n.',
 answer_criterion='Prove that every fixed rational η∈(0,1/2) admits a learner satisfying these guarantees, or prove that at least one such fixed rate admits no uniform randomized polynomial-time learner. An unconditional superpolynomial lower bound must cover arbitrary polynomial memory and direct access to the samples. A lower bound only for statistical-query algorithms or small-memory streaming learners does not refute the proposition. Subexponential-time algorithms, algorithms using superpolynomially many examples, and guarantees requiring vanishing noise or a sparse secret are partial results.',
 context=[
 paragraph('A parity function is among the simplest algebraic classifiers: choose a hidden subset of coordinates and return their XOR. Without label noise, sufficiently many random examples give linear equations, and Gaussian elimination recovers the secret with high probability. Independent noise changes the task from solving a consistent system to identifying which apparent equations should be trusted. Ordinary elimination mixes error bits along with the equations, so its usual exactness argument no longer applies.'),
 paragraph('The difficulty is computational rather than a lack of information. For a fixed noise rate below one half, the true secret agrees with a fresh label with probability 1−η. Every other secret agrees with probability one half under the uniform distribution on inputs. With a sufficiently large constant multiple of n examples, concentration and a union bound over the 2^n candidates identify the true secret with high probability. Exhaustively testing those candidates takes exponential time, leaving open whether their search can be avoided.','memory'),
 paragraph('At η=1/4, for example, the correct candidate has expected agreement 3/4, while every incorrect parity has expected agreement 1/2. A threshold strictly between these values separates them once enough independent samples have been collected. This simple gap explains why a polynomial sample bound alone is not the desired breakthrough. One must locate the exceptional candidate efficiently among exponentially many possibilities.'),
 paragraph('Writing the sample vectors as rows of a matrix A gives b=As+e over the binary field. The columns of A generate a random linear code, and the task becomes decoding a random noisy codeword. This connection explains the relevance to cryptography. It does not turn a worst-case NP-hardness theorem for decoding arbitrary codes into an average-case hardness theorem for the random distribution used here. Quantifiers over matrices, errors and sample counts have to survive the reduction.','worstcase'),
 paragraph('Blum, Kalai and Wasserman give a 2^{O(n/log n)}-time algorithm using a comparable subexponential number of examples for constant noise. Combining examples cancels blocks of coordinates, while the analysis controls how the combined noise approaches a fair coin. Their work also separates noise-tolerant learning from the statistical-query framework in an appropriate restricted parity regime. Thus failure of statistical-query methods cannot simply be interpreted as failure of all algorithms with access to individual examples.','bkw'),
 paragraph('Lyubashevsky answers a different sample-efficiency question: subexponential computation is possible using only n^{1+ε} examples for each fixed ε>0. The resulting running time is 2^{O(n/log log n)}. This result is directly relevant to a learner that can collect only polynomially many samples, but its time bound is still superpolynomial. Keeping the two resources visible prevents the better exponent of the many-sample algorithm from being quoted as a polynomial-sample guarantee.','samples'),
 paragraph('There are substantial unconditional lower bounds in restricted resource models. Garg, Kothari, Liu and Raz show that a streaming learner needs either Ω(n²/(1/2−η)) bits of memory or exponentially many samples, with a strong success-probability guarantee in their theorem. For fixed η, the memory alternative is quadratic, which is permitted by the polynomial-time question. This establishes a real storage cost without ruling out a general polynomial-time algorithm.','memory'),
 paragraph('Aggarwal, Gupta and Zeyong’s May 2026 hardness amplification relates success on a small fraction of instances to success on almost all instances after changing the dimension and noise parameters. Aggarwal and coauthors’ September 8 revision gives low-noise LPN hardness under simultaneous worst-case assumptions concerning decoding a code and distinguishing noisy codewords of its dual. These strengthen the understanding of hardness assumptions; neither is an unconditional proof that this learner cannot exist.','amplification'),
 paragraph('The every-secret guarantee is not an artificial extra obstacle compared with a uniform random secret. A learner can choose a uniform mask r, replace each label b by b⊕⟨a,r⟩, learn the masked secret s⊕r and remove the mask. The transformed secret is uniform while the noise law is unchanged. The central uncertainty therefore persists even when randomness in the hidden parity itself is supplied for free.')],
 why='A canonical computational learning problem where a tiny amount of independent label noise defeats the obvious algebraic method, connecting efficient learning, random-code decoding and cryptographic hardness.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A fundamental boundary between information-theoretic learnability and efficient learning, with broad consequences for noise-tolerant algorithms and cryptographic assumptions.'),
 progress=[
 step('2003','Blum–Kalai–Wasserman obtain a subexponential-time, subexponential-sample algorithm and clarify limits of the statistical-query abstraction.','bkw'),
 step('2005','Lyubashevsky obtains 2^{O(n/log log n)} time using only polynomially many samples.','samples'),
 step('2021-09-15','Garg–Kothari–Liu–Raz prove memory/sample tradeoffs for noisy parity learning; these do not exclude polynomial memory.','memory'),
 step('2026-05-12','Revised hardness-amplification results relate different success fractions and noise/dimension parameters.','amplification'),
 step('2026-09-08','Revision 1 of Towards Worst-case Hardness for Low-Noise LPN supplies conditional code/dual-code reductions; it does not prove unconditional polynomial-time hardness.','worstcase')],
 references=[
 ref('bkw','Noise-Tolerant Learning, the Parity Problem, and the Statistical Query Model','Avrim Blum; Adam Kalai; Hal Wasserman',2003,'https://www.microsoft.com/en-us/research/wp-content/uploads/2016/11/2003-Noise-Tolerant_Learning.pdf','Journal of the ACM 50(4), 506–519, July; the 2016 directory is a hosting date, not publication year'),
 ref('samples','The Parity Problem in the Presence of Noise, Decoding Random Linear Codes, and the Subset Sum Problem','Vadim Lyubashevsky',2005,'https://cseweb.ucsd.edu/~vlyubash/papers/parityproblem.pdf','APPROX/RANDOM 2005, pp. 378–389; fixed positive sample-exponent slack ε'),
 ref('memory','Memory-Sample Lower Bounds for Learning Parity with Noise','Sumegha Garg; Pravesh K. Kothari; Pengda Liu; Ran Raz',2021,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.APPROX/RANDOM.2021.60','§§1.1–1.3 and Corollary 19; the paper denotes the bias 1/2−η by ε; its numbered open conjecture concerns a sharper memory tradeoff'),
 ref('amplification','Hardness Amplification for (Sparse) LPN','Divesh Aggarwal; Rishav Gupta; Li Zeyong',2026,'https://arxiv.org/abs/2605.10056','v2, 12 May; success amplification changes dimension and noise parameters'),
 ref('worstcase','Towards Worst-case Hardness for Low-Noise LPN','Divesh Aggarwal; Rishav Gupta; Hai Hoang Nguyen; Kel Zin Tan; Prashant Nalini Vasudevan',2026,'https://eccc.weizmann.ac.il/report/2026/095/','Revision 1, 8 September; first manuscript 4 June; §1.1, joint code-decoding and dual-code distinguishing assumptions')],
 status='source_open',status_note='The primary literature checked through 11 September 2026 leaves classical polynomial-time learning at fixed constant noise open. The card asks for all fixed rational rates separately, allowing rate-dependent polynomial bounds. The September 2026 reduction is conditional; sparse, quantum-example and limited-memory models do not replace the specified problem.',formulation_reviewed_on='2026-09-11')
