import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('quantum-cycle-three-coloring-sub-log-star',
 id='TCS-0522',title='Quantum 3-coloring of cycles in o(log* n) rounds',
 area='Distributed and local algorithms',criterion='resources',question_type='yes_no',
 formal=r'''Is there a uniform quantum-LOCAL algorithm that, for every n≥3 and every identifier assignment to an n-cycle, outputs a proper 3-coloring with global probability at least 1−1/n in $T(n)=o(1+\log^* n)$ communication rounds? Every node is given n, its own identifier from [n²], and a consistent clockwise/counterclockwise orientation. Initial quantum registers are unentangled across nodes.''',
 definitions=r'''The network is a simple cycle; the orientation only identifies predecessor and successor, and communication is allowed in both directions. Nodes do not receive their numerical position in the cycle, a leader, or the list of other identifiers. They run one finite classical control program which may perform arbitrary finite local quantum computations, then exchange finite but unbounded numbers of qubits with each neighbor in each synchronous round. For a concrete uniform model, local quantum operations are finite circuits over H, T, and CNOT, fresh |0⟩ ancillas, and computational-basis measurements with adaptive classical control. Register size, message size, and local computation time are not charged, but are finite on every branch. Initially the joint quantum state is a product of local |0⟩ registers; the given classical local input may affect subsequent operations. No shared randomness, initial entanglement, or graph-dependent advice is supplied. The protocol may generate entanglement by sending qubits during its counted rounds. Every node eventually outputs one color in {1,2,3}. Success means that every cycle edge has differently colored endpoints, simultaneously. T(n) bounds all branches of the protocol, not its expected time. The little-o condition is T(n)/(1+log* n)→0 as n→∞; log* counts iterated base-2 logarithms down to at most 1. This card fixes the standard directed-cycle input variant, while allowing communication in either direction.''',
 answer_criterion='Construct such a protocol with a proof of its worst-case round bound and global success probability, or prove that no such protocol exists. A constant-round protocol would answer yes. An anonymous zero-error lower bound, a two-color lower bound, or a lower bound using unbounded-degree trees does not by itself answer this high-probability three-color cycle question.',
 context=[
  paragraph('A cycle is the simplest network in which many nearby choices must be coordinated. Two colors encode a global parity constraint, but three colors allow a much more local solution. In classical distributed computing, the exact deterministic cost of this symmetry breaking is Θ(log* n).', 'classical'),
  paragraph('Naor’s lower bound shows that classical randomization with high-probability correctness still needs Ω(log* n) rounds. Quantum messages can create correlations unavailable to classical messages, but a coloring algorithm still has to return ordinary classical colors. The question is whether those correlations allow neighboring processors to agree on a valid local pattern faster than the classical symmetry-breaking threshold. The orientation and identifiers are explicit inputs, so no lower bound may rely on their absence.', 'randomized'),
  paragraph('There is a fundamental obstacle to arguments based only on causality. Finitely dependent proper colorings exist: far-separated sets of outputs can be independent while all adjacent colors differ. Consequently, the output distribution of a hypothetical constant-round quantum coloring algorithm need not violate a general no-signaling or finite-dependence constraint. Existence of such a distribution does not provide a quantum protocol that samples it.', 'dependent'),
  paragraph('The August 2026 result attacks the quantum implementation itself using matrix-product-state structure and a teleportation-based reduction. It proves a linear lower bound for anonymous finite-qubit protocols that must always succeed. Its Section 1.4 explicitly identifies the extension to high-probability correctness as the remaining problem. That is precisely the error regime retained on this card.', 'zero'),
  paragraph('A separate July 2026 paper proves a log-star lower bound for 3-coloring rooted trees through growing-degree instances, and a linear lower bound for 2-coloring even cycles. Neither theorem handles the combination here: degree exactly two, three available colors, and small nonzero failure probability.', 'trees')],
 why='This is a canonical test of quantum advantage for a natural distributed symmetry-breaking task. A faster protocol would improve one of the basic local coordination primitives; a lower bound would have to explain a limitation of quantum realizability that mere causal consistency does not capture.',
 importance=dict(score=89,method='editorial',assessed_on='2026-09-10',reason='A central concrete benchmark for quantum distributed computation, with an elementary output condition and a sharp classical threshold. The recent zero-error breakthrough leaves the practically standard high-probability regime unresolved.'),
 progress=[
  step('1980s–1990s','Cole–Vishkin and subsequent algorithms give O(log* n) classical coloring. Linial proves a matching deterministic lower bound. These classical bounds also give a quantum upper bound by running a classical protocol.','classical'),
  step('1991','Naor proves the classical randomized ring-coloring lower bound, preserving the log-star obstruction when small failure probability is allowed.','randomized'),
  step('2016','Holroyd and Liggett construct finitely dependent colorings. These establish the barrier to deriving the desired quantum lower bound solely from finite dependence or causality.','dependent'),
  step('2026-07','Fraigniaud, Magniez, and Ziccardi give quantum lower bounds for rooted-tree 3-coloring and even-cycle 2-coloring. Their rooted-tree lower bound uses degree as a growing parameter.','trees'),
  step('2026-08','Coiteux-Roy and coauthors prove that for any fixed c≥3, anonymous quantum-PN c-coloring of an even directed n-cycle with probability 1 needs more than floor(n/2)−2 rounds. They explicitly leave high-probability correctness open.','zero')],
 references=[
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#quantum-local','Updated 23 February 2026; Coloring cycles, sub-log-star and constant-round questions'),
  ref('classical','Locality in Distributed Graph Algorithms','Nathan Linial',1992,'https://doi.org/10.1137/0221015','SIAM Journal on Computing 21(1), 193–201; cycle-coloring lower bound and matching prior upper bound. Randomized lower bound is cited separately below.'),
  ref('randomized','A Lower Bound on Probabilistic Algorithms for Distributive Ring Coloring','Moni Naor',1991,'https://doi.org/10.1137/0404036','SIAM Journal on Discrete Mathematics 4(3), 409–412; randomized ring-coloring lower bound'),
  ref('dependent','Finitely Dependent Coloring','Alexander E. Holroyd; Thomas M. Liggett',2016,'https://doi.org/10.1017/fmp.2016.7','Forum of Mathematics, Pi 4, e9; finite-dependence constructions; the August 2026 paper discusses their cycle-coloring consequence'),
  ref('trees','No Distributed Quantum Advantage for 3-Coloring Rooted Trees and 2-Coloring Even Cycles','Pierre Fraigniaud; Frédéric Magniez; Isabella Ziccardi',2026,'https://arxiv.org/abs/2607.04852v2','11 July 2026; Section 1.1.1 explains why the growing-degree rooted-tree result does not give a bounded-degree or cycle lower bound'),
  ref('zero','Distributed Quantum Algorithms Cannot Color Cycles with Probability 1','Xavier Coiteux-Roy; Maxime Flin; Carlos de Gois; Marc-Olivier Renou; Jukka Suomela; Isadora Veeren',2026,'https://arxiv.org/abs/2608.11720v1','12 August 2026; Theorem 1, Table 1, and Section 1.4 Open Questions; finite-qubit anonymous quantum-PN, success exactly 1')],
 status='source_open',status_note='The August 2026 primary paper explicitly leaves high-probability cycle 3-coloring open. Its new theorem is for anonymous nodes and success probability exactly 1, so it is not recorded as resolving this identified, bounded-error protocol question. No later resolution located through 10 September 2026.',formulation_reviewed_on='2026-09-10')
