import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('deterministic-volume-sublinear-gap',
 id='TCS-0515',title='Does sublinear deterministic volume always collapse to O(log* n)?',
 area='Distributed and local algorithms',criterion='resources',question_type='yes_no',
 formal=r'''For every locally checkable labeling problem Π on all finite graphs of some fixed maximum degree Δ, does the existence of a deterministic VOLUME algorithm A with V_A(n)=o(n) imply the existence of a deterministic VOLUME algorithm B with V_B(n)=O(1+log* n)? Algorithms know the exact size of their input graph, and node identifiers are distinct integers in {1,…,|V(G)|²}. Here V_A(n) is the maximum number of distinct vertices visited to determine one vertex’s output, over all allowed instances with at most n vertices and all requested vertices.''',
 definitions=r'''An LCL is specified by fixed Δ≥2, a fixed verification radius r≥1, finite nonempty input/output alphabets, and a finite set of permitted rooted radius-r labeled neighborhoods. Rules may inspect degrees and local ports, but not n or IDs. Instances include every finite nonempty simple undirected graph of maximum degree Δ, possibly disconnected, every input labeling and every port numbering. A labeling is valid exactly when all neighborhoods satisfy the rules. A deterministic VOLUME computation for a requested vertex v starts with v’s ID, degree, input, ports, Π and the exact |V(G)|, and visited set {v}. It may adaptively choose a visited vertex w and one of its incident ports, learning the neighbor u, its ID, degree, input and incident port names, then add u to the visited set. Arbitrary jumps to unseen IDs are forbidden. Only the number of distinct visited vertices, including v, is charged; local computation must terminate but its time and temporary space are unrestricted. Queries at different vertices run independently with no preprocessing or shared mutable state. Their outputs must jointly form a valid labeling for every input and ID assignment. Each algorithm is one finite computable program for all graph sizes. log* n is the number of iterated base-2 logarithms needed to reach at most 1; the added 1 handles small n.''',
 answer_criterion='Prove the universal implication, or specify one fixed LCL with a sublinear-volume deterministic algorithm and prove it has no O(log* n)-volume deterministic algorithm. Precisely, the latter lower bound means that for every correct B, every C>0 and every n₀, some n≥n₀ satisfies V_B(n)>C(1+log* n). This gap formulation fixes the asymptotic quantifiers without assuming an optimal algorithm or an arbitrary symbolic complexity function exists.',
 context=[
  paragraph('A processor that sees far through a narrow part of a graph can inspect much less information than one that explores an entire ball of the same radius. The VOLUME model measures that inspected information. Its adaptive exploration captures a central feature of answering a query about a huge graph without first constructing an entire solution.'),
  paragraph('Correctness still couples the answers. Independently determining the color or matching status of one vertex must agree with the answers obtained for every other vertex. The algorithm cannot save previous answers and use their accumulated state as a growing global solution. This makes a low-volume construction substantially stronger than an arbitrary sequential greedy algorithm.'),
  paragraph('Rosenbaum and Suomela ask whether there is any deterministic volume complexity strictly between iterated logarithmic and linear, and conjecture there is none. Their model supplies exact graph size and polynomially bounded identifiers. Removing these conventions changes the indistinguishability arguments, so the card keeps them explicit.', 'volume'),
  paragraph('The known small-complexity gaps leave the central interval unresolved. Randomized examples inhabit many intermediate scales, but an algorithm that follows a favorable random exploration does not automatically give a deterministic procedure that succeeds on every labeled graph. A deterministic counterexample to the proposed collapse would establish a new basic behavior.', 'landscape'),
  paragraph('July 2026 work constructs additional randomized polylogarithmic and polynomial volume complexities. Its introduction explicitly separates those results from the still-open deterministic question. The increased richness on the randomized side makes the contrast sharper while supplying no deterministic intermediate example.', 'recent')],
 why='This tests whether deterministic access to local solutions has only a tiny-information regime and an essentially global regime. Either outcome would substantially constrain the design and possible complexity classes of deterministic local computation algorithms.',
 importance=dict(score=85,method='editorial',assessed_on='2026-09-10',reason='A proposed collapse of an entire deterministic complexity interval, rather than a bound for one task. It clarifies the power of adaptive exploration and the role of randomness in local computation.'),
 progress=[
  step('2020','Rosenbaum and Suomela introduce the distance-versus-volume framework and pose the deterministic intermediate-volume question as Question 7.1. Their examples establish several randomized intermediate scales while retaining linear deterministic volume.','volume'),
  step('2021','Brandt, Grunau, and Rozhoň show that randomized local computation below o(√log n) can be sped up to deterministic O(log* n). Their results also give linear deterministic volume lower bounds for fixed-color tree-coloring tasks in the relevant bounded-degree setting. These do not cover every LCL.','lll'),
  step('2022','Grunau, Rozhoň, and Brandt close the gap between constant and iterated-logarithmic VOLUME complexity. The much larger interval above log* n remains the issue here.','landscape'),
  step('2026-02','Suomela’s updated problem list retains the question of deterministic volume strictly between iterated logarithmic and linear.','problem'),
  step('2026-07','Peng gives randomized VOLUME and LCA constructions of complexity Θ(log^k n) for positive integers k and polynomial scales up to logarithmic factors. Section 1.1 explicitly leaves the deterministic gap unresolved.','recent')],
 references=[
  ref('volume','Seeing Far vs. Seeing Wide: Volume Complexity of Local Graph Problems','Will Rosenbaum; Jukka Suomela',2020,'https://arxiv.org/abs/1907.08160v2','PODC 2020; Sections 2.1–2.2 and Question 7.1; revision 17 February 2020'),
  ref('lll','The randomized local computation complexity of the Lovász local lemma','Sebastian Brandt; Christoph Grunau; Václav Rozhoň',2021,'https://arxiv.org/abs/2103.16251v2','Revision 3 December 2021; abstract and main lower-bound/speedup results'),
  ref('landscape','The Landscape of Distributed Complexities on Trees and Beyond','Christoph Grunau; Václav Rozhoň; Sebastian Brandt',2022,'https://arxiv.org/abs/2202.04724v2','PODC 2022; Section 1.3, contribution concerning VOLUME'),
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#volume','Updated 23 February 2026; VOLUME model, LCL complexities'),
  ref('recent','New Complexity Classes in Locally Checkable Labeling for Local Computation Algorithms','Sijin Peng',2026,'https://arxiv.org/abs/2607.09626v1','10 July 2026; Section 1.1 distinguishes the open deterministic gap from Theorems 1–2 for randomized algorithms')],
 status='source_open',status_note='The July 2026 primary paper explicitly retains the deterministic gap as open. The new constructions are randomized; no deterministic resolution located through 10 September 2026.',formulation_reviewed_on='2026-09-10')
