import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('negative-partial-transpose-bound-entanglement',
 id='TCS-6518',title='Does NPT bound entanglement exist?',area='Quantum computation',criterion='characterization',question_type='yes_no',
 formal='Do there exist finite integers a,b≥2 and a bipartite density matrix ρ on ℂᵃ⊗ℂᵇ such that ρ has negative partial transpose, but ⟨ψ|(ρ^{Γ_B})^{⊗k}|ψ⟩≥0 for every integer k≥1 and every unit vector ψ of Schmidt rank at most two across (ℂᵃ)^{⊗k}:(ℂᵇ)^{⊗k}?',
 definitions='A density matrix is a positive semidefinite Hermitian matrix with trace one. In fixed local orthonormal bases, partial transpose on B is defined by (ρ^{Γ_B})_{ij,kℓ}=ρ_{iℓ,kj}. Negative partial transpose (NPT) means that ρ^{Γ_B} has at least one negative eigenvalue; it does not mean that the whole matrix is negative semidefinite. Schmidt rank is the minimum number of product vectors whose sum is ψ. Tensor powers represent independent copies of the same fixed state. A state is k-copy distillable exactly when a Schmidt-rank-at-most-two vector makes the displayed expectation strictly negative. Thus the proposed state is undistillable for every finite number of copies. Operationally, Alice and Bob may use arbitrary local quantum operations, local auxiliary systems and unlimited classical communication in both directions, but no quantum communication or additional shared entanglement. Distillability means that they can asymptotically obtain Bell pairs (|00⟩+|11⟩)/√2 at a positive rate with error tending to zero. The finite-copy criterion above is equivalent to positive distillability in this model.',
 answer_criterion='Answer yes by exhibiting, or proving existence of, one finite-dimensional NPT state satisfying the inequality for every k. Answer no by proving that every finite-dimensional NPT state has some finite k and some Schmidt-rank-at-most-two vector giving a negative expectation. Showing that for each k there exists a possibly different k-copy-undistillable NPT state is insufficient for a yes answer. No uniform bound on the required k is demanded by a no answer.',
 context=[
 paragraph('Entanglement is a property of a state, whereas distillation is an operational ability to turn many noisy shared states into nearly perfect Bell pairs. These pairs are useful because a pair, together with classical communication, can transfer an unknown qubit by teleportation. The question asks whether there is a form of entanglement that passes the necessary negative-partial-transpose test for distillation but is nevertheless permanently unusable for this particular conversion.','original'),
 paragraph('The Horodeckis established that entangled states with positive partial transpose can be bound entangled. Their obstruction survives every tensor power: a positive semidefinite partial transpose remains positive semidefinite after tensoring, so no test vector can have negative expectation. This card concerns the complementary regime, where some negative eigenvector exists already, but its Schmidt rank may be too large to provide the rank-two witness needed for a distillation protocol.','original'),
 paragraph('Low local dimension explains why a spectral test alone can be misleading in larger systems. If one party has dimension two, every vector has Schmidt rank at most two. A negative eigenvector then immediately certifies one-copy distillability. In higher dimensions, a negative eigenvector can require three or more product terms. Combining copies enlarges both local spaces and permits collective operations, creating additional opportunities to extract a useful two-dimensional entangled subsystem.'),
 paragraph('The systematic search for NPT bound entanglement dates at least to the families studied by DiVincenzo, Shor, Smolin, Terhal and Thapliyal. Their work provides evidence and reductions to structured states rather than a proof of an all-copy counterexample. Such reductions matter because the original statement quantifies over all finite dimensions and all density matrices; symmetry can expose a tractable algebraic problem inside that enormous search space.','evidence'),
 paragraph('A canonical family is ρ_W(d,α)=(I+αF)/(d²+αd), where d≥3, −1≤α≤1 and F swaps the two d-dimensional systems. These Werner states are NPT exactly when α<−1/d, and one-copy distillable exactly when α<−1/2. Consequently the interval −1/2≤α<−1/d consists of particularly important candidates. It is nonempty for d≥3. The endpoint α=−1/2 is NPT even though its minimum expectation on rank-two vectors is zero.','two'),
 paragraph('Several July 2026 papers prove that the one-copy and two-copy thresholds for Werner states coincide. Fraser and coauthors obtain this from a rank-constrained partial-trace inequality, with no Hermiticity or positivity assumption on the coefficient matrix. These results include the formerly open two-ququart example ρ_W(4,−1/2). They remove a major finite-copy obstacle, but do not prove that any particular NPT Werner state is undistillable for every number of copies.','trace'),
 paragraph('A two-copy proof cannot simply be iterated. In the corresponding matrix formulation, taking a partial trace can increase rank; tensor products also need not preserve the relevant positivity property. Bharti, Gajjala and Haug make these obstacles explicit while giving restricted many-copy extensions. Likewise, a sequence of examples that resists progressively larger numbers of copies can approach the PPT boundary without yielding one fixed NPT state that resists all of them.','extensions'),
 paragraph('Wu and Zou’s subsequent three-copy analysis proves endpoint nonnegativity for the normal rank-two coefficient sector, among other restricted sectors, and studies genuinely nonnormal cases separately. It does not settle the unrestricted three-copy question, much less the all-copy target. The distinction makes the remaining challenge concrete: control every admissible rank-two witness across the full collection of copies, rather than only witnesses with a convenient internal structure.','three')],
 why='A defining question about whether partial-transpose negativity completely captures the possibility of converting bipartite entanglement into useful Bell pairs. Its precise all-copy quantifier connects quantum resource theory to tensor-stable matrix inequalities.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A central structural boundary in entanglement theory, with canonical finite-dimensional candidates and consequences for what quantum correlations can accomplish under local operations.'),
 progress=[
 step('1998','The Horodeckis prove the partial-transpose obstruction and establish bound entanglement in the PPT regime.','original'),
 step('2000','DiVincenzo and coauthors develop structured NPT candidates and evidence for undistillability.','evidence'),
 step('2026-07-23','Fu–Gao–Park submit a proof of the exact two-copy threshold for all Werner dimensions; v2 follows on 27 July.','two'),
 step('2026-07-27','Fraser–Huber–Pozsgay–Vona derive the threshold from a general rank-constrained partial-trace inequality.','trace'),
 step('2026-07-27','Bharti–Gajjala–Haug give another two-copy proof and restricted finite-copy extensions, explicitly retaining the all-copy question.','extensions'),
 step('2026-07-31','Wu–Zou prove three-copy endpoint inequalities for specified coefficient-operator sectors; the general problem remains unresolved.','three')],
 references=[
 ref('original','Mixed-state entanglement and distillation: is there a “bound” entanglement in nature?','Michał Horodecki; Paweł Horodecki; Ryszard Horodecki',1998,'https://arxiv.org/abs/quant-ph/9801069','Physical Review Letters 80, 5239–5242; necessity of NPT for distillation'),
 ref('evidence','Evidence for Bound Entangled States with Negative Partial Transpose','David P. DiVincenzo; Peter W. Shor; John A. Smolin; Barbara M. Terhal; Ashish V. Thapliyal',2000,'https://arxiv.org/abs/quant-ph/9910026','Physical Review A 61, 062312; candidate families and positive-map reformulation'),
 ref('two','A solution to 2-copy distillability of Werner states','Jinshi Fu; Li Gao; Sang-Jun Park',2026,'https://arxiv.org/abs/2607.21367','v2, 27 July; introduction gives the Schmidt-rank criterion and Werner thresholds; Theorem 1.1 settles two copies'),
 ref('trace','On the two-copy distillability of Werner states and a new partial trace inequality','Thomas C. Fraser; Felix Huber; Balázs Pozsgay; István Vona',2026,'https://arxiv.org/abs/2607.24309','v1, 27 July; Theorem A and Corollaries B–C; PDF dated 28 July'),
 ref('extensions','Two-copy nondistillability of Werner states: sharp partial-trace inequalities and finite-copy extensions','Kishor Bharti; Rishikesh Gajjala; Tobias Haug',2026,'https://arxiv.org/abs/2607.24479','v1, 27 July; all-copy reformulations and obstacles to induction'),
 ref('three','Sharp Plucker Geometry for Three-Copy Werner Distillation','Tianhao Wu; Qiran Zou',2026,'https://arxiv.org/abs/2608.02647','v1, submitted 31 July; restricted three-copy coefficient-operator sectors')],
 status='source_open',status_note='The all-copy NPT bound-entanglement question remains explicitly open in the July 2026 primary sources. New two-copy solutions and restricted three-copy progress do not settle this formulation. Reviewed through 11 September 2026.',formulation_reviewed_on='2026-09-11')
