import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import dispose, ref, step

dispose('TCS-0485',kind='duplicate',duplicate_of='TCS-0310',
 reason='Duplicate of TCS-0310. The seminar entry links directly to Monet’s original weighted-falsifiability question, also used by the earlier catalogue record. It introduces no different formula class, weight encoding, or complexity target.',
 formal='This source pointer refers to the weighted falsifiability of unambiguous DNFs. The full statement, binary-weight convention, decision target, progress, and importance assessment are on TCS-0310. This retained record is not counted as a second mathematical problem.',
 context='The catalogue originally acquired this topic by two routes. TCS-0310 came from Antoine Amarilli’s maintained list, under weighted falsifiability of unambiguous DNFs. TCS-0485 came from the 2024 Dagstuhl report on database representation, provenance, and explanations. Inspecting the latter’s Section 6.1 shows that its entire problem contribution is a pointer to Monet’s question numbered 53733 on Theoretical Computer Science Stack Exchange.\n\nThat original question supplies an explicitly listed unambiguous DNF, binary-encoded nonnegative integer weights, and an objective maximizing the weight of an assignment that falsifies the formula. It also gives the equivalent threshold decision formulation. Amarilli’s entry links to the same question and describes the same computational task. Using an at-least threshold instead of a strict integer threshold only shifts the threshold by one; it does not create a separate complexity question.\n\nThe overlap was checked through the primary link rather than inferred from similar titles. The seminar record does not introduce a special graph representation, a different source of weights, or a restriction that would merit its own card. Its provenance remains useful as evidence that the problem was discussed at the seminar. The original ID is therefore retained, along with its bibliography and any personal browser notes, and its related-card link leads to the completed canonical formulation. Any future refinement with a substantively different mathematical target should be stated explicitly before being counted separately.',
 why='The question’s significance is explained on TCS-0310. Keeping this bibliographic pointer preserves provenance, while marking the duplicate prevents repeated appearances from inflating the collection’s number of distinct problems.',
 progress=[step('2024','Section 6.1 identifies the problem solely by a link to Monet’s question 53733.','seminar'),step('2026-09-10','The primary links and formulations were compared individually; the complete card is TCS-0310.','monet')],
 references=[
  ref('seminar','Representation, Provenance, and Explanations in Database Theory and Logic (Dagstuhl Seminar 24032)','Mikaël Monet',2024,'https://doi.org/10.4230/DagRep.14.1.49','Section 6.1'),
  ref('monet','Is this problem on unambiguous DNFs hard?','Mikaël Monet',2024,'https://cstheory.stackexchange.com/questions/53733/is-this-problem-on-unambiguous-dnfs-hard','Original formulation linked from both source routes'),
  ref('list','Weighted falsifiability for unambiguous DNFs','Antoine Amarilli',2026,'https://a3nm.net/work/research/questions/#weighted-falsifiability-for-unambiguous-dnfs','Source of canonical catalogue ID TCS-0310; accessed 10 September 2026')])
