import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('constant-improvement-over-two-unrelated-makespan',
 id='TCS-6638',title='A constant improvement over factor 2 for unrelated-machine makespan',area='Scheduling and packing',criterion='resources',question_type='yes_no',
 formal='Does there exist a constant ε with 0<ε<1 and a deterministic polynomial-time algorithm which, for every unrelated-machine scheduling instance, assigns all jobs to machines with makespan at most (2−ε)OPT?',
 definitions='An instance consists of m≥1 machines, n≥0 independent jobs, and an explicitly given m×n matrix of processing times pᵢⱼ in the nonnegative rationals or ∞. Rational numerators and denominators are binary encoded; ∞ forbids an assignment. Every job has at least one finite processing time. A schedule is a function σ:{1,…,n}→{1,…,m} with p_{σ(j),j}<∞. Its makespan is Cmax(σ)=maxᵢ Σ_{j:σ(j)=i} pᵢⱼ, and OPT is the minimum of this quantity over all feasible schedules. Jobs are available at time zero, indivisible and processed without interruption on one machine; there are no precedence constraints or communication costs. Jobs assigned to one machine can run consecutively in any order. The algorithm must output σ, not merely an estimate of OPT. Its bit running time is polynomial in the entire input length. ε and the polynomial are independent of m, n and all processing times; no predictions or promises on matrix structure are supplied. Empty or zero-optimum instances require makespan zero.',
 answer_criterion='Give one fixed ε>0, an algorithm and a proof of the guarantee for every input, or prove no such deterministic polynomial-time algorithm exists. A hardness result under P≠NP or another hypothesis must state that condition. A ratio 2−1/m, an instance-dependent improvement, a quasi-polynomial-time algorithm, or a result requiring accurate predictions does not resolve the stated question. A randomized guarantee is a distinct algorithmic variant unless derandomized.',
 context=[
  paragraph('Each job can have a completely different processing time on each machine. There need not be a single ranking from fastest to slowest machines, as in the related-machine model. The challenge is to balance total load while respecting which assignments are expensive or forbidden. Even when every job has an individually attractive machine, sending all jobs to their favorite machines can create a severe bottleneck.'),
  paragraph('Lenstra, Shmoys and Tardos obtain a polynomial-time factor-2 approximation by rounding a fractional assignment. For a candidate makespan T, assignments with pᵢⱼ>T are forbidden; the relaxation divides each job fractionally among the remaining machines while bounding each machine’s fractional load by T. Their rounding can charge the overload to at most one additional job per machine. Since every eligible job fits individually within T, the resulting schedule has load at most 2T.','lst'),
  paragraph('The same foundational work establishes NP-hardness of approximation below 3/2. This leaves a genuine gap: the known hardness is compatible with an algorithm of ratio 1.9, 1.75 or 1.5. Moreover, Shchepin and Vakhania improve the general guarantee to 2−1/m. That is strictly less than two for each finite number of machines, but it approaches two as m grows. The ε in this question must be one fixed positive constant, so this refinement is not a resolution.','rounding'),
  paragraph('A stronger relaxation uses configurations: a variable represents an entire subset of jobs that fits on one machine within T. This remembers much more local packing structure than individual fractional assignments. Nevertheless, Verschae and Wiese construct an integrality gap approaching two even when each job is eligible on at most two machines. Thus rounding this relaxation solely against its own optimum cannot prove a universal constant improvement. This is a limitation of the relaxation, not a hardness theorem for all algorithms.','gap'),
  paragraph('Restricted assignment is a special case in which job j has one processing time pⱼ on all eligible machines. It is substantially more structured than arbitrary unrelated processing times. Bamas and coauthors obtain a polynomial-time (1.75+δ)-approximation for the further restriction to two finite job sizes. Their general two-value unrelated-machine result instead gives 2−1/nᵟ for fixed δ>0, whose improvement still depends on instance size. Neither guarantee extends to the full target here.','reduction'),
  paragraph('The same SODA 2024 paper gives a formal connection to the Santa Claus allocation problem, where indivisible resources must be distributed to maximize the least satisfied player’s additive value. A (2−1/α)-approximation for makespan, for constant α≥2, would yield an (α+δ)-approximation for general Santa Claus for any fixed δ>0. Thus even a small fixed improvement here would also resolve a major constant-factor approximation question in fair allocation.','reduction'),
  paragraph('Baba, Bampis and Mitropoulos’ June 2026 preprint studies predictions of assignments for heavy jobs. For accurate predictions their algorithm approaches factor one, while its worst-case guarantee with arbitrary prediction error remains two. This identifies valuable information that helps scheduling, but the classical question supplies no such information. A worst-case proof cannot assume that a learned assignment resembles an optimal schedule.','predictions'),
  paragraph('The fundamental issue is whether indivisibility forces an approximation barrier at two, or whether a stronger global argument can control the interactions that fractional rounding loses. Progress would clarify both the power of optimization relaxations and the complexity of balancing heterogeneous resources.')],
 why='A defining unresolved approximation barrier in scheduling. Beating two by any fixed constant would also imply a constant approximation for general Santa Claus allocation, while known relaxation gaps rule out a large family of straightforward proofs.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A decades-old central scheduling problem with a large hardness gap, robust LP barriers and formal consequences for fair allocation.'),
 progress=[
  step('1987–1990','Lenstra–Shmoys–Tardos establish a polynomial-time factor-2 approximation and hardness below 3/2 unless P=NP.','lst'),
  step('2005','Shchepin–Vakhania achieve 2−1/m. The saving vanishes as the number of machines grows.','rounding'),
  step('2010','Verschae–Wiese show that the configuration LP has integrality gap two even for unrelated graph balancing.','gap'),
  step('2023–2024','Bamas and coauthors reduce constant-factor Santa Claus approximation to a constant improvement over two for unrelated makespan, and give stronger special-case algorithms.','reduction'),
  step('2026-06-11','Baba–Bampis–Mitropoulos obtain improved prediction-sensitive guarantees with worst-case factor two; the unconditional classical barrier remains.','predictions')],
 references=[
  ref('lst','Approximation Algorithms for Scheduling Unrelated Parallel Machines','Jan Karel Lenstra; David B. Shmoys; Éva Tardos',1990,'https://ir.cwi.nl/pub/18055','Mathematical Programming 46:259–271, DOI 10.1007/BF01585745; FOCS 1987 precursor; LP rounding and 3/2 hardness'),
  ref('rounding','An optimal rounding gives a better approximation for scheduling unrelated machines','Evgeny V. Shchepin; Nodari Vakhania',2005,'https://www.sciencedirect.com/science/article/abs/pii/S0167637704000690','Operations Research Letters 33(2):127–133, March 2005; DOI 10.1016/j.orl.2004.05.004; factor 2−1/m'),
  ref('gap','On the Configuration-LP for Scheduling on Unrelated Machines','José Verschae; Andreas Wiese',2010,'https://arxiv.org/abs/1011.4957','v1, 22 November; integrality gap two for the configuration LP, including unrelated graph balancing'),
  ref('reduction','Santa Claus meets Makespan and Matroids: Algorithms and Reductions','Étienne Bamas; Alexander Lindermayr; Nicole Megow; Lars Rohwedder; Jens Schlöter',2024,'https://arxiv.org/abs/2307.08453','SODA 2024, pp. 2829–2860, DOI 10.1137/1.9781611977912.100; Theorem 1, Theorem 2 and special-case corollaries; preprint 17 July 2023'),
  ref('predictions','Learning-Augmented Approximation for Unrelated-Machines Makespan Scheduling','Kaito Baba; Evripidis Bampis; Giorgos Mitropoulos',2026,'https://arxiv.org/abs/2606.13133','v1, 11 June; Theorem 5.2 and Corollary 5.4; fixed search budget gives polynomial time, with robust factor two')],
 status='source_open',status_note='Checked through 10 September 2026. The full worst-case constant-improvement question remains open in the checked primary literature. The known 2−1/m ratio and prediction-assisted results have different quantifiers from the fixed-ε target. The 3/2 hardness is conditional on P≠NP.',formulation_reviewed_on='2026-09-10')
