import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('information-theoretic-classical-quantum-verification',
 id='TCS-6580', title='Information-theoretic classical verification of quantum computation',
 area='Quantum computation', criterion='models', question_type='yes_no',
 formal='Does there exist a uniform interactive protocol (P,V) for the following promise problem? Input is an explicit quantum circuit C over {H,T,CNOT}, starting on all-zero qubits, with one designated output bit and binary description length N. Let p(C) be the probability of output 1. YES instances have p(C)≥2/3 and NO instances have p(C)≤1/3. V is a classical probabilistic polynomial-time algorithm and the honest P is a quantum polynomial-time algorithm; they exchange only classical messages. On every YES instance, Pr[V accepts after interacting with P]≥2/3. On every NO instance, for every computationally unbounded cheating prover P*, Pr[V accepts after interacting with P*]≤1/3. Both honest running times, the number of rounds and total communication must be polynomial in N.',
 definitions='H is the Hadamard gate, T=diag(1,exp(iπ/4)), and CNOT is controlled NOT. The circuit explicitly specifies its qubits and gates, with at most N qubits. The promise excludes intermediate acceptance probabilities; no answer is required there. The two parties know C. The verifier may use private classical random coins, but has no trusted quantum memory, operations or measurements. The honest prover starts without an input-dependent advice state and uses a uniform polynomial-size quantum computation with classical control. All communication is through a single classical interface to one prover. Soundness quantifies over arbitrary adaptive response strategies with no computational bound; probabilities include the verifier’s coins and any prover randomness or measurements. There is no trusted setup, shared secret, second noncommunicating prover or cryptographic assumption. Fixed constant completeness and soundness gaps are the target; no constant-round requirement is imposed. This circuit promise problem expresses verification for arbitrary BQP computations.',
 answer_criterion='Construct such a protocol and prove its completeness, information-theoretic soundness and honest-party efficiency, or prove that none exists. A cryptographically sound argument against efficient cheaters, an interactive proof requiring a superpolynomial-time honest prover, or a protocol with quantum verifier operations does not meet the specification. A lower bound for a restricted number of rounds or a particular construction does not refute all polynomial-round protocols.',
 context=[
  paragraph('A user who can run only classical computations would like to check the answer returned by a quantum computer. Repeating the same claimed computation on the same untrusted device gives no independent reason to trust it. Interactive verification instead lets the user issue challenges whose answers constrain whether the reported result is correct. The survey by Gheorghiu, Kapourniotis and Kashefi organizes approaches according to what the verifier can do and which resources or assumptions establish trust. This card fixes the most restrictive physical verifier: entirely classical.','survey'),
  paragraph('The usual inclusion BQP⊆IP does not settle the question. Since quantum polynomial time is contained in polynomial space, Shamir’s IP=PSPACE theorem supplies a classical interactive proof with an unrestricted prover. However, a proof system whose honest prover must carry out much harder auxiliary computations cannot be implemented merely by running the quantum computation being certified. Requiring the honest prover to be quantum polynomial time is therefore substantive.','shamir'),
  paragraph('Aharonov, Ben-Or, Eban and Mahadev show that a verifier with a small quantum register can verify arbitrary efficient quantum computations. Quantum authentication lets a weak client protect data while delegating its processing. This demonstrates that a very limited quantum capability can be enough, but its communication and trusted operations do not satisfy the all-classical interface specified here. Their 2017 paper supplies the completed journal treatment of work first reported in 2008.','quantumverifier'),
  paragraph('Reichardt, Unger and Vazirani provide another route: a classical verifier interacts with separated quantum devices sharing entanglement. Correlations in nonlocal games can force the devices to implement the required states and measurements. Isolation is crucial because it prevents the devices from coordinating arbitrary answers during the test. Combining both devices into one freely communicating prover removes that constraint, so the multiprover result cannot simply be reused for this card.','ruv'),
  paragraph('Mahadev’s 2018 breakthrough gives classical verification with one efficient quantum prover under the hardness of Learning With Errors for quantum algorithms. Cryptographic structure conceals information needed to cheat in the measurement tests. Its soundness is computational: the theorem protects against efficiently implementable attacks under the assumption. The present question deliberately quantifies over unbounded cheating strategies, which may break the underlying cryptography.','mahadev'),
  paragraph('Recent work continues to refine these neighboring models. Kalai, Khurana and Raizes’s February 2026 construction verifies computations using one reusable QMA witness without destroying it, with negligible errors under post-quantum LWE. This is useful when the input quantum state cannot be copied. It retains the computational soundness assumption and therefore does not supply an unconditional protocol for the simpler BQP target here.','cat'),
  paragraph('Kashefi, Leichtle, Music and Ollivier’s May 2026 journal article achieves information-theoretic verification without trusted state preparations or measurements. Its client still applies trusted quantum gates: one construction uses single-qubit Z rotations and bit flips. Removing two particular hardware requirements is meaningful progress, but a client performing these gates is not a purely classical verifier.','gates'),
  paragraph('Aaronson, Natarajan, Tal and Villányi explicitly retain the single-prover question in April 2026. They prove BQP^O⊆MIP^O for every classical oracle O using an exponentially long classical proof queried in polynomially many locations. Their theorem concerns multiple classical provers and does not establish efficient honest provers. Relativization is proposed as a way to investigate the difficulty, rather than as an equivalence that resolves it.','mip')],
 why='This asks whether efficient quantum computation has an equally efficient, purely classical way to establish trust without computational hardness assumptions or isolated extra devices. A resolution would identify a basic boundary between producing quantum answers and certifying them.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A central quantum-complexity question connecting interactive proofs, delegation and the minimum resources needed to verify computations beyond classical simulation.'),
 progress=[
  step('1992','Shamir proves IP=PSPACE. Combined with BQP⊆PSPACE this gives interactive proofs, without guaranteeing quantum-polynomial-time honest provers.','shamir'),
  step('2012-09-03','Reichardt, Unger and Vazirani release their detailed classical-control protocol using separated entangled quantum devices.','ruv'),
  step('2017-04-14','Aharonov, Ben-Or, Eban and Mahadev release the completed treatment of interactive proofs with a verifier holding a few qubits; the original work dates to 2008.','quantumverifier'),
  step('2018-04-03','Mahadev introduces classical single-prover verification whose soundness relies on quantum hardness of LWE; presented at FOCS 2018.','mahadev'),
  step('2026-02-09','Kalai, Khurana and Raizes construct witness-preserving classical verification with negligible errors under post-quantum LWE.','cat'),
  step('2026-04-13','Aaronson, Natarajan, Tal and Villányi prove a relativizing multiprover containment and explicitly retain unconditional, efficient single-prover verification as open.','mip'),
  step('2026-05-07','Kashefi, Leichtle, Music and Ollivier publish verification using trusted gates without trusted preparation or measurement; the preprint first appeared in March 2024.','gates')],
 references=[
  ref('survey','Verification of quantum computation: An overview of existing approaches','Alexandru Gheorghiu; Theodoros Kapourniotis; Elham Kashefi',2018,'https://arxiv.org/abs/1709.06984','Survey v2, 9 July 2018; Theory of Computing Systems, DOI 10.1007/s00224-018-9872-3; classification by verifier capabilities and assumptions'),
  ref('shamir','IP = PSPACE','Adi Shamir',1992,'https://doi.org/10.1145/146585.146609','Journal of the ACM 39(4):869–877; unrestricted-prover interactive-proof characterization'),
  ref('quantumverifier','Interactive Proofs for Quantum Computations','Dorit Aharonov; Michael Ben-Or; Elad Eban; Urmila Mahadev',2017,'https://arxiv.org/abs/1704.04487','14 April 2017 journal-version manuscript; verifier with a small quantum register; original 2008 work and ICS 2010 presentation'),
  ref('ruv','A classical leash for a quantum system: Command of quantum systems via rigidity of CHSH games','Ben W. Reichardt; Falk Unger; Umesh Vazirani',2012,'https://arxiv.org/abs/1209.0448','3 September 2012 full proof; classical control of separated entangled subsystems'),
  ref('mahadev','Classical Verification of Quantum Computations','Urmila Mahadev',2018,'https://arxiv.org/abs/1804.01082','FOCS 2018; initial preprint 3 April 2018, current v3 8 December 2023; measurement protocol and LWE-based soundness'),
  ref('cat','How to Classically Verify a Quantum Cat without Killing It','Yael Tauman Kalai; Dakshita Khurana; Justin Raizes',2026,'https://arxiv.org/abs/2602.09282','Preprint v1, 9 February 2026; one-copy QMA witness preservation under post-quantum LWE'),
  ref('gates','Verification of Quantum Computations Without Trusted Preparations or Measurements','Elham Kashefi; Dominik Leichtle; Luka Music; Harold Ollivier',2026,'https://advanced.onlinelibrary.wiley.com/doi/10.1002/qute.202501018','Advanced Quantum Technologies 9(5):e01018, 7 May 2026; trusted-gate constructions; preprint arXiv:2403.10464'),
  ref('mip','A Relativizing MIP for BQP','Scott Aaronson; Anand Natarajan; Avishay Tal; Ági Villányi',2026,'https://arxiv.org/abs/2604.11952','Preprint v1, 13 April 2026; §1 open doubly efficient single-prover question, Theorems 1–2, §2 future work')],
 status='source_open', status_note='Checked through 10 September 2026. The April 2026 primary paper explicitly leaves this single-prover, information-theoretic question open. The May 2026 trusted-gate result changes verifier resources, and the February 2026 witness-preserving protocol retains LWE. Neither meets this card’s classical-verifier and unbounded-cheater requirements.', formulation_reviewed_on='2026-09-10')
