import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('optimal-asymptotic-binary-code-rate-distance-function',
 id='TCS-1010',title='The optimal asymptotic binary rate–distance tradeoff',area='Coding and information theory',criterion='tightness',question_type='exact_value',
 formal='Determine R₂(δ)=limsupₙ→∞ (1/n)log₂ A₂(n,⌈δn⌉) for every fixed real δ∈(0,1/2), where A₂(n,d) is the largest size of a binary length-n code with minimum Hamming distance at least d.',
 definitions='A code C is any nonempty subset of {0,1}ⁿ; it need not be linear or efficiently encodable or decodable. The Hamming distance d_H(x,y) is the number of coordinates on which x and y differ. Require d_H(x,y)≥d for every pair of distinct codewords x,y∈C; a singleton satisfies this condition vacuously. A₂(n,d) is the maximum of |C| over all such subsets. A code has rate (log₂|C|)/n, measured in information bits per transmitted bit, and relative distance d/n. The ceiling fixes integer rounding. The limsup permits code families on a subsequence of blocklengths; existence of a full limit is not assumed. δ is fixed before n grows. All logarithms in this card are base two unless stated otherwise. The binary entropy function is h₂(t)=−t log₂t−(1−t)log₂(1−t), with 0 log₂0=0. The endpoint regimes are known: R₂(0)=1 and R₂(δ)=0 for 1/2≤δ≤1.',
 answer_criterion='Identify the function R₂ by matching upper and lower asymptotic bounds at every δ∈(0,1/2). For a proposed value r at a fixed δ, prove that for every ε>0 there are arbitrarily large n with a code of size at least 2^{n(r−ε)} and distance at least ⌈δn⌉, and that for every ε>0 all sufficiently large n admit no such code larger than 2^{n(r+ε)}. A nonconstructive existence proof is acceptable; polynomial-time construction and decoding are additional questions. Restating the maximum over all codes or the defining limsup is not a determination of its value. A polynomial-factor improvement in code size, or a bound for linear codes alone, does not resolve the full tradeoff.',
 context=[
  paragraph('A binary code represents messages by selected bit strings. Keeping codewords far apart lets a receiver distinguish them after errors, while selecting many codewords increases the amount of information carried by each transmitted block. The rate–distance function asks for the best possible compromise, allowing every conceivable code. It is therefore an information-theoretic limit that must be understood before asking how efficiently an optimal code can be built or decoded.','vadhan'),
  paragraph('For a small example, the repetition code {000,111} has rate 1/3 and distance three, so it corrects one arbitrary flipped bit. The full set of eight three-bit strings has rate one and distance one, so it cannot correct even one arbitrary flip. Generally, disjoint Hamming balls of radius t around codewords are necessary and sufficient for unique correction of every pattern of at most t errors; this requires minimum distance at least 2t+1.'),
  paragraph('The Gilbert–Varshamov bound guarantees R₂(δ)≥1−h₂(δ). A maximal distance-d code covers the cube by balls of radius d−1, because otherwise another codeword could be inserted. Comparing the cube’s size with the volume of these balls gives the lower bound. In contrast, disjoint balls of radius roughly d/2 give the elementary Hamming upper bound 1−h₂(δ/2). The different radii create a genuine asymptotic gap.','vadhan'),
  paragraph('McEliece, Rodemich, Rumsey and Welch’s 1977 linear-programming bounds greatly sharpen the converse. The first gives R₂(δ)≤h₂(1/2−√(δ(1−δ))); the second also uses constant-weight restrictions and is never weaker. The argument constrains a code’s distribution of pairwise distances through positivity relations, extracting information that a volume count loses. These were the long-standing general benchmarks, but they are no longer the strongest reported bounds after August 2026.','mrrw'),
  paragraph('Alrabiah and Guruswami’s August 2026 preprint uses classical-input, quantum-output channels to prove stronger bounds for classical binary codes, including nonlinear codes. Mixed-qubit channels strictly improve the first MRRW bound, and a masked version strictly improves the second throughout 0<δ<1/2. Quantum states enter the converse proof as an analytical tool; the codes whose sizes are bounded still consist of ordinary bit strings. The result narrows the gap without matching the Gilbert–Varshamov lower curve.','cq'),
  paragraph('Barg’s September 2026 note explains the relationship between this channel argument and a concurrent Delsarte-certificate proof. For the improvement of the first bound, he shows that the two variational expressions coincide. The geometric change is to associate a moving subspace, rather than a single vector, with each codeword, allowing a stronger packing argument. This provides a further derivation and interpretation of the new bound; it does not establish the exact rate function.','barg'),
  paragraph('Lower-bound improvements require equally careful interpretation. Jiang and Vardy improve the finite-length Gilbert bound by a factor proportional to n in the fixed-distance regime they cover. Yuan and Zhu’s January 2026 preprint gives a concise probabilistic proof of a square-root-n improvement for linear codes and extends the method to quantum codes; the classical square-root factor had predecessors. After taking log₂ and dividing by n, any polynomial multiplicative factor contributes only O(log n/n). Such refinements do not increase the leading rate exponent.','gv2026'),
  paragraph('Changing the error model also changes the answer. Capacity for independent random bit flips and capacity for list decoding are not the same quantity as the largest rate at a prescribed minimum distance. This card asks about worst-case pairwise separation with unrestricted binary codes. It also does not transfer improvements for sufficiently large alphabets directly to binary codes: changing alphabet and concatenating codes changes their rate and distance parameters.','cq')],
 why='The basic unresolved packing limit for reliable binary information. An exact answer would identify how much redundancy is intrinsically necessary for a prescribed worst-case separation, independently of algorithmic or algebraic restrictions on the code.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-10',reason='A foundational coding-theory limit with a precise extremal target, a large gap between existence and converse bounds, and connections to combinatorics, information theory and quantum methods.'),
 progress=[
  step('1952–1957','The Gilbert–Varshamov existence bound yields the rate lower curve 1−h₂(δ).','vadhan'),
  step('1977','MRRW establishes the two classical linear-programming upper bounds.','mrrw'),
  step('2004','Jiang–Vardy improve code size by a polynomial factor without changing the leading asymptotic rate.','jv'),
  step('2026-01-26','Yuan–Zhu give another proof of an improved linear-code GV factor and extend the method to quantum codes; the exponent remains unchanged.','gv2026'),
  step('2026-08-10','Alrabiah–Guruswami report strict improvements to both MRRW upper bounds for arbitrary binary codes.','cq'),
  step('2026-09-01','Barg relates the new channel and Delsarte approaches and identifies their coinciding first-bound optimization.','barg')],
 references=[
  ref('vadhan','Pseudorandomness','Salil P. Vadhan',2012,'https://people.seas.harvard.edu/~salil/pseudorandomness/','Foundations and Trends in Theoretical Computer Science 7(1–3):1–336; §5.1, Open Problem 5.9, printed page 137 / PDF page 140'),
  ref('mrrw','New upper bounds on the rate of a code via the Delsarte–MacWilliams inequalities','Robert J. McEliece; Eugene R. Rodemich; Howard Rumsey Jr.; Lloyd R. Welch',1977,'https://doi.org/10.1109/TIT.1977.1055688','IEEE Transactions on Information Theory 23(2):157–166; both asymptotic upper bounds; restated and improved in the 2026 primary papers'),
  ref('jv','Asymptotic Improvement of the Gilbert–Varshamov Bound on the Size of Binary Codes','Tao Jiang; Alexander Vardy',2004,'https://arxiv.org/abs/math/0404325','IEEE Transactions on Information Theory 50(8):1655–1664; logarithmic Hamming-ball-volume factor for d/n≤0.499'),
  ref('gv2026','Improvement of the Gilbert-Varshamov Bound for Linear Codes and Quantum Codes','Chen Yuan; Ruiqi Zhu',2026,'https://arxiv.org/abs/2601.18590','v1, 26 January; polynomial size improvements, with the 2022 Hao–Huang–Livshyts–Tikhomirov classical predecessor acknowledged in §1'),
  ref('cq','Binary code rate bounds via classical–quantum channels','Omar Alrabiah; Venkatesan Guruswami',2026,'https://arxiv.org/abs/2608.09347','v1, 10 August; Theorem 1 gives the pretty good criterion; Theorems 2–3 improve first and second MRRW; Introduction distinguishes classical, stochastic and list-decoding models'),
  ref('barg','Comments on the recent improvements of the MRRW bounds','Alexander Barg',2026,'https://arxiv.org/abs/2609.01860','v1, 1 September; §2 defines R₂ using limsup and identifies the coinciding first-bound formulas; §§5–7 explain moving subspaces and channel methods')],
 status='source_open',status_note='Checked through 10 September 2026. The August and September primary sources report genuine asymptotic upper-bound improvements beyond MRRW, but retain a gap above the binary GV lower curve. The exact function remains undetermined; polynomial multiplicative size improvements and results for other alphabets or coding models do not settle it.',formulation_reviewed_on='2026-09-10')
