import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('almost-linear-exact-maximum-cardinality-general-matching',
 id='TCS-6538',title='Almost-linear-time exact maximum matching in general graphs',area='Algorithms & data structures',criterion='tightness',question_type='yes_no',
 formal='Is there one randomized sequential algorithm that, on every explicitly represented finite simple undirected graph G with n vertices and m edges, outputs an exact maximum-cardinality matching with probability at least 2/3 and has expected running time (n+m+2)^{1+o(1)} in the word-RAM model below?',
 definitions='A matching M⊆E(G) is a set of edges no two of which share an endpoint. Its size is |M|, and ν(G)=max{|M|:M is a matching in G}. The algorithm must output valid edge identifiers forming a matching on every terminating execution, and |M|=ν(G) with probability at least 2/3 on each input. It must terminate with probability one. Vertices are labelled 1,…,n and the input is an adjacency-list or edge-list representation of size O(n+m); isolated vertices are included in n. Put N=n+m+2. Use a random-access machine with Θ(log N)-bit words, supporting constant-cost reads, writes, comparisons, addition, subtraction, multiplication, integer division with nonzero divisor, bitwise Boolean operations and shifts on words, and fresh uniform random words. Intermediate larger integers require multiple words and their processing is charged. Preprocessing and output writing are included. The program is uniform, with no advice or free precomputed tables. The time statement means that this same algorithm satisfies: for every real ε>0 there are constants Cε and Nε such that for every input with N≥Nε, its expected number of operations is at most Cε N^{1+ε}. The expectation is over its own random choices, not a distribution on graph inputs. No edge weights, degree restriction, bipartiteness promise, approximation slack or auxiliary communication model is assumed.',
 answer_criterion='Give a single algorithm meeting the stated exactness, success probability and almost-linear time bounds, or prove no such algorithm exists. A fixed bound N^{1+c} for c>0 is not enough. Nor is a separate unrelated algorithm for each ε without establishing the single-algorithm subpolynomial-overhead guarantee. An algorithm restricted to bipartite graphs, a (1−δ)-approximation for fixed δ, an algorithm returning only a maximal matching, or a bound solely in parallel rounds does not settle the target.',
 context=[
 paragraph('Maximum matching is a basic model of pairing compatible objects while using each object at most once. General graphs allow compatibility patterns that cannot be separated into two sides. Edmonds’ blossom method established that this optimization is polynomial-time solvable. The remaining question is how close its exact computational cost can come to the size of the graph that must be read.','implementation'),
 paragraph('Maximum and maximal have different meanings. A maximal matching merely cannot be extended by adding a single edge. On a four-vertex path, the middle edge alone is maximal, while the two outside edges form a maximum matching of size two. A greedy linear-time procedure can therefore solve maximal matching and still fail the exact task on a tiny input. The card requires the global optimum, with no allowed loss of even one matched pair.'),
 paragraph('Alternating paths explain how a nonmaximum matching can improve. Such a path alternates edges outside and inside the matching and starts and ends at unmatched vertices. Flipping its edge membership increases the matching size by one. In general graphs, odd cycles complicate the search for shortest augmenting paths; contracted structures called blossoms keep track of these possibilities. Micali and Vazirani’s classical algorithm achieves O(m√n) time, with later work developing its proof and presentation.','mv'),
 paragraph('Bipartite graphs have a particularly effective flow formulation. Direct each edge from the left side to the right, join a source to left vertices and right vertices to a sink, and give every edge capacity one. Integral maximum flow gives a maximum matching. Almost-linear exact flow algorithms therefore solve bipartite matching within the desired time scale. There is no supplied bipartition in the present question, and the same construction does not automatically encode odd-cycle constraints.','flow'),
 paragraph('A triangle illustrates the polyhedral obstacle without requiring a large example. If a fractional variable of one half is placed on each edge, every vertex has total incident value one, but the total value is 3/2 while an integral matching has size at most one. For any odd vertex set S, an integral matching uses at most (|S|−1)/2 edges entirely inside S. Handling these additional odd-set restrictions efficiently is part of what distinguishes general matching from its bipartite counterpart.'),
 paragraph('Algebraic algorithms offer another route. Mucha and Sankowski use Gaussian elimination to construct maximum matchings in randomized time governed by matrix multiplication, conventionally written O(n^ω) for an available exponent ω>2. This is a major improvement over combinatorial bounds on dense graphs. It still does not yield input-size almost-linear time on all sparse graphs, where a dense n-by-n matrix representation can itself exceed the input size by a large factor.','algebra'),
 paragraph('Approximation also behaves differently. Duan, Pettie and Su obtain a (1−δ)-approximation for maximum weight matching in O(mδ⁻¹ log δ⁻¹) time, hence linear time for fixed δ; unit weights cover cardinality. To force exact cardinality purely by rounding this guarantee, one would need δ small enough that the possible loss is below one edge. When the optimum is Θ(n), that requires δ=O(1/n), so substituting it into the approximation running time loses the desired almost-linear bound.','approximation'),
 paragraph('Ansaripour, Danaei and Mehlhorn’s 2024 implementation study is useful for interpreting experiments: the observed behaviour on random graphs can be close to linear, while specially constructed inputs expose substantial differences between algorithms. Empirical speed and average graph behaviour therefore cannot establish the bound quantified over every input here. Their paper also keeps the distinction between the faster bipartite results and general matching explicit.','implementation'),
 paragraph('A June 2026 revision by Chakraborty and coauthors places construction of a general maximum matching in polynomial-time catalytic logspace. This model permits a large auxiliary tape with arbitrary initial contents, provided those contents are restored. It is progress on space and reversible use of auxiliary memory. The polynomial-time statement is not an almost-linear running-time theorem, so it does not resolve this card.','catalytic')],
 why='A major remaining exact graph-optimization problem beyond the almost-linear flow framework. It asks whether odd-cycle and blossom structure impose a real asymptotic cost, even when randomization is allowed.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A core combinatorial optimization primitive with a large gap between general graphs and the fast bipartite case, connecting augmenting paths, polyhedral methods and algebraic algorithms.'),
 progress=[
 step('1980','Micali–Vazirani obtain the classical O(m√n) algorithm; later correctness work refines its alternating-path theory.','mv'),
 step('2004','Mucha–Sankowski construct maximum matchings using fast algebraic operations.','algebra'),
 step('2011','Duan–Pettie–Su obtain linear-time approximation for each fixed accuracy parameter in general weighted graphs.','approximation'),
 step('2022','Chen and coauthors achieve almost-linear exact flow algorithms, giving the corresponding bipartite matching consequence.','flow'),
 step('2024-09-23','Ansaripour–Danaei–Mehlhorn publish a detailed implementation and experimental study of Gabow’s general matching algorithm.','implementation'),
 step('2026-06-01','The catalytic-logspace revision constructs general maximum matchings with a polynomial-time bound, a different resource guarantee.','catalytic')],
 references=[
 ref('mv','A Theory of Alternating Paths and Blossoms from the Perspective of Minimum Length','Vijay V. Vazirani',2024,'https://pubsonline.informs.org/doi/abs/10.1287/moor.2020.0388','Published online 7 May 2024; proof of the Micali–Vazirani FOCS 1980 algorithm; arXiv:2012.03582 precursor has the title A Proof of the MV Matching Algorithm'),
 ref('algebra','Maximum Matchings via Gaussian Elimination','Marcin Mucha; Piotr Sankowski',2004,'https://www.mimuw.edu.pl/~mucha/pub/mucha_sankowski_focs04.pdf','FOCS 2004; construction in general and bipartite graphs; Remark 1.1 notes a logarithmic factor at exponent exactly two'),
 ref('approximation','Scaling algorithms for approximate and exact maximum weight matching','Ran Duan; Seth Pettie; Hsin-Hao Su',2011,'https://arxiv.org/abs/1112.0790','v1, 4 December; general-graph approximate result and separate bipartite exact weighted result'),
 ref('flow','Maximum Flow and Minimum-Cost Flow in Almost-Linear Time','Li Chen; Rasmus Kyng; Yang P. Liu; Richard Peng; Maximilian Probst Gutenberg; Sushant Sachdeva',2022,'https://arxiv.org/abs/2203.00671','v2, 22 April; exact flow with polynomially bounded integral data; unit-capacity bipartite reduction fits the model'),
 ref('implementation','Gabow’s Cardinality Matching Algorithm in General Graphs: Implementation and Experiments','Matin Ansaripour; Alireza Danaei; Kurt Mehlhorn',2024,'https://arxiv.org/abs/2409.14849','v1, 23 September; §§1–3, worst-case families versus random graph experiments'),
 ref('catalytic','Maximum Matching and Related Problems in Catalytic Logspace','Srijan Chakraborty; Samir Datta; Aryan Kusre; Partha Mukhopadhyay; Amit Sinhababu',2026,'https://eccc.weizmann.ac.il/report/2026/080/','Revision 1, 1 June; general matching construction in CLP, not an almost-linear time bound')],
 status='source_open',status_note='No almost-linear exact general-graph algorithm was found in the primary literature checked through 11 September 2026. Bipartite flow algorithms, approximation schemes and the 2026 catalytic-space result do not meet the stated target. This card explicitly permits bounded-error randomization and expected running time.',formulation_reviewed_on='2026-09-11')
