import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('rigidity-of-all-turing-degrees',
 id='TCS-6647',title='Rigidity of the Turing degrees',area='Computability and algorithmic information',criterion='characterization',question_type='yes_no',
 formal='Is every order automorphism of the partial order (Dₜ,≤ₜ) of all Turing degrees the identity? Equivalently, does every bijection π:Dₜ→Dₜ satisfying a≤ₜb if and only if π(a)≤ₜπ(b), for all a,b∈Dₜ, also satisfy π(a)=a for every a∈Dₜ?',
 definitions='For sets A,B⊆ℕ, A≤ₜB means that an oracle Turing machine with membership-query access to B halts on every natural-number input and decides membership in A. There is no time or space bound. A≡ₜB means A≤ₜB and B≤ₜA. The Turing degree [A] is the equivalence class of A under ≡ₜ, and Dₜ is the quotient of all subsets of ℕ by this equivalence. The relation [A]≤ₜ[B] is independent of the chosen representatives and is a partial order. An automorphism is any set-theoretic bijection of Dₜ preserving and reflecting this order. It is not assumed computable, definable, continuous, measure-preserving or induced by one operation on representatives. The domain includes all degrees, not only degrees of computably enumerable sets or degrees below a fixed bound. The question is interpreted for the actual degree structure in ordinary set theory, for example ZFC.',
 answer_criterion='Prove that every such bijection fixes every degree, or prove the existence of one order automorphism and one degree that it moves. An automorphism of a proper substructure, a non-surjective order embedding, or a permutation of subsets that fails to descend to degrees is not a counterexample. Rigidity of one cone or of a restricted class of induced automorphisms is only a partial positive result. An independence result should specify the axiomatic base and would settle provability relative to that base rather than assert either mathematical answer.',
 context=[
  paragraph('Turing degrees classify decision problems by what can be computed from an oracle for them. Different encodings that compute one another become one point, and the order records comparative computational power. The rigidity question asks whether this order has any genuine symmetry: could all degrees be consistently relabeled, changing at least one degree while preserving every reducibility comparison? A positive answer would make the entire relative-computability structure intrinsically asymmetric.'),
  paragraph('Elementary examples illustrate what is already forced. The degree 0 of computable sets is the unique least element and therefore cannot move. The join of [A] and [B] is represented by A⊕B, which stores A on even positions and B on odd positions; because it is the least upper bound, every order automorphism preserves joins as well. These observations do not identify arbitrary degrees, whose patterns of predecessors and successors are far more complicated.'),
  paragraph('The Turing jump sends [A] to the degree of the halting problem for machines equipped with oracle A. Shore and Slaman prove that this operation is first-order definable using the degree order alone. Consequently every automorphism commutes with the jump, and fixes 0′, 0″ and all finite iterates starting from 0. This is a major restriction, but commuting with an operation does not by itself force a map to fix every argument.','jump'),
  paragraph('Slaman and Woodin prove that every automorphism fixes every degree above 0″. Their analysis also shows that the automorphism group is at most countable, despite the continuum-sized underlying degree structure. The unresolved region is the complement of that upper cone. It includes degrees incomparable with 0″, not just degrees strictly below it. Thus describing the remaining question as only the interval below 0″ would omit part of the problem.','survey'),
  paragraph('One possible way to construct an automorphism would be to permute the natural-number coordinates of every oracle set. Kjos-Hanssen rules this out: if one permutation of ℕ induces an order automorphism on all Turing degrees, the induced automorphism is trivial, and the permutation itself must be computable. His result also treats homeomorphisms of Cantor space preserving all Bernoulli product measures. The full question imposes none of these representation or measure restrictions.','permutations'),
  paragraph('Rigidity must also be distinguished from defining every single degree by a first-order formula without parameters. There are only countably many such formulas but uncountably many degrees, so the latter is impossible. A rigid infinite structure can contain elements that are not individually definable: absence of global symmetries is weaker than having a separate finite logical description of each element.'),
  paragraph('The historical literature includes an announced nontrivial automorphism by Cooper in 1999. Slaman’s survey explicitly reports that its construction had not been independently verified and continues to treat rigidity as open. Kjos-Hanssen’s later journal article likewise states the general question as open. These cards follow the established partial-result literature; an old announcement alone is not treated as a resolution.','survey'),
  paragraph('This is a foundational computability question rather than an efficient-algorithm problem. Its significance is whether relative computability already determines its own global structure, or whether the degree order admits hidden symmetries that are invisible to all reducibility comparisons.')],
 why='A central structural question about relative computability: whether the ordering of computational power has any nontrivial global symmetry. It tests how much mathematical information is recoverable from reducibility alone.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A defining open problem of degree theory, closely tied to the intrinsic definability of computational structure and constrained by deep but incomplete rigidity theorems.'),
 progress=[
  step('1980 and later','Cone-rigidity results culminate in Slaman–Woodin’s theorem that all degrees above 0″ are fixed; the full structure remains outside this conclusion.','permutations'),
  step('1999','Shore–Slaman prove that the Turing jump is definable from the order, so every automorphism preserves it.','jump'),
  step('2008','Slaman’s published survey presents the countability of the automorphism group, rigidity above 0″ and the unresolved general question.','survey'),
  step('2016–2018','Kjos-Hanssen excludes nontrivial automorphisms induced by integer permutations and certain measure-preserving homeomorphisms; the journal paper appears in 2018.','permutations')],
 references=[
  ref('jump','Defining the Turing Jump','Richard A. Shore; Theodore A. Slaman',1999,'https://math.berkeley.edu/~slaman/papers/jump.pdf','Mathematical Research Letters 6:711–722; order-theoretic definability of the jump'),
  ref('survey','Global Properties of the Turing Degrees and the Turing Jump','Theodore A. Slaman',2008,'https://math.berkeley.edu/~slaman/papers/IMS_slaman.pdf','Computational Prospects of Infinity, Part I: Tutorials, vol. 14, pp. 83–101; introduction, Theorems 4.28 and 4.30, and §6; based on 2005 lectures'),
  ref('permutations','Permutations of the Integers Induce Only the Trivial Automorphism of the Turing Degrees','Bjørn Kjos-Hanssen',2018,'https://arxiv.org/abs/1603.00525','Bulletin of Symbolic Logic 24(2):165–174, DOI 10.1017/bsl.2018.15; preprint Question 1 and Theorems 20, 22, 25; journal online 7 August 2018')],
 status='source_open',status_note='Literature search checked through 10 September 2026. The checked primary sources explicitly retain general rigidity as open; no later verified resolution was located. The last substantive result documented here is the 2018 journal article, not a claimed 2026 advance. The historical Cooper announcement is distinguished from an independently verified solution.',formulation_reviewed_on='2026-09-10')
