import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('computability-of-unassisted-quantum-channel-capacity',
 id='TCS-6520',title='Computability of quantum channel capacity',area='Quantum computation',criterion='decision',question_type='yes_no',
 formal='Does there exist a single classical Turing algorithm that, given any effectively described finite-dimensional memoryless quantum channel Φ and a positive rational ε, halts and outputs a rational r satisfying |r−Q(Φ)|≤ε, where Q is the unassisted quantum capacity in qubits per channel use?',
 definitions='The input includes positive integers d_A,d_B and a program describing the unnormalized Choi matrix J(Φ)=Σᵢⱼ |i⟩⟨j|⊗Φ(|i⟩⟨j|), a matrix of order d_A d_B. On input k≥1, that program must halt and output a rational complex matrix whose real and imaginary entries approximate the corresponding entries of J(Φ) within 2⁻ᵏ. It is promised that the limiting matrix is positive semidefinite and Tr_B J(Φ)=I_A, so it defines a completely positive trace-preserving linear map from d_A-dimensional input states to d_B-dimensional output states. This explicitly specifies “effective description”; finite algebraic matrix descriptions are included. The requested algorithm need only meet its guarantees on inputs satisfying these promises. Memorylessness means n uses implement Φ^{⊗n}, allowing arbitrary joint encoding and decoding across those uses. No preshared entanglement, additional classical communication, feedback or auxiliary channel is free. Operationally Q(Φ) is the supremum of asymptotically achievable quantum transmission rates with error tending to zero. Equivalently, Q(Φ)=sup_{n≥1} n⁻¹ max_ρ I_c(ρ,Φ^{⊗n}). Here ρ ranges over density matrices on A^{⊗n}; if ψ_{RAⁿ} is any purification and ω=(id_R⊗Φ^{⊗n})(ψ), then I_c=S(ω_{Bⁿ})−S(ω_{RBⁿ}), with S(τ)=−Tr(τ log₂τ) and 0 log₂0=0. There is no running-time bound beyond eventual halting for every valid channel description and every ε>0.',
 answer_criterion='A positive answer requires a uniform algorithm with a proved finite stopping rule and additive error guarantee for every promised input. A negative answer must prove that no such approximation algorithm exists in this specified representation. An asymptotic formula without an effective convergence bound, hardness only for polynomial-time computation, or undecidability of a different assisted, zero-error or memoryful capacity is insufficient. Undecidability of testing the exact equality Q(Φ)=0 alone would also not disprove computable additive approximation.',
 context=[
 paragraph('Capacity is the best rate at which a noisy channel can transmit information reliably after coding over many uses. For quantum transmission, the object being preserved is an arbitrary quantum state, including its entanglement with a reference system. A channel may badly corrupt each individual input and still support a positive asymptotic rate through suitable coding. This card asks whether that optimal rate can always be computed to requested precision at all.','coding'),
 paragraph('The quantum coding theorem expresses capacity through regularized coherent information: optimize over a block of n uses, divide by n, and take the supremum over every block length. Devetak’s coding theorem gives an operational justification for this expression. It is an exact mathematical characterization, but it involves infinitely many optimization problems. A numerical procedure needs an additional way to know when unexamined block lengths cannot improve the answer by more than ε.','coding'),
 paragraph('For each fixed block length, the input dimension is finite and the coherent-information objective can be approximated on the compact space of density matrices. Exhaustive computation can therefore produce successively better certified lower bounds on Q. This can be absurdly expensive and still count as computation here. The obstruction is that increasing lower bounds need not come with a computable certificate of how far they remain below their limit.'),
 paragraph('Cubitt, Elkouss, Matthews, Ozols, Pérez-García and Strelchuk show that no universal constant number of channel uses suffices even to expose positive coherent information. For every chosen block length, they construct a channel whose optimized coherent information is zero there, but becomes positive at a larger block length. These are different channels as the chosen length changes. The theorem does not rule out an algorithm whose stopping time depends on the channel description and requested precision.','unbounded'),
 paragraph('The input convention is important because a quantum channel is described by real and complex numbers. A finite program that supplies certified rational approximations gives an algorithm meaningful access to those numbers without granting exact tests of arbitrary computable-real equality. It also includes ordinary finite circuit descriptions over computable gates. The validity of the channel and approximation program is promised; solving the separate problem of recognizing all valid descriptions is not required.'),
 paragraph('Leung and Smith prove continuity of unassisted quantum capacity in finite output dimension, with an explicit bound in terms of channel distance and dimension. Thus small errors in specifying a fixed-dimensional channel change its capacity by a controlled amount. This prevents a simple discontinuity argument from settling this approximation question. Continuity controls perturbations of the channel, while the missing stopping rule concerns convergence over code block lengths.','continuity'),
 paragraph('The 2025 review Undecidability in Physics distinguishes this question from established undecidability results for other information-theoretic quantities. Channels with memory can carry an evolving hidden state across uses; that is different from repeating Φ independently. Zero-error capacities demand perfect distinguishability at finite stages, unlike an error that tends to zero under asymptotic coding. Neither change can be imported silently into the present problem.','review'),
 paragraph('Bhattacharyya, Mehta and Zhao prove in 2026 that approximating quantum capacity is QMA-hard for channels specified succinctly by circuits. Their promise distinguishes capacity at least 3/4 from capacity at most 1/4, even for degradable channels. This is strong evidence against efficient computation, but it leaves unrestricted computability untouched: a QMA-hard problem can still have an exhaustive terminating algorithm. Circuit size also differs substantially from the length of a fully expanded channel matrix.','hardness'),
 paragraph('Their corrected March 2026 version proves undecidability for a separate restricted capacity: one-shot, entanglement-assisted, zero-error classical communication through a classical-to-quantum channel, with maximally entangled assistance and projective decoding measurements. Those restrictions are part of the theorem. The paper explicitly says it does not resolve general quantum-capacity computability. Its revision history records a correction to the earlier treatment of the assisted zero-error result.','hardness'),
 paragraph('It is also necessary to separate approximation from deciding whether the answer is exactly zero. Even when a nonnegative real quantity is computable to arbitrary error, every finite approximation can leave open whether it is zero or merely very small. Conversely, identifying some zero-capacity families does not provide approximations for every channel. The requested output and tolerance make this card an unambiguous uniform approximation problem.'),
 paragraph('A positive resolution would supply a general certification procedure for quantum communication rates, however slow. A negative resolution would show that no universal procedure can always certify the optimal rate to a chosen tolerance, despite finite input and output dimensions and independent repeated noise. Either outcome would clarify whether regularized formulas describe quantities that are algorithmically accessible or can exceed the reach of computation.')],
 why='Determine whether the fundamental reliable quantum communication rate is algorithmically accessible even without efficiency constraints.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A foundational computability question about regularized information quantities, separating lack of efficient algorithms from the possible absence of any certified approximation algorithm.'),
 progress=[
 step('2003–2005','Devetak proves a quantum coding theorem yielding the regularized coherent-information expression for unassisted capacity.','coding'),
 step('2009','Leung–Smith establish explicit continuity bounds for finite-dimensional unassisted quantum capacity.','continuity'),
 step('2015-03-31','Cubitt and coauthors prove that arbitrarily many channel uses may be needed before positive coherent information appears.','unbounded'),
 step('2025','Undecidability in Physics reviews the open computability issue and distinguishes memoryful channels and zero-error capacities.','review'),
 step('2026-03-30','Bhattacharyya–Mehta–Zhao’s corrected v3 proves circuit-input QMA-hardness for quantum capacity and undecidability for a restricted assisted zero-error classical capacity; ordinary quantum-capacity computability remains open.','hardness')],
 references=[
 ref('coding','The private classical capacity and quantum capacity of a quantum channel','Igor Devetak',2005,'https://arxiv.org/abs/quant-ph/0304127','First posted 18 April 2003; checked v6, 21 October 2004; IEEE Transactions on Information Theory 51(1), 44–55, 2005; quantum coding theorem and regularization'),
 ref('continuity','Continuity of quantum channel capacities','Debbie Leung; Graeme Smith',2009,'https://arxiv.org/abs/0810.4931','Checked v2, 18 February 2009; Communications in Mathematical Physics 292, 201–215; Sections III–IV, explicit finite-output-dimension continuity bounds'),
 ref('unbounded','Unbounded number of channel uses may be required to detect quantum capacity','Toby Cubitt; David Elkouss; William Matthews; Maris Ozols; David Pérez-García; Sergii Strelchuk',2015,'https://www.nature.com/articles/ncomms7739','Nature Communications 6, Article 6739, 31 March 2015; channel construction for arbitrary prescribed block length; not an uncomputability theorem'),
 ref('review','Undecidability in Physics: a Review','Álvaro Perales-Eceiza; Toby Cubitt; Mile Gu; David Pérez-García; Michael M. Wolf',2025,'https://arxiv.org/abs/2410.16532','Checked v2, 14 July 2025, quantum-information discussion, preprint pp. 42–46; Physics Reports 1138, 1–29'),
 ref('inherited','Undecidability in physics: A review — journal version','Álvaro Perales-Eceiza; Toby Cubitt; Mile Gu; David Pérez-García; Michael M. Wolf',2025,'https://doi.org/10.1016/j.physrep.2025.06.004','Inherited journal reference retained; text checked in the authors’ arXiv v2 because publisher retrieval returned 403'),
 ref('hardness','On the undecidability of quantum channel capacities','Archishna Bhattacharyya; Arthur Mehta; Yuming Zhao',2026,'https://arxiv.org/abs/2601.22471','First posted 30 January 2026; checked corrected v3, 30 March 2026; Theorems 1.1–1.2, Section 1.2.1 circuit representation, Definition 2.3 and Corollaries 3.13 and 4.2; v2 error corrected in Sections 2 and 4')],
 status='source_open',status_note='No uniform computability theorem or impossibility proof for this finite-dimensional memoryless unassisted capacity found through 11 September 2026. The corrected 2026 paper explicitly leaves the general question open: its quantum-capacity result is QMA-hardness, while its undecidability result concerns a restricted assisted zero-error classical capacity.',formulation_reviewed_on='2026-09-11')
