import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('polynomial-bit-time-primal-simplex-pivot-rule',
 id='TCS-6572', title='Is there a polynomial-time simplex pivot rule?',
 area='Optimization and numerics', criterion='resources', question_type='yes_no',
 formal='Does there exist a uniform deterministic primal-simplex pivot algorithm and a polynomial p such that, for every rational linear program max{cᵀx: Ax=b, x≥0} with A of full row rank, a finite optimum, and any supplied feasible basis B_0, the algorithm reaches a basis whose reduced costs are all nonpositive using at most p(L) bit operations in total? Here L is the binary input length of A,b,c and B_0, and every basis change must be a legal improving simplex pivot as defined below.',
 definitions='A has m rows and n columns with 1≤m≤n; all rational numerators and positive denominators are explicit binary integers. A basis B is a set of m columns with invertible A_B. Its basic solution is x_B=A_B^{-1}b and x_j=0 for j∉B, and feasibility means x_B≥0. An entering column j∉B must have reduced cost r_j=c_j−c_BᵀA_B^{-1}A_j>0. Put a=A_B^{-1}A_j. Choose a leaving basic index i attaining θ=min_{k∈B:a_k>0}x_k/a_k, and replace i by j in the basis. The finite-optimum promise ensures that this minimum exists for an improving column. Ties may be resolved by the rule; θ=0 is an allowed degenerate pivot and counts toward the bound. The rule may inspect the whole input and maintain history, with all preprocessing, pivot selection, exact arithmetic, helper computations and memory operations charged to p(L). It must follow these basis exchanges on the supplied LP from B_0: it may not jump to another feasible basis or replace the feasible region by an extended formulation. The required terminal condition r_j≤0 for all j∉B certifies optimality. This is the supplied-feasible-basis optimization version; phase-I feasibility construction is not part of this card.',
 answer_criterion='Construct such a rule and prove its total polynomial bit complexity for every promised input and initial feasible basis, or prove that no such rule exists. Merely bounding the number of pivots while leaving their selection computationally unbounded is insufficient. A lower bound for a prescribed family of rules, or for nonlinear objectives, does not establish the negative answer for all rules here.',
 context=[
  paragraph('Linear programming already has algorithms with polynomial bit complexity, including ellipsoid and interior-point methods. The unresolved question is whether the same guarantee can be achieved while moving through bases by the simplex method. A pivot rule determines which improving direction to expose next and how to break ties. The STACS 2026 paper on ranking-based rules states that the general question remains open.','ranking'),
  paragraph('There are two obstacles to a polynomial guarantee. First, a short route to an optimal basis must exist under the permitted improving moves. Second, the rule must discover such a route efficiently. Knowing the optimum from another computation does not authorize skipping the route: every intervening basis exchange is still required. Likewise, a short path in the undirected graph of a polyhedron need not be a short path along improving edges.'),
  paragraph('The bit-complexity requirement is deliberately weaker than strongly polynomial simplex. It permits the running time to depend polynomially on the number of bits in coefficients. A strongly polynomial rule would instead bound its arithmetic work polynomially in m and n, together with appropriate bounds on the sizes of numbers used. Therefore this card does not assert that a positive answer alone settles Smale’s strongly polynomial LP problem or a diameter bound depending only on dimension and number of facets.'),
  paragraph('Degeneracy means several bases can describe the same vertex. A legal pivot with θ=0 changes the basis without improving the objective value, so an algorithm can stall even if the geometric route is short. Kukharenko and Sanità’s March 2026 paper bounds a block of consecutive degenerate pivots at a nonoptimal vertex by n−m−1, given an improving feasible direction. Such a direction can be obtained using an LP solver. This controls local stalling, but does not bound how many different nonoptimal vertices the method must visit.','stalling'),
  paragraph('Positive average-case results are also substantial. Spielman and Teng show polynomial smoothed complexity for a simplex algorithm under random perturbations of the input. Smoothed analysis studies the expected behavior around an arbitrary instance as a function of perturbation size. It helps explain good practical performance, but does not give a deterministic worst-case guarantee on every exact rational instance.','smoothed'),
  paragraph('The 2026 ranking-based lower bounds exclude broader families than a single greedy rule. One result covers index-ranking rules with a specified limit on their memory states; another covers memoryless rules using rankings by index, reduced cost and objective improvement. Full access to numerical data and unrestricted polynomially bounded history are allowed in this card, so those lower bounds do not cover every candidate.','ranking'),
  paragraph('A striking neighboring result does exclude every pivot rule for the active-set method with a nonlinear objective. Disser and Mosis first use higher-degree polynomial objectives on the hypercube. Bach and coauthors then obtain the phenomenon for maximizing a convex quadratic function, published at SODA 2026. The direction of optimization matters: this is convex maximization. Their construction does not have a linear objective, and the authors explicitly distinguish it from a general simplex lower bound.','quadratic')],
 why='A fundamental question about whether local, improving basis exchanges can support efficient global optimization. It would explain a central practical algorithm and sharpen the relationship between polyhedral geometry, degeneracy and algorithmic access to an optimum.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A longstanding foundational problem about one of the most important optimization algorithms; the existence and efficient discovery of short improving basis paths remain unresolved even though LP itself is polynomial-time solvable.'),
 progress=[
  step('2004','Spielman and Teng establish polynomial smoothed complexity for a simplex algorithm; this is a distributional guarantee rather than worst-case polynomial bit complexity.','smoothed'),
  step('2025','Disser and Mosis give an unconditional active-set lower bound using a nonlinear polynomial objective on a hypercube; the linear-objective question remains open.','hypercube'),
  step('2026 — SODA','Bach, Disser, Huiberts and Mosis strengthen the all-rules active-set lower bound to convex quadratic maximization. The latest preprint version is dated 22 October 2025.','quadratic'),
  step('2026-02-25','Disser, Loho, Maat and Mosis publish superpolynomial lower bounds for specified ranking-based classes, with explicit information and memory restrictions.','ranking'),
  step('2026-03-23','Kukharenko and Sanità publish an antistalling rule bounding consecutive degenerate pivots at a nonoptimal vertex by n−m−1, given an improving feasible direction. It leaves the global pivot count open.','stalling')],
 references=[
  ref('smoothed','Smoothed Analysis of Algorithms: Why the Simplex Algorithm Usually Takes Polynomial Time','Daniel A. Spielman; Shang-Hua Teng',2004,'https://www.cs.yale.edu/homes/spielman/simplex/','Journal of the ACM 51(3):385–463; DOI 10.1145/990308.990310; author page links full version and explains differences from STOC 2001'),
  ref('hypercube','An unconditional lower bound for the active-set method on the hypercube','Yann Disser; Nils Mosis',2025,'https://arxiv.org/abs/2502.18019','IPCO 2025; preprint v1, 25 February 2025; nonlinear polynomial objectives'),
  ref('quadratic','An Unconditional Lower Bound for the Active-Set Method in Convex Quadratic Maximization','Eleon Bach; Yann Disser; Sophie Huiberts; Nils Mosis',2026,'https://epubs.siam.org/doi/10.1137/1.9781611978971.14','SODA 2026; full preprint arXiv:2507.16648v2, 22 October 2025; maximization of a convex quadratic, not a linear objective'),
  ref('ranking','Lower Bounds for Ranking-Based Pivot Rules','Yann Disser; Georg Loho; Matthew Maat; Nils Mosis',2026,'https://drops.dagstuhl.de/storage/00lipics/lipics-vol364-stacs2026/html/LIPIcs.STACS.2026.31/LIPIcs.STACS.2026.31.html','STACS 2026, 31:1–19; §2 simplex model, Theorems 1.1–1.2 information and memory restrictions'),
  ref('stalling','On the number of degenerate simplex pivots','Kirill Kukharenko; Laura Sanità',2026,'https://link.springer.com/article/10.1007/s10107-026-02349-x','Mathematical Programming 216:757–791; published 23 March 2026; Theorem 1 and §2.1 legal improving pivots')],
 status='source_open', status_note='Checked through 10 September 2026. The STACS 2026 and March 2026 primary publications retain the general polynomial simplex question as open. This card fixes deterministic total bit complexity for legal improving primal-simplex pivots from any supplied feasible basis on a finite-optimum rational LP. Strongly polynomial algorithms, nonlinear active-set bounds and distributional performance are distinct formulations.', formulation_reviewed_on='2026-09-10')
