import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('frege-polynomial-size-simulation-of-extended-frege',
 id='TCS-6663',title='Does Frege simulate Extended Frege with polynomial proof size?',area='Proof complexity',criterion='resources',question_type='yes_no',
 formal='Do there exist constants C>0 and k≥1 such that every Extended Frege proof π of a propositional tautology φ has some ordinary Frege proof ρ of the same formula with |ρ|≤C(|π|+2)ᵏ? Equivalently, if sF(φ) and sEF(φ) are the minimum proof sizes in the two systems, is sF(φ) polynomially bounded in sEF(φ), uniformly over all tautologies?',
 definitions='Fix formulas over negation ¬ and material implication →, with binary-encoded variable indices. Ordinary Frege uses the axiom schemes A→(B→A), (A→(B→C))→((A→B)→(A→C)), and (¬B→¬A)→(A→B), and modus ponens: infer B from A and A→B. A proof is a finite sequence ending with φ; earlier lines may be cited and reused without restriction. Extended Frege adds acyclic definitions, introducing the pair e→θ and θ→e, where e is a new variable absent from φ, θ and all preceding lines. θ may use variables of φ and earlier extension variables. The final formula contains no extension variables. Proof size is the complete binary encoding length of every explicitly written line, definition and inference reference. No formula-depth, proof-depth or tree-shape bound is imposed. These presentations are polynomially equivalent to the usual finite-basis Frege and Extended Frege systems. The target is existence of short translated proofs: it does not require a polynomial-time function that finds ρ from π.',
 answer_criterion='Answer yes by proving one polynomial overhead valid for all EF proofs. Answer no by proving that for every constants C>0 and k≥1 some tautology φ satisfies sF(φ)>C(sEF(φ)+2)ᵏ. It is sufficient to exhibit polynomial-size EF proofs of a family and prove superpolynomial Frege lower bounds for that family. A lower bound relative only to |φ| without control of EF size need not separate the systems. An efficient proof translator would prove a stronger affirmative statement; a quasipolynomial translator would not establish the stated polynomial bound.',
 context=[
  paragraph('The extension rule gives reusable names to intermediate computations. If a subformula is used many times, ordinary formula syntax writes out each occurrence; Extended Frege can define it once and refer to its name. A network of such definitions represents a Boolean circuit with shared gates. The rule does not permit a false final theorem: every assignment to the original variables uniquely extends through the definitions, and the conclusion uses only original variables.','rewriting'),
  paragraph('Repeated substitution eliminates definitions, but can create exponentially large formula trees. This explains why the obvious simulation is expensive; it does not prove that all ordinary Frege proofs must be expensive. A Frege derivation is free to find a different argument, use algebraic identities, introduce useful intermediate tautologies or avoid the computations used in the EF proof. The challenge is to compare the shortest proofs, not one syntactic expansion procedure.'),
  paragraph('The distinction between proof size and proof-search time is essential. The quantifiers are “for every EF proof there exists a short Frege proof.” They do not supply an algorithm for locating that proof. The stronger notion usually called p-simulation requires a polynomial-time transformation. A size simulation alone can hold even if the available methods for finding the translated proof are much slower.','consistency'),
  paragraph('Buss connects the comparison to finite consistency statements. Frege has polynomial-size proofs of its own partial consistency, meaning the corresponding finite statements that no contradiction has a proof up to a specified length. His theorem characterizes Frege simulation of EF by polynomial-size Frege proofs of the analogous partial consistency statements for EF. This turns a comparison of all proofs into a canonical family of propositional statements; it is not a general proof of the desired simulation.','consistency'),
  paragraph('Natural candidate separations have repeatedly proved harder to establish than expected. For example, Aisenberg and coauthors give polynomial-size EF proofs and quasipolynomial-size Frege proofs of propositional Kneser–Lovász coloring principles. That upper bound constrains possible lower bounds for the family, but it does not demonstrate a separation and does not rule out a polynomial Frege upper bound. Quasipolynomial and polynomial must remain distinct in this problem.','kneser'),
  paragraph('Krajíček’s June 2026 paper gives a circuit-rewriting description of EF reasoning. An EF proof of circuit equivalence yields a polynomially long chain of equivalence-preserving rewrites; each rewrite adds at most seven gates and may delete gates. This is a normal-form result about circuit reasoning. The intermediate objects still retain circuit sharing, so it does not turn an arbitrary EF proof into a polynomial-size formula-based Frege proof.','rewriting'),
  paragraph('A September 2026 preprint by Chatterjee, Chatterjee, Ghosal and Mukhopadhyay proves a quasipolynomial Frege simulation of a partially commutative formula version of the Ideal Proof System over GF(2). Variables lie in two groups: they commute across groups but not within a group. The proof formalizes an identity-testing algorithm inside Frege. The restrictions on the algebraic certificates, and the quasipolynomial overhead, both matter; the theorem is not the full EF simulation asked for here.','ips'),
  paragraph('A negative answer would establish a concrete benefit of reusable definitions for strong propositional reasoning. It would also imply superpolynomial Frege lower bounds, since the final formula is part of every EF proof. By contrast, proving that Frege has some hard tautologies, or assuming NP≠coNP, does not automatically separate it from EF: those same tautologies might require equally long EF proofs. The separate question of whether EF itself is polynomially bounded asks about a different comparison.')],
 why='This asks whether reusable definitions fundamentally shorten mathematical proofs, beyond any polynomial factor. It is one of the central comparisons between strong propositional proof systems and captures the difficulty of reasoning with shared circuits versus explicit formulas.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A canonical strong-system simulation problem, directly tied to Frege lower bounds, finite consistency and circuit-based reasoning.'),
 progress=[
  step('1979','Cook–Reckhow’s framework establishes the robustness of standard Frege and Extended Frege presentations; EF contains ordinary Frege.','foundation'),
  step('1991','Buss characterizes the simulation by polynomial-size Frege proofs of partial EF consistency statements.','consistency'),
  step('2014','Buss’s mini-tutorial explicitly identifies Frege versus EF as a longstanding open simulation question.','tutorial'),
  step('2015–2018','Aisenberg and coauthors obtain polynomial EF and quasipolynomial Frege upper bounds for Kneser–Lovász principles, without proving a lower-bound separation.','kneser'),
  step('2026-06-11','Krajíček gives an EF/circuit-equivalence rewriting characterization, retaining circuit intermediate representations.','rewriting'),
  step('2026-09-05','ECCC TR26-166 extends quasipolynomial Frege simulation to two-group partially commutative formula IPS over GF(2).','ips')],
 references=[
  ref('foundation','The Relative Efficiency of Propositional Proof Systems','Stephen A. Cook; Robert A. Reckhow',1979,'https://www.cs.toronto.edu/~sacook/homepage/cook_reckhow.pdf','Journal of Symbolic Logic 44(1):36–50; standard systems, proof-size simulation and efficient simulation'),
  ref('consistency','Propositional Consistency Proofs','Samuel R. Buss',1991,'https://mathweb.ucsd.edu/~sbuss/ResearchWeb/prop_consis/paper.pdf','Annals of Pure and Applied Logic 52:3–29; abstract and main partial-consistency characterization; downloadable copy bears a 2002 compilation date'),
  ref('tutorial','Towards (Non-)Separations in Propositional Proof Complexity','Samuel R. Buss',2014,'https://mathweb.ucsd.edu/~sbuss/ResearchWeb/Stanford_February2014/','Stanford mini-tutorial, 27 February; second part concerns Frege versus EF; some cited candidate upper bounds are quasipolynomial and do not establish polynomial simulation'),
  ref('kneser','Short Proofs of the Kneser–Lovász Coloring Principle','James Aisenberg; Maria Luisa Bonet; Samuel R. Buss; Adrian Crăciun; Gabriel Istrate',2018,'https://arxiv.org/abs/1505.05531','ICALP 2015 precursor; Information and Computation, DOI 10.1016/j.ic.2018.02.010; polynomial EF versus quasipolynomial Frege upper bounds'),
  ref('rewriting','Extended Frege proofs, circuits and rewriting','Jan Krajíček',2026,'https://arxiv.org/abs/2606.13367','v1, 11 June; §1 distinguishes size from step count and circuit from formula proofs; Theorem 4.1 gives local circuit rewrites'),
  ref('ips','Quasi-polynomial Frege Simulation of IPS beyond Noncommutativity','Abhranil Chatterjee; Prerona Chatterjee; Utsab Ghosal; Partha Mukhopadhyay',2026,'https://eccc.weizmann.ac.il/report/2026/166/','TR26-166, submitted 4 September, published 5 September; Definition 1.1 and Theorems 1.2–1.3; formula certificates, two groups of variables, GF(2)')],
 status='source_open',status_note='Checked through 10 September 2026. No polynomial size simulation or superpolynomial separation of unrestricted Frege and EF was found in the primary literature. The newest checked simulation, TR26-166, concerns a restricted algebraic formula system and has quasipolynomial overhead.',formulation_reviewed_on='2026-09-10')
