import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('log-rank-conjecture-deterministic-total-communication',
 id='TCS-6603', title='Log-rank conjecture for deterministic two-party communication',
 area='Communication complexity and Boolean function analysis', criterion='tightness', question_type='yes_no',
 formal=r'''Do there exist universal constants C>0 and k≥1 such that every total Boolean function f:X×Y→{0,1}, on arbitrary nonempty finite sets X,Y, satisfies $D(f)\le C(\log_2(r(f)+2))^k$, where r(f) is the real rank of its 0/1 communication matrix and D(f) is its deterministic communication complexity?''',
 definitions=r'''Alice receives x∈X and Bob receives y∈Y. Both know the complete function f and the protocol. They exchange bits interactively; each next transmitted bit is a deterministic function of the sender’s own input and the previous transcript. A binary protocol tree specifies whose turn it is, and every leaf has a Boolean output that must equal f(x,y) for every input pair reaching it. D(f) is the minimum, over all such exact protocols, of the maximum number of transmitted bits on an input pair. The number of rounds and the local computation are unrestricted; protocol description length is not charged. The communication matrix M_f has rows X, columns Y, and entry f(x,y); r(f)=rank_R(M_f) is ordinary matrix rank over the real numbers. The +2 makes the statement unambiguous for rank zero or one. The same constants C,k must work for all matrix dimensions and all functions. There are no undefined entries, input promises, random bits, quantum messages, approximation errors, or restrictions to one-way protocols. Sign rank and approximate rank are different parameters.''',
 answer_criterion='Prove one universal polynomial upper bound in log(r+2), or prove that for every choice of C,k there is a total Boolean matrix whose deterministic communication cost exceeds it. A superpolynomial separation in log-rank refutes the conjecture; a fixed-power separation, a counterexample to one particular exponent, or a partial-function separation does not.',
 context=[
  paragraph('Matrix rank gives a general lower bound on communication. A protocol using at most d bits has at most 2ᵈ leaves, and the inputs reaching each leaf form a rectangle A×B. Summing the indicator matrices of the output-one rectangles represents M_f as a sum of at most 2ᵈ rank-one matrices. Consequently log₂r(f)≤D(f) when r(f)≥1. The conjecture asks whether this algebraic obstruction controls deterministic communication up to a polynomial.','lifting'),
  paragraph('An elementary upper bound goes in the other direction but is much larger. A rank-r Boolean matrix has at most 2ʳ distinct rows: choose r columns that determine every row, and record their Boolean entries. Alice can identify her row with at most r bits, after which Bob can determine the answer and send one output bit. This protocol makes clear why the question concerns the gap between rank and its logarithm.','lifting'),
  paragraph('A low-rank factorization permits arbitrary real coefficients and cancellation. A protocol instead needs a recursively organized partition into monochromatic rectangles. Moving between these kinds of structure is the main difficulty. Lovett used discrepancy to obtain an O(√r log r) communication bound; Sudakov and Tomon remove the logarithmic factor using a stronger discrepancy estimate for sparse matrices. The resulting O(√r) remains far larger than a polynomial in log r.','discrepancy'),
  paragraph('Lower-bound constructions show that a linear bound in log-rank is too optimistic. Göös, Pitassi, and Watson obtain a nearly quadratic separation through query-to-communication lifting.','gpw'),
  paragraph('Song’s August 2026 preprint revisits the construction without first converting its pointer alphabet to Boolean bits and reports a more precise lower bound Ω((log r)²/log log r). This still has a fixed polynomial exponent and therefore supports no refutation of log-rank.','lifting'),
  paragraph('A recent equivalent formulation isolates the role of cancellation more sharply. Hambardzumyan, Lovett, and Shirley show that a rank-r Boolean matrix is a signed sum of O(r log r) rectangle indicator matrices. The open task can then be expressed as converting such signed decompositions into positive disjoint rectangle decompositions with quasipolynomial growth. This theorem supplies a new formulation, while the needed conversion remains unresolved.','equivalences')],
 why='One of the central organizing conjectures of communication complexity. It asks whether a basic linear-algebraic quantity characterizes efficient exact communication, and connects protocols to rectangle partitions, discrepancy, graph structure, and cancellation in matrix decompositions.',
 importance=dict(score=98, method='editorial', assessed_on='2026-09-10', reason='A flagship structural conjecture linking deterministic protocols and matrix rank, with many equivalent combinatorial formulations and a large quantitative gap.'),
 progress=[
  step('1988','Lovász and Saks formulate the conjecture relating real rank and deterministic communication; the 2026 equivalent-formulations paper gives the original attribution and related graph versions.','equivalences'),
  step('2014–2016','Lovett proves D(f)=O(√r log r), the first general sublinear-in-rank upper bound; the later discrepancy paper explains and improves this step.','discrepancy'),
  step('2015–2018','Göös, Pitassi, and Watson establish nearly quadratic lower bounds in log-rank, along with separations involving communication partition number.','gpw'),
  step('2023–2025','Sudakov and Tomon improve the universal upper bound to O(√r). The 2023 preprint is published online in 2024 and in Mathematical Programming volume 212 in 2025.','discrepancy'),
  step('2026-08-03','Song reports an explicit lower bound Ω((log r)²/log log r) via alphabet-preserving lifting. The card records this as a preprint refinement, not an independently certified new universal separation record.','lifting'),
  step('2026-08-14','The CCC 2026 version of Hambardzumyan–Lovett–Shirley gives the O(r log r) signed-rectangle decomposition and equivalent formulations. It explicitly leaves the general conjecture open.','equivalences')],
 references=[
  ref('equivalences','The Log-Rank Conjecture: New Equivalent Formulations','Lianna Hambardzumyan; Shachar Lovett; Morgan Shirley',2026,'https://arxiv.org/abs/2510.02583v3','CCC 2026 version, uploaded 14 August 2026; manuscript dated 17 August; Conjecture 1.1, Theorem 1.2, Corollary 1.4'),
  ref('discrepancy','Matrix discrepancy and the log-rank conjecture','Benny Sudakov; István Tomon',2025,'https://doi.org/10.1007/s10107-024-02117-9','Mathematical Programming 212, 567–579; online 5 July 2024; arXiv:2311.18524 from 30 November 2023; Theorem 1.1 and communication consequence'),
  ref('gpw','Deterministic Communication vs. Partition Number','Mika Göös; Toniann Pitassi; Thomas Watson',2018,'https://doi.org/10.1137/16M1059369','SIAM Journal on Computing 47(6), 2435–2450; preliminary FOCS 2015; lifting and log-rank lower bounds'),
  ref('lifting','Alphabet-Preserving Lifting for the Log-Rank Conjecture','Zhao Song',2026,'https://arxiv.org/abs/2608.01812v1','3 August 2026; introduction, main lifting result and Appendix A; explicit polyloglog-factor refinement claimed in a preprint')],
 status='source_open', status_note='Explicitly open in the August 2026 CCC version of Hambardzumyan–Lovett–Shirley. Checked through 10 September 2026. The established general upper bound is O(√r); recent fixed-polynomial lower-bound refinements and signed-decomposition equivalences do not settle the conjecture.', formulation_reviewed_on='2026-09-10')
