import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('polynomial-time-weighted-falsifiability-unambiguous-dnf',
 id='TCS-0310',title='Is weighted falsifiability of unambiguous DNFs in polynomial time?',
 area='Computational and circuit complexity',criterion='decision',question_type='yes_no',
 formal=r'''Is there a deterministic algorithm, polynomial in the total binary input length, that solves the following problem? The input consists of an unambiguous DNF $F=\bigvee_{j=1}^{m}T_j$ over n Boolean variables, nonnegative integer weights w_1,...,w_n encoded in binary, and an integer threshold t encoded in binary. Decide whether there exists $a\in\{0,1\}^n$ such that $F(a)=0$ and $\sum_{i=1}^{n}w_i a_i\ge t$. Each T_j is an explicitly listed conjunction of literals. Unambiguous means that no assignment satisfies two distinct terms simultaneously.''',
 definitions='A literal is either x_i or its negation. A term is true exactly when all its literals are true; the DNF is true when at least one term is true. Contradictory terms can be discarded. For the remaining terms, unambiguity is equivalent to every pair containing opposite literals on some variable, so this promise is itself checkable in polynomial time. Weights are exact integers, with no rounding. The running time must depend polynomially on their bit lengths rather than on their numerical sum. The threshold uses at least, not exactly; a strict-threshold formulation is equivalent by shifting the integer threshold by one. The output is a yes/no answer. A tautology has no falsifying assignment and always gives no, regardless of the threshold.',
 answer_criterion='Give a polynomial-time decision algorithm for all such inputs, or prove that the decision problem is not in P. An NP-hardness proof would provide a negative answer conditional on P differing from NP; its assumption must be stated. A pseudopolynomial algorithm, a method only for unweighted assignments, or hardness after changing the comparison to exact equality does not settle the specified question.',
 context=[
  paragraph('Unambiguity makes the satisfying regions disjoint. This is useful for counting: after fixing the literals of one consistent term, every remaining variable is free, and the term’s satisfying assignments can be counted directly. Summing across terms gives the total without any inclusion-exclusion correction. Subtracting that count from 2^n decides whether a falsifying assignment exists at all.', 'monet'),
  paragraph('The weighted version asks where the complement lies relative to an additive score. Knowing how many points lie outside the DNF does not reveal whether even one of them has a large score. For example, take F=(x AND y) OR ((NOT x) AND z), whose two terms are incompatible. With weights 8, 3, and 5, the assignment (1,0,1) falsifies F and has score 13. The all-ones assignment has larger score 16 but satisfies F, so unconstrained maximization does not answer the question.'),
  paragraph('There is an important asymmetry between maximizing over satisfying and falsifying assignments. To maximize over satisfying assignments, optimize each term separately by setting every unrestricted positive-weight variable to one, then take the best result. To falsify the DNF, every term must fail at once, and choices made to destroy one term can interact with all the others.'),
  paragraph('Dynamic programming over achievable scores gives a pseudopolynomial algorithm; it becomes polynomial when weights are unary. The missing guarantee is polynomial dependence on binary descriptions of potentially large weights. Amarilli also explains a connection to complementing compiled Boolean representations: efficient complementation into a representation supporting weighted maximization would give an algorithm, while suitable hardness would obstruct that route.', 'questions')],
 why='The problem separates easy counting from optimization on the complement of a simple disjoint representation. It tests whether unambiguity retains its algorithmic value when a compactly encoded additive objective is introduced, and it bears on the power of knowledge-compilation representations under negation.',
 importance=dict(score=74,method='editorial',assessed_on='2026-09-10',reason='A focused but structural tractability question connecting unambiguous representations, binary-weight optimization, and complementation. It has a clear gap between polynomial unweighted methods and an unresolved weighted case.'),
 progress=[
  step('2024-01-04','Monet formulates the binary-weight optimization problem and records NP membership of its decision version, polynomial-time weighted satisfaction, and a pseudopolynomial dynamic program for falsification.','monet'),
  step('2024','The Dagstuhl seminar on database representation and provenance presents this exact question by linking to Monet’s formulation. The catalogue’s separate TCS-0485 record comes from that link.','seminar'),
  step('2026-09-10 check','Amarilli’s maintained list still asks for a polynomial-time weighted-falsifiability algorithm and discusses its connection to complementation of d-DNNFs. Monet’s original question has no posted answer at this check.','questions')],
 references=[
  ref('monet','Is this problem on unambiguous DNFs hard?','Mikaël Monet',2024,'https://cstheory.stackexchange.com/questions/53733/is-this-problem-on-unambiguous-dnfs-hard','Original author’s formulation, 4 January 2024; binary weights and optimization/decision versions'),
  ref('seminar','Representation, Provenance, and Explanations in Database Theory and Logic (Dagstuhl Seminar 24032)','Mikaël Monet (problem contributor)',2024,'https://doi.org/10.4230/DagRep.14.1.49','Section 6.1 points to the original question'),
  ref('questions','List of open questions: Weighted falsifiability for unambiguous DNFs','Antoine Amarilli, with formulation assistance from Mikaël Monet',2026,'https://a3nm.net/work/research/questions/#weighted-falsifiability-for-unambiguous-dnfs','Maintained problem and partial observations, accessed 10 September 2026')],
 status='source_open',status_note='Open in the original 2024 question and the maintained list accessed 10 September 2026. Searches did not locate a polynomial algorithm or hardness resolution. TCS-0485 is a duplicate seminar pointer to the same formulation, not a separate open question.',
 formulation_reviewed_on='2026-09-10')
