import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('general-erdos-hajnal-conjecture',
 id='TCS-6652',title='The Erdős–Hajnal conjecture for every forbidden induced graph',area='Structural graph theory',criterion='construction',question_type='yes_no',
 formal='For every finite undirected simple graph H with at least two vertices, does there exist a real constant c(H)>0 such that every n-vertex undirected simple graph G with n≥1 and no induced copy of H satisfies max{α(G),ω(G)}≥n^{c(H)}?',
 definitions='An induced copy of H is an injective map f:V(H)→V(G) such that distinct u,v are adjacent in H if and only if f(u),f(v) are adjacent in G. Thus both edges and nonedges must match. α(G) is the maximum size of a set of pairwise nonadjacent vertices, and ω(G) is the maximum size of a set of pairwise adjacent vertices. The constant c(H) may depend arbitrarily on the entire fixed graph H, but not on G or n. No density, degree, dimension or algorithmic promise is imposed on G. The claim concerns existence of a clique or independent set, without requiring a polynomial-time construction. A hereditary graph class is one closed under taking induced subgraphs; the class of H-free graphs is hereditary.',
 answer_criterion='Prove the stated bound for every H, or give one fixed finite H and prove that for every c>0 there are arbitrarily large H-free graphs G with max{α(G),ω(G)}<|V(G)|^c. H must remain fixed along a counterexample family. Any positive exponent suffices; determining the optimal exponent is a stronger problem. Results for finitely many H, or bounds of the form exp(o(log n)), do not settle the universal polynomial bound.',
 context=[
  paragraph('Ramsey’s theorem guarantees a clique or independent set of logarithmic size in every sufficiently large graph, and random graphs show that this order of magnitude is unavoidable without further restrictions. Erdős–Hajnal predicts a dramatic change after forbidding even one fixed induced pattern: the guaranteed set should grow as a positive power of the number of vertices. The conjecture therefore asks how much global organization a single local structural exclusion forces.','original'),
  paragraph('For a simple example, a graph with no induced three-vertex path is a disjoint union of cliques. If it has t components, choosing one vertex from each gives an independent set of size t, while the largest component has at least n/t vertices and is a clique. One of these sets has size at least √n. This proves the conjecture for that forbidden graph and illustrates the desired polynomial gain through a structural decomposition.'),
  paragraph('The general theorem of Erdős and Hajnal gives a lower bound exp(c_H√log n). Bucić, Nguyen, Scott and Seymour improve it to exp(c_H√(log n·log log n)) for a positive constant depending on H. Their 2024 journal paper is the first improvement of this general bound. It is still smaller than nᵟ for every fixed δ>0 as n grows, so the extra logarithmic factor does not reach the conjectured scale.','general'),
  paragraph('Closure under complementation and vertex substitution lets proofs for a few building blocks settle many further forbidden graphs. Substitution replaces one vertex by a graph whose vertices all have the same neighbors outside the replacement. The remaining five-vertex building blocks were the bull, the five-cycle and the five-vertex path, together with its complement. Nguyen, Scott and Seymour’s proof for the path, published in March 2026, completes all forbidden graphs on at most five vertices.','p5'),
  paragraph('For longer fixed paths, their separate all-path theorem gives homogeneous sets of size 2^{(log n)^{1−o(1)}}. This is close to the polynomial scale in its exponent but still does not assert n^c for any fixed positive c. In particular, the five-vertex result should not be described as resolving the conjecture for paths of arbitrary length.','paths'),
  paragraph('Huang, Ju and Zhou’s August 2026 revision proves two additional six-vertex cases using an extension of iterative sparsification. The E-graph is a five-vertex path with a new leaf attached to its middle vertex. The Bird starts from a triangle with leaves attached to two different triangle vertices, then extends one of those leaves by one more edge. Both contain an induced five-vertex path, so excluding either permits a larger class than excluding the path itself.','six'),
  paragraph('A 28 August 2026 preprint by Tran and Nguyen reports another six-vertex case, specified without a drawing by vertex set {a,b,c,d,e,f} and edge set {ab,bc,cd,de,af,bf,df}. It develops the comb and sparsification framework further. This is an individual new forbidden pattern, rather than a proof for every six-vertex graph.','third'),
  paragraph('Another strand connects the conjecture with finding large nearly empty or nearly complete induced subgraphs. Bucić, Fox and Pham prove equivalence with polynomial quantitative versions of the Rödl and Nikiforov statements. This makes the problem relevant to structural decompositions and induced-pattern density, beyond locating a single clique or independent set.','equivalence'),
  paragraph('There are also stronger quantitative results under additional hypotheses. Sun, Wang and Zeng’s July 2026 preprint gives exponent at least (Cd)⁻ᵈ for graphs of neighborhood VC-dimension at most d. This dimension bounds the size of a vertex set on which neighborhoods realize every possible subset. Such a restriction controls neighborhood complexity; arbitrary H-free graphs are not assumed to satisfy a fixed VC-dimension bound.','vc')],
 why='A foundational prediction that forbidding any fixed induced pattern forces polynomial-size order inside a graph. Its links to hereditary classes, neighborhood complexity and sparse/dense decompositions make it a central structural question with connections to algorithmic graph theory.',
 importance=dict(score=97,method='editorial',assessed_on='2026-09-10',reason='A major unifying conjecture for hereditary graph classes, with a sharp qualitative gap between general bounds and the target and substantial recent progress on special cases.'),
 progress=[
  step('1989','Erdős–Hajnal’s Ramsey-type theorems establish exp(c_H√log n) and pose the polynomial target.','original'),
  step('2023–2024','Bucić–Nguyen–Scott–Seymour improve the general bound by a √log log n factor in the exponent.','general'),
  step('2024','Bucić–Fox–Pham prove equivalence with polynomial Rödl and Nikiforov formulations.','equivalence'),
  step('2026-03-23','The five-vertex-path theorem is published, completing the property for all forbidden graphs with at most five vertices; the preprint first appeared in December 2023.','p5'),
  step('2026-07-10','Sun–Wang–Zeng sharpen the exponent for graphs of bounded VC-dimension, an additional restriction on the input graphs.','vc'),
  step('2026-08-28','Tran–Nguyen post a proof for the six-vertex graph with edge set {ab,bc,cd,de,af,bf,df}.','third'),
  step('2026-08-31','Huang–Ju–Zhou revise their E-graph and Bird proofs and unified sparsification framework.','six')],
 references=[
  ref('original','Ramsey-type theorems','Paul Erdős; András Hajnal',1989,'https://mathweb.ucsd.edu/~asuk/erdos_hajnal.pdf','Discrete Applied Mathematics 25(1–2):37–52; DOI 10.1016/0166-218X(89)90045-0'),
  ref('general','Induced subgraph density. I. A loglog step towards Erdős–Hajnal','Matija Bucić; Tung Nguyen; Alex Scott; Paul Seymour',2024,'https://arxiv.org/abs/2301.10147','v3, 19 February; IMRN 2024(12):9991–10004, DOI 10.1093/imrn/rnae065; general √(log n log log n) exponent'),
  ref('p5','Induced subgraph density. VII. The five-vertex path','Tung Nguyen; Alex Scott; Paul Seymour',2026,'https://arxiv.org/abs/2312.15333','v3, 23 February; Proceedings of the London Mathematical Society 132(3), e70133, DOI 10.1112/plms.70133; Theorem 1.2, published 23 March'),
  ref('paths','Induced subgraph density. V. All paths approach Erdős–Hajnal','Tung Nguyen; Alex Scott; Paul Seymour',2024,'https://arxiv.org/abs/2307.15032','v2, 21 October; arbitrary fixed paths obtain 2^{(log n)^{1−o(1)}}, not a fixed polynomial exponent'),
  ref('six','Erdős–Hajnal conjecture beyond five-vertex graphs','Shenwei Huang; Yiao Ju; Yidong Zhou',2026,'https://arxiv.org/abs/2606.06258','v3, 31 August; Theorems 1.10 and 1.11 for the E-graph and Bird; first posted 4 June'),
  ref('third','The Erdős–Hajnal Property for the six-vertex Graph with Edge Set {ab,bc,cd,de,af,bf,df}','Viet-Hoang Tran; Tan M. Nguyen',2026,'https://arxiv.org/abs/2608.28551','v1, 28 August; Theorem 1.1 and §1.2 specify the graph and the proof framework'),
  ref('equivalence','Equivalence between Erdős–Hajnal and polynomial Rödl and Nikiforov conjectures','Matija Bucić; Jacob Fox; Huy Tuan Pham',2024,'https://arxiv.org/abs/2403.08303','v2, 19 April; equivalence of the three conjectures, not an unconditional proof of them'),
  ref('vc','A Single-Exponential Erdős–Hajnal Bound for Graphs of Bounded VC-Dimension','Shuang Sun; Yan Wang; Jiasheng Zeng',2026,'https://arxiv.org/abs/2607.09049','v1, 10 July; exponent at least (Cd)⁻ᵈ under bounded neighborhood VC-dimension'),
  ref('claim','On Induced Subgraphs of Finite Graphs not Containing Large Empty and Complete Subgraphs','Gábor Sági',2017,'https://arxiv.org/abs/1211.3876','Historical full-solution claim: v2 withdrawn 24 July 2017; v3, 18 August, offers a revised proof. The author acknowledges a serious error in the 2012 proof. The revised claim was not independently validated in this review; contemporary primary literature still treats the conjecture as open')],
 status='source_open',status_note='Checked through 10 September 2026. The 2026 primary literature explicitly retains the full conjecture as open. Sági’s historical revised claim is recorded separately and is not treated as a verified solution; the withdrawal of its earlier version does not itself refute the revision. New six-vertex and bounded-VC-dimension results have restricted scope.',formulation_reviewed_on='2026-09-10')
