import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('mansour-strong-fourier-concentration',
 id='TCS-6581',title='Mansour’s conjecture with logarithmic accuracy dependence',area='Learning theory',criterion='characterization',question_type='yes_no',
 formal='Does there exist an absolute constant C>0 such that, for every n≥1, integer s≥2, Boolean function f:{−1,1}ⁿ→{−1,1} representable by a DNF with at most s terms, and ε∈(0,1/2], some family F⊆2^[n] satisfies |F|≤⌈s^{C log₂(1/ε)}⌉ and Σ_{S∉F} f̂(S)²≤ε?',
 definitions='A DNF is an OR of conjunctions of literals x_i=1 or x_i=−1; a satisfied formula has value +1 and an unsatisfied formula value −1. Term widths, overlaps, and the number of occurrences of a variable are unrestricted. On the uniform probability space {−1,1}ⁿ, χ_S(x)=∏_{i∈S}x_i, χ_∅=1, and f̂(S)=2^{−n}Σ_x f(x)χ_S(x). Parseval gives Σ_S f̂(S)²=1. Thus ε-concentration on F means that the polynomial g=Σ_{S∈F}f̂(S)χ_S has E[(f−g)²]≤ε. The coefficients are ordinary Walsh coefficients, not a basis adapted to a different distribution. The same C must work for all n,s,ε and f. This is an existence question about the spectrum; no efficient algorithm for finding F is part of the proposition.',
 answer_criterion='An affirmative resolution proves the stated bound with one universal C. A negative resolution must show that for every C some admissible s,n,ε and DNF require more than ⌈s^{C log₂(1/ε)}⌉ coefficients to leave squared Fourier mass at most ε. A polynomial bound whose exponent has an unspecified dependence on ε would settle only the weaker fixed-accuracy form.',
 context=[
 paragraph('A DNF describes a function as a short list of sufficient conditions for acceptance. Its Fourier expansion describes the same function through parity correlations. Mansour’s question asks whether a short description in the first language forces an approximately short description in the second. The number n of available variables may greatly exceed the number s of terms, yet the proposed number of relevant correlations depends only on s and the permitted error.'),
 paragraph('The approximation is measured in squared error under uniformly random inputs. It does not require exact agreement everywhere, and the approximating polynomial need not have Boolean outputs. Keeping the largest squared coefficients is the best approximation with that many Walsh characters. Consequently the question is a statement about how rapidly the sorted Fourier mass decays, independent of an algorithm’s ability to identify the important characters.'),
 paragraph('Sparsity and degree are different resources. A parity involving every variable has just one nonzero Fourier coefficient but has degree n. Conversely, restricting a polynomial to degree d can leave a number of possible coefficients that grows like n^d. A theorem saying that high-degree coefficients have little total mass therefore does not by itself give the requested bound, which must avoid such dependence on the ambient dimension.'),
 paragraph('Even one wide conjunction can have many nonzero coefficients exactly. This does not contradict the conjecture: if the conjunction fixes w distinct coordinates, its satisfying event has probability 2^{−w}. Approximating its ±1-valued function by the constant −1 incurs squared error 4·2^{−w}. Rare accepting terms can therefore produce an exactly dense spectrum while contributing very little approximation error. Combining many overlapping terms is where the simple observation stops being sufficient.'),
 paragraph('There are two common strengths of the named conjecture. The weaker one allows s^{K(ε)} coefficients for an arbitrary function K of the error. The stronger one in this saved record asks for K(ε)=O(log(1/ε)). O’Donnell–Wright–Zhou explicitly distinguish these statements. The card preserves the stronger target instead of treating all polynomial concentration claims as interchangeable.','primary'),
 paragraph('The connection to Fourier entropy explains that distinction. If the Fourier entropy were O(log s), Markov’s inequality applied to the surprisal log(1/f̂(S)²) would capture all but ε of the mass on at most s^{O(1/ε)} coefficients. The Fourier Entropy–Influence conjecture, combined with the influence bound for DNF, would supply such an entropy estimate. This implication gives the weaker form, but its exponent does not establish the logarithmic dependence required here.','primary'),
 paragraph('Mansour’s classical general bound gives s^{O(log log s)} coefficients at fixed accuracy. Klivans–Lee–Wan proved polynomial concentration for a specified random-DNF model and for every fixed read number. These are substantial structural results, but randomness in the formula cannot be assumed in a worst-case statement about every DNF. Their final May 2010 revision corrects an earlier issue in the read-number argument.','ref2'),
 paragraph('Lecomte–Tan sharpen the fixed-accuracy general estimate to s^{O(log log k)}, where k bounds the number of terms containing a variable. Their stronger small-read theorem gives (s/ε)^{O(log(1/ε))} concentration for read number up to a stated roughly doubly logarithmic range. The explicit s/ε base should be retained when comparing accuracy parameters. Their work also explains how control of term covers improves Fourier estimates beyond a single global norm bound.','sharper'),
 paragraph('The learning consequences depend on access to the target. Through the agnostic-learning reduction described by Klivans–Lee–Wan, suitable sparse Fourier approximation yields efficient agnostic learning under the uniform distribution with membership queries, for fixed approximation accuracy. Such queries allow selected input points; they are stronger access than an ordinary stream of independently sampled labeled examples. This conjecture should not be advertised as automatically solving every version of passive DNF learning.','ref2'),
 paragraph('Recent neighboring results retain these distinctions. Han’s 2025 entropy estimate contains an additional sum involving individual influences, rather than the full conjectured constant times total influence. González–MacManus–Pereyra’s June 2026 revision proves FEI for further classes under structural separation conditions. Neither is a universal theorem with the strong DNF accuracy bound in the question.','recentfei'),
 paragraph('Heidari–Khardon’s June 2026 revision studies generalized Fourier representations associated with Bayesian networks. Its DNF learning theorem uses membership queries and a restricted distributional model; its agnostic result concerns decision trees. These changes in basis, distribution and target class are mathematically meaningful, but they do not establish concentration of every DNF in the ordinary uniform Walsh basis used here.','learning')],
 why='A fundamental bridge between short logical formulas, sparse spectral representations, and learning with queries. The strong accuracy parameter makes the question a precise test of how much analytic structure small DNF size forces.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A defining conjecture in Boolean function analysis and learning theory, connecting representation size to approximate Fourier sparsity and agnostic learning.'),
 progress=[step('1992–1995','Mansour obtains general s^{O(log log s)} Fourier concentration for fixed error; the later sources state the full accuracy-dependent bound.','sharper'),step('2010-05-04','Klivans–Lee–Wan’s final ECCC revision proves the random-DNF result and corrects the read-k theorem. The random model does not cover arbitrary formulas.','ref2'),step('2011','O’Donnell–Wright–Zhou explain the weak and strong versions and the weaker accuracy bound implied by FEI.','primary'),step('2021-10-15','Lecomte–Tan’s revision improves dependence on the read number and obtains polynomial concentration for a growing range of small read numbers.','sharper'),step('2025','Han proves a new Fourier entropy bound with additional individual-influence terms; this is partial progress on the broader FEI direction.','han'),step('2026-06-02','Heidari–Khardon revise generalized-Fourier learning results under Bayesian-network distributions; the setting differs from this uniform spectral conjecture.','learning'),step('2026-06-09','González–MacManus–Pereyra extend FEI to further structured classes; no universal DNF concentration theorem is claimed.','recentfei')],
 references=[ref('primary','The Fourier Entropy–Influence Conjecture for certain classes of Boolean functions','Ryan O’Donnell; John Wright; Yuan Zhou',2011,'https://www.ias.edu/sites/default/files/math/ODonnell_Fourier.pdf','Inherited reference; ICALP 2011, pp. 330–341; §1.1 distinguishes strong and weak Mansour conjectures; accessible author copy at https://www.cs.cmu.edu/~jswright/papers/fei.pdf'),ref('ref2','Mansour’s Conjecture is True for Random DNF Formulas','Adam Klivans; Homin K. Lee; Andrew Wan',2010,'https://eccc.weizmann.ac.il/report/2010/023/revision/3/download/','Inherited reference; revision 3, 4 May 2010; Theorems 1–2 and learning consequences; final revision restores a corrected read-k argument'),ref('sharper','Sharper bounds on the Fourier concentration of DNFs','Victor Lecomte; Li-Yang Tan',2021,'https://arxiv.org/abs/2109.04525v2','FOCS 2021; revision 15 October 2021; introduction, Theorems 1–2 and precise parameter bounds'),ref('han','A New Bound for the Fourier-Entropy-Influence Conjecture','Xiao Han',2025,'https://link.springer.com/article/10.1007/s00493-024-00133-z','Combinatorica 45, article 4; online 20 December 2024; entropy bound includes Σ_i I_i(f)log(1/I_i(f))'),ref('recentfei','Further evidence towards the Fourier Entropy-Influence conjecture','María José González; Paul MacManus; María Cristina Pereyra',2026,'https://arxiv.org/abs/2606.00246v2','Posted 29 May, revised 9 June 2026; new structured Boolean-function classes, not all DNF'),ref('learning','Learning DNF through Generalized Fourier Representations','Mohsen Heidari; Roni Khardon',2026,'https://arxiv.org/abs/2506.01075v2','First posted 1 June 2025; revision 2 June 2026; Bayesian-network Fourier basis, DNF learning with queries, and separate agnostic decision-tree results')],
 status='source_open',status_note='Open in the strong logarithmic-accuracy form stated here, following the inspected primary sources and a later-result search through 11 September 2026. Fixed-error polynomial concentration, restricted DNF models, and generalized-basis learning results do not by themselves settle this formulation.',formulation_reviewed_on='2026-09-11')
