import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('polynomial-size-arithmetic-formulas-for-determinant',
 id='TCS-6613',title='Polynomial-size arithmetic formulas for the determinant',area='Algebraic computation',criterion='resources',question_type='yes_no',
 formal='Do there exist constants K,C≥1 such that for every n≥1 the symbolic determinant Det_n(X)=Σ_{π∈S_n}sgn(π)∏_{i=1}^n x_{i,π(i)} has an arithmetic formula over the complex numbers with at most K n^C nodes?',
 definitions='The n² entries x_{ij} of X are distinct commuting indeterminates. S_n is the set of permutations of [n], and sgn(π) is +1 or −1 according to the parity of π. An arithmetic formula is a rooted binary tree. Leaves are labelled by input variables or arbitrary constants from ℂ; internal nodes apply addition, subtraction or multiplication. The output must equal Det_n as a formal polynomial in ℂ[x_{11},…,x_{nn}]. Size counts every node, including each repeated occurrence of a variable, constant or copied subformula. Intermediate results cannot be shared between different parents. Constants are charged unit size, without a bound on their bit description; this is nonuniform algebraic complexity, so no algorithm generating the family is required. Division, comparisons, branching and input-dependent constants are not allowed. Intermediate polynomials may contain higher powers of individual variables and cancellations of those powers; only the final polynomial is required to be the determinant. There is no multilinearity, homogeneity, fixed-depth, monotonicity or bounded-coefficient restriction on intermediate computation. The fixed field ℂ is an explicit characteristic-zero specialization of the inherited question.',
 answer_criterion='Exhibit polynomial-size formulas with one fixed size exponent for all n, or prove that the minimum formula-size function is not bounded by any polynomial: for every K,C≥1 there is an n for which every allowed formula has more than K n^C nodes. A fixed-power lower bound such as Ω(n³) is insufficient to refute polynomial size. A lower bound restricted to multilinear formulas, noncommuting variables, or bounded depth does not settle this unrestricted commutative formula question.',
 context=[
 paragraph('The determinant is computationally easy when an algorithm may save intermediate work and reuse it. A formula imposes a stricter discipline: each computed quantity has only one consumer. To use the same expression twice, the expression must be copied. This can turn a compact computation graph into a much larger tree. The problem asks whether the determinant has an alternative expression that avoids this potential blow-up.'),
 paragraph('The familiar permutation expansion has n! terms, but this does not prove that every formula is that large. Algebraic identities can compress a sum dramatically, just as a product of short sums can represent many expanded monomials. Conversely, Gaussian elimination is not itself a small formula: its usual presentation reuses entries, performs divisions and selects pivots. Its numerical running time therefore cannot answer the stated symbolic question.'),
 paragraph('Berkowitz’s division-free construction gives polynomial-size arithmetic circuits of depth O(log² n). Unfolding a bounded-fan-in circuit of that depth into a tree gives a formula of size 2^{O(log² n)}=n^{O(log n)}. This is quasipolynomial, already far below the permutation expansion, but still larger than a fixed power of n. A polynomial-size formula would close this remaining gap.','parallel'),
 paragraph('The determinant is also a complete problem for polynomial-size algebraic branching programs, whose outputs are sums of products of edge labels along directed source-to-sink paths. Consequently, polynomial-size determinant formulas would imply VF=VBP: every polynomial family having polynomial-size branching programs would have polynomial-size formulas. The larger class VP allows general arithmetic circuits. The June 2026 factoring primer still lists VF⊆VBP⊆VP without a known strict containment and explicitly leaves small determinant formulas unresolved.','primer'),
 paragraph('An unrestricted lower bound is known, but it is only a fixed power. Kalorkoti proves Ω(n³) formula size for the n by n determinant, even in a model allowing division. Here n is the matrix dimension; there are n² independent variables. Thus the bound is cubic in dimension and only a power 3/2 in the number of variables. It must not be described as a cubic lower bound in the input-variable count.','cubic'),
 paragraph('Raz proves a much stronger n^{Ω(log n)} lower bound when every intermediate polynomial is multilinear. This restriction is substantive even though the final determinant is multilinear. For a simple illustration, (x+y)²−x²−y² equals 2xy, a multilinear output obtained through nonmultilinear intermediate terms. The example does not establish a size advantage, but it shows why output multilinearity alone cannot justify applying a theorem that assumes multilinearity throughout a computation.','multilinear'),
 paragraph('Recent progress tests which determinant features are needed for that restricted lower bound. Boyapati, Chillara and Vempati prove the existence of sparse n by n symbolic matrices with only Θ(n log⁶ n) nonzero entries whose determinants still require n^{Ω(log n)} multilinear formulas. This shows that the dense n²-variable presentation is not essential to Raz’s obstruction. It leaves the permission to use nonmultilinear intermediate computations untouched.','sparse'),
 paragraph('The question also organizes complexity outside generic matrices. Chaugule and coauthors connect small formulas for Schur polynomials and generalized Vandermonde determinants to small formulas for the general determinant. Such reductions make the determinant a useful benchmark for whether apparently special algebraic expressions really admit efficient tree computations. A separation would reveal a basic cost of forbidding reuse, already within problems that possess efficient arithmetic circuits.','schur')],
 why='The canonical test of whether reusing intermediate expressions gives a superpolynomial advantage over arithmetic expression trees, even for an efficiently computable polynomial.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A fundamental separation inside algebraic computation, equivalent to the formula-versus-branching-program question through determinant completeness and linked to many explicit polynomial families.'),
 progress=[
 step('1984','Berkowitz gives division-free polynomial-size, O(log² n)-depth determinant circuits; unfolding yields quasipolynomial-size formulas.','parallel'),
 step('1985','Kalorkoti proves an unrestricted Ω(n³) formula lower bound for an n by n determinant, also allowing division.','cubic'),
 step('2003–2009','Raz establishes n^{Ω(log n)} lower bounds for formulas that remain multilinear at every gate; the original ECCC report precedes the journal publication.','multilinear'),
 step('2019-11-28','Chaugule and coauthors relate formula complexity of Schur polynomials and generalized Vandermonde determinants to the generic determinant.','schur'),
 step('2026-06-02','Boyapati–Chillara–Vempati’s sparse-determinant preprint retains the strong multilinear lower bound with Θ(n log⁶ n) nonzero entries; it appears at CCC 2026.','sparse'),
 step('2026-06-12','The updated factoring primer explicitly records that polynomial-size symbolic determinant formulas are still unknown, despite new formula-factoring results.','primer')],
 references=[
 ref('parallel','On computing the determinant in small parallel time using a small number of processors','Stuart J. Berkowitz',1984,'https://www.sciencedirect.com/science/article/pii/0020019084900188','Information Processing Letters 18(3), 147–150; division-free circuits over commutative rings, size polynomial and depth O(log² n)'),
 ref('cubic','A Lower Bound for the Formula Size of Rational Functions','K. A. Kalorkoti',1985,'https://epubs.siam.org/doi/10.1137/0214050','SIAM Journal on Computing 14(3), 678–687; Ω(n³) for n by n determinant; the publisher’s 2006 online date is not the publication year'),
 ref('multilinear','Multi-Linear Formulas for Permanent and Determinant are of Super-Polynomial Size','Ran Raz',2003,'https://eccc.weizmann.ac.il/report/2003/067/','TR03-067, posted 9 September 2003; Sections 1–1.2 define intermediate multilinearity and distinguish it from general formulas; journal version JACM 56(2), 2009'),
 ref('schur','Schur Polynomials do not have small formulas if the Determinant doesn’t!','Prasad Chaugule; Mrinal Kumar; Nutan Limaye; Chandra Kanta Mohapatra; Adrian She; Srikanth Srinivasan',2019,'https://arxiv.org/abs/1911.12520','First preprint, 28 November; determinant-related conditional formula lower bounds for Schur and generalized Vandermonde families'),
 ref('sparse','Multilinear Formula Lower Bounds for Sparse Determinants','Pruthvi Boyapati; Suryajith Chillara; Pratyush Vempati',2026,'https://eccc.weizmann.ac.il/report/2026/090/','Submitted 30 May, posted 2 June; CCC 2026 article 33; existence of sparse matrices and restricted multilinear-formula lower bounds'),
 ref('primer','A primer on the closure of algebraic complexity classes under factoring','C. S. Bhargav; Prateek Dwivedi; Nitin Saxena',2026,'https://eccc.weizmann.ac.il/report/2025/083/revision/1/download/','Revision 1, 12 June; Definition 7.2, Remark 7.3 and printed page 54 explicitly retain the determinant-formula problem')],
 status='source_open',status_note='The June 2026 primary survey explicitly retains the question. Sparse and dense multilinear lower bounds do not apply to unrestricted intermediate computations, and recent factoring progress does not furnish determinant formulas. Checked through 11 September 2026.',formulation_reviewed_on='2026-09-11')
