import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('bin-packing-universal-constant-additive-approximation',
 id='TCS-6640',title='Constant additive error for one-dimensional bin packing',area='Scheduling and packing',criterion='resources',question_type='yes_no',
 formal='Do a universal integer C≥0 and a randomized polynomial-time algorithm exist that pack every explicitly listed one-dimensional bin-packing instance into at most OPT+C unit-capacity bins with probability at least 2/3?',
 definitions='The input is a list of n≥1 rational item sizes s₁,…,s_n∈(0,1], each encoded as a binary numerator and positive binary denominator; L is the total encoding length. A feasible packing is a map b:[n]→[k] with Σ_{i:b(i)=j}s_i≤1 for every bin j. OPT is the minimum feasible integer k. The algorithm is uniform and classical, has access to the entire input before assigning items, and must output an explicit feasible packing. For absolute constants K,d, every execution must take at most KL^d bit operations. Its output is always feasible, and on each fixed input it uses at most OPT+C bins with probability at least 2/3 over its private random bits. C,K,d are independent of n, the number of distinct sizes, OPT and coefficient precision. No capacity augmentation, splitting of items, cardinality constraint or promise on the input distribution is allowed. Repeated items are explicitly listed rather than represented by binary multiplicities. Randomization is expressly allowed; a deterministic algorithm would also resolve the question.',
 answer_criterion='Give one algorithm with a fixed additive constant on all instances and the stated complexity and success guarantees, or establish a lower bound excluding every such constant for this model. Conditional impossibility must identify its computational assumption. A guarantee OPT+O(log OPT), an asymptotic ratio 1+ε with ε-dependent additive loss, or a result with a fixed number of item types does not establish the target.',
 context=[
 paragraph('The objective is to minimize the number of identical containers needed to hold indivisible items. Each bin has a single numerical capacity constraint, so the model contains no geometric placement issue. Nevertheless, many different combinations of small and large items can fit exactly or almost exactly, and choices that look locally efficient can leave unusable capacity elsewhere. The inherited invited survey explicitly asks for an OPT+O(1) guarantee.','primary'),
 paragraph('Additive and multiplicative errors behave differently as the optimum grows. A one-percent excess can mean thousands of unnecessary bins on a large instance; an additive constant remains fixed. Conversely, this card allows any universal constant, even a very large one. It does not ask for an additive-one algorithm or for exact optimization on small instances.'),
 paragraph('The elementary hardness example is distinguishing instances needing two bins from those needing three, through Partition. This rules out exact polynomial optimization under the usual complexity assumptions, but it does not settle constant additive approximation. With allowance C=1, a valid three-bin answer is permitted in both cases. A stronger hardness argument would need a gap that survives the particular additive allowance.','primary'),
 paragraph('Asymptotic approximation schemes achieve a ratio approaching one, with additional losses depending on their accuracy parameter. This does not automatically give OPT+C. Choosing ε on the order of 1/OPT makes ε·OPT small, but the additive term and the running time may worsen as ε shrinks. The dependence on every parameter must be controlled simultaneously; the existence of a scheme alone does not establish the desired fixed loss.'),
 paragraph('A major route uses the Gilmore–Gomory configuration LP. A configuration specifies a multiset of item types that fits in one bin. The LP permits fractional numbers of such bins while covering all required items. Its optimum OPT_f is a lower bound on the integral optimum. Karmarkar–Karp obtain a polynomial-time packing with O(log² OPT) additive loss by combining approximate LP optimization with repeated rounding.','loggap'),
 paragraph('Hoberg–Rothvoss improve the guarantee to OPT_f+O(log OPT_f), and hence OPT+O(log OPT). Their Theorem 2 gives randomized expected polynomial time in the number of explicitly represented items, with the usual accounting for encoded numerical data. Packing first into intermediate containers, and then into bins, improves how rounding errors accumulate. This is the logarithmic-additive general algorithmic benchmark found in the checked literature.','loggap'),
 paragraph('A constant additive LP integrality gap is a related mathematical conjecture, but it is not identical to this card. An efficiently constructible packing within a constant of OPT_f would suffice. A nonconstructive proof of a small gap would still need an algorithmic rounding step. Conversely, an unbounded gap for this LP would not rule out a different algorithm whose guarantee is measured against the true integral optimum.'),
 paragraph('Discrepancy results explain why several familiar approaches encounter barriers. Eisenbrand–Pálvölgyi–Rothvoß connect a restricted bin-packing relaxation to discrepancy of three permutations. Their revised paper also proves limitations for a class of algorithms based on rounding item sizes upward. Those limitations concern specified techniques, rather than all algorithms for the original packing problem.','discrepancy'),
 paragraph('Newman–Nikolov disprove the conjecture that three permutations always have constant discrepancy, constructing examples requiring Ω(log n). This eliminates one proposed route to a constant additive bound. It does not itself provide numerical item sizes with a growing bin-packing integrality gap, and it does not show that every polynomial-time packing algorithm must lose logarithmically many bins.','permutations'),
 paragraph('Recent work also settles nearby structural questions. Jansen–Pirotton–Tutas’s ESA 2025 paper constructs bin-packing instances requiring exponentially many distinct configurations as a function of the number of item types. Its discussion records an OPT+1 algorithm whose runtime depends heavily on that parameter. Exponential support in the number of types does not contradict a polynomial algorithm in an explicit list of all items, and a parameter-dependent additive-one algorithm is not uniformly polynomial as the number of types grows.','support'),
 paragraph('The ICALP 2026 work of Jansen–Ohnesorge–Pirotton proves a tight ETH-based lower bound for the dependence on the number of types in a high-multiplicity exact algorithmic regime. Binary multiplicities can encode far more items than the input length. Both the compressed input model and exact optimization differ from the constant-additive, explicitly listed target here. The result should therefore not be reported as a negative answer to this question.','highmultiplicity'),
 paragraph('This problem isolates how close efficient approximation can come to an integral packing optimum. A constant-additive algorithm would show that all unavoidable combinatorial inefficiency can be confined to a bounded number of extra bins, regardless of instance size. A general impossibility theorem would establish a meaningful approximation barrier beyond the standard two-versus-three-bin hardness example.')],
 why='A basic boundary between asymptotic approximation and almost exact combinatorial optimization: can efficient packing lose only a fixed number of bins on every instance?',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A longstanding central problem in approximation algorithms, with connections to configuration LPs, discrepancy and the computational effect of input encoding.'),
 progress=[step('1982','Karmarkar–Karp obtain polynomial-time bin packing with O(log² OPT) additive loss.','loggap'),step('2011–2012','Permutation-discrepancy connections and lower bounds for specified item-rounding methods identify barriers to several approaches.','discrepancy'),step('2011','Newman–Nikolov construct three permutations requiring Ω(log n) discrepancy, refuting Beck’s conjecture.','permutations'),step('2014','Bansal’s invited survey explicitly lists OPT+O(1), and even OPT+1, as open algorithmic targets.','primary'),step('2015–2017','Hoberg–Rothvoss give an OPT_f+O(log OPT_f) packing algorithm; preprint 2015, SODA 2017.','loggap'),step('2025','Jansen–Pirotton–Tutas prove exponential configuration support in the number of item types.','support'),step('2026','Jansen–Ohnesorge–Pirotton establish a tight ETH-based lower bound for high-multiplicity exact bin packing in the stated parameter regime, without resolving constant additive approximation.','highmultiplicity')],
 references=[ref('primary','New Developments in Iterated Rounding (Invited Talk)','Nikhil Bansal',2014,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.FSTTCS.2014.1','Inherited source; FSTTCS 2014, 1–10; §2.3, page 5, states the constant-additive algorithm question'),ref('loggap','A Logarithmic Additive Integrality Gap for Bin Packing','Rebecca Hoberg; Thomas Rothvoss',2017,'https://arxiv.org/abs/1503.08796','Preprint dated 30 March 2015; SODA 2017; Theorem 2, §1.1 and explicit-item-count convention in §2'),ref('discrepancy','Bin Packing via Discrepancy of Permutations','Friedrich Eisenbrand; Dömötör Pálvölgyi; Thomas Rothvoß',2012,'https://arxiv.org/abs/1007.2170','SODA 2011 precursor; journal-version v2 dated 2 February 2012; restricted rounding-method lower bounds'),ref('permutations','A counterexample to Beck’s conjecture on the discrepancy of three permutations','Alantha Newman; Aleksandar Nikolov',2011,'https://arxiv.org/abs/1104.2922','Posted 14 April 2011; discrepancy lower bound, not a general bin-packing lower bound'),ref('support','The Support of Bin Packing Is Exponential','Klaus Jansen; Lis Pirotton; Malte Tutas',2025,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ESA.2025.48','ESA 2025; distinct-configuration support lower bound and introduction’s parameter-dependent OPT+1 algorithm'),ref('highmultiplicity','A Tight Double-Exponential Lower Bound for High-Multiplicity Bin Packing','Klaus Jansen; Felix Ohnesorge; Lis Pirotton',2026,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2026.116','ICALP 2026; arXiv 2512.02691 v3 dated 18 May 2026; exact compressed-input complexity, with the FPT question distinguished in the conclusion')],
 status='source_open',status_note='Reviewed through 11 September 2026. No universal constant-additive polynomial-time algorithm or general impossibility result was found in the checked primary sources. The logarithmic-additive guarantee and recent high-multiplicity/support results do not settle this explicitly listed, randomized formulation.',formulation_reviewed_on='2026-09-11')
