import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('orthogonal-vectors-hypothesis-logarithmic-dimension',
 id='TCS-6596',title='The Orthogonal Vectors Hypothesis',area='Fine-grained complexity',criterion='decision',question_type='yes_no',
 formal='Is it true that for every ε∈(0,1) there is a fixed integer c≥1 for which no uniform randomized word-RAM algorithm decides bichromatic Orthogonal Vectors on two lists of n vectors in {0,1}^d, with d=⌈c log₂ n⌉, in worst-case time O(n^{2−ε}) and with error probability at most 1/3 on every input?',
 definitions='Here n≥2 and the two input lists A and B each have length n; repeated vectors are allowed. The answer is YES exactly when some a∈A and b∈B satisfy Σ_{j=1}^d a_j b_j=0 as an integer sum, equivalently their supports are disjoint. This is not an inner product over the field with two elements. Inputs are explicitly supplied as packed binary vectors. Computation uses a uniform classical RAM with words of Θ(log(n+d)) bits, ordinary constant-time word arithmetic, Boolean operations, shifts, comparisons, memory access and generation of a random word. Each program uses a fixed word-length constant; arbitrary-precision unit-cost operations, nonuniform advice and free preprocessing tables are excluded. Reading, preprocessing and all subsequent computation count in the time bound. For fixed ε and c, hidden time constants and the program may depend on these parameters, but not on n. There is no promise on vector weights, overlap or input distribution. Randomness is internal to the algorithm; correctness must hold for every pair of lists.',
 answer_criterion='Prove the stated lower-bound proposition, or refute it by exhibiting one fixed ε>0 such that for every fixed integer c≥1 an algorithm A_c meets the n^{2−ε} time and error bounds. This quantifier order matters: the algorithms and constants may depend on c, but the exponent saving ε must work for every c. Giving a different positive saving ε_c that tends to zero with c, shaving logarithmic factors from quadratic time, or proving lower bounds only for restricted circuit models does not settle the proposition.',
 context=[
 paragraph('Each vector can be viewed as a subset of a universe of d coordinates. The task is to find a disjoint pair across two collections. Although checking one pair is easy, there are n² possible pairs. For logarithmic dimension, packed coordinates make a single check take only a constant number of machine operations when c is fixed. The hypothesis asks whether there is an unavoidable exponent arbitrarily close to two as that fixed dimension constant grows.'),
 paragraph('The dependence on c is the main subtlety. There are already truly subquadratic algorithms for each fixed c, with a saving that can deteriorate as c increases. The polynomial-method algorithm of Abboud, Williams and Yu runs in time n^{2−1/O(log c)} in the relevant large-c regime. This is consistent with the hypothesis: selecting a sufficiently large c can make that known saving smaller than any proposed universal ε. The source is SODA 2015; some later bibliographies mistakenly label it 2014.','polynomial'),
 paragraph('Very small dimension permits another strategy: enumerate possible coordinate patterns and aggregate the input instead of considering all pairs separately. The 2026 low-dimensional algorithms achieve a randomized bound of Õ(1.25^d n), with a further reported O(1.16^d n) bound obtained through computer-aided parameter evaluation. These improve the useful range of the pattern-based approach, but their exponential dependence on d becomes a power of n when d=c log₂ n.','lowdim'),
 paragraph('For example, substituting c=2 into 1.25^d n gives, up to constant and logarithmic factors, n^{1+2 log₂ 1.25}, whose exponent is about 1.644. Increasing c increases this exponent. Thus an impressive subquadratic algorithm for one small logarithmic dimension does not supply one exponent saving for all logarithmic dimensions. This numerical example illustrates the quantifiers; it is not an additional algorithmic theorem.'),
 paragraph('The hypothesis is useful because disjointness can encode compatibility between partial solutions. In the standard split-and-list SAT reduction, each half-assignment produces a vector marking clauses it fails to satisfy. Two half-assignments extend to a satisfying assignment exactly when their vectors are disjoint. Sparsification controls the number of clause coordinates. For the randomized version stated here, the corresponding randomized Strong Exponential Time Hypothesis supplies a conditional justification; a deterministic-only SAT assumption must not silently be used to exclude randomized solvers.','concrete'),
 paragraph('Reductions then transfer the conjectured time barrier to problems that look quite different. Rohatgi’s Earth Mover Distance paper, the inherited source for this record, develops one such geometric application. The significance of OV is its role as a common intermediate problem: a new algorithm can overturn a collection of conditional barriers, while an unconditional proof would establish a strong lower bound for a concrete problem already known to be in polynomial time.','emd'),
 paragraph('Restricted-model lower bounds provide evidence without establishing that unrestricted conclusion. Choudhury and coauthors prove near-quadratic monotone-circuit lower bounds for the negation of OV at logarithmic dimension. This negated predicate says every cross-pair intersects and is monotone in the input bits. Their July 2026 paper also strengthens formula and branching-program bounds. General RAM programs can use operations and intermediate representations beyond those restrictions, so these theorems do not prove the hypothesis as formulated here.','concrete'),
 paragraph('Distributional improvements are a separate frontier. Alman, Andoni and Zhang obtain faster algorithms when vector coordinates are independently sampled with a specified Bernoulli bias, including difficult parameter ranges. Such a result can explain why random instances are easier while leaving adversarial instances unresolved. The card deliberately requires correctness and the stated running time on every input rather than only on a random input distribution.','average')],
 why='A basic disjointness problem anchors a large part of fine-grained complexity. Settling its uniform exponent barrier would reshape conditional lower bounds for strings, geometry and data structures.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='One of the principal hypotheses organizing polynomial-time lower bounds across multiple algorithmic areas, with an elementary explicit task and precise dimension dependence.'),
 progress=[
 step('2015','Abboud–Williams–Yu obtain dimension-dependent truly subquadratic algorithms via the polynomial method; the exponent saving decreases with the dimension constant.','polynomial'),
 step('2019','Rohatgi develops OV-based conditional hardness for exact Earth Mover Distance, illustrating geometric consequences.','emd'),
 step('2024-10-29','Alman–Andoni–Zhang improve average-case OV algorithms; the work appears at SOSA 2025.','average'),
 step('2026-07-01','Dürr–Kipouridis–Lampis–Węgrzycki present Õ(1.25^d n) randomized low-dimensional algorithms at ICALP, with a computer-aided O(1.16^d n) refinement.','lowdim'),
 step('2026-07-26','Choudhury and coauthors establish the logarithmic-dimension monotone-circuit version for the negated predicate and strengthen other restricted-model lower bounds.','concrete')],
 references=[
 ref('polynomial','More Applications of the Polynomial Method to Algorithm Design','Amir Abboud; Ryan Williams; Huacheng Yu',2015,'https://theory.stanford.edu/~yuhch123/files/faster-orthog-soda.pdf','SODA 2015, 218–230; abstract and Boolean Orthogonal Detection theorem'),
 ref('emd','Conditional Hardness of Earth Mover Distance','Dhruv Rohatgi',2019,'https://arxiv.org/abs/1909.11068','APPROX/RANDOM 2019 article 12; exact-distance OVH consequences; approximation hardness also uses a different Hitting Set assumption'),
 ref('average','Faster Algorithms for Average-Case Orthogonal Vectors and Closest Pair Problems','Josh Alman; Alexandr Andoni; Hengjie Zhang',2025,'https://arxiv.org/abs/2410.22477','v1, 29 October 2024; SOSA 2025; independent Bernoulli-coordinate input model'),
 ref('lowdim','Faster Algorithms for k-Orthogonal Vectors in Low Dimension','Anita Dürr; Evangelos Kipouridis; Michael Lampis; Karol Węgrzycki',2026,'https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ICALP.2026.85','Published 1 July; Theorem 1.1 and introduction; one-sided error and computer-aided constant refinement'),
 ref('concrete','New and Improved Concrete Lower Bounds for Orthogonal Vectors','Tameem Choudhury; Nutan Limaye; Karteek Sreenivasaiah; Srikanth Srinivasan',2026,'https://arxiv.org/abs/2607.23799','v1, 26 July; Conjecture 1, Theorem 5 and restricted-model discussion; no unrestricted word-RAM lower bound')],
 status='source_open',status_note='The July 2026 primary literature explicitly states the unrestricted OV conjecture as open while proving restricted-model variants. Low-dimensional and average-case improvements do not negate its quantifier order. Checked through 11 September 2026.',formulation_reviewed_on='2026-09-11')
