import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('crouzeix-sharp-two-spectral-set',
 id='TCS-6579',title='Crouzeix’s sharp numerical-range inequality',area='Optimization and numerics',criterion='tightness',question_type='yes_no',
 formal='For every integer n≥1, every complex matrix A∈C^{n×n}, and every scalar polynomial p∈C[z], does ‖p(A)‖₂≤2 max_{z∈W(A)}|p(z)| hold?',
 definitions='The numerical range is W(A)={x*Ax:x∈C^n,‖x‖₂=1}, where x* denotes conjugate transpose and ‖x‖₂ is the Euclidean norm. The matrix norm is its induced spectral norm, ‖B‖₂=max_{‖x‖₂=1}‖Bx‖₂. For p(z)=Σ_{j=0}^m c_j z^j, define p(A)=Σ_{j=0}^m c_j A^j with A⁰=I. There is no restriction on degree, coefficients, normality, diagonalizability or dimension, and no coordinate-encoding assumption. W(A) is compact, so the scalar maximum exists. The coefficient 2 must work universally. This is the scalar-polynomial conjecture. It does not assert the stronger complete inequality for matrices of polynomials [p_ij], where one compares the norm of the block matrix [p_ij(A)] with max_{z∈W(A)}‖[p_ij(z)]‖₂ for all block sizes.',
 answer_criterion='The requested universal inequality is affirmative in the July–August 2026 proofs described below. A negative answer would require a finite complex matrix and scalar polynomial violating it. The constant cannot be reduced: for J=[[0,1],[0,0]] and p(z)=z, ‖J‖₂=1 and max_{W(J)}|z|=1/2. This historical problem is retained with resolved status; the stronger complete conjecture is not silently substituted for its original target.',
 context=[
 paragraph('This saved open problem has been resolved in the scalar form stated here, according to two 2026 proof manuscripts and an explicit expert assessment. Jin’s first preprint was posted on July 27, and Lorist–Schwenninger’s independent proof on August 4. In an August 15 report, Townsend and Greenbaum state that they and Crouzeix checked Jin’s argument thoroughly and believe it correct. The catalogue therefore marks this entry resolved while recording that formal journal review was still pending in the inspected repository.','assessment'),
 paragraph('The underlying issue is the behavior of functions of a nonnormal matrix. For a normal matrix, a unitary diagonalization reduces the norm of p(A) to the largest |p(λ)| over eigenvalues λ. For a nonnormal matrix, eigenvalues alone can miss substantial amplification. The nilpotent matrix J in the answer criterion has only the eigenvalue zero, yet J itself has norm one. Taking p(z)=z shows why a bound based only on scalar values at the spectrum cannot work universally.'),
 paragraph('The numerical range incorporates all quadratic forms x*Ax on unit vectors, rather than only eigenvectors. For the same J, x*Jx=conjugate(x₁)x₂. Its maximum modulus is 1/2, attained when the two coordinates have equal modulus. Thus replacing the spectrum by the numerical range gives meaningful information, but still requires the factor two. This small example establishes sharpness independently of the general proof.'),
 paragraph('A numerical-range estimate transfers scalar approximation to matrix approximation. For example, if two scalar polynomials p and q differ by at most ε throughout W(A), the theorem gives ‖p(A)−q(A)‖₂≤2ε. That is useful when a matrix polynomial is applied to a vector: the same bound controls the resulting vector error relative to its norm. The role in matrix functions and polynomial or rational Krylov methods is discussed in the expert report.','assessment'),
 paragraph('The dimension-independent nature of the constant was already a major achievement before sharpness was settled. Crouzeix obtained the bound 11.08 in 2007, and Crouzeix–Palencia reduced it to 1+√2 in 2017. The inherited Ransford–Schwenninger paper clarifies the latter proof using the numerical-range functional calculus. The remaining gap from approximately 2.414 to 2 was small numerically but resisted the existing estimates.','primary'),
 paragraph('Jin’s proof uses a positive-real completion theorem for a matrix-valued function. In the August 7 version, the key argument is organized around an auxiliary eigenbasis and a mass parameter; the numerical-range double-layer construction has mass two. The manuscript then uses approximation by matrices with simple spectrum and suitable convex outer domains to obtain the general statement. The theorem itself is stated for every finite complex matrix and scalar polynomial, exactly matching this card.','jin'),
 paragraph('Lorist and Schwenninger use an operator-theoretic perturbation lemma. In their notation, T has a contraction dilation with error terms E_n=2V*Q^{*n}V−T^{*n}. Uniform boundedness of these errors and their commutation with T force ‖T‖≤2. Their proof exploits all powers n through a telescoping estimate, rather than only the first power. Applying this to T=f(A) and the double-layer representation proves the scalar spectral-set bound.','lorist'),
 paragraph('The two arguments are valuable for more than lowering a constant: they identify additional structure in the earlier functional-calculus estimates that had not been sufficient when used one power at a time. The Lorist–Schwenninger manuscript explicitly acknowledges Jin’s independent proof, and its August 17 revision adds exposition and remarks rather than a restriction to a special matrix class. The exact scalar theorem and main lemma were inspected for this catalogue; no local Lean verification was performed.','lorist'),
 paragraph('The complete version remains a separate question because it asks for a bound after replacing scalar polynomial values by matrices of polynomial values, uniformly in that additional matrix size. A proof for each scalar p does not automatically supply this stronger simultaneous norm estimate. Åhag, Czyż and Virtanen’s September 9, 2026 revision proves the complete conjecture for matrices A of order at most three and develops related square-function estimates. That result must not be presented as the all-dimensional complete theorem.','complete'),
 paragraph('The original question is retained because it records a fundamental sharp relation between a scalar geometric set and nonnormal matrix computation, together with a very recent change in mathematical status. It also provides a useful test of catalogue freshness: an entry based only on the 2018 or 2024 references would incorrectly describe the scalar conjecture as still open. New work on complete bounds or related spectral sets should receive its own precise statement.')],
 why='A sharp dimension-independent bridge from scalar approximation on the numerical range to norms of functions of nonnormal matrices; retained as a recently resolved foundational problem.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='Historically central in numerical linear algebra and operator theory, with direct relevance to matrix approximation; resolved scalar status keeps it after remaining open questions in category ordering.'),
 progress=[step('2004–2007','Crouzeix formulates the conjecture and obtains the first dimension-independent constant 11.08; the inherited 2018 paper records the foundation.','primary'),step('2017–2018','Crouzeix–Palencia prove the constant 1+√2; Ransford–Schwenninger clarify that argument.','primary'),step('2024','O’Loughlin–Virtanen develop results for classes of matrices; this inherited reference predates the general resolution.','ref2'),step('2026-07-27','Jin posts The Numerical Range Is a 2-Spectral Set, proving the scalar constant two; the inspected latest version is August 7.','jin'),step('2026-08-04','Lorist–Schwenninger post an independent scalar proof via a perturbation lemma for 2-dilations; inspected revision August 17.','lorist'),step('2026-08-15','Townsend–Greenbaum report that they and Crouzeix have checked Jin’s proof and believe it correct.','assessment'),step('2026-09-09','Åhag–Czyż–Virtanen’s revision addresses the stronger complete conjecture through dimension three; this is distinct from the now-resolved scalar question.','complete')],
 references=[ref('primary','Remarks on the Crouzeix–Palencia Proof that the Numerical Range is a (1+√2)-Spectral Set','Thomas Ransford; Felix L. Schwenninger',2018,'https://ris.utwente.nl/ws/portalfiles/portal/171656886/17m1143757.pdf','Inherited reference; SIAM Journal on Matrix Analysis and Applications 39(1), 342–345; DOI 10.1137/17M1143757'),ref('ref2','Crouzeix’s conjecture for classes of matrices','Ryan O’Loughlin; Jani Virtanen',2024,'https://www.sciencedirect.com/science/article/pii/S0024379523004585','Inherited reference; Linear Algebra and its Applications 697, 277–292; restricted-class work predating the 2026 resolution'),ref('jin','The Numerical Range Is a 2-Spectral Set','Shanmu Jin',2026,'https://www.preprints.org/manuscript/202607.1919/v4','First posted 27 July; version 4 posted 7 August 2026; Theorem 1 gives the exact finite-dimensional scalar inequality; preprint, journal peer review pending'),ref('lorist','A solution to Crouzeix’s conjecture','Emiel Lorist; Felix L. Schwenninger',2026,'https://arxiv.org/abs/2608.03841v2','First posted 4 August, revised 17 August 2026; Lemma 1 and Theorem 3 give an independent scalar proof using all powers in the dilation estimate'),ref('assessment','The Neurosurgery Resident Who Proved Crouzeix’s Conjecture','Alex Townsend; Anne Greenbaum',2026,'https://alextownsend.net/essays/SIAMNews_CrouzeixConjecture.pdf','Author-hosted report dated 15 August 2026; p. 2 explicitly records proof checking and acceptance by the authors and Michel Crouzeix'),ref('repository','Crouzeix Conjecture — research repository and review status','Shanmu Jin',2026,'https://github.com/jinshanmu/CrouzeixConjecture','README inspected 11 September 2026; manuscript and Lean artifacts are supplied, while formal peer review is marked pending; Lean verification was not run for this catalogue'),ref('complete','Square Functions, Complete Crouzeix Conjecture in Dimension Three, and the Clouâtre–Ostermann–Ransford conjecture','Per Åhag; Rafał Czyż; Jani Virtanen',2026,'https://arxiv.org/abs/2608.27346v3','Posted 27 August, revised 9 September 2026; complete conjecture for matrices of order at most three and related stronger scalar COR results')],
 status='resolved',status_note='Resolved affirmatively in the scalar form by July–August 2026 preprints of Jin and independently Lorist–Schwenninger. The status is supported by the explicit August 15 expert assessment of Townsend–Greenbaum, including their report of Crouzeix’s checking. Formal journal peer review is still marked pending in Jin’s repository; no local formalization audit is claimed. Retained as a historical detailed card, not a remaining open problem. The all-dimensional complete conjecture is a different question.',formulation_reviewed_on='2026-09-11')
