import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('uniform-isomorphism-one-relator-groups',
 id='TCS-6677',title='The isomorphism problem for one-relator groups',area='Automated reasoning and unification',criterion='decision',question_type='yes_no',
 formal='Is there a total algorithm which, given any two finite one-relator group presentations G=⟨x₁,…,x_k | r=1⟩ and H=⟨y₁,…,y_ℓ | s=1⟩, decides whether G and H are isomorphic as abstract groups?',
 definitions='The input consists of integers k,ℓ≥1 and explicitly written finite words r and s in the respective generators and formal inverses. The groups are the free groups on these generators modulo the normal closures of r and s. An empty relator is permitted and presents a free group. An isomorphism is a bijective homomorphism of the resulting abstract groups; it need not carry a listed generator to a listed generator, preserve the spelling of a relator, or come from an automorphism of a free group on the given generators. The numbers of displayed generators may differ. The sought procedure is one deterministic Turing machine which halts and answers correctly on every valid pair of presentations. No polynomial-time, elementary-time or other quantitative runtime bound is imposed. There is no promise of torsion, hyperbolicity, nontrivial center, genericity or a supplied geometric decomposition.',
 answer_criterion='Give a uniform terminating decision procedure for all such pairs, or prove that the isomorphism language on these one-relator presentations is undecidable. A procedure that halts only for isomorphic pairs, or one correct only on a specified subclass or almost all random presentations, is insufficient. Undecidability for arbitrary finite presentations, systems of equations or other algebraic structures must be connected to this exact input class by a valid reduction to count as a negative solution.',
 context=[
 paragraph('A group presentation is a finite description of an often infinite algebraic object. The same group can have quite different descriptions: for example, ⟨a,b | b=a²⟩ and ⟨x | empty relator⟩ both describe an infinite cyclic group. The question is whether one defining relation leaves enough structure to recognize abstract equality of group types algorithmically, even when the supplied generators and words look unrelated.'),
 paragraph('This is the third of Dehn’s classical decision problems. Word equality compares elements within one fixed presentation; conjugacy asks for a particular kind of equivalence between elements; isomorphism compares the entire groups. Linton and Nyberg-Brodda’s survey records the general one-relator isomorphism problem as open, despite broad positive results for subclasses.','primary'),
 paragraph('The known uniform word algorithm gives a useful positive semidecision procedure. Enumerate possible word images u₁,…,u_k for the generators of G in H and v₁,…,v_ℓ for the generators of H in G. Check that the images satisfy each defining relation and that the two compositions fix every generator. Every check is a finite collection of word-equality tests. If mutual inverse homomorphisms exist, their finite descriptions eventually appear.'),
 paragraph('The missing part is termination on nonisomorphic inputs. Searching longer for generator images cannot certify that none exist. Equivalently, an effective bound on the lengths of some pair of mutually inverse generator-image tuples, depending only on the input length, would permit a finite search. Conversely, a total isomorphism algorithm would allow such a computable bound to be assembled by checking the finitely many inputs of bounded length and finding witnesses for the positive cases.'),
 paragraph('Easily computable invariants can reject some pairs. Abelianization, for example, takes the exponent sums of the relator and gives a finitely generated abelian quotient whose isomorphism type can be computed by integer linear algebra. But it is incomplete: the free group on two generators and ℤ² have the same abelianization, whereas one is nonabelian and the other is abelian. The free group is represented here using the allowed empty relator, and ℤ² by the commutator relation.'),
 paragraph('Another tempting simplification is to ask whether an automorphism of the free group carries one relator to the other, allowing inversion. Whitehead’s algorithm handles the corresponding orbit question. The survey explains that this sufficient condition is not necessary for isomorphism of the quotient groups: the Magnus conjecture asserting such a converse was disproved, and some groups have infinitely many inequivalent one-relator descriptions.','primary'),
 paragraph('Hyperbolic groups form a large positive case. Dahmani and Guirardel solve isomorphism uniformly for all hyperbolic groups, including those with torsion. Their result also handles peripheral structures and automorphism computations, reflecting how geometric decompositions can organize otherwise unbounded searches. It is a decision theorem, not merely a heuristic for finding likely isomorphisms.','hyperbolic'),
 paragraph('All one-relator groups with torsion are hyperbolic, so this theorem covers that entire subclass. The survey also records decidability for one-relator groups with nontrivial center and other structured families. General torsion-free one-relator groups remain beyond these combined results. Even elementary examples such as ℤ² show that the one-relator condition does not imply hyperbolicity.','primary'),
 paragraph('Generic-case results explain why many randomly generated instances may nevertheless be tractable. Kapovich, Schupp and Shpilrain establish rigidity for large classes of random one-relator presentations: isomorphism can be forced by simple transformations of the displayed generators and relator. The exceptional inputs are small in a specified distributional sense, but an undecidable set of inputs could still lie among such exceptions.','generic'),
 paragraph('Kapovich’s August 18, 2026 preprint extends a generic rigidity program to fixed numbers of generators and relators. It gives an algorithmically recognizable generic family and a quadratic-time generic isomorphism algorithm, using small-cancellation stability and rigidity under free-group automorphisms. Its one-relator specialization is relevant progress, while its guarantee remains a generic one rather than a terminating decision procedure for every input.','recent'),
 paragraph('A different August 2026 result by Nyberg-Brodda proves undecidability of the Diophantine problem for certain one-relator Baumslag–Gersten groups. That task asks whether arbitrary systems of equations with coefficients have solutions. It demonstrates that one relation does not ensure decidability of every natural algebraic question. However, it supplies no automatic reduction to isomorphism between two one-relator presentations, so the present problem remains distinct.','equations'),
 paragraph('A resolution would clarify whether this very economical presentation format has an effective classification in principle. The positive answer could be extremely slow and still be decisive. The negative answer would require encoding undecidable information into abstract group type while retaining a single defining relator—a much more specific construction than demonstrating difficult equations inside one fixed group.')],
 why='One of the central decision problems for finitely presented groups, testing whether a single defining relation permits effective recognition of abstract algebraic structure.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A classical unresolved computability boundary with deep connections to geometric group theory, effective classification and the limitations of presentation-based invariants.'),
 progress=[step('1970s','Counterexamples to the Magnus conjecture show that free-group equivalence of relators cannot characterize all isomorphisms; torsion and center subclasses admit positive results.','primary'),step('2003–2006','Kapovich–Schupp–Shpilrain obtain strong generic rigidity and fast isomorphism algorithms for random one-relator groups.','generic'),step('2010–2011','Dahmani–Guirardel solve isomorphism for all hyperbolic groups, covering one-relator groups with torsion.','hyperbolic'),step('30 January 2025','Linton–Nyberg-Brodda’s survey records the unrestricted one-relator isomorphism problem as open.','primary'),step('3 August 2026','Nyberg-Brodda proves undecidability for the separate Diophantine problem in one-relator groups.','equations'),step('18 August 2026','Kapovich’s preprint extends generic small-cancellation stability and isomorphism rigidity to fixed generator and relator counts.','recent')],
 references=[ref('primary','The theory of one-relator groups: history and recent progress','Marco Linton; Carl-Fredrik Nyberg-Brodda',2025,'https://arxiv.org/abs/2501.18306','Inherited source; §§1.6.3 and 1.8.2, pages 52–54 and 69–71; torsion, center, and general torsion-free isomorphism'),ref('hyperbolic','The isomorphism problem for all hyperbolic groups','François Dahmani; Vincent Guirardel',2011,'https://arxiv.org/abs/1002.2590','Geometric and Functional Analysis 21(2), 223–300; v2, 31 December 2010; DOI 10.1007/s00039-011-0120-0'),ref('generic',"Generic properties of Whitehead's Algorithm and isomorphism rigidity of random one-relator groups",'Ilya Kapovich; Paul Schupp; Vladimir Shpilrain',2006,'https://arxiv.org/abs/math/0303386','Pacific Journal of Mathematics 223(1), 113–140; generic rigidity and isomorphism consequences; DOI 10.2140/pjm.2006.223.113'),ref('recent','Small Cancellation Stability and Isomorphism Rigidity for Generic Finitely Presented Groups','Ilya Kapovich',2026,'https://arxiv.org/abs/2608.17238','Posted 18 August 2026; Theorem C and §§9–11; generic rather than all-input isomorphism algorithms'),ref('equations','Undecidability of the Diophantine problem for one-relator groups and one-relation monoids','Carl-Fredrik Nyberg-Brodda',2026,'https://arxiv.org/abs/2608.01983','Posted 3 August 2026; Theorem A and Baumslag–Gersten examples; a different decision problem')],
 status='source_open',status_note='Reviewed through 11 September 2026. No uniform algorithm or undecidability theorem for isomorphism of arbitrary one-relator group presentations was found in the checked sources. The 2026 generic algorithms and Diophantine undecidability result do not settle this all-input isomorphism question.',formulation_reviewed_on='2026-09-11')
