import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('linear-iteration-bound-stable-semiring-polynomial-systems',
 id='TCS-0482',title='Does naive evaluation over p-stable semirings converge in O((p+1)n) rounds?',
 area='Database theory and finite model theory',criterion='tightness',question_type='yes_no',
 formal=r'''Is there a universal constant C such that the following holds for every integer p>=0, every n>=1, every commutative p-stable semiring S, and every polynomial map F:S^n -> S^n with coefficients in S? Starting with x^(0)=(0,...,0), perform synchronous iteration x^(t+1)=F(x^(t)). There must exist an integer t<=C(p+1)n with x^(t+1)=x^(t). Here p-stability means $1\oplus a\oplus\cdots\oplus a^p=1\oplus a\oplus\cdots\oplus a^{p+1}$ for every a in S. The constant C is independent of the semiring, coefficients, number of monomials, and polynomial degrees. This is the grounded polynomial-system formulation of the source’s proposed linear convergence bound.''',
 definitions=r'''A commutative semiring has associative, commutative addition op-plus with identity 0 and associative, commutative multiplication op-times with identity 1. Multiplication distributes over addition, and 0 times a=0. No additive inverses are assumed. Powers use semiring multiplication and a^0=1. Every component of F is a finite sum of finite products of coefficients and variables; repeated variables and constant terms are allowed. S need not be finite. One round evaluates all components using only the previous vector, not partially updated coordinates. Equality means exact equality of semiring elements. The cost measure is the number of rounds, irrespective of the work needed to evaluate a component or represent an element. In a grounded Datalog program, coordinates represent individual derived facts and their values are annotations; using all n coordinates also includes any that remain zero.''',
 answer_criterion='Prove the universal bound, or refute it by constructing systems whose first fixed-point time divided by (p+1)n is unbounded. A fixed example exceeding n rounds does not refute an unspecified constant C. A bound with a growing factor depending on degrees, coefficients, or n does not establish this target. A faster evaluation algorithm with a different update rule does not by itself bound the number of synchronous naive iterations.',
 context=[
  paragraph('In ordinary Boolean Datalog, a derived fact switches from absent to present at most once. A nonstationary round must add a fact, so the number of possible facts bounds the number of rounds. Annotated recursion can improve the value attached to an already known fact many times. Counting how many coordinates exist therefore ceases to give an immediate termination bound.'),
  paragraph('The stability assumption controls repeated use of a single semiring element. It says that a sufficiently long truncated geometric sum absorbs the next power. The question asks whether a system of n interacting recurrences can multiply the resulting delay by only O(n), even when the equations are nonlinear. This is a structural claim about composition of recursive dependencies, not a bound on the time taken by one database join.'),
  paragraph('The examined Im–Moseley–Ngo–Pruhs preprint proves a polynomial convergence bound, with explicit dependence on sigma, the number of distinct coefficients referenced, and lambda, the maximum number of multiplicands. Its bound is O(sigma p n^2 (n^2 log(lambda+1)+log(sigma+1))) for positive p; the 0-stable case has a separate linear bound. Suppressing sigma and lambda would conceal part of the remaining challenge.', 'polynomial'),
  paragraph('The 2025 seminar asks for O((p+1)n), matching the order of its stated lower bound. A newer paper titled Optimal Convergence of Iterative Methods for Datalogo is now listed by its authors. The inspected listings supply no theorem or accessible manuscript for that entry. This card therefore preserves the precise historical question with an uncertain current status; the title alone does not identify which convergence bound, iteration scheme, or semiring hypotheses it settles.', 'announcement')],
 why='The problem asks whether local algebraic stability imposes a sharp global limit on recursive evaluation. A universal linear bound would explain why a broad class of annotated recursive computations needs only an output-scale number of rounds, while a separation would expose a fundamental cost of nonlinear interactions.',
 importance=dict(score=83,method='editorial',assessed_on='2026-09-10',reason='A foundational convergence question for semiring-valued recursion, with implications beyond one query language. Its historical significance is high, but a newly announced directly relevant paper makes current open status uncertain.'),
 progress=[
  step('2022','Work on convergence of Datalog over pre-semirings establishes stable-semiring convergence and an exponential upper bound in the number of grounded coordinates; the later polynomial paper reviews this starting point.','polynomial'),
  step('2024 / PODS 2025','Im, Moseley, Ngo, and Pruhs establish polynomial convergence for nonlinear programs. The inspected arXiv v2 states the additional sigma and lambda dependencies explicitly.','polynomial'),
  step('2025','Ngo records the gap between the polynomial upper bound and Omega((p+1)n), and proposes a matching linear upper bound.','seminar'),
  step('2026-09-10 check','Author publication pages list Optimal Convergence of Iterative Methods for Datalogo, with a forthcoming PODS 2027 label on Ngo’s page. No theorem text was obtained for that entry. Its relationship to this exact target requires verification.','announcement')],
 references=[
  ref('seminar','Semirings in Databases, Automata, and Logic (Dagstuhl Seminar 25081)','Hung Ngo (problem contributor)',2025,'https://doi.org/10.4230/DagRep.15.2.89','Section 4.2'),
  ref('polynomial','Polynomial Time Convergence of the Iterative Evaluation of Datalogo Programs','Sungjin Im; Benjamin Moseley; Hung Q. Ngo; Kirk Pruhs',2024,'https://arxiv.org/abs/2312.14063v2','Theorem 1.1, Section 2.1 definitions, Section 2.4 grounding; revised 21 February 2024, subsequently listed at PODS 2025'),
  ref('announcement','Publication listing: Optimal Convergence of Iterative Methods for Datalogo','Simon Frisk; Hangdong Zhao; Hung Ngo; Kirk Pruhs; Benjamin Moseley; Sungjin Im; Paraschos Koutris',2026,'https://hung-q-ngo.github.io/publications.html','Author-maintained announcement accessed 10 September 2026; entry labeled PODS 2027, without a linked manuscript')],
 status='uncertain',status_note='Open in the 2025 source. A directly relevant paper, Optimal Convergence of Iterative Methods for Datalogo, is announced on author pages accessed 10 September 2026. The inspected entry has no theorem text or manuscript link; the similarly placed arXiv link on the home page leads to a different paper on even-cycle listing. Do not treat this card as a verified currently open problem until the new result’s precise scope is checked.',
 formulation_reviewed_on='2026-09-10')
