import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('bipartite-maximal-matching-polynomial-degree-volume',
 id='TCS-0519',title='Bipartite maximal matching with polynomial-in-degree volume',
 area='Distributed and local algorithms',criterion='resources',question_type='yes_no',
 formal='Do there exist constants C>0 and k≥1 and one deterministic VOLUME algorithm that computes a maximal matching on every bipartite graph of maximum degree at most Δ, inspecting at most C(Δ+1)^k distinct vertices per queried vertex, independently of the number n of graph vertices? A proper input two-coloring specifying the bipartition is supplied. Answers to all vertex queries must describe the same matching.',
 definitions='The input is a finite simple undirected graph, arbitrary local port orders, a supplied proper two-coloring, distinct identifiers in [n²], and known integers n and Δ≥1 bounding its size and degrees as stated. A query at v must output either ⊥ for unmatched or the local port of its matching edge. If v names u then u must name v. Every edge must have at least one matched endpoint, which is equivalent to maximality by inclusion. Initially the algorithm sees only v’s identifier, degree, color, ports, n, and Δ. It may adaptively follow a port at any already visited vertex; doing so reveals the neighbor’s identifier, degree, color, and reciprocal port. Count all distinct visited vertices, including v. The explored set is connected: arbitrary jumps to identifiers are forbidden. Each query starts afresh, with no preprocessing or memory retained between queries. Repeating a query must give the same answer regardless of other queries or their order. Local computation and temporary memory are unrestricted but finite, and only the number of distinct visited vertices is charged. One finite deterministic program must work for all n, Δ, graphs, identifiers, and port orders; the constants C,k are universal. There is no additional log n or log* n term in the allowed volume.',
 answer_criterion='Construct the uniform polynomial-in-Δ algorithm with globally consistent matching answers, or prove that every correct deterministic algorithm violates every such polynomial bound on some valid input and query. A randomized bound, expected volume, an approximation to maximum matching that need not be maximal, or a polynomial bound containing a factor depending on n does not settle this formulation.',
 context=[
  paragraph('A matching is maximal when there is no edge that can be added while keeping its endpoints disjoint from the current matching. It can be much smaller than a maximum matching. The local output is only one port or an unmatched symbol, so the difficulty is the information needed to make this small answer consistent with answers elsewhere.'),
  paragraph('The supplied bipartition lets the two sides play different roles. A simple distributed procedure has unmatched vertices on one side propose along a new incident edge, while vertices on the other side accept at most one proposal and remain matched thereafter. After O(Δ) rounds this yields a maximal matching. Gathering a whole neighborhood to simulate those rounds can inspect Δ raised to a linear-in-Δ power many vertices.', 'rounds'),
  paragraph('Volume asks whether that exploration can be made much narrower. A vertex may follow a few carefully chosen dependencies far into the graph, instead of collecting every branch of a large ball. But it cannot simply choose a convenient partner in isolation: when that partner is queried separately, the answers must agree. The lack of shared mutable query state makes this coordination part of the algorithm itself.', 'model'),
  paragraph('The independence from n is essential. For each fixed Δ, even an enormous function such as Δ^(2Δ) is constant as n grows. This question compares those constants uniformly as Δ grows, asking for a single polynomial. It is therefore different from obtaining logarithmic dependence on n for fixed degree or from studying only a single fixed-degree LCL.'),
  paragraph('Known round lower bounds force at least linear dependence on Δ when n is sufficiently large. They leave a large interval between that obstruction and full-neighborhood simulation. Suomela conjectures an exponential degree dependence for volume, so even deciding whether a polynomial is possible would determine which side of that major gap is achievable.', 'problem')],
 why='This is a basic test of whether a fast distributed symmetry-breaking algorithm can be evaluated locally without exploring an exponentially branching dependency structure. A polynomial bound would give a small deterministic oracle for a fundamental graph primitive; a superpolynomial lower bound would expose an information cost that round complexity alone does not capture.',
 importance=dict(score=82,method='editorial',assessed_on='2026-09-10',reason='A fundamental maximal-matching oracle question that isolates degree dependence and the difference between distance and volume. It asks for a qualitative polynomial-versus-superpolynomial classification with no network-size term.'),
 progress=[
  step('2020: rounds','Brandt and Olivetti sharpen the degree dependence of bipartite maximal matching in LOCAL. In the identifier model, the deterministic Ω(min{Δ,log n/log log n}) lower bound gives an Ω(Δ) obstruction to any degree-only volume bound by choosing sufficiently large n.','rounds'),
  step('2020: volume model','Rosenbaum and Suomela formalize connected adaptive exploration and explain why an f-round LOCAL algorithm gives a Δ^O(f)-volume algorithm. Combining this with the bipartite O(Δ)-round procedure gives the baseline Δ^O(Δ) volume.','model'),
  step('2026-02','Suomela explicitly asks whether bipartite maximal matching admits polynomial volume in Δ, and conjectures 2^Θ(Δ) as the correct dependence. The conjecture is not a proved lower bound.','problem')],
 references=[
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#volume','Updated 23 February 2026; VOLUME model, Maximal matching'),
  ref('model','Seeing Far vs. Seeing Wide: Volume Complexity of Local Graph Problems','Will Rosenbaum; Jukka Suomela',2020,'https://arxiv.org/abs/1907.08160v2','17 February 2020; PODC 2020; Sections 1 and 2, connected deterministic volume model'),
  ref('rounds','Truly Tight-in-Δ Bounds for Bipartite Maximal Matching and Variants','Sebastian Brandt; Dennis Olivetti',2020,'https://arxiv.org/abs/2002.08216v1','19 February 2020; PODC 2020; introduction, supplied two-coloring, and LOCAL lower bounds. Exact additive constants in anonymous round models are not claimed for VOLUME.')],
 status='source_open',status_note='Explicitly open in the February 2026 primary problem list. Review through 10 September 2026 found no deterministic degree-only polynomial-volume algorithm or superpolynomial lower bound. The bipartition, connected probes, stateless consistency, and worst-case deterministic guarantee are fixed explicitly.',formulation_reviewed_on='2026-09-10')
