import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('maximum-independent-set-congested-clique',
 id='TCS-0469',title='What is the deterministic round complexity of maximum independent set in the congested clique?',
 area='Distributed and local algorithms',criterion='resources',question_type='asymptotic_complexity',
 formal=r'''Determine, up to constant factors as n grows, the optimal worst-case number $T_{\mathrm{MIS}}(n)$ of synchronous communication rounds needed to output an exact maximum independent set of an arbitrary simple undirected n-vertex graph in the deterministic unicast congested-clique model below. For every vertex v, its processor must output one bit indicating whether v belongs to the chosen set. Local computation and local storage are unrestricted; only communication rounds are charged. Here maximum means largest cardinality, not merely inclusion-wise maximal.''',
 definitions=r'''There is one processor for each vertex in {1,...,n}. Initially every processor knows n, all processor identifiers, its own identifier, and exactly the edges incident to its vertex. The communication network is the complete graph regardless of which input edges exist. In each synchronous round, each processor may send a different message of at most $b=\max\{1,\lceil\log_2 n\rceil\}$ bits to each other processor; messages sent in a round become available at its end. Protocols are deterministic and must terminate correctly on every input. An independent set S contains no edge with both endpoints in S; maximum requires |S| >= |I| for every independent set I of the input graph. Define T_MIS(n) as the minimum round bound among protocols for n processors in this model. No polynomial bound is imposed on the computation between rounds. The deterministic and fixed-bandwidth conventions specialize the broader seminar question.''',
 answer_criterion='Give asymptotically matching upper and lower bounds: identify an explicit asymptotic function f(n), construct protocols taking O(f(n)) rounds on every graph, and prove that every correct deterministic protocol requires Omega(f(n)) rounds on some n-vertex graph for all sufficiently large n. Bounds separated by a logarithmic factor or a result only for maximal independent sets do not settle this target.',
 context=[
  paragraph('The graph being optimized and the network carrying messages are different objects. Two vertices that are not adjacent in the input can still communicate directly. This removes distance as an obstacle while retaining a limit on how much information a processor can receive in one round. The task asks how much this distributed information limits exact optimization.'),
  paragraph('A simple baseline is to collect the entire graph at processor 1. Each other processor sends its n-bit adjacency row along its direct link, in blocks of b bits. These transmissions happen simultaneously and take O(n / log n) rounds for n >= 2. Processor 1 then enumerates subsets locally, chooses a largest independent set, and sends each processor its membership bit. This is an elementary upper bound for the stated model, rather than a claim that centralizing the graph is optimal.'),
  paragraph('The unlimited local computation is essential to interpreting this baseline. The exponential subset enumeration has no communication cost. Conversely, a faster centralized algorithm does not by itself reduce the number of rounds needed to assemble the input. The question isolates information movement from the ordinary running-time difficulty of exact independent set.'),
  paragraph('Lower bounds are especially delicate in the unicast clique. Drucker, Kuhn, and Oshman relate this model to powerful circuit computations, explaining why familiar sparse-network bottleneck arguments do not transfer directly. Chechik nevertheless identifies exact maximum independent set as a concrete round-complexity question. The catalogue has a separate constant-round question for a maximal independent set; that weaker output requirement must not be substituted here.', 'power')],
 why='This places a canonical exact graph optimization problem in a model where computation is free but communication is limited. Understanding its round complexity would help distinguish the benefit of distributing information from merely gathering the graph at one processor.',
 importance=dict(score=82,method='editorial',assessed_on='2026-09-10',reason='A canonical exact optimization task testing the communication power of the congested clique. Its relevance extends beyond symmetry breaking, although the chosen deterministic model is one specific frontier.'),
 progress=[
  step('2014','Drucker, Kuhn, and Oshman establish circuit-simulation connections and distinguish unicast from broadcast congested cliques. Their work supplies model context, not a tight bound for the present task.','power'),
  step('2025','Chechik explicitly asks for the communication rounds necessary to compute a maximum independent set in the congested clique.','seminar')],
 references=[
  ref('seminar','Adaptive and Scalable Data Structures (Dagstuhl Seminar 25191)','Shiri Chechik (problem contributor)',2025,'https://doi.org/10.4230/DagRep.15.5.1','Section 5.8'),
  ref('power','On the Power of the Congested Clique Model','Andrew Drucker; Fabian Kuhn; Rotem Oshman',2014,'https://www.cs.tau.ac.il/~roshman/papers/podc14_clique.pdf','PODC 2014; model definitions and circuit-simulation results')],
 status='source_open',status_note='The 2025 seminar source asks for the optimal round complexity. Searches through 10 September 2026 did not locate matching bounds for this exact task. Randomness and bandwidth are fixed explicitly here; results for maximal MIS, broadcast cliques, or edge-restricted CONGEST do not resolve this formulation.',
 formulation_reviewed_on='2026-09-10')
