import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('decide-constant-local-complexity-unrooted-trees',
 id='TCS-0513',title='Can constant-time LOCAL solvability on unrooted trees be decided?',
 area='Distributed and local algorithms',criterion='decision',question_type='yes_no',
 formal=r'''Is there a Turing algorithm D that, given a finite description of a locally checkable labeling problem Π on trees of maximum degree Δ, always halts and decides whether Π has a deterministic LOCAL algorithm that solves every allowed input instance in at most t communication rounds, for some constant t depending only on Π? Trees are unrooted, arbitrary finite input labels are allowed, and each node knows the exact number n of nodes.''',
 definitions=r'''The input description is (Δ,r,Σ_in,Σ_out,C), with integers Δ≥2,r≥1, finite nonempty input and output alphabets, and a finite list C of permitted rooted radius-r neighborhood types. Neighborhoods record input/output labels, degrees and incident port numbers, but not processor IDs or n. Ports at a degree-d node are numbered 1,…,d; the two port numbers of an edge need not agree. A labeling is valid precisely when every node’s radius-r neighborhood is isomorphic, preserving this data and its center, to a type in C. Instances range over every finite nonempty simple undirected tree of degree at most Δ, every input labeling, and every port numbering. Processors additionally have distinct IDs in {1,…,n²}. Initially a node knows its own input, ID, degree, ports, n, and Π. In each synchronous round it can send arbitrary finite messages to its neighbors; local computation is unrestricted in cost but must be computable and terminate. The same finite program runs at every node and works for all n and all ID assignments. No distinguished global root, parent pointers, randomness, or additional advice is supplied. D itself is centralized, with no running-time bound. Descriptions with an unsolvable instance are no instances of the decision problem.''',
 answer_criterion='Give an always-terminating decider for exactly the described constant-round solvability property, or prove that no such decider exists. A procedure that eventually recognizes every positive instance but may run forever on negative instances is insufficient. This is an explicitly chosen binary subproblem of the saved broader question about deciding the entire asymptotic complexity.',
 context=[
  paragraph('An LCL is specified by local rules rather than a global objective. Proper coloring and maximal independent set illustrate the distinction: a completed labeling can be checked from small neighborhoods, yet finding a valid labeling may require substantially more communication. Here the input to the decision procedure is the rulebook itself, not one network to label.'),
  paragraph('The question asks whether a finite rulebook reveals that a bounded communication radius will always suffice. The radius may be enormous and may depend on the rulebook, but it cannot grow with the network. Testing small trees alone cannot certify this property; a procedure must account for every larger tree, every input labeling, and every assignment of identifiers.'),
  paragraph('The possible round complexities and the ability to recognize them are separate issues. Grunau, Rozhoň, and Brandt prove that an LCL on bounded-degree trees with o(log* n) complexity actually has constant complexity. Their paper nevertheless explicitly leaves constant-time decidability open. A gap theorem supplies a separation between cases without automatically providing a test for which case applies.', 'landscape'),
  paragraph('Positive instances can be recognized by searching the finite local-rule candidates associated with each fixed radius. If a suitable radius exists, this search eventually finds it. The missing part is a terminating certificate or other method for the negative answer. The full complexity-classification question would also need to distinguish further classes, so an affirmative answer here is only one stage of that larger goal.', 'landscape'),
  paragraph('Rooted-tree classification results use the supplied parent-child direction to organize their certificates. An arbitrary port numbering on an unrooted tree provides no such globally consistent direction. Recent results also show that knowledge of network size and the computability of local state transitions can matter. This card fixes both assumptions rather than silently moving between models.', 'size')],
 why='This asks whether one can automatically recognize when local verification can be converted into truly local construction on the simplest branching networks. A decider would be a basic ingredient of distributed algorithm synthesis; undecidability would expose a limit that persists even on trees.',
 importance=dict(score=86,method='editorial',assessed_on='2026-09-10',reason='A core decidability boundary for local distributed computation, linking finite specifications, algorithm synthesis, and lower-bound certificates on trees. It isolates a fundamental unresolved stage of full complexity classification.'),
 progress=[
  step('2022','Grunau, Rozhoň, and Brandt close the o(log* n)-to-O(1) gap on bounded-degree trees. Their Section 1.4, Question 1.7, explicitly asks whether constant-time solvability is decidable and explains why recognizing positive instances is not the missing direction.','landscape'),
  step('2022','Balliu, Brandt, Chang, Olivetti, Studený, and Suomela classify the O(log n)-versus-polynomial region efficiently for their regular-tree formalism. Their abstract explicitly leaves finer classification in the O(log n) region open for unrooted trees.','regular'),
  step('2026-02','Cruciani and coauthors show that computable and arbitrary local transition functions give the same round complexity for LCLs when a bound on n is supplied. Without such knowledge they can differ. The exact-n convention of this card avoids that ambiguity.','computable'),
  step('2026-05','Balliu and coauthors show that weakening exact network-size knowledge changes the tree complexity landscape. Their result motivates keeping that assumption fixed; it does not decide constant-round solvability from an arbitrary LCL description.','size'),
  step('2026-06','Piombi extends decidable polynomial complexity gaps to a more general logical formalism on unbounded-degree rooted trees. The paper still identifies the lower-complexity classification of unrooted LCLs as an unresolved boundary.','recent')],
 references=[
  ref('problem','Open problems related to locality in distributed graph algorithms','Jukka Suomela',2026,'https://jukkasuomela.fi/open/#local','Updated 23 February 2026; Decidability of distributed complexity; broader original deterministic question'),
  ref('landscape','The Landscape of Distributed Complexities on Trees and Beyond','Christoph Grunau; Václav Rozhoň; Sebastian Brandt',2022,'https://arxiv.org/abs/2202.04724v2','PODC 2022; Theorem 1.1 and Section 1.4, Question 1.7; revised 23 September 2022'),
  ref('regular','Efficient Classification of Locally Checkable Problems in Regular Trees','Alkida Balliu; Sebastian Brandt; Yi-Jun Chang; Dennis Olivetti; Jan Studený; Jukka Suomela',2022,'https://arxiv.org/abs/2202.08544v2','DISC 2022; abstract and classification scope; revised 2 September 2022'),
  ref('computable','Is a LOCAL algorithm computable?','Antonio Cruciani; Avinandan Das; Massimo Equi; Henrik Lievonen; Diep Luong-Le; Augusto Modanese; Jukka Suomela',2026,'https://arxiv.org/abs/2602.21022v2','Revised 25 February 2026; abstract; PODC 2026 brief announcement DOI 10.1145/3796701.3815908'),
  ref('size','The Distributed Complexity Landscape on Trees Depends on the Knowledge About the Network Size','Alkida Balliu; Sebastian Brandt; Fabian Kuhn; Dennis Olivetti; Timothé Picavet; Gustav Schmid',2026,'https://arxiv.org/abs/2605.12787','12 May 2026; abstract and introduction; PODC 2026'),
  ref('recent','Generalizing LCL Complexity Gaps to Unbounded Degree via Monadic Second-Order Properties','Chiara Piombi',2026,'https://arxiv.org/abs/2606.10693','9 June 2026; Section 1.1, decidability discussion on pp. 3–4; main theorem concerns rooted trees')],
 status='source_open',status_note='The 2022 primary paper poses this exact constant-time subproblem. The February–June 2026 sources retain the unrooted-tree decidability gap; recent model and rooted-tree results do not settle it. Search checked through 10 September 2026.',
 formulation_reviewed_on='2026-09-10')
