import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('superpolynomial-extended-frege-proof-lower-bounds',
 id='TCS-6601', title='Do some tautologies require superpolynomial Extended Frege proofs?',
 area='Proof complexity', criterion='tightness', question_type='yes_no',
 formal=r'''Is Extended Frege not polynomially bounded? Precisely, for every constants C>0 and c≥1, is there a propositional tautology φ whose shortest Extended Frege proof has bit length greater than C(|φ|+2)ᶜ? Here |φ| is the bit length of the explicitly written formula.''',
 definitions=r'''Fix Boolean formulas over ¬ and →, with → interpreted as material implication and variable indices encoded in binary. Use the Frege axiom schemes A→(B→A), (A→(B→C))→((A→B)→(A→C)), and (¬B→¬A)→(A→B), together with modus ponens from A and A→B to B. An Extended Frege proof of φ may additionally introduce an abbreviation variable e by the two extension axioms e→θ and θ→e. Here e is fresh, absent from φ, θ, and every preceding line; θ uses original variables of φ and previously introduced extension variables. Extensions are thus acyclic definitions. Other proof lines are axiom instances or applications of modus ponens, and the last line must be φ, with no extension variables. Lines may cite and reuse earlier lines arbitrarily: proofs are not required to be trees. Proof size is the full binary encoding length of all explicitly written formulas, extension definitions, and inference references; there is no depth or per-line-size restriction. A tautology is true under every assignment to its variables. This fixed presentation is polynomially equivalent to the usual Extended Frege systems, so changing a standard finite Frege basis does not change polynomial boundedness.''',
 answer_criterion='Answer yes by proving that no single polynomial bounds the shortest EF proof of every tautology. Answer no by establishing constants C,c that bound the shortest proof of every tautology by C(|φ|+2)ᶜ. The yes direction does not require that the hard tautologies be generated in polynomial time. A lower bound for an algorithm that searches for proofs, or for a restricted subsystem, is not a lower bound on all EF proofs.',
 context=[
  paragraph('Extension variables let a proof name a formula once and reuse its name. This can represent shared computations economically, as a Boolean circuit shares intermediate gates. Expanding all abbreviations into formula trees can cause an exponential increase in length, so a lower bound that counts only ordinary Frege proofs does not automatically survive the extension rule.','foundation'),
  paragraph('The question concerns the existence of short certificates, not the time required to discover them. A particular proof search method might take exponential time even though another method could find a short proof; conversely, a proof-size lower bound would constrain every method that outputs an EF derivation. The input length is the final tautology’s actual encoding length, so a lower bound exponential in a smaller hidden parameter may still be only polynomial in the input.','book'),
  paragraph('If NP≠coNP, every polynomial-time verifiable propositional proof system has hard tautologies, including EF. The converse for this particular system is unknown: showing that EF is inefficient does not rule out a different proof system that gives short certificates for all tautologies. This is why an EF lower bound would be a major advance without automatically constituting a proof of NP≠coNP.','foundation'),
  paragraph('Recent algebraic lower bounds illustrate an encoding issue. Alekseev proves exponential bit-size lower bounds for an extension of polynomial calculus that can simulate EF on suitable propositional translations. The hard Binary Value Principle instance is not the corresponding translation of a polynomial-size CNF. The paper explicitly explains that its result therefore does not yield a Frege or EF lower bound.','algebraic'),
  paragraph('Pich and Santhanam give implications from EF lower bounds to P≠NP under additional bounded-arithmetic assumptions. This explores the consequences of proof-complexity hypotheses without proving an unconditional EF lower bound.','conditional'),
  paragraph('Hsieh and coauthors construct succinct arguments under derandomization, cryptographic, and formal unprovability assumptions. Their result connects the difficulty of certifying hard tautologies to cryptography; it does not establish the unconditional size lower bound asked for here.','snargs')],
 why='Extended Frege captures a powerful form of efficient propositional reasoning with reusable definitions. A superpolynomial lower bound would cross one of the central barriers in proof complexity and clarify whether a standard, highly expressive certificate language necessarily fails on some short true statements.',
 importance=dict(score=99, method='editorial', assessed_on='2026-09-10', reason='A defining open lower-bound problem for strong propositional reasoning, closely connected to bounded arithmetic, circuit complexity, and the limits of efficiently checkable certificates.'),
 progress=[
  step('1979','Cook and Reckhow formalize propositional proof systems, polynomial simulation, and Extended Frege, proving robustness under the choice of standard rules and connectives.','foundation'),
  step('1980s–2019','Strong lower bounds emerge for weaker systems, while even unrestricted Frege lower bounds remain open. EF adds the ability to abbreviate and share formulas.','book'),
  step('2023–2026','Pich and Santhanam establish conditional routes from EF proof lower bounds to P≠NP. The assumptions include formally provable computational statements; the result is not an unconditional EF lower bound.','conditional'),
  step('June 2026','Hsieh, Jain, Li, and Mathialagan obtain SNARGs for NP from derandomization, LWE, SXDH, and a bounded-arithmetic unprovability assumption concerning certificates of EF-hard tautologies.','snargs'),
  step('21 June 2026','Alekseev’s journal paper proves an exponential bit-size lower bound for algebraic Binary Value Principle refutations in extended polynomial calculus with a square-root rule. Its Section 1 explicitly distinguishes this from propositional Frege and EF lower bounds.','algebraic')],
 references=[
  ref('foundation','The Relative Efficiency of Propositional Proof Systems','Stephen A. Cook; Robert A. Reckhow',1979,'https://www.cs.toronto.edu/~sacook/homepage/cook_reckhow.pdf','Journal of Symbolic Logic 44(1), 36–50; Sections 1–2 and 4, especially Extended Frege and polynomial equivalence'),
  ref('book','Mathematics and Computation','Avi Wigderson',2019,'https://www.math.ias.edu/files/Book-online-Aug0619.pdf','6 August 2019 edition; Sections 6.2–6.3, Open Problem 6.10, footnote 12 on Extended Frege, and proof-complexity barriers'),
  ref('conditional','Towards P≠NP from Extended Frege lower bounds','Jan Pich; Rahul Santhanam',2023,'https://arxiv.org/abs/2312.08163','13 December 2023 preprint; conditional implications and formal provability hypotheses; journal DOI 10.1145/3801091 (2026)'),
  ref('snargs','SNARGs for NP from Unprovability of Mathematical Theorems','YaoChing Hsieh; Abhishek Jain; Jiatu Li; Surya Mathialagan',2026,'https://eccc.weizmann.ac.il/report/2026/098/','ECCC TR26-098, June 2026; formal unprovability and cryptographic assumptions, not an unconditional EF size lower bound'),
  ref('algebraic','A Lower Bound for Polynomial Calculus with Extension Rule','Yaroslav Alekseev',2026,'https://mirror.theoryofcomputing.org/articles/v022a004/','Theory of Computing 22, Article 4, 1–29; Section 1, pages 4–5, explains why the algebraic encoding does not yield an EF lower bound; DOI 10.4086/toc.2026.v022a004')],
 status='source_open', status_note='Explicitly open in the primary proof-complexity sources, including Alekseev’s June 2026 journal article. Research through 10 September 2026 found no unconditional resolution for unrestricted Extended Frege. The algebraic and conditional results cited here retain their stated scope.', formulation_reviewed_on='2026-09-10')
