import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('fully-dynamic-exact-apsp-edge-linear-updates',
 id='TCS-0478',title='Can exact fully dynamic APSP have edge-linear amortized updates and polylogarithmic queries?',
 area='Graph theory and graph algorithms',criterion='resources',question_type='yes_no',
 formal=r'''For every fixed positive integer c, do there exist a deterministic data structure and constants a,d >= 1 such that the following holds for all n >= 2 and $n\le m\le n^2$? Maintain a directed simple graph on a fixed set of n vertices, with at most m edges at every time and integer edge weights in {1,...,n^c}, under single-edge insertions, deletions, and weight changes. Return the exact current distance from any queried vertex s to any queried vertex t in $O(\log^a n)$ worst-case time. After $O(n^d)$ preprocessing, require $O(m\log^a n)$ amortized time per update and polynomial space. Constants may depend on c, but not on n, m, the initial graph, or the operation sequence.''',
 definitions=r'''The capacity m is supplied in advance and bounds the maximum number of live edges throughout the sequence; it is not a count of all updates. Each ordered vertex pair has at most one edge and there are no self-loops. An insertion adds an absent edge, a deletion removes a present edge, and a weight change replaces the weight of one present edge by another permitted weight. A distance query returns the minimum sum of edge weights on a directed s-to-t path, zero for s=t, and a distinguished infinity value if no path exists. Only the distance is requested, not every path or the whole distance matrix. All answers must be exact for any interleaving of updates and queries. Use a word RAM with Theta(log n)-bit words, with a sufficiently large constant for the fixed weight exponent and polynomially bounded addresses; comparisons, arithmetic, Boolean operations, shifts, and random access cost one step. Amortization means that after preprocessing any U updates and Q queries together cost $O(U m\log^a n+Q\log^a n)$; the query bound must also hold for each query individually.''',
 answer_criterion='Give a data structure with these guarantees for every fixed polynomial weight bound, or prove that the quantified proposition is false. A conditional lower bound must state its assumption. A near-quadratic-in-n update bound only meets the target for dense graphs; a subpolynomial approximation ratio or a guarantee only for insertions does not meet the exact fully dynamic specification.',
 context=[
  paragraph('Recomputing distances from every source after each change is expensive, while postponing the work until a query can make a single query expensive. A dynamic distance oracle tries to divide this work so that both kinds of operation remain useful. The requested update budget is roughly the size of the current graph representation, even when that graph is sparse.'),
  paragraph('A single changed edge can alter distances for quadratically many vertex pairs. That observation does not by itself rule out a fast oracle: the representation may store those changes implicitly, and the interface only asks for one pair at a time. Proving a lower bound therefore requires more than counting changed entries in a materialized distance matrix.'),
  paragraph('The classical Demetrescu–Italiano algorithm achieves O(n^2 log^3 n) amortized update time and constant distance-query time for nonnegative weights. This is already close to the proposed bound when m is quadratic in n. The substantial gap is the sparse regime, where the desired amortized update cost can be nearly a factor n smaller.', 'classic'),
  paragraph('Several nearby frontiers have different guarantees. Mao’s revised 2024 result targets worst-case vertex-update time and gives a randomized bound at the n^(5/2) scale. ESA 2025 sparsification gives extremely fast dynamic approximate distances, with a growing approximation factor. Neither result establishes the exact, edge-sensitive, amortized target on this card. Fixing those distinctions is necessary when assessing progress.', 'sparsification')],
 why='This asks whether exact shortest-path information can be maintained at a cost reflecting the number of input edges, rather than all possible vertex pairs. It is a central dynamic-graph trade-off between update work, sparse structure, and immediate exact access to global information.',
 importance=dict(score=90,method='editorial',assessed_on='2026-09-10',reason='A broad exact dynamic-graph frontier with a major sparse-versus-dense gap. It tests whether global metric information can be maintained at input-scale update cost while preserving fast queries.'),
 progress=[
  step('2004','Demetrescu and Italiano give deterministic O(n^2 log^3 n) amortized updates and constant worst-case distance queries for general directed nonnegative-weight graphs.','classic'),
  step('2021','Henzinger asks for fully dynamic APSP with edge-linear update cost and constant query cost, both allowing polylogarithmic factors. The fixed weight, edge-update, and amortization conventions here make that direction precise.','seminar'),
  step('2024-08-27','Mao’s revised paper gives a Monte Carlo algorithm with tilde-O(n^(5/2)) worst-case vertex-update time and near-quadratic space. This addresses a different update guarantee.','worstcase'),
  step('2025','Kyng, Meierhans, and Zöcklein use sparsification for near-linear total processing of a bounded-length update sequence with polylogarithmic queries, but their returned distances have a subpolynomial approximation factor.','sparsification')],
 references=[
  ref('seminar','Scalable Data Structures (Dagstuhl Seminar 21071)','Monika Henzinger (problem contributor)',2021,'https://doi.org/10.4230/DagRep.11.1.1','Section 5.2'),
  ref('classic','A New Approach to Dynamic All Pairs Shortest Paths','Camil Demetrescu; Giuseppe F. Italiano',2004,'https://www.diag.uniroma1.it/~demetres/docs/dapsp-full.pdf','Journal version; abstract and main amortized bound'),
  ref('worstcase','Fully-Dynamic All-Pairs Shortest Paths: Likely Optimal Worst-Case Update Time','Xiao Mao',2024,'https://arxiv.org/abs/2306.02662v3','Revised 27 August 2024; abstract'),
  ref('sparsification','Bootstrapping Dynamic APSP via Sparsification','Rasmus Kyng; Simon Meierhans; Gernot Zöcklein',2025,'https://doi.org/10.4230/LIPIcs.ESA.2025.113','Abstract; approximate rather than exact distances')],
 status='source_open',status_note='The edge-sensitive target is open in the 2021 source. Searches through 10 September 2026 did not locate an exact algorithm with the stated sparse update and query bounds. This is a deterministic bounded-integer-weight specialization; approximate and worst-case vertex-update results are recorded with their different guarantees.',
 formulation_reviewed_on='2026-09-10')
