import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('optimal-deterministic-rip-matrices',
 id='TCS-6662',title='Optimal deterministic restricted-isometry matrices',area='Pseudorandomness and derandomization',criterion='construction',question_type='yes_no',
 formal='Do there exist universal constants C,B,b>0 and a deterministic algorithm which, for every pair of integers N≥2 and 2≤s≤N, outputs in at most B N^b bit operations a rational m×N matrix A, with m≤C s ln(eN/s), such that (2/3)‖x‖₂²≤‖Ax‖₂²≤(4/3)‖x‖₂² for every real vector x∈ℝ^N with at most s nonzero coordinates?',
 definitions='The input consists of N and s in binary. The output is an explicit list of all entries of A, each encoded as a signed integer numerator and positive integer denominator in binary. Its total encoding length must also be at most B N^b. Time is ordinary deterministic Turing-machine bit complexity, polynomial in N; randomness, advice and unit-cost exact real arithmetic are unavailable. The row count m is a positive integer chosen by the algorithm. The same constants and algorithm work for all allowed pairs N,s. The norm is Euclidean, and the displayed inequalities concern squared norms. They define restricted isometry of order s and distortion δ=1/3. The condition must hold simultaneously for every support of size at most s and every real choice of coefficients on that support. No probability over supports or signals is permitted. The natural logarithm and the factor e ensure a nonzero expression when s is close to N. The omitted case s=1 is trivial and can be handled by a single row of ones.',
 answer_criterion='Give a deterministic algorithm satisfying all the uniform dimension, encoding, time and restricted-isometry requirements, or prove that no such algorithm exists. A negative result conditional on a complexity assumption must state it. An existence proof, a construction using random bits, success for most sparse signals, or a deterministic construction with a larger asymptotic row count does not settle the stated question.',
 context=[
 paragraph('Suppose an unknown vector has N coordinates but only s of them matter. A measurement matrix replaces the vector by m linear measurements. Sparsity allows m to be much smaller than N, but the matrix must preserve every possible sparse direction if the measuring device is to work uniformly. The question asks whether a short, guaranteed measurement design can be computed without random choices.'),
 paragraph('The restricted-isometry requirement has a concrete spectral interpretation. For every set S of at most s column indices, all eigenvalues of A_SᵀA_S must lie between 2/3 and 4/3. Thus columns must behave almost orthogonally in every small group. Checking only individual column lengths, only pairs of columns, or a large collection of sampled test vectors leaves many of these simultaneous constraints untested.'),
 paragraph('This condition supports stable sparse recovery. If a matrix has restricted isometry of order 2t with distortion 1/3, then two different t-sparse signals cannot have identical measurements: their difference has at most 2t nonzero coordinates. Standard recovery theorems also give robust reconstruction by ℓ₁ minimization. The distinction between order t and order 2t is necessary; injectivity for t-sparse differences alone would not compare arbitrary t-sparse signals.','road'),
 paragraph('Random independent Bernoulli or Gaussian matrices attain m=O(s log(eN/s)) for fixed distortion, and matching row lower bounds make this the optimal order for s≥2. Rao’s paper summarizes this benchmark and improves the amount of randomness needed to attain it. The unresolved resource in the card is therefore deterministic construction time, rather than whether matrices with the desired geometric property exist.','randomness'),
 paragraph('Requiring rational output does not destroy the random benchmark. For example, choose the number of rows to be a perfect square t² within a constant factor of a sufficiently large target value, and use independent entries ±1/t. This keeps the usual normalized Bernoulli construction while giving an exact, short binary description of every entry. The real difficulty is choosing all the signs deterministically with a proof that every sparse direction is preserved.'),
 paragraph('One basic deterministic analysis bounds the coherence μ, the largest absolute inner product between two unit columns. Gershgorin’s theorem then gives restricted-isometry constant at most (s−1)μ. When μ is about 1/√m, this argument certifies only s on the order of √m. This is a limitation of that sufficient-condition analysis, commonly called the square-root bottleneck, rather than an impossibility theorem for deterministic matrices.','road'),
 paragraph('Bourgain, Dilworth, Ford, Konyagin and Kutzarova broke that bottleneck in a restricted parameter regime. Their explicit construction uses additive-combinatorial and exponential-sum estimates to control interactions beyond pairwise coherence. It is a major proof that deterministic analysis can go further, but its small exponent improvement does not reach the optimal s log(eN/s) row count uniformly in N and s.','bourgain'),
 paragraph('Rao’s construction achieves the optimal row order with O(s log(N/s) log s) random bits in the sparse parameter regime discussed in the paper. Its proof extends the Hanson–Wright inequality to biased distributions. Reducing the seed length makes progress toward explicit construction, but enumerating all seeds can still take far more than polynomial time, and recognizing a successful seed is a separate issue.','randomness'),
 paragraph('The inherited 2025 paper of Fickus and Lake studies highly symmetric equiangular tight frames, which minimize coherence. It analyzes their minimal dependent column sets through regular simplices and designs. Such structure is informative in both directions: a dependent set of r columns immediately prevents restricted isometry of order r with distortion less than one. Optimal pairwise geometry alone does not guarantee the higher-order property.','primary'),
 paragraph('For a simple illustration, the m+1 unit vertices of a regular simplex in ℝ^m have small and equal pairwise inner products, yet their sum is zero. Their coefficient vector of all ones is therefore a nonzero sparse kernel vector. The example explains why an attractive frame construction must be accompanied by control over all relevant column subsets, not just a calculation of coherence.'),
 paragraph('The all-parameter formulation also matters. The identity matrix handles s comparable to N, while many explicit algebraic constructions work only along particular dimension sequences or for specified sparsity ranges. A resolution must cover the intermediate sparse regimes with one polynomial-time procedure. Likewise, statistical recovery guarantees and ℓ₁-norm versions of restricted isometry answer different geometric questions.')],
 why='A central gap between random existence and efficient explicit construction, with direct consequences for uniform sparse recovery and for how pseudorandomness controls exponentially many spectral constraints.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='An optimal derandomization problem connecting compressed sensing, pseudorandomness, additive combinatorics and explicit geometric constructions.'),
 progress=[step('2010–2011','Bourgain and coauthors give explicit RIP matrices beyond the coherence-based square-root bottleneck in a restricted parameter range.','bourgain'),step('2013','Bandeira–Fickus–Mixon–Wong compare deterministic verification methods and formulate frame-based routes toward stronger constructions.','road'),step('2023–2025','Rao obtains optimal row counts with fewer random bits; the December 2024 revision appeared in Information Processing Letters 189 (2025), article 106553.','randomness'),step('July–December 2025','Fickus–Lake’s revised and published frame results describe minimal dependencies in doubly transitive equiangular tight frames; their introduction still identifies optimal deterministic RIP construction as open.','primary')],
 references=[ref('primary','Doubly transitive equiangular tight frames that contain regular simplices','Matthew Fickus; Evan C. Lake',2025,'https://www.sciencedirect.com/science/article/pii/S0024379525003143','Inherited source; Linear Algebra and its Applications 726, 113–163; introduction and §2.1; accessible preprint arXiv:2302.08879v2, 21 July 2025; DOI 10.1016/j.laa.2025.07.023'),ref('road','The road to deterministic matrices with the restricted isometry property','Afonso S. Bandeira; Matthew Fickus; Dustin G. Mixon; Percy Wong',2013,'https://www.math.ucdavis.edu/~strohmer/courses/270/road_to_rip.pdf','Journal of Fourier Analysis and Applications; §§1–4, especially the sparse-recovery theorem and coherence bottleneck'),ref('bourgain','Explicit constructions of RIP matrices and related problems','Jean Bourgain; Stephen J. Dilworth; Kevin Ford; Sergei Konyagin; Denka Kutzarova',2011,'https://arxiv.org/abs/1008.4535','Duke Mathematical Journal 159(1), 145–185; explicit construction beyond the square-root bottleneck; v3, 29 May 2011'),ref('randomness','Satisfying the restricted isometry property with the optimal number of rows and slightly less randomness','Shravas Rao',2025,'https://arxiv.org/abs/2311.07889','Information Processing Letters 189, 106553; introduction and Theorem 1.1; preprint 2023, v2 December 2024; DOI 10.1016/j.ipl.2024.106553')],
 status='source_open',status_note='Reviewed through 11 September 2026. No polynomial-time deterministic construction with the required uniform optimal row bound was found in the checked sources. Optimal randomized row counts, restricted parameter regimes and coherence guarantees are recorded as partial progress.',formulation_reviewed_on='2026-09-11')
