import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('polynomial-hirsch-conjecture',
 id='TCS-6573',title='Polynomial Hirsch conjecture for edge-path diameter',area='Optimization and numerics',criterion='tightness',question_type='yes_no',
 formal='Do universal constants C>0 and k≥1 exist such that every nonempty pointed d-dimensional convex polyhedron with n facets has vertex-edge graph diameter at most C(n+d)^k?',
 definitions='A polyhedron is an intersection of finitely many closed affine halfspaces over the real numbers. Work in its affine hull, identified with R^d, where d≥1, and require it to be pointed, meaning that it contains no affine line; this ensures that its vertices are present. Both bounded polyhedra, called polytopes, and unbounded pointed polyhedra are included. The number n counts distinct facets in an irredundant description, rather than repeated input inequalities. The graph G(P) has one vertex per geometric vertex of P and an undirected edge between u and v precisely when their segment is a bounded one-dimensional face of P. An unbounded ray is not an extra graph vertex or an edge to infinity. Graph distance counts edges, each at unit cost; diameter is the maximum distance between vertices and is zero for a one-vertex polyhedron. The constants C,k must be independent of dimension, facet count, coordinates, coefficient bit length and the choice of polyhedron. Real coordinates are allowed, and no simplicity or nondegeneracy assumption is made. Paths need not improve any objective function, and no algorithm for finding them is required.',
 answer_criterion='Prove the universal polynomial edge-diameter bound, or prove its negation: for every C>0 and integer k≥1 there is a polyhedron in the stated class with diameter greater than C(n+d)^k. A single counterexample to the linear bound n−d is insufficient. Bounds with an exponent depending on d, with an uncontrolled dependence on coefficient magnitudes, or permitting non-edge steps do not establish this statement.',
 context=[
 paragraph('The feasible region of a linear program is a polyhedron. Its vertices are candidate basic feasible solutions, and its edges describe elementary geometric moves between them. The diameter asks for the largest minimum number of such moves between any two vertices. It is therefore a question about the geometry of feasible solutions before one chooses a particular rule for navigating them.','primary'),
 paragraph('The facet count is the relevant measure of description size here. A polyhedron described by a modest number of inequalities can have exponentially many vertices, so the trivial bound by the number of vertices is far too large. The d-dimensional cube illustrates the distinction: it has 2d facets and 2^d vertices, yet its diameter is only d because one can change differing coordinates one at a time.'),
 paragraph('Polynomial means a fixed exponent that works in every dimension. An n^d upper bound is polynomial in n when d is held fixed, but does not answer this question. Neither does a bound whose constant grows exponentially with d. The card includes pointed unbounded polyhedra, matching the saved formulation; pointedness removes polyhedra with no vertices, for which a vertex-graph diameter would not express the intended problem.'),
 paragraph('Hirsch originally proposed the much sharper n−d bound for bounded polytopes. Santos’s counterexample, announced in 2010 and published in 2012, has dimension 43 and 86 facets, with diameter exceeding 43. This refutes that linear expression, but it remains fully compatible with a bound such as Cn² or Cn¹⁰. The distinction between failure of one attractive formula and failure of every polynomial is the reason a major open question survived.','santos'),
 paragraph('General upper bounds are quasipolynomial. Kalai and Kleitman’s 1992 argument gave n^{2+log₂d}; Todd improved it in 2014 to (n−d)^{log₂d}. For large d, Sukegawa’s later asymptotic refinement has the form (n−d)^{log₂d−log₂log d+O(1)}. The last exponent still grows with dimension. These are substantial structural bounds, but they do not reach one universal constant exponent.','sukegawa'),
 paragraph('The conjecture concerns shortest available paths, not the paths a chosen simplex pivot rule happens to take. A rule may visit exponentially many vertices even on a polytope whose graph has small diameter. Conversely, proving that short undirected paths exist would not tell a solver which edge to select efficiently, or ensure a short path that improves a specified linear objective at every step. Polynomial diameter is a geometric ingredient, not by itself a strongly polynomial linear-programming algorithm.'),
 paragraph('Recent complexity results make the distinction sharper. Wulf’s FOCS 2025 paper proves Π₂^p-hardness of computing the diameter of bipartite perfect-matching polytopes, and the corresponding decision problem is complete for that class. Such hardness is compatible with a polynomial upper bound on the value of the diameter. A small optimum can be difficult to compute exactly, just as short witnesses can be difficult to find.','complexity'),
 paragraph('Natura’s February 2026 paper proves a polynomial bound for a different geometric distance: circuit diameter. For a standard-form polyhedron {x∈R^N:Ax=b,x≥0}, with A having r rows, the stated bound is O(r²log r), and the construction also supplies monotone circuit walks. Circuit directions are support-minimal dependencies of A; a maximal feasible step in such a direction need not stay on an edge of the current polyhedron.','circuit'),
 paragraph('Every edge step is allowed among the circuit moves, but the converse fails. Consequently, a short circuit walk gives no automatic equally short edge walk: its intermediate points may lie inside higher-dimensional faces. The 2026 theorem settles the circuit analogue of the polynomial conjecture, while its introduction explicitly retains the ordinary combinatorial-diameter problem. The distinction is geometric, not a question of hiding logarithmic factors.','circuit'),
 paragraph('Other positive results exploit extra structure, such as totally unimodular constraint matrices or numerical bounds on subdeterminants. Those assumptions control features absent from the unrestricted statement. Random-polytope and smoothed analyses likewise describe particular distributions or perturbations; a worst-case theorem must include every allowed realization. This is why the model specifies arbitrary coefficients and requires constants independent of their encoding.'),
 paragraph('A positive resolution would reveal a universal short-route property of all polyhedral feasible regions, despite their potentially enormous vertex sets. A negative resolution would produce polyhedra on which every route between some vertices is intrinsically long. Both outcomes would identify a basic geometric limit underlying pivot-based optimization, independently of the performance of any individual implementation.')],
 why='Determine whether all polyhedral feasible regions have uniformly short edge routes, a central structural question underlying linear programming.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='The surviving fundamental diameter question after the original Hirsch bound failed; it separates geometric existence of short routes from algorithmic navigation and the newly resolved circuit analogue.'),
 progress=[step('1992','Kalai–Kleitman establish a quasipolynomial general edge-diameter bound; Todd’s paper records and sharpens the recurrence-based result.','todd'),step('2010–2012','Santos disproves the original linear Hirsch conjecture with a 43-dimensional bounded polytope having 86 facets.','santos'),step('2014','Todd proves the upper bound (n−d)^{log₂d}.','todd'),step('2018–2019','Sukegawa’s asymptotic improvement lowers the exponent by log₂log d up to an additive constant, still quasipolynomial.','sukegawa'),step('2025','The ETH geometry notes retain the polynomial problem; Wulf establishes Π₂^p-hardness of computing diameters even for bipartite perfect-matching polytopes.','complexity'),step('2026-02-10','Natura’s revised manuscript proves polynomial circuit diameter, including monotone circuit walks; ordinary edge diameter remains open.','circuit')],
 references=[ref('primary','Geometry: Combinatorics and Algorithms 2025 — Chapter 10, Convex Polytopes','ETH Zürich, Institute of Theoretical Computer Science',2025,'https://ti.inf.ethz.ch/ew/courses/Geo25/lecture/gca25-10.pdf','Inherited reference; Section 10.4.1, printed p. 173, explains simplex geometry and explicitly states the surviving polynomial Hirsch problem for bounded polytopes'),ref('santos','A counterexample to the Hirsch Conjecture','Francisco Santos',2012,'https://annals.math.princeton.edu/2012/176-1/p07','Annals of Mathematics 176(1), 383–412; 43 dimensions, 86 facets; 2010 announcement'),ref('todd','An improved Kalai–Kleitman bound for the diameter of a polyhedron','Michael J. Todd',2014,'https://arxiv.org/abs/1402.3579','March 2014 revision; (n−d)^{log₂d} bound and the earlier Kalai–Kleitman bound'),ref('sukegawa','An Asymptotically Improved Upper Bound on the Diameter of Polyhedra','Noriyoshi Sukegawa',2019,'https://link.springer.com/article/10.1007/s00454-018-0016-y','Discrete & Computational Geometry 62, 690–699; published online 19 June 2018; asymptotic bound (n−d)^{log₂ O(d/log d)}'),ref('complexity','Computing the Polytope Diameter is Even Harder than NP-hard (Already for Perfect Matchings)','Lasse Wulf',2025,'https://arxiv.org/abs/2502.16398v3','FOCS 2025; revision 3 November 2025; Π₂^p-hardness and completeness for the corresponding bipartite perfect-matching diameter decision problem'),ref('circuit','Circuit Diameter of Polyhedra is Strongly Polynomial','Bento Natura',2026,'https://arxiv.org/abs/2602.06958v2','Posted 6 February, revised 10 February 2026; Theorem 1.1 and the monotone construction concern maximal feasible circuit steps, not edge-only walks')],
 status='source_open',status_note='No polynomial upper bound or superpolynomial counterexample for the stated worst-case edge-diameter problem was found through 11 September 2026. Natura’s 2026 result resolves the circuit analogue and explicitly leaves the combinatorial problem open. The card includes bounded and pointed unbounded polyhedra, counts facets, and imposes neither monotonicity nor an efficient path-finding requirement.',formulation_reviewed_on='2026-09-11')
