import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('exponential-general-circuit-lower-bound-for-variable-parameterized-3sat',
 id='TCS-0016',title='Exponential circuit lower bounds for 3-SAT',area='Computational complexity',criterion='tightness',question_type='yes_no',
 formal='For the explicitly encoded n-variable 3-SAT function SATₙ defined below, do there exist constants c>0 and n₀ such that CC(SATₙ)≥2^{cn} for every n≥n₀?',
 definitions='For each n≥1, enumerate all clauses on variables x₁,…,xₙ containing zero, one, two or three distinct variables, each with either sign. A zero-literal clause is false. There are M(n)=Σⱼ₌₀³2ʲ·binom(n,j) such clauses, with binom(n,j)=0 when j>n. Order them first by length, then by the increasing tuple of variable indices, then by their sign bits, with 0 meaning positive and 1 negated. The input is b∈{0,1}^{M(n)}; its jth bit says whether clause j is included. Let Φ_b be the conjunction of included clauses, with an empty conjunction true, and define SATₙ(b)=1 iff some assignment in {0,1}ⁿ satisfies Φ_b. Thus every input is valid. CC counts gates in a directed acyclic circuit with one output, arbitrary Boolean gates of at most two inputs, constants 0 and 1, unrestricted depth and fan-out, and exact correctness on every b. Inputs, constants and output wires are not gates. Circuits may be chosen nonuniformly for each n. The exponential parameter is the number n of variables, while the circuit has M(n)=Θ(n³) input bits. This fixed encoding and the restriction to 3-CNF are an editorial variable-parameter formulation of the source’s exponential SAT circuit question.',
 answer_criterion='Prove the displayed eventual exponential lower bound for unrestricted circuits, or prove its negation: for every c>0 and N≥1 there exists n≥N with CC(SATₙ)<2^{cn}. A circuit family of size 2^{o(n)} at all lengths would suffice for the negative direction, but that is stronger than the exact negation. A lower bound only against bounded-depth, monotone, formula, uniform or proof-system models does not settle the question. A circuit upper bound 2^{αn} for one fixed α>0 remains compatible with a smaller positive lower-bound exponent.',
 context=[
  paragraph('SAT asks whether a collection of local constraints admits a simultaneous Boolean assignment. Here each selected clause prohibits one pattern on at most three variables. An assignment can be checked efficiently, but the conjecture says that deciding whether any assignment works requires exponentially many gates even when a different circuit may be designed separately for every n. It is a quantitative strengthening of the question whether NP has polynomial-size circuits.','book'),
  paragraph('Fixing the representation is essential. An n-variable 3-CNF can have Θ(n³) distinct clauses; writing a list of literals instead introduces binary variable names and a different bit length. These encodings are polynomially interconvertible, but a claim exponential in the literal number of input bits is not invariant under polynomial changes of encoding. This card therefore fixes both the representation and the variable parameter. The target is 2^{Ω(n)}, which is 2^{Ω(M^{1/3})} in the number M of circuit inputs.'),
  paragraph('There is a simple matching exponential scale for an upper bound. For each of the 2ⁿ assignments, form an AND requiring bⱼ=0 for every clause that assignment would falsify. OR these tests over all assignments. The resulting circuit decides SATₙ and has O(M(n)2ⁿ) gates. This is an explicit construction showing what exhaustive search means in the chosen nonuniform model. The conjecture allows substantial improvements in the exponential constant, while ruling out the absence of every positive eventual exponential lower bound.'),
  paragraph('The Exponential Time Hypothesis concerns uniform algorithms and the number of variables. Impagliazzo, Paturi and Zane’s sparsification lemma relates general fixed-width CNFs to disjunctions of sparse CNFs, with at most 2^{εn} branches for each fixed ε>0. This explains why variable and clause parameters are closely connected in exponential-time reductions. It does not automatically turn a uniform hypothesis into a lower bound against arbitrary circuits, and the precise almost-everywhere quantifiers on this card are part of its target.','sparse'),
  paragraph('Even much weaker general-circuit lower bounds remain elusive. Li and Yang prove 3.1N−o(N) gates for particular explicit single-output functions of N input bits. That is a theorem about carefully chosen affine dispersers, not an exponential lower bound for SAT. A counting argument can prove that most truth tables are exponentially hard, but it cannot identify SAT among those hard functions.','liyang'),
  paragraph('There has been important progress by linking faster satisfiability algorithms to lower bounds for other circuit classes. Williams proves that nondeterministic exponential time has languages without polynomial-size ACC circuits. ACC restricts depth while allowing unbounded-fan-in Boolean and modular gates. The distinction matters in two places: the hard language need not be in NP, and the competing circuits are not unrestricted. This theorem demonstrates a powerful strategy without resolving this card.','acc'),
  paragraph('Algorithmic progress continues within the exponential regime. Jiang and Cai’s July 2026 preprint refines the analysis of the existing PPSZ algorithm, reporting a randomized general-3-SAT running-time base of 1.307031578 and a slightly smaller base under uniqueness. The authors retain the same algorithm and unique-to-general lifting theorem; their improvement comes from a sharper combination of inequalities with rational certificates. These are upper bounds, with randomness and success guarantees, rather than lower bounds for exact circuits. A constant base above one remains compatible with the target.','ppsz'),
  paragraph('A positive answer would rule out polynomial-size circuits for this NP decision problem and therefore imply P≠NP. A negative answer would not imply P=NP: circuits of size 2^{√n}, for example, would refute an eventual exponential bound while still being superpolynomial in the input size, and a nonuniform circuit family need not be constructible by one efficient algorithm.')],
 why='A precise worst-case formulation of the belief that satisfiability retains exponential complexity even with arbitrary nonuniform preprocessing by input size. It separates exponential hardness from polynomial hardness and from bounds tied to a restricted computational model.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-10',reason='A sweeping quantitative lower-bound target for the canonical efficiently verifiable problem, directly connected to nonuniform complexity and the foundations of exponential-time algorithms.'),
 progress=[
  step('1998–2001','Impagliazzo–Paturi–Zane develop sparsification and reductions preserving subexponential complexity in variable parameters.','sparse'),
  step('2011–2014','Williams establishes NEXP lower bounds for constant-depth ACC circuits using satisfiability algorithms.','acc'),
  step('2018','Wigderson states the exponential SAT circuit conjecture; this card makes its parameter and encoding explicit.','book'),
  step('2021–2022','Li–Yang prove a 3.1N−o(N) general-circuit bound for explicit functions; it is neither exponential nor a SAT bound.','liyang'),
  step('2026-07-12','Jiang–Cai report a small improvement in the randomized PPSZ upper exponent for general 3-SAT.','ppsz')],
 references=[
  ref('book','Mathematics and Computation','Avi Wigderson',2018,'https://www.math.ias.edu/files/mathandcomp.pdf','27 March draft, §5.2.1, Conjecture 5.7 and footnote 49, printed page 65; encoding and variable parameter are fixed editorially here'),
  ref('sparse','Which Problems Have Strongly Exponential Complexity?','Russell Impagliazzo; Ramamohan Paturi; Francis Zane',2001,'https://cseweb.ucsd.edu/~paturi/myPapers/pubs/ImpagliazzoPaturiZane_2001_jcss.pdf','Journal of Computer and System Sciences 63:512–530; sparsification lemma and subexponential reduction families; DOI 10.1006/jcss.2001.1774'),
  ref('liyang','3.1n − o(n) Circuit Lower Bounds for Explicit Functions','Jiatu Li; Tianqi Yang',2022,'https://eccc.weizmann.ac.il/report/2021/023/','February 2021 preprint; STOC 2022, pages 1180–1193; general B₂ circuits for affine dispersers'),
  ref('acc','Nonuniform ACC Circuit Lower Bounds','Ryan Williams',2014,'https://people.csail.mit.edu/rrw/acc-lbs-journal-final.pdf','JACM 61(1), Article 2; Theorems 1.1–1.2 in the author version; CCC 2011 precursor; the PDF retains placeholder journal metadata'),
  ref('ppsz','A Better Analysis For PPSZ For 3-SAT','Tao Jiang; Shaowei Cai',2026,'https://arxiv.org/abs/2607.10697','v1, 12 July; Theorem 1.1 is Unique-3-SAT and Corollary 1.2 lifts to general 3-SAT; randomized upper bounds, not a subexponential algorithm')],
 status='source_open',status_note='Checked through 10 September 2026. No unconditional exponential lower bound for unrestricted circuits deciding variable-parameterized 3-SAT was located. The card specifies an almost-everywhere bound, an explicit total clause-incidence encoding, and n as the variable count; it does not assert exponential hardness in the Θ(n³) encoding length.',formulation_reviewed_on='2026-09-10')
