import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('three-dimensional-passive-quantum-memory-under-unconstrained-thermal-noise',
 id='TCS-6517',title='Passive quantum memory in three dimensions — claimed resolution',area='Quantum computation',criterion='construction',question_type='yes_no',
 formal='Does there exist a family of three-dimensional, bounded-density local Pauli stabilizer Hamiltonians Hₙ and a fixed inverse temperature 0<β<∞ for which the lifetime τₙ(β) of one encoded qubit, under the thermal dynamics below and without intervention during storage, tends to infinity as n→∞?',
 definitions='The family may use an unbounded subsequence of qubit counts n. Place the qubits in ℝ³, with at most B qubits in each unit ball. Let Hₙ=Σⱼ(I−Sⱼ)/2, where the Sⱼ are commuting nonidentity Hermitian Pauli checks, each supported in a ball of radius R, each qubit belongs to at most B checks, and their joint +1 eigenspace has dimension two. B and R are constants independent of n. A Pauli check is a signed tensor product of I,X,Y,Z; X flips |0⟩ and |1⟩, Z changes the sign of |1⟩, and Y=iXZ. Use the following fixed Davies-type thermal generator, in units with ℏ=k_B=1. If Π_E is the energy-E spectral projector of Hₙ, define A_{i,P,ω}=Σ_{E′−E=ω}Π_{E′}PᵢΠ_E for every qubit i, P∈{X,Y,Z}, and energy difference ω. Put gβ(ω)=min{1,exp(−βω)} and Lₙ,β(ρ)=−i[Hₙ,ρ]+Σ_{i,P,ω}gβ(ω)[AρA†−(A†Aρ+ρA†A)/2], with A=A_{i,P,ω} in each summand. Its evolution is Φₙ,β,t=exp(tLₙ,β). Every single-qubit Pauli error is coupled to the bath; energy-raising rates are positive, and attempt rates do not shrink with system size. Choose a completely positive trace-preserving encoding map Encₙ,β from one-qubit states to n-qubit states, with a completely positive trace-preserving left inverse at t=0. It may use a thermal auxiliary state and need not be efficiently preparable. For this fixed encoding, let εₙ,β(t)=inf_D sup_ρ ∥D∘Φₙ,β,t∘Encₙ,β(ρ)−ρ∥₁, where ρ ranges over all one-qubit density matrices, D over recovery channels from n qubits to one, and ∥A∥₁=Tr√(A†A). Define τₙ(β)=inf{t≥0:εₙ,β(t)>1/10}, with infimum of the empty set equal to infinity. Encoding happens before storage and recovery only at the end. This card fixes a stabilizer and thermal-bath model for the broader physical existence question; it imposes neither translation invariance nor a symmetry restriction on allowed errors.',
 answer_criterion='Prove existence of a family, one fixed finite β, and encodings with τₙ(β)→∞, or prove that no family in this stated model has that property. A bound exp(Ω(n^η)) for a fixed η>0 would be stronger than required. A lifetime improving only up to a temperature-dependent maximum system size does not suffice. Cooling the bath as n grows, increasing local interaction strengths, slowing error rates with n, enforcing an error-forbidding symmetry, or applying active correction during storage changes the target.',
 context=[
  paragraph('This record now has a claimed affirmative resolution. Balasubramanian, Davydova and Lin’s May 2026 preprint presents local three-dimensional stabilizer Hamiltonians with lifetime exp(Ω(n^η)) at sufficiently low fixed temperature, for some η>0. Its initialization is a thermal encoding. The catalogue flags this as a recent proof claim whose complete argument has not been independently verified here, rather than continuing to present the broad existence problem as confidently open.','claim'),
  paragraph('A passive memory asks the Hamiltonian and its thermal environment to preserve information between an initial encoding and a final recovery. No repeated syndrome measurements or corrections are performed during storage. Quantum information requires preserving arbitrary superpositions, not only two distinguishable classical states. A material can preserve whether it is mostly magnetized up or down while rapidly losing the phase between those two possibilities; such a material is a classical memory, not a qubit memory.','survey'),
  paragraph('The bath must be part of the mathematical specification. If errors that change the logical information are simply forbidden, a long lifetime may reflect that restriction. If every local transition is slowed as the device grows, a divergent lifetime can be manufactured by changing the clock. The generator above fixes the time scale and includes all single-qubit Pauli couplings, with ordinary positive-temperature suppression of energy-raising transitions.'),
  paragraph('An energy barrier is informative but does not alone determine memory time. A logical error may require crossing a high-energy configuration, yet the number of routes and intermediate configurations can be so large that entropy offsets the energetic suppression. Thermodynamic stability criteria therefore use both the bath dynamics and the thermal probability of configurations on which a recovery rule becomes unstable. A recovery map used to analyze the information is compatible with passive storage when it is applied only at readout.','criterion'),
  paragraph('The order of limits matters. Williamson’s layer-code result, published in August 2026, proves a regime in which lifetime grows exponentially with linear system size, but only up to a length scale exponential in inverse temperature. The lifetime at that crossover is very large as temperature falls. For the present question, however, temperature is fixed while system size goes to infinity, so an improvement restricted to a finite crossover regime is partial self-correction.','layer'),
  paragraph('Roberts, Koh, Tan and Yao’s cored product codes take a different route using disordered geometry. Their January 2026 revision reports finite-temperature simulations of a pinwheel-based three-dimensional memory with up to 60,000 qubits, finding evidence that lifetime increases with size below a critical temperature. Those numerical results motivate a candidate construction but cannot by themselves establish the infinite-family limit required here.','cored'),
  paragraph('Stahl and Nandkishore obtain protection in three dimensions by enforcing a one-form symmetry on the dynamics, even when enforcement is confined to a subvolume of vanishing relative size. This is a meaningful mechanism, but it restricts which local errors the environment may produce. The present model permits every single-qubit X, Y and Z coupling, so symmetry-protected results must be distinguished from this target.','symmetry'),
  paragraph('The May construction’s proven version uses a randomized geometric embedding; its separate explicit variant lacks a complete lifetime proof. Efficient passive preparation and stability under arbitrary local Hamiltonian perturbations are also left for further work. These are additional requirements, beyond the fixed-Hamiltonian storage question formulated here.','claim'),
  paragraph('The status distinction is useful for selecting research projects: the original existence target now requires assessment of the new theorem, while initialization, perturbation stability and alternative constructions remain separate directions. They should receive their own precise statements if added to the catalogue, rather than silently replacing the question under this identifier.')],
 why='A foundational question about whether quantum information can enjoy passive thermal protection in physical three-dimensional space. The recent claimed solution makes careful separation of storage, initialization, bath restrictions and stability especially important.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A defining problem at the intersection of quantum information and many-body physics; retained with an explicit claimed-resolution flag to preserve its history and prevent misleading open-status selection.'),
 progress=[
  step('2010','Chesi and coauthors formulate thermodynamic criteria and relaxation bounds for stabilizer and subsystem quantum memories.','criterion'),
  step('2016','Brown and coauthors survey passive thermal memories, dimensional restrictions and proposed ways around them.','survey'),
  step('2021','Stahl–Nandkishore prove symmetry-protected three-dimensional memory mechanisms with constrained dynamics.','symmetry'),
  step('2026-01-23','The cored-product revision reports finite-size evidence on memories up to 60,000 qubits.','cored'),
  step('2026-05-11','Balasubramanian–Davydova–Lin claim an affirmative solution with thermal encoding and stretched-exponential lifetime.','claim'),
  step('2026-08-25','Williamson’s layer-code result appears in PRL; its guarantee is partial self-correction over a temperature-dependent size regime.','layer')],
 references=[
  ref('criterion','Thermodynamic stability criteria for a quantum memory based on stabilizer and subsystem codes','Stefano Chesi; Daniel Loss; Sergey Bravyi; Barbara M. Terhal',2010,'https://arxiv.org/abs/0907.2807','New Journal of Physics 12, 025013; Markovian bath model and Theorem 1, used by the May 2026 construction'),
  ref('survey','Quantum memories at finite temperature','Benjamin J. Brown; Daniel Loss; Jiannis K. Pachos; Chris N. Self; James R. Wootton',2016,'https://arxiv.org/abs/1411.6643','Reviews of Modern Physics 88, 045005; passive storage, noise models and dimensional examples'),
  ref('symmetry','Symmetry protected self correcting quantum memory in three space dimensions','Charles Stahl; Rahul Nandkishore',2021,'https://arxiv.org/abs/2103.08622','Physical Review B 103, 235112; protection depends on enforcing a one-form symmetry on the dynamics'),
  ref('cored','Cored product codes for quantum self-correction in three dimensions','Brenden Roberts; Jin Ming Koh; Yi Tan; Norman Y. Yao',2026,'https://arxiv.org/abs/2510.05479','v2, 23 January; finite-temperature numerical evidence, rather than a proved thermodynamic-limit lifetime'),
  ref('claim','A passive self-correcting quantum memory in three dimensions','Shankar Balasubramanian; Margarita Davydova; Ting-Chun Lin',2026,'https://arxiv.org/abs/2605.10943','v1, 11 May; Theorems 1.1–1.2, §2.5 and §5.4; thermal encoding and limitations in §1.3. Use the trace-norm estimate, not the reversed first-threshold inequality printed in Eq. (5)'),
  ref('layer','Partial Self-Correction in Layer Codes','Dominic J. Williamson',2026,'https://journals.aps.org/prl/abstract/10.1103/mb89-8436','Physical Review Letters 137, 090601, 25 August; arXiv:2510.09218 precursor; fixed-temperature crossover remains essential')],
 status='uncertain',status_note='Claimed affirmative resolution in arXiv:2605.10943, 11 May 2026, for passive storage with thermal encoding. Its assumptions and stated theorems were checked, but the full proof was not independently verified. This is not labelled confirmed open. Review cutoff: 11 September 2026.',formulation_reviewed_on='2026-09-11')
