import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('hadwiger-conjecture-chromatic-number-clique-minors',
 id='TCS-6651', title='Hadwiger’s conjecture: high chromatic number forces a clique minor',
 area='Structural graph theory', criterion='tightness', question_type='yes_no',
 formal='For every integer t≥1 and every finite nonempty simple undirected graph G, does χ(G)≥t imply that G contains K_t as a graph minor? Equivalently, is every K_t-minor-free graph (t−1)-colorable?',
 definitions='A simple graph has no loops or parallel edges. A proper coloring assigns colors to vertices so that adjacent vertices receive different colors; χ(G) is the minimum number of colors. K_t is the complete graph on t vertices. A K_t minor is witnessed by t pairwise disjoint nonempty vertex sets B_1,…,B_t such that each induced subgraph G[B_i] is connected and every pair B_i,B_j has at least one edge between it. These branch sets can be contracted and all unwanted vertices or edges deleted. They may have arbitrary sizes; the minor need not be induced and no parity condition is imposed. Equivalently, the Hadwiger number h(G), the largest t for which G has a K_t minor, must satisfy h(G)≥χ(G). The statement concerns existence, with no running-time requirement on finding the coloring or branch sets.',
 answer_criterion='Prove the assertion for every finite graph and every t, or provide a finite graph with χ(G)>h(G), together with proofs of its required chromatic number and absence of the corresponding clique minor. An O(t) coloring bound with an unspecified constant would be substantial progress but would not establish the exact t−1 bound. A result about odd minors or subdivisions alone does not settle the stated ordinary-minor question.',
 context=[
  paragraph('A graph can have very few large complete subgraphs and still need many colors. Hadwiger asks whether contracting connected pieces always reveals a complete graph as large as the number of colors originally needed. This would make a global obstruction to coloring visible through a precise structural certificate: disjoint connected regions linked in every pair. The complete graph K_(t−1) shows that the proposed upper bound for K_t-minor-free graphs cannot be reduced.'),
  paragraph('The conjecture encompasses the Four-Color Theorem because planar graphs exclude K_5 minors. Wagner’s structure theorem makes the t=5 case equivalent to four-colorability of planar graphs. Robertson, Seymour, and Thomas extended this equivalence to t=6 by proving that a minimal counterexample in that case would be apex: deleting one vertex leaves a planar graph. Thus the known exact cases extend through K_6 minors; the first unresolved case is t=7.','six'),
  paragraph('The earlier general approach forced clique minors from high average degree. The resulting O(t√log t) degeneracy bound gives a coloring bound of the same order by repeatedly removing a low-degree vertex and coloring in reverse. That density threshold is sharp, so simply improving its numerical constant cannot yield Hadwiger’s linear target. The chromatic-number question requires using structure beyond this degree argument.','delcourt'),
  paragraph('Delcourt and Postle obtain O(t log log t) colors through a reduction to coloring much smaller minor-free subgraphs, on roughly t times a polylogarithmic number of vertices. Their reduction also shows that proving a linear bound on these small graphs would imply a linear bound without a size restriction. It narrows where a genuinely new coloring argument is needed, without imposing the small-size hypothesis on the conjecture itself.','delcourt'),
  paragraph('Liu and Luo’s September 2026 preprint builds on that reduction and claims O(t log log log t). Its proof combines contractions that reduce degeneracy with fractional colorings, which distribute weight across independent sets. Even this extra logarithm removed leaves both the O(t) weakening and the sharp coefficient in the original conjecture unresolved. The result is recorded as a new preprint claim, not as an independently verified proof.','liu'),
  paragraph('An odd clique minor imposes additional compatibility conditions on two-colorings inside its branch trees. Kühn, Sauermann, Steiner, and Wigderson construct graphs with no odd K_t minor and chromatic number approximately 1.5t, disproving the odd Hadwiger conjecture. Their graphs are not counterexamples to the ordinary-minor assertion asked here: forbidding odd minors permits more graphs than forbidding all clique minors.','odd')],
 why='A flagship structural graph problem connecting coloring, contractions, and excluded-minor classes. A resolution would identify the exact universal coloring obstruction in every minor-closed setting; improvements also develop structural tools relevant to graph algorithms and approximation.',
 importance=dict(score=98, method='editorial', assessed_on='2026-09-10', reason='One of the central graph-theoretic conjectures, with an exact extremal target and consequences across coloring and minor structure.'),
 progress=[
  step('1943','Hadwiger proposes the relation between chromatic number and complete graph minors; the current preprint restates the original assertion.','liu'),
  step('1982–1984','Kostochka and Thomason establish the asymptotically sharp average-degree threshold yielding O(t√log t) colors; sharpness of this density method does not give a matching chromatic lower bound.','delcourt'),
  step('1993','Robertson, Seymour, and Thomas prove the K_6-minor case using the Four-Color Theorem.','six'),
  step('2021–2025','Delcourt and Postle prove O(t log log t) coloring and their reduction to small graphs. The preprint began in 2021 and the journal version appeared in 2025.','delcourt'),
  step('2025-12-23','Kühn, Sauermann, Steiner, and Wigderson disprove the stronger odd-minor version, leaving ordinary Hadwiger open.','odd'),
  step('2026-09-09','Version 2 of Liu and Luo’s preprint claims an absolute-C upper bound χ(G)≤Ct log log log t for every K_t-minor-free graph and t≥16 (Theorem 1.1). This does not reach χ(G)≤t−1.','liu')],
 references=[
  ref('liu','Beyond Halfway to Hadwiger’s Conjecture','Chun-Hung Liu; Jason Luo',2026,'https://arxiv.org/abs/2609.06867v2','9 September 2026 version; Theorem 1.1 and §2 proof overview; first version 6 September'),
  ref('delcourt','Reducing Linear Hadwiger’s Conjecture to Coloring Small Graphs','Michelle Delcourt; Luke Postle',2025,'https://arxiv.org/abs/2108.01633v5','Journal of the American Mathematical Society 38(2), 481–507 (2025); 5 March 2024 preprint version, introduction and Theorem 1.6'),
  ref('six','Hadwiger’s conjecture for K6-free graphs','Neil Robertson; Paul Seymour; Robin Thomas',1993,'https://doi.org/10.1007/BF01202354','Combinatorica 13(3), 279–361; apex structure of a minimal counterexample'),
  ref('odd','Disproof of the Odd Hadwiger Conjecture','Marcus Kühn; Lisa Sauermann; Raphael Steiner; Yuval Wigderson',2025,'https://arxiv.org/abs/2512.20392','23 December 2025 preprint; ordinary formulation in Conjecture 1.1, odd-minor definition, and Theorem 1.3')],
 status='source_open', status_note='Ordinary Hadwiger remains explicitly open in the 9 September 2026 preprint; checked through 10 September 2026. The new triple-logarithmic upper bound is a preprint claim. The December 2025 disproof concerns the stronger odd-minor conjecture.', formulation_reviewed_on='2026-09-10')
