import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('search-decision-equivalence-for-finite-promise-csps',
 id='TCS-6675',title='Search-to-decision equivalence for finite promise CSPs',area='Constraint satisfaction',criterion='reductions',question_type='yes_no',
 formal='For every fixed pair of finite relational structures A and B with the same finite signature and A→B, does polynomial-time solvability of the decision promise CSP(A,B) imply polynomial-time solvability of its search version? Decision must accept X whenever X→A and reject X whenever X↛B. Search, on every X promised to satisfy X→A, must output an explicit homomorphism X→B.',
 definitions='A finite relational signature is a finite list of relation symbols with fixed positive integer arities. A structure A consists of a finite nonempty domain and one relation R^A⊆A^r for each r-ary symbol R; B and the input X have relations with the same symbols and arities. A homomorphism h:X→B is a map on domains such that (x₁,…,x_r)∈R^X implies (h(x₁),…,h(x_r))∈R^B for every symbol and tuple. Write X→B when some such map exists. A and B are constants defining the computational problem, and are not part of each input. The input explicitly lists X’s vertices and relation tuples; its encoding length is N. Both algorithms are deterministic Turing machines with running time polynomial in N on all inputs; their constants and exponents may depend on A and B. The decision algorithm may answer either way when X↛A but X→B. The search algorithm receives no homomorphism to A, only the promise that one exists. It must output the image of every vertex and satisfy every B-relation on promised inputs; outside that promise it may output anything or a failure symbol, but must still halt within its polynomial bound. The quantifiers are ∀(A,B): (∃ polynomial-time decider D)⇒(∃ polynomial-time search algorithm S). No uniform procedure that discovers D or S from arbitrary templates, and no requirement to use D as a black-box oracle, is included.',
 answer_criterion='Prove the implication for every fixed finite template pair, or identify one fixed pair with a polynomial-time decision algorithm and prove that its promised search problem has no polynomial-time algorithm. An impossibility for one rounding scheme, an undecidable problem with the template as part of the input, or hardness on instances lacking X→A does not refute the statement. A conditional separation is relevant progress but must retain its complexity assumption.',
 context=[
 paragraph('A promise CSP separates the conditions known to be satisfiable from the conditions a solution must meet. The structure A describes the stronger requirements; B describes the weaker ones. The fixed homomorphism A→B ensures that an A-solution can always be converted into a B-solution if it is known. The difficulty is that the input supplies only the existence promise, without the stronger solution itself.'),
 paragraph('Graph colouring is a concrete example. Take A to be the complete graph on three vertices and B the complete graph on six vertices. Search asks for an actual six-colouring of a graph known to be three-colourable. Decision merely separates three-colourable graphs from graphs that are not six-colourable. On graphs whose chromatic number is four, five or six, the decider may say anything. That unconstrained region is a central obstacle to turning its answers into a colouring.','algebra'),
 paragraph('Search immediately gives decision: run the search algorithm and check the proposed B-homomorphism. Every A-satisfiable input yields a valid output, while a graph or structure with no B-homomorphism can never pass verification. The all-input polynomial running-time requirement makes this argument valid even when the search promise fails. The unknown direction is whether a decider can always be made constructive.','survey'),
 paragraph('For ordinary finite CSPs, where A=B, polynomial-time decision and search are equivalent. With a genuine promise, a step-by-step fixing procedure has an extra difficulty. After committing a variable to a B-value, the residual instance may still have a B-solution but cease to have an A-solution. The original decision guarantee then no longer certifies which remaining choices are safe. Adding arbitrary pinning constraints can also change the fixed constraint language.','survey'),
 paragraph('Some positive cases are immediate. If there is a fixed finite structure C with A→C→B and a polynomial-time solver for CSP(C), solve in C and compose with the fixed map C→B. This includes the cases where CSP(A) or CSP(B) is tractable. But the general PCSP framework admits tractable examples that are not explained by an intermediate tractable finite CSP, assuming P≠NP, so this method does not cover the whole question.','survey'),
 paragraph('There are also elementary constructive relaxations. Suppose Boolean variables occur in triples, with a promise of an assignment having exactly one 1 in every triple, and the goal is merely to make each triple nonconstant. Solve the integer linear system x+y+z=1 for the listed triples, allowing arbitrary integers. The promise makes it feasible. Map positive integers to 1 and nonpositive integers to 0. No equation can have all three integers positive, or all three nonpositive, so this map satisfies every weaker triple. This illustrates a rounding rule whose correctness can be checked directly.'),
 paragraph('Larrauri’s FOCS 2025 work proves that finding a B-solution on every instance accepted by BLP, AIP or their combination can encode any chosen TFNP problem through a suitable fixed template. TFNP consists of polynomially verifiable search problems whose solutions are guaranteed to exist. The accepted instances need not satisfy X→A. Thus the rounding task can be harder than the promised search task. The May 2026 revision explicitly corrects earlier overbroad claims and keeps the general implication open.','rounding'),
 paragraph('The same work proves undecidability of several algorithmic meta-problems, where A and B are supplied as input and one asks whether a relaxation solves their PCSP. This concerns recognizing an entire family of templates. Our question permits a different fixed algorithm for each fixed template, so undecidability of that recognition task is logically compatible with a positive answer here.','rounding'),
 paragraph('Recent constructive progress also occurs under explicit algebraic hypotheses. The SODA 2026 robust-satisfiability paper gives algorithms for Boolean PCSPs with majority polymorphisms when the stronger constraints are almost satisfiable, along with matching conditional tradeoffs in several settings. Such results identify useful rounding structure, but do not provide a transformation for an arbitrary tractable decision template.','robust'),
 paragraph('The issue is fundamental because a feasibility guarantee is often only the beginning of an algorithmic application: one needs the assignment, colouring or schedule. A positive theorem would justify moving between classification of decision problems and construction of solutions throughout finite PCSPs. A negative theorem would reveal a precise local-constraint problem where efficient recognition of the promised gap conceals a harder search task.')],
 why='Determine whether every efficiently decidable finite promise constraint problem also has an efficient way to construct its promised weaker solution.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A foundational search-versus-decision question spanning graph colouring, satisfiability and the algebraic classification of finite PCSPs.'),
 progress=[
 step('2019–2021','The algebraic PCSP framework distinguishes decision and search, with the general reverse implication left open; preliminary STOC/LICS 2019 papers, JACM 2021 full article.','algebra'),
 step('2022','Krokhin–Opršal survey the open equivalence and constructive cases obtained through tractable intermediate CSPs.','survey'),
 step('2025','Larrauri proves hardness for relaxation-accepted rounding instances and undecidability of template meta-problems; FOCS 2025.','rounding'),
 step('2026-02-10','Full version of the SODA 2026 robust-satisfiability work gives constructive results for templates with specified polymorphism structure.','robust'),
 step('2026-05-25','Larrauri’s v4 clarifies the gap between rounding hardness and genuine search–decision separation; introduction footnote and §10.','rounding')],
 references=[
 ref('survey','An invitation to the promise constraint satisfaction problem','Andrei Krokhin; Jakub Opršal',2022,'https://arxiv.org/abs/2208.13538','ACM SIGLOG News 9(3), July 2022, 30–59; preprint 29 August; introduction distinguishes search and decision and gives intermediate-CSP algorithms; inherited reference'),
 ref('algebra','Algebraic approach to promise constraint satisfaction','Libor Barto; Jakub Bulín; Andrei Krokhin; Jakub Opršal',2021,'https://arxiv.org/abs/1811.00970','Checked v3, 21 June 2019; JACM 68(4), Article 28, July 2021; PCSP definitions and approximate graph-colouring framework'),
 ref('rounding','Ineffectiveness for Search and Undecidability of PCSP Meta-Problems','Alberto Larrauri',2026,'https://arxiv.org/abs/2504.04639','FOCS 2025, 1313–1350; checked v4, 25 May 2026; Theorem 1.1, definition of relaxation-accepted search, introduction footnote 1 and §10'),
 ref('robust','New Algorithms and Hardness Results for Robust Satisfiability of (Promise) CSPs','Joshua Brakensiek; Lorenzo Ciardo; Venkatesan Guruswami; Aaron Potechin; Stanislav Živný',2026,'https://arxiv.org/abs/2602.10368','v1, 10 February 2026; full version of SODA 2026 paper; robust algorithms assume majority or related polymorphism structure'),
 ref('inherited','Publications — FOCS 2025 research summary','Alberto Larrauri',None,'https://albertolarrauri.github.io/publications/','Inherited author summary; the revised full paper is used for precise scope and correction history')],
 status='source_open',status_note='Explicitly open in §10 of Larrauri’s revised full paper, dated 25 May 2026. Its rounding hardness uses a weaker input promise than X→A, and its meta-problem undecidability varies the template. The revision corrects earlier overbroad interpretations. No full resolution found through 11 September 2026; this card asks the per-template tractability implication, not a stronger uniform black-box reduction theorem.',formulation_reviewed_on='2026-09-11')
