import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('chosen-ciphertext-security-from-public-key-encryption',
 id='TCS-6548',title='Chosen-ciphertext security from ordinary public-key encryption',area='Cryptography',criterion='assumptions',question_type='yes_no',
 formal='Does the existence of IND-CPA-secure public-key encryption imply the existence of IND-CCA2-secure public-key encryption in the plain model, with classical security against all nonuniform polynomial-size adversaries and no additional computational assumption?',
 definitions='A public-key encryption scheme has uniform probabilistic polynomial-time algorithms Gen(1ⁿ)→(pk,sk) and Enc(pk,m)→c and a deterministic polynomial-time algorithm Dec(sk,c)→m or ⊥. It supports bit-string messages of any polynomially bounded length. For every polynomial p, the maximum decryption-error probability over messages |m|≤p(n) is negligible in n, with probability over key generation and honest encryption. In the IND-CPA game an adversary receives pk, chooses equal-length messages m₀,m₁ and state, receives c*=Enc(pk,m_b) for an independent uniform bit b, and guesses b. Its advantage is |Pr[guess=b]−1/2|. In the IND-CCA2 game it also has adaptive access to Dec(sk,·), both before and after choosing the challenge messages and receiving c*. After the challenge, the oracle rejects the exact bit string c*; all other ciphertext queries are allowed. Security requires negligible advantage for every nonuniform probabilistic polynomial-time adversary, allowing any polynomial number of oracle queries. Negligible means eventually smaller than n^{-a} for every a>0. Each adversary has its own polynomial resource bound, but the scheme is fixed independently of that bound. The plain model has no ideal random oracle, externally supplied common reference string, hardware or trusted setup beyond the recipient generating its own key pair. This is an unrestricted existence implication, not a requirement that a compiler treat the original scheme as a black box.',
 answer_criterion='Prove that an IND-CCA2 scheme with these guarantees exists whenever an IND-CPA scheme exists, or refute that implication in the ordinary computational model. A conversion assuming additional trapdoor functions, suitable proof systems, special pseudorandom generators or ideal random oracles does not by itself suffice. A theorem excluding a restricted class of black-box conversions is a barrier, not a negative answer to the unrestricted implication. Fixed-query bounded CCA2, pre-challenge-only CCA1 and non-malleability without adaptive decryption access are weaker targets.',
 context=[
 paragraph('Public-key encryption already allows anyone, including the attacker, to create ciphertexts. Ordinary chosen-plaintext security protects the contents of an honestly generated challenge ciphertext. Chosen-ciphertext security additionally protects it while the attacker submits other ciphertexts for decryption and uses the responses to decide what to ask next. The only forbidden query is the challenge itself, because returning its plaintext would make confidentiality impossible by definition.'),
 paragraph('A simple modification illustrates the gap between definitions. Start with a secure ordinary scheme, append an unused bit to every ciphertext, and make decryption ignore that bit. The modification preserves chosen-plaintext security. A chosen-ciphertext attacker flips the challenge’s unused bit and submits the resulting different string to the oracle, which returns the challenge plaintext. This proves that a particular CPA scheme need not itself be CCA-secure; it does not rule out building another scheme from its existence.'),
 paragraph('This is why the question concerns a construction or existence implication. A successful transformation may change the ciphertext format, use many public keys, encode messages, and inspect the original algorithms’ descriptions. It must arrange that responses to every other ciphertext remain harmless. A proof faces the corresponding simulation problem: how can it answer decryption queries while relying only on a challenge from the weaker security game?'),
 paragraph('The source proposal points to Trevisan’s cryptography project list, which explicitly asks whether CCA security can be derived from CPA security by black-box techniques or by any techniques. Its bibliography juxtaposes partial negative results with positive results for non-malleability. That distinction remains important: an advance for one attack model should not silently be reported as a solution for another.','primary'),
 paragraph('Gertner, Malkin and Myers give a black-box separation for constructions whose new decryption algorithm never calls the original encryption algorithm. This covers a substantial class of natural attempts. It still leaves constructions that re-encrypt during decryption, and does not cover arbitrary use of the source code. The scope of that restriction is central to the theorem, rather than a technical detail that can be omitted.','barrier'),
 paragraph('Choi, Dachman-Soled, Malkin and Wee construct non-malleable encryption from any semantically secure scheme and extend their approach to bounded chosen-ciphertext attacks. In the bounded version, the permitted number q of decryption queries is fixed before constructing the scheme. Full CCA2 instead asks for one scheme that withstands every polynomial-time attacker, whose query polynomial can be larger than any particular bound built into that scheme.','bounded'),
 paragraph('Another productive route adds a primitive that helps enforce ciphertext validity. Hohenberger, Koppula and Waters prove in CRYPTO 2020 that injective trapdoor functions suffice for CCA-secure public-key encryption, without requiring lossiness or correlated-product security. This removes significant earlier restrictions. An arbitrary encryption scheme is not automatically such a trapdoor function: its decryption need only recover the message, not a unique full input including encryption randomness.','trapdoor'),
 paragraph('Koppula and Waters obtain generic upgrades using a hinting pseudorandom generator, whose security survives a special kind of auxiliary information. Ordinary pseudorandomness does not state that guarantee. Their construction offers another way to organize the decryption proof, but applying it to arbitrary public-key encryption still requires establishing the additional hinting property from the original assumption.','hinting'),
 paragraph('Matsuda’s PKC 2025 work shows that a publicly verifiable noninteractive batch argument for NP can supply the additional ingredient. The May 2025 revision weakens the required proof-length savings: they need not be strong enough for currently known constructions of noninteractive zero knowledge. This is progress in reducing the extra structure needed for the upgrade. The paper still assumes the batch argument; it does not construct it from arbitrary CPA encryption.','barg'),
 paragraph('A PKC 2026 paper by Brzuska, Klooß and Woo gives CPA-to-CCA transformations for threshold encryption, where several parties jointly decrypt. Its generic transform from arbitrary CPA-secure threshold encryption uses a random oracle. Its other route has additional requirements, including a stronger semi-malicious CPA notion. The July 2026 revision therefore does not establish the plain-model implication in this card.','threshold'),
 paragraph('Resolving the implication would clarify whether protection against active ciphertext manipulation is an additional foundational assumption or a consequence of ordinary public-key confidentiality. It would also explain why existing general approaches repeatedly need structure beyond the weak starting primitive. The target is a foundational security theorem; it does not ask that the resulting construction be practical or preserve the original scheme’s efficiency.')],
 why='Determine whether public-key confidentiality alone can always be strengthened to resist adaptive decryption attacks, without importing another cryptographic assumption.',
 importance=dict(score=95,method='editorial',assessed_on='2026-09-11',reason='A central question about the minimal assumptions for robust public-key encryption, connecting encryption, proof systems, trapdoor structure and generic security transformations.'),
 progress=[
 step('2007','Gertner–Malkin–Myers exclude a class of black-box conversions whose decryption algorithm does not call the underlying encryption algorithm.','barrier'),
 step('2008','Choi–Dachman-Soled–Malkin–Wee construct non-malleable encryption from CPA encryption and obtain a bounded-CCA extension.','bounded'),
 step('2019','Koppula–Waters use a hinting PRG as an extra ingredient for generic chosen-ciphertext security transformations.','hinting'),
 step('2020','Hohenberger–Koppula–Waters derive CCA-secure encryption from arbitrary injective trapdoor functions.','trapdoor'),
 step('2025-05-12','Matsuda’s revised PKC paper weakens the batch-argument succinctness required to upgrade CPA encryption.','barg'),
 step('2026-07-17','The revised threshold-encryption work retains additional-model or stronger-security requirements in its CPA-to-CCA transformations.','threshold')],
 references=[
 ref('primary','CS 276 — Projects','Luca Trevisan',None,'https://theory.stanford.edu/~trevisan/cs276/projects.html','Inherited source; Impossibility Results section explicitly poses CCA from CPA in a black-box way or in any way; undated course page'),
 ref('barrier','Towards a Separation of Semantic and CCA Security for Public Key Encryption','Yael Gertner; Tal Malkin; Steven Myers',2007,'https://www.iacr.org/archive/tcc2007/43920433/43920433.pdf','TCC 2007; abstract states the no-encryption-query restriction on the constructed decryption algorithm'),
 ref('bounded','Black-Box Construction of a Non-malleable Encryption Scheme from Any Semantically Secure One','Seung Geol Choi; Dana Dachman-Soled; Tal Malkin; Hoeteck Wee',2008,'https://www.cs.columbia.edu/~dglasner/MyPapers/non-mal.pdf','TCC 2008; introduction’s Bounded CCA2 non-malleability discussion fixes q before the construction'),
 ref('hinting','Realizing Chosen Ciphertext Security Generically in Attribute-Based Encryption and Predicate Encryption','Venkata Koppula; Brent Waters',2019,'https://www.iacr.org/archive/crypto2019/116940363/116940363.pdf','CRYPTO 2019; extra hinting-PRG assumption, including ordinary public-key encryption as a case'),
 ref('trapdoor','Chosen Ciphertext Security from Injective Trapdoor Functions','Susan Hohenberger; Venkata Koppula; Brent Waters',2020,'https://par.nsf.gov/servlets/purl/10295635','CRYPTO 2020; introduction and main construction: injective TDFs suffice without lossiness or correlated-product assumptions; author manuscript also ePrint 2020/759'),
 ref('barg','Chosen Ciphertext Security via BARGs','Takahiro Matsuda',2025,'https://eprint.iacr.org/2023/1957','First posted 25 December 2023, PKC 2025; revised 12 May 2025, Section 1.2 weakens proof succinctness beyond what is known to imply NIZK'),
 ref('threshold','Threshold Public-Key Encryption: Definitions, Relations, and CPA-to-CCA Transforms','Chris Brzuska; Michael Klooß; Ivy K. Y. Woo',2026,'https://eprint.iacr.org/2025/1665','PKC 2026 full version, revised 17 July 2026; the arbitrary-CPA transform uses a random oracle, while the other route requires semi-malicious CPA security')],
 status='source_open',status_note='No construction from ordinary CPA-secure public-key encryption alone in the plain model, or refutation of that unrestricted implication, was found through 11 September 2026. Bounded-CCA results and constructions with injective trapdoor functions, hinting PRGs, batch arguments or random oracles leave this target open.',formulation_reviewed_on='2026-09-11')
