import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('exponential-time-hypothesis-deterministic-three-sat',
 id='TCS-6593', title='Does deterministic 3-SAT have a positive optimal exponential rate?',
 area='Parameterized and exact algorithms', criterion='tightness', question_type='yes_no',
 formal=r'''Is there a constant c>0 such that, for every deterministic algorithm A that correctly decides every 3-CNF satisfiability instance, and every constant d≥0, A does not have worst-case running time O(2^{cn}L^d)? Here n is the number of variables and L is the full binary input length. This is the deterministic Exponential Time Hypothesis (ETH).''',
 definitions=r'''A 3-CNF formula is a conjunction of explicitly listed clauses, each containing at most three literals xᵢ or ¬xᵢ. Satisfiability means existence of a Boolean assignment satisfying all clauses. Variables are relabeled consecutively; n counts the distinct variables actually present, and L includes all literal indices, signs, delimiters, and repetitions. An empty clause is unsatisfiable and an empty conjunction is satisfiable. Algorithms are uniform deterministic Turing machines with no advice or oracles; they must halt and answer exactly on all inputs, with no promise about density, solution count, or distribution. Define s₃=inf{α≥0 : some such algorithm runs in O(2^{αn}L^d) for a fixed d}. ETH asserts s₃>0. The excluded exponent c is a single constant independent of the algorithm. The polynomial exponent and hidden constant may depend on the algorithm, but not the instance. Polynomial input factors allow the complete formula to be read even if clauses are repeated many times.''',
 answer_criterion='Prove s₃>0, or refute ETH by proving that for every ε>0 there is a deterministic O(2^{εn}L^{d_ε})-time 3-SAT algorithm. A single 2^{o(n)}L^{O(1)}-time algorithm would suffice for refutation, but the infimum formulation does not require that all ε-speedups be supplied by one algorithm. An improvement to any fixed positive exponent is compatible with ETH.',
 context=[
  paragraph('NP-completeness describes the possibility of polynomial-time algorithms and does not itself impose a positive exponential rate. Even if P differs from NP, a running time such as 2^{√n} remains possible for 3-SAT. ETH asks for a stronger obstruction: some fixed amount of exponential work must remain unavoidable when complexity is measured by the number of Boolean choices.','foundation'),
  paragraph('That parameter must be preserved carefully by a reduction. An ordinary polynomial-time reduction may turn an n-variable formula into an instance of size n³, which can destroy a claimed exponential lower bound in the new parameter. Sparsification supplies a controlled disjunction of bounded-density formulas, allowing variables and clauses to be related without an arbitrary polynomial blowup. This is a main reason ETH can support sharp bounds across many problems.','book'),
  paragraph('The infimum over all algorithms matters. Excluding one 2^{o(n)} algorithm is the common informal wording, but the textbook explicitly keeps the stronger positive-infimum statement because the converse is unclear. ETH would be false if arbitrarily small constant exponents were attainable, even if the known algorithms depended on the desired exponent. A card that omitted this distinction would change the quantified question.','book'),
  paragraph('There are substantial deterministic improvements over trying all 2ⁿ assignments. Liu combines branching with derandomized local search to obtain a 1.32793ⁿ bound for 3-SAT, up to polynomial factors. Such an algorithm decreases an upper bound on s₃ while leaving it positive. Empirical solver success, promises of many solutions, and bounded-occurrence restrictions do not address worst-case unrestricted formulas.','liu'),
  paragraph('ETH is weaker than SETH, whose optimal rates approach one as the fixed clause width grows. It also differs from randomized ETH and from Gap-ETH, which asks for hardness of distinguishing fully satisfiable formulas from formulas with a constant unsatisfied fraction. Recent lattice reductions illustrate the value of tracking these distinctions: some approximation hardness can be obtained from deterministic ETH, while other results use randomized ETH. They extend the consequences of assumptions without proving the assumptions.','lattices')],
 why='ETH is the central hypothesis for ruling out subexponential exact algorithms and many fixed-parameter speedups. It turns the qualitative P versus NP question into a quantitative claim that can be transferred through carefully sized reductions.',
 importance=dict(score=98, method='editorial', assessed_on='2026-09-10', reason='A foundational quantitative hardness hypothesis underlying exact, parameterized, graph, and geometric algorithm lower bounds.'),
 progress=[
  step('2001','Impagliazzo and Paturi formalize the exponential rates of k-SAT and study their relations. These rates remain conjectural lower bounds against unrestricted algorithms.','foundation'),
  step('2013','The authors’ IPEC survey describes how exact satisfiability complexity connects to parameterized complexity, circuit lower bounds, and data structures.','ipec'),
  step('2015','The parameterized-algorithms textbook states ETH as a positive infimum, develops sparsification, and derives consequences including FPT≠W[1]. It distinguishes randomized variants.','book'),
  step('2018','Liu gives a deterministic 3-SAT upper bound with base 1.32793 using branching and generalized covering codes. The saving leaves a positive exponential rate.','liu'),
  step('2026','Aggarwal, Gupta, Morolia, and Zhang obtain new lattice approximation hardness from ETH or randomized ETH, depending on the target problem and reduction. Their ICALP paper continues to treat these as hypotheses and separates them from Gap-ETH.','lattices')],
 references=[
  ref('foundation','On the Complexity of k-SAT','Russell Impagliazzo; Ramamohan Paturi',2001,'https://cseweb.ucsd.edu/~paturi/myPapers/pubs/ImpagliazzoPaturi_2001_jcss.pdf','JCSS 62(2), 367–375; exponential rates sₖ and ETH; DOI 10.1006/jcss.2000.1727'),
  ref('book','Parameterized Algorithms','Marek Cygan; Fedor V. Fomin; Łukasz Kowalik; Daniel Lokshtanov; Dániel Marx; Marcin Pilipczuk; Michał Pilipczuk; Saket Saurabh',2015,'https://www.mimuw.edu.pl/~malcin/book/parameterized-algorithms.pdf','§14.1, Conjecture 14.1 and pages 469–470 on the infimum and subexponential distinction; sparsification and parameterized consequences in Chapter 14'),
  ref('ipec','Exact Complexity and Satisfiability','Russell Impagliazzo; Ramamohan Paturi',2013,'https://cseweb.ucsd.edu/~paturi/myPapers/pubs/ImpagliazzoPaturi_2013_ipec.pdf','IPEC 2013, LNCS 8246, 1–3; invited survey and definition s₃>0'),
  ref('liu','Chain, Generalization of Covering Code, and Deterministic Algorithm for k-SAT','S. Cliff Liu',2018,'https://arxiv.org/abs/1804.07901','ICALP 2018; version 7 dated 17 March 2020; deterministic 1.32793ⁿ bound for 3-SAT'),
  ref('lattices','Mind the Gap? Not for SVP Hardness Under ETH!','Divesh Aggarwal; Rishav Gupta; Aditya Morolia; Chuanqi Zhang',2026,'https://doi.org/10.4230/LIPIcs.ICALP.2026.8','ICALP 2026, Article 8; introduction and hypothesis definitions; deterministic ETH for approximate CVP, randomized ETH for the stated SVP result')],
 status='source_open', status_note='The cited foundational and 2026 conference sources treat ETH as an open hypothesis. Checked through 10 September 2026. This formulation is uniform, deterministic, and a positive-infimum assertion; randomized, nonuniform, gap, and stronger all-width hypotheses are distinct.', formulation_reviewed_on='2026-09-10')
