import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('collision-resistant-hashing-from-one-way-functions',
 id='TCS-6547',title='Does one-wayness suffice for collision-resistant hashing?',area='Cryptography',criterion='assumptions',question_type='yes_no',
 formal='In the ordinary classical computational model, does the existence of a polynomial-time computable one-way function secure against all polynomial-size circuit families imply the existence of a publicly keyed collision-resistant hash family H_k:{0,1}^{2λ}→{0,1}^λ secure against all polynomial-size circuit families?',
 definitions='A one-way function is a deterministic uniformly polynomial-time computable map f on finite binary strings, with output length bounded by a polynomial in the input length, such that for every family of possibly randomized Boolean circuits A_n of size polynomial in n, Pr[f(A_n(1^n,f(X)))=f(X) and |A_n(1^n,f(X))|=n] is negligible in n, where X is uniform on {0,1}^n. The same invocation of A_n supplies the candidate preimage in both parts of this event. A function μ is negligible if for every c>0 there is N_c such that μ(n)≤n^{-c} for all n≥N_c. A hash family consists of a uniform probabilistic polynomial-time key generator Gen(1^λ) producing a polynomial-length public key k, and a uniform deterministic polynomial-time evaluator H(1^λ,k,x). For every key in the generator’s support, H_k maps every 2λ-bit input to a λ-bit output. Collision resistance means that for every polynomial-size possibly randomized circuit family B_λ, the probability that B_λ(1^λ,k) outputs distinct x,x′∈{0,1}^{2λ} with H_k(x)=H_k(x′) is negligible in λ, over k←Gen(1^λ) and the attacker’s coins. Both messages may be chosen after the attacker sees k. Circuit descriptions may depend on the security parameter, but not on the freshly sampled key. The implication permits arbitrary use of the description of f and arbitrary proof techniques; no random oracle, additional setup assumption, quantum resource, trapdoor, or stronger quantitative hardness assumption is supplied.',
 answer_criterion='Establish the stated existence implication without additional assumptions, or refute it in the ordinary unrelativized model. A positive result may use non-black-box techniques. An oracle world where one-way functions exist but collision-resistant hashing fails proves only a relativizing barrier. Failure of a particular construction, even for a specific one-way function, is also insufficient to refute the existence implication. Producing only target-collision resistance, noncompressing injective functions, or a construction from stronger product-hardness assumptions does not settle the proposition.',
 context=[
 paragraph('A collision-resistant hash compresses its input while making it computationally difficult to find two distinct messages with the same digest. Collisions must exist by the pigeonhole principle: there are 2^{2λ} possible inputs and only 2^λ outputs. Security is therefore not a claim that collisions never occur, or that a digest uniquely identifies a message. It is a claim about what an efficient adversary can construct after learning the hash key.'),
 paragraph('A one-way function poses a different challenge. The attacker receives the image of a random input and must find any preimage. An injective one-way function can have no collisions at all, yet it is not a compressing hash. Conversely, a compressing map may have easily found collisions even if some inversion tasks look difficult. The question asks whether the minimal assumption of computationally hard inversion can always supply the more structured difficulty of finding collisions.','product'),
 paragraph('The public key matters to the asymptotic definition. If a single compressing function were fixed at each security parameter and security were required against nonuniform circuits, an attacker could hard-code one collision for each parameter. A fresh polynomial-length key prevents that pair from being selected in advance for the actual function used. The key is not secret: the adversary sees it before choosing either colliding message.'),
 paragraph('Target-collision resistance changes the order of moves. An attacker first commits to one message, then sees a random key and seeks a second message colliding with its committed target. Rompel constructs universal one-way hash functions of this kind from arbitrary one-way functions, as part of the route to secure signatures. That theorem does not give the present game, where both messages are chosen after the key is known. The order difference is small syntactically but central to the unresolved assumption gap.','rompel'),
 paragraph('Simon constructs an oracle setting with one-way permutations but no collision-resistant hash functions in the relevant relativized sense. It rules out building and proving the desired primitive by treating the assumed function purely as an oracle in the separated framework. The theorem does not rule out exploiting a function’s implementation or a proof that fails to relativize. The ordinary mathematical implication in this card therefore remains stronger than the black-box construction question already answered negatively.','simon'),
 paragraph('Holmgren and Lombardi give a positive route under stronger assumptions about simultaneously inverting independent challenges. Their one-way product functions require quantitative batch hardness beyond ordinary one-wayness. They construct collision-resistant hashing from suitable such functions and connect the missing assumption to unusually strong parallel repetition. This identifies a concrete intermediate target without showing that every ordinary one-way function possesses the required batch security.','product'),
 paragraph('The separation also connects hashing to total search problems. Given a circuit for a compressing map, a collision is guaranteed to exist and can be checked efficiently. Folwarczný and coauthors study whether one-way functions can establish hardness for total NP search more generally, extending limitations for a class of single-query reductions. These are restrictions on reductions, not an unconditional proof that collision-resistant families cannot follow from one-wayness by any method.','tfnp'),
 paragraph('Applications can sometimes avoid the full primitive. Rothblum’s July 2026 work constructs efficient interactive arguments for bounded-space computations from one-way functions. Communication depends on the space bound times a polynomial in log T and the security parameter, and the security loss depends polynomially on the computation time T. This weakens assumptions for that interactive application; it does not construct a publicly evaluable compressing hash that withstands arbitrary key-dependent collision attempts.','arguments'),
 paragraph('A resolution would clarify the foundations of many protocols that use short commitments to large data. It would either place full collision resistance on the same assumption level as ordinary one-wayness, or demonstrate a separation that survives beyond black-box barriers. The card asks for polynomial security only; requiring near-optimal exponential security or resistance to quantum attacks would introduce additional questions.')],
 why='Determines whether a fundamental compressing cryptographic primitive needs assumptions beyond ordinary one-wayness, while exposing the gap between known black-box barriers and unrestricted constructions.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A central unresolved implication among cryptographic primitives, with consequences for authentication, data commitments and succinct verification.'),
 progress=[
 step('1990','Rompel obtains universal one-way hashing and secure signatures from arbitrary one-way functions; this uses the weaker target-before-key collision game.','rompel'),
 step('1998','Simon proves an oracle separation from one-way permutations, establishing the classical black-box obstacle.','simon'),
 step('2018','Holmgren–Lombardi construct collision-resistant hashing from quantitatively strong one-way product functions, an additional assumption.','product'),
 step('2023-06-16','Folwarczný and coauthors extend related barriers to single-query reductions for total search.','tfnp'),
 step('2026-07-02','Rothblum constructs bounded-space interactive arguments from one-way functions, without resolving the hashing implication.','arguments')],
 references=[
 ref('rompel','One-Way Functions are Necessary and Sufficient for Secure Signatures','John Rompel',1990,'https://www.cs.princeton.edu/courses/archive/spr08/cos598D/Rompel.pdf','STOC 1990, pp. 387–394; universal one-way hashing, not full key-first collision resistance'),
 ref('simon','Finding collisions on a one-way street: Can secure hash functions be based on general assumptions?','Daniel R. Simon',1998,'https://link.springer.com/chapter/10.1007/BFb0054137','EUROCRYPT 1998, LNCS 1403, pp. 334–345; electronic archive dates in 2006 are not the original publication year'),
 ref('product','Cryptographic Hashing From Strong One-Way Functions: Or: One-Way Product Functions and their Applications','Justin Holmgren; Alex Lombardi',2018,'https://ieee-focs.org/FOCS-2018-Papers/pdfs/59f850.pdf','FOCS 2018; Question I.1 and §I.A; DOI 10.1109/FOCS.2018.00085'),
 ref('tfnp','One-Way Functions vs. TFNP: Simpler and Improved','Lukáš Folwarczný; Mika Göös; Pavel Hubáček; Gilbert Maystre; Weiqiang Yuan',2023,'https://eprint.iacr.org/2023/945','Manuscript 16 June; §1 and the stated single-query/semi-black-box restriction'),
 ref('arguments','Doubly-Efficient Interactive Arguments for Bounded-Space from One-Way Functions','Guy N. Rothblum',2026,'https://eccc.weizmann.ac.il/report/2026/111/','2 July; verifier time (S+n)·poly(log T,κ), polylog(T) rounds, and explicit soundness-security loss')],
 status='source_open',status_note='No unrestricted implication or refutation was found in the primary literature checked through 11 September 2026. Existing black-box separations do not settle this ordinary-model existence statement. The definitions explicitly use uniform honest algorithms, nonuniform classical adversaries, public fresh keys and factor-two compression.',formulation_reviewed_on='2026-09-11')
