import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('fo-model-checking-on-hereditary-monadically-dependent-classes',
 id='TCS-6678',title='FO model checking on hereditary monadically dependent graph classes',area='Database theory and finite model theory',criterion='characterization',question_type='yes_no',
 formal='For every hereditary effectively monadically dependent class C of finite simple graphs, do there exist a deterministic algorithm A_C, a computable function f_C:N→N and a constant d_C such that A_C decides whether G satisfies a first-order sentence φ in time f_C(|φ|)(|V(G)|+1)^{d_C} for every G∈C? The precise effectiveness condition is given below; the graph is supplied without a structural decomposition.',
 definitions='The class C is fixed, is closed under isomorphism and induced subgraphs, and is not part of each input. First-order sentences use equality, adjacency E(x,y), Boolean connectives and quantifiers over individual vertices. They do not quantify over sets, and no vertex order or arithmetic is supplied. The input is the explicitly represented graph G and the sentence φ; the parameter k=|φ| is its encoded length. The algorithm must halt on every input, and its correctness and stated time bound are required when G∈C; it need not recognize membership in C. To define monadic dependence, let θ(x,y) be any fixed first-order formula using adjacency and finitely many additional unary predicates. A graph in T_θ(G) is obtained by interpreting these predicates as arbitrary vertex subsets, putting an edge between distinct u,v whenever θ(u,v) or θ(v,u) holds, and taking any induced subgraph. C is monadically dependent when no single θ gives all finite graphs among the outputs T_θ(G), G∈C. For an explicit effective version, define P_s as the bipartite powerset graph with vertices a₁,…,a_s and b_S for every S⊆{1,…,s}, and edges a_i b_S exactly when i∈S. Require a computable function b:N→N_{≥1} such that, for every formula θ and every G∈C, P_{b(|θ|)} is absent from T_θ(G). Formula length includes its predicate symbols under a fixed effective encoding. This is the computable dependence-function convention of Mählmann’s Definition 12.24. The programs computing b and the eventual algorithm may depend on C; they are not extra per-instance certificates. The exponent d_C is independent of k. The query-evaluation problem here is for the plain graph signature; unary colours occur in the structural definition.',
 answer_criterion='Prove this class-wise fixed-parameter tractability statement with a computable parameter dependence, or exhibit a hereditary class satisfying the stated effective dependence condition for which it fails. If the negative result relies on a parameterized complexity separation, state that assumption. A running time n^{g(|φ|)}, a theorem requiring an input decomposition, or a result limited to monadically stable classes does not establish the target. The effectiveness assumption may not be left implicit or replaced by an arbitrary noncomputable runtime bound.',
 context=[
 paragraph('First-order logic describes many small graph queries with quantifiers over vertices. For example, the existence of a dominating set of size k can be expressed by choosing k vertices and requiring every vertex to equal or be adjacent to one of them. A direct evaluation can try n^k choices. Fixed-parameter tractability asks for the stronger form f(k)n^d: the query may be expensive, but its length must not keep increasing the exponent of the graph size.'),
 paragraph('Graph structure can make this possible. The broad research programme asks which hereditary classes support such evaluation. Hereditary means that deleting vertices keeps a graph inside the class, a natural closure property when a query examines a portion of a database or network. Sparse graph classes gave early positive results, but dense classes with controlled structure also admit efficient model checking. Thus density alone cannot describe the boundary.','survey'),
 paragraph('Monadic dependence measures whether unrestricted graph structure can be hidden inside a class through a fixed logical interpretation. Unary predicates mark arbitrary vertex subsets. A formula then defines new edges, after which selected vertices may be retained. If this process can generate every finite graph, apparently restricted inputs still contain arbitrary graph complexity in an interpretable form. Monadic dependence forbids that possibility.','survey'),
 paragraph('The effective hypothesis matters to the exact computational claim. A structural class can have finite obstruction bounds at every logical complexity while those bounds grow faster than any computable function. Mählmann makes the dependence condition quantitative using forbidden powerset graphs and distinguishes computable parameter bounds from weaker conventions for fixed-parameter tractability. This card adopts that explicit effective formulation, so “there exists a finite bound” is not silently substituted for an algorithmically bounded parameter function.','effective'),
 paragraph('One direction of the broader classification has been established. Dreier, Mählmann and Toruńczyk prove that first-order model checking is AW[*]-hard on every hereditary monadically independent graph class. Under the standard assumption FPT≠AW[*], this excludes efficient model checking on the independent side. Their structural characterization uses flip-breakability, a separation property allowing controlled changes to adjacency between vertex groups. The missing direction is the algorithm for dependent classes.','hardness'),
 paragraph('A major positive theorem proves fixed-parameter tractability for monadically stable classes. Stability additionally forbids interpreting arbitrarily long linear orders; dependence forbids arbitrary graph encoding and allows more classes. The 2023 preprint by Dreier, Eleftheriadis, Mählmann, McCarty, Pilipczuk and Toruńczyk, published at FOCS 2024, settles the stable case using neighborhood complexity and suitable covers. It does not make the two structural notions equivalent.','stable'),
 paragraph('Merge-width offers another route. Dreier and Toruńczyk describe a graph by a sequence of successively coarser vertex partitions, recording deviations from default adjacencies between parts. Their model-checking theorem applies to bounded merge-width when a witnessing construction sequence is supplied. Two issues remain in applying this approach to the entire target class: obtaining the necessary structural bounds and computing a suitable sequence from the graph alone.','merge'),
 paragraph('The July 2026 neighborhood-complexity paper proves that, for every fixed positive η, the number of distinct sets N(v)∩A is O(|A|^{1+η}) in a monadically dependent class, with the constant depending on the class and η. It also constructs sequences witnessing radius-one merge-width n^{o(1)} in polynomial time. This supplies a concrete structural and algorithmic step. General first-order formulas require control at radii depending on the formula, so radius one does not complete the model-checking argument.','neighborhood'),
 paragraph('Related February 2026 work by Dreier and Kuske accelerates the construction of low-crossing orders and neighborhood covers, improving model-checking runtimes within the already tractable monadically stable setting. Such refinements are useful because they make the structural tools more practical, while leaving the dependent-versus-stable boundary in place.','welzl'),
 paragraph('A positive answer would unify several major algorithmic graph frameworks through one logical condition and explain when small declarative queries can avoid repeated high-dimensional enumeration. A counterexample satisfying the effective hypothesis would show that the absence of arbitrary logical graph encoding is insufficient for tractability. Either outcome would sharpen the connection between graph structure and query evaluation.')],
 why='Determine whether excluding arbitrary first-order graph encoding exactly supplies the structure needed for tractable logical queries on hereditary graph classes.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='The central proposed tractability boundary for first-order model checking on hereditary graph classes, connecting database queries, model theory, sparsity and dense graph structure.'),
 progress=[
 step('2023–2024','First-order model checking becomes fixed-parameter tractable on monadically stable graph classes; preprint November 2023, FOCS 2024.','stable'),
 step('2024','Flip-breakability yields a combinatorial characterization and AW[*]-hardness for hereditary monadically independent classes; STOC 2024.','hardness'),
 step('2024-09-05','Mählmann’s dissertation makes effective dependence and computable parameter bounds explicit; Definition 12.24 and surrounding discussion.','effective'),
 step('2025–2026','Merge-width gives model checking with a supplied construction sequence; STOC 2025, checked full version revised 23 June 2026.','merge'),
 step('2026-02-16','Dreier–Kuske improve low-crossing-order and neighborhood-cover algorithms, with faster model checking on monadically stable classes.','welzl'),
 step('2026-07-12','Almost-linear neighborhood complexity and polynomial-time construction of radius-one merge-width sequences are established for all monadically dependent classes.','neighborhood')],
 references=[
 ref('survey','Graph classes through the lens of logic','Michał Pilipczuk',2025,'https://arxiv.org/abs/2501.04166','v1, 7 January 2025; Conjecture 2 and sections on monadic dependence and model checking; class-wise exponent may depend on C'),
 ref('effective','Monadically Stable and Monadically Dependent Graph Classes: Characterizations and Algorithmic Meta-Theorems','Nikolas Mählmann',2024,'https://media-api.suub.uni-bremen.de/api/core/bitstreams/64278fff-a8bb-43a8-aa91-32469c6394ac/content','University of Bremen dissertation, defended 5 September 2024; pp. 157–159, Example 12.23, Definition 12.24 and Theorem 12.25 distinguish computable dependence bounds'),
 ref('hardness','Flip-Breakability: A Combinatorial Dichotomy for Monadically Dependent Graph Classes','Jan Dreier; Nikolas Mählmann; Szymon Toruńczyk',2024,'https://arxiv.org/abs/2403.15201','Checked v2, 27 March 2024; STOC 2024, 1550–1560; hereditary monadically independent classes are AW[*]-hard'),
 ref('stable','First-Order Model Checking on Monadically Stable Graph Classes','Jan Dreier; Ioannis Eleftheriadis; Nikolas Mählmann; Rose McCarty; Michał Pilipczuk; Szymon Toruńczyk',2024,'https://arxiv.org/abs/2311.18740','Preprint 30 November 2023; FOCS 2024, 21–30; tractability for the stable subclass; computable-parameter qualification made explicit in Mählmann’s thesis'),
 ref('merge','Merge-width and First-Order Model Checking','Jan Dreier; Szymon Toruńczyk',2026,'https://arxiv.org/abs/2502.18065','STOC 2025, 1944–1955; checked v2, 23 June 2026; bounded merge-width theorem requires an input construction sequence'),
 ref('welzl','Near-Linear Time Computation of Welzl Orders on Graphs with Linear Neighborhood Complexity','Jan Dreier; Clemens Kuske',2026,'https://arxiv.org/abs/2602.14625','v1, 16 February 2026; randomized low-crossing-order algorithm and applications to neighborhood covers and monadically stable model checking'),
 ref('neighborhood','Neighborhood Complexity and Radius-1 Merge-Width in Monadically Dependent Graph Classes','Jan Dreier; Nikolas Mählmann; Rose McCarty; Michał Pilipczuk; Szymon Toruńczyk',2026,'https://arxiv.org/abs/2607.10941','v1, 12 July 2026; Conjecture 1, Theorem 2 and algorithmic radius-one construction; full tractability direction explicitly retained'),
 ref('slides','Monadically stable graph classes — Oberwolfach talk','Rose McCarty',2025,'https://mccarty.math.gatech.edu/McCarty-2025-Oberwolfach.pdf','Inherited source; motivating hereditary-class model-checking conjecture'),
 ref('flipwidth','Flip-Width: Cops and Robber on Dense Graphs','Szymon Toruńczyk',2023,'https://ieee-focs.org/FOCS-2023-Papers/pdfs/FOCS2023-35YPEGokY3iqqos5xlCDsn/189400a663/189400a663.pdf','FOCS 2023; Conjecture I.1; inherited source')],
 status='source_open',status_note='Explicitly open in the July 2026 neighborhood-complexity paper. The independent-side hardness and stable-side algorithm are known; radius-one merge-width does not provide the full algorithm. This card fixes the effective dependence-function convention to require a computable FPT bound. No resolution found through 11 September 2026.',formulation_reviewed_on='2026-09-11')
