import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from authoring import finish,ref,step,paragraph
finish('exact-unassisted-qubit-depolarizing-capacity',
 id='TCS-6519',title='Exact quantum capacity of the qubit depolarizing channel',area='Quantum computation',criterion='tightness',question_type='exact_value',
 formal='Determine Q(q), the unassisted asymptotic quantum capacity of D_q(ρ)=(1−q)ρ+(q/3)(XρX+YρY+ZρZ), for every real q∈[0,1]. Capacity is measured in reliably transmitted qubits per independent channel use, under the coding definition below.',
 definitions='ρ is a one-qubit density matrix. The Pauli operators satisfy X|0⟩=|1⟩, X|1⟩=|0⟩, Z|0⟩=|0⟩, Z|1⟩=−|1⟩ and Y=iXZ. Thus q is the total probability of a nonidentity Pauli error, each type having probability q/3. For block length n, choose an integer kₙ≥0 and completely positive trace-preserving maps Eₙ from kₙ qubits to n qubits and Rₙ from n qubits to kₙ qubits. Let |Φₖ⟩=2^{−k/2}Σ_{x∈{0,1}ᵏ}|x⟩_A|x⟩_B, and define Fₙ=⟨Φ_{kₙ}|[id_A⊗(Rₙ∘D_q^{⊗n}∘Eₙ)](|Φ_{kₙ}⟩⟨Φ_{kₙ}|)|Φ_{kₙ}⟩. A rate r≥0 is achievable if there is a sequence of such codes with liminfₙ kₙ/n≥r and Fₙ→1. Q(q) is the supremum of achievable rates. Sender and receiver have no initially shared entanglement, classical side channel, feedback, or auxiliary quantum channel. Encoding and recovery may be computationally unrestricted and jointly process an entire block. The same q is used independently on every channel use. This definition concerns transmission of quantum states, not merely classical bits through a quantum device.',
 answer_criterion='Give an explicit determination of the function Q(q) and prove matching achievability and converse bounds: every rate below the proposed value is achievable and no rate above it is achievable, for each q. Evaluating only a fixed block length, identifying only where capacity becomes zero, giving an approximation of unspecified accuracy, or restating the existing unbounded coherent-information optimization does not determine the requested function. The already known endpoints and zero-capacity region must be consistent with the answer.',
 context=[
 paragraph('This channel is a basic model of unbiased qubit noise: a bit flip, a phase flip, or both occur with equal probabilities. Its one-parameter definition hides a hard coding problem. A quantum code must preserve superpositions and correlations with a reference system, which is why the fidelity test in the definition uses half of a maximally entangled state. Correctly transmitting only computational-basis strings would test a weaker, classical task.'),
 paragraph('Noise conventions differ substantially between papers. In this card q is the total Pauli error probability. A paper writing probabilities (1−3p,p,p,p) uses p=q/3. A paper writing (1−λ)ρ+λI/2 uses λ=4q/3 on the usual mixture range q≤3/4. For example, q=3/4 completely erases the input, even though the channel formula remains a valid quantum channel for all q≤1. The 2026 threshold values below have been converted to q once.'),
 paragraph('Quantum coding theorems give an exact but unbounded optimization: Q(q)=supₙ max_σ I_c(σ,D_q^{⊗n})/n. Here I_c is the output entropy minus the entropy jointly held by the output and a purifying reference, with entropy S(τ)=−Tr(τ log₂τ). This regularization permits inputs entangled across channel uses. It identifies the mathematical quantity, but does not by itself evaluate this particular function.','coding'),
 paragraph('Using a maximally mixed one-qubit input gives the hashing lower bound max{0,1−h₂(q)−q log₂3}, where h₂ is binary entropy and 0 log₂0 is interpreted as zero. The expression becomes zero near q=0.1893. Degenerate quantum codes can surpass this benchmark because multiple physical errors can have the same effect on the encoded information. Consequently counting error types as if each required separate correction can underestimate achievable rates.','symmetry'),
 paragraph('Agarwal and coauthors’ May 2026 paper searches rank-two input states inside the permutation-symmetric subspace, using representation theory to evaluate many-copy coherent information. It reports a 45-copy numerical positivity threshold p=0.064657, or q=0.193971 here, and explains how degeneracy suppresses the effective environment entropy. This is evidence for better codes and a lower bound on the true threshold, not an optimization over all possible block lengths and states.','symmetry'),
 paragraph('Krohn-Grimberghe’s August revision provides an explicit 45-copy state with exact-arithmetic certificates for positive coherent information at q=48717/250000=0.194868. The result extends positivity to smaller q by channel composition and data processing. The preprint distinguishes the threshold printed in the May paper from a stronger state in its authors’ public repository, and bounds both that state and the new witness using certified arithmetic. The certificates are supplied by the author; this review checked the stated bounds and conventions but did not independently rerun the verification artifact.','certified'),
 paragraph('On the upper-bound side, Q(0)=1 and Q(q)=0 for every q≥1/4. In the latter range the channel is antidegradable: the environment can simulate the receiver’s output. Reliable positive-rate transmission would then permit incompatible copies of unknown quantum information. Between the current positive-capacity lower bound and q=1/4, even the location where capacity vanishes remains unsettled. Determining that location would still leave the exact positive-rate curve to be found.','cloning'),
 paragraph('There are also finer results away from the threshold. Leditzky, Leung and Smith control the gap between single-letter coherent information and capacity at low noise through approximate degradability. Zhu and coauthors optimize channel extensions to obtain tighter upper bounds, with their work presented at TQC 2026. These techniques reduce the gap without proving that a proposed family of codes is optimal at every noise value.','low'),
 paragraph('Kondra and coauthors’ August 2026 strong-converse result concerns fidelity decay above capacity for degradable and antidegradable channels. Such a theorem strengthens the operational meaning of an upper bound, but does not supply the unknown capacity curve of the depolarizing channel in its intermediate regime. A full resolution here must match the best achievable rates with upper bounds that apply to arbitrary encodings and arbitrary block lengths.','strong')],
 why='The unresolved communication limit of a canonical quantum-noise model. It tests whether quantum coding theory can turn regularized existence formulas into sharp quantitative limits despite degeneracy and multi-copy advantages.',
 importance=dict(score=96,method='editorial',assessed_on='2026-09-11',reason='A benchmark capacity problem connecting quantum error correction, information-theoretic converses and the operational effect of entangled encodings.'),
 progress=[
 step('2000','Cerf derives no-cloning upper bounds for Pauli channels, including the depolarizing zero-capacity boundary.','cloning'),
 step('2005','Devetak proves quantum coding and converse results underlying the regularized coherent-information formula.','coding'),
 step('2018','Leditzky–Leung–Smith determine low-noise capacities to leading orders; their arXiv v3 strengthens a lemma in December 2023.','low'),
 step('2025-10-14','Zhu and coauthors revise geometric optimization bounds; this work is presented at TQC on 4 September 2026.','geometric'),
 step('2026-05-13','Agarwal and coauthors revise improved capacity-threshold lower bounds from symmetric rank-two states.','symmetry'),
 step('2026-08-02','Kondra and coauthors give exponential strong converses for degradable and antidegradable channels.','strong'),
 step('2026-08-18','Krohn-Grimberghe’s v2 retains certified positivity at total Pauli error q=0.194868 and clarifies the scope of the certificate claims.','certified')],
 references=[
 ref('coding','The private classical capacity and quantum capacity of a quantum channel','Igor Devetak',2005,'https://arxiv.org/abs/quant-ph/0304127','IEEE Transactions on Information Theory 51, 44–55; coding theorem and converse'),
 ref('cloning','Quantum cloning and the capacity of the Pauli channel','Nicolas J. Cerf',2000,'https://arxiv.org/abs/quant-ph/9803058','Physical Review Letters 84, 4497; no-cloning upper bound; full-range antidegradability is also recorded after Corollary 6 of the August 2026 certificate paper'),
 ref('low','Quantum and private capacities of low-noise channels','Felix Leditzky; Debbie Leung; Graeme Smith',2018,'https://arxiv.org/abs/1705.04335','Physical Review Letters 120, 160503; latest v3, 5 December 2023; §4.1 and Theorem 13 for depolarizing noise'),
 ref('geometric','Geometric optimization for quantum communication','Chengkai Zhu; Hongyu Mao; Kun Fang; Xin Wang',2025,'https://arxiv.org/abs/2509.15106','v2, 14 October; §3.4 upper bounds for depolarizing channels; TQC 2026 Information Theory session, 4 September'),
 ref('symmetry','Enhanced quantum capacity thresholds from symmetry','Avantika Agarwal; Amolak Ratan Kalra; Sungjai Lee; Debbie Leung; Luke Schaeffer; Pulkit Sinha; Graeme Smith',2026,'https://arxiv.org/abs/2605.09138','v2, 13 May; §1.2 reports per-Pauli p=0.064657 at length 45; numerical threshold evaluation'),
 ref('certified','A certified lower bound on the quantum-capacity threshold of the depolarizing channel','Artus Krohn-Grimberghe',2026,'https://arxiv.org/abs/2608.15870','v2, 18 August; Theorem 5, Corollary 6 and §7 limitations; q=3p conversion; verification artifact DOI 10.5281/zenodo.21962925'),
 ref('strong','Sharp Quantum Capacity Thresholds: Exponential Strong Converses for Degradable and Antidegradable Channels','Tulja Varun Kondra; Raphael Brinster; Hermann Kampermann; Dagmar Bruß; Nikolai Wyderka',2026,'https://arxiv.org/abs/2608.01308','v1, 2 August; fidelity above capacity, not an exact evaluation of the intermediate depolarizing-capacity curve')],
 status='source_open',status_note='Exact unassisted capacity remains open in the 2026 primary literature. The August certificate improves a positive-capacity lower bound, without claiming an exact threshold or capacity formula. All displayed thresholds use total Pauli error q. Review cutoff: 11 September 2026.',formulation_reviewed_on='2026-09-11')
