import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('deterministic-k-server-exact-competitive-ratio',
 id='TCS-6575', title='The deterministic k-server conjecture',
 area='Optimization and numerics', criterion='tightness', question_type='yes_no',
 formal='For every integer k≥1, every metric space (M,d) with at least k+1 points, and every initial placement C_0 of k servers, does there exist a deterministic online serving rule A and a finite constant β≥0 such that cost_A(σ;C_0)≤k·OPT(σ;C_0)+β for every finite request sequence σ∈M*? The rule and β may depend on M,d,k,C_0, but neither may depend on future requests or on the length of the request sequence.',
 definitions='The metric is symmetric, has finite real distances, is zero exactly on equal points, and satisfies the triangle inequality; the space may be finite or infinite and is known to the online rule. There are exactly k interchangeable, unweighted servers, whose current positions form a multiset. A request r_t must be served before r_{t+1} is revealed. If a server is already at r_t, no movement is needed; otherwise the rule chooses one of the k servers and moves it to r_t, paying the metric distance. Restriction to these lazy moves loses no competitive power. A deterministic online rule is a function of the known metric, initial placement and revealed request prefix, with arbitrary memory and no access to future requests; this card imposes no running-time bound. OPT is the minimum total movement cost of an offline rule serving the same finite sequence from C_0 with the same k servers and advance knowledge of the sequence. The additive β must be fixed before requests arrive and cannot grow with the number or cost of requests. Randomization, advice about future requests, and extra servers are not supplied.',
 answer_criterion='Prove the stated exact k-competitive guarantee on every metric space, using any deterministic online rule, or refute it by showing that some k, metric and initial placement admit no such rule with any finite additive constant. Proving that the work-function algorithm or a particular potential-function family fails is insufficient for a negative answer about all algorithms. A (k+ε)-competitive guarantee for every ε>0 does not by itself prove attainment of ratio k.',
 context=[
  paragraph('The problem isolates the price of making placement decisions without seeing future demand. Servers can represent cache slots, mobile resources or copies of data; a movement pays for changing which demand locations are covered. On a uniform metric, where every distinct pair has distance one, serving a request is precisely the paging problem. The online rule and the offline optimum have the same number of servers. Their difference is information about the future, not available capacity.','origin'),
  paragraph('The proposed factor k is a sharp target, already forced by paging lower bounds. The classical work of Manasse, McGeoch and Sleator establishes the lower-bound framework and settles the two-server case on general metrics. An additive constant is included so that a fixed initial placement does not distort asymptotic performance. Allowing that constant to depend on the request sequence would make the definition vacuous, which is why its quantifiers are explicit.','origin'),
  paragraph('Koutsoupias and Papadimitriou prove that the work-function algorithm is (2k−1)-competitive on every metric space. Its work function records the minimum offline cost of serving the already revealed prefix and ending in each possible server configuration. The algorithm uses these values to weigh movement against how well a configuration fits the past. This provides a single general strategy and leaves a factor approaching two between the known guarantee and the conjectured optimum.','wfa'),
  paragraph('It is widely conjectured that the same algorithm is actually k-competitive. Proving that stronger statement would settle this card, but the card permits a completely different algorithm. Similarly, failure of one proposed potential function only identifies a gap in that proof method. A potential proof typically compares changes in a quantity assigned to the current work function with the online and offline costs, so that the inequalities telescope over an arbitrarily long request sequence.','circle'),
  paragraph('Several geometric settings attain the target. Chrobak and Larmore give k-competitive algorithms on tree metrics, covering line-like settings as well. Trees have unique connecting paths, which support movement rules unavailable in arbitrary metrics. This is substantial positive evidence, but arbitrary metric spaces can contain cycles and distance patterns that do not admit the same analysis.','trees'),
  paragraph('Huang and Zhang prove that the work-function algorithm is 3-competitive on a circle, with distance measured along the shorter circular arc. Their result first appeared in a 2022 preprint and was published in Theoretical Computer Science in 2024. They also give computer-assisted evidence excluding their defined canonical family of potential functions for the general three-server case. The geometric theorem and the limitation of that proof family are different conclusions.','circle'),
  paragraph('Bubeck, Coester and Rabani’s STOC 2023 theorem disproves the randomized O(log k) conjecture by constructing metrics with randomized competitive ratio Ω(log²k). It does not refute the deterministic target k: these are different claimed rates, and log²k is asymptotically smaller than k. The deterministic lower bound and the (2k−1) upper bound remain the relevant endpoints here.','randomized'),
  paragraph('Brilliantov, Bamas and Abbé’s April 2026 benchmark studies automated searches for potentials, particularly for four servers on a circle. A violated checked inequality refutes a candidate under the chosen formulation, while passing the finite checks is not a proof for every metric configuration and request sequence. Their experiments leave the open case unresolved. This offers concrete research tooling without changing the status of the conjecture.','benchmark')],
 why='A central problem in competitive analysis that asks whether the number of available servers exactly captures the worst-case price of future uncertainty. Its techniques and limitations inform caching, online movement and broader metric optimization problems.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A foundational conjecture about online decision-making, with an optimal lower bound, one broadly applicable candidate algorithm, and a persistent gap on general metrics despite many resolved special cases.'),
 progress=[
  step('1990','Manasse, McGeoch and Sleator formulate the server framework, give the deterministic lower bound k, and resolve the two-server case on general metrics.','origin'),
  step('1991','Chrobak and Larmore attain deterministic competitive ratio k on tree metrics.','trees'),
  step('1994–1995','Koutsoupias and Papadimitriou prove the general (2k−1) guarantee for the work-function algorithm; STOC 1994 is followed by the JACM 1995 paper.','wfa'),
  step('2022–2024','Huang and Zhang settle work-function 3-competitiveness on circles. The May 2022 preprint appears in TCS on 12 December 2024.','circle'),
  step('2023-06-02','Bubeck, Coester and Rabani publish the Ω(log²k) randomized lower bound, disproving the randomized O(log k) conjecture without refuting deterministic k-competitiveness.','randomized'),
  step('2026-04-08','Brilliantov, Bamas and Abbé release a potential-discovery benchmark. The four-server circle experiments and finite inequality checks do not resolve the conjecture.','benchmark')],
 references=[
  ref('origin','Competitive Algorithms for Server Problems','Mark S. Manasse; Lyle A. McGeoch; Daniel D. Sleator',1990,'https://www.cs.cmu.edu/~sleator/papers/server-problems.pdf','Journal of Algorithms 11:208–230; §2 laziness reduction, Theorem 6 and Corollary 7 lower bounds, §8 open problem'),
  ref('wfa','On the k-server conjecture','Elias Koutsoupias; Christos H. Papadimitriou',1995,'https://cgi.di.uoa.gr/~elias/papers/paper-kp95.html','Journal of the ACM 42(5):971–983; author page links manuscript; STOC 1994 precursor; general (2k−1) bound'),
  ref('trees','An Optimal On-Line Algorithm for K Servers on Trees','Marek Chrobak; Lawrence L. Larmore',1991,'https://epubs.siam.org/doi/10.1137/0220008','SIAM Journal on Computing 20(1):144–148; tree-metric competitive ratio k'),
  ref('circle','Deterministic 3-server on a circle and the limitation of canonical potentials','Zhiyi Huang; Hanwen Zhang',2024,'https://www.sciencedirect.com/science/article/abs/pii/S0304397524004614','Theoretical Computer Science 1020:114844; DOI 10.1016/j.tcs.2024.114844; preprint arXiv:2205.08103v1, 17 May 2022; §§3–4 circle theorem and canonical-family limitation'),
  ref('randomized','The Randomized k-Server Conjecture Is False!','Sébastien Bubeck; Christian Coester; Yuval Rabani',2023,'https://arxiv.org/abs/2211.05753','STOC 2023, 581–594; DOI 10.1145/3564246.3585132; preprint v2, 6 July 2023; randomized Ω(log²k) on certain (k+1)-point metrics'),
  ref('benchmark','k-server-bench: Automating Potential Discovery for the k-Server Conjecture','Kirill Brilliantov; Etienne Bamas; Emmanuel Abbé',2026,'https://arxiv.org/abs/2604.07240','Preprint v1, 8 April 2026; §1 general status, §4 limits of finite evaluation, Appendix B work-function background')],
 status='source_open', status_note='Checked through 10 September 2026. The April 2026 primary source retains the deterministic conjecture and the general (2k−1) upper bound. The 2023 randomized disproof concerns O(log k), not the deterministic factor k. This card fixes all finite request sequences, identical initial placements, exactly k servers and an additive constant independent of requests; it asks for any deterministic online rule, not specifically WFA.', formulation_reviewed_on='2026-09-10')
