import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from authoring import finish, ref, step, paragraph

finish('decidability-word-equations-linear-length-constraints',
 id='TCS-6562', title='Are word equations with linear length constraints decidable?',
 area='Automata and formal languages', criterion='decision', question_type='yes_no',
 formal='Is there a Turing machine that halts on every finite input consisting of a system of word equations U_i=V_i and a system of integer linear equalities and inequalities on the variable lengths, and answers YES exactly when a simultaneous solution exists in the free monoid Σ*? The alphabet, equations, variables, and arithmetic coefficients are part of the input, with the conventions below.',
 definitions='Σ is a finite nonempty alphabet of constant symbols and X={X_1,…,X_k} is a disjoint finite set of variables. Each U_i,V_i is an explicitly written finite word over Σ∪X; repeated occurrences of a variable must receive the same substitution. A solution assigns a finite word σ(X_j)∈Σ* to each variable and extends by concatenation while fixing every letter of Σ. The empty word is allowed. Every substituted equality σ(U_i)=σ(V_i) must hold as a literal equality of words. The additional constraints are a finite conjunction of atoms sum_j a_j|σ(X_j)|≤b or sum_j a_j|σ(X_j)|=b, where all coefficients and constants are signed binary integers. Length is the number of alphabet symbols. There is no product of two variable lengths, letter-frequency counter, regular-expression predicate, string-to-integer conversion, or universal quantifier. The requested decider need not run in polynomial, elementary, or any specified computable time bound, but must terminate on satisfiable and unsatisfiable inputs alike. Nonempty-substitution requirements can be imposed using |σ(X_j)|≥1.',
 answer_criterion='Prove decidability by a correct algorithm terminating on every instance, or prove undecidability for this exact input language. Enumerating satisfying substitutions is only a semidecision procedure. A hardness lower bound for any decidable complexity class does not prove undecidability. A procedure for a syntactically restricted fragment, bounded solution lengths, or a stronger theory with additional predicates does not by itself settle the problem.',
 context=[
  paragraph('The two ingredients are individually manageable: plain word equations are decidable by Makanin’s theorem, and integer linear arithmetic is decidable. Their combination is difficult because string equality constrains how letters align, while arithmetic constrains the lengths of pieces across those alignments. A decision procedure for either component does not automatically decide their interaction. Ciobanu’s survey identifies this specific combination as a major remaining question.','survey'),
  paragraph('Taking lengths gives useful necessary conditions, but can lose decisive information. For distinct letters a and b, the equation Xa=bX yields the harmless length identity |X|+1=1+|X|. Nevertheless, it has no finite-word solution. If X is nonempty its first letter must be b, and cancelling that b leaves the same equation for a shorter word; eventually one obtains the false equality a=b. This example shows why satisfying the induced linear equations alone cannot certify a word solution.'),
  paragraph('There is an elementary way to recognize every YES instance eventually: enumerate all tuples of finite words and test the equations and length constraints. If a solution exists, this search reaches it. For a NO instance, however, there is no prescribed point at which enumeration can stop. A computable bound on the size of some solution to every satisfiable input would therefore be sufficient for decidability. The existence of large witnesses by itself does not establish undecidability.'),
  paragraph('Several nearby theories have a different status. Constraints on the numbers of individual letters, or on the full vector of letter counts, can make word-equation satisfiability undecidable. Those predicates carry information beyond total length. Similarly, results with alternating quantifiers concern a stronger logical language. Importing either kind of undecidability theorem into this purely existential length-only question would change the problem.','survey'),
  paragraph('Day and Konefal prove decidability for quadratic word equations in at most two unknowns, using a connection with matrix-semigroup reachability. Quadratic means each unknown has at most two occurrences across the equation. The two-unknown restriction is essential to the result stated in their RP 2025 paper. Its abstract also explains that sets of possible solution-length vectors need not be semilinear, so representing every such set by ordinary Presburger arithmetic cannot simply be assumed.','two'),
  paragraph('Przybocki and Barrett’s IJCAR 2026 work analyzes when extended Nielsen transformations terminate. These transformations reason about prefixes of variable values while tracking partial length information. Their cut graph records dependencies between occurrences, giving a sufficient termination criterion and a partial converse. This advances a procedure used in string solvers, but neither guarantees termination for every input nor decides the unrestricted problem.','nielsen'),
  paragraph('Barros, Cadilhac, and Pérez’s July 2026 preprint claims NEXP-hardness for nonerasing satisfiability of positive Boolean combinations of word equations and Presburger length constraints, already over two letters. This strengthens the PP-hardness stated in its first version. Its NEXP-completeness theorem is for arithmetic with divisibility, not for unrestricted word equations with lengths. Positive Boolean formulas can be expanded into finitely many conjunctions for purposes of decidability, but that expansion need not be polynomial. The result therefore records a substantial complexity barrier without establishing a general decider or undecidability.','hard')],
 why='A fundamental boundary for reasoning about concatenation and numerical size simultaneously. It governs whether a complete terminating solver can exist for a basic fragment of string constraints used in verification, while connecting free-monoid equations, arithmetic and reachability.',
 importance=dict(score=97, method='editorial', assessed_on='2026-09-10', reason='A longstanding decidability question at the intersection of formal languages, number-theoretic constraints and automated verification; even unrestricted termination is unknown, before asking for efficient algorithms.'),
 progress=[
  step('1977 onward','Makanin establishes decidability of plain word equations. Adding linear length constraints remains outside that theorem; the distinction is reviewed by Ciobanu.','survey'),
  step('2024','Ciobanu’s survey explicitly separates the open length-constraint problem from undecidable letter-count and Parikh-image extensions.','survey'),
  step('2025-11-05','Day and Konefal’s RP 2025 paper appears online, giving decidability for quadratic equations with at most two unknowns and semilinear constraints on solution lengths. The proceedings carry a 2026 copyright year.','two'),
  step('2026-07-19','Version 3 of Barros, Cadilhac, and Pérez claims NEXP-hardness for the nonerasing positive-Boolean formulation. Only its arithmetic-with-divisibility problem is asserted NEXP-complete.','hard'),
  step('2026-07-24','Przybocki and Barrett’s IJCAR 2026 paper gives partial termination criteria for extended Nielsen transformations and explicitly retains general decidability as open.','nielsen')],
 references=[
  ref('survey','Word equations, constraints, and formal languages','Laura Ciobanu',2024,'https://arxiv.org/abs/2406.02160','DLT 2024 survey; §2, Example 1 and following discussion distinguish WordEqn+LEN from letter-count and Parikh constraints'),
  ref('two','Word Equations with Length Constraints via Weak Arithmetics and Matrix Reachability Problems','Joel D. Day; Matthew Konefal',2025,'https://link.springer.com/chapter/10.1007/978-3-032-09524-4_4','RP 2025, LNCS 16230:51–67; first online 5 November 2025, proceedings copyright 2026; quadratic equations with at most two unknowns'),
  ref('nielsen','The Termination of Nielsen Transformations Applied to Word Equations with Length Constraints','Benjamin Przybocki; Clark Barrett',2026,'https://link.springer.com/chapter/10.1007/978-3-032-32592-1_14','IJCAR 2026, Part II, 234–250; §1 and Theorems 1–2; full preprint arXiv:2501.11789, where theorem numbers are 6.1 and 7.3'),
  ref('hard','NEXP-Completeness and Exponential Coefficient Growth for Existential Presburger Arithmetic with Divisibility','Ignacio Barros; Michaël Cadilhac; Guillermo A. Pérez',2026,'https://arxiv.org/abs/2606.14167v3','Preprint v3, 19 July 2026; Theorem 1 is EPAD NEXP-completeness; Corollary 2 is NEXP-hardness of the nonerasing positive-Boolean word-equation formulation')],
 status='source_open', status_note='Checked through 10 September 2026. The IJCAR 2026 primary source explicitly leaves general word-equation satisfiability with length constraints open. The two-variable quadratic theorem is a restricted case, and the July NEXP-hardness claim is a lower bound rather than a decidability result. This card fixes existential satisfiability with concatenation and integer linear length constraints only.', formulation_reviewed_on='2026-09-10')
