"""Specify the source's directed-grid bandit-regret problem."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-5252';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Optimal bandit regret for paths in a directed grid',status='source_open',criterion='resources',question_type='asymptotic_complexity',
 formal=r'''Determine the minimax expected regret \(R(n,T)\) for paths from \((1,1)\) to \((n,n)\) in the directed square grid, with only total path loss observed, up to universal multiplicative constants, jointly for all integers \(n\ge2\) and \(T\ge1\). Specifically, supply an explicit asymptotic rate \(F(n,T)>0\) and constants \(0<c\le C<\infty\), independent of both parameters, such that
\[
cF(n,T)\le R(n,T)\le CF(n,T)
\]
throughout this domain. Edge losses lie in \([0,1]\), are fixed in advance, and the comparator is the best single path in hindsight. The precise minimax quantity is defined below.''',
 definitions=r'''The graph has vertices \([n]\times[n]\), where \([n]=\{1,\ldots,n\}\). Its edges are \((i,j)\to(i+1,j)\) for \(i<n\) and \((i,j)\to(i,j+1)\) for \(j<n\). Let \(E_n\) be this set of \(2n(n-1)\) edges and \(\mathcal P_n\) the finite nonempty set of directed paths from \((1,1)\) to \((n,n)\). Every such path has exactly \(k=2(n-1)\) edges. There are no backward edges, obstacles, unknown edges or choices of endpoints.

Before play an adversary fixes a deterministic sequence \(\ell=(\ell_1,\ldots,\ell_T)\in([0,1]^{E_n})^T\), hidden from the learner. No independence between edge losses or between rounds is assumed. In round \(t\), the learner chooses a path \(P_t\in\mathcal P_n\), incurs loss \(L_t=\sum_{e\in P_t}\ell_t(e)\), and observes precisely this real number. It does not observe the separate losses of the traversed edges, any losses outside its path, or losses of other paths. Each round is one complete path choice followed by one aggregate observation; there is no feedback at intermediate vertices. The sum is not divided by path length.

The learner initially knows \(n,T\) and the entire grid. An admissible randomized strategy specifies, for each round, a Borel-measurable map from the finite history \((P_1,L_1,\ldots,P_{t-1},L_{t-1})\) to a probability distribution on \(\mathcal P_n\). Histories carry the product of the discrete path spaces and the usual Borel structure on real losses. This is an information-theoretic model with exact observations and unrestricted computation or memory. Strategies may depend on \(n,T\), but cannot access the hidden sequence or future losses. Their private randomness is independent of the adversary's fixed sequence.

For a strategy \(A\), define
\[
\operatorname{Reg}(A,\ell)=\mathbb E_A\!\left[\sum_{t=1}^T\sum_{e\in P_t}\ell_t(e)\right]
-\min_{P\in\mathcal P_n}\sum_{t=1}^T\sum_{e\in P}\ell_t(e),\qquad
R(n,T)=\inf_A\sup_{\ell\in([0,1]^{E_n})^T}\operatorname{Reg}(A,\ell).
\]
Expectation is over the learner alone. The comparator knows the full sequence but uses the same path in every round. The infimum allows strategies specialized to the known parameter pair and need not be attained. The adversary is oblivious: it cannot change its sequence after seeing the learner's sampled paths. A distribution over fixed sequences may be used to prove a lower bound, but does not give the adversary additional feedback.

The requested rate must describe the full joint dependence, including small horizons; a large-\(T\) bound with an unstated threshold depending on \(n\) is insufficient. Logarithmic factors are part of the rate and cannot be hidden in the constants. The answer must give parameter bounds that actually determine the asymptotic order, rather than rename the defining optimization over strategies and loss sequences. An efficient algorithm is welcome but is not an extra requirement. The ordinary absolute numerical tolerance for a numerical value is inapplicable to this constant-factor asymptotic target.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof of matching upper and lower bounds for an explicit rate on the full parameter domain. The upper bound must be witnessed by admissible aggregate-feedback strategies, and the lower bound must apply to every such strategy. Bounds for arbitrary graphs in the worst case, separate edge feedback, full information, or independent stochastic losses do not by themselves answer the grid question.',
 importance=dict(score=77,method='editorial',reason='A concrete structured network tests whether general combinatorial-bandit bounds reflect actual path geometry. Resolving its joint minimax rate would clarify the statistical price of aggregate routing feedback beyond worst-case action-set bounds.'),
 why='Paths overlap heavily in a grid, so treating them as unrelated arms discards useful information while observing only a total loss hides the responsible edges. This elementary network isolates how action geometry affects the limits of online exploration.',
 source_formulation=dict(text='The source asks broadly which features of an action set determine regret and singles out a directed square grid with opposite-corner endpoints as an unresolved example. This card selects that example and specifies a uniform constant-factor minimax rate. The selection is an announced editorial default after an unanswered optional scope question.',caption='Cohen–Hazan–Koren 2017, §5, PDF p.12; feedback model in §1.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Tight Bounds for Bandit Combinatorial Optimization','Alon Cohen; Tamir Hazan; Tomer Koren',2017,'https://proceedings.mlr.press/v65/cohen17a.html','§1 model and §5, PDF p.12, grid example'),ref('later','Improved Regret Bounds for Bandit Combinatorial Optimization','Shinji Ito; Daisuke Hatano; Hanna Sumita; Kei Takemura; Takuro Fukunaga; Naonori Kakimura; Ken-ichi Kawarabayashi',2019,'https://papers.neurips.cc/paper/9373-improved-regret-bounds-for-bandit-combinatorial-optimization.pdf','§§1–2 and Theorem 1, PDF pp.1–4')],
 context_blocks=[block('The 2017 lower bounds concern difficult action systems and shortest-path networks. They do not assert that every graph, including this particular grid, has the same minimax rate.'),block('The 2019 work sharpens lower bounds and addresses the separate full-permutation ranking question from the 2017 conclusion. Its reduction to shortest paths supplies hard networks, not a matching characterization of the directed square grid.','later'),block('The selected model allows correlated adversarial edge losses and reveals only their sum along the chosen path. Semi-bandit feedback, which reveals each selected edge loss, is a different information model.')],
 progress=[progress('2017','The source explicitly identifies opposite-corner paths in a directed square grid as an unresolved structured example.'),progress('2019','Sharper general lower bounds and a resolution of the neighboring full-permutation question do not establish the grid-specific rate.','later')],
),['Selected the explicit grid example and a joint constant-factor minimax target as an announced editorial default.','Defined directed edges, aggregate loss scale, measurable strategies, oblivious sequences, comparator and quantifier order.','Individually assessed importance and distinguished the known ranking result from grid paths.'],['Read the original §1 model and complete §5 question passage.','Read the 2019 abstract, §§1–2, Theorem 1 and its shortest-path reduction discussion.','Bounded later primary-source searches through 18 September 2026 found no matching grid-specific rate; unrelated discretized contextual-bandit grids were excluded.'],'Source-open for the directed-grid example in Cohen–Hazan–Koren (2017). The checked 2019 result resolves the neighboring full-permutation target but does not determine this grid rate. Bounded later searches through 18 September 2026 found no verified resolution; this is not an exhaustive certification of openness. The precise branch is an editorial default, not a received user confirmation.',summary=['Each round the learner chooses a path between opposite corners of a directed square grid.','It observes the sum of the losses on that path without seeing individual edge losses.','Performance is compared with the best fixed path after all rounds are known.','The question asks for the optimal worst-case expected regret in both grid size and horizon, up to constant factors.','General hard-network bounds and newer results on ranking do not yet identify the selected grid rate.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
