"""Complete the deterministic logarithmic-round LOCAL MIS question."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,block,progress
from review_queue import read_claims
identifier='TCS-6506';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text())
complete(identifier,dict(
 title='Logarithmic-round deterministic maximal independent set',status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Do there exist one uniform deterministic LOCAL algorithm \(A\) and an absolute constant \(C>0\) such that on every finite nonempty simple undirected graph with \(n\) vertices, and every valid identifier assignment and port numbering, all vertices output the membership bits of a maximal independent set within
\[C\log_2(n+2)\]
synchronous communication rounds? Vertices may know \(n\) and the maximum degree. No random bits are available, and the constant is independent of graph degree.''',
 definitions=r'''The network is the input graph \(G=(V,E)\), which can be disconnected and can have isolated vertices. Its maximum degree \(\Delta\) may be any integer from zero to \(n-1\). A set \(I\subseteq V\) is independent if no edge has both endpoints in \(I\). It is maximal if every vertex outside \(I\) has a neighbor in \(I\). This is inclusion maximality, not maximum cardinality. Each vertex outputs exactly one bit indicating its own membership, and the joint labeling must satisfy both conditions on every instance.

Identifiers are arbitrary pairwise distinct integers from \(\{1,\ldots,n^2\}\). At a vertex of degree \(d\), its incident edges receive distinct local ports \(1,\ldots,d\); port numbers at the two endpoints need not agree. Initially a vertex knows its own identifier, its degree and ports, the identifiers of its neighbors, the exact \(n\) and the exact \(\Delta\). Supplying neighbor identifiers initially saves at most the one round required to exchange them.

In each LOCAL round every vertex may perform an arbitrary finite deterministic local computation and send a separate finite binary message to each neighbor. The message lengths and local working memory are unrestricted. Messages arrive before the next round. Communication is possible only along graph edges; there is no centralized graph preprocessing, shared memory, nonuniform advice or external oracle. Every local computation terminates. All vertices execute one finite program independent of the graph size, with the listed information as input.

A halted vertex has fixed its output and may subsequently send dummy messages. The round count is elapsed synchronous time until all vertices have output, not the sum of their work or a count of active rounds. The displayed bound includes all graphs, identifiers, ports and degrees simultaneously. The use of \(\log_2(n+2)\) handles the one-vertex case; after changing the constant it is equivalent to an eventual \(O(\log n)\) guarantee on \(n\ge2\).

For a correct algorithm \(A\), let \(T_A(n)\) be the largest elapsed round count on the allowed instances of exactly \(n\) vertices. The question is \(\exists A\,\exists C>0\,\forall n\ge1:T_A(n)\le C\log_2(n+2)\). Its negation must exclude every correct uniform deterministic program, not merely algorithms using a particular decomposition or rounding method.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked construction and analysis of a correct uniform deterministic algorithm with the displayed bound, or a proof of the full negation. A polylogarithmic bound with exponent greater than one, a randomized algorithm, a degree-dependent constant, or a result restricted to a special graph family is insufficient.''',
 source_formulation=dict(text='The source places deterministic MIS between a nearly logarithmic lower bound and a roughly log-to-the-five-thirds upper bound. This card retains the saved exact logarithmic upper-bound milestone, rather than the already attained polylogarithmic milestone.',citation='upper',caption='Ghaffari–Grunau 2024, §1.4 and Theorem 1.3.',format='editorial_paraphrase'),
 references=old['references'],
 progress=[progress('2019',r'The primary lower-bound result gives \(\Omega(\min\{\Delta,\log n/\log\log n\})\) deterministic rounds. It does not rule out the target logarithmic bound.','lower'),progress('2020','Deterministic network decomposition yields polylogarithmic deterministic MIS, settling the older broader milestone. This history is also described in the checked 2024 §1.4.','decomposition'),progress('2024-10-25',r'Theorem 1.3 gives \(\widetilde O((\log n)^{5/3})\) deterministic LOCAL rounds, with suppressed factors polynomial in \(\log\log n\).','upper'),progress('2026',r'The SODA coloring reduction cites the same MIS benchmark. Its improved \(\Delta\)-coloring result does not provide logarithmic deterministic MIS.','current')],
 context_blocks=[block('Identifiers break symmetry but may be adversarially arranged. An algorithm must coordinate compatible choices without access to fresh random choices.','upper'),block('Network decomposition settled the existence of polylogarithmic deterministic algorithms. Its standard use incurs an extra cost which the 2024 improvement partly avoids.','upper'),block('Faster deterministic MIS can improve other local graph tasks through reductions. The later coloring result illustrates that consequence while leaving this upper-bound milestone intact.','current')],
),['Preserved the deterministic logarithmic target and individual importance score of 87.','Specified the full LOCAL model, identifier range, initial knowledge, maximality and elapsed time.','Made the constant independent of graph degree and gave the literal existential and negative criteria.','Separated the solved polylogarithmic milestone and later coloring reductions.'],['Read Ghaffari–Grunau 2024 model introduction, §1.4 and Theorem 1.3 in the primary PDF.','Checked the Balliu et al. primary abstract and 2021 revision metadata for the deterministic lower-bound corollary.','Checked the later Bourreau–Brandt–Nolin primary abstract for the MIS benchmark and coloring reduction; bounded later searches through 18 September 2026 found no verified logarithmic MIS algorithm.'],'The selected logarithmic deterministic target remains unanswered in the checked 2024 MIS theorem and later coloring paper. Polylogarithmic deterministic MIS is already known. This bounded source and later-work review through 18 September 2026 is not an exhaustive certification or independent audit of the full proofs.',summary=['The vertices of an arbitrary graph must deterministically choose a maximal independent set.','They can exchange unlimited finite messages along edges, but their identifiers may be adversarial.','The target is a number of rounds bounded by one constant times the logarithm of the graph size.','The guarantee must hold uniformly over all degrees and identifier assignments.','Known polylogarithmic algorithms and nearly logarithmic lower bounds leave this sharper upper-bound milestone open in the checked sources.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
