"""Review input-only perfect versus statistical interactive zero knowledge."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete
from review_queue import read_claims
identifier='TCS-7225';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text())
refs=old['references'];next(r for r in refs if r['id']=='separation').update(pdf_url='https://eccc.weizmann.ac.il/report/2016/140/revision/3/download/',locator='ECCC revision 3, 8 May 2017: §1.2, Theorem 1.2, §2.1 Definition 2.1 and §5 Definition 5.1 with bounded simulator failure; journal version 2020.')
complete(identifier,dict(
 title='PZK versus SZK',status='source_open',criterion='models',question_type='yes_no',
 formal=r'''Is \(\mathrm{PZK}=\mathrm{SZK}\) for classical single-prover interactive proofs of promise problems in the precise input-only simulation model below? Both classes use uniform polynomial-time verifiers and simulators, negligible completeness and soundness errors, and zero knowledge against every uniform probabilistic polynomial-time verifier. Perfect simulation may output a failure symbol with probability at most \(1/2\); conditioned on success its distribution must be exactly correct. Statistical simulation permits negligible total variation distance.''',
 definitions=r'''A promise problem is a pair \(L=(Y,N)\) of disjoint subsets of \(\{0,1\}^*\). An interactive proof has a single computationally unbounded honest prover \(P\) and a uniform probabilistic Turing verifier \(V\), both receiving the common input \(x\). They exchange binary messages over an ordinary interactive channel. The verifier uses at most polynomially many random bits, computational steps and communicated bits, with a fixed polynomial in \(|x|\); its bound holds on every random tape and against every prover. A message or interaction exceeding the verifier's prescribed length or turn limit can be rejected. The prover has arbitrary computation and private randomness, but sees only the input and communicated history, not the verifier's private random tape.

A function \(\varepsilon:\mathbb N\to\mathbb R_{\ge0}\) is negligible if for every real \(d>0\), some integer \(n_d\) has \(\varepsilon(n)\le n^{-d}\) for all \(n\ge n_d\). There must be one negligible error bound with honest acceptance probability at least \(1-\varepsilon(|x|)\) for every \(x\in Y\), and acceptance probability at most \(\varepsilon(|x|)\) for every \(x\in N\) and every possibly unbounded cheating prover strategy. Soundness thus concerns proofs, not arguments secure only against computationally bounded provers. No correctness or simulation condition is imposed outside the promise. Completeness is not required to be perfect.

A malicious verifier \(V^*\) is any fixed uniform probabilistic polynomial-time interactive Turing machine, with polynomial worst-case bounds on its computation, random bits and communication on every interaction. The honest prover has a specified behavior on every received history, including malformed messages or early halting. The view \(\operatorname{View}_{P,V^*}(x)\) is the resulting finite record of \(x\), the verifier's random bits and all exchanged messages with their order and delimiters. Its output and final state are determined by this record and its program. Random tapes can be padded to the verifier's fixed polynomial bound. This fixes one finite binary encoding of views; the special simulator failure symbol \(\bot\) is not a view.

The promise problem belongs to SZK if it has such a proof \((P,V)\) and, for every \(V^*\), a uniform probabilistic polynomial-time simulator \(S^*\) and a negligible function \(\mu_{V^*}\) such that for every \(x\in Y\),
\[
\operatorname{TV}\bigl(S^*(x),\operatorname{View}_{P,V^*}(x)\bigr)\le\mu_{V^*}(|x|).
\]
For distributions on finite binary records, \(\operatorname{TV}(D,E)=\tfrac12\sum_z|\Pr[D=z]-\Pr[E=z]|\); the sum may include records given zero probability by one distribution. Any simulator output not encoding a real view counts in that distance.

PZK uses the same requirements on the proof but replaces the last simulation condition by
\[
\Pr[S^*(x)=\bot]\le\tfrac12,\qquad
\mathcal L(S^*(x)\mid S^*(x)\ne\bot)=\mathcal L(\operatorname{View}_{P,V^*}(x))
\]
for every \(x\in Y\). Here \(\mathcal L\) denotes the probability distribution, and equality requires equality of each record's probability. Nonfailure has positive probability, so conditioning is defined.

Every simulator has a strict polynomial bound on every input and random tape, rather than an expected-time bound. Its polynomial and description may depend on the fixed verifier \(V^*\), but not on \(x\). It receives \(x\) alone, with no witness, prover interaction, nonuniform advice or separate auxiliary input. It may use the fixed verifier's description internally; no black-box simulation requirement is imposed. There is no common random string, oracle, computational assumption or multiprover resource. This retains the saved input-only convention; an auxiliary-input or expected-time variant is not substituted.

Class equality quantifies over all promise problems and permits the perfect proof system to differ completely from the statistical one. PZK is contained in SZK under these conventions: repeat a perfect simulator independently polynomially many times, retain the first nonfailure output and use any fixed record if all runs fail. The latter event can be made negligible while preserving a strict polynomial bound.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof that every promise problem in the stated SZK class also belongs to the stated PZK class, or exhibit a promise problem in SZK and prove that it admits no PZK proof in this model. The positive direction need not be a uniform compiler from protocol descriptions. An oracle separation, a failure of one proposed compiler, a perfect-zero-knowledge PCP or multiprover protocol, or an honest-verifier-only result without a matching transformation does not resolve the unrelativized equality.''',
 source_formulation=dict(text='The sources ask whether statistical and perfect zero knowledge have the same expressive power. The saved convention follows the corrected bounded-failure perfect-simulation definition and specializes to uniform input-only simulation for ordinary single-prover interactive proofs.',citation='separation',caption='Bouland et al., revision 3, §1.2, §2.1 and §5 Definition 5.1; Goldreich provides the historical class-comparison question.',format='editorial_paraphrase'),
 references=refs,
 context_blocks=old['context_blocks'],progress=old['progress'],
),['Preserved the saved uniform input-only, strict-polynomial-time, bounded-failure simulation conventions.','Repaired the malformed negligibility expression and quantified the error uniformly over YES inputs.','Defined the verifier view, total variation distance, promise conventions and unbounded-prover soundness.','Added the Lean acceptance requirement and retained individual importance 89; separated oracle, PCP and multiprover results.'],['Read the primary 2017 revision §1.2 and Theorem 1.2, §2.1 Definition 2.1 and §5 Definition 5.1, including the distinction from super-perfect simulation.','Read the 2024 PCP paper introduction around the explicit PZK versus SZK open statement and its different proof-access models.','Checked the author textbook page and revision metadata, and made bounded later-work searches through 18 September 2026; no new full textbook or oracle-proof audit is claimed.'],'The checked 2024 primary paper explicitly retains the ordinary interactive-proof equality as unknown. The corrected 2017/2020 definition permits bounded simulator failure, and the known separation is relativized. Bounded later-work checks through 18 September 2026 found no verified unrelativized resolution, without claiming exhaustive coverage.',summary=['Zero knowledge asks whether an efficient simulator can reproduce what any efficient verifier sees.','Statistical simulation allows negligible total variation error, while perfect simulation requires exact agreement conditioned on not failing.','The question compares the classes of promise problems admitting these two kinds of ordinary interactive proofs.','All machines are uniform, simulators have strict polynomial runtime and receive only the common input.','Known oracle separations and perfect-zero-knowledge results in other proof models leave this class equality unresolved in the checked sources.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
