"""Review the saved square-root-logarithmic metric-labeling approximation target."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-7287';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text())
refs=old['references']+[ref('hardness','The Hardness of Metric Labeling','Julia Chuzhoy; Joseph (Seffi) Naor',2007,'https://doi.org/10.1137/06065430X','Journal abstract: conditional constant-factor and almost-square-root-logarithmic inapproximability; not a refutation of the selected square-root-logarithmic guarantee.')]
complete(identifier,dict(
 status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Do there exist absolute constants \(C,K\ge1\), an integer \(d\ge1\), and one uniform classical randomized algorithm such that on every metric-labeling instance of binary length \(L\) with \(k\ge1\) labels, every execution halts within \(K(L+1)^d\) bit steps and outputs a labeling \(f\) satisfying
\[
\Pr\!\left[\operatorname{cost}(f)\le C\sqrt{\log_2(k+2)}\,\operatorname{OPT}\right]\ge\tfrac23?
\]
The input graph, nonnegative rational edge weights and assignment costs, and full rational metric on the labels are arbitrary. The output is always a feasible labeling; \(\operatorname{OPT}\) is the least cost of any labeling.''',
 definitions=r'''An instance has a finite simple undirected graph \(G=(V,E)\), with \(V=[n]\) and \(n\ge0\), and label set \([k]=\{1,\ldots,k\}\), with \(k\ge1\). Every edge \(\{u,v\}\in E\) has a nonnegative rational weight \(w_{uv}\). For each vertex \(v\) and label \(i\) there is a nonnegative rational assignment cost \(c(v,i)\). A metric is supplied as the entire \(k\)-by-\(k\) matrix \(d\): its entries are finite nonnegative rationals, \(d(i,j)=d(j,i)\), \(d(i,j)=0\) if and only if \(i=j\), and \(d(i,j)\le d(i,\ell)+d(\ell,j)\) for all labels. There is no dimension, embedding, graph-structure or distance-ratio promise.

A feasible labeling is a function \(f:V\to[k]\), with cost
\[
\operatorname{cost}(f)=\sum_{v\in V}c(v,f(v))+
\sum_{\{u,v\}\in E}w_{uv}\,d(f(u),f(v)).
\]
Each undirected edge is counted once. Define \(\operatorname{OPT}=\min_{f:V\to[k]}\operatorname{cost}(f)\); this is a finite minimum over \(k^n\) possibilities. For the empty graph the cost and optimum are zero. More generally the multiplicative guarantee applies also when \(\operatorname{OPT}=0\), requiring zero output cost on the successful event. No infinite forbidden-assignment penalties or label capacities are part of the input.

Use an explicit binary encoding listing \(n,k\), the edges with endpoints and weights, all \(nk\) assignment costs, and the full metric matrix in a fixed order. Each rational is a binary nonnegative numerator over a binary positive denominator, with length delimiters; reduced form is optional. \(L\) is the total bit length, including all numbers and delimiters. Any malformed input may be rejected; the accuracy condition applies to valid metric instances. An output lists one label for each vertex.

The algorithm is one probabilistic Turing machine with independent fair random bits, no advice and no oracle. Its finite description, time exponent and constants are independent of \(n,k\), the graph and all numeric values. Every input and every random tape satisfy the time bound, including tapes on which the approximation fails. All preprocessing, arithmetic on rational encodings and output writing are charged. The probability is over the algorithm's coins separately for each fixed input. The constant \(C\) is chosen before the input and need not have a prescribed numerical value. The number of labels is part of the input, rather than a fixed parameter.

This is a claim about algorithms for the integer labeling objective, not a request that a particular linear-programming relaxation have that integrality gap. Algorithms can use any technique meeting the stated bit complexity.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof of the stated uniform existence claim or its logical negation. An affirmative solution must prove feasibility, the per-input probability guarantee and worst-case polynomial bit time. An approximation with a larger asymptotic factor, a result for a special label metric or graph family, or a bound only for one relaxation does not decide this proposition. A complexity-theoretic assumption must be explicit, and a conditional negative result establishes only its conditional claim.''',
 source_formulation=dict(text='The saved card chooses the square-root-logarithmic algorithmic milestone between general logarithmic approximation and the hardness landscape. The 2005 primary paper supplies the metric-labeling objective and logarithmic upper bound; this precise milestone is an editorial target, not a quoted theorem or conjecture of that paper.',citation='primary',caption='Chekuri et al. 2005, §1, §5 and Theorem 5.3; Chuzhoy–Naor 2007 for separate conditional hardness.',format='editorial_paraphrase'),
 references=refs,
 context_blocks=[block('Local assignment costs prefer particular labels, while edge penalties encourage neighboring objects to receive nearby labels. Arbitrary label metrics make the objective more general than uniform-label partitioning.','primary'),block('The known logarithmic algorithm provides an upper benchmark. Special metrics, such as a uniform metric or a line, allow stronger guarantees but do not settle the general target.','primary'),block('Conditional hardness motivates the square-root-logarithmic scale. It does not by itself refute an algorithm at the scale asked here, and an LP gap alone is not a lower bound against every algorithm.','hardness')],
 progress=[progress('2005',r'The primary paper gives an \(O(\log k)\) approximation for general metrics and stronger guarantees in specified special cases; Theorem 5.3 controls its relaxation.','primary'),progress('2007','The primary hardness paper excludes constant-factor approximation under P different from NP and gives a stronger conditional near-square-root-logarithmic lower bound. The precise hardness model and assumptions remain distinct from this randomized algorithmic existence claim.','hardness')],
),['Preserved the saved randomized square-root-logarithmic target and importance score of 85.','Defined the full metric, finite rational input encoding, objective and zero-optimum case.','Made universal constants, uniformity, feasible output and worst-case bit time explicit.','Repaired malformed math and distinguished the editorial milestone, conditional hardness and specific-relaxation gaps.'],['Read the 2005 primary §1 objective, §5 Theorem 5.3 and conclusions from the author PDF.','Read the 2007 primary publisher abstract for the actual hardness assumptions and parameter scope; no independent full reduction audit is claimed.','Bounded later-work searches through 18 September 2026 found special-metric, capacity and multi-label variants but no verified solution of this arbitrary-metric milestone.'],'The checked primary papers establish logarithmic upper bounds and distinct conditional hardness results. No solution of the selected randomized square-root-logarithmic arbitrary-metric milestone was verified in bounded checks through 18 September 2026. The exact milestone is editorial rather than a literal source conjecture, and the search is not exhaustive.',summary=['Metric labeling assigns one label to each graph vertex.','Its cost combines vertex assignment costs with distances between labels across weighted edges.','The selected target is a randomized polynomial-time approximation growing only as the square root of the logarithm of the number of labels.','The label metric and all rational costs are explicit and unrestricted, and zero optimum is included.','General logarithmic approximation and special-metric results leave this chosen milestone unanswered in the checked sources.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
