"""Specify the balanced NP mild-to-strong exponential amplification target."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-6703';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Optimal exponential hardness amplification for balanced NP languages',status='source_open',criterion='reductions',question_type='yes_no',
 formal=r'''Is \(H_{\mathrm{balanced}}\Rightarrow H_{\mathrm{strong}}\), where
\[
H_{\mathrm{balanced}}:\quad\exists L\in\mathrm{NP}\ \exists\alpha\in\mathbb Q\cap(0,1)\ \exists a,N\in\mathbb Z_{\ge1}:\quad
\bigl(\forall n\ge1:\Pr_{x\sim U_n}[x\in L]=1/2\bigr)
\ \land\quad
\bigl(\forall n\ge N\ \forall C\in\mathcal C(n,\lfloor2^{\alpha n}\rfloor):\Pr_{x\sim U_n}[C(x)\ne1_L(x)]\ge n^{-a}\bigr),
\]
and
\[
H_{\mathrm{strong}}:\quad\exists M\in\mathrm{NP}\ \exists\beta\in\mathbb Q\cap(0,1)\ \exists N'\ge1\ \forall n\ge N'\ \forall C\in\mathcal C(n,\lfloor2^{\beta n}\rfloor):\quad
\Pr_{x\sim U_n}[C(x)\ne1_M(x)]\ge\frac12-2^{-\beta n}?
\]
The distribution \(U_n\) is uniform on all \(n\)-bit strings, and \(\mathcal C(n,s)\) consists of deterministic Boolean circuits of size at most \(s\). No additional hypothesis is allowed.''',
 definitions=r'''For a language \(L\subseteq\{0,1\}^*\), its characteristic function \(1_L(x)\) is one on members and zero otherwise. The language is in \(\mathrm{NP}\) if a single deterministic polynomial-time Turing-machine verifier accepts exactly its members when supplied with a suitable polynomial-length binary certificate. The verifier and its polynomial bounds are fixed for all input lengths; there is no advice or oracle. The amplified language \(M\) must also have such a verifier, although it may use a different polynomial and certificate format.

Circuits have \(n\) labeled Boolean inputs, constants zero and one, fan-in-two AND and OR gates, fan-in-one NOT gates, unrestricted fan-out, and one output. They are finite and acyclic. Size counts operation gates, not the input vertices or the two available constants. A direct input or constant output is allowed. The circuit for one length need not be related to a circuit for another length; the quantifiers cover all nonuniform choices. The definition uses deterministic circuits and exact finite uniform input probabilities. It is not a statement about average running time, uniformly generated circuits, randomized verifiers or nondeterministic prediction circuits.

Balanced means that \(L\) accepts exactly \(2^{n-1}\) strings at every positive length \(n\). Its behavior on the empty string is irrelevant. This hypothesis applies only to the starting language. The conclusion imposes no exact balance requirement on \(M\), though its hardness against constant circuits forces its acceptance probability close to one half. Mild hardness in the premise allows only an inverse-polynomial fraction of errors, whereas the conclusion demands that every eligible circuit's success probability be at most \(1/2+2^{-\beta n}\).

The premise and conclusion hold at all sufficiently large lengths, with fixed thresholds independent of circuits. The constants \(\alpha,a,N\) are witnesses to the premise; the conclusion may choose another language and another positive exponent \(\beta\) depending on those witnesses. It is enough to use one \(\beta\) for the size exponent and the error advantage: if an argument yields two different positive constants, their minimum gives the displayed form after increasing the length threshold. A loss to an exponent \(n/\operatorname{polylog}(n)\), or \(n^\gamma\) for fixed \(\gamma<1\), does not meet the linear-in-\(n\) exponent required here.

This target is the existence implication between these two assertions, not a prescribed oracle construction. A proof may inspect verifiers, use nondeterminism to describe the new language, or employ any other valid method; no black-box or monotone-combiner restriction is imposed. It need not provide one effective map from every NP verifier to an amplified verifier. The output hardness is measured in the output language's own input length. This formulation asks for optimal exponential-scale parameters without independently imposing a syntactic input-length map between the two verifiers.

The logical negation is \(H_{\mathrm{balanced}}\land\neg H_{\mathrm{strong}}\). A barrier for a particular amplification technique or an oracle separation does not establish it. The problem begins with average-case hardness, unlike the worst-case-to-mild-average target of TCS-6702. In particular, ordinary worst-case NP hardness alone is not the stated premise.''',
 answer_criterion='Provide a complete mathematically correct Lean-checked proof of the implication or its full logical negation. An affirmative proof must retain membership in NP and exponential circuit hardness while making the prediction advantage exponentially small in the output input length. It may assume precisely the displayed balanced mild-hardness premise. A negative answer must establish that premise and exclude every strong-hardness language allowed by the conclusion, not merely one construction.',
 importance=dict(score=87,method='editorial',reason='Optimal amplification would strengthen a weak average-case NP assumption to nearly unpredictable membership bits without losing the exponential security scale. The remaining parameter gap is important for the boundary between nondeterministic computation and pseudorandomness.'),
 why='Combining independent hard bits by parity amplifies prediction hardness, but NP is not known to preserve membership under such a combination. The question asks whether amplification that stays inside NP can nevertheless attain a truly exponential advantage bound without weakening the exponential circuit-size scale.',
 source_formulation=dict(text='The monograph asks to improve the near-exponential parameters of NP hardness amplification to an exponent linear in the amplified input length. This card spells out the standard balanced starting-language assumption from the cited constructions and uses an all-sufficiently-large-length existence implication. That scope is an announced editorial default after an unanswered optional question.',caption='Vadhan 2012, §8.2.3 pp.298–299; Healy–Vadhan–Viola main theorem; Gopalan et al. Corollary 5.9.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Pseudorandomness','Salil P. Vadhan',2012,'https://people.seas.harvard.edu/~salil/pseudorandomness/pseudorandomness-published-Dec12.pdf','§8.2.3, Hardness Amplification in NP, pp.298–299'),ref('balanced','Using Nondeterminism to Amplify Hardness','Alexander Healy; Salil Vadhan; Emanuele Viola',2006,'https://people.seas.harvard.edu/~salil/research/HardAmpNP-sicomp.pdf','Author version of 29 July 2005, Definition 1.1 and Main Theorem, pp.2–3; SIAM J. Comput. 35(4), 903–931'),ref('improvement','Better Pseudorandom Generators from Milder Pseudorandom Restrictions','Parikshit Gopalan; Raghu Meka; Omer Reingold; Luca Trevisan; Salil Vadhan',2012,'https://arxiv.org/abs/1210.0049','Corollary 5.9 and preceding hardness-amplification discussion, p.23'),ref('later','Hardness Amplification Beyond Boolean Functions','Nobutaka Shimizu; Kenji Yasunaga',2026,'https://eccc.weizmann.ac.il/report/2026/038/','Abstract and §1, arithmetic XOR and counting applications')],
 context_blocks=[block('The standard XOR combination need not have an NP membership verifier, because rejecting one of its component instances is not generally accompanied by an NP certificate. The source therefore discusses monotone combinations and nondeterministic constructions.'),block('Healy–Vadhan–Viola explicitly start with a balanced mildly hard language. Their amplification achieves substantial hardness within NP but loses the optimal linear exponent at the exponential end.','balanced'),block('The improved construction approaches the target with exponents of the form n divided by a polylogarithmic factor. The monograph identifies removal of this loss as the remaining optimal-scale question.','improvement'),block('The checked 2026 arithmetic XOR result concerns finite-field sums and counting applications. It does not give the required Boolean membership language in NP with the displayed optimal parameters.','later')],
 progress=[progress('2006','The nondeterministic amplification construction explicitly uses balanced input functions and improves the achievable error within NP.','balanced'),progress('2012','Improved generators yield near-exponential amplification; the monograph records the optimal linear-exponent target as open.','improvement'),progress('2026-03-05','The checked finite-field amplification report extends XOR-style results to other outputs, without resolving the NP-preserving target.','later')],
),['Selected the balanced premise and full exponential conclusion as an announced editorial default.','Defined nonuniform circuit size, exact uniform error, verifier-based NP, balance and all-length quantifiers.','Formulated an unrestricted existence implication and distinguished it from a black-box transformation requirement.','Individually assessed importance and checked the near-exponential parameter gap.'],['Read Vadhan §8.2.3 pp.298–299 and Healy–Vadhan–Viola Definition 1.1 and Main Theorem.','Read Lu–Tsai–Wu 2007 Theorem 1 and Gopalan et al. Corollary 5.9; used the monograph to disambiguate evident sign/parameter typos in the latter surrounding hardness notation.','Checked the currently downloaded Viola draft §11.3.6 Theorem 11.53 and notes, and Shimizu–Yasunaga 2026 abstract and §1. Neither checked statement supplies the requested optimal exponent.'],'Source-open as the optimal exponential-scale NP amplification question in Vadhan (2012). The balanced premise comes from the checked original constructions; the explicit eventual-length existence formulation is an editorial selection. Bounded primary-source checks through 18 September 2026, including the 2026 draft exposition and arithmetic amplification report, found no verified resolution. This is not an exhaustive theorem-status certificate.',summary=['The premise supplies a balanced NP language that is mildly hard for exponentially large circuits on uniformly random inputs.','The target is another NP language whose membership bit can be predicted with only exponentially small advantage over chance.','The allowed circuit size must remain exponential in the amplified language’s own input length.','Known constructions achieve near-exponential parameters but do not provide the selected linear exponent.','The implication permits any proof method and does not require a black-box construction.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
