"""Archive the user-selected finite unrestricted-computation kernel-RL target."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0708';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Minimax regret for finite kernel reinforcement learning',status='resolved',criterion='resources',question_type='asymptotic_complexity',
 formal=r'''For all finite nonempty state and action sets \(S=[s]\), \(A=[a]\), positive integers \(H,T\), rational rewards \(r_h:S\times A\to[0,1]\), a rational positive-semidefinite matrix \(K\) indexed by \(S\times A\), and a rational norm bound \(u>0\), determine the minimax expected regret
\[
\mathcal R(K,u,r,H,T)=\inf_{\pi}\ \sup_{P\in\mathcal P(K,u),\ b\in S^T}
\mathbb E_{\pi,P,b}\!\left[\sum_{t=1}^T V^*_{P,1}(b_t)-\sum_{t=1}^T\sum_{h=1}^H r_h(s_{h,t},a_{h,t})\right]
\]
up to universal constant factors, uniformly over all such data for which \(\mathcal P(K,u)\ne\varnothing\). Supply a uniform finite algorithm producing a nonnegative rational value \(F\) and absolute constants \(0<c\le C\) such that
\[
cF\le\mathcal R(K,u,r,H,T)\le CF.
\]
There is no running-time or space bound. In particular, zero regret must be recognized exactly. The finite model and the class of learning policies are defined below.''',
 definitions=r'''The input lists all entries of \(K\), all rewards, and the integers and rational numbers in binary. There are no state or action oracles and no unknown rewards. The Gram matrix is symmetric and positive semidefinite, meaning \(v^{\mathsf T}Kv\ge0\) for every real vector \(v\). It may be singular. For a column vector \(p\) on \(S\times A\), membership in its finite reproducing-kernel Hilbert space with norm at most \(u\) means that there exists a real vector \(v\) with
\[
Kv=p,\qquad v^{\mathsf T}Kv\le u^2.
\]
Equivalently, \(p\) lies in the image of \(K\) and \(p^{\mathsf T}K^{\dagger}p\le u^2\), where \(K^{\dagger}\) is the Moore–Penrose inverse. This defines the norm convention without requiring a feature map or a choice of basis.

A transition model \(P\) consists of real numbers \(P_h(s'\mid s,a)\ge0\), summing to one over \(s'\) for every \((h,s,a)\), for \(1\le h<H\). For each \(h,s'\), the vector \((P_h(s'\mid s,a))_{(s,a)}\) must satisfy the displayed norm condition with the same \(K,u\). These models form \(\mathcal P(K,u)\). There is no transition after the final reward. When \(H=1\), the transition condition is empty. The learner knows the defining data but not \(P\). The same stage-dependent model is used in every episode, with conditionally independent draws from its transition distributions.

Before play the environment chooses \(P\) and a sequence \(b=(b_1,\ldots,b_T)\) of starting states, independently of the learner's random bits. Episode \(t\) begins at \(s_{1,t}=b_t\), which is revealed then. At stage \(h\), the learner observes the current state, selects an action, receives the known reward, and, if \(h<H\), observes the sampled next state. It receives no additional samples, transition entries or information about future starting states. A learning policy \(\pi\) may randomize and use the whole observed history of this and previous episodes. For fixed finite input parameters it is a collection of probability vectors on actions, one for each possible finite decision history. Arbitrary real action probabilities and unlimited computation are allowed in defining the minimax value.

The comparator knows \(P\). Its value is given by the finite-horizon Bellman recursion
\[
V^*_{P,H}(s)=\max_{a\in A}r_H(s,a),\qquad
V^*_{P,h}(s)=\max_{a\in A}\left(r_h(s,a)+\sum_{s'\in S}P_h(s'\mid s,a)V^*_{P,h+1}(s')\right).
\]
It is the best expected return from that state during one episode. The regret averages both transition randomness and the learner's randomization. The supremum ranges over the stated transitions and all fixed starting-state sequences. Thus the target depends on the entire supplied kernel and reward data, rather than only on state counts or an unspecified spectral summary.

One algorithm must halt on every valid finite input and output \(F\). Its cost may grow arbitrarily rapidly with any input parameter. The constants in the two-sided comparison must be independent of all data. A formula that merely repeats the minimax definition without a terminating evaluation procedure is insufficient. An exact real-algebraic determination followed by a certified rational multiplicative approximation is sufficient. This is the user's finite specialization; the broader infinite-domain kernel-learning question is not claimed resolved.''',
 answer_criterion='Give a complete mathematically correct Lean-checked construction of a uniform terminating algorithm and universal constants proving both displayed regret bounds on every valid input, or prove that no such construction exists. Exact computation of the real-algebraic minimax value, with exact zero testing and a certified rational constant-factor approximation, satisfies the target. No computational-efficiency guarantee or separate asymptotic kernel-class theorem is required.',
 why='The original research direction asks how nonlinear transition structure controls exploration. In the selected finite variant, retaining the entire rational model description and allowing unlimited computation makes the minimax value accessible to general real-algebraic decision procedures.',
 source_formulation=dict(text='Vakili asks for no-regret and order-optimal regret under pointwise RKHS bounds on transition probabilities. The user selected finite spaces, the full known rational Gram matrix and rewards, and no computation limit, then explicitly chose archival of that finite computational target on 18 September 2026. The fixed, unrevealed future starting-state sequence convention makes the finite interaction model explicit.',caption='COLT 2024 §§2–4; finite specialization and archival explicitly selected by the user.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Open Problem: Order Optimal Regret Bounds for Kernel-Based Reinforcement Learning','Sattar Vakili',2024,'https://proceedings.mlr.press/v247/vakili24a.html','§§2–4, episodic model, Assumption 1 and open problem'),ref('qe','Algorithms in Real Algebraic Geometry: A Survey','Saugata Basu',2014,'https://arxiv.org/abs/1409.1534','§2.1, Theorem 2.1 and effective quantifier elimination')],
 context_blocks=[block('The source permits much broader spaces and asks for meaningful regret-growth bounds under a kernel assumption. The archived card records a deliberately selected finite computational specialization.'),block('For fixed finite H and T there are finitely many histories. Transition constraints are semialgebraic, policy choices form products of simplexes, and trajectory expectations are polynomials in transition and action probabilities. The Bellman optimum is a maximum of finitely many policy-return polynomials.'),block('The resulting continuous optimization is over compact finite-dimensional sets. Quantifier elimination over rational polynomial conditions can isolate its minimax value as a real algebraic number, decide whether it is zero, and otherwise produce a positive rational approximation within a factor of two. This is an editorial deduction from the standard theorem, not a claim that the cited survey studies kernel reinforcement learning.','qe')],
 progress=[progress('2014','The cited survey explains effective quantifier elimination over real closed fields, the general decision procedure used by the finite specialization.','qe'),progress('2024','The source poses the broader kernel-regret program.'),progress('2026-09-18','The user selected and authorized archival of the finite unrestricted-computation target; the compact semialgebraic reduction explains its known algorithmic status.','qe')],
),['Applied the user-selected finite full-Gram-matrix model and explicit archival decision.','Specified rational inputs, pointwise norm bounds, unknown real transition probabilities, history-dependent learning and starting-state conventions.','Explained the finite compact semialgebraic reduction, including exact zero testing needed for multiplicative approximation.','Preserved the previous importance assessment for provenance; did not claim the broader infinite-domain problem solved.'],['Read Vakili COLT 2024 §§2–4 in full, including known deterministic rewards, stage-dependent transitions and pointwise RKHS norms.','Read Basu survey §2.1, Theorem 2.1 and the effective quantifier-elimination discussion.','Individually checked the finite-history polynomial encoding, compactness and algebraic-value argument as an editorial consequence; no Lean formalization was performed.'],'Resolved as the user-selected finite computational target with unrestricted running time. Finite histories and rational kernel constraints reduce minimax regret to compact semialgebraic optimization; effective real quantifier elimination supplies exact zero testing and a uniform constant-factor rational approximation. This is an editorial application of a standard theorem, not a literature claim settling Vakili’s broader infinite-domain or sharp analytic-rate question.',summary=['The selected model has finite states and actions, known rational rewards and a known rational kernel matrix.','Unknown transition probabilities satisfy explicitly bounded finite-kernel Hilbert-space norms.','The target is minimax expected regret up to constant factors, with no limit on computation.','Finite interaction histories turn that value into a compact real-algebraic optimization that can be evaluated by quantifier elimination.','The user therefore chose to archive this finite computational target without closing the broader kernel reinforcement-learning question.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'],archive_reason='User-confirmed archival of the finite full-kernel, unrestricted-computation minimax-regret target: known real quantifier elimination gives exact algebraic evaluation and constant-factor rational approximation; broader infinite-domain regret questions are not claimed resolved.')
