"""Make the linear-total-space MPC cycle conjecture fully quantified."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,block,progress
from review_queue import read_claims
identifier='TCS-6505';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text())
complete(identifier,dict(
 title='One-cycle versus two-cycles conjecture',status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Is the following conjecture true? For every fixed sublinear local-memory exponent \(0<\delta<1\), every uniform randomized MPC algorithm \(A\) that distinguishes a single cycle of length \(n\) from two disjoint cycles of length \(n/2\), with high probability and linear total memory as specified below, requires \(\Omega(\log n)\) worst-case synchronous rounds. More precisely, for every fixed positive integer confidence parameter \(h\), there must be constants \(c_{A,h}>0\) and \(n_{A,h}\) such that
\[T_A(n,h)\ge c_{A,h}\log_2 n\]
for every even \(n\ge n_{A,h}\). Correctness has probability at least \(1-n^{-h}\) on each promised graph and every admissible initial placement of its edge list.''',
 definitions=r'''The input is an edge list of a simple undirected graph with vertex set \(\{1,\ldots,n\}\), for even \(n\ge6\). It is promised to consist either of one cycle through all \(n\) vertices or of exactly two disjoint cycles, each through \(n/2\) vertices. Every edge appears once as its pair of endpoints; the orientation of that pair and list order are arbitrary. Both cases have exactly \(n\) edges and degree two at every vertex. The vertex names carry no order around a cycle. Inputs outside the promise impose no correctness requirement.

Here is a fixed finite-word version of linear-total-space MPC. For a fixed \(\delta\), use \(p(n)=\lceil n^{1-\delta}\rceil\) machines, indexed from one to \(p(n)\). For each fixed \(h\), the algorithm may choose constants \(K_h\ge4\) and an integer \(B_h\ge2\), independent of \(n\). A word has \(B_h\lceil\log_2(n+2)\rceil\) bits. Each machine can store at most \(K_h\lceil n^\delta\rceil\) words, including its input, work state and communication buffers. Thus the sum of memory capacities is \(O(n)\) words for fixed \(h,\delta\). Initially each edge record is placed on one machine, and every placement fitting these local capacities is allowed. Other mutable memory is initially blank. Each machine knows \(n,p(n),h\) and its own index; fixed model parameters are part of the program.

Each synchronous round allows arbitrary finite local computation within that memory and communication with arbitrary other machines. Each machine sends at most \(K_h\lceil n^\delta\rceil\) words in total and receives at most that many; words may encode arbitrary information rather than whole graph records. Recipient addresses count as part of the communicated data. The algorithm must respect both send and receive bounds on every promised input and every random tape. Messages arrive before the next round. Local computation must terminate but has no time bound. Machines have private independent fair random bits and may additionally use a common read-only fair random tape; random bits retained for later use occupy memory. There is no further advice or oracle.

All machines execute one finite program with their indices as input. The program is uniform over \(n,h\); it can depend on the fixed exponent. It suffices to quantify over rational \(\delta\in(0,1)\), so all machine counts and capacity bounds are effectively specified: any fixed smaller real exponent is dominated by a rational exponent below one, and a lower bound for every rational exponent covers it. Constants in the resource bounds may depend on the program and fixed confidence parameter, but not on the input or placement.

Machine one must eventually output ONE or TWO. On every promised input and placement, the output must be correct with probability at least \(1-n^{-h}\), jointly over all random bits. No machine may exceed the resource bounds even on a tape leading to an incorrect answer. Let \(T_A(n,h)\) be the supremum of the number of synchronous rounds until this output, over all promised inputs with exactly \(n\) vertices, all initial placements and all random tapes. Eligible algorithms have finite \(T_A(n,h)\) for each \(n,h\). The target is a worst-case round bound, not expected time.

High probability means that every fixed positive integer \(h\) can be requested as an input parameter; integer parameters also imply every fixed real failure exponent. The lower-bound constants may depend on \(h,\delta,A\). No component-stability, comparison-only or indivisible-record restriction is imposed. In particular, graph distance does not bound the distance a message can travel between machines.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof of the universal logarithmic lower bound or of its full negation. A uniform \(o(\log n)\)-round algorithm for one fixed \(\delta<1\), with the stated correctness and space bounds for every fixed confidence parameter, suffices to refute it. The literal negation can also be witnessed by failure of the eventual lower bound along an unbounded subsequence; a refutation need not be little-o at every size. A bound only for restricted encodings, component-stable algorithms, geometric embeddings or larger total memory does not prove the stated conjecture.''',
 source_formulation=dict(text='The source explicitly states the 2-CYCLE conjecture with strongly sublinear local memory, linear total space and high-probability correctness. This card fixes the word and communication conventions and writes the eventual logarithmic lower bound literally.',citation='grid',caption='Gan–Wirth–Zhang, ICDT 2025, p.7:2, MPC model and 2-CYCLE conjecture.',format='editorial_paraphrase'),
 references=old['references'],
 progress=[progress('2022','The equivalence-class work relates cycle distinctions to other MPC tasks. Such transfers have their own total-space conditions and are not used as a proof of this linear-space conjecture.','equivalence'),progress('2025-03-21','The checked source states the linear-total-space 2-CYCLE conjecture while obtaining constant-round connectivity for geometrically embedded grid graphs. Arbitrarily labeled promised cycles do not supply that geometry.','grid')],
 context_blocks=[block('The two promised cases have identical vertex and edge counts and identical degrees. The algorithm must learn how the distributed edge records connect into components.','grid'),block('No machine can store the whole input, but communication can connect any pair of machines. A valid lower bound must handle arbitrary coded messages and unrestricted finite computation within the memory limit.','grid'),block('This small connectivity promise is used to organize conditional MPC round lower bounds. The selected linear total-space convention should remain explicit when comparing those reductions.','equivalence')],
),['Preserved the source’s linear-total-space conjecture and individual importance score of 88.','Defined arbitrary edge placements, word size, machine memory, general messages and the output convention.','Made confidence and eventual lower-bound quantifiers explicit, including the true negation versus a sufficient little-o refutation.','Excluded an accidental LOCAL-distance argument and did not transfer broader-memory equivalences.'],['Read the primary ICDT 2025 p.7:2 MPC model, exact conjecture and geometric algorithm scope.','Checked the existing equivalence-work bibliographic record and bounded later searches; the DOI fetch failed, so no new full-paper proof read is claimed for that auxiliary reference.','Bounded searches through 18 September 2026 found no verified resolution of the selected arbitrary-message linear-total-space conjecture.'],'The exact local/total-memory conjecture is explicitly stated in the checked ICDT 2025 source. Its geometric connectivity algorithm uses additional structure and does not settle the promise problem here. Bounded later-work checks through 18 September 2026 found no verified resolution, without certifying exhaustive coverage.',summary=['The input graph is promised to be one large cycle or two equal-sized cycles.','Its edge list is spread across machines with sublinear local memory and linear total memory.','Machines can exchange arbitrary coded messages with any other machines, subject to per-round volume limits.','The conjecture requires logarithmically many rounds for every uniform high-probability algorithm in this model.','The identical local degrees and edge counts make the global arrangement of the components the essential information.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
