"""Complete the true constant-approximation target for capacitated k-median."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-6309';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='A polynomial-time constant approximation for capacitated k-median without violations',
 status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Do there exist an absolute rational constant \(\rho\ge1\), positive integers \(K,a\), and one classical randomized algorithm \(A\) such that every capacitated metric \(k\)-median instance of bit length \(L\) is processed in at most \(K(L+2)^a\) steps on every execution, with the following guarantee? Infeasibility is always reported correctly. On every feasible instance, every execution returns a feasible solution \((S,\phi)\), and
\[
\Pr\!\left[\sum_{c\in C}d(c,\phi(c))\le\rho\,\mathrm{OPT}\right]\ge\frac23.
\]
The solution must use at most \(k\) distinct facilities and respect every facility’s capacity exactly; neither constraint may be exceeded.''',
 definitions=r'''The input specifies a finite ground set \(V=[N]\), with \(N\ge1\), a nonempty facility set \(F\subseteq V\), a client set \(C\subseteq V\), and an integer \(1\le k\le|F|\). A point may be both a client and a facility. Every client represents one unit of demand. The full distance table \(d:V\times V\to\mathbb Q_{\ge0}\) is explicit and satisfies \(d(v,v)=0\), \(d(u,v)>0\) for distinct points, symmetry and the triangle inequality. Distances are encoded as binary integer numerator and positive denominator. Each facility \(f\in F\) has a nonnegative integer capacity \(u_f\), encoded in binary. Capacities may differ arbitrarily. Values exceeding \(|C|\) may equivalently be truncated to \(|C|\). The subsets, integer parameters and entire distance table form the finite input of total bit length \(L\).

A solution opens a subset \(S\subseteq F\) with \(|S|\le k\) and gives a map \(\phi:C\to S\). It is feasible when \(|\phi^{-1}(f)|\le u_f\) for every \(f\in S\). Every client must be assigned wholly to one open facility; demands cannot be split or discarded. A facility can be opened only once. The cost is \(\sum_{c\in C}d(c,\phi(c))\), and \(\mathrm{OPT}\) is the minimum of this cost over all feasible solutions. There are no opening costs, outliers, extra centers or soft capacities. If \(C\) is empty, the empty solution is feasible with cost zero.

Feasibility itself is elementary in this model: every client may use every facility, so a feasible solution exists exactly when the sum of the \(k\) largest capacities is at least \(|C|\). A deterministic fallback can open those facilities and assign clients greedily. Consequently, insisting on a feasible output even on unsuccessful random tapes is a harmless normalization of the approximation target. Zero optimum must be treated by the same multiplicative guarantee, without an additive error allowance.

The algorithm is a uniform randomized multitape Turing machine using only independent fair random bits. The time bound includes reading the finite encoding, rational arithmetic, all random bits and the explicit facility list and assignment output. No exact real arithmetic, advice, oracle or uncharged preprocessing is available. The constants are independent of \(N,|F|,|C|,k\), capacities and numerical precision. The success probability is per input, not an average over a distribution of instances. The question imposes no guarantee on malformed tables that are not metrics.

The target is polynomial in the entire input length with one fixed exponent. A running time \(f(k)L^{O(1)}\) with superpolynomial dependence on \(k\) does not suffice. An approximation that opens \((1+\varepsilon)k\) facilities or uses \((1+\varepsilon)u_f\) capacity does not suffice, even for arbitrarily small fixed \(\varepsilon>0\). The question concerns arbitrary finite metrics and nonuniform capacities, not only Euclidean spaces or uniform-capacity instances.''',
 answer_criterion='Give a complete mathematically correct Lean-checked construction and proof of the algorithm with an absolute approximation factor and uniform polynomial bit time, or a complete Lean-checked refutation of this existence statement. Verify exact feasibility on every execution and the per-instance probability bound. An FPT-time approximation or any capacity/cardinality violation is insufficient; conditional hardness alone is not an unconditional refutation.',
 why='This is a central facility-location approximation problem in which both resource constraints must be enforced. Resolving it would determine whether constant-factor metric clustering survives exact capacities and an exact bound on the number of open facilities in polynomial time.',
 importance=dict(score=89,method='editorial',reason='A prominent general-metric approximation barrier repeatedly highlighted in clustering literature, with the simultaneous capacity and cardinality requirements distinguishing it from known bicriteria and FPT results.'),
 source_formulation=dict(text='The source explicitly asks for a polynomial-time constant-factor approximation preserving both capacities and the number of open facilities. Its model uses general metrics and individual capacities. The finite rational input and randomized success convention are the announced editorial recommendation after an optional question remained unanswered; they are not represented as an explicit user confirmation.',caption='Adamczyk et al., abstract and §1.1 pp.1:1–3.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Constant-Factor FPT Approximation for Capacitated k-Median','Marek Adamczyk; Jarosław Byrka; Jan Marcinkowski; Syed M. Meesum; Michał Włodarczyk',2019,'https://doi.org/10.4230/LIPIcs.ESA.2019.1','Abstract and §1.1 pp.1:1–3'),ref('recent','On Tight FPT Time Approximation Algorithms for k-Clustering Problems','Han Dai; Shi Li; Sijin Peng',2026,'https://doi.org/10.4230/LIPIcs.ICALP.2026.72','§1.1, capacitated clustering discussion pp.72:2–3; Theorem 1')],
 context_blocks=[block('The source obtains a constant approximation in time exponential in a function of k times a polynomial in the instance size. That addresses fixed-parameter approximation, while the selected question requires ordinary polynomial time.'),block('Earlier constant-factor methods can violate capacities or the number of facilities. The source emphasizes that preserving both constraints is the unresolved part, even though logarithmic true approximations are available.'),block('The ICALP 2026 paper again describes a true constant approximation for capacitated k-median without violations as open. Its new general-norm result is also parameterized by k and does not resolve the selected polynomial-time question.','recent')],
 progress=[progress('2019','A constant-factor FPT approximation is proved while the polynomial-time true-approximation question is retained.'),progress('2026','ICALP work still identifies the no-violation polynomial-time constant factor as an open target.','recent')],
),['Specified the exact two constraints, unit clients, nonuniform hard capacities and arbitrary rational metrics.','Made the uniform randomized polynomial bit model and per-input success guarantee explicit as the announced editorial default.','Required feasibility on every execution and handled empty clients, zero optimum and infeasible inputs.','Distinguished FPT time and bicriteria guarantees from the requested polynomial-time approximation.'],['Read the 2019 abstract, full input definition and comparison with true, bicriteria and FPT approximation algorithms.','Read the ICALP 2026 abstract, §1.1 capacitated-clustering discussion and Theorem 1.','Bounded checks through 18 September 2026 did not locate a contrary resolution.'], 'Source-open, explicitly repeated in the checked ICALP 2026 discussion. Bounded checks through 18 September 2026 found no verified polynomial-time constant approximation preserving both constraints. The finite bit model and allowance of randomization were announced after an unanswered optional scope question.',summary=['Clients must be assigned to at most k chosen facilities in a finite metric space.','Each facility has its own hard capacity, and every client must be served.','The question asks for a constant-factor approximation in ordinary polynomial time.','Randomization is permitted, but every output must respect both resource constraints.','Known algorithms that use FPT time or exceed a resource bound do not settle this target.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
