"""Specify the maximum generalized-assignment configuration-LP gap."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0922';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Configuration-LP gap for maximum generalized assignment',status='source_open',criterion='tightness',question_type='numerical_value',
 area='Approximation algorithms and hardness of approximation',category_assignment=dict(method='editorial_topic',reason='The recovered source target is an offline configuration-LP integrality gap, not an online arrival problem.'),
 formal=r'''Determine, with absolute error at most \(1/100\), the constant
\[
g_{\mathrm{GAP}}=\inf_{\substack{I\text{ a finite rational maximum}\text{ generalized-assignment instance}\\\mathrm{LP}(I)>0}}
\frac{\mathrm{OPT}(I)}{\mathrm{LP}(I)},
\]
where \(\mathrm{OPT}\) is the maximum total value of a feasible integral assignment and \(\mathrm{LP}\) is the configuration relaxation defined below. The convention is integral optimum divided by fractional optimum, so \(g_{\mathrm{GAP}}\in[0,1]\). The numbers of items and bins are unbounded.''',
 definitions=r'''An instance has \(m\ge1\) bins, each with capacity one, and \(n\ge1\) indivisible items. For every bin \(i\in[m]\) and item \(j\in[n]\), it specifies nonnegative rational size \(s_{ij}\) and value \(v_{ij}\). Both may depend on the bin. The complete finite tables are explicit, with rationals represented by binary numerators and positive binary denominators; there is no bound on their bit lengths. Zero sizes and zero values are permitted, and a size exceeding one makes that bin-item assignment infeasible.

A feasible integral assignment is a tuple of pairwise disjoint subsets \((S_1,\ldots,S_m)\) of \([n]\) satisfying \(\sum_{j\in S_i}s_{ij}\le1\) for every bin. Items may remain unassigned. Its objective is \(\sum_i\sum_{j\in S_i}v_{ij}\), and \(\mathrm{OPT}(I)\) is the maximum of this objective over all feasible assignments. All decisions use the full input; there is no arrival order, uncertainty, strategic bidding or recourse constraint.

For bin \(i\), let \(\mathcal C_i=\{S\subseteq[n]:\sum_{j\in S}s_{ij}\le1\}\) and \(v_i(S)=\sum_{j\in S}v_{ij}\). The configuration LP has one real variable \(x_{i,S}\) for every \(i\) and every \(S\in\mathcal C_i\), including the empty configuration. Its optimum is
\[
\mathrm{LP}(I)=\max\left\{\sum_{i=1}^m\sum_{S\in\mathcal C_i}v_i(S)x_{i,S}:\
x_{i,S}\ge0,\quad\sum_{S\in\mathcal C_i}x_{i,S}\le1\ (i\in[m]),\quad
\sum_{i=1}^m\sum_{\substack{S\in\mathcal C_i\\j\in S}}x_{i,S}\le1\ (j\in[n])\right\}.
\]
It is a finite, possibly exponentially large LP. Using equality for each bin gives the same optimum because unused mass can be put on its empty configuration. Integral solutions embed in this LP, so \(0\le\mathrm{OPT}(I)\le\mathrm{LP}(I)\). Instances with zero fractional optimum are excluded from the ratio. The family is nonempty, for example one positive-value item fitting in one bin.

The infimum ranges over all such finite rational instances, with no bound on either cardinality or numerical precision. It need not be attained by a single instance. This is a worst-case extremal constant for this particular relaxation, not the best approximation ratio of unrestricted polynomial-time algorithms. No complexity hypothesis or efficiency requirement for evaluating the submitted answer is imposed. The selected maximization of total value is different from maximizing the minimum load received by a bin or minimizing a scheduling makespan.

An admissible answer is a real number \(a\) with a proof that \(|a-g_{\mathrm{GAP}}|\le1/100\), or certified bounds \(l\le g_{\mathrm{GAP}}\le u\) with \(u-l\le1/50\), whose midpoint supplies such an answer. A mathematical expression may specify the number; merely repeating the defining infimum does not determine it. Bounds for only one fixed item count, bin count or restricted size family do not establish the full-domain lower bound.''',
 answer_criterion='Supply an approximation or enclosing interval with the stated absolute tolerance and a complete mathematically correct Lean-checked proof over all finite rational instances of the displayed configuration LP. Exact determination is welcome but unnecessary. A feasible fractional assignment, a single bad instance without a sufficiently matching universal bound, or an algorithmic hardness ratio for another model does not meet the criterion.',
 why='Configuration relaxations encode every feasible packing within each bin while retaining fractional conflicts between bins. Locating their unavoidable loss measures the strength of a central relaxation for allocation and distinguishes its limitations from those of particular rounding algorithms.',
 source_formulation=dict(text='The 2016 entry first discusses improving upper and lower bounds on the configuration-LP gap for maximum generalized assignment, including investigations of restricted instances, and then poses a separate restricted max-min allocation question. The selected target is numerical determination of the former full-family gap to the atlas tolerance. This exact scope is an announced editorial default after an unanswered optional branch question.',caption='Scheduling, Seminar 16081, §4.7 p.114; maximum-assignment definitions and LP in Vondrák, Chapter 6.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Scheduling: Generalized assignment','Christos Kalaitzis',2016,'https://doi.org/10.4230/DagRep.6.2.97','Seminar 16081, §4.7 p.114'),ref('gap','Submodularity in Combinatorial Optimization','Jan Vondrák',2007,'https://theory.stanford.edu/~jvondrak/data/KAM_thesis.pdf','Chapter 6 pp.127–130; §6.1 two-bin example and Theorem 6.2'),ref('recent','Improved Hardness Results for Nash Social Welfare, Budgeted Allocation and GAP via the Unique Games Conjecture','Vignesh Viswanathan',2026,'https://arxiv.org/abs/2605.27098v2','Revision of 26 July 2026, §1.1 Theorem 1.3 and related-work discussion p.4')],
 context_blocks=[block('The source groups maximum total-value assignment and restricted max-min allocation under one heading. They use different objectives and different configuration relaxations; the latter is not part of this card.'),block(r'The checked earlier source proves a universal guarantee strictly above \(1-1/e\) and exhibits an instance with integral-to-fractional ratio \(4/5\). These bounds leave an interval much wider than the required numerical tolerance.','gap'),block('The July 2026 revision reports improved conditional inapproximability for maximum generalized assignment, while still distinguishing that algorithmic threshold from the known configuration-LP gap. Its hardness theorem does not determine the selected constant.','recent')],
 progress=[progress('2007',r'The checked thesis gives a \(4/5\) integrality-gap example for two bins and a universal lower bound strictly exceeding \(1-1/e\).','gap'),progress('2016','The seminar report calls for tighter configuration-LP gap bounds for generalized assignment.'),progress('2026-07-26','The current checked preprint improves UGC-based algorithmic hardness but describes the relaxation bounds separately; it does not provide the requested gap value.','recent')],
),['Recovered the offline maximum-value objective and separated the max-min allocation paragraph.','Defined every configuration, LP constraint, integral assignment and ratio convention.','Selected the full rational instance family and absolute 1/100 numerical criterion as the announced editorial default.','Moved the card from online algorithms to approximation algorithms based on its actual target and preserved its importance score.'],['Read Scheduling 2016 §4.7 in full.','Read Vondrák Chapter 6 pp.127–130, including the displayed LP, explicit gap example and universal rounding theorem statement.','Checked the 26 July 2026 revision of Viswanathan §1.1; distinguished its conditional algorithmic lower bound from an exact LP integrality-gap determination.'], 'Source-open as a configuration-LP gap investigation in the 2016 seminar report. The selected numerical full-family target remains unsupported by a matching known interval in the bounded primary-source review through 18 September 2026; the checked July 2026 preprint does not resolve it. The precise numerical and branch selection is an announced editorial default, not a received user confirmation.',summary=['Maximum generalized assignment packs indivisible items into bins to maximize their total value.','Both an item’s size and its value may depend on the bin receiving it.','The configuration LP allows fractional mixtures of every feasible packing while limiting each item’s total assignment.','The target is the worst integral-to-fractional optimum ratio, determined to absolute accuracy one hundredth.','This measures the relaxation’s strength and is distinct from the source’s separate max-min allocation question.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
