"""Specify an unconditional lower bound for the source's fixed two-step query."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-7128';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Unconditional constant-delay lower bound for the two-step query',status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Is it true, without any unproved complexity assumption, that the fixed query
\[
q_R=\{(x,y)\in[n]^2:\exists z\in[n],\ (x,z)\in R\ \land\ (z,y)\in R\}
\]
has no uniform deterministic constant-delay enumeration algorithm after linear preprocessing in the model below? Equivalently, is there no pair of finite programs \((P,E)\) and no integers \(B,c,d,s\ge1\), with \(B\ge2\), such that for every explicitly listed binary relation \(R\subseteq[n]^2\), \(P\) uses at most \(cN\) word-RAM instructions and \(E\) then outputs exactly \(q_R\), without repetition, with worst-case delay at most \(d\) and at most \(s\) additional working words? Here \(N=n+|R|+1\) and words have \(B\lceil\log_2(N+2)\rceil\) bits.''',
 definitions=r'''The input contains a nonnegative domain size \(n\), an explicit list of the domain elements \(1,\ldots,n\), and an arbitrarily ordered duplicate-free list of ordered pairs defining \(R\). There are no promises of symmetry, acyclicity, bounded degree or an existing adjacency matrix. Loops are allowed. Both coordinates of every pair belong to the domain. The parameter \(N\) measures input size in words up to constant factors, rather than in bits. A tuple coordinate fits in one word. The query itself is fixed and is not part of the input.

The existential variable is a witness, not part of an output tuple. In particular, several different \(z\) values producing the same pair must lead to only one output. Vertices may coincide, and a pair joined by an edge can also be an answer. Thus the query is the existence of a directed walk of exactly two edges; it does not ask that shortest-path distance equal two. The output order is unrestricted.

The computation model is a uniform word-RAM with word size \(w=B\lceil\log_2(N+2)\rceil\), where \(B\) is a fixed constant chosen with the programs. Each instruction accesses a constant number of words. Unit-cost instructions are copying a word, reading or writing an addressed word, comparisons, conditional branching, addition and subtraction modulo \(2^w\), and bitwise Boolean operations and shifts by an amount stored in a word. A shift by at least \(w\) returns zero. Multiplication and division are not primitive unit-cost operations. There is no unbounded-precision arithmetic instruction, nonuniform lookup table, randomness or oracle. Programs have only finitely many fixed constants, independent of the input. Memory addresses fit in one word, and uninitialized memory contains zero. This specifies a finite-word addition-based RAM convention for the source's RAM-with-addition model.

Preprocessing may read the entire input and write a data structure, using at most \(cN\) instructions. Consequently it can initialize only \(O(N)\) memory cells. The enumeration phase can read the input and this prepared structure by random access but cannot modify them. Apart from them, its entire mutable state consists of at most \(s\) words, including registers and counters, and a finite control state. Its output is a write-only stream of vertex pairs, which cannot be read back as working memory. Producing a pair costs a constant number of instructions.

The delay is the largest number of instructions from the end of preprocessing to the first output, between consecutive outputs, and from the last output to termination. If the answer is empty, termination must occur within \(d\) instructions of the end of preprocessing. Constants \(B,c,d,s\) and the programs are fixed before \(n,R\) vary. No amortized, expected, logarithmic-delay or unrestricted-extra-memory substitute meets these conditions.

The statement is the nonexistence of the algorithm pair. Its refutation requires a construction meeting both the preprocessing and delay bounds for all relations. Its proof must be unconditional. An implication from a Boolean-matrix-multiplication hardness conjecture, or a lower bound only in a more restrictive comparison model, is not the requested unconditional result.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof of the displayed unconditional nonexistence statement, or refute it by supplying uniform preprocessing and enumeration programs with the stated bounds. All word-size and hidden constants must be fixed independently of the relation. A conditional reduction, a lower bound for one particular algorithm, or a total-time guarantee without worst-case delay control is insufficient.',
 importance=dict(score=81,method='editorial',reason='An unconditional barrier for a canonical two-atom query would go beyond the conditional framework supporting much of query-enumeration complexity. It would explain whether duplicate-free constant-delay output has an inherent cost even for a minimal join pattern.'),
 why='Checking a particular two-edge walk is easy, but listing all endpoint pairs must suppress potentially many witnesses for the same output. The target asks for an unconditional obstruction to combining that task with linear preparation and constant time between outputs.',
 source_formulation=dict(text='The survey asks for unconditional enumeration lower bounds and names the two-step query as a concrete example. This card selects that example as an editorial default after an optional scope question. It retains the source’s constant extra enumeration space and read-only prepared index, and specifies a finite-word addition-based RAM.',caption='Segoufin, §2.2, §2.4, Example 2 and §6.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Constant Delay Enumeration for Conjunctive Queries','Luc Segoufin',2015,'https://databasetheory.org/sites/default/files/2016-06/segoufin.pdf','§2.2 RAM convention; §2.4 constant-delay class; Example 2; §6 unconditional lower bounds')],
 context_blocks=[block('The query is fixed, so constants depending only on query size are ordinary constants here. The source explicitly makes the prepared index read-only and allows only constant additional memory during enumeration.'),block('The known conditional connection to Boolean matrix multiplication motivates the difficulty, but the selected benchmark asks to remove an unproved hardness premise. New results for strings, restricted graph classes or different logical queries do not settle this fixed general-relation task.')],
 progress=[progress('2015','The survey identifies unconditional lower bounds for this concrete query as an open challenge, beyond its conditional lower-bound framework.'),progress('2026-09-18','The target and machine conventions have been individually specified; bounded later-work checks found no verified unconditional resolution.')],
),['Selected the fixed two-step relation query as the announced editorial default.','Distinguished walk length from shortest-path distance and output pairs from existential witnesses.','Defined word size, RAM instructions, read-only preprocessing output and constant additional enumeration memory.','Included initial and terminal delay and required an unconditional lower bound; assessed importance individually.'],['Read Segoufin §§2.2 and 2.4, Example 2 and the conclusion’s unconditional-lower-bound paragraph.','Checked the stated connection to conditional matrix-product hardness without importing it as an allowed assumption.','Bounded later searches through 18 September 2026 found different restricted-query and dynamic-enumeration results, but no verified unconditional solution of this target.'],'Source-open in Segoufin’s 2015 unconditional-enumeration discussion. The selected two-step query and finite-word addition-based RAM are now explicit, including the source’s constant extra enumeration-space convention. Bounded later-work checks through 18 September 2026 found no verified unconditional resolution, without certifying exhaustive coverage.',summary=['The input is one finite binary relation, viewed as a directed graph.','The fixed query returns each endpoint pair connected by a two-edge walk, regardless of how many intermediate witnesses it has.','The proposed algorithm would prepare a read-only index in linear time and enumerate answers with constant worst-case delay and constant extra memory.','The question asks for an unconditional proof that no such deterministic algorithm exists in the specified addition-based word-RAM model.','A result relying on matrix-multiplication hardness would not meet that requirement.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
