"""Audit the saved general SCS approximation value, separate from greedy."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,block,progress
from review_queue import read_claims
identifier='TCS-7322';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text());refs=old['references']
refs[0]['locator']='§§1 and 2.5, Theorem 3.1: cycle-cover inequality and its 7/3 general-approximation consequence; Theorem 3.3 limits that inequality, not all algorithms.'
refs[1]['locator']='September 2026 version 1; introduction and contribution statement: a 9/4 lower-bound claim for maximum-overlap greedy, not for every polynomial-time algorithm.'
complete(identifier,dict(
 status='uncertain',criterion='decision',question_type='numerical_value',
 formal=r'''Determine, with absolute error at most \(1/100\), the real number
\[
\rho_{\mathrm{SCS}}=\inf\mathcal R,\qquad
\mathcal R=\{r\ge1:r\text{ is an achievable approximation ratio}\}.
\]
A ratio is achievable if one uniform deterministic polynomial-bit-time algorithm outputs, on every instance \(I\), a common superstring \(w\) with \(|w|\le r\operatorname{OPT}(I)\).
The input alphabet and strings are explicit, and the algorithm may be any algorithm in the model below. This is the best possible approximation ratio for shortest common superstring, not the worst-case ratio of maximum-overlap greedy.''',
 definitions=r'''An instance is an integer \(\sigma\ge1\) and a finite list of finite strings \(s_1,\ldots,s_k\) over \(\Sigma=\{1,\ldots,\sigma\}\), where \(k\ge0\). Encode \(\sigma,k\), the length of each string and each symbol in binary with self-delimiting integer fields. For definiteness, encode \(z\ge0\) by a unary prefix giving the bit length of \(z+1\), a zero delimiter, then the binary expansion of \(z+1\). The list contains every symbol explicitly; neither grammar compression nor an oracle representation is allowed. Let \(L\) be the total number of input bits.

A feasible output is an explicit string \(w\in\Sigma^*\) such that, for each \(i\), there are strings \(u_i,v_i\) with \(w=u_i s_i v_i\). Occurrences are ordinary forward contiguous substrings; reversal, reverse complementation, subsequences and cyclic wraparound are not allowed. The objective \(|w|\) counts symbols, not bits. Define \(\operatorname{OPT}(I)\) as the minimum feasible length. Concatenating the input strings proves feasibility and finiteness. Empty and repeated input strings are allowed. If the list is empty or every member is empty, the optimum is zero, and every finite-factor algorithm must return the empty string. Strings contained in other input strings may be removed by preprocessing, but that work is charged.

An admissible algorithm is one finite deterministic multitape Turing-machine program. For its chosen ratio \(r\), some constants \(K>0\) and integer \(d\ge1\) bound its total steps by \(K(L+1)^d\) on every encoded input. It rejects malformed encodings within that bound. On valid inputs it always outputs a feasible string satisfying the claimed ratio. Reading, preprocessing, integer and symbol operations and writing the complete output all count as bit steps. The program has no advice, randomness or free oracle. Its program and polynomial may depend on \(r\), but not on input size or on the instance.

The infimum is over ratios achievable with one such global guarantee. It need not itself be achievable by a single algorithm. Known constant-factor algorithms make the set nonempty, so \(\rho_{\mathrm{SCS}}\) is finite and at least one. A lower bound on this infimum concerns all deterministic polynomial-time algorithms; a bad input for one particular heuristic is insufficient. No separation assumption such as \(\mathrm P\ne\mathrm{NP}\) is built into this numerical target. In particular, an algorithmic or hardness claim conditional on an assumption yields only a conditional bound unless that assumption is also proved.''',
 answer_criterion=r'''Supply a specified real number \(a\), given by an explicit mathematical expression or construction independent of the defining optimization, and a complete mathematically correct Lean-checked proof that \(|a-\rho_{\mathrm{SCS}}|\le1/100\). Certified bounds \(\ell\le\rho_{\mathrm{SCS}}\le u\) with \(u-\ell\le1/50\) suffice via their midpoint. Exact equality also qualifies. A one-sided approximation improvement, a renamed defining infimum or an unsupported numerical estimate is insufficient. A proof assuming an unproved hardness hypothesis establishes only its conditional conclusion, not this unconditional acceptance target. The tolerance does not decide whether a particular exact threshold, such as two, is achievable.''',
 references=refs,
 source_formulation=dict(text='The sources study approximation guarantees for the general shortest common superstring problem and separately for maximum-overlap greedy. The saved September 12–13 broader numerical target is retained: approximate the optimum deterministic polynomial-time guarantee itself.',citation='primary',caption='General approximation problem in §1, distinguished from the greedy analysis in §2.5.',format='editorial_paraphrase'),
 context_blocks=[block('Shortest common superstring models assembly by overlaps, with exact containment as the feasibility requirement. Its approximation frontier asks how close polynomial-time assembly can always come to the shortest possible output.','primary'),block(r'The August 2026 report derives a \(7/3\) general approximation from its cycle-cover inequality and a factor-three greedy guarantee. Tightness of that inequality only limits the specific analysis, not all possible algorithms.','primary'),block(r'The September preprint claims greedy instances approaching ratio \(9/4\). That refutes a greedy factor-two guarantee if verified, while leaving the existence of a different factor-two algorithm and the full numerical frontier unsettled.','greedy-claim')],
 progress=[progress('2026-08-30',r'The ECCC report gives the \(7/3\) general bound and greedy upper bound three; §2.5 states the algorithmic consequence of Theorem 3.1.','primary'),progress('2026-09-01',r'Shibata’s preprint claims a greedy lower ratio \((9k+2)/(4k+4)\) for even \(k\ge10\), tending to \(9/4\). This review checks the statement and its scope, not the full counterexample proof.','greedy-claim')],
),['Retained the saved numerical optimum with absolute 1/100 tolerance and no silently added complexity assumption.','Made the infimum, global uniformity, explicit alphabet encoding, zero optimum and output requirement self-contained.','Separated general approximation, a tight analysis inequality and the specific greedy-counterexample claim.','Preserved individual importance 85 and uncertain status for the precise tolerance-level frontier.'],['Read the August 2026 full primary report’s introduction, §2.5 and main inequality statements.','Read the September 2026 primary greedy preprint’s introduction, contribution formula and substring conventions; no independent full proof audit is claimed.','Bounded subsequent searches through 18 September 2026 found reverse-complement variants and greedy refinements, not certified two-sided bounds of width 1/50 for this general numerical target.'],'The checked primary sources leave the best general approximation ratio unknown. They do not provide a tolerance-1/100 characterization of the unconditional numerical infimum. The greedy refutation is recorded as a recent preprint claim with its narrower scope. Bounded checks through 18 September 2026 are not an exhaustive certification of current openness.',summary=['A common superstring contains every supplied string as an ordinary contiguous substring.','The objective is its minimum number of symbols over the explicitly supplied alphabet.','The target is the infimum approximation ratio of all uniform deterministic polynomial-bit-time algorithms.','The numerical answer must have a proved absolute error of at most one hundredth.','Recent general upper bounds and a separate greedy counterexample do not determine that full optimum.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
