"""Specify the DAG-treewidth candidate for sparse-host homomorphism counting."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-5374';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='A DAG-treewidth dichotomy for homomorphism counting in degenerate graphs',
 status='source_open',criterion='characterization',question_type='yes_no',
 formal=r'''Is the following dichotomy true for every computable isomorphism-closed class \(\mathcal C\) of finite nonempty simple undirected graphs? For exact homomorphism counting \(\#\mathrm{Hom}_d(\mathcal C)\), parameterized by \(|V(H)|+d(G)\):

If \(\sup_{H\in\mathcal C}\tau_1(H)<\infty\), the problem is fixed-parameter tractable; if \(\sup_{H\in\mathcal C}\tau_1(H)=\infty\), it is \(\#\mathsf W[1]\)-hard under deterministic fixed-parameter Turing reductions.

Here \(d(G)\) is the degeneracy of the host graph and \(\tau_1\) is the maximum generalized DAG-treewidth over all acyclic orientations, with the exact definitions below. The bounded-width direction is known; the target includes the unbounded-width hardness direction.''',
 definitions=r'''An input consists of a pattern \(H\in\mathcal C\), with \(k\ge1\) vertices, and a host graph \(G\) with \(n\ge1\) vertices. Both are simple, undirected, unweighted and explicitly encoded by binary adjacency matrices. Let \(L\) be their combined encoding length. The required exact integer output is
\[
\#\mathrm{Hom}(H,G)=|\{\phi:V(H)\to V(G):\{u,v\}\in E(H)\Rightarrow\{\phi(u),\phi(v)\}\in E(G)\}|,
\]
written in binary. The maps need not be injective, and nonedges need not be preserved. Vertices are labeled for counting maps; there is no division by an automorphism count. There are no colors or prescribed vertex images. The class \(\mathcal C\) is fixed, not part of each input; membership must be decidable by some halting algorithm and preserved under graph isomorphisms. Correctness is required on the promise \(H\in\mathcal C\).

The degeneracy \(d(G)\) is the smallest nonnegative integer \(d\) such that every nonempty induced subgraph of \(G\) contains a vertex of degree at most \(d\). Equivalently, \(G\) has an acyclic orientation with maximum outdegree at most \(d\). The parameter is \(q=k+d(G)\). Degeneracy is not fixed to one universal constant: the parameter-dependent factor may depend on its value as well as on \(k\). No orientation or decomposition is supplied as advice.

For a directed acyclic orientation \(D\) of \(H\) and a set \(B\subseteq V(H)\), let \(R_D(B)\) be all vertices reachable from a member of \(B\), allowing paths of length zero. A generalized DAG-tree decomposition is a finite nonempty tree with a bag \(B_t\subseteq V(H)\) at each tree node \(t\), such that
\[
\bigcup_t R_D(B_t)=V(H)
\]
and, whenever \(t\) lies on the unique tree path between \(s\) and \(u\),
\[
R_D(B_s)\cap R_D(B_u)\subseteq R_D(B_t).
\]
Its width is \(\max_t|B_t|\). Let \(\tau(D)\) be the minimum width over all such decompositions and \(\tau_1(H)=\max_D\tau(D)\), where the maximum ranges over all acyclic orientations of \(H\). A one-bag decomposition always exists. A root may be chosen arbitrarily without changing the conditions. Bags may contain any vertices, not just vertices of indegree zero: this is Definition 24 in the full source. The older source-only-bag definition and the unrelated directed graph parameter called DAG-width are not substituted here.

Fixed-parameter tractability means that some deterministic multitape Turing machine outputs the exact count on every promised input in time \(f(q)(L+2)^b\), for a computable \(f:\mathbb N\to\mathbb N_{\ge1}\) and fixed integer \(b\). The program, \(f\) and \(b\) may depend on \(\mathcal C\); \(b\) cannot depend on \(H,G,q\). There is no imposed growth bound on \(f\).

For this question, \(\#\mathsf W[1]\)-hardness is specified directly by a reduction from counting cliques. On input a finite simple graph \(F\) and positive integer \(r\), a deterministic oracle Turing machine must output the number of \(r\)-element vertex subsets inducing a clique. It may adaptively query exact values \(\#\mathrm{Hom}(H',G')\), but each query must satisfy \(H'\in\mathcal C\) and \(|V(H')|+d(G')\le g(r)\), for a computable function \(g\). All local work, query writing, integer operations and reading oracle answers must take at most \(f'(r)(L_F+2)^{b'}\) bit steps for some computable \(f'\) and constant \(b'\); an oracle invocation itself costs one step. The oracle answers are binary exact counts. The reduction may depend on \(\mathcal C\), but is one uniform finite program for all \(F,r\). It has no other oracles or advice.

The statement asks for algorithms and reductions, without assuming a complexity-class separation. The two labels are not asserted to be disjoint if parameterized counting classes collapse. Under their usual separation hypothesis, the dichotomy would characterize precisely the tractable pattern classes. No uniform procedure taking a description of \(\mathcal C\) and deciding whether its widths are bounded is requested.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof or refutation of the stated dichotomy, using the specified generalized width and joint parameter. A positive answer must establish the hard direction for every computable pattern class of unbounded width, with a valid parameter-bounded reduction. Hardness for some unbounded-width family, or a classification of linear time instead of FPT, is insufficient.',
 why='This would identify the structural boundary of exact homomorphism counting when the host is sparse in the degeneracy sense. It would extend known classifications for subgraph and induced-subgraph counting and link acyclic-orientation width to parameterized counting hardness.',
 importance=dict(score=84,method='editorial',reason='A general structural dichotomy for a central counting problem on sparse hosts, with a clear known tractable direction and a substantial missing universal hardness direction.'),
 source_formulation=dict(text='The source asks for an explicit FPT-versus-#W[1] criterion and discusses DAG-treewidth as a possible boundary, related to an induced-grid-minor conjecture. This card selects the DAG-treewidth dichotomy using the generalized width of the full version. That was the announced recommendation after an optional scope question remained unanswered; no user confirmation is inferred.',caption='FOCS 2021 §VI Open Problem 1; full version §1.5 p.10, Definition 24 and equation (7) p.14.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Exact and Approximate Pattern Counting in Degenerate Graphs: New Algorithms, Hardness Results, and Complexity Dichotomies','Marco Bressan; Marc Roth',2021,'https://doi.org/10.1109/FOCS52979.2021.00036','§VI Open Problem 1, proceedings p.283'),ref('full','Exact and Approximate Pattern Counting in Degenerate Graphs: New Algorithms, Hardness Results, and Complexity Dichotomies — full version','Marco Bressan; Marc Roth',2021,'https://arxiv.org/abs/2103.05588','Version 2, June 2021; §1.5 p.10; counting reductions p.13; Definition 24 and equation (7) p.14; §6.2.2 Definition 55 p.32')],
 context_blocks=[block('The paper completely classifies exact subgraph and induced-subgraph counting under its stated assumptions, while leaving the analogous homomorphism classification open.'),block('Bounded generalized DAG-treewidth yields an FPT upper bound. The hardness side is established for classes with unbounded induced grid minors. Equating these structural boundaries would give the proposed criterion, but that equivalence is not assumed by the card.','full'),block('The full version explicitly distinguishes generalized decompositions, whose bags may contain arbitrary vertices, from the older bags-of-sources convention. The card follows the generalized definition consistently.','full'),block('A dichotomy for near-linear host-graph time is a different threshold: polynomial exponents larger than one can still give FPT algorithms. Such fine-grained results do not automatically establish the present class-wide FPT criterion.','primary')],
 progress=[progress('2021','The paper identifies homomorphism counting as the remaining exact-counting classification and records the DAG-treewidth candidate.')],
),['Selected the source-motivated DAG-treewidth criterion as an announced editorial default.','Defined generalized reachability-bag decompositions, all acyclic orientations and the joint pattern-plus-degeneracy parameter.','Specified exact uncolored noninjective homomorphism counting and computable pattern classes.','Defined #W[1]-hardness by an explicit parameterized counting-clique oracle reduction without assuming a separation.'],['Read the full FOCS 2021 Open Problem 1 discussion.','Read full-version §1.5, parameterized Turing reductions, Definition 24/equation (7), and the comparison with Definition 55.','Checked later primary-source results on linear and subquadratic homomorphism counting through 18 September 2026; no class-wide resolution of this generalized-width FPT candidate was verified.'], 'Source-open as the candidate boundary discussed in the 2021 source, with the exact generalized-width dichotomy selected editorially after an unanswered optional question. Bounded checks through 18 September 2026 found no verified resolution. Later linear-time dichotomies concern a different resource threshold.',summary=['A homomorphism maps pattern vertices to host vertices while preserving every edge.','The problem asks for the exact number of these maps when the host has small degeneracy.','The joint parameter is pattern size plus host degeneracy.','The candidate criterion is bounded generalized DAG-treewidth across the permitted patterns.','The missing direction would make every computable class with unbounded width hard for parameterized counting.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
