"""Fix the seed saving and gate-count target for depth-two threshold PRGs."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-3958';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='One-bit-stretch PRGs for depth-two threshold circuits with superlinear gate count',
 status='source_open',criterion='construction',question_type='yes_no',
 formal=r'''Do there exist a rational constant \(\delta\in(0,1)\), positive integers \(a,K,n_0\), and one deterministic algorithm \(G\) such that, for every integer \(n\ge n_0\), the map
\[
G_n:\{0,1\}^{n-1}\longrightarrow\{0,1\}^n,\qquad G_n(s)=G(1^n,s),
\]
is computed in at most \(K(n+2)^a\) bit operations and, for every depth-at-most-two linear-threshold circuit \(C\) on \(n\) input bits with at most \(\lfloor n^{1+\delta}\rfloor\) gates,
\[
\left|\Pr[C(G_n(U_{n-1}))=1]-\Pr[C(U_n)=1]\right|\le\frac1{10}?
\]
Here \(U_j\) is the uniform distribution on \(j\) independent fair bits. The size bound counts gates, with no separate restriction on their fan-in or the number of wires.''',
 definitions=r'''A linear-threshold gate with Boolean inputs \(z_1,\ldots,z_t\) computes \(1\) exactly when \(\sum_{i=1}^t w_i z_i\ge\theta\), where the weights \(w_i\) and threshold \(\theta\) are arbitrary real numbers. A circuit is a finite directed acyclic graph with \(n\) designated input nodes, threshold gates and one designated Boolean output. Every input-to-output path contains at most two gates. The output may also be an input or a constant, and constant gates are permitted. Arbitrary fan-out and connections from inputs directly to the output gate are allowed. Input nodes and wires are not gates; the output gate, when present, is counted. Circuit weights may depend on \(n\) and on the particular circuit. No uniformity or bit-length bound is imposed on this test class.

The generator is a single finite deterministic multitape Turing-machine program, with unary \(n\) and the explicit seed as input. Its running time includes writing all \(n\) output bits; no advice, oracle, arbitrary-real operation, preprocessing depending on \(n\), or extra random bits are allowed. Its output distribution is induced solely by the uniform seed. The circuit is not input to the generator: the same distribution must fool every circuit of the stated size simultaneously. Quantifying over arbitrary real gate descriptions therefore does not give the generator a real-arithmetic resource.

The constants and program are independent of \(n\). The seed is exactly \(n-1\) bits; any uniformly computable generator using fewer bits can ignore padding bits, so this captures a saving of at least one bit. The asymptotic cutoff avoids irrelevant small lengths. The gate exponent improvement \(\delta>0\) is fixed, rather than a quantity tending to zero. A circuit with this many gates can have on the order of \(n^{2+\delta}\) input wires, so an upper bound allowing only slightly superlinear wires is not the same target.

This is an unconditional existence question for a standard pseudorandom generator with a genuine probability distribution. A weighted pseudodistribution, a circuit-dependent acceptance estimator, an expected-time sampler, or a conditional construction under an unproved hardness hypothesis does not establish the displayed statement.''',
 answer_criterion='Give a complete mathematically correct Lean-checked construction and proof of the displayed generator guarantee, or a complete Lean-checked refutation of its existence. Verify uniform polynomial bit time, a fixed positive superlinear gate exponent, the one-bit seed saving and the worst-circuit error bound. A generator for a smaller wire-bounded class or an exponential-time acceptance estimator is insufficient.',
 why='Depth-two threshold circuits are a central frontier between individually tractable threshold gates and powerful shallow computation. Fooling a superlinear number of unrestricted-fan-in gates would address a gate-complexity barrier not covered by current sparse-wire derandomization.',
 importance=dict(score=85,method='editorial',reason='A standard shallow-circuit derandomization barrier with a consequential gate-versus-wire distinction; the weak seed-saving target still tests uniform pseudorandomness against a substantial circuit class.'),
 source_formulation=dict(text='The source asks for a nontrivial PRG for depth-two LTF circuits with a superlinear number of gates. The exact saving n−1, constant error 1/10 and fixed gate exponent 1+delta are an announced editorial specialization after an unanswered optional question; the source does not specify these thresholds.',caption='Kabanets–Lu, §6, p.46:13.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Satisfiability and Derandomization for Small Polynomial Threshold Circuits','Valentine Kabanets; Zhenjian Lu',2018,'https://doi.org/10.4230/LIPIcs.APPROX-RANDOM.2018.46','Theorem 4 p.46:5; §6 p.46:13'),ref('wires','Fooling Constant-Depth Threshold Circuits','Pooya Hatami; William M. Hoza; Avishay Tal; Roei Tell',2021,'https://ieee-focs.org/FOCS-2021-Papers/pdfs/FOCS2021-5stbVHiOp5jRHWlSl41FkR/205500a104/205500a104.pdf','Abstract, Theorem I.1 and related-work discussion p.112'),ref('recent','Super-quadratic Lower Bounds for Depth-2 Linear Threshold Circuits','Lijie Chen; Avishay Tal; Yichuan Wang',2026,'https://eccc.weizmann.ac.il/report/2026/039/','14 March 2026 full version, abstract and introduction')],
 context_blocks=[block('The 2018 PRG theorem handles a sublinear number of polynomial-threshold gates, while its final question explicitly asks for superlinear gate count at depth two.'),block('The 2021 generator allows a slightly superlinear number of wires at any fixed depth. Its comparison with earlier depth-two work also states a wire bound. Those theorems do not automatically cover every circuit in the present gate-bounded class.','wires'),block('The March 2026 work improves gate lower bounds using a faster-than-exhaustive acceptance estimator. Its hard function lies in exponential time with an NP oracle. Neither that lower bound nor the estimator supplies the uniform polynomial-time generator required here.','recent')],
 progress=[progress('2018','The source poses the superlinear-gate PRG question.'),progress('2021','A PRG for superlinear wire count is obtained.','wires'),progress('2026-03','New gate lower bounds and acceptance-estimation algorithms are announced, with different resources from this generator target.','recent')],
),['Made nontriviality a one-bit saving with error 1/10 and polynomial bit time as an announced, unconfirmed editorial default.','Specified arbitrary real threshold functions, two layers, gate counting and unrestricted wires.','Separated circuit-independent PRGs from acceptance estimation and wire-bounded results.','Individually assessed importance and supplied a complete Lean-checked acceptance criterion.'],['Read the 2018 theorem and complete §6 open-problem paragraph.','Read the 2021 abstract, main wire-bounded theorem and depth-two related-work comparison.','Checked the current ECCC 2026/039 report and the saved full text introduction; its lower-bound and counting resources differ from this target.','Bounded searches through 18 September 2026 found no matching resolution.'], 'Source-open in the 2018 problem statement. Bounded primary-source checks through 18 September 2026 did not locate a resolution of the selected one-bit-stretch, superlinear-gate target. The exact quantitative specialization is editorial, not a verbatim conjecture; sparse-wire PRGs and the 2026 acceptance estimator are distinct results.',summary=['The circuit class has at most two layers of gates that compare a weighted sum against a threshold.','The question allows a fixed superlinear number of gates with arbitrary real weights and unrestricted fan-in.','One uniform polynomial-time generator must expand n−1 random bits into n bits.','Every circuit in the class must distinguish that output from uniform with advantage at most one tenth.','Known generators for restricted wire count and exponential-time acceptance estimators do not by themselves meet this requirement.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
