"""Archive the established general-circuit factoring-to-PIT reduction."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-6914';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Deterministic multivariate factorization from polynomial identity testing',
 status='resolved',criterion='resources',question_type='yes_no',
 formal=r'''Does complete factorization of a multivariate polynomial over \(\mathbb Q\), given by its arithmetic circuit, admit a uniform deterministic polynomial-cost reduction to polynomial identity testing and dense univariate factorization over \(\mathbb Q\)?

More precisely, are there fixed \(K>0\), \(a\in\mathbb N\), and one deterministic oracle algorithm which, on every nonzero polynomial \(f\) given by a size-\(s\) circuit in \(n\) variables with a supplied bound \(D\) on every gate's total degree, outputs
\[
f=c\prod_{i=1}^{r}g_i^{e_i}
\]
within \(K(s+n+D+2)^a\) operations in the exact arithmetic oracle model below? Here \(c\in\mathbb Q\setminus\{0\}\), the \(g_i\) are pairwise nonassociate nonconstant irreducible polynomials over \(\mathbb Q\), each returned as an arithmetic circuit, and the positive integers \(e_i\) are returned in binary. The same polynomial bound must cover the total output circuit size, all query circuit sizes and degree bounds, all univariate query degrees, and the number of oracle calls.''',
 definitions=r'''The input and output polynomials have commuting variables. A circuit is a finite directed acyclic graph whose input gates are variables or rational constants and whose internal gates perform binary addition or multiplication. One gate is designated as output. Values can be reused arbitrarily, and size counts all gates, including input gates. Subtraction is available using the constant \(-1\). There are no division gates in the input or output circuits, and equality means exact formal coefficient equality. The supplied \(D\ge0\) bounds the actual degree at every input-circuit gate, including its output; the zero polynomial at a gate satisfies every nonnegative bound. The reduction need only be correct on inputs satisfying this promise. No depth or multilinearity restriction is imposed.

The polynomial identity-testing oracle takes a complete rational arithmetic circuit and answers whether its formal output is zero. Its answer is always exact. The univariate factorization oracle takes the explicitly listed coefficients of a nonzero polynomial in \(\mathbb Q[t]\) and returns its nonzero scalar factor and all distinct monic irreducible factors with their multiplicities, in dense coefficient representation. It factors only polynomials in one variable; multivariate factorization is the task to be reduced. The algorithm must work with any ordering of the returned factors. No multivariate irreducibility, root-selection or factorization oracle is supplied.

For the reduction cost, exact rational constants are field atoms. One rational addition, subtraction, multiplication, division by a nonzero element, equality test, copy, read or write costs one operation. Each ordinary control-bit operation, branch and addressed-register access also costs one operation; addresses and integer parameters are manipulated as binary strings with this bit cost. Creating, reading or writing each coefficient atom or circuit gate is charged. Each oracle invocation costs one additional operation, but constructing its full query and processing its answer are charged separately. The polynomial bounds on query degrees and lengths prevent a single query from concealing an exponentially large dense instance. Oracle internal work and rational numerator/denominator bit lengths are outside this arithmetic reduction cost.

Uniformity means a single finite program with finitely many fixed rational constants and no input-length advice. Formal polynomials are represented by their gate lists; they cannot be inspected as expanded coefficient tables for free. The reduction is deterministic and has no random-bit source. This statement isolates the multivariate reduction after the usual univariate factoring operation is provided. It is not an assertion of polynomial bit time for arbitrary atom-valued rational circuits, nor an assertion that unconditional deterministic PIT has been obtained.

A nonconstant polynomial is irreducible over \(\mathbb Q\) if it is not the product of two nonconstant rational polynomials. Two factors are associates if they differ by a nonzero rational scalar. The representation need not choose a canonical normalization for multivariate factors. If \(f\) is a nonzero constant, \(r=0\) and the empty product is 1. For a nonconstant input, \(r\le D\) and \(\sum_i e_i\deg(g_i)\le D\). Zero has no factorization of the stated form and is excluded by the input promise.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof of this reduction, including termination, oracle-query bounds, exact irreducibility and completeness of the returned factorization, multiplicities, and total arithmetic and control cost. The recorded mathematical answer is affirmative. Archival records the known theorem; it does not claim that its Lean formalization has been supplied. Existence of small factor circuits alone is insufficient: the reduction must construct them deterministically with the stated oracles. A randomized factoring algorithm or a reduction only for multilinear input polynomials does not establish the full historical target.''',
 why='The result identifies the additional difficulty of multivariate factorization with polynomial identity testing once univariate factorization is available. It resolves the historical proposed connection, while the unconditional derandomization of general PIT remains a separate research question.',
 importance=dict(score=86,method='editorial',reason='A fundamental established equivalence between two central algebraic derandomization tasks; the historical implication is resolved rather than a remaining open target.'),
 source_formulation=dict(text='The 2010 survey asks whether derandomizing PIT implies derandomization of general polynomial factorization, beyond its variable-disjoint decomposition results. The card preserves that implication as a white-box reduction over Q with the ordinary univariate factoring subroutine made explicit.',caption='Shpilka–Yehudayoff, §4.9.1, printed pp.91–92, and the concluding paragraph of Chapter 4, printed p.95. The import’s “p.100” refers to PDF pagination for the latter passage.',citation='primary',format='editorial_paraphrase'),
 references=[
 ref('primary','Arithmetic Circuits: A Survey of Recent Results and Open Questions','Amir Shpilka; Amir Yehudayoff',2010,'https://www.cs.tau.ac.il/~shpilka/publications/SY10.pdf','§4.9.1, printed pp.91–92; Chapter 4 concluding factorization paragraph, printed p.95 (PDF p.100)'),
 ref('solution','Equivalence of Polynomial Identity Testing and Deterministic Multivariate Polynomial Factorization','Swastik Kopparty; Shubhangi Saraf; Amir Shpilka',2014,'https://sites.math.rutgers.edu/~ss1984/PITfactoring.pdf','Author manuscript, abstract and Introduction pp.1–2; §1.1 Theorem 1 and rational/finite-field qualifications p.3; §1.2 reduction outline pp.4–6; CCC 2014, journal version Computational Complexity 2015'),
 ref('current','A primer on the closure of algebraic complexity classes under factoring','C. S. Bhargav; Prateek Dwivedi; Nitin Saxena',2026,'https://eccc.weizmann.ac.il/report/2025/083/revision/1/','Revision of 12 June 2026, §3.1, printed pp.11–12: the general white-box and black-box equivalence'),
 ],
 context_blocks=[
 block('Variable-disjoint decomposition is easier to state because different factors use disjoint variable sets. The historical question was whether the PIT connection extends to arbitrary factors with overlapping variables.'),
 block('Kopparty, Saraf and Shpilka give that general reduction. The white-box direction constructs circuits for the factors from a complete circuit description using identity tests and univariate factoring, rather than merely asserting that small factor circuits exist.','solution'),
 block('The rational-field version avoids positive-characteristic inseparability. The same paper explicitly qualifies its finite-field output by powers of the characteristic and includes a characteristic-dependent cost, so it must not be cited as unrestricted polynomial-bit-time finite-field factoring.','solution'),
 block('The June 2026 survey continues to present the general PIT/factorization equivalence as an established result. Its separate factor-closure questions for restricted models and positive characteristic are not the historical implication archived here.','current'),
 block('The affirmative reduction is conditional on access to exact identity testing. It does not supply an unconditional deterministic polynomial-time identity test for general circuits.','current'),
 ],
 progress=[progress('2010','The survey raises extension from the known decomposition/PIT connection to general factorization.'),progress('2014','The general white-box and black-box reductions are given by Kopparty, Saraf and Shpilka; a journal version follows in 2015.','solution'),progress('2026-06-12','The revised factorization survey presents the equivalence as established.','current')],
),[
 'Separated the source’s reduction question from the still-open task of unconditional general derandomization.',
 'After the optional choice remained unanswered, announced and applied the recommended archival default; no user confirmation is inferred.',
 'Specified rational commuting circuits, a supplied gate-degree bound, full factor-circuit output and multiplicities.',
 'Made the univariate factorization primitive and exact arithmetic reduction cost explicit, avoiding a hidden claim about rational atom bit lengths or finite-field polynomial-log-characteristic factoring.',
 'Read the main affirmative theorem and the current June 2026 survey confirmation, then archived the preserved historical target as resolved.',
 'Individually assessed historical importance and preserved a complete Lean proof criterion without claiming an existing formalization.',
],[
 'Read Shpilka–Yehudayoff §4.9.1 printed pp.91–92, including the variable-disjoint decomposition distinction, and the final paragraph of Chapter 4 printed p.95/PDF p.100 asking whether PIT derandomization suffices for general polynomial factorization.',
 'Read Kopparty–Saraf–Shpilka author manuscript abstract, Introduction pp.1–2 and §1.1 Theorem 1 p.3, including the rational constant-complexity parameter and positive-characteristic powered-factor qualification. Read §1.2 pp.4–6 for the factoring reduction and univariate subroutine framework. This card records the exact arithmetic oracle reduction, not a stronger unqualified rational bit-time claim.',
 'Checked the authors’ publication listing: CCC 2014 preliminary version and Computational Complexity 2015 journal version. A search snippet about a flawed Theorem 5.3 on the same listing belongs to a different 2009 reconstruction paper, not this equivalence theorem.',
 'Read the 12 June 2026 revision of Bhargav–Dwivedi–Saxena, §3.1 printed pp.11–12. It explicitly attributes the general white-box and black-box equivalence to Kopparty–Saraf–Shpilka. This supports the resolved status as of the 17 September 2026 review.',
], 'Resolved affirmatively by Kopparty–Saraf–Shpilka (CCC 2014; Computational Complexity 2015): deterministic multivariate circuit factorization reduces to deterministic PIT with the ordinary univariate factoring subroutine. The historical implication is archived, with rational exact arithmetic and oracle qualifications explicit. The June 2026 survey confirms the established equivalence. This does not assert unconditional PIT derandomization, unrestricted finite-field polynomial-bit-time factoring, or a completed Lean formalization.',summary=[
 'The historical question asks whether identity testing suffices for general multivariate factorization.',
 'Its precise version uses full rational circuit descriptions and returns circuits for all irreducible factors with multiplicities.',
 'A deterministic polynomial-cost reduction may query exact identity testing and dense univariate factorization.',
 'Kopparty, Saraf and Shpilka established this reduction, so the implication is archived as resolved.',
 'The complete Lean-checked reduction remains the stated proof criterion, and no unconditional PIT algorithm is claimed.',
],expected_sha256=claim['input_sha256'],claim_token=claim['token'],archive_reason='The historical general-circuit factoring-from-PIT implication is affirmative by Kopparty–Saraf–Shpilka (CCC 2014; Computational Complexity 2015), confirmed in the June 2026 factoring survey. Preserve the precise rational exact-arithmetic reduction, including the univariate factoring subroutine, as a resolved record; do not replace it by the separate unconditional derandomization problem.')
