"""Retain the all-constant-factor ETH target after the 2026 partial resolution."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-1945';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Tight ETH lower bounds for binary Nearest Codeword at every constant factor',
 status='source_open',criterion='assumptions',question_type='yes_no',
 formal=r'''Does the deterministic Exponential Time Hypothesis imply the following statement? For every fixed rational \(\gamma>1\), there do not exist computable functions \(f:\mathbb N_{\ge1}\to\mathbb N_{\ge1}\) and \(g:\mathbb N_{\ge1}\to\mathbb Q_{\ge0}\) with \(\lim_{k\to\infty}g(k)/k=0\), and a uniform deterministic algorithm that solves \(\gamma\)-Gap-\(k\)-Nearest Codeword over \(\mathbb F_2\) in at most
\[
f(k)(L+2)^{g(k)}
\]
bit operations on every valid encoded instance of length \(L\)? The parameter \(k\) bounds the number of erroneous coordinates, and the two promised cases are distance at most \(k\) versus distance greater than \(\gamma k\).''',
 definitions=r'''An instance consists of a matrix \(A\in\mathbb F_2^{N\times M}\), a target \(t\in\mathbb F_2^N\), and an integer \(1\le k\le N\), where \(N,M\ge1\). All matrix entries and all target coordinates are explicitly supplied as bits, together with self-delimiting binary encodings of the three integers. Let \(L\) be the total bit length of this encoding. The matrix may have dependent or zero columns. The represented binary linear code is \(\mathcal C_A=\{Ax:x\in\mathbb F_2^M\}\), with addition and multiplication modulo two. Define
\[
d(A,t)=\min_{x\in\mathbb F_2^M}|\{i\in[N]:(Ax)_i\ne t_i\}|.
\]
A yes instance has \(d(A,t)\le k\); a no instance has \(d(A,t)>\gamma k\). Inputs with \(k<d(A,t)\le\gamma k\) violate the gap promise. The algorithm must halt within its bound on all valid encodings and answer correctly on every promised instance; its answer in the gap is unrestricted. This is a decision problem, so it need not output a codeword or its coefficient vector.

For this card, deterministic ETH means that there is a real constant \(\eta>0\) for which no deterministic algorithm decides satisfiability of all Boolean 3-CNF formulas with \(v\) variables in time \(O(2^{\eta v}(L_F+2)^b)\) for any fixed \(b\), where \(L_F\) is the explicit formula encoding length. Each clause has at most three literals, a literal is a variable or its negation, and the input supplies the full clause list. The running time is measured on a deterministic multitape Turing machine. This is the gap-free hypothesis about exact satisfiability, not Gap-ETH about distinguishing satisfiable formulas from formulas with a constant unsatisfied fraction.

The coding algorithm uses the same deterministic bit model, with no advice, oracle or random bits. For each fixed \(\gamma\), its program and functions \(f,g\) may be different. No upper growth bound is imposed on computable \(f\). The little-o condition requires \(g(k)/k\) to tend to zero; it does not mean a small fixed positive multiple of \(k\). Taking rational factors loses no all-constant-factor scope: a rational factor larger than any given real factor gives a subpromise that an algorithm for the smaller factor must also solve. The field, input model and deterministic assumption are fixed parts of the target.

The requested theorem is the implication from ETH to these lower bounds for every constant approximation factor. It is not an unconditional impossibility claim, and it does not require lower bounds for Minimum Distance or lattice problems in addition to Nearest Codeword.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof or refutation of the displayed implication. A positive answer must rule out every computable parameter prefactor and every sublinear parameter exponent for each fixed constant factor, using deterministic ETH rather than Gap-ETH. A bound only for some constant factor, or an exponent k^epsilon with epsilon below one, does not settle the selected target.',
 why='This asks whether ordinary satisfiability hardness already yields the tight parameter dependence for arbitrarily coarse constant-factor decoding. It would close a specific gap between ETH and Gap-ETH in the fine-grained theory of error-correcting codes.',
 importance=dict(score=81,method='editorial',reason='A sharp parameterized approximation barrier connecting gap-free satisfiability assumptions to decoding; the all-factor scope remains substantive after the 2026 fixed-factor advance.'),
 source_formulation=dict(text='Open Problem 34 asks for n^{o(k)} approximation lower bounds under assumptions weaker than Gap-ETH. This card selects deterministic ETH, the binary Nearest Codeword problem, and every fixed constant factor. These were announced as the recommendation after an unanswered optional scope question. The 2026 paper explicitly retains the all-factor ETH extension as a future direction.',caption='Li–Lin–Liu, Open Problem 34 p.107:17; Gupta–Lin–Zheng, Future Directions p.4.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Improved Lower Bounds for Approximating Parameterized Nearest Codeword and Related Problems Under ETH','Shuangle Li; Bingkai Lin; Yuwei Liu',2024,'https://doi.org/10.4230/LIPIcs.ICALP.2024.107','Corollaries 2–4 p.107:3; Open Problem 34 p.107:17'),ref('recent','Tight Lower Bound for Approximating Parametrized Maximum Likelihood Decoding under ETH','Rishav Gupta; Bingkai Lin; Xin Zheng',2026,'https://arxiv.org/abs/2605.08797','Version 1, 9 May 2026; Theorem 1.1 p.3, Future Directions p.4, Definitions 2.6 and 2.8 pp.5–6, Corollary 3.9 p.12')],
 context_blocks=[block('The 2024 work obtains ETH-based sublinear powers of k in the exponent through a polynomial parameter increase, whereas the stronger Gap-ETH assumption had yielded the desired linear scale for every constant factor.'),block('The May 2026 preprint gives the linear-exponent barrier for some constant approximation factor via a deterministic reduction. Its future-directions paragraph explicitly asks to extend the result to every constant factor under ETH. The different factor quantifier prevents archiving the entire original request as solved.','recent'),block('The preprint defines Nearest Codeword by a generator matrix and Hamming distance. Its maximum-likelihood-decoding formulation instead uses a parity-check equation; the card fixes the generator-matrix interface to avoid conflating the two input descriptions.','recent')],
 progress=[progress('2024','The source asks to recover the tight parameter exponent from a weaker, gap-free assumption.'),progress('2026-05-09','A preprint obtains the tight scale for some constant factor and expressly leaves arbitrary constant factors as a further target.','recent')],
),['Selected binary Nearest Codeword and deterministic ETH, with every constant factor retained, as the announced editorial default.','Defined the gap promise, generator matrix, Hamming metric, explicit bit length and computable parameter dependence.','Distinguished every factor from the May 2026 some-factor result.','Individually assessed significance and required a complete Lean-checked implication.'],['Read 2024 Corollaries 2–4 and the complete Open Problem 34 discussion.','Read the May 2026 preprint introduction, definitions of ETH and Nearest Codeword, Future Directions and Corollary 3.9.','Checked its current arXiv record and bounded later searches through 18 September 2026; no verified all-factor resolution was located.'], 'Source-open for the all-constant-factor direction: the May 2026 preprint explicitly retains it after proving a some-factor result. Bounded checks through 18 September 2026 found no matching resolution. The binary deterministic-ETH specialization was announced after an unanswered optional question and is not recorded as a user confirmation.',summary=['Nearest Codeword asks how many bits separate a target from the nearest word in a binary linear code.','The parameter k is the promised upper bound on that distance in yes instances.','The target excludes time f(k) times an input-size power whose exponent grows slower than k.','This lower bound must follow from ordinary deterministic ETH for every fixed approximation factor greater than one.','A May 2026 result handles some constant factor, while its stated all-factor extension remains the selected question.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
