"""Select fixed-parameter coloring of induced-P5-free graphs."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0597';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Fixed-parameter tractability of coloring graphs with no induced P5',
 status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Do there exist a computable function \(f:\mathbb N_{\ge1}\to\mathbb N_{\ge1}\), an integer constant \(C\ge1\), and one deterministic algorithm \(A\) which, for every finite simple undirected graph \(G\) on \(n\ge1\) vertices and every integer \(1\le k\le n\), halts in at most
\[
f(k)(n+2)^C
\]
bit operations and, whenever \(G\) contains no induced path on five vertices, decides correctly whether \(G\) has a proper coloring using at most \(k\) colors?''',
 definitions=r'''The graph has vertex set \([n]=\{1,\ldots,n\}\), no loops and no multiple edges. It is given by its full symmetric zero-diagonal Boolean adjacency matrix, together with binary encodings of \(n\) and \(k\). A proper \(k\)-coloring is a map \(c:[n]\to\{1,\ldots,k\}\) with \(c(u)\ne c(v)\) for every edge \(\{u,v\}\). Colors need not all be used. The algorithm returns a decision bit, not necessarily a coloring.

An induced \(P_5\) is an ordered sequence of five distinct vertices \(v_1,\ldots,v_5\) such that, among these vertices, the edges are exactly \(\{v_i,v_{i+1}\}\) for \(1\le i<5\). All other pairs among the five vertices must be nonedges. The promise excludes this induced configuration; it does not exclude every five-vertex path as a noninduced subgraph. Arbitrarily large cliques, for example, obey the promise.

Measure running time by steps of a classical deterministic multitape Turing machine on the explicit binary input, including input access and output. The program is uniform for all \(n,k\). The constant \(C\) is independent of both parameters. The arbitrary computable prefactor \(f(k)\) is allowed to grow faster than any specified elementary function; the target places no further bound on it. The program receives no advice, oracle or structural decomposition. It must halt within the stated bound on all valid graph inputs, but its output on graphs violating the promise is unrestricted. One can instead check the promise by enumerating five vertices, at a polynomial cost absorbed in \(C\).

Restricting to \(1\le k\le n\) removes trivial encodings: every \(n\)-vertex graph can be colored with \(n\) colors. Empty graphs and zero-color conventions are not part of the nontrivial domain. The requested bound is fixed-parameter tractability with parameter \(k\). A family of bounds \(n^{h(k)}\), even for a computable function \(h\), does not meet it. The question concerns ordinary coloring with a common color set, not list coloring, precoloring extension or choosability.

The target is the unconditional existence of such an algorithm. A hardness classification under an additional separation hypothesis is useful context, but alone does not prove unconditional nonexistence.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof or refutation of this algorithm-existence statement. A positive answer must supply one uniform algorithm, a computable parameter dependence and a graph-size exponent independent of k, with correctness on every P5-free input. Polynomial-time algorithms separately for each fixed k, or algorithms requiring additional forbidden subgraphs, are insufficient.',
 why='Coloring on P5-free graphs is tractable for each fixed number of colors, but the known polynomial exponent can depend on that number. Removing that dependence would distinguish structural fixed-parameter tractability from the weaker fixed-k phenomenon in a basic hereditary graph class.',
 source_formulation=dict(text='The 2019 seminar entry contains separate questions about 3-coloring as the forbidden-path length varies and k-coloring on P5-free graphs as the color count varies. This card selects the latter, following the announced recommendation after an optional question remained unanswered. The same target is stated again in the 2022 seminar report.',caption='Golovach, Seminar 19271 §4.1 p.138; Seminar 22481 §4.2 p.121.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Graph Colouring: from Structure to Algorithms (Dagstuhl Seminar 19271)','Petr A. Golovach, open-problem contribution; Maria Chudnovsky, Daniel Paulusma and Oliver Schaudt, report editors',2019,'https://doi.org/10.4230/DagRep.9.6.125','§4.1 p.138 (standalone PDF p.14)'),ref('later','Vertex Partitioning in Graphs: From Structure to Algorithms (Dagstuhl Seminar 22481)','Petr A. Golovach, open-problem contribution; Maria Chudnovsky, Daniel Král and Daniël Paulusma, report editors',2022,'https://doi.org/10.4230/DagRep.12.11.109','§4.2 p.121 (standalone PDF p.13)')],
 context_blocks=[block('The seminar describes a known polynomial-time algorithm for each fixed k and asks whether the dependence on k can be confined to a multiplicative factor. It separately asks a hardness question for 3-coloring with variable forbidden-path length.'),block('The later seminar repeats the fixed-parameter question and notes that it is also interesting for the smaller class excluding two disjoint induced edges. A result for that subclass does not settle the full P5-free class.','later')],
 progress=[progress('2019','The seminar formulates the fixed-parameter coloring question explicitly.'),progress('2022','The later seminar again records the same question as open.','later')],
),['Selected ordinary k-coloring on induced-P5-free graphs rather than the separate 3-coloring hardness branch.','Specified the explicit graph input, induced exclusion, variable color parameter and uniform deterministic bit model.','Distinguished FPT from XP, ordinary coloring from choosability and unconditional existence from conditional hardness.','Preserved the prior individual importance assessment.'],['Read the complete 2019 §4.1 and its two distinct questions.','Read the complete 2022 §4.2 repetition with the 2K2-free subclass.','Bounded later-work searches through 18 September 2026 found no verified resolution; choosability results concern a different problem.'], 'Source-open in both the 2019 and 2022 seminar reports. Bounded primary-source checks through 18 September 2026 did not find a resolution of the selected P5-free FPT coloring target. The branch selection was an announced editorial default after an unanswered optional question, not a recorded user confirmation.',summary=['A graph is P5-free when no five vertices induce precisely a path.','The input asks whether such a graph can be colored with at most k colors.','The target is one deterministic algorithm with running time f(k) times a polynomial in the graph size.','The polynomial exponent must be independent of the number of colors.','Existing polynomial algorithms for each separately fixed k leave this stronger parameterized question open in the checked sources.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
