"""Specify exact efficient stopping for a uniform mixture of product distributions."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0700';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Exact optimal stopping for mixtures of product distributions',status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Do there exist two uniform deterministic algorithms \(P,E\) and positive integers \(C,a\) with the following property? For every rational mixture-of-scenarios instance \(I\) of binary length \(L\) defined below, \(P(I)\) constructs a binary policy description \(z_I\) in at most \(C(L+2)^a\) bit steps, and \(E(I,z_I,h)\) decides whether to stop at each observed history \(h\) within the same time bound. The resulting stopping time \(\tau\) must satisfy
\[
\mathbb E_I[X_\tau]=\max_{\sigma\text{ an online stopping rule}}\mathbb E_I[X_\sigma].
\]
The equality is exact. All constants, programs and polynomial exponents are independent of the number of scenarios, sequence length, support size and numerical precision.''',
 definitions=r'''An instance specifies integers \(m,n,k\ge1\), distinct nonnegative rational values \(v_1<\cdots<v_k\), and the entire table of nonnegative rational probabilities \(p_{j,t,q}\), for \(j\in[m]\), \(t\in[n]\), \(q\in[k]\), satisfying \(\sum_{q=1}^k p_{j,t,q}=1\). All integers and rational numerators and positive denominators have explicit binary encodings; \(L\) is the length of the whole encoding, including all \(mnk\) table entries. No succinct circuit or sampling oracle replaces this table. Values need not be bounded by a constant, and zero probabilities and the value zero are permitted.

A hidden scenario \(J\) is first drawn uniformly from \([m]\). Conditional on \(J=j\), the variables \(X_1,\ldots,X_n\) are independent, with \(\Pr[X_t=v_q\mid J=j]=p_{j,t,q}\). Hence, for every index sequence \((q_1,\ldots,q_n)\in[k]^n\),
\[
\Pr_I[X_1=v_{q_1},\ldots,X_n=v_{q_n}]=\frac1m\sum_{j=1}^m\prod_{t=1}^n p_{j,t,q_t}.
\]
All parameters and probabilities are known to the decision maker; the drawn scenario is never directly disclosed. Only \(X_t\) is revealed at time \(t\), in the fixed order \(1,\ldots,n\). Its distinct support index \(q_t\) may be used as its encoding. Observations carry no extra scenario label.

After seeing \(X_t\), an online stopping rule either takes that value and terminates or discards it forever and continues. It may not return to an earlier value, reorder observations, make extra probes or select more than one value. It must stop by time \(n\). The class in the maximum includes every deterministic rule assigning stop/continue to every support-index history \((q_1,\ldots,q_t)\), with stop mandatory at \(t=n\), regardless of computation or memory cost. There are finitely many such rules, so the maximum exists. Permitting additional private randomization in this benchmark does not improve its optimum: a distribution over deterministic finite-history rules cannot exceed their largest expected reward. Expectation in the objective is over the hidden scenario and all conditional draws.

The preprocessing algorithm \(P\) receives the full instance before any observation and returns \(z_I\). The evaluation algorithm \(E\) receives \(I,z_I\) and the complete history \(h=(q_1,\ldots,q_t)\), with \(1\le t\le n\), and returns one bit for stop or continue. On length-\(n\) histories it must return stop. Its answers on impossible histories, or histories at which the induced rule has previously stopped, need not be optimal, but its time bound applies to every support-index history. Its induced stopping time is the first position whose answer is stop. The full-history convention permits any polynomial-space memory of past observations by recomputation within the specified evaluation budget.

Both algorithms are deterministic multitape Turing machines, with all preprocessing, input access, binary arithmetic, memory operations and output charged. The description length is bounded by its construction time. The evaluation time is polynomial in \(L\), including reading the history, whose length is itself polynomial in \(L\). An exponentially large explicit policy tree or exponential preprocessing does not meet the target. No unit-cost exact-real operations, advice or external computational oracles are allowed. The requested output is an executable optimal policy, not necessarily the numerical value of its expected reward. The comparator is the best online rule for the same distribution, not the offline maximum \(\max_tX_t\).''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof or refutation of the stated uniform polynomial-bit-time policy-construction and evaluation proposition. A positive answer must achieve exactly the optimal expected online reward for every explicit rational instance. Approximate value computation, approximation to the online optimum, an offline-prophet ratio, or a policy requiring exponential preprocessing does not settle this selected target.',
 why='A small latent scenario model can describe exponentially many observation histories. The question asks whether this compact source of dependence still permits exact efficient decisions, separating concise distribution descriptions from concise optimal policies.',
 source_formulation=dict(text='The source contrasts an easy explicit list of deterministic scenarios with a uniform mixture of product distributions and asks whether an optimal online policy can be computed in polynomial time, followed by a separate approximation question. The selected target keeps exact optimality and specifies polynomial construction and execution in the binary input length. This is the announced editorial recommendation after an unanswered optional choice.',caption='Cristi, Dagstuhl Seminar 25132, §4.2 models (1) and (2), pp.172–173.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Approximation Algorithms for Stochastic Optimization: Hardness of Correlated Prophet Inequality','Andrés Cristi',2025,'https://doi.org/10.4230/DagRep.15.3.159','Seminar 25132, §4.2 pp.172–173; model (2)')],
 context_blocks=[block('For an explicit list of deterministic sequences, only polynomially many observed prefixes need to be considered. The source identifies this as the easy model before asking about independent draws conditional on a hidden scenario.'),block('In the selected mixture model, observations reveal partial information about the hidden scenario. Independence holds conditional on that scenario, not necessarily in the unconditional sequence.'),block('The familiar comparison with an offline prophet is a different performance question. This card concerns the computation needed to match the best online rule with the same information.')],
 progress=[progress('2025','The seminar source poses exact efficient policy computation for model (2), and asks about approximation if the exact goal is intractable.')],
),['Recovered the uniform hidden-scenario mixture and retained exact optimal online reward as the announced editorial default.','Specified the shared finite rational support, full probability table and complete generative distribution.','Defined policy construction, finite-history execution, stopping conventions and worst-case bit cost.','Separated online optimum from the offline prophet and from the source’s approximation follow-up.'],['Read both scenario models in §4.2 pp.172–173 of the 2025 seminar report.','Bounded primary-source checks through 18 September 2026 found no verified resolution for this particular mixture representation; general correlated-prophet ratios and Pandora search with choice of probing order were not treated as answers.'], 'Source-open in the 2025 seminar report for a uniform mixture of product distributions. No verified later resolution was found in the bounded review through 18 September 2026. The exact finite-bit policy interface is an announced editorial interpretation; a general hardness claim for a different distribution representation does not establish this one.',summary=['A hidden scenario is selected uniformly before a sequence of values is generated.','Conditional on that scenario the values are independent, and every conditional distribution is explicitly known.','The decision maker observes values in order and must select one when it arrives.','The target asks whether an exactly optimal online stopping rule can be prepared and executed in polynomial bit time.','The benchmark is the best rule with the same online information, rather than an observer who sees the whole future.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
