"""Archive the known conditional numerical precision target for Max Di-Cut."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0088';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='The Max Di-Cut approximation threshold to accuracy 1/100 under Unique Games',
 status='resolved',criterion='tightness',question_type='numerical_value',
 formal=r'''Assuming the Unique Games Conjecture and \(\mathsf{NP}\not\subseteq\mathsf{BPP}\), determine the optimal polynomial-time approximation ratio \(\alpha_{\rm DC}\) for Max Di-Cut with certified absolute error at most \(1/100\). Equivalently, supply a real number \(q\) and prove under these assumptions that
\[
|q-\alpha_{\rm DC}|\le1/100.
\]
The finite weighted graph model, randomized ratio convention and both assumptions are defined below. The requested accuracy is a known conditional target; the exact optimal ratio is not asserted to be known.''',
 definitions=r'''An instance is a finite directed graph on \([n]\), given by an explicit list of ordered pairs of distinct vertices and their nonnegative rational weights in binary. Oppositely directed edges and repeated edges are allowed; repeated edges can equivalently be merged by adding their weights. A cut is a set \(S\subseteq[n]\), encoded by its characteristic bit vector, with value
\[
\operatorname{val}(S)=\sum_{(u,v):u\in S,\ v\notin S}w_{uv},\qquad
\operatorname{OPT}=\max_{S\subseteq[n]}\operatorname{val}(S).
\]
Only edges leaving \(S\) count. All vertices are listed explicitly so that output length is polynomial in the input length \(L\). Zero total edge weight is allowed and makes every cut optimal. This is the rational weighted Max Di-Cut convention used by the cited theorem; unit-weight graphs are included.

A rational \(r\in[0,1]\) is achievable if one uniform randomized multitape Turing machine, with constants \(K,b\), returns a cut on every execution within \(K(L+2)^b\) bit steps and, on every instance, returns a cut of value at least \(r\operatorname{OPT}\) with probability at least \(2/3\). Random bits are independent fair bits; their generation, finite-precision arithmetic and output are charged. There is no real-arithmetic oracle, advice or free preprocessing. The program and constants may depend on \(r\). Define \(\alpha_{\rm DC}\) as the supremum of the achievable rational ratios. It lies in \([0,1]\); the supremum need not itself be achieved.

For the Unique Games Conjecture, a finite instance has a graph, a fixed alphabet \([s]\), nonnegative rational edge weights summing to one and, for each oriented edge \((u,v)\), a permutation \(\pi_{uv}\) of \([s]\), with the reverse permutation its inverse. A labeling \(a:V\to[s]\) satisfies an edge if \(a(v)=\pi_{uv}(a(u))\); its value is the total satisfied weight. Let \(\operatorname{UGval}\) be the maximum value over labelings. The conjecture says that for every pair of positive rational constants \(\eta,\zeta\) with \(\eta+\zeta<1\), some fixed \(s\ge2\) makes distinguishing \(\operatorname{UGval}\ge1-\eta\) from \(\operatorname{UGval}\le\zeta\) NP-hard under deterministic polynomial-time many-one reductions. Concretely, there must be a polynomial-time reduction from Boolean 3-CNF satisfiability preserving these yes and no cases.

The additional assumption \(\mathsf{NP}\not\subseteq\mathsf{BPP}\) means that not every language with polynomial-length, polynomial-time verifiable witnesses has a uniform randomized polynomial-time decision algorithm with error at most \(1/3\) on each input. Equivalently here, Boolean 3-CNF satisfiability has no such algorithm. It is stated separately because a UG-hardness reduction alone does not rule out randomized algorithms if all NP problems were in BPP.

A valid numerical answer may be a rational, a rigorously specified real expression, or an enclosing interval \([\ell,u]\) with \(u-\ell\le1/50\), whose midpoint has the requested error. No time limit is imposed on finding the answer or its certificate. Both bounds must concern the optimal ratio over all algorithms in the given model, rather than just one SDP rounding family. Merely naming the defining supremum again does not give a numerical answer.''',
 answer_criterion='Supply a concrete numerical approximation and a complete mathematically correct Lean-checked proof of absolute error at most 1/100 under the two stated assumptions, or a Lean-checked enclosing interval of width at most 1/50. Justify both the algorithmic lower bound and the conditional upper bound. This archived record does not request an exact threshold or claim that a Lean formalization of the cited proof has already been completed.',
 why='Max Di-Cut is a standard directed constraint-satisfaction problem whose approximation threshold differs from that of undirected Max Cut. Its precise ratio remains interesting, but the benchmark’s one-hundredth numerical tolerance is already covered by a much tighter published interval.',
 source_formulation=dict(text='The source asks for the best polynomial-time approximation ratio and immediately records bounds 0.87446 and 0.87461 under Unique Games. This review applies the catalogue’s numerical accuracy 1/100, uses the cited paper’s weighted finite-input model, and states NP not contained in BPP explicitly for randomized algorithms. Archival of this conditional numerical target was the announced recommendation after an unanswered optional question.',caption='TCS Open Problems, Problem 1; Brakensiek et al., Theorems 1.2–1.3.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Best approximation ratio for Max Di-Cut — TCS Open Problems, Problem 1','TCS Open Problems; contributor kunal',2026,'https://tcsopenproblems.com/problem/1','Question and stated known bounds; posted 15 January 2026'),ref('bounds','Separating MAX 2-AND, MAX DI-CUT and MAX CUT','Joshua Brakensiek; Neng Huang; Aaron Potechin; Uri Zwick',2023,'https://arxiv.org/abs/2212.11191','Version 2, 12 April 2023; Theorems 1.2–1.3; Definitions 2.1–2.5; Theorem 3.1; §4.4.2 proof of Theorem 1.3')],
 context_blocks=[block('The problem page itself records an interval far narrower than one hundredth, while asking for the exact best ratio. The archival decision concerns the selected numerical tolerance, not exact determination.'),block(r'The checked theorems give \(0.87446\le\alpha_{\rm DC}\le0.87461\) under the stated assumptions. Their midpoint \(q=174907/200000=0.874535\) has certified error at most \(15/200000=0.000075<1/100\). Thus the requested conditional accuracy is already known.','bounds'),block('The upper bound follows from UG-hardness, not a restriction on a particular algorithm design. The lower bound uses a distribution of rounding rules certified by interval arithmetic, together with a small probability of independent rounding to handle low-completeness configurations. This review checked the theorem statements and that final combination, without claiming an independent rerun of the computer-assisted certificate.','bounds'),block('The theorem’s expected-value algorithm gives the same supremum under the per-input probability convention: for any fixed positive slack, bounded output value turns an expectation guarantee into a positive constant success probability, and independent repetition boosts it. Finite precision can be absorbed into that slack. Taking the supremum removes the arbitrarily small loss.','bounds')],
 progress=[progress('2023','The approximation and UG-hardness bounds confine the ratio to an interval of width 0.00015.','bounds'),progress('2026','The indexed problem page cites those bounds while leaving the exact threshold open.')],
),['Applied the numerical accuracy rule and separated that known target from the still finer exact-ratio question.','Defined weighted finite inputs, directed cut value, randomized bit-time approximation and the supremum convention.','Stated Unique Games and the additional randomized complexity assumption explicitly.','Retained the existing importance assessment and archived only the known conditional target.'],['Read the current source page, including both numerical bounds and its cited paper.','Read the 2023 full-version theorem statements, weighted CSP/Unique Games definitions, Theorem 3.1 and the §4.4.2 proof combining interval-certified and independent rounding.','Checked the expected-value to bounded-success supremum convention and the exact rational midpoint/error calculation; no independent computer-assisted proof rerun is claimed.'], 'Conditionally resolved at absolute precision 1/100 by the known 2023 interval, assuming UGC and NP not contained in BPP. The exact approximation threshold is not claimed resolved. The numerical archival scope was an announced editorial recommendation after an unanswered optional question; no Lean proof or independent certificate execution is claimed.',summary=['Max Di-Cut maximizes the total weight of directed edges leaving a chosen side of a partition.','The numerical target is the best ratio achievable by randomized polynomial-time algorithms.','The selected assumptions are Unique Games and NP not contained in BPP.','Published bounds place the ratio between 0.87446 and 0.87461, already much more precise than one hundredth.','The record is archived for that known conditional accuracy, while exact determination remains a stronger question.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'],archive_reason='Known conditional numerical target: the 2023 interval [0.87446,0.87461], under UGC and NP not contained in BPP, already certifies the required 1/100 accuracy. The exact threshold is not claimed resolved; this archival follows the announced numerical-scope recommendation.')
