"""Complete the general-graph sublogarithmic randomized LOCAL MIS target."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,block,progress
from review_queue import read_claims
identifier='TCS-6499';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text())
complete(identifier,dict(
 status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''Does there exist one uniform classical randomized LOCAL algorithm \(A\), taking a positive integer confidence parameter \(h\), such that for every fixed \(h\ge1\), on every \(n\)-vertex simple undirected graph with \(n\ge2\), its vertex outputs form a maximal independent set with probability at least \(1-n^{-h}\), and its worst-case elapsed round count \(T_A(n,h)\) satisfies
\[
\lim_{n\to\infty}\frac{T_A(n,h)}{\log_2 n}=0?
\]
The guarantee ranges over all degrees, all valid distinct identifier assignments and all port numberings. Local computation, storage and message lengths are unrestricted; vertices have private random bits and may know \(n\) and the maximum degree.''',
 definitions=r'''The network is the input finite simple undirected graph \(G=(V,E)\); disconnected graphs and isolated vertices are included. Vertex \(v\) eventually outputs a bit \(b_v\). Set \(I=\{v:b_v=1\}\). Independence requires that no edge have both endpoints in \(I\), and maximality requires that every vertex outside \(I\) have a neighbor in \(I\). Maximal does not mean maximum cardinality. For the one-vertex graph the algorithm must output its vertex, without an asymptotic restriction beyond finite time.

Vertices have pairwise distinct identifiers in \(\{1,\ldots,n^2\}\). Each vertex initially knows its own identifier, its degree, the identifiers of its neighbors, the exact \(n\), the exact maximum degree \(\Delta\), and \(h\). An arbitrary port numbering bijectively labels each vertex's incident edges by the integers from one to its degree. The two endpoints need not give an edge the same port number. Knowing neighbors initially instead of after an identifier-exchange round changes the count by at most one round and does not change the little-o target.

The LOCAL model runs in synchronous rounds. Each vertex can send a different finite binary message of arbitrary length along each incident edge, with messages delivered before the next round. There are no other channels, graph preprocessing, advice strings or shared random tape. Each vertex runs the same finite program with its own sequence of independent fair random bits. Local storage and intermediate computation are unbounded but must be finite and terminate on every random tape between rounds. The program is uniform over \(n,\Delta,h\) and vertex identifiers. After a vertex emits its output it may send fixed dummy messages until all vertices have finished.

For fixed \(n,h\), \(T_A(n,h)\) is the supremum of the number of elapsed rounds until all outputs are available, over every graph with exactly \(n\) vertices, identifiers, ports and random tapes. This supremum must be finite. The displayed success probability concerns the entire output labeling simultaneously on each particular input, not each vertex separately. The time guarantee holds even on tapes on which the output is wrong.

The limit means that for every \(\varepsilon>0\) and every fixed integer \(h\ge1\), some \(n_0\) has \(T_A(n,h)\le\varepsilon\log_2n\) for every \(n\ge n_0\). The threshold may depend on \(h,\varepsilon\) and the program, but not on the graph, degrees or identifiers. Positive integer confidence parameters suffice for every requested real constant failure exponent. No common bound uniform in unbounded \(h\) is required. This explicit confidence-input convention realizes the saved high-probability requirement.

A bound on awake rounds, expected rounds, node-average rounds, or graphs avoiding short cycles is not the all-input worst-case elapsed-round bound in the question.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof of existence of such a uniform algorithm, including maximality, joint success probability and the little-o limit for every fixed confidence parameter; or prove the negation of this existential statement in the specified model. A lower bound for a restricted algorithmic technique, a sublogarithmic bound only for some graph classes, or a merely expected-time bound does not settle the target.''',
 source_formulation=dict(text='Open Question 1 asks for a randomized o(log n)-round MIS algorithm with high probability on general graphs. Its footnote defines high probability with an arbitrarily large fixed failure exponent. The card makes this confidence parameter and the elapsed-round convention explicit.',citation='girth',caption='Khoury–Schild 2025, introduction, Open Question 1 and footnote 1; Theorem 1 addresses girth at least seven.',format='editorial_paraphrase'),
 references=old['references'],
 progress=[progress('2016',r'The known degree-sensitive approach replaces dependence on \(n\) by \(\log\Delta\) plus a slower-growing residual term. The checked 2025 introduction explains why this leaves polynomial-degree graphs unresolved.','degree'),progress('2025-05-21',r'Theorem 1 gives sublogarithmic MIS for graphs without cycles of length at most six, while Open Question 1 and the discussion retain the general-graph target.','girth'),progress('2025-05-21',r'The companion primary paper proves a randomized maximal-matching lower bound \(\Omega(\min\{\log\Delta,\sqrt{\log n}\})\), which transfers to MIS on general graphs but not to MIS on trees. It is compatible with the requested little-o-logarithmic upper bound.','lower')],
 context_blocks=[block('The output is locally checkable: adjacent vertices cannot both be selected, and every unselected vertex needs a selected neighbor. Obtaining those compatible choices quickly is a basic symmetry-breaking task.','girth'),block('The strongest restricted-graph progress does not cover the short cycles allowed here. Arbitrarily large maximum degree is also essential to the remaining general question.','girth'),block('The matching lower bound and the MIS upper bound on trees concern different problems after reduction. The graph-class distinction prevents treating the tree progress as a general solution.','lower')],
),['Preserved the all-graph sublogarithmic randomized target and individual importance score of 89.','Made high-probability quantifiers explicit through one uniform confidence-parameter algorithm.','Specified identifiers, initial information, private coins, maximality and worst-case elapsed time.','Separated girth-restricted progress, maximal matching, and awake or expected time.'],['Read Khoury–Schild 2025 introduction, Open Question 1, footnotes 1–2 and Theorem 1 in the primary PDF.','Checked the companion 2025 primary abstract for the lower bound and the non-tree transfer to MIS.','Bounded subsequent searches through 18 September 2026 found no verified general-graph sublogarithmic resolution; the cited 2016 history is corroborated by the read 2025 introduction.'],'Source-open explicitly in Khoury–Schild 2025 Open Question 1. Its new upper bound requires excluding cycles of length at most six and does not settle arbitrary graphs. Bounded later-work checks through 18 September 2026 found no verified resolution; no independent full proof audit is claimed.',summary=['Vertices must choose a maximal independent set using only communication along graph edges.','The LOCAL model allows arbitrarily long messages and unlimited finite local computation.','The question asks for a randomized round count that is little-o of the logarithm of the graph size.','Success must hold jointly with arbitrarily high fixed polynomial confidence on every graph and identifier assignment.','Recent algorithms handle graphs without short cycles, while the unrestricted graph case remains the selected target.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
