"""Archive the refuted general contextual-bandit model-selection guarantee."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0711';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Simultaneous model-selection regret for general contextual bandits',
 status='resolved',criterion='resources',question_type='yes_no',
 formal=r'''Do there exist absolute constants \(\alpha\in[1/2,1)\), \(C>0\), an integer \(p\ge0\), and a contextual-bandit learning rule such that, for every finite context space, every action count \(K\ge2\), horizon \(T\ge1\), and nested sequence of finite nonempty policy classes \(\Pi_1\subsetneq\cdots\subsetneq\Pi_M\), the same run satisfies, against every nonanticipating adaptive adversary and for every \(m\in[M]\),
\[
\max_{\pi\in\Pi_m}\mathbb E\!\left[\sum_{t=1}^T\ell_t(a_t)-\sum_{t=1}^T\ell_t(\pi(x_t))\right]
\le C\Bigl(KM\bigl(1+\log_2\log_2(4|\Pi_M|)\bigr)\Bigr)^p
T^\alpha\bigl(\log_2(2|\Pi_m|)\bigr)^{1-\alpha}?
\]
The information available to the learner and the adversary is defined below. This is the general model-selection target; the known answer is negative.''',
 definitions=r'''The context space is \(\mathcal X=[N]\) for an arbitrary positive integer \(N\), and the actions are \([K]\). A deterministic policy is a function \(\pi:\mathcal X\to[K]\). The learner is given \(T,K,N\) and the entire finite nested sequence, with all policies represented by their full tables. There may be only one class. The learner is not told which class contains a useful comparator, and the desired inequalities must all hold for its same behavior without separately choosing a learner for each \(m\).

At round \(t\), before the learner draws its fresh action, the adversary chooses a context \(x_t\in\mathcal X\) and a full loss vector \(\ell_t\in[0,1]^K\). The learner sees \(x_t\), chooses \(a_t\in[K]\), and then sees only \(\ell_t(a_t)\). It does not see the other loss coordinates. Its rule may use all previous observed contexts, chosen actions and observed losses, and its own private randomness. It may choose any action; it need not select one policy from a class before seeing the current context.

The adversary may choose its next context and vector based on the entire past interaction, including past actions and its past full vectors, and may use its own randomness. It cannot depend on the learner’s unrevealed current random choice. Thus the current loss vector is fixed before \(a_t\) is drawn. Policies in the comparison are fixed functions, not adaptive opponents. Their losses are evaluated on the actual realized contexts \(x_t\), not on a counterfactual sequence that would have arisen from playing the comparator. The expectation averages the entire interaction, and the maximum over \(\pi\) is outside that expectation, exactly as displayed.

A learning rule here is a family of measurable conditional distributions on the finite action set given the initial tables and the observable history. Histories of real losses carry their usual Borel sigma-algebra. There is no restriction on computation or memory: the question is statistical possibility with bandit feedback. In particular, its negative answer applies also to implementable finite algorithms. The same constants and general rule must work for every input table and every adversary; no environment description, unobserved losses or future contexts are supplied.

The factor preceding \(T^\alpha\) represents an arbitrary fixed polynomial in \(K,M\) and the double logarithm of the largest class. A single power of their positive product covers such polynomial dependence after adjusting constants. The logarithms have been regularized explicitly so that singleton classes receive a positive bound. No impossibility is inferred from a zero logarithm. The exponent pair \(\alpha,1-\alpha\) must sum to one, and \(\alpha<1\) is one universal constant. The guarantee must hold at every finite horizon; a class-dependent burn-in period is not allowed.

For example, with constant \(K,M\), whenever \(\log|\Pi_m|\) grows slower than \(T\) by a fixed power and the largest-class factor is polylogarithmic in \(T\), the requested bound is sublinear in \(T\). A bound with larger exponents whose sum exceeds one does not provide the same promise. The target does not restrict the environment to a linear regression family, a known context distribution, or another additional structural condition.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof or refutation of the stated universal learning guarantee. A refutation must rule out every fixed alpha below one, every polynomial overhead and every learning rule using only bandit feedback, with the positive logarithm convention. This archived record identifies a published negative result; it does not claim that the result has already been formalized in Lean.',
 why='Model selection aims to adapt to a useful small policy class without paying for the largest possible class. The negative result identifies a fundamental statistical limit caused by the information needed for exploration, even with unlimited computation.',
 source_formulation=dict(text='Open Problem 1b, item 2, asks for simultaneous T^alpha log^{1−alpha}(|Pi_m|) regret with polynomial dependence on the listed side parameters, for some fixed alpha below one. This record retains that general adversarial target and uses positive logarithms to avoid degenerate singleton-class bounds. Archival as a known negative result was the announced recommendation after an unanswered optional question.',caption='Foster–Krishnamurthy–Luo, Open Problem 1b(2), PDF p.2; model on p.1.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','Open Problem: Model Selection for Contextual Bandits','Dylan J. Foster; Akshay Krishnamurthy; Haipeng Luo',2020,'https://proceedings.mlr.press/v125/foster20a.html','§2, Open Problem 1b(2), PDF pp.1–2'),ref('negative','The Pareto Frontier of model selection for general Contextual Bandits','Teodor Marinov; Julian Zimmert',2021,'https://papers.nips.cc/paper/2021/hash/9570efef719d705326f0ff817ef084e6-Abstract.html','§2 model; §4 Theorem 3, Corollary 1 and Theorem 5; §4.1–4.2; Appendix B')],
 context_blocks=[block('The source also proposes a sharper square-root bound and a realizable stochastic variant. This card chooses its broad weaker adversarial guarantee, which would already adapt to the size of a useful policy class.'),block('Corollary 1 of Marinov–Zimmert explicitly rules out the requested exponent tradeoff for every learner against an adaptive adversary. The construction has a constant number of actions and classes, so allowing polynomial rather than logarithmic dependence on those two parameters does not remove the obstruction. Its asymptotic argument also tolerates polylogarithmic factors from the largest class.','negative'),block('The lower-bound tradeoff forces near-linear regret to the larger class when regret to the smaller class is constrained as requested. The competing requested rate remains smaller by a fixed power for every alpha below one. This is an exploration lower bound, not a computational hardness assumption or a defect at log(1)=0.','negative'),block('The paper separately treats stochastic environments and distinguishes proper from unrestricted learners, giving a final impossibility statement for unrestricted learners as well. The selected adversarial target already follows from its earlier corollary; results for specially structured stochastic models do not reverse it.','negative')],
 progress=[progress('2020','The source formulates general simultaneous model-selection regret as an open problem.'),progress('2021','Marinov–Zimmert refute the universal exponent tradeoff and prove accompanying regret tradeoffs.','negative')],
),['Selected the source’s weaker general adversarial exponent tradeoff as the announced archival default.','Defined the adaptive information order, maximum outside expectation and actual-context comparator.','Regularized logarithms and allowed unrestricted learning rules to avoid an artificial computational or singleton obstruction.','Checked that the constant-action, constant-class lower bound survives the stated polynomial side factors.','Preserved the individual importance assessment and archived the known negative target.'],['Read the complete 2020 problem paper’s model, Open Problem 1a/1b and stochastic alternative.','Read the 2021 model, Theorem 3, Corollary 1, Theorem 5 and the corresponding proof explanations; checked the proper/improper distinction.','Bounded later-work checks through 18 September 2026 found refinements under extra stochastic or oblivious-adversary assumptions, not a reversal of the general adaptive lower bound. No independent full proof formalization is claimed.'], 'Resolved negatively by Marinov–Zimmert, NeurIPS 2021, for the retained universal adaptive-adversary target. The result is unconditional and tolerates the positive logarithm convention and listed polynomial side factors. This archival was the announced recommendation after an unanswered optional scope question; a Lean formalization has not been claimed.',summary=['A contextual-bandit learner observes a context but receives only the loss of its chosen action.','The historical goal was to compete simultaneously with each class in a nested collection of policies.','The requested bound adapts to the logarithm of the relevant class size with complementary exponents on time and complexity.','A 2021 lower bound rules out every such fixed exponent tradeoff in the general adaptive setting.','The card is archived as a known negative result, while stronger structural assumptions define different questions.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'],archive_reason='Resolved negatively: Marinov–Zimmert (NeurIPS 2021), Theorem 3 and Corollary 1, refute the general adaptive contextual-bandit model-selection target of Foster–Krishnamurthy–Luo Open Problem 1b(2), including the regularized positive-logarithm formulation. No claim of a completed Lean formalization.')
