"""Review exact dynamic APSP with capacity-sensitive amortized updates."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-0478';claim=read_claims(ROOT)[identifier]
notes=[
 'Retained the deterministic directed positive-integer-weight specialization and the supplied edge-capacity parameter, rather than silently replacing it by the current edge count or update-sequence length.',
 'Made the uniform word-RAM model, finite word operations, polynomial preprocessing and space, exact output and online operation interface explicit.',
 'Preserved the post-preprocessing bound for every finite operation prefix, with worst-case individual queries and amortized updates; no extra preprocessing-size credit is inserted into that bound.',
 'Read the original seminar question and distinguished its broad tilde-O(m)/tilde-O(1) target from the inherited editorial choices.',
 'Checked the journal-version near-quadratic update theorem, its sequence-length hypothesis and its log-cubed factor; approximate and planar offline results are separately scoped.',
 'Preserved importance and source-open status with a bounded current search, and required a complete Lean-checked proof or refutation.',
]
sources=[
 'Read Henzinger, Dynamic All Pairs Shortest Paths, §5.2 printed p.22 of Dagstuhl Seminar 21071, DOI 10.4230/DagRep.11.1.1. The paragraph asks for fully dynamic tilde-O(m) updates and tilde-O(1) queries, without specifying all of this card’s weight, determinism and amortization conventions.',
 'Read Demetrescu–Italiano, A New Approach to Dynamic All Pairs Shortest Paths, author-hosted journal manuscript: abstract and problem definition pp.1–2; Theorem 8 and proof p.26; conclusion p.27. The theorem states O(n^2 log^3 n) amortized vertex updates, optimal queries and polynomial space, for a sequence of Omega(m/n) operations under its uniqueness convention. The earlier conference log-squared claim is not used. This is background on the near-quadratic scale, not a certification of every prefix requirement on this card.',
 'Read Kyng–Meierhans–Zöcklein, Bootstrapping Dynamic APSP via Sparsification, ESA 2025 Article 113: abstract p.113:1, Theorem 1 and §2.1 p.113:2. Its theorem processes up to m updates in m^(1+o(1)) total time with an m^o(1) multiplicative approximation and polylogarithmic queries. That m is an update budget; it is not automatically the capacity parameter of this card. Exactness alone already prevents treating the result as a solution here.',
 'Read the primary arXiv abstract and metadata of Das–Probst Gutenberg–Wulff-Nilsen, arXiv:2606.01809v1, posted 1 June 2026 and marked Appeared in SODA 2022. It concerns planar digraphs, an offline fully dynamic result with tilde-O(sqrt(n)) update and query time, and an online incremental result. The posting date is not described as a new 2026 theorem.',
 'Bounded primary-source searches through 17 September 2026 for exact fully dynamic sparse APSP did not locate a result meeting all the selected deterministic, exact, general-digraph, edge-capacity-sensitive and polylog-query requirements. No independent proof audit of the cited algorithms is claimed.',
]
complete(identifier,dict(
 status='source_open',criterion='resources',question_type='yes_no',
 formal=r'''For every fixed integer \(c\ge1\), do there exist integers \(a,d\ge1\) and \(B\ge c+3\), a real constant \(K\ge1\), and one uniform deterministic word-RAM data structure with the following guarantees for every \(n\ge2\) and supplied integer capacity \(n\le m\le n^2\)?

The data structure maintains a simple directed graph on the fixed vertex set \(\{1,\ldots,n\}\), with at most \(m\) live edges and edge weights in \(\{1,\ldots,n^c\}\), under online single-edge insertions, deletions and weight changes. It returns the exact current distance for every queried ordered vertex pair. Write \(\ell=\log_2(n+2)\). Preprocessing an arbitrary initial graph uses at most \(Kn^d\) instructions, and space is at most \(Kn^d\) words at every time. Every individual query uses at most \(K\ell^a\) instructions. After preprocessing, every finite valid sequence containing \(U\) updates and \(Q\) queries uses at most
\[
K\bigl(Um\ell^a+Q\ell^a\bigr)
\]
instructions in total. The constants and program may depend on \(c\), but not on \(n,m\), the initial graph or the operation sequence.''',
 definitions=r'''The initial graph is explicitly given as a list of ordered endpoint pairs and integer weights, together with \(n\) and \(m\). There are no self-loops, and each ordered pair has at most one edge. An insertion supplies an absent edge and its allowed weight, a deletion names a present edge, and a weight change supplies a new allowed weight for a present edge. Every resulting graph must have at most the fixed supplied capacity \(m\) edges. The algorithm must support all such valid sequences, however long. The value \(m\) is neither the number of updates nor the current number of edges.

A query supplies \(s,t\in\{1,\ldots,n\}\) and requests the minimum sum of edge weights along a directed path from \(s\) to \(t\), with distance zero when \(s=t\) and a distinguished symbol \(\infty\) when no path exists. Positive weights imply that every finite distance is at most \((n-1)n^c\). The output is this one distance, not a shortest path or a full matrix. Every answer must be correct. Operations arrive one at a time, and each must finish before the next is supplied; future operations are unavailable.

For a given \(n\), a machine word has exactly \(w=B\lceil\log_2(n+2)\rceil\) bits. Memory is indexed by unsigned words, and \(B\) must also be large enough to address the allowed \(Kn^d\) words. Unit-cost instructions are word reads and writes, unsigned comparisons and conditional branching, addition, subtraction and multiplication modulo \(2^w\), unsigned integer quotient and remainder with nonzero divisor, bitwise Boolean operations, and logical shifts. A shift by at least \(w\) returns zero. Finite distances and the infinity marker must have an unambiguous constant-word encoding. Arithmetic on larger integers must be implemented and charged through these operations. The program is finite and independent of \(n,m\); it receives no advice or uncharged precomputed tables.

Preprocessing includes reading and constructing all initial data. After it finishes, the displayed total bound applies to every finite prefix, including prefixes with no updates or no queries. There is no extra additive \(n^d\) allowance in that post-preprocessing bound. Individual updates may exceed their amortized charge, but each query also satisfies the stated worst-case bound, regardless of the preceding operations. All instruction counts include maintenance work and any rebuilding performed during the operation sequence. The space bound applies throughout preprocessing and all operations.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof of the quantified existence statement or its logical negation. A positive answer must specify a uniform deterministic data structure for every fixed \(c\), prove all exact query answers and the capacity-sensitive bounds for every allowed graph and operation prefix, and account for word size and polynomial space.

A negative answer must disprove the existence proposition in the stated model; a result conditional on an unproved complexity hypothesis remains a conditional obstruction and must identify that assumption. An update bound near \(n^2\) only has the requested dependence on \(m\) for sufficiently dense graphs. Approximate distances, offline sequences, planar graphs, insertion-only updates, or an amortized query bound alone do not establish the stated target. The fact that one edge change alters many pairwise distances is not by itself a lower bound on an implicit distance oracle.''',
 source_formulation=dict(text='The seminar asks for a fully dynamic all-pairs shortest-path algorithm with update cost proportional to the edge count and constant query cost, allowing polylogarithmic factors in both. This card retains the previously selected deterministic, directed, bounded-integer-weight version with amortized edge updates and a supplied edge capacity.',caption='Henzinger, Dagstuhl Seminar 21071, §5.2, printed p.22. The detailed machine and prefix conventions are editorial specifications.',citation='primary',format='editorial_paraphrase'),
 references=[
 ref('primary','Scalable Data Structures — Dynamic All Pairs Shortest Paths','Monika Henzinger (problem contributor)',2021,'https://doi.org/10.4230/DagRep.11.1.1','Dagstuhl Seminar 21071, §5.2, printed p.22'),
 ref('classic','A New Approach to Dynamic All Pairs Shortest Paths','Camil Demetrescu; Giuseppe F. Italiano',2004,'https://www.diag.uniroma1.it/~demetres/docs/dapsp-full.pdf','Journal manuscript: abstract and problem definition pp.1–2, Theorem 8 and proof p.26, conclusion p.27'),
 ref('sparsification','Bootstrapping Dynamic APSP via Sparsification','Rasmus Kyng; Simon Meierhans; Gernot Zöcklein',2025,'https://doi.org/10.4230/LIPIcs.ESA.2025.113','Abstract p.113:1; Theorem 1 and §2.1 p.113:2'),
 ref('planar','A Near-Optimal Offline Algorithm for Dynamic All-Pairs Shortest Paths in Planar Digraphs','Debarati Das; Maximilian Probst Gutenberg; Christian Wulff-Nilsen',2022,'https://arxiv.org/abs/2606.01809v1','Abstract and metadata; posted 1 June 2026, marked as appeared in SODA 2022'),
 ],
 context_blocks=[
 block('The data structure must combine cheap updates with immediately available exact answers. The requested update scale follows a supplied bound on live edges, so it asks for a substantial saving on sparse graphs even though the number of possible queried pairs is quadratic.'),
 block('Changing one edge can change many shortest-path distances. An oracle may represent those changes implicitly and expose only one distance per query, so counting changed entries in a materialized matrix does not settle its update cost.'),
 block(r'The classical journal result achieves \(O(n^2\log^3 n)\) amortized updates and constant distance queries. Its theorem has its own initialization, sequence-length and tie-handling conventions. It supplies the near-quadratic baseline, while the selected card asks for a bound that scales with the edge capacity even when it is close to \(n\).','classic'),
 block('The ESA 2025 sparsification theorem achieves near-linear total processing for its bounded update sequence with a subpolynomial multiplicative distance approximation. Both the approximation and the meaning of its update-budget parameter must be kept explicit when comparing that theorem with exact capacity-sensitive maintenance.','sparsification'),
 block('The planar result posted to arXiv in June 2026 was already a SODA 2022 result according to its metadata. Its main fully dynamic guarantee is offline, and its query cost is near square-root rather than polylogarithmic. It does not resolve the general online target.','planar'),
 ],
 progress=[progress('2004','The journal algorithm establishes the classical near-quadratic amortized-update and constant-query baseline under its stated initialization and sequence conventions.','classic'),progress('2021','The seminar asks for edge-linear updates and constant queries up to polylogarithmic factors.'),progress('2025','The sparsification theorem gives very fast dynamic approximate distances for a bounded-length update sequence.','sparsification'),progress('2026-06-01','The SODA 2022 planar offline result is posted to arXiv; its model and query bound differ from this target.','planar')],
),notes,sources,'Source-open target, retaining the inherited deterministic positive-integer-weight specialization. Bounded searches through 17 September 2026 did not locate an exact general-digraph algorithm satisfying all the selected capacity-sensitive update, worst-case query, online and prefix guarantees. The 2025 approximate theorem and the planar offline paper posted in 2026 do not meet these requirements. This search does not establish unconditional current openness.',summary=[
 'The data structure maintains exact directed distances while individual weighted edges change.',
 'The supplied capacity m bounds the number of live edges throughout an arbitrary online operation sequence.',
 'The requested update charge is m times a fixed polylogarithmic factor, with polylogarithmic worst-case distance queries.',
 'The deterministic model allows polynomial preprocessing and space but requires the operation bound after preprocessing for every finite prefix.',
 'The review separates this sparse exact target from near-quadratic, approximate and planar offline results.',
],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
