"""Audit general randomized reallocation against oblivious request sequences."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,block,progress
from review_queue import read_claims
identifier='TCS-7340';claim=read_claims(ROOT)[identifier]
old=json.loads((ROOT/'data/cards'/f'{identifier}.json').read_text())
complete(identifier,dict(
 status='source_open',criterion='resources',question_type='asymptotic_complexity',
 formal=r'''Determine, up to absolute constant factors as \(\varepsilon\to0^+\), the optimal worst-case expected overhead \(F(\varepsilon)\) for online memory reallocation at load at most \(1-\varepsilon\). In the model below,
\[
F(\varepsilon)=\inf_{\mathcal A}\ \sup_{M,\sigma,j}\ \mathbb E[\operatorname{cost}_{\mathcal A,M}(\sigma,j)],
\qquad 0<\varepsilon\le\tfrac12.
\]
The supremum ranges over positive integer capacities, nonempty valid finite request sequences fixed independently of the allocator's randomness, and one update in each sequence. All live objects occupy disjoint contiguous intervals.''',
 definitions=r'''The memory consists of integer slots \(\{0,\ldots,M-1\}\). Each object has a distinct name and a positive integer size \(s(x)\). A request inserts a fresh object and supplies its size, or deletes a named live object. Valid sequences start empty and, after each update, have total live size at most \((1-\varepsilon)M\). There is no restriction on the individual sizes beyond that load bound, and deleted object names are not reused. At every operation boundary an allocation map \(\phi\) assigns each live object a starting slot, with interval \([\phi(x),\phi(x)+s(x))\) contained in \([0,M)\); these intervals are pairwise disjoint.

If the updated object is \(x\), the live sets before and after the update are \(X,X'\), and their allocation maps are \(\phi,\phi'\), then
\[
\operatorname{cost}=1+\frac{1}{s(x)}\sum_{\substack{y\in X\cap X'\\\phi(y)\ne\phi'(y)}}s(y).
\]
The leading one charges the inserted or deleted object. Each persistent object whose start changes is charged its full size once. This is the source's boundary-allocation switching cost: intermediate physical copying steps, implementation time and allocation metadata are not an additional cost. Objects may be rearranged arbitrarily between valid boundary allocations; this is not an in-place copying task with a separately limited scratch buffer.

For each fixed \(\varepsilon\), an admissible family \(\mathcal A=(A_M)_{M\ge1}\) consists of online randomized allocation rules. Each rule knows \(M,\varepsilon\), all past requests and its private randomness, but has no future request information. Its allocations must always be valid. There is no computational, history-independence, resizability or metadata-space restriction. Rules may be specified as distributions over valid next allocations conditional on past requests and allocations. There is no requirement to compute them from a finite representation of the real parameter \(\varepsilon\).

The adversary may select any finite valid sequence \(\sigma\) after the family is fixed, but cannot change it based on the realized randomness or observed allocations. For each \(j\in\{1,\ldots,|\sigma|\}\), expectation covers the allocator's entire random history through update \(j\). Taking the supremum after that expectation requires a bound for each update separately. It is neither an amortized average over updates nor a bound on the expectation of their maximum. Capacities with no valid nonempty sequence contribute no candidate to the supremum. Larger capacities permit insertions, so the supremum is nonempty and the overhead is at least one. The infimum need not be attained.

The requested characterization supplies an explicit positive expression \(f(\varepsilon)\), independent of the optimization defining \(F\), and constants \(c,C>0\), \(0<\varepsilon_0\le1/2\), such that \(c f(\varepsilon)\le F(\varepsilon)\le C f(\varepsilon)\) for every \(0<\varepsilon\le\varepsilon_0\). All logarithmic factors matter. Renaming the defining extremum or solving each finite-horizon allocation game separately is not a matching asymptotic expression uniform over all capacities and sequence lengths.''',
 answer_criterion=r'''Give a complete mathematically correct Lean-checked proof of an explicit matching expression and both inequalities with the stated absolute constants. The upper result must cover arbitrary object sizes and every individual update of every oblivious sequence. The lower result must apply to all allowed allocator families, including those without resizability or history independence. Bounds only in amortized expectation, or high-probability tail bounds for another resource, do not settle this target.''',
 references=old['references'],
 source_formulation=dict(text='The primary 2026 paper asks for the best overhead as a function of unused capacity and explicitly leaves the gap between its general logarithmic lower bound and polylogarithmic upper bound open.',citation='recent',caption='Introduction pp. 2–4, exact allocation-map cost; Theorems 1.1 and 1.3.',format='editorial_paraphrase'),
 context_blocks=[block('When memory is nearly full, insertion may force relocation of other objects even though total free volume suffices. Charging moved volume relative to the updated object isolates that fragmentation cost.','recent'),block(r'The 2026 upper bound is \(O(\log^4(1/\varepsilon)(\log\log(1/\varepsilon))^2)\); the lower bound is \(\Omega(\log(1/\varepsilon))\) for general allocators. Thus the remaining logarithmic powers are part of the selected target.','recent'),block('The new lower bound removes the extra restrictions in earlier lower-bound models. Its separate tail obstruction explains why expected overhead and a high-probability guarantee must not be conflated.','recent')],
 progress=[progress('2024','The earlier work gives a near-square-root overhead in inverse slack; its additional resizability guarantee is stronger than required here.','origin'),progress('2026-02-17','Theorems 1.1 and 1.3 give polylogarithmic expected overhead and a logarithmic lower bound even without extra allocation restrictions. The paper explicitly asks to close their gap.','recent')],
),['Retained general allocator families, arbitrary sizes and worst-case per-update expectation against oblivious sequences.','Verified the exact boundary-allocation switching cost, including the unit charge for the updated object.','Specified allocation validity, parameter dependence and the supremum/expectation order without introducing an implementation-time restriction.','Preserved importance 84 and separated general lower bounds from resizable, history-independent and tail guarantees.'],['Read the February 2026 introduction’s exact model and overhead definition, Theorems 1.1, 1.3 and 1.4, and §2 load-factor convention.','Checked current primary arXiv metadata on 18 September 2026; the cited version remains v1 and is listed for STOC 2026.','Bounded later-work searches found no verified matching logarithmic rate. The 2024 result is corroborated by the 2026 introduction; no new independent audit of either full algorithm proof is claimed.'],'Jin’s February 2026 primary paper explicitly leaves the near-quartic logarithmic gap open for this exact general expected-overhead model. Bounded checks through 18 September 2026 found no verified resolution; this is not exhaustive certification.',summary=['An online allocator stores variable-sized objects contiguously in a nearly full array.','Insertions and deletions may force other live objects to change addresses.','Each update is charged moved volume divided by the size of its updated object.','The target is the optimal worst-case expected overhead as unused capacity tends to zero.','The checked logarithmic lower bound and polylogarithmic upper bound leave a gap for general allocators.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
