"""Select a precise nonparameterized constant-gap Clique implication from ETH."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'research/card-completion-20260913'))
from complete_review import complete,ref,block,progress
from review_queue import read_claims
identifier='TCS-2662';claim=read_claims(ROOT)[identifier]
complete(identifier,dict(
 title='Does ETH rule out subexponential constant-gap Max-Clique?',
 status='source_open',criterion='assumptions',question_type='yes_no',
 formal=r'''Does deterministic ETH imply that there exists a rational constant \(\gamma>1\) for which no uniform deterministic algorithm solves the following promise problem in time \(2^{o(n)}\)? Given an \(n\)-vertex graph \(G\) and an integer \(1\le k\le n\), distinguish
\[
\omega(G)\ge k\qquad\text{from}\qquad\omega(G)<k/\gamma,
\]
where \(\omega(G)\) is the maximum number of pairwise adjacent vertices. The exponent parameter \(n\) is the total number of graph vertices, not the requested clique size \(k\).''',
 definitions=r'''Graphs are finite, simple, undirected and unweighted, with vertex set \([n]=\{1,\ldots,n\}\), \(n\ge1\). The input contains binary encodings of \(n,k\) and the full symmetric zero-diagonal Boolean adjacency matrix. A clique is a set of vertices for which every two distinct members are adjacent; its size is its cardinality. A yes input has a clique of size at least \(k\), and a no input has no clique of size \(k/\gamma\) or larger, using the strict inequality in the displayed statement. On inputs with \(k/\gamma\le\omega(G)<k\), either decision bit is allowed.

For a fixed factor \(\gamma\), a \(2^{o(n)}\)-time solver means that there exist a positive integer \(K\), a computable function \(h:\mathbb N_{\ge1}\to\mathbb Q_{\ge0}\) with \(h(n)/n\to0\), and a deterministic multitape Turing machine that halts on every valid input in at most \(K2^{h(n)}\) bit operations and is correct on all promised inputs. Input access, arithmetic, preprocessing and output are included. The bound is uniform over every \(k\le n\). Polynomial factors in input size are absorbed in \(h(n)\); an arbitrary multiplicative function of \(k\) is not allowed. No advice, oracle or randomness is available.

The deterministic Exponential Time Hypothesis used here asserts that some real \(\eta>0\) has the following property: no deterministic algorithm decides satisfiability of every Boolean 3-CNF formula with \(v\) variables in time \(O(2^{\eta v}(L_F+2)^b)\), for any fixed \(b\), where \(L_F\) is the complete binary formula length. A clause is a disjunction of at most three literals, each a variable or its negation; the input is the full conjunction of its clauses. The computation uses the same deterministic bit model. This hypothesis concerns exact satisfiability. It does not promise a constant gap in the fraction of satisfiable clauses and is not replaced by Gap-ETH.

The order of quantifiers is: ETH implies that some fixed \(\gamma>1\) rules out every such subexponential solver. The factor must be independent of \(n,k\); it is not supplied as an input. The question does not ask for a lower bound for every fixed approximation factor. Restricting the existential factor to rationals is harmless: if the impossibility holds at any real factor greater than one, it also holds for a smaller rational factor greater than one, whose promise includes the former promise.

A multiplicative clique approximation that always outputs a clique of size at least \(\omega(G)/\gamma\) would solve the stated gap problem by comparing its size with \(k/\gamma\). The card asks directly about gap decision to make its success condition unambiguous. The conclusion is a conditional nonexistence theorem; a complete answer must address the implication itself.''',
 answer_criterion='Give a complete mathematically correct Lean-checked proof or refutation of the displayed ETH implication. A positive answer must identify some fixed factor and exclude all uniform subexponential bit-time gap solvers as a consequence of ordinary deterministic ETH. A result assuming Gap-ETH, an exact-clique lower bound without a multiplicative gap, or a parameterized lower bound with insufficient graph-size control is not enough.',
 why='Exact Clique has an ETH barrier at the exponential-in-vertices scale. Preserving that scale under even one fixed approximation gap would explain whether coarse approximation escapes the barrier without assuming gap hardness at the outset.',
 importance=dict(score=84,method='editorial',reason='A basic gap-free versus gap-hardness question for a central optimization problem; it concerns the full graph-size exponent rather than a narrower parameterized running-time improvement.'),
 source_formulation=dict(text='Question 2 asks about a 2^{o(n)} algorithm for nonparameterized constant-gap Max-Clique under ETH. The selected target is the ETH implication excluding such an algorithm for some fixed factor greater than one. The factor quantifier and deterministic finite-input model are the announced editorial recommendation after an unanswered optional question.',caption='Lin–Ren–Sun–Wang, §6 Question 2 p.90:16; ETH definition in §2.',citation='primary',format='editorial_paraphrase'),
 references=[ref('primary','On Lower Bounds of Approximating Parameterized k-Clique','Bingkai Lin; Xuandi Ren; Yican Sun; Xiuhan Wang',2022,'https://doi.org/10.4230/LIPIcs.ICALP.2022.90','§2 Hypothesis 4; §6 Question 2 p.90:16')],
 context_blocks=[block('The paper primarily studies parameterized approximation, but its final second question explicitly changes to an n-vertex nonparameterized problem. That distinction determines which exponential running-time scale must be preserved.'),block('The preceding question concerns an f(k) times n^{O(k/log k)} bound. Such a statement does not itself settle a 2^{o(n)} algorithm for arbitrary n-vertex inputs with k also varying.'),block('The selected formulation fixes a genuine multiplicative gap and an existential constant factor. It does not infer approximation hardness solely from the known exact-clique ETH barrier.')],
 progress=[progress('2022','The source poses the nonparameterized subexponential constant-gap question separately from its parameterized questions.')],
),['Selected the some-constant-factor lower-bound implication as the announced editorial default.','Defined the clique gap, strict boundary, explicit graph encoding and uniform subexponential bit time.','Distinguished total graph size from clique-size parameter and ETH from Gap-ETH.','Individually assessed importance and supplied a complete Lean-checked implication criterion.'],['Read the source ETH convention and the complete concluding Questions 1 and 2.','Bounded primary-source searches through 18 September 2026 found no verified resolution of the selected nonparameterized implication; restricted graph classes and parameterized statements were not treated as general resolutions.'], 'Source-open as the nonparameterized constant-gap question in ICALP 2022. Bounded checks through 18 September 2026 found no verified resolution of the selected some-factor deterministic-ETH implication. The exact factor quantifier was an announced editorial default after an unanswered optional scope question.',summary=['The input is an arbitrary graph and a requested clique size k.','The promise separates graphs with a k-clique from graphs whose largest clique is smaller by a fixed multiplicative factor.','The target asks whether ordinary ETH rules out subexponential time in the total number of vertices.','It is enough to establish this barrier for some fixed factor greater than one.','Parameterized running times and assumptions that already contain a satisfiability gap do not settle the selected implication.'],expected_sha256=claim['input_sha256'],claim_token=claim['token'])
