add('37A','Average-case RSA inversion versus factoring for exponent 65537','crypto','reductions',
    'Does polynomial-time inversion of RSA with public exponent 65537 on random valid moduli and random ciphertexts imply polynomial-time factoring of those random moduli?',
    'A valid modulus is N=pq for distinct primes p,q with gcd(65537,(p−1)(q−1))=1. RSA maps x∈ℤ_N^* to x^65537 mod N. The intended distributions choose equal-bit-length primes uniformly subject to validity and choose the plaintext uniformly in ℤ_N^*. The target is a classical average-case reduction, not a claim that recovering a private key and factoring are different tasks.',
    'Factoring an RSA modulus gives the private exponent and hence breaks encryption, but the reverse reduction is a longstanding cryptographic question. It would identify whether RSA inversion rests on precisely the factoring assumption or on a potentially weaker computational task.\n\nBoneh’s survey explicitly poses factoring with access to an RSA inversion oracle. The personal proposal chooses a fixed widely used exponent and average-case distributions, which require an additional formal reduction convention. Restricted-model separation results do not settle an unrestricted implication.',
    'Identify the computational assumption underlying one of the central public-key primitives.',92,
    'Twenty Years of Attacks on the RSA Cryptosystem','Dan Boneh',1999,'Open Problem 1; fixed-exponent average-case specialization is editorial.',
    'The survey distinguishes factoring-to-inversion from the unresolved converse.',
    issue='Specify nonnegligible versus high inversion success, reduction access to the inverter, the success requirement over moduli, and the exact uniform prime ensemble before certifying the fixed-exponent average-case formulation.')

add('41A','Does public-key encryption imply compact fully homomorphic encryption?','crypto','assumptions',
    'Does the existence of IND-CPA-secure public-key encryption imply compact fully homomorphic encryption for all polynomial-size Boolean circuits in the classical standard model?',
    CRYPTO+' Fully homomorphic encryption permits public evaluation of a Boolean circuit on encrypted inputs, producing an encryption of its output. Compactness requires the evaluated ciphertext length and decryption cost to be bounded by a polynomial in the security parameter and output length, independently of the evaluated circuit size. The intended scheme is unleveled: key generation receives no circuit-depth bound.',
    'Public-key encryption permits confidential communication; fully homomorphic encryption additionally permits computation over ciphertexts. A general implication would make the stronger capability follow from the existence of the basic public-key primitive.\n\nThe cited black-box separation rules out deriving fully homomorphic encryption from even hierarchical identity-based encryption by that restricted type of construction. It therefore supplies a barrier and motivation, not a negative answer to an arbitrary non-black-box implication. The existing LWE-to-FHE card starts from a specific stronger assumption.',
    'Determine whether computation over encrypted data requires fundamentally more than public-key confidentiality.',90,
    'On the Power of Hierarchical Identity-Based Encryption','Mohammad Mahmoody; Ameer Mohammed',2015,'Abstract and black-box separations involving fully homomorphic encryption.',
    'The paper rules out specified fully black-box constructions; unrestricted implications remain distinct.',related=('TCS-6551',),
    issue='Reproduce complete IND-CPA games and compact-FHE correctness, key-generation and evaluation quantifiers. Fix the correctness convention for circuit families before promoting this candidate.')

add('42B','Identity-based encryption from arbitrary public-key encryption','crypto','assumptions',
    'Does the existence of IND-CPA-secure public-key encryption imply adaptively secure identity-based encryption supporting every identity in {0,1}^λ with polynomial-size public parameters in the standard model?',
    CRYPTO+' An identity-based scheme has master key generation, extraction of a secret key for an identity, encryption using the public parameters and identity, and decryption using the extracted key. Adaptive security permits chosen-identity key extraction queries before and after the challenge, excluding the challenge identity. The identity space is exponential in the security parameter, so a separate ordinary public key for every identity does not satisfy the size requirement.',
    'Identity-based encryption lets a single public setup support a large collection of recipient names. Deriving it from ordinary public-key encryption would resolve whether this form of key management needs additional hardness.\n\nThe source proves a sharp limitation in the generic-group model and discusses constructions that overcome earlier restrictions by leaving that model. It does not establish an impossibility for arbitrary constructions from public-key encryption. The size of the identity space distinguishes the target from a polynomial list of separately generated public keys.',
    'Compare the assumptions needed for basic encryption and large-scale identity-based access control.',86,
    'Generic-Group Identity-Based Encryption: A Tight Impossibility Result','Gili Schul-Ganz; Gil Segev',2021,'Introduction and generic-group impossibility threshold.',
    'The source limits the number of identities in generic-group constructions relative to public-parameter size.',
    issue='Supply the full adaptive IND-ID-CPA experiment and quantifiers for correctness and key extraction, then verify the general PKE implication against the precise source conventions.')

add('43A','Succinct noninteractive arguments for all NP from LWE alone','crypto','assumptions',
    'Does standard polynomial-hard Learning With Errors suffice for succinct noninteractive arguments for every NP relation in the honestly generated CRS model, without another computational or proof-complexity assumption?',
    'An NP relation has polynomial-time verification and polynomially bounded witnesses. A SNARG has a polynomial-time prover and verifier and a common reference string generated before the statement; proof length must be polynomial in the security parameter and logarithm of the computation length. Soundness must hold against polynomial-size adversaries for all sufficiently large security parameters, not merely infinitely often. No knowledge-extraction or zero-knowledge property is demanded.',
    'Succinct arguments compress the evidence for a potentially long computation into a short message. Basing them on a standard lattice assumption would connect a powerful verification primitive to a much more established cryptographic foundation.\n\nThe June 2026 source obtains SNARGs for NP from LWE, SXDH, derandomization and a proof-complexity assumption together. Those additional hypotheses matter. Results for restricted NP subclasses or infinitely-often soundness do not settle the target for all NP.',
    'A major minimal-assumption question for general succinct verification.',94,
    'SNARGs for NP from Unprovability of Mathematical Theorems','YaoChing Hsieh; Abhishek Jain; Jiatu Li; Surya Mathialagan',2026,'Abstract and assumptions of the main theorem.',
    'The construction for all NP uses additional cryptographic, derandomization and proof-complexity assumptions beyond LWE.',
    issue='Fix the LWE modulus/noise family, CRS dependence on input size, adaptivity of the soundness game and exact succinctness bound. These choices are not supplied by the short personal proposal.')

add('44B','One-way permutations from Learning With Errors','crypto','assumptions',
    'Does standard polynomial-hard Learning With Errors imply a polynomial-time computable family of full-domain one-way permutations?',
    CRYPTO+' A full-domain permutation at length n is a bijection of {0,1}^n, not merely an injective map to a larger space or a permutation of a hidden subset. One-wayness requires every polynomial-size inverter to recover the preimage of a uniform output with only negligible probability. Publicly indexed permutations and a single uniform permutation family must be distinguished.',
    'Lattice assumptions support many encryption and verification primitives, but obtaining a genuine permutation imposes an exact bijectivity requirement. This is a different issue from constructing arbitrary one-way functions.\n\nThe Simons problem list records Vaikuntanathan’s challenge of one-way permutations from worst-case lattice assumptions and notes that stronger obfuscation results would imply it. The proposed LWE version is an explicit assumption specialization. It is retained as a formulation candidate rather than being conflated with the general OWF-to-OWP question.',
    'Test the reach of lattice hardness under an exact reversibility constraint on the forward map.',85,
    'Open Problems, Cryptography, Summer 2015','Simons Institute; compiled by Ron Rothblum and Alessandra Scafuro',2015,'Problem 1 and the stated implication from problem 3.',
    'The list poses one-way permutations from a worst-case lattice assumption.',related=('TCS-6546','TCS-6550'),
    issue='Choose a precise LWE parameter family and specify whether the permutation is publicly indexed, including key generation and allowed domains. Record how that specialization relates to the original worst-case lattice question.')

add('46B','Unconditional NP-hardness at the Goemans–Williamson Max-Cut threshold','approximation','reductions',
    'For every rational ε with 0<ε<1−α_GW, do rationals 0<b<a≤1 with b/a<α_GW+ε exist such that distinguishing Max-Cut value at least a from value at most b is NP-hard under deterministic polynomial-time many-one reductions?',
    'For a finite simple undirected graph with at least one edge, its Max-Cut value is the maximum fraction of edges crossing a bipartition. Let α_GW=min_{0<θ≤π} 2θ/(π(1−cos θ)). NP-hardness means there is a polynomial-time map from 3-CNF formulas to graphs mapping satisfiable formulas to the at-least-a case and unsatisfiable formulas to the at-most-b case. The reduction and constants may depend on ε. No Unique Games or other hardness conjecture is assumed.',
    'The Goemans–Williamson approximation ratio is a landmark in semidefinite optimization. Matching hardness from ordinary NP-hardness would identify that ratio as an intrinsic computational threshold under P≠NP.\n\nKnown optimal hardness follows from Unique Games; it is not an unconditional NP-hardness theorem. The target deliberately concerns the reduction itself, so a conditional implication from UGC does not count as a solution. This separates the problem from the Unique Games conjecture and from improving a particular rounding algorithm.',
    'Determine whether a defining semidefinite approximation threshold follows from ordinary NP-hardness alone.',94,
    'Optimal Inapproximability Results for MAX-CUT and Other 2-Variable CSPs','Subhash Khot; Guy Kindler; Elchanan Mossel; Ryan O’Donnell',2007,'Main Max-Cut hardness theorem and its Unique Games hypothesis.',
    'The source derives the Goemans–Williamson hardness threshold assuming Unique Games.',url='https://faculty.wharton.upenn.edu/wp-content/uploads/2014/07/Optimal_Inapproximability_Results_for_MAX_CUT_and_Other_2_Variable_CSPs_1.pdf',related=('TCS-0006',))

add('47A','A constant improvement over factor two for Vertex Cover','approximation','tightness',
    'Do a constant ε∈(0,1) and a deterministic polynomial-time algorithm exist which, on every finite simple undirected graph G, output a vertex cover of size at most (2−ε)τ(G)?',
    BIT+' A vertex cover is a subset S of the vertices containing at least one endpoint of every edge; τ(G) is the minimum size of such a set. The graph is represented by its adjacency matrix. The same ε and algorithm must work for graphs of all sizes, with no promise on degree, coloring or graph class. An edgeless input requires the empty cover. The question asks for an unconditional algorithm or unconditional refutation of its existence.',
    'Vertex Cover is one of the canonical NP-hard covering problems and has a simple factor-two approximation. The absence of a fixed improvement despite extensive work makes the factor a central approximation barrier.\n\nUnique Games implies hardness below two, while unconditional NP-hardness leaves a gap. A restricted graph-class algorithm does not answer the universal target. The source seminar situates the question in the development of approximation algorithms and primal-dual methods.',
    'Resolve a basic approximation threshold for a widely used covering primitive.',95,
    'Approximation Algorithms: seminar by Vijay Vazirani','Vijay V. Vazirani',2001,'Vertex Cover and the factor-two approximation barrier.',
    'The source discusses the factor-two benchmark among fundamental approximation questions.',related=('TCS-0006',))

add('49A','Superpolynomial semidefinite extension complexity of perfect matching','optimization','resources',
    'For every C,c>0, does some even n≥2 satisfy xc_SDP(P_n)>Cn^c, where P_n is the perfect-matching polytope of K_n?',
    'P_n⊆ℝ^(n choose 2) is the convex hull of the zero-one incidence vectors of all perfect matchings of the complete graph on n labeled vertices. A size-r semidefinite lift is an affine subspace L of the real symmetric r×r matrices and an affine map π into ℝ^(n choose 2) such that P_n=π(L∩S_+^r), where S_+^r consists of positive semidefinite matrices. xc_SDP is the smallest such integer r. Coefficients may be arbitrary real numbers and need not be efficiently generated. The representation is exact; approximate relaxations and linear lifts are different notions.',
    'Perfect matching can be optimized in polynomial time, yet exact linear descriptions in higher-dimensional spaces can require exponentially many inequalities. The question asks whether positive semidefinite constraints also suffer a superpolynomial representation barrier.\n\nA linear extension-complexity lower bound is not a semidefinite one. Allowing an arbitrary affine slice of a positive semidefinite cone makes the model substantially stronger. A lower bound here would separate efficient optimization from compact exact SDP representation for a canonical tractable polytope.',
    'Identify a fundamental limitation of exact semidefinite optimization representations.',92,
    'Lower Bounds for Interactive Compression and Linear Programs','Makrand Sinha',2018,'Section 8.2.1, Open Question 8.4; definitions in Section 6.3.5.',
    'The source distinguishes the known linear extension lower bound from the open semidefinite target.')

add('49B','FIXP-hardness of exact Hylland–Zeckhauser equilibrium','game','reductions',
    'Is computing an exact Hylland–Zeckhauser equilibrium for a one-sided matching market FIXP-hard under the standard FIXP reductions?',
    'There are equally many agents and unit-supply goods with explicitly given nonnegative rational utilities. Each agent has budget one and consumes a lottery totaling one unit. At equilibrium the lotteries clear the market and maximize each agent’s expected utility subject to budget and unit-demand constraints. Exact equilibrium coordinates may be irrational. FIXP is the class of fixed-point search problems defined by algebraic circuits with rational constants and the standard arithmetic/max/min operations.',
    'The Hylland–Zeckhauser market turns random assignment into a pricing equilibrium with fairness and efficiency properties. Exact equilibrium is known to belong to FIXP, while approximation is PPAD-complete.\n\nThe source explicitly leaves exact FIXP-hardness open. This is not the already established hardness of approximate equilibrium, nor a claim that every exact output can be written as a short rational vector. An exact classification would identify the real-algebraic difficulty of this central assignment mechanism.',
    'Complete the exact complexity classification of an influential market mechanism with irrational equilibria.',88,
    'Computational Complexity of the Hylland–Zeckhauser Mechanism for One-Sided Matching Markets','Vijay V. Vazirani; Mihalis Yannakakis',2025,'Abstract and exact FIXP-hardness question.',
    'The journal version records FIXP membership, irrational examples and PPAD-completeness of approximation while leaving exact FIXP-hardness open.',
    issue='Copy the equilibrium tie-breaking/minimum-expenditure conventions and the complete FIXP reduction/output model from the source. The informal market equations alone do not specify the exact search reduction.')

add('50B','Strongly explicit Ramanujan families for every degree','structural','construction',
    'For every integer d≥3, is there an infinite family of connected d-regular Ramanujan graphs whose neighbor function is computable deterministically in poly(log n) bit operations?',
    'A d-regular graph is Ramanujan if every adjacency eigenvalue other than the trivial eigenvalues d and, in the bipartite case, −d has absolute value at most 2√(d−1). Strong explicitness means a vertex and a port index specify a neighbor without writing down the whole graph. The target permits a family of selected unbounded sizes rather than every admissible size; no positive additive slack in the eigenvalue bound is allowed.',
    'Ramanujan graphs achieve the optimal asymptotic spectral expansion bound for a fixed degree. Strong explicitness makes their local connectivity available with work polynomial in the vertex-label length.\n\nExplicit and strongly explicit almost-Ramanujan constructions are different from attaining the exact bound at every fixed degree. Alon’s paper carefully separates these guarantees. The personal list’s 2026 signing-preprint citation has been replaced: that preprint was withdrawn and did not support the construction target.',
    'Combine extremal spectral quality with efficient local access for arbitrary constant-degree expanders.',86,
    'Explicit expanders of every degree and size','Noga Alon',2020,'Definition of strong explicitness and comparison of exact versus near-Ramanujan constructions.',
    'The source constructs explicit or strongly explicit near-Ramanujan graphs with stated slack, not the general exact strongly explicit target.',url='https://arxiv.org/abs/2003.11673',related=('TCS-6874','TCS-6875'),
    issue='Specify a uniform family index, computability of its admissible sizes, vertex labels, rotation map and whether simple graphs are required. Avoid hiding graph-dependent advice in the neighbor function.')

add('53B','Does continuous local search have polynomial-time algorithms?','complexity','models',
    'Does every total search problem in CLS admit a deterministic polynomial-time solution algorithm, equivalently CLS⊆FP?',
    'CLS is the class of total search problems reducible in polynomial time to ContinuousLocalOpt, with the source’s polynomial-time representations and explicit Lipschitz and accuracy parameters. Solutions may be an approximate local optimum or a valid violation certificate for the supplied promises. FP here means a polynomial-time algorithm that returns a valid output on every instance, not equality between decision languages.',
    'Continuous local search formalizes a broad class of optimization tasks for which a local progress argument guarantees a solution. The equality CLS=PPAD∩PLS places that class simultaneously in two major total-search frameworks.\n\nThat classification does not provide a polynomial-time algorithm. The open target asks whether the common part is tractable, rather than whether the two classes intersect. Gradient-descent complexity supplies a concrete motivation for this algorithmic frontier.',
    'Determine the tractability of the common core of fixed-point search and potential-based local optimization.',93,
    'The Complexity of Gradient Descent: CLS = PPAD ∩ PLS','John Fearnley; Paul W. Goldberg; Alexandros Hollender; Rahul Savani',2021,'Definitions of ContinuousLocalOpt, CLS and the main equality theorem.',
    'The source establishes CLS=PPAD∩PLS, leaving polynomial-time solvability as a separate question.',
    issue='Reproduce the complete ContinuousLocalOpt instance and solution relation, including promise-violation outputs and circuit evaluation conventions, before certifying a self-contained class target.')

add('56A','Square-root logarithmic approximation for metric labeling','approximation','tightness',
    'Does a randomized polynomial-time algorithm exist giving an O(√log(k+2)) approximation for every metric-labeling instance with k labels?',
    'An instance consists of a finite undirected graph G=(V,E), nonnegative rational edge weights w_uv, a metric d on [k] supplied by its rational distance matrix, and nonnegative rational assignment costs c(v,i). A labeling f:V→[k] has cost Σ_v c(v,f(v))+Σ_{uv∈E}w_uv d(f(u),f(v)). The guarantee is cost(f)≤C√log(k+2)·OPT with probability at least 2/3 for a universal C. Running time on every random tape is polynomial in the entire binary input length; k is part of the input. No restriction on the metric or graph is promised.',
    'Metric labeling combines local assignment costs with penalties for assigning far-apart labels to neighboring vertices. It captures a broad family of classification and partitioning objectives.\n\nGeneral algorithms give logarithmic approximation, while the square-root logarithmic scale arises in hardness. Closing the gap would identify the approximation power of this general model. Results for a uniform, line or truncated metric leave arbitrary label metrics unresolved.',
    'Close a major gap for a general labeling objective linking metric geometry and approximation.',85,
    'A Linear Programming Formulation and Approximation Algorithms for the Metric Labeling Problem','Chandra Chekuri; Sanjeev Khanna; Joseph Naor; Leonid Zosin',2005,'General metric-labeling definition and O(log k) approximation; compare the Chuzhoy–Naor hardness paper linked in the original proposal.',
    'The source gives O(log k) approximation for arbitrary label metrics and sharper bounds for special metrics.',url='https://chekuri.cs.illinois.edu/papers/metric-labeling-sidma.pdf')

add('56B','Constant adaptivity gap for influence maximization with full feedback','beyond','models',
    'Is there a universal constant C such that OPT_adaptive(G,p,k)≤C·OPT_nonadaptive(G,p,k) for every independent-cascade influence instance under full-adoption feedback?',
    'The input is any finite directed graph, an independent retention probability p_e∈[0,1] for each edge, and a budget 1≤k≤|V|. Sample a live-edge subgraph once. A seed activates all vertices reachable from it along live edges. A nonadaptive strategy selects at most k seeds before observing the subgraph. An adaptive strategy selects seeds sequentially, observing after each choice the resulting activated set and the outcomes of edges explored by its completed cascade. Both objectives maximize the expected total number of activated vertices over strategies with no computational restriction. The expectation is over the live-edge graph and strategy coins. Failed transmissions into vertices already active reveal no additional state.',
    'Feedback may allow later interventions to respond to the success of earlier ones. The adaptivity gap measures the value of that information, independently of the difficulty of finding an optimal strategy.\n\nThe cited research obtains bounds for full-adoption feedback and distinguishes it from the myopic-feedback model, where constant bounds are known. A constant full-feedback gap would say that a preselected seed set always captures a fixed share of the best adaptive policy. The source model’s precise observation convention remains important.',
    'Determine whether sequential feedback changes influence-maximization power by an unbounded factor.',81,
    'Adaptive Influence Maximization: Bounding Adaptivity Gaps and Beyond','Debashmita Poddar',2023,'Full-adoption feedback and bounds for general graphs.',
    'The thesis reports a sublinear upper bound for general graphs and distinguishes myopic and full-adoption feedback.',url='https://iris.gssi.it/handle/20.500.12571/26964',
    issue='Verify and reproduce exactly which successful and failed edge states full-adoption feedback reveals in the selected source; activated-set-only and full explored-edge observations should not be silently identified.')

add('57A','Hamiltonian paths in all connected vertex-transitive graphs','structural','construction',
    'Does every finite nonempty connected vertex-transitive simple undirected graph have a Hamiltonian path?',
    'A graph is vertex-transitive if for every u,v there is a bijection of its vertex set preserving adjacency and sending u to v. A Hamiltonian path is an ordering of all vertices without repetition in which consecutive vertices are adjacent; the one-vertex graph is allowed. The target asks for existence, with no requirement to compute the path efficiently. It asks for a path rather than a cycle, and is not restricted to Cayley graphs.',
    'Vertex transitivity expresses complete local symmetry, but does not give an obvious global route visiting each vertex once. The Hamiltonian-path conjecture is a classical structural question connecting graph symmetry with spanning paths.\n\nIt lies within the atlas’s accepted graph-structure and path scope. Positive results for particular group actions or graph families do not settle the universal statement. The cycle variant has exceptional behavior and is not substituted for the path question.',
    'Resolve a canonical connection between graph symmetry and global spanning structure.',88,
    'Towards the Lovász conjecture via sublinear expanders','Matija Bucić; Micha Christoph; Alexey Pokrovskiy; Raphael Steiner',2026,'Introduction and statement of the general vertex-transitive Hamiltonian-path problem.',
    'The July 2026 revision proves a cycle-length lower bound of n^{2/3−o(1)} for general connected vertex-transitive graphs; it does not establish Hamiltonian paths.')

add('58A','The sunflower conjecture','misc','tightness',
    'For every integer r≥3, is there a real C_r>0 such that every family of more than C_r^k distinct k-element sets contains r members whose pairwise intersections are all equal, for every integer k≥1?',
    'The sets may lie in any finite universe. The r selected sets must be distinct. Their common pairwise intersection is called the core; removing it gives pairwise disjoint petals, which may include the empty set. C_r depends only on r, not on k, the universe or the family. No construction algorithm or bound on the universe size is required.',
    'Sunflowers capture a simple repeated pattern inside a large family of small sets. Bounds on their forced occurrence are basic tools in circuit complexity, pseudorandomness and kernelization.\n\nThe breakthrough bound of Alweiss, Lovett, Wu and Zhang replaces a much larger dependence by roughly (log k)^{O(k)} for fixed r. The conjecture asks for a constant base to the k-th power. This is admitted as a computationally motivated exception to the exclusion of general combinatorics, not to fill a combinatorics category.',
    'A general combinatorial principle with established applications to computational lower bounds and parameterized reductions.',89,
    'Improved sunflower bounds','Ryan Alweiss; Shachar Lovett; Kewen Wu; Jiapeng Zhang',2020,'Introduction, Erdős–Rado sunflower conjecture and computational applications.',
    'The source proves substantially improved bounds while leaving C_r^k open.')

add('59B','Tutte’s nowhere-zero 5-flow conjecture','structural','construction',
    'Does every finite bridgeless undirected multigraph admit an orientation and integer values f(e)∈{1,2,3,4} on its edges such that total incoming flow equals total outgoing flow at every vertex?',
    'Parallel edges and loops are allowed; a loop contributes once to each side of the conservation equation. An edge is a bridge if deleting it increases the number of connected components. Isolated vertices and disconnected graphs are permitted. An orientation chooses a direction for each nonloop edge. All equalities are ordinary integer equalities, not only congruences modulo five. No efficiency requirement is imposed on the orientation or flow.',
    'Nowhere-zero flows are a fundamental integral counterpart of graph coloring and circulation. The condition of having no bridges is necessary for a nonzero conserved flow and is the only hypothesis in Tutte’s conjecture.\n\nSeymour proved that six suffices for every bridgeless graph. Reducing the universal bound to five is a longstanding structural threshold, with a broad graph-theoretic role beyond one algorithm. Signed graphs and vector-valued flows give related questions but are not this target.',
    'Resolve a central universal threshold for integral graph flows, linking coloring and circulation structure.',88,
    'Nowhere-zero 6-flows','Paul Seymour',1981,'Main theorem and its relationship to Tutte’s 5-flow conjecture.',
    'Seymour establishes the universal nowhere-zero 6-flow theorem; the universal 5-flow statement is stronger.')

add('60B','An almost-linear bound on planar halving lines','geometry','tightness',
    'For every ε>0, does a constant C_ε exist such that every even n≥2 and every n-point set P⊂ℝ² with no three collinear determine at most C_ε n^(1+ε) halving lines?',
    'A halving line is the unique line through two distinct points of P with exactly (n−2)/2 of the remaining points in each open half-plane. Count distinct such lines, equivalently unordered endpoint pairs under the general-position hypothesis. Coordinates may be arbitrary real numbers. C_ε must be independent of n and P. This is an extremal counting question rather than the running time of a line-enumeration algorithm.',
    'Halving lines describe the combinatorial complexity of central levels in arrangements and of balanced geometric partitions. Their maximum number remains one of the central gaps in planar discrete geometry.\n\nThe almost-linear conjecture asks for n^{1+o(1)}, not a linear or polylogarithmic bound. The Open Problems Project connects the question with the broader k-set problem. Its consequences concern the size of geometric structures that algorithms must represent.',
    'Determine a basic geometric complexity bound underlying arrangements, levels and range-search structures.',88,
    'The Open Problems Project: k-Sets','Erik D. Demaine; Joseph S. B. Mitchell; Joseph O’Rourke, editors',2001,'Problem 7, planar k-sets and halving lines.',
    'The source records the unresolved gap between lower and upper bounds for halving lines.')

add('61A','Polynomial-time recognition of the 3-sphere','geometry','decision',
    'Is there a deterministic polynomial-time algorithm deciding whether a finite simplicial complex promised to triangulate a closed connected PL 3-manifold is PL-homeomorphic to the standard 3-sphere?',
    BIT+' The complex is represented by its vertex set and list of maximal tetrahedra, with all faces implicit. The promise requires each point of its realization to have a neighborhood PL-homeomorphic to ℝ³ and requires compactness, connectedness and no boundary. The standard PL 3-sphere is the boundary of a 4-simplex. PL-homeomorphism means that after finite subdivisions there is a simplicial isomorphism. Correctness is required on promised inputs; the time bound holds on all encodings.',
    'Sphere recognition is a canonical task in computational topology. Decidability is known, but a decision algorithm can still be far too expensive as a triangulation grows.\n\nThe source places 3-sphere recognition in NP, separating certificate length from the existence of an efficient search or decision algorithm. The target is polynomial time for arbitrary promised triangulations. Results about generic triangulations or short simplifications of small examples do not settle it.',
    'Determine the complexity of a basic three-dimensional topological recognition problem.',91,
    'Sphere recognition lies in NP','Saul Schleimer',2011,'Main theorem and recognition problem.',
    'The source establishes NP membership, not deterministic polynomial-time recognition.',url='https://arxiv.org/abs/math/0407047')

add('61B','Decidability of PL 4-sphere recognition','geometry','decision',
    'Is there a Turing algorithm that, for every finite simplicial complex promised to triangulate a closed connected PL 4-manifold, halts and decides whether it is PL-homeomorphic to the boundary of a 5-simplex?',
    'The input lists vertices and maximal 4-simplices, with all faces implicit. Its geometric realization is promised to be a compact connected PL 4-manifold without boundary. Two finite complexes are PL-homeomorphic when some finite subdivisions are simplicially isomorphic. The boundary of the 5-simplex fixes the standard PL structure on S⁴. No running-time bound is requested, and behavior outside the promise is unrestricted. Topological homeomorphism without preserving the PL category is a different target.',
    'Four dimensions are a special boundary for algorithmic manifold topology. Even the existence of a recognition procedure for the standard PL sphere is unresolved in the cited discussion.\n\nThe formulation fixes the PL category, avoiding confusion with topological or smooth recognition. Higher-dimensional undecidability theorems cannot simply be transferred to dimension four. Conversely, recognizing a topological sphere would not alone establish that a supplied PL structure is standard.',
    'Locate a foundational decidability boundary in computational topology.',92,
    'Frontiers of sphere recognition in practice','Michael Joswig; Davide Lofano; Frank H. Lutz; Mimi Tsuruga',2022,'Discussion of the unresolved recognition problem for the standard PL 4-sphere.',
    'The source distinguishes dimension-four sphere recognition from established recognition and undecidability results in other dimensions.')

add('62B','Distribution-free improper learning of two unrestricted halfspaces','learning','resources',
    'Can intersections of two halfspaces on {0,1}^n be PAC learned, with an arbitrary efficiently evaluable hypothesis, in time polynomial in n, the target description length and inverse accuracy?',
    'Each target is the conjunction of two integer-weight linear threshold functions on the Boolean cube; threshold weights and offsets use binary encoding. Samples are independent labeled examples from an arbitrary distribution on the cube, with realizable labels. The intended guarantee is error at most ε with success probability at least 2/3 using polynomial time in n, target encoding length and 1/ε. Membership queries are unavailable. There is no margin or factorization promise.',
    'A single halfspace is efficiently learnable, but combining only two thresholds introduces a longstanding computational obstacle. Allowing an arbitrary output representation avoids the known hardness of proper learning.\n\nThe existing TCS-6544 explicitly assumes a positive margin and polynomial dependence on its reciprocal. This candidate instead concerns unrestricted integer-weight thresholds on the Boolean cube. The distinction affects the running time and cannot be hidden behind their similar titles.',
    'Determine whether combining two elementary classifiers already defeats efficient distribution-free learning.',90,
    'The Intersection of Two Halfspaces Has High Threshold Degree','Alexander A. Sherstov',2009,'Background on improper learning of intersections of halfspaces; compare the original proposal’s broader learning source.',
    'The source distinguishes proper-learning hardness from the unresolved unrestricted-output learning question.',url='https://web.cs.ucla.edu/~sherstov/pdf/hshs.pdf',related=('TCS-6544',),
    issue='Confirm the original proposal’s domain convention against its source and specify how the learner receives a target-size bound and how arbitrary output hypotheses are represented and evaluated.')

add('63B','Learning decision trees from uniform random examples in polynomial time','learning','resources',
    'Is there a uniform randomized learner which, for all n,s≥1 and rational ε∈(0,1), learns every size-at-most-s Boolean decision tree on n variables from uniform random labeled examples in time poly(n,s,1/ε), with error at most ε and success probability at least 2/3?',
    'A decision tree has internal nodes querying one input coordinate, two outgoing edges labeled zero and one, and leaves labeled zero or one. Size counts all nodes. Samples are independent uniform x∈{0,1}^n labeled by the unknown target f. The learner receives n,s,ε and may draw samples but cannot request labels at chosen inputs. It outputs a Boolean circuit h of polynomial size, with Pr_{x uniform}[h(x)≠f(x)]≤ε on at least two thirds of runs. All sampling, computation, circuit writing and evaluation costs use classical bit operations; the total worst-case learning time has one polynomial bound.',
    'Decision trees are an elementary representation for Boolean classification. Uniform data removes distributional pathologies but still leaves open whether random examples suffice for fully polynomial learning.\n\nKalai and Teng contrast the unresolved uniform-distribution problem with their positive result for most perturbed product distributions. Chosen-input queries can provide information unavailable from examples alone. The existing proper-learning card allows membership queries and requires a tree output. This target permits improper output but removes that query access.',
    'Settle the sample-only computational learnability of a canonical interpretable Boolean model.',91,
    'Decision trees are PAC-learnable from most product distributions: a smoothed analysis','Adam Tauman Kalai; Shang-Hua Teng',2008,'Abstract and introduction: the unresolved uniform-example problem.',
    'The source learns from most randomly perturbed product distributions, leaving the fixed uniform distribution unresolved.',url='https://arxiv.org/abs/0812.0933',related=('TCS-0677',))

add('66A','Polynomial-time density estimation for arbitrary Gaussian mixtures','testing','resources',
    'Can every mixture of k Gaussians in ℝ^d be learned to total-variation error ε from independent samples in time and sample size polynomial in d,k,1/ε, without separation, weight or covariance-conditioning promises?',
    'The target distribution is Σ_{i=1}^k w_i N(μ_i,Σ_i), with w_i≥0, Σ_i w_i=1 and positive-definite covariance matrices. Total-variation distance between densities f and g is one half the integral of |f−g|. The learner may output a distribution outside the mixture class. The degree of the running-time polynomial must be independent of k, and parameter recovery is not required.',
    'Gaussian mixtures model data with several latent populations. Density estimation asks for an accurate distributional description even when individual components cannot be identified reliably.\n\nMoitra and Valiant establish polynomial learnability for a fixed number of components, with dependence on k that does not meet the joint polynomial target. Existing atlas cards concern compression-style unsupervised learning, robustness for fixed k, or separated parameter estimation. Those are different statistical goals.',
    'Resolve a central statistical-computational gap for latent-distribution learning without geometric separation.',92,
    'Settling the Polynomial Learnability of Mixtures of Gaussians','Ankur Moitra; Gregory Valiant',2010,'Density-estimation consequence and dependence on the number of components.',
    'The source gives polynomial-time density estimation for each fixed k; the runtime is not polynomial jointly in k.',related=('TCS-0683','TCS-5179','TCS-3391'),
    issue='Specify sample precision, bit versus real arithmetic costs and a usable representation of the improper output density; the short proposal does not fix these choices.')

add('67A','Statistically optimal sparse robust Gaussian mean estimation in polynomial time','learning','resources',
    'Is there a polynomial-time algorithm for ε-contaminated N(μ,I_d) samples, with k-sparse μ, achieving Euclidean error O(ε) from Õ(k log d/ε²) samples?',
    'The clean samples are independent draws from a d-dimensional Gaussian with identity covariance; at most an ε fraction may be replaced adversarially after observing them. A k-sparse mean has at most k nonzero coordinates. Success is intended with probability at least 2/3 over clean samples and algorithm coins for every such contamination. Runtime must be polynomial jointly in d,k and 1/ε, rather than having an exponent depending on k.',
    'Sparsity reduces the number of samples statistically needed to estimate a high-dimensional mean. Adversarial corruption creates a gap between that sample advantage and the guarantees of polynomial-time estimators.\n\nThe cited work develops sum-of-squares algorithms and lower-bound evidence for this gap. Their resource tradeoffs do not establish a universal polynomial-time algorithm at the stated statistical scale. The goal is distributional robustness, not a particular estimator or proof technique.',
    'Determine whether a fundamental sparse statistical model retains its sample efficiency under computationally efficient robust estimation.',88,
    'Robust Sparse Mean Estimation via Sum of Squares','Ilias Diakonikolas; Daniel M. Kane; Sushrut Karmalkar; Ankit Pensia; Thanasis Pittas',2022,'Sample-computation tradeoffs for robust sparse Gaussian means.',
    'The source gives algorithms with explicit sparsity and computation tradeoffs rather than the full stated optimum.',
    issue='Fix logarithmic factors in Õ, finite-precision sample access, the allowed ε range and uniform constants in O(ε). These affect a proof-checkable yes/no target.')

add('69B','Polylogarithmic ℓ₁ distortion for edit distance','strings','characterization',
    'Do constants C,c>0 exist such that, for every n≥2, there are a dimension D_n, a map f_n:{0,1}^n→ℝ^(D_n) and a scale a_n>0 satisfying a_n ED(x,y)≤∥f_n(x)−f_n(y)∥₁≤C(log n)^c a_n ED(x,y) for all x,y?',
    'ED is ordinary Levenshtein edit distance with unit-cost insertion, deletion and substitution; intermediate strings may have other lengths. The ℓ₁ norm is the sum of absolute coordinate values. The target places no polynomial bound on D_n and no construction or evaluation-time requirement on f_n. All constants C,c are uniform in n; the dimension, map and scale may depend on n. This asks for metric existence, not automatically an edit-distance algorithm.',
    'An embedding compares a difficult sequence metric with the additive geometry of ℓ₁. Polylogarithmic distortion would sharply improve the known structural representation of edit distance.\n\nThe Ostrovsky–Rabani construction gives subpolynomial distortion that is larger than polylogarithmic. The existence target is distinct from fast approximation algorithms: a nonconstructive embedding need not be efficiently evaluable. The convention includes substitutions explicitly.',
    'Resolve a central metric-embedding barrier for sequence comparison.',87,
    'Low Distortion Embeddings for Edit Distance','Rafail Ostrovsky; Yuval Rabani',2005,'Main embedding theorem and the remaining distortion gap.',
    'The source constructs an embedding with subpolynomial distortion, leaving the polylogarithmic endpoint open.',related=('TCS-6624',))

add('70B','Constant-factor entrywise ℓ₁ rank-k approximation with variable k','optimization','resources',
    'Is there a randomized polynomial-time algorithm and a universal constant C≥1 which return a rank-at-most-k matrix B satisfying ∥A−B∥₁≤C·min_{rank(B′)≤k}∥A−B′∥₁ for every rational matrix A and every input k?',
    'A∈ℚ^(m×n), 0≤k≤min(m,n), and ∥M∥₁=Σ_{i,j}|M_ij| is the entrywise norm. Success probability is at least 2/3. The approximation factor is independent of m,n,k; output rank may not exceed k. The running time must be polynomial jointly in the input matrix and k, not merely polynomial for each fixed k. The optimum ranges over real matrices.',
    'Entrywise absolute error is a standard robust alternative to squared reconstruction error. Exact rank control and a constant independent of k distinguish the target from bicriteria or rank-dependent guarantees.\n\nThe existing TCS-7008 asks for a near-optimal relative approximation and does not resolve the weaker but separately significant constant-factor tractability threshold with growing rank. Known fixed-k schemes permit a polynomial exponent depending on k and therefore do not meet this target.',
    'Determine whether robust low-rank compression remains computationally tractable with unrestricted target rank.',85,
    'A PTAS for ℓp-Low Rank Approximation','Frank Ban; Vijay Bhattiprolu; Karl Bringmann; Pavel Kolev; Euiwoong Lee; David P. Woodruff',2019,'Entrywise ℓ₁ low-rank approximation; compare later fixed-k approximation schemes.',
    'The source gives a relative approximation scheme whose dependence on rank does not meet a polynomial bound jointly in the input and k.',related=('TCS-7008',),
    issue='Fix rational-output accuracy and bit-complexity conventions, including polynomial-size representation of factors when the real optimum is irrational.')

add('71A','Explicit binary codes attaining the Gilbert–Varshamov bound','coding','construction',
    'For every fixed δ∈(0,1/2), can binary codes of relative distance at least δ and asymptotic rate at least 1−H₂(δ) be constructed deterministically in polynomial time?',
    'A binary block code maps distinct messages to distinct binary words of a common length n. Relative distance is the minimum Hamming distance divided by n; rate is log₂ of the number of messages divided by n. H₂ is binary entropy. Construction must give a succinct polynomial-time encoder rather than explicitly enumerate exponentially many codewords. No efficient decoder is required, and no improvement beyond the GV rate is requested.',
    'Random binary codes attain the Gilbert–Varshamov tradeoff, but an efficient deterministic construction remains a central explicit-coding question. It asks for access to optimal known objects, not a stronger information-theoretic existence bound.\n\nThe coding materials explicitly separate attaining the bound constructively from beating it existentially. The inherited TCS-1012 has a list-decoding-capacity source and a misleading distance-bound title; it is not used as a duplicate for this minimum-distance construction.',
    'Turn the basic random-code rate-distance guarantee into an efficiently usable explicit family.',94,
    'Essential Coding Theory (draft of 26 August 2025)','Venkatesan Guruswami; Atri Rudra; Madhu Sudan',2025,'Binary rate-distance bounds and explicit construction at the GV bound.',
    'The materials identify explicit binary GV construction separately from list decoding and the existential rate-distance question.',url='https://cse.buffalo.edu/faculty/atri/courses/coding-theory/book/web-coding-book.pdf',related=('TCS-1012',),
    issue='Specify the family’s block-length indexing and uniformity, how δ is supplied or fixed, and the rate-convergence convention. Avoid silently restricting the proposal to linear codes.')
