add('76B','Average-case hardness of multiplicatively approximating Gaussian permanents','quantum','reductions',
    'Is multiplicative approximation of the permanent of an independent complex Gaussian matrix, on a sufficiently large fraction of instances, #P-hard under randomized polynomial-time reductions as in the Permanent-of-Gaussians Conjecture?',
    'For X∈ℂ^(n×n), Per(X)=Σ_{σ∈S_n}∏_i X_(i,σ(i)). The entries are independent standard complex Gaussians. The GPE× task receives accuracy and failure parameters ε,δ and should return z with |z−Per(X)|≤ε|Per(X)| on at least a 1−δ fraction of matrices. This concerns the complex permanent itself; hardness of worst-case permanent evaluation or additive approximation alone does not give this claim.',
    'Boson-sampling probabilities are governed by matrix permanents. Average-case hardness addresses whether the apparent difficulty persists on the random matrices relevant to that model.\n\nAaronson and Arkhipov state the Permanent-of-Gaussians Conjecture separately from their anti-concentration conjecture. The distinction matters: neither the worst-case #P-completeness of the permanent nor an assumption about tiny probabilities establishes the average-case reduction.',
    'Establish a major complexity foundation for a restricted quantum sampling model.',94,
    'The Computational Complexity of Linear Optics','Scott Aaronson; Alex Arkhipov',2013,'Definition of GPE× and the Permanent-of-Gaussians Conjecture.',
    'The source isolates the average-case hardness assumption used in its approximate-sampling consequences.',url='https://arxiv.org/abs/1011.3245',
    issue='Reproduce the oracle reduction quantifiers, dependence on ε and δ, and discretization of Gaussian inputs and complex outputs from the source before certifying a bit-model statement.')

add('77B','Classical simulation of polynomial-gap local stoquastic adiabatic computation','quantum','models',
    'Can every polynomial-time adiabatic computation described by explicit local stoquastic Hamiltonians with an inverse-polynomial global spectral gap be sampled classically in polynomial time to inverse-polynomial total-variation error?',
    'A Hamiltonian is stoquastic in the computational basis when every off-diagonal matrix entry is real and nonpositive. The intended input describes a smoothly varying sum of terms acting on a constant number of qubits, an efficiently preparable initial ground state and computational-basis measurement at the end. The gap is the separation of the lowest two eigenvalues of the full Hamiltonian, not only a symmetry-restricted subspace. The intended simulator is uniform randomized classical computation.',
    'Stoquasticity removes a sign obstruction that often complicates classical statistical simulation. Whether that suffices for efficient simulation of general explicit local adiabatic computations remains a basic question about the source of quantum computational power.\n\nBringewatt and Jarret study obstructions based on symmetry sectors and obtain subexponential simulations for those examples. Their result does not establish a general polynomial-time simulation theorem. Oracle-model separations also require care before being transferred to explicitly supplied local interactions.',
    'Determine the computational power of a central restricted adiabatic model.',90,
    'Effective Gaps Are Not Effective: Quasipolynomial Classical Simulation of Obstructed Stoquastic Hamiltonians','Jacob Bringewatt; Michael Jarret',2020,'Abstract, simulation model and distinction between effective and global gaps.',
    'The source simulates a class of previously obstructed examples without resolving the general explicit-local polynomial-time target.',
    issue='Specify Hamiltonian-path encoding, precision, derivative and norm bounds, gap and ground-state uniqueness promises, initialization and exact sampling accuracy quantifiers. The local-input version must be kept separate from oracle-input results.')

add('80A','Exponential parallel repetition for every two-player entangled game','quantum','tightness',
    'For every finite two-player one-round game G with ω*(G)<1, does a constant c_G>0 exist such that ω*(G^⊗k)≤exp(−c_G k) for every integer k≥1?',
    'G consists of finite nonempty question and answer sets X,Y,A,B, a probability distribution μ on X×Y and a predicate V:X×Y×A×B→{0,1}. The players share an arbitrary finite-dimensional bipartite quantum state and, without communicating, answer their individual questions using local positive-operator-valued measurements. Such a measurement is a finite family of positive semidefinite operators summing to the identity; outcome probabilities obey the Born rule. ω* is the supremum of the winning probability over all finite dimensions, states and measurements. G^⊗k samples k independent question pairs; the players receive their entire question tuples and win only if every coordinate passes V. Their measurements may act jointly across coordinates. The constant may depend on the entire game, with no uniform rate across games required.',
    'Parallel repetition is supposed to amplify the soundness of a verification game. Entangled strategies can correlate answers across repeated instances, making the amplification theorem substantially different from its classical counterpart.\n\nThe source develops parallel repetition for entangled games and identifies the general exponential-decay challenge. Later convergence-to-zero results and exponential theorems for restricted game classes do not prove this universal rate. The existing TCS-5077 concerns the weaker convergence question.',
    'Resolve a central soundness-amplification barrier for entangled interactive proofs.',94,
    'Parallel Repetition of Entangled Games','Julia Kempe; Thomas Vidick',2011,'Introduction and scope of the parallel-repetition bounds.',
    'The source establishes decay guarantees with restrictions or weaker rates, leaving the universal exponential statement distinct.',related=('TCS-5077',))

add('81B','Publicly verifiable quantum money from quantum-secure LWE alone','quantum','assumptions',
    'Does polynomial-hard Learning With Errors against quantum polynomial-time adversaries suffice for publicly verifiable quantum money, without obfuscation or any other computational assumption?',
    'A bank generates a public verification key and a secret minting key. A banknote consists of a serial number and a quantum state. Anyone can verify it using the public key, while a polynomial-time quantum counterfeiter given valid notes should not produce more accepted notes than it received. The intended construction is in the standard model, with no ideal random oracle and no extra trusted setup.',
    'Quantum money seeks a publicly checkable object that cannot be copied even by its legitimate holder. Deriving that property from a familiar lattice assumption would substantially clarify its cryptographic foundations.\n\nThe cited construction of anonymous public-key quantum money uses additional assumptions, including obfuscation. Anonymous notes and voting are consequences of a stronger construction; their existence under those assumptions does not establish ordinary public quantum money from LWE alone.',
    'Base quantum unclonability with public verification on a standard computational assumption.',89,
    'Anonymous Public-Key Quantum Money and Quantum Voting','Alper Çakan; Vipul Goyal; Takashi Yamakawa',2024,'Abstract and assumptions of the public-key money construction.',
    'The construction uses assumptions beyond quantum-secure LWE.',
    issue='Specify LWE parameters and the full quantum counterfeiting experiment, including minting access, note verification/reusability, correctness error and adaptive adversary access.')

add('82A','Nearly quadratic bit complexity for perfectly secure asynchronous Byzantine agreement','parallel','resources',
    'Is there a randomized asynchronous binary Byzantine-agreement protocol tolerating every t<n/3 with perfect security and expected Õ(n²) communication bits, using private authenticated channels and no setup?',
    'There are n processes with binary inputs and reliable asynchronous point-to-point channels. Byzantine processes may deviate arbitrarily; honest processes must agree, and if all honest inputs equal b then their decision must be b. Perfect security requires zero probability of a safety violation against computationally unbounded adversaries, with almost-sure termination under fair delivery. Communication is to be measured for honest processes; faulty processes cannot be charged a bounded number of arbitrary transmissions.',
    'Byzantine agreement is a basic fault-tolerance primitive. Nearly quadratic communication with optimal resilience and information-theoretic security would combine the strongest correctness guarantee with a fundamental efficiency scale.\n\nABEL obtains efficient multivalue extension given a binary agreement primitive. Its extension overhead is not a complete binary protocol with that communication bound. The candidate keeps the underlying binary agreement question separate from the solved extension result.',
    'Close a basic communication gap for agreement without computational trust assumptions.',88,
    'ABEL: Perfect Asynchronous Byzantine Extension from List-Decoding','Ittai Abraham; Gilad Asharov',2025,'Introduction, binary agreement primitive and extension communication cost.',
    'The paper solves the multivalue extension overhead relative to an assumed binary agreement protocol.',
    issue='Fix adaptive-corruption and erasure conventions, the adversary’s access to honest channel traffic and randomness, admissible fairness, logarithmic factors and termination-time requirements.')

add('83B','Quadratic expected message complexity for asynchronous crash consensus','parallel','resources',
    'Does a randomized asynchronous binary consensus protocol exist with expected O(n²) messages against a strong adaptive adversary, tolerating every t<n/2 crash failures?',
    'The n processes communicate by reliable asynchronous point-to-point messages and start with binary inputs. A crashed process takes no further steps. Every process that does not crash must eventually decide with probability one under fair scheduling; all decisions agree, and when all initial inputs are b every decision is b. A strong adversary observes past states, messages and revealed random outcomes and chooses subsequent process steps, message deliveries and crashes without seeing future coins. The bound counts all messages sent before protocol termination and must hold in expectation for every admissible adversary. It does not impose a bit bound on each message.',
    'Randomization makes asynchronous agreement possible despite crash failures, but robustness to a strong scheduler affects its communication cost. A quadratic bound would reach a central efficiency frontier in the standard message-passing model.\n\nAlistarh, Aspnes, King and Saia give nearly quadratic expected communication against a strong adversary. Their logarithmic overhead is not a proof of the exact quadratic target. This question concerns crash failures, separately from Byzantine behavior or private-channel security.',
    'Determine the fundamental message cost of randomized agreement under adversarial asynchrony.',85,
    'Communication-Efficient Randomized Consensus','Dan Alistarh; James Aspnes; Valerie King; Jared Saia',2017,'Main message-complexity theorem and strong-adversary model.',
    'The source gives O(n² log² n) expected messages in its model, leaving the quadratic endpoint unresolved.',
    issue='Reconcile the precise t-dependent constants, stop condition and validity convention with the journal model; specify whether the protocol knows n and t and whether computation and message sizes have additional constraints.')

add('84A','Robustness of the deterministic consensus hierarchy','parallel','characterization',
    'Can combining deterministic shared-object types yield a wait-free consensus number strictly larger than the maximum consensus number of the types used separately?',
    'The intended hierarchy permits any number of instances of a type and atomic read/write registers. Its consensus number is the largest process count for which deterministic wait-free binary consensus can be implemented; it is infinite when all finite counts are possible. Combining types means allowing instances of each type in one implementation. Wait freedom requires completion after finitely many steps of each participating nonfaulty process regardless of other process speeds or crashes. The target excludes nondeterministic shared objects.',
    'Consensus number measures the synchronization power of a shared-memory primitive. Robustness asks whether that power composes: can several individually weak primitive types jointly become stronger?\n\nThe book distinguishes the refined hierarchy used here from an earlier nonrobust version. Counterexamples using nondeterministic objects also do not settle the deterministic question. The hierarchy’s definition is therefore part of the mathematical problem, not a terminology choice.',
    'Determine whether a central measure of synchronization power behaves consistently under composition.',88,
    'Algorithms for Concurrent Systems (course manuscript)','Rachid Guerraoui; Petr Kuznetsov',2018,'Consensus hierarchy chapter, robustness discussion and historical notes.',
    'The discussion separates known nonrobust variants and nondeterministic counterexamples from the deterministic refined-hierarchy question.',
    issue='Copy the refined consensus-number definition, allowed object initializations, deterministic type semantics and process-access restrictions; the older one-object hierarchy is not interchangeable with this model.')

add('84B','Wait-free queues from two-process consensus objects','parallel','models',
    'For every finite n≥2, can a linearizable unbounded FIFO queue with n unrestricted enqueuers and dequeuers be implemented deterministically and wait-free using atomic registers and two-process consensus objects?',
    'A queue begins empty. Enqueue(v) appends a finite binary value; dequeue returns and removes the oldest remaining value, or returns EMPTY when none remains. Linearizability requires every finite concurrent history to extend to a sequential legal queue history consistent with the real-time order of nonoverlapping completed calls. Wait freedom requires each call by a process that continues taking steps to finish after finitely many of its own steps, regardless of delays or crashes elsewhere. A two-process consensus object accepts at most one proposal from each of two designated processes and returns one proposed value consistently to both; processes may use arbitrarily many objects and registers. No stronger primitive, randomization or bound on total queue length is supplied.',
    'A queue has consensus number two, but that upper bound does not automatically give an implementation from consensus objects of the same level. The question tests the completeness of level two for a basic concurrent data structure.\n\nEisenstat implements a queue with only two possible enqueuers in Common2. General queues permit every process to enqueue and dequeue repeatedly, so that restriction does not settle the target. The process count may affect the implementation, which must support arbitrarily long histories.',
    'Clarify the relation between synchronization power and implementability of a canonical concurrent object.',86,
    'Two-enqueuer queue in Common2','David Eisenstat',2009,'Abstract and distinction between two-enqueuer and unrestricted queues.',
    'The source implements the two-enqueuer case while leaving the unrestricted queue question open.')

add('85B','Compact routing at stretch 2k−1 and n^(1/k) storage','parallel','resources',
    'For every integer k≥2, do universal graph-routing schemes exist with stretch at most 2k−1 and Õ(n^(1/k)) words of routing information per vertex, without a preliminary handshake?',
    'A routing scheme preprocesses a connected undirected weighted graph and assigns local routing tables and destination labels. During a route, each vertex chooses an outgoing port using only its local table, the destination label and a bounded packet header. Stretch bounds routed length divided by shortest-path distance for every ordered pair. The intended model permits topology-dependent labels; it is not name-independent routing, and a global distance oracle alone is insufficient.',
    'Compact routing asks how much global network knowledge must be stored locally to deliver paths close to shortest. The proposed space-stretch curve is a central target connecting routing with sparse distance representations.\n\nChechik improves the achievable stretch in this storage range while retaining a gap to 2k−1. The existing TCS-5770 instead extracts an extremal girth-construction question; that graph-existence target does not provide routing tables, labels or packet forwarding.',
    'Reach a basic space-versus-route-quality frontier for distributed network representations.',86,
    'Compact Routing Schemes with Improved Stretch','Shiri Chechik',2013,'Main routing guarantees and comparison with the desired 2k−1 stretch.',
    'The source improves routing guarantees without attaining this universal space-stretch endpoint.',related=('TCS-5770',),
    issue='Specify weight encoding, word size, admissible destination labels and header length, preprocessing costs and constants depending on k; confirm the exact no-handshake model.')

add('87B','A recursively enumerable theory for an effective continuous lambda-model','semantics','characterization',
    'Does an effective model of the untyped λ-calculus in Scott’s continuous semantics have a recursively enumerable equational theory?',
    'The equational theory of a model is the set of encoded pairs of λ-terms with equal denotations, under the source’s convention for free variables. Recursively enumerable means that a Turing machine can enumerate exactly those pairs. A continuous model interprets function abstraction and application using a reflexive object in an appropriate category of domains and continuous maps. Effectiveness is the additional computability structure defined in the source, not merely a countable presentation.',
    'Denotational semantics assigns mathematical meanings to programs. An enumerable complete equality theory would connect those meanings to a mechanically enumerable calculus of program equations.\n\nBerline, Manzonetto and Salibra rule out recursively enumerable order theories for their effective models and obtain stronger equational impossibility results in stable settings. The order theory and equality theory are different objects, and Scott-continuous semantics is broader than the stable settings covered by those negative theorems.',
    'Locate a basic boundary between effective semantic models and effective equational reasoning.',84,
    'Effective lambda-models vs recursively enumerable lambda-theories','Chantal Berline; Giulio Manzonetto; Antonino Salibra',2008,'Definition of effective models and open questions after the equational-theory results.',
    'The source distinguishes its negative order-theory results from the remaining continuous equational-theory question.',
    issue='Include the exact effective-domain presentation, reflexive-object operations and computability conditions, together with the source convention for open-term equality.')

add('88B','An absolutely unorderable nontrivial combinatory algebra','semantics','construction',
    'Does a combinatory algebra A with at least two elements exist such that every combinatory algebra B admitting an embedding of A has only the equality relation as a compatible partial order?',
    'A combinatory algebra consists of a set, a total binary application operation and distinguished elements K,S satisfying (Kx)y=x and ((Sx)y)z=(xz)(yz) for all x,y,z. Parentheses specify the application order. An embedding is an injective map preserving application and both distinguished elements. A compatible partial order is a reflexive, antisymmetric, transitive relation ≤ such that x≤x′ and y≤y′ imply xy≤x′y′. The target quantifies over B of arbitrary cardinality and every such embedding. No countability, effectiveness or additional extensionality axiom is required.',
    'Order-theoretic models underlie much of the semantics of untyped computation. Absolute unorderability would exhibit an algebra whose equations cannot be faithfully retained inside any nontrivially ordered combinatory model.\n\nSelinger distinguishes unorderability of one algebra from the stronger prohibition on all embeddings into ordered extensions. The former does not answer the latter: an algebra with only a discrete compatible order can still embed in an orderable extension. The target is the combinatory-algebra version explicitly stated in the source.',
    'Test a foundational limitation of order-theoretic semantics for universal untyped computation.',82,
    'Order-Incompleteness and Finite Lambda Reduction Models','Peter Selinger',2003,'Section 3 and Definition in Section 3.1: absolute unorderability.',
    'The source characterizes absolute unorderability algebraically but leaves existence in combinatory algebra open.')

add('91A','Bell nonlocality from finitely many copies of every entangled state','quantum','characterization',
    'For every entangled finite-dimensional bipartite state ρ, do finitely many copies ρ^⊗k and local filters suffice to produce correlations violating a Bell inequality, without an auxiliary entangled state?',
    'A state is a positive semidefinite trace-one operator on H_A⊗H_B. It is entangled when it is not a convex combination of product states. Local filters are trace-nonincreasing completely positive maps F_A,F_B applied to the respective k-fold systems before measurement questions are selected; the joint success probability must be positive. Normalize the successful filtered state. Each party then chooses a local measurement from a finite set of positive-operator-valued measurements. The resulting conditional distribution p(a,b|x,y) is Bell-nonlocal when it has no representation Σ_λ q_λ p_A(a|x,λ)p_B(b|y,λ), with nonnegative q_λ summing to one. Such a representation is precisely a local hidden-variable model for finite questions and answers. Local ancillary states and shared randomness are allowed, but no additional shared entangled state is supplied.',
    'Entanglement and observable Bell nonlocality are related but distinct resources. This question asks whether repeated access to the same entanglement always reveals nonlocal behavior after local preprocessing.\n\nLiang, Masanes and Rosset prove an activation result using a suitable auxiliary state. That resource is stronger than additional copies of the given state and is expressly excluded here. Direct one-copy Bell tests also do not settle the finite-copy filtered target.',
    'Determine whether every bipartite entangled state has an intrinsic finite-copy nonlocal manifestation.',93,
    'All entangled states display some hidden nonlocality','Yeong-Cherng Liang; Lluís Masanes; Denis Rosset',2012,'Introduction and auxiliary-state activation theorem.',
    'The source establishes activation with an additional state while distinguishing the unresolved repeated-copy setting.')

add('94B','Decidability with two parametric clocks and arbitrarily many integer parameters','automata','decision',
    'Is reachability decidable for discrete-time parametric timed automata with at most two parametric clocks and an arbitrary finite number of nonnegative integer parameters?',
    'An input has finitely many locations, clocks initially zero, parameter symbols, guarded transitions and an initial and target location. A time-elapse step adds the same nonnegative integer to every clock. A transition guard is a conjunction of comparisons x⋈c or x⋈p, where c is a nonnegative integer, p a parameter and ⋈∈{<,≤,=,≥,>}; the transition may reset designated clocks to zero. Other clocks are unchanged. At most two clocks appear in comparisons to parameters; arbitrarily many clocks compared only with constants are allowed. A parameter valuation assigns a nonnegative integer to every parameter once for the entire run. The algorithm must halt on every finite binary encoding and answer whether some valuation permits a finite run to the target. This transition-guard presentation has no extra diagonal or parameter-arithmetic guards.',
    'Parametric clocks describe systems whose timing constants are not fixed in advance. Decidability asks whether some assignment of those constants can make a target behavior reachable.\n\nGöller and Hilaire establish EXPSPACE-completeness with two parametric clocks and one parameter in discrete time. They explicitly leave arbitrary numbers of parameters open. Dense-time results and infinite-word acceptance questions use different semantics and cannot be substituted for this finite-reachability target.',
    'Resolve a longstanding decidability boundary in timing-parameter synthesis.',88,
    'Reachability in Two-Parametric Timed Automata with one Parameter is EXPSPACE-Complete','Stefan Göller; Mathieu Hilaire',2023,'Definitions and concluding open question on arbitrarily many parameters.',
    'The source settles one parameter and explicitly leaves the multiple-parameter case open.')

add('96B','Unconditional decidability of exact time-bounded CTMDP reachability','semantics','decision',
    'Is there an unconditional algorithm deciding whether the optimal probability of reaching a designated target by rational time T in a finite rational-rate continuous-time Markov decision process is at least a rational threshold p?',
    'A CTMDP has a finite state set, finitely many available actions and nonnegative rational transition rates. A policy resolves action choices based on admissible observations of the elapsed-time stochastic process. Reachability asks whether a target state is visited by the deadline, and the optimum is over all policies in the selected model. The comparison is exact; producing an additive approximation to the optimum alone does not decide threshold equality.',
    'Quantitative verification often asks whether a stochastic system meets a probability requirement before a deadline. Exact comparison creates difficulties that can survive even for a finite model with rational data.\n\nMajumdar, Salamati and Soudjani prove decidability conditional on Schanuel’s conjecture. They also connect an unconditional decision procedure to the bounded continuous Skolem problem. The conditional theorem and numerical approximation algorithms do not establish an unconditional exact test.',
    'Settle a foundational exact-verification question for continuous-time controlled stochastic systems.',89,
    'On Decidability of Time-Bounded Reachability in CTMDPs','Rupak Majumdar; Mahmoud Salamati; Sadegh Soudjani',2020,'Model definition, threshold problem and conditional decidability theorem.',
    'The source proves decidability under Schanuel’s conjecture and identifies an unconditional decidability barrier.',
    issue='Specify the precise scheduler class, whether actions may change during residence in a state, and threshold strictness from the source; include the induced probability measure and supremum/attainment convention.')

add('99A','Does choiceless polynomial time with counting capture PTIME?','database','characterization',
    'Is every isomorphism-invariant polynomial-time property of finite relational structures definable in choiceless polynomial time with counting?',
    'The input is a finite structure over a fixed finite relational vocabulary, without a supplied linear order. Invariance means that relabeling its elements preserves the property. PTIME is measured on explicit relational encodings; the machine deciding a property may use the encoding order, but its answer must be invariant. The intended choiceless model operates on hereditarily finite sets built from input atoms, with counting and polynomial bounds on the active objects and execution time. No arbitrary selection of a representative from an unordered set is available.',
    'Capturing polynomial time without relying on an arbitrary input order is a central problem of descriptive complexity. Choiceless computation is a concrete candidate formalism rather than an unspecified future logic.\n\nBlass, Gurevich and Shelah introduce the model and analyze limits of computation without choices. Adding counting is part of this candidate’s target; negative results for the version without counting do not settle it. Particular graph families likewise do not establish capture on all finite structures.',
    'Test a leading concrete candidate for an order-independent characterization of polynomial-time computation.',94,
    'Choiceless Polynomial Time','Andreas Blass; Yuri Gurevich; Saharon Shelah',1999,'Machine model and discussion of the counting extension.',
    'The source develops choiceless polynomial computation and distinguishes the additional role of counting.',
    issue='Reproduce the exact syntax and operational semantics of the counting extension, its active-object size measure and uniform polynomial clock. A high-level model name is insufficient for completed formulation review.')

add('99B','Fixed-parameter tractability of graph isomorphism by rank-width','parameterized','resources',
    'Do a computable function f:ℕ→ℕ, an absolute constant c and a deterministic algorithm exist which decide isomorphism of graphs G,H in time f(k)(|V(G)|+|V(H)|+2)^c, where k=max(rw(G),rw(H))?',
    'Graphs are finite simple undirected graphs given by adjacency matrices. Isomorphism is a vertex bijection preserving adjacency. For a graph G and X⊆V(G), the cut-rank is the rank over the two-element field of the adjacency submatrix with rows X and columns V(G)∖X. A rank decomposition is a tree of maximum degree three whose leaves are bijectively labeled by V(G). Every tree edge partitions the leaves and hence defines a cut-rank; the decomposition width is the maximum of those ranks. Rank-width rw(G) is the minimum width, with rw(G)=0 for at most one vertex. No decomposition or parameter value is supplied to the algorithm. The exponent c is independent of the rank-width.',
    'Rank-width measures graph complexity through low-rank adjacency cuts and supports many structural algorithms. Graph isomorphism on bounded rank-width is tractable at each fixed width, but that does not by itself yield one exponent independent of the parameter.\n\nNeuen’s 2026 survey identifies the remaining parameterized isomorphism frontiers. An n^{g(k)} algorithm or a quasipolynomial dependence involving n does not establish fixed-parameter tractability. The target concerns testing isomorphism, without additionally demanding canonization.',
    'Resolve a major parameterized isomorphism boundary for a broad graph-decomposition measure.',88,
    'Parameterized complexity of graph isomorphism testing','Daniel Neuen',2026,'Rank-width section and open fixed-parameter tractability question.',
    'The survey distinguishes known parameter-dependent-exponent algorithms from the remaining FPT target.')

add('100B','Does ETH imply Gap-ETH?','fine','assumptions',
    'Does the deterministic Exponential Time Hypothesis imply the deterministic Gap Exponential Time Hypothesis for sparse 3-CNF formulas?',
    'For a 3-CNF formula F with n variables, let val(F) be the maximum fraction of clauses simultaneously satisfiable. The ETH convention here asserts that there is c>0 for which no deterministic algorithm decides satisfiability of all 3-CNF formulas in time O(2^(cn) poly(L)), where L is the binary encoding length. Gap-ETH asserts that there exist constants B≥1, δ∈(0,1) and c′>0 for which no deterministic algorithm in time O(2^(c′n) poly(L)) distinguishes val(F)=1 from val(F)≤1−δ on formulas with at most Bn clauses. Its inputs are promised to satisfy one of those two alternatives. Empty formulas are satisfiable. All constants are fixed independently of F; randomized versions are not asserted.',
    'ETH concerns exact satisfiability, while Gap-ETH postulates comparable exponential hardness even when unsatisfiable inputs violate a fixed fraction of clauses. Their equivalence would unify many exact and approximation lower-bound assumptions.\n\nBitansky and coauthors distinguish ETH from the stronger gap hypothesis while obtaining exponential hardness for particular approximation tasks. Hardness for those tasks does not imply a gap-preserving sparse 3-CNF statement. This implication is distinct from asking whether either hypothesis is true.',
    'Clarify whether a major approximation-hardness assumption adds strength to the standard exact exponential-time hypothesis.',93,
    'Dot-Product Proofs and Their Applications','Nir Bitansky; Prahladh Harsha; Yuval Ishai; Ron D. Rothblum; David J. Wu',2024,'Section 3.3 and the comparison of ETH with Gap-ETH.',
    'The source separates its ETH-based approximation consequences from the general Gap-ETH assumption.',related=('TCS-6593','TCS-6738'),
    note='The positive-exponent ETH convention is stated explicitly; the original shorthand 2^{o(n)} is not used to hide a quantifier choice.')
