add('3B','Linear-time minimization of deterministic finite automata','automata','resources',
    'For every fixed integer a≥2, is there a deterministic word-RAM algorithm that minimizes every complete n-state DFA over [a] in O(n) worst-case time?',
    RAM+' Here w=⌈2 log₂(n+2)⌉. The input gives n, a transition table δ:[n]×[a]→[n], an initial state and n accepting-state bits. A word is accepted when its successive transitions from the initial state end in an accepting state. The output is a complete DFA for exactly the same language with the fewest possible states. Unreachable states may be removed. The time constant may depend on a; it cannot depend on n or the automaton.',
    'Minimization asks for the smallest deterministic recognizer of a regular language, a basic operation in language processing and finite-state verification. Hopcroft’s algorithm gives O(n log n) time for a fixed alphabet.\n\nThe remaining question concerns unrestricted sequential algorithms in an explicit RAM model. Lower bounds for a particular partition-refinement framework do not establish a lower bound for every such algorithm. The unary-alphabet special case does not resolve the fixed alphabet of size at least two.',
    'Determine the intrinsic sequential cost of a canonical finite-state operation, beyond the limitations of its classical algorithmic framework.',84,
    'Minimization of Symbolic Automata','Loris D’Antoni; Margus Veanes',2014,'Introduction and classical DFA minimization comparison; the word-RAM target is an explicit editorial model convention.',
    'The paper uses Hopcroft’s O(a n log n) algorithm as the classical baseline and distinguishes symbolic alphabets from ordinary finite alphabets.')

add('4B','Strassen’s asymptotic rank conjecture for concise cubic tensors','algebra','resources',
    'For every n≥1 and every tensor T∈ℂ^n⊗ℂ^n⊗ℂ^n whose three flattenings all have rank n, is lim_{k→∞} R(T^⊗k)^(1/k)=n?',
    'R(T) is the least r such that T=Σ_{i=1}^r a_i⊗b_i⊗c_i with a_i,b_i,c_i∈ℂ^n. Each flattening views the tensor as a linear map from the dual of one factor into the tensor product of the other two. In T^⊗k the first, second and third tensor factors are respectively grouped, producing a tensor with three factors ℂ^(n^k). Submultiplicativity of rank makes the displayed limit equal to inf_{k≥1} R(T^⊗k)^(1/k). This is exact rank over ℂ, not border rank, and there is no explicitness or computational requirement on T.',
    'Matrix rank has a simple algebraic characterization, whereas tensor rank changes substantially when many independent copies are considered jointly. Strassen’s conjecture says that in the asymptotic setting the three flattening dimensions already determine the answer.\n\nThe cubic concise formulation is the target proposed in the personal list. It includes matrix-multiplication tensors, so a positive resolution would imply matrix multiplication exponent two; the reverse implication is not claimed. The 2024–2026 source studies structural properties of asymptotic rank without proving this equality.',
    'A structural conjecture about the cost of all bilinear computations, extending well beyond one matrix-multiplication algorithm.',95,
    'Asymptotic tensor rank is characterized by polynomials','Matthias Christandl; Koen Hoeberechts; Harold Nieuwboer; Péter Vrana; Jeroen Zuiddam',2024,'Introduction, asymptotic rank conjecture; consult the displayed revision history for the later version.',
    'The source establishes algebraic characterizations and upper semicomputability properties of asymptotic rank; the general conjecture is retained.',related=('TCS-0007',))

add('6B','Linear-time directed shortest paths with positive integer weights','structural','resources',
    'Is there a uniform deterministic word-RAM algorithm which computes all single-source distances in every directed graph with positive integer edge weights in O(m+n) worst-case time?',
    RAM+' The graph has vertex set [n], m explicitly listed directed edges, a designated source s, and weights in {1,…,2^w−1}, with w≥⌈log₂(n+m+2)⌉. Parallel edges and loops are allowed. A distance is the minimum sum of weights on a directed s-to-v path, or infinity if no such path exists. Finite distances can be represented in at most two words; output costs count. The algorithm must work for every w with a universal constant in O(m+n).',
    'Positive weights make directed shortest paths a fundamental optimization primitive, yet direction obstructs the classical linear-time result for undirected integer-weighted graphs. The target removes all superlinear overhead in the integer RAM model.\n\nRecent algorithms break the sorting barrier for directed real-weighted shortest paths. Their sublogarithmic overhead and the later almost-linear results are substantial advances, but neither “almost linear” nor “nearly linear” means O(m+n). This card fixes the weight representation and charges preprocessing.',
    'Settle whether directed weighted reachability has the same input-linear cost as its basic unweighted counterpart in the integer model.',90,
    'Breaking the Sorting Barrier for Directed Single-Source Shortest Paths','Ran Duan; Jiayi Mao; Xiao Mao; Xinkai Shu; Longhui Yin',2025,'Main theorem and computational model; integer-word target distinguished from the paper’s comparison-addition model.',
    'The source gives a deterministic O(m log^(2/3) n) algorithm for nonnegative real weights; it does not give linear integer-word time.')

add('11B','Single-exponential dependence on dimension for integer programming','optimization','resources',
    'Do constants C,c>0 and a deterministic algorithm exist that decide whether Ax≤b has an integer solution x∈ℤ^n in at most 2^(Cn)(L+1)^c bit operations, for every rational matrix A and vector b?',
    BIT+' A has m rows and n columns, both dimensions are part of the input, and the system need not be bounded. No limit on coefficient size, number of constraints or lattice width is promised. This target concerns feasibility.',
    'Integer programming is polynomial-time solvable in every fixed dimension, but the dependence on dimension determines how far that tractability extends. The single-exponential target would make the geometric dimension cost comparable to exhaustive search over a constant-size choice per variable.\n\nThe 2025 survey records the Reis–Rothvoss bound (log n)^{O(n)}·poly(L) and explicitly identifies 2^{O(n)}·poly(L) as open. Here n is the number of integer variables, not the coefficient bit length. The question applies to unrestricted systems rather than one block-structured subclass.',
    'Close the central dimension-dependence gap in a general-purpose optimization primitive used throughout parameterized algorithms.',94,
    'A Brief History of Parameterized Algorithms for Block-Structured Integer Programs','Martin Koutecký',2025,'Introduction, fixed number of variables and the explicit single-exponential open question.',
    'The survey reports (log n)^{O(n)}·poly(L) and distinguishes the unresolved single-exponential bound.',url='https://drops.dagstuhl.de/storage/00lipics/lipics-vol358-ipec2025/html/LIPIcs.IPEC.2025.1/LIPIcs.IPEC.2025.1.html')

add('15B','Deterministic polynomial-time construction of a prime of a given bit length','lattices','construction',
    'Is there a deterministic algorithm and constants C,c>0 which, on input 1^n for every n≥2, output a prime p with 2^(n−1)≤p<2^n in at most Cn^c bit operations?',
    BIT+' The unary input parameter requests an n-bit output. A prime is an integer greater than one with no positive divisors other than one and itself. Correctness and the bound must hold for every n≥2; neither randomization, an oracle, a prime table supplied as advice, nor an unproved number-theoretic hypothesis is allowed.',
    'Primality testing and finding a prime are different algorithmic tasks. A quickly checkable certificate for a candidate does not by itself identify a candidate in a prescribed bit-length interval.\n\nRandom sampling efficiently finds primes, while deterministic generation is a classical explicit-construction problem tied to derandomization and time-bounded information. The source uses the sequence of primes produced by deterministic search to explain that connection. Pseudodeterministic randomized generation also leaves this all-input deterministic target unresolved.',
    'A canonical explicit construction at the interface of number theory, randomness and algorithmic information.',91,
    'Theory and Applications of Probabilistic Kolmogorov Complexity','Zhenjian Lu; Igor C. Oliveira',2022,'Discussion of n-bit prime generation and deterministic search.',
    'The survey describes the deterministic prime-generation bottleneck and its role in probabilistic time-bounded Kolmogorov complexity.')

add('22A','Separate nonuniform TC⁰ from NC¹','complexity','models',
    'Is there a language in nonuniform NC¹ that is not in nonuniform TC⁰?',
    'A language is a set of finite binary strings. A circuit family has one Boolean circuit for each input length n and need not be computably generated. NC¹ consists of languages computed by circuits with at most n^{O(1)} gates and depth O(log(n+2)), using fan-in-two AND and OR gates and unary NOT gates. TC⁰ allows unbounded-fan-in AND, OR and majority gates and NOT gates, with polynomial size and a depth bound independent of n. A majority gate outputs one when at least half its input bits are one. Input wires count toward the polynomial description size. Constants may depend on the language; there are no oracle gates. The known inclusion TC⁰⊆NC¹ makes the question a strictness problem.',
    'Threshold circuits can aggregate many inputs in one layer, but a fixed number of layers may still be weaker than logarithmic-depth computation. This is one of the basic unresolved boundaries between standard Boolean circuit models.\n\nThe cited work quantifies how stronger bounds for threshold circuits would imply separations. Its conclusions are conditional implications, not a proof that NC¹ exceeds TC⁰. The existing NEXP-versus-TC⁰ card uses a much larger source class and asks a different separation.',
    'Locate a central boundary in the expressive power of shallow threshold computation.',96,
    'Bootstrapping Results for Threshold Circuits “Just Beyond” Known Lower Bounds','Lijie Chen; Roei Tell',2018,'Introduction and the NC¹ versus TC⁰ consequences.',
    'The paper relates quantitative circuit-analysis improvements to threshold-circuit lower bounds.',related=('TCS-7161',))

add('23A','Constant-factor approximation for uniform Sparsest Cut','approximation','tightness',
    'Do a universal C≥1 and a randomized polynomial-time algorithm exist which, on every finite simple undirected graph G on n≥2 vertices, output a nonempty proper set S with φ_G(S)≤C min_{∅≠T⊊V} φ_G(T), with probability at least 2/3?',
    'Here φ_G(S)=|E(S,V∖S)|/(|S|·|V∖S|), where E(S,V∖S) is the set of edges having exactly one endpoint in S. The graph is supplied explicitly by an adjacency matrix. Polynomial time is measured in bit operations on every random tape; the same algorithm and constant must work for all graphs. The zero-optimum disconnected case requires returning a zero cut. Uniform refers to equal demand for each pair of vertices, not regularity of the graph.',
    'Uniform Sparsest Cut balances a cut’s edge boundary against the number of separated pairs. It is a basic measure of the decomposability of a graph and a major test case for approximation algorithms.\n\nThe ARV result gives an O(√log n) approximation, with a bound growing with the graph size. A constant factor would cross the remaining qualitative approximation barrier. Nonuniform pair demands, conductance normalized by volumes, and Small-Set Expansion have different targets and are not silently substituted here.',
    'Determine whether a central graph-decomposition objective admits approximation independent of instance size.',94,
    'Lecture Notes on the ARV Algorithm for Sparsest Cut','Thomas Rothvoss',2016,'Definition of Uniform Sparsest Cut and the ARV approximation theorem.',
    'The notes present the O(√log n) approximation guarantee of Arora, Rao and Vazirani.')

add('24B','Do binary codes beat the Gilbert–Varshamov rate asymptotically?','coding','tightness',
    'Do constants δ∈(0,1/2) and η>0 and binary codes C_n⊆{0,1}^n for arbitrarily large n exist with minimum Hamming distance at least δn and log₂|C_n|/n≥1−H₂(δ)+η?',
    'A code is any nonempty subset of the binary strings of length n; linearity, explicit construction and efficient decoding are not required. Hamming distance is the number of unequal coordinates, and minimum distance is the minimum over distinct codewords. H₂(t)=−t log₂t−(1−t)log₂(1−t). The constants δ and η must be chosen before n and remain fixed along an unbounded sequence of block lengths. Finite-length improvements vanishing in normalized rate do not meet the target.',
    'The Gilbert–Varshamov bound describes a rate-distance tradeoff achievable by random binary codes. Whether an asymptotically better tradeoff exists is a fundamental question about the information lost to adversarial errors.\n\nThis is a nonconstructive existence question, independent of whether codes meeting the bound can be efficiently written down. A polynomial improvement in the number of codewords at fixed length need not yield a positive constant improvement in rate. The coding-course materials distinguish these two open challenges.',
    'Determine whether the basic random-coding benchmark is an intrinsic binary information limit.',96,
    'Essential Coding Theory (draft of 26 August 2025)','Venkatesan Guruswami; Atri Rudra; Madhu Sudan',2025,'Rate-distance tradeoff and discussion of attaining or beating the binary Gilbert–Varshamov bound.',
    'The materials distinguish the existential binary rate-distance gap from explicit construction and list decoding.',url='https://cse.buffalo.edu/faculty/atri/courses/coding-theory/book/web-coding-book.pdf')

add('25B','The inverse-polynomial-soundness sliding-scale PCP conjecture','complexity','construction',
    'Do constants a,b,c>0 and q≥1 exist such that 3-SAT has a verifier using at most a log₂(N+2) random bits and q queries to a proof of at most (N+2)^b symbols over an alphabet of size at most (N+2)^b, with perfect completeness and soundness at most (N+2)^(−c)?',
    'N is the bit length of an explicitly encoded 3-CNF formula. A uniform deterministic polynomial-time verifier receives the input, a uniform random bit string and oracle access to a fixed proof string. It reads at most q alphabet symbols, each encoded with O(log N) bits, and accepts or rejects. Queries may be adaptive. On a satisfiable formula some proof is always accepted; on an unsatisfiable formula every proof has acceptance probability at most (N+2)^(−c). Polynomial bounds and all constants are universal. No cryptographic soundness assumption or interaction is allowed.',
    'The PCP theorem achieves constant error with a constant number of queries. Driving soundness down to an inverse polynomial while retaining a constant number of queries would give substantially stronger verification and constraint-satisfaction gaps.\n\nDinur, Harsha and Kindler obtain inverse-polynomial error with polyloglogarithmically many queries. Their paper explicitly names the constant-query polynomial-alphabet endpoint as the sliding-scale conjecture in this regime. This is different from asking that a constant-error PCP have linear proof length.',
    'A central quantitative PCP barrier controlling the strength of gap amplification and inapproximability.',94,
    'Polynomially Low Error PCPs with polyloglog n Queries via Modular Composition','Irit Dinur; Prahladh Harsha; Guy Kindler',2015,'Abstract and introduction, inverse-polynomial-soundness sliding-scale conjecture.',
    'The source achieves inverse-polynomial soundness with O(polyloglog N) queries rather than a constant number.',related=('TCS-6738',))

add('28B','Exponential multilinear-formula lower bounds for the permanent','algebra','resources',
    'Does there exist c>0 such that, for every sufficiently large n, every multilinear arithmetic formula over ℂ computing perm_n has at least 2^(cn) gates?',
    'The permanent is perm_n(X)=Σ_{π∈S_n}∏_{i=1}^n x_{i,π(i)}. An arithmetic formula is a finite rooted tree with variable or complex-constant leaves and binary addition or multiplication gates, evaluated as a commutative polynomial. Every gate must compute a multilinear polynomial: every variable has degree at most one in every monomial after cancellation. The formula must agree identically with perm_n on ℂ^(n²), not merely on Boolean inputs. Size counts all gates, including leaves. No restriction on the numerical complexity of complex constants is imposed.',
    'Multilinear formulas give a restricted but important setting in which superpolynomial lower bounds are known for an explicit central polynomial. The exponential target asks how far that separation can be taken even after substantial algebraic structure is imposed.\n\nRaz’s lower bound grows as n^{Ω(log n)}, which is superpolynomial but not exponential in n. The broader permanent circuit problem permits sharing subcomputations and intermediate nonmultilinear polynomials, so these are not interchangeable targets. The survey records the unresolved exponential strengthening.',
    'Establish a qualitatively stronger explicit algebraic lower bound in one of the few models already admitting superpolynomial separations.',86,
    'P=?NP','Scott Aaronson',2017,'Survey discussion of Raz’s multilinear-formula lower bounds and the exponential gap.',
    'The survey discusses n^{Ω(log n)} multilinear-formula lower bounds for determinant and permanent.',related=('TCS-0005',))

add('29B','Beat exhaustive search for satisfiability of linear-size Boolean circuits','fine','resources',
    'For every fixed integer c≥1, do ε_c>0 and a deterministic algorithm exist deciding satisfiability of every Boolean circuit with n inputs and at most cn gates in time O((2−ε_c)^n·n^{O(1)})?',
    BIT+' Circuits are finite acyclic directed graphs with input bits and one output, binary AND and OR gates and unary NOT gates; gates have unrestricted fan-out. Size counts non-input gates. The input lists every gate and predecessor index. Satisfiability means that some assignment to the n input bits makes the output one. The algorithm and the constants in its polynomial factor may depend on c, but ε_c must be positive and independent of n. There is no depth restriction.',
    'Exhaustive assignment search works in roughly 2^n time regardless of circuit structure. Linear-size circuits restrict the amount of computation performed on each assignment while retaining arbitrary depth and sharing.\n\nObtaining a fixed exponential saving for every fixed size density would establish a general algorithmic benefit of that restriction. The question is part of the algorithms-to-lower-bounds landscape described by Wigderson. Algorithms for bounded-depth or threshold-restricted circuits do not settle the stated general model.',
    'A broad satisfiability-speedup question connecting fine-grained algorithms with unrestricted circuit lower bounds.',88,
    'Mathematics and Computation','Avi Wigderson',2019,'Sections on circuit satisfiability, nontrivial algorithms and circuit lower bounds.',
    'The book describes the connection between circuit-SAT speedups and circuit lower bounds.')

add('31A','Two-source extraction at log n plus constant entropy','randomness','construction',
    'Do a constant C and a deterministic algorithm running in poly(n) time exist that compute E_n:{0,1}^n×{0,1}^n→{0,1} with |Pr[E_n(X,Y)=1]−1/2|≤0.01 for every pair of independent sources X,Y of min-entropy at least log₂n+C?',
    'The algorithm receives n and the two n-bit strings, and defines one function for every n≥1. A source is any probability distribution on {0,1}^n; its min-entropy is −log₂(max_x Pr[X=x]). Independence means the joint law is the product of the two marginal distributions. For n where the entropy threshold exceeds n there are no eligible sources. No auxiliary uniform seed, advice or distribution description is supplied. The constants and time polynomial are universal.',
    'Two independent weak sources can contain much randomness while neither source by itself yields even one predictably unbiased bit. The target reaches the entropy threshold permitted by a random truth table with a polynomial-time evaluable function.\n\nXin Li’s construction achieves entropy O(log n), with an unspecified multiplicative constant. The requested log₂n+C threshold is stronger than that asymptotic-order statement. This distinction also matters when converting extraction into explicit Ramsey graphs.',
    'Reach the information-theoretic entropy threshold for a foundational seedless randomness primitive.',92,
    'Two Source Extractors for Asymptotically Optimal Entropy, and (Many) More','Xin Li',2023,'Main results and comparison with the existential entropy threshold.',
    'Li obtains explicit two-source extractors for O(log n) min-entropy; the coefficient-one plus additive-constant target is not asserted.',url='https://arxiv.org/abs/2303.06802')

add('32B','Does noninteractive statistical zero knowledge equal SZK?','crypto','models',
    'Does NISZK equal SZK for classical promise problems with an honestly generated common uniformly random reference string in the noninteractive model?',
    'SZK denotes statistical zero-knowledge interactive proofs; NISZK denotes their one-message analogue with public random setup. In both cases the verifier and simulator run in probabilistic polynomial time and the honest prover may be computationally unbounded. The comparison concerns promise problems, constant completeness-soundness gap and statistical simulation, not merely computational indistinguishability.',
    'Zero knowledge restricts what a verifier learns while checking a mathematical claim. This question asks whether public randomness can replace the interaction needed for statistical zero knowledge.\n\nThe classic study of noninteractive statistical zero knowledge relates the two classes but does not establish equality. The setup is essential: removing interaction in the plain model gives a different question. Perfect versus statistical simulation is also a separate axis, already represented in the atlas.',
    'Determine the intrinsic role of interaction in information-theoretic zero-knowledge proofs.',90,
    'On the Power of Non-Interactive Statistical Zero Knowledge','Oded Goldreich; Amit Sahai; Salil Vadhan',1999,'Definitions of NISZK and SZK and their relationship.',
    'The source studies complete problems and structural relations for NISZK without establishing equality with SZK.',related=('TCS-7225',),
    issue='Recover and reproduce the precise setup joint-distribution simulator definition, auxiliary-input convention and error amplification conventions from the source before certifying a self-contained class-equality statement.')

add('33B','A complete disjoint NP pair','proof','reductions',
    'Do disjoint languages A,B∈NP exist such that, for every disjoint pair C,D∈NP, there is a deterministic polynomial-time function f with f(C)⊆A and f(D)⊆B?',
    'All four languages consist of finite binary strings. NP means membership has a polynomial-length certificate checked by a deterministic polynomial-time verifier. Disjoint means A∩B=∅ and C∩D=∅. The total function f:{0,1}*→{0,1}* may depend on (C,D); its running-time polynomial need not be universal across pairs. No requirement is imposed on f(x) when x∉C∪D. Completeness uses one function for both sides, not two unrelated reductions.',
    'A disjoint NP pair expresses two efficiently certifiable cases that cannot occur together. Complete pairs would provide a universal object for this kind of promise complexity.\n\nCanonical disjoint pairs arise from propositional proof systems, tying the question to proof simulation and finite incompleteness. The existence of a p-optimal proof system would imply a complete pair, but the converse is not asserted. This card asks the pair-completeness question itself.',
    'Test the existence of universal promise problems in a class closely connected with proof-system strength and feasible incompleteness.',90,
    'Incompleteness in the finite domain','Pavel Pudlák',2017,'Disjoint NP pairs and the conjecture that no complete pair exists.',
    'The paper organizes the complete-pair question and its connections to proof-complexity conjectures.',related=('TCS-7162',))

add('36A','Do arbitrary one-way functions imply one-way functions in NC⁰?','crypto','models',
    'Does the existence of a classical one-way function imply the existence of a classical one-way function computed by a polynomial-time uniform NC⁰ circuit family?',
    CRYPTO+' A one-way function is a deterministic polynomial-time map f:{0,1}*→{0,1}* of polynomially bounded, length-dependent output size, such that every allowed inverter on (1^n,f(U_n)) finds any n-bit preimage with negligible probability, for uniform U_n. A polynomial-time uniform NC⁰ family is generated from 1^n in poly(n) time, has polynomial size and a universal constant depth, and uses fan-in-two AND/OR and unary NOT gates. Inversion security quantifies over all polynomial-size adversaries, not just shallow ones.',
    'Local evaluation and global inversion difficulty are strikingly different requirements. An NC⁰ one-way function has each output bit depend on only a constant number of input bits, while inverting the full output must defeat every polynomial-size adversary.\n\nKnown locality transformations start from stronger assumptions such as one-way functions in NC¹. Those constructions establish plausible NC⁰ cryptography, but they do not derive it from an arbitrary sequentially computable one-way function. The implication therefore asks whether cryptographic hardness can always be made local.',
    'Identify whether extreme locality is inherent in minimal cryptographic hardness or requires a stronger assumption.',86,
    'Cryptography in NC⁰','Benny Applebaum; Yuval Ishai; Eyal Kushilevitz',2006,'Main reductions from NC¹ primitives and the distinction from arbitrary one-way functions.',
    'The source constructs local cryptographic primitives from assumptions available in NC¹.',url='https://doi.org/10.1137/S0097539705446950',related=('TCS-7167',),
    note='The original personal-list citation studied attacks on Goldreich’s candidate; the foundational locality-construction reference is used here instead.')

add('38A','Exponential lower bounds for unrestricted perfect secret sharing','crypto','resources',
    'Do constants c>0 and n₀ exist such that, for every n≥n₀, some monotone access structure Γ on [n] requires max_i log₂|S_i|/log₂|S|≥2^(cn) in every perfect secret-sharing scheme for a uniform secret in an arbitrary finite alphabet S with |S|≥2?',
    'Γ⊆2^[n] is upward closed, excludes ∅ and includes [n]. A scheme is a joint distribution of a uniformly distributed secret over a finite alphabet S and shares X_i in finite alphabets S_i. For every A∈Γ a deterministic function of (X_i)_{i∈A} equals S with probability one. For every A∉Γ the share vector (X_i)_{i∈A} is statistically independent of S. There is no linearity, efficiency or restriction on reconstruction functions. Share size counts the logarithm of its alphabet size, not its entropy or the total size of all shares. The structure may depend on n and need not be explicitly constructed.',
    'Perfect secret sharing implements an arbitrary policy specifying which coalitions may recover a secret. General constructions use exponentially long shares, while unconditional lower bounds for unrestricted schemes are much smaller.\n\nThe cited work proves an exponential alternative involving share length or the description of reconstruction. That does not prove an exponential share lower bound when reconstruction is unrestricted. The existing upper-bound card asks whether every access structure has smaller shares; this conjecture asks for genuinely difficult structures with a different quantitative target.',
    'Determine whether exponential information overhead is unavoidable for some access policies, without assumptions on linearity or computation.',93,
    'Towards an Exponential Lower Bound for Secret Sharing','Kasper Green Larsen; Mark Simkin',2019,'Conjecture 1 and the share-length versus reconstruction-complexity distinction.',
    'The paper establishes an alternative between exponential share length and exponential reconstruction description complexity.',related=('TCS-0465',),
    issue='Verify the source conjecture’s secret-length quantifier and its equivalence, if any, to a lower bound on normalized share size for all finite secret alphabets. A one-bit lower bound must not silently replace the original information-ratio target.')
